### PR TITLE
Fixed an issue in ambient multicluster where informer errors for remote clusters would persist until an istiod restart

### LINKED ISSUE #58047: Missed Secret reconciliation
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

If you run through the workflow of creating a remote secret and then need to update that secret the control plane misses the change.

Scenario:
1. Run `istioctl create-remote-secret --name=foo |  kubectl apply -f`
2. Realize the server address is wrong for a KinD setup (`127.0.0.1`)
3. Update the secret via `istioctl create-remote-secret --name=foo --server https://<youraddr>:<port> |  kubectl apply -f -`
4. See that the control plane is still stuck trying to talk to the wrong endpoint like `2025-10-21T17:13:48.546106Z	error	watch error in cluster foo: failed to list *v1.Namespace: Get "https://127.0.0.1:51251/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 127.0.0.1:51251: connect: connection refused`

Currently a full restart of the control plane is required for the updated secret to be picked up correctly.

Tagging @keithmattix as requested.

### Version

```Text
istioctl version
client version: 1.27.1
control plane version: 1.27.1
data plane version: 1.27.1 (1 proxies)


kubectl version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by keithmattix**
**Please provide a description of this PR:**

Fixes #58047
We were waiting for discovery filters to successfully sync before adding a cluster ot the cluster store, so changes/fixes to a bad remote secret would be interpreted as an add not an update. In these cases, the bad cluster object/set of informers would never be shut down. This PR changes the ordering and deals with the implications of potentially bad clusters being added to the cluster store. Note that sidecar multicluster doesn't have this problem because the informers aren't a part of the cluster object.

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go [hunk 1]
```diff
@@ -202,16 +202,21 @@ func (c *Cluster) Run(localMeshConfig meshwatcher.WatcherCollection, debugger *k
...
 	namespaces := kclient.New[*corev1.Namespace](c.Client)
-	// This will start a namespace informer and wait for it to be ready. So we must start it in a go routine to avoid blocking.
-	filter := filter.NewDiscoveryNamespacesFilter(namespaces, localMeshConfig, c.stop)
+	// When this cluster stops, clean up the namespace watcher
+	go func() {
+		<-c.stop
+		namespaces.ShutdownHandlers()
+	}()
+	// This will start a namespace informer but DON'T wait for it to be ready because that will block
+	filter, syncWaiter := filter.NewDiscoveryNamespacesFilterNoWait(namespaces, localMeshConfig, c.stop)
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go]: nit: Calling the old one as NewBlockingDiscoveryNamespaceFilter or NewWaitingDisoveryNamespaceFilter may be better?

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go [hunk 2]
```diff
@@ -271,6 +276,8 @@ func (c *Cluster) Run(localMeshConfig meshwatcher.WatcherCollection, debugger *k
 	}
 
 	go func() {
+		log.Debugf("Waiting for discovery filter sync for cluster %s before starting all the other informers", c.ID)
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go:281]: Do we also have to change WaitUntilSynced func to account for this discoverySelectorSyncWaiter?

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/clusterstore.go [hunk 3]
```diff
@@ -143,3 +144,25 @@ func (c *ClusterStore) HasSynced() bool {
...
 }
+
+func (c *ClusterStore) TriggerRecomputeOnSync(id cluster.ID) {
+	cluster := c.GetByID(id)
+	if cluster == nil {
+		log.Debugf("cluster %s not found in store to trigger recompute", id)
+		return
+	}
+	c.Lock()
+	c.clustersAwaitingSync.Insert(id)
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/clusterstore.go]: When will we remove from this set?

File: pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets.go [hunk 4]
```diff
@@ -115,6 +115,8 @@ func (a *index) addSecret(name types.NamespacedName, s *corev1.Secret, debugger
 			}
 			// stop previous remote cluster
 			prev.Stop()
+			prev.Client.Shutdown()
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets.go]: Shall we move this to Stop so that we do not forget to call it every time stop is called?

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go (hunk 1 above)
Comment (keithmattix) [reply pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go]: I didn't want to change the old one just to prevent changing all of the callers. I can improve this name to `NewNonBlockingDiscoveryNamespacesFilter` though

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go (hunk 2 above)
Comment (keithmattix) [reply pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/cluster.go:281]: I don't think so because WaitUntilSynced checks the informers themselves, and those informers won't be synced (or even run) until the manual sync is complete

File: pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets.go (hunk 4 above)
Comment (keithmattix) [reply pilot/pkg/serviceregistry/kube/controller/ambient/remotesecrets.go]: Good idea

File: pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/clusterstore.go (hunk 3 above)
Comment (keithmattix) [reply pilot/pkg/serviceregistry/kube/controller/ambient/multicluster/clusterstore.go]: Great catch; completely missed that part of the logic

**Comment by keithmattix** [comment]
Looks like there's a race somewhere: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/58602/unit-tests-arm64_istio/2008404358760239104
