### PR TITLE
fix(docs): Add documentation to Mixer ENV var registrations

### LINKED ISSUE #12769: Document all environment variables used by Mixer & friends.
Find all uses of RegisterXXXVar in the Mixer code base and provide a suitable description for each environment variable.

This documentation will be published to istio.io

### PR DESCRIPTION
**Pull request by douglas-reid**
Fixes #12769

### CODE REVIEW

**Comment by douglas-reid** [comment]
@geeknoid does this need to go into 1.2 for collateral generation as well?

File: mixer/tools/mixgen/cmd/adapter.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ spec:
 		}
 	}
 
-	goPath := env.RegisterStringVar("GOPATH", "", "").Get()
+	goPath := env.RegisterStringVar("GOPATH", "", "Specifies directories outside of $GOROOT that contain the source for Go projects and their binaries".).Get()
```
Comment (golangcibot) [inline mixer/tools/mixgen/cmd/adapter.go]: expected selector or type assertion, found ')' (from `typecheck`)
