### PR TITLE
spire: add support for file certificates

### LINKED ISSUE #47481: File path based Gateway TLS setting is not working when using SPIRE as workload identity issuer.
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

*Hypothesis*

When SPIRE is configured to provide workload identity it replaces the default sds-cluster. However for ingress gateway, the source of the TLS certs is also moved to sds-cluster. The default SDS client, when SPIRE workload api socket is not mount, understand the specific resource name `file-cert:<key>~<cert>`. However, once it is replaced by SPIRE, the above resource name is passed onto the `spire-agent`, which is not able to resolve it.

This breaks the file based TLS SIMPLE mode configuration when SPIRE is the workload identity issuer.

*Context*
I set up my mesh to use SPIRE issuing workload identity. Traffic between proxies, including ingress gateway, are mTLS based on SPIRE issued identity. Workload socket are mounted from spire-agent through CSI.

*Error case*
I'm trying to set up SIMPLE mode TLS at the ingress gateway. Following is the Gateway resource:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: mesh-config
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 8080
        protocol: HTTP
    - hosts:
        - "romeo.example.net"
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /run/secrets/gateway-tls/tls.key
        serverCertificate: /run/secrets/gateway-tls/tls.cert
```

Running this configuration, I fail to curl over TLS. (I replaced the host name in logs below to avoid expose internal details)

_The gateway open up at 8443, but my NLB maps 443 to 8443._

```
❯ curl -k https://romeo.example.net/httpbin/hostname
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to romeo.example.net:443
```

```
❯ openssl s_client -connect romeo.example.net:443
CONNECTED(00000006)
00D329DB01000000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:304:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 345 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

```
❯ istioctl proxy-config secret istio-ingressgateway-6bd97dcb68-22rc5.istio-system
RESOURCE NAME                                                                    TYPE           STATUS      VALID CERT     SERIAL NUMBER                                NOT AFTER                NOT BEFORE
file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key                    WARMING     false
...

```

In ingress gateway log stream, I saw
```
2023-10-20T02:30:35.254103Z     warning envoy config external/envoy/source/common/config/grpc_stream.h:153      StreamSecrets gRPC config stream to sds-grpc closed: 3, workload is not authorized for the requested identities ["file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key"]      thread=18
```

It seems to me that the proxy attempted to fetch identity from spire-agent for unknown reason.

I dump the config on ingress gateway, the TLS config doesn't seem to be right

```
            "tls_certificate_sds_secret_configs": [
             {
              "name": "file-cert:/run/secrets/gateway-tls/tls.cert~/run/secrets/gateway-tls/tls.key",
              "sds_config": {
               "api_config_source": {
                "api_type": "GRPC",
                "grpc_services": [
                 {
                  "envoy_grpc": {
                   "cluster_name": "sds-grpc"
                  }
                 }
                ],
                "set_node_on_first_message_only": true,
                "transport_api_version": "V3"
               },
               "resource_api_version": "V3"
              }
             }
            ]
```

*Alternative*

Using the same cert and key, I place them in Kubernetes secret, the TLS works correctly.
```
      tls:
        mode: SIMPLE
        credentialName: romeo
```

That indicate the keys and cert are correct.

*Restriction*

I don't wish to use Kubernetes secret to store the key and cert as it is not safe. My design is to use a sidecar mount in memory medium with the gateway and rotate the cert and key in memory.

### Version

```Text
❯ istioctl version
client version: 1.19.0
control plane version: 1.18.2
data plane version: 1.18.2 (6 proxies)
```

### Additional Information

_No response_

### LINKED ISSUE #54365: Istio - SPIRE : File path based Gateway TLS setting is not working when using SPIRE as workload identity issuer
**Issue Description**

When SPIRE is configured to provide workload identity it replaces the default sds-cluster. However for ingress gateway, the source of the TLS certs is also moved to sds-cluster. The default SDS client, when SPIRE workload api socket is not mount, understand the specific resource name file-cert:<key>~<cert>. However, once it is replaced by SPIRE, the above resource name is passed onto the spire-agent, which is not able to resolve it.

This breaks the file based TLS SIMPLE mode configuration when SPIRE is the workload identity issuer.

Gateway TLS
```
 tls:
        mode: SIMPLE
        privateKey: /etc/ingress-certs/tls.key
        serverCertificate: /etc/ingress-certs/tls.crt
```

Envoy Config Dump - Downstream TLS context
```
"tls_certificate_sds_secret_configs": [
             {
              "name": "file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key",
              "sds_config": {
               "api_config_source": {
                "api_type": "GRPC",
                "grpc_services": [
                 {
                  "envoy_grpc": {
                   "cluster_name": "sds-grpc"
                  }
                 }
                ],
                "set_node_on_first_message_only": true,
                "transport_api_version": "V3"
               },
               "resource_api_version": "V3"
              }
             }
            ]
```

Error in ingress gateway logs, istio tries to make use of spire agent socket to fetch the file-cert based certificate

```
warning envoy config external/envoy/source/common/config/grpc_stream.h:153      StreamSecrets gRPC config stream to sds-grpc closed: 3, workload is not authorized for the requested identities ["file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key"]      thread=18
```

Using EnvoyFilter to patch the downstream TLS context to use a simple filename based TLS context doesn't remove the `tls_certificate_sds_secret_configs`, instead adds `tls_certificates {}` along with it
Giving an error **SDS and non-SDS TLS certificates may not be mixed in server contexts**

```
...
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: GATEWAY
        listener:
          name: "0.0.0.0_8443"
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificate_sds_secret_configs: []
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/ingress-certs/tls.crt
                    private_key:
                      filename: /etc/ingress-certs/tls.key
```

```
"transport_socket": {
                    "name": "envoy.transport_sockets.tls",
                    "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
                        "common_tls_context": {
                            "tls_certificates": [
                                {
                                    "certificate_chain": {
                                        "filename": "/etc/ingress-certs/tls.crt"
                                    },
                                    "private_key": {
                                        "filename": "[redacted]"
                                    }
                                }
                            ],
                            "alpn_protocols": [
                                "h2",
                                "http/1.1"
                            ],
                            "tls_certificate_sds_secret_configs": [
                                {
                                    "name": "file-cert:/etc/ingress-certs/tls.crt~/etc/ingress-certs/tls.key",
                                    "sds_config": {
                                        "api_config_source": {
                                            "api_type": "GRPC",
                                            "grpc_services": [
                                                {
                                                    "envoy_grpc": {
                                                        "cluster_name": "sds-grpc"
                                                    }
                                                }
                                            ],
                                            "set_node_on_first_message_only": true,
                                            "transport_api_version": "V3"
                                        },
                                        "resource_api_version": "V3"
                                    }
                                }
                            ]
                        },
                        "require_client_certificate": false
                    }
                }
            }
        ],
        "listener_filters": [
            {
                "name": "envoy.filters.listener.tls_inspector",
                "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
                }
            }
        ],
        "socket_options": [
            {
                "level": "1",
                "name": "9",
                "int_value": "1",
                "state": "STATE_BOUND"
            },
            {
                "level": "6",
                "name": "4",
                "int_value": "180",
                "state": "STATE_BOUND"
            },
            {
                "level": "6",
                "name": "5",
                "int_value": "180",
                "state": "STATE_BOUND"
            }
        ],
        "listener_filters_timeout": "0s",
        "traffic_direction": "OUTBOUND"
    },
    "last_update_attempt": "2024-12-16T06:44:09.425Z",
    "details": "SDS and non-SDS TLS certificates may not be mixed in server contexts"
}
```

Based on the comment in the issue

https://github.com/istio/istio/issues/47481#issuecomment-2136281410

I even tried the below

1. Istio ingress gateway should have the spire agent socket mounted on var/run/secrets/credential-uds/socket so that outbound traffic from gateway uses spire issued svid -- ( using credential-uds )
2. The file based certificates for inbound tls termination at gateway will use the regular istio's well known socket var/run/secrets/workload-spiffe-uds/socket -- ( using istio-sds )

**I tried this out and this completely removes SPIRE out of mesh and serves gateway SVID signed by Istio CA**

Is there a known workaround to overcome this. This stands a blocker in using gateway certificates or site specific certificates that are provider by a different issuer with downstream TLS context when spire is integrated and uses the well known `var/run/secrets/workload-spiffe-uds/socket `socket for serving workload identities.

### PR DESCRIPTION
**Pull request by howardjohn**
Istio has 3 types of 'secrets' it reads:
1. Workload mTLS certs
2. Files - we serve these over SDS from the istio-agent to support
   rotation
3. credentialName -- pulled from Istio

Typically, 1/2 are served by Istio agent and (3) is served from Istiod.

With SPIRE (or others, but usually SPIRE), we want to move (1) over to SPIRE. However, because this is
typically tied to (2) we in-advertantly move the files over to SPIRE as
well. SPIRE won't handle these, so we are broken

Note this happens even when not explicitly referencing files; the
following config just hard-fails with SPIRE:

```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: echo
spec:
  host: echo
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: echo
  workloadSelector:
    matchLabels:
      app: shell
```

The fix is to have 3 distinct SDS servers, matching the 3 kinds we have.
This PR does that.

~Note: this PR is a WIP due to using some hacky semantics to get the third one.
We need to make a socket somewhere, but we need to come up with a place to put it. I don't
really want to add yet another directory but just re-using a random one seems wonky.
Additionally, this hardcodeds Istiod. We will need to send some XDS metadata to conditionally point
to the alternative file location, and make the bootstrap generation conditional as well.~

Fixes https://github.com/istio/istio/issues/47481

### CODE REVIEW

**Comment by bleggett** [comment]
Also fixes https://github.com/istio/istio/issues/54365 I think?

File: pkg/istio-agent/agent.go [hunk 1]
```diff
@@ -371,24 +371,25 @@ func (a *Agent) Run(ctx context.Context) (func(), error) {
...
+
 	socketExists, err := checkSocket(ctx, configuredAgentSocketPath)
 	if err != nil {
 		return nil, fmt.Errorf("failed to check SDS socket: %v", err)
 	}
 	if socketExists {
-		log.Infof("Existing workload SDS socket found at %s. Default Istio SDS Server won't be started", configuredAgentSocketPath)
-	} else {
+		log.Infof("Existing workload SDS socket found at %s. Default Istio SDS Server will only serve files", configuredAgentSocketPath)
+		disableCaClient = true
```
Comment (bleggett) [inline pkg/istio-agent/agent.go:382]: (WIP so ignore if already intend to change) probably can just set `a.secOpts.ServeOnlyFiles` directly here.

**Review by bleggett — APPROVED** [review]
Directionally LGTM, thanks!

File: pkg/security/security.go [hunk 2]
```diff
@@ -500,6 +502,11 @@ func GetIstioSDSServerSocketPath() string {
 	return filepath.Join(WorkloadIdentityPath, DefaultWorkloadIdentitySocketFile)
 }
 
+func GetIstioSDSFileServerSocketPath() string {
+	// TODO: wrong path!!!
+	return filepath.Join(WorkloadIdentityCredentialsPath, "files-socket")
```
Comment (bleggett) [inline pkg/security/security.go:507]: I vote to reuse `CredentialNameSocketPath` and put 2x sockets in the same dir there.

Comment (howardjohn) [reply pkg/security/security.go:507]: Good call

**Review by craigbox — APPROVED** [review]

**Review by dhawton — APPROVED** [review]

File: samples/security/spire/README.md
Comment (bleggett) [inline samples/security/spire/README.md:1]: We need to delete this `spire-quickstart.yaml` - it hardcodes wildly outdated SPIRE images and outdated configs. No one should use or do this anymore.

We should just point people at [our docs](https://istio.io/latest/docs/ops/integrations/spire/) that installs SPIRE from its own upstream Helm charts and delete all of this.

Comment (bleggett) [reply samples/security/spire/README.md:1]: Or rather, it would be better to delete everything but `spire-sleep.yaml` and `spire-curl.yaml` - both of which are also redundant, but unlike the others directly referenced in docs (for now, they also should not be): https://github.com/istio/istio.io/issues/15754

Comment (howardjohn) [reply samples/security/spire/README.md:1]: Re sleep/curl -- if someone is using SPIRE, wouldn't they want it on every pod? You can do the `templates` thing at the global level so everything gets it, and make the template include the `spiffe.io/spire-managed-identity` label.

Comment (howardjohn) [reply samples/security/spire/README.md:1]: Agree with you, though

Comment (bleggett) [reply samples/security/spire/README.md:1]: > Re sleep/curl -- if someone is using SPIRE, wouldn't they want it on every pod? You can do the `templates` thing at the global level so everything gets it, and make the template include the `spiffe.io/spire-managed-identity` label.

Yeah - also in the docs we are just doing `kubectl -f spire-sleep.yaml` which is less obvious (asking you to install a weird yaml) - we should just install vanilla `sleep` and `kubectl label`, so it's obvious what we're doing differently.

**Review by bleggett — APPROVED** [review]
This LGTM codewise, approved but added a hold since

- Needs a release note.
- Still think we should delete the redundant/outdated `samples/security/spire` stuff but authors choice on whether to defer that.

**Comment by howardjohn** [comment]
> Still think we should delete the redundant/outdated samples/security/spire stuff but authors choice on whether to defer that.

Ill back out the changes here and split it out

File: pkg/istio-agent/agent.go [hunk 3]
```diff
@@ -376,19 +377,18 @@ func (a *Agent) Run(ctx context.Context) (func(), error) {
 		return nil, fmt.Errorf("failed to check SDS socket: %v", err)
 	}
 	if socketExists {
-		log.Infof("Existing workload SDS socket found at %s. Default Istio SDS Server won't be started", configuredAgentSocketPath)
-	} else {
+		log.Infof("Existing workload SDS socket found at %s. Default Istio SDS Server will only serve files", configuredAgentSocketPath)
```
Comment (jaellio) [inline pkg/istio-agent/agent.go:380]: Update the [above comments](https://github.com/istio/istio/pull/54725/files#diff-31c475bbc33537cd99e6c4e87b7e33dd04dd1a14b3135bcc04d864df3338b374L350-L362) to reflect the changes made in this PR.

File: security/pkg/nodeagent/sds/server.go [hunk 4]
```diff
@@ -91,13 +95,17 @@ func (s *Server) initWorkloadSdsService() {
...
 					sdsServiceLog.Errorf("SDS grpc server for workload proxies failed to set up UDS: %v", err)
 					setUpUdsOK = false
 				}
 			}
 			if s.grpcWorkloadListener != nil {
-				sdsServiceLog.Infof("Starting SDS server for workload certificates, will listen on %q", security.GetIstioSDSServerSocketPath())
+				if opts.ServeOnlyFiles {
+					sdsServiceLog.Infof("Starting SDS server for workload certificates, will listen on %q", path)
+				} else {
+					sdsServiceLog.Infof("Starting SDS server for file certificates only, will listen on %q", path)
```
[the remark this answers is not in the document]
Comment (howardjohn) [reply security/pkg/nodeagent/sds/server.go:107]: :+1: nice catch

**Review by jaellio — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]
