### PR TITLE
install: fix PDB overrides

### LINKED ISSUE #54087: PDB maxUnavailable field cannot be set in Istio operator (1.24.x regression)
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When installing Istio 1.24.x via istioctl, setting `components.pilot.k8s.podDisruptionBudget.maxUnavailable` gives the error below and installation fails:

```plain
❯ istioctl install -y --set components.pilot.k8s.podDisruptionBudget.maxUnavailable=1
...
✔ Istio core installed ⛵️                                                                                               
✘ Istiod encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: PodDisruptionBudget.policy "istiod" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0x401ad5f9a0), Selector:(*v1.LabelSelector)(0x401ad5f9c0), MaxUnavailable:(*intstr.IntOrString)(0x401ad5f9e0), UnhealthyPodEvictionPolicy:(*policy.UnhealthyPodEvictionPolicyType)(nil)}: minAvailable and maxUnavailable cannot be both set
```

### Version

```Text
❯ istioctl version       
Istio is not present in the cluster: no running Istio pods in namespace "istio-system"
client version: 1.24.1

❯ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.2+k3s1
```

### Additional Information

An identical bug was previously reported as #31910 and fixed under #32358. This works correctly with Istio 1.23.3 and 1.22.6 so it seems to be a regression specifically in 1.24.0 and 1.24.1.

### PR DESCRIPTION
**Pull request by howardjohn**
install: fix PDB overrides

Fixes istio#54087

### CODE REVIEW

**Review by zirain — APPROVED** [review]

File: operator/cmd/mesh/manifest-generate_test.go [hunk 1]
```diff
@@ -518,7 +518,7 @@ func TestManifestGeneratePilot(t *testing.T) {
 		},
 		{
 			desc:       "pilot_override_kubernetes",
-			diffSelect: "Deployment:*:istiod, Service:*:istiod,MutatingWebhookConfiguration:*:istio-sidecar-injector,ServiceAccount:*:istio-reader-service-account",
+			diffSelect: "Deployment:*:istiod, Service:*:istiod,PodDisruptionBudget:*:istiod,MutatingWebhookConfiguration:*:istio-sidecar-injector,ServiceAccount:*:istio-reader-service-account",
```
Comment (zirain) [inline operator/cmd/mesh/manifest-generate_test.go:521]: //nolint: lll
