### PR TITLE
Prevent empty revision on install

### LINKED ISSUE #26940: Fail istioctl install on explicitly empty revision
**Bug description**
istioctl install fails to distinguish between unset revision and empty string revision.  In both cases, an in-place upgrade is applied.  This can cause problems when the user has a typo in their bash session such as: 

```
export REVISION=1.6.4
istioctl install --revision $REVISION_NAME
```

In this case, the user expects a revision-based upgrade which poses no risk to the existing mesh, but because of their typo they get a destructive in-place upgrade.  When the revision flag is supplied, but an invalid value is associated with it (such as empty string, not sure if other scenarios exist), the command should fail, not fall back to in-place upgrade.  Users should have 100% certainty which sort of upgrade they are performing.

[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Multi Control Plane upgrade fails.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6+

### PR DESCRIPTION
**Pull request by therealmitchconnors**
commands like `istioctl install --revision $REVISION` should not result in in-place upgrades when `$REVISION` isn't set.
Fixes #26940

### CODE REVIEW

**Comment by brian-avery** [comment]
@therealmitchconnors should this show up in release notes? It looks like a change in istioctl to will return an error when REVISION isn't set. Other than that, LGTM

File: tests/integration/pilot/istioctl_test.go [hunk 1]
```diff
@@ -362,6 +362,17 @@ func jsonUnmarshallOrFail(t *testing.T, context, s string) interface{} {
 	}
 	return val
 }
+func TestInstallEmptyRevision(t *testing.T) {
```
Comment (howardjohn) [inline tests/integration/pilot/istioctl_test.go:365]: This should really be a unit test.

File: pkg/test/framework/features/features.yaml [hunk 2]
```diff
@@ -83,6 +83,7 @@ features:
       uninstall_revision:
       uninstall_manifest:
       uninstall_purge:
+      install-revision:
```
Comment (howardjohn) [inline pkg/test/framework/features/features.yaml:86]: this doesn't actually test installing a revision.. it tests you can not install a revision

File: operator/cmd/mesh/install.go [hunk 3]
```diff
@@ -110,6 +110,9 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
 }
 
 func runApplyCmd(cmd *cobra.Command, rootArgs *rootArgs, iArgs *installArgs, logOpts *log.Options) error {
+	if iArgs.revision == "" && cmd.PersistentFlags().Changed("revision") {
+		return fmt.Errorf("empty revision specified")
+	}
```
Comment (zerobfd) [inline operator/cmd/mesh/install.go:115]: Since we're validating revision here, I think it's a good opportunity to go ahead and validate all of it instead of just empty. Specifically it's a k8s label, so it needs to adhere to the [Syntax and character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). We also state that it can't contain the "." character although I'm having trouble finding official documentation on what the exact syntax is, and 10 minutes examining the call path didn't lead me to anywhere that we actually check this.

So maybe something like

```
if cmd.PersistentFlags().Changed("revision") {
  err := validateRevision(iArgs.revision); if err != nil {
    return err
  }
  return nil
}

func validateRevision(rev string) error{
  if empty: error (is empty)
  if len > 63: error (too long)
  matched, err := regexp.Match(`[[:alnum:]]{1}[a-z0-9A-Z_-]*[[:alnum:]]{1}`, rev)
  if err handle
  if not matched: error (must start/end with alphanum separated by - or _)
}
```

Also as a nit, I'd prefer this to go in PreRunE on the `ic` Command above instead of runApplyCmd. IIRC this is the standard place for flag validation, and in any case doesn't seem to be part of running the apply cmd.

File: go.sum [hunk 4]
```diff
@@ -749,8 +748,8 @@ github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8/go.mod h1:HUYIGzjTL3rfEspMx
 github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2/go.mod h1:UETIi67q53MR2AWcXfiuqkDkRtnGDLqkBTpCHuJHxtU=
 github.com/xlab/handysort v0.0.0-20150421192137-fb3537ed64a1/go.mod h1:QcJo0QPSfTONNIgpN5RA8prR7fF8nkF6cTWTcNerRO8=
 github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77/go.mod h1:aYKd//L2LvnjZzWKhF00oedf4jCCReLcmhLdhm1A27Q=
-github.com/yl2chen/cidranger v1.0.0 h1:9tdo0orHQJvXsX6mf+1Goou/R4kq21AfpbYeTcpXs2Q=
```
[the remark this answers is not in the document]
Comment (therealmitchconnors) [reply go.sum:752]: Yes, the 1.0.0 version of cidrblocks was poisoned, which causes build errors.

File: tests/integration/pilot/istioctl_test.go [hunk 5]
```diff
@@ -362,6 +362,17 @@ func jsonUnmarshallOrFail(t *testing.T, context, s string) interface{} {
...
+	framework.NewTest(t).Features("installation.istioctl.install-revision").
+		RequiresSingleCluster().
+		Run(func(ctx framework.TestContext) {
+
+			istioCtl := istioctl.NewOrFail(ctx, ctx, istioctl.Config{})
+			args := []string{"install", "--revision", ""}
+			_, _, err := istioCtl.Invoke(args)
+			gomega.Expect(err).To(gomega.HaveOccurred())
+	})
+}
```
Comment (therealmitchconnors) [inline tests/integration/pilot/istioctl_test.go:375]:
```suggestion
```

File: pkg/test/framework/features/features.yaml (hunk 2 above)
Comment (therealmitchconnors) [inline pkg/test/framework/features/features.yaml:86]:
```suggestion
```

File: operator/cmd/mesh/install.go [hunk 6]
```diff
@@ -100,6 +101,13 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
   istioctl install --set "values.sidecarInjectorWebhook.injectedAnnotations.container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy=runtime/default"
 `,
 		Args: cobra.ExactArgs(0),
+		PreRunE: func(cmd *cobra.Command, args []string) error {
+			errs := validation.IsQualifiedName(iArgs.revision)
+			if len(errs) != 0 && cmd.PersistentFlags().Changed("revision") {
+				return fmt.Errorf("invali revision specified: %v", errs)
```
Comment (zerobfd) [inline operator/cmd/mesh/install.go:107]: nit: I think passing a []string to a fmt.*f function just inlines the entire slice, so this might result in one 500 character wide line.

You might want to do something like

```
return fmt.Errorf("invalid revision specified:\n%v", strings.Join(errs, "\n"))
```

but it's up to you.

**Review by zerobfd — APPROVED** [review]
lgtm, thanks!

File: operator/cmd/mesh/install.go (hunk 6 above)
Comment (therealmitchconnors) [inline operator/cmd/mesh/install.go:107]:
```suggestion
				return fmt.Errorf("invalid revision specified:\n%v", strings.Join(errs, "\n"))
```

**Comment by linsun** [comment]
> @therealmitchconnors should this show up in release notes? It looks like a change in istioctl to will return an error when REVISION isn't set. Other than that, LGTM

When revision isn't set, istioctl install will continue work and set to default revision.  Is this correct?

**Comment by therealmitchconnors** [comment]
> When revision isn't set, istioctl install will continue work and set to default revision. Is this correct?

Yes, this PR differentiates between UNSET and EMPTY revision.  If the flag isn't specified, install proceeds as normal.  If the flag is specified, but the value is empty, as in the example (with intentional typo) below.

```
MY_REVISION=1.5.5
istioctl install --revision $MY-REVISION
ERROR
```

File: operator/cmd/mesh/install.go [hunk 7]
```diff
@@ -100,6 +102,13 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
   istioctl install --set "values.sidecarInjectorWebhook.injectedAnnotations.container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy=runtime/default"
 `,
 		Args: cobra.ExactArgs(0),
+		PreRunE: func(cmd *cobra.Command, args []string) error {
+			errs := validation.IsQualifiedName(iArgs.revision)
```
Comment (howardjohn) [inline operator/cmd/mesh/install.go:106]: I don't think `IsQualifiedName` is right here, you cannot set revision to `foo/bar`

**Review by howardjohn — APPROVED** [review]
