### PR TITLE
pilot: fix double SE deletion

### LINKED ISSUE #51212: applying then deleting a ServiceEntry with the same host results in missing endpoint
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Apply se1. Apply se2, then delete se1. Only difference between the two is the exportTo field. The endpoint for `httpbin-vd.internal.com` will be removed and the service will become unreachable.

Restarting istiod or reapplying se1 will restore the endpoint.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se1
  namespace: httpbin
spec:
  addresses:
  - 250.59.249.145
  exportTo:
  - default
  - httpbin
  - istio-system
  hosts:
  - httpbin-vd.internal.com
  location: MESH_INTERNAL
  ports:
  - name: http-8000
    number: 8000
    protocol: HTTP
    targetPort: 8080
  resolution: STATIC
  subjectAltNames:
  - spiffe://mgmt-cluster/ns/httpbin/sa/httpbin
  workloadSelector:
    labels:
      app: httpbin
```

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se2
  namespace: httpbin
spec:
  addresses:
  - 250.59.249.145
  exportTo:
  - istio-system
  - httpbin
  hosts:
  - httpbin-vd.internal.com
  location: MESH_INTERNAL
  ports:
  - name: http-8000
    number: 8000
    protocol: HTTP
    targetPort: 8080
  resolution: STATIC
  subjectAltNames:
  - spiffe://mgmt-cluster/ns/httpbin/sa/httpbin
  workloadSelector:
    labels:
      app: httpbin
```

### Version

```Text
reproduced on 1.19.10, 1.20.6, 1.22.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes #51212

In draft since I will probably go and add more comments, etc

Root cause is we key on `hostname+namespace` and delete instances. But we actually need to take into account which SE its from, otherwise if 2 SE share the same hostname, removal of one removes all instances

### CODE REVIEW

File: pilot/pkg/serviceregistry/serviceentry/store.go [hunk 1]
```diff
@@ -30,7 +31,7 @@ type hostPort struct {
 type serviceInstancesStore struct {
 	ip2instance map[string][]*model.ServiceInstance
 	// service instances by hostname -> config
-	instances map[instancesKey]map[configKey][]*model.ServiceInstance
+	instances map[instancesKey]map[configKeyWithParent][]*model.ServiceInstance
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/serviceentry/store.go:34]: can we use map[instancesKey]map[parentKey]map[configKey][]*model.ServiceInstance

**Review by hzxuzhonghu — COMMENTED** [review]
Do you abalyzed whether service select pods has same problem?

**Comment by howardjohn** [comment]
> Do you abalyzed whether service select pods has same problem?

Seems to be fine

File: pilot/pkg/serviceregistry/serviceentry/store.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/serviceentry/store.go:33]: This is just a hierachy choice.  One maybe clear, one maybe simple to manage. I donot feel strongly.

**Review by hzxuzhonghu — APPROVED** [review]
