### PR TITLE
pilot: fix nil pointer dereference in meshwatcher adapter

### LINKED ISSUE #59153: istiod 1.29.0 panic: nil pointer dereference in meshwatcher.adapter.Mesh() during multi-cluster startup
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

istiod 1.29.0 crashes with a nil pointer dereference when processing endpoint slices from a remote cluster. The crash is caused by the new per-remote-cluster mesh config watcher introduced in #58455.

Based on our investigation, the probable root causes are (though the exact cause may differ):
1. **RBAC mismatch during rolling upgrades**: The remote cluster (on 1.28) likely lacks `configmaps` in its reader ClusterRole (added by #58455), so the KRT Singleton for mesh config may remain permanently empty.
2. **Missing nil guard + sync barrier**: Even with correct RBAC, `Controller.informersSynced()` does not appear to wait for the mesh ConfigMap Singleton, so the endpoint queue may start before mesh config is loaded. `adapter.Mesh()` has no nil check.

### Version

- **Affected**: 1.29.0
- **Working**: 1.28.3

### Setup

- Multi-cluster with `multiCluster.enabled: true`
- Upgrade one cluster to 1.29.0 while remote cluster remains on 1.28.3

### Stack Trace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2584589]

goroutine 1047 [running]:
istio.io/istio/pkg/config/mesh/meshwatcher.adapter.Mesh(...)
	istio.io/istio/pkg/config/mesh/meshwatcher/mesh.go:49
istio.io/istio/pkg/config/mesh.restrictedConfigAdapter.TrustDomain(...)
	istio.io/istio/pkg/config/mesh/watchers.go:80
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).NewEndpointBuilder(...)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go:55 +0xa6
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*endpointSliceController).updateEndpointCacheForSlice(...)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointslice.go:303 +0x4f7
...
istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).AddRegistryAndRun(...)
	istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:263 +0x1e9
```

### Debug Logs

```json
{"level":"debug","msg":"waiting for sync...","name":"ConfigMap_istio-stable","attempt":7,"time":"127ms"}
{"level":"info","scope":"kube","msg":"kube controller for remote-cluster synced after 126ms"}
{"level":"debug","msg":"started queue remote-cluster"}
{"level":"info","scope":"model","msg":"Incremental push, service some-svc.some-ns.svc.cluster.local at shard Kubernetes/remote-cluster has no endpoints"}
{"level":"debug","msg":"closed queue remote-cluster"}
panic: runtime error: invalid memory address or nil pointer dereference
```

`ConfigMap_istio-stable` is still waiting for sync when the endpoint queue starts.

### Probable Root Cause

The nil dereference chain is clear from the stack trace: `NewEndpointBuilder` → `TrustDomain()` → `restrictedConfigAdapter.Mesh()` → `adapter.Mesh()` → `Singleton.Get()` returns nil → SIGSEGV.

Our best assessment of why the Singleton is empty (though the exact cause may differ):
- **Rolling upgrade**: remote cluster on 1.28 may lack `configmaps` RBAC (added by #58455) → informer cannot read the ConfigMap
- **Race**: `informersSynced()` does not appear to include the mesh config Singleton → queue starts before ConfigMap syncs

### Introduced By

#58455 

### Workaround

Revert to 1.28.3 OR upgrade all the clusters together.

### Version

```Text
### Istio Version

- **Affected**: 1.29.0
- **Working**: 1.28.3

### Environment

- Kubernetes: GKE 1.31+ (Stable channel)
- Multi-cluster, multi-primary
- Helm chart: istiod 1.29.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

Fixes #59153

**Root cause:**

The `Mesh` function in the krt adapter incorrectly assumed that `Singleton.Get()` would always return a non-nil value. In practice, this assumption is not guaranteed. As shown below, the singleton responsible for reading the mesh `ConfigMap` can legitimately be nil, which leads to unexpected behavior when the code dereferences it without proper checks:

https://github.com/istio/istio/blob/60f61c20c122cff69e8e75dac2eb27523a3f6606/pkg/config/mesh/kubemesh/watcher.go#L38-L68

### CODE REVIEW

File: pkg/config/mesh/meshwatcher/mesh.go [hunk 1]
```diff
@@ -44,9 +44,11 @@ var _ mesh.Watcher = adapter{}
 
 // Mesh returns the current MeshConfig
 func (a adapter) Mesh() *meshconfig.MeshConfig {
-	// Just get the value; we know there is always one set due to the way the collection is setup.
```
Comment (keithmattix) [inline pkg/config/mesh/meshwatcher/mesh.go:47]: Can we add a comment explaining why the value might be nil?

Comment (jewertow) [reply pkg/config/mesh/meshwatcher/mesh.go:47]: Sure, done.

**Review by keithmattix — APPROVED** [review]
