### PR TITLE
Display warning if the installed Istio version is different

### LINKED ISSUE #18487: istioctl manifest apply command should issue warning if the installed Istio version is different
It's quite possible that a user would have multiple versions of istioctl floating around - we want to prevent them running (say) istioctl manifest apply using the wrong version of istioctl, since this may lead to wrong charts being used.

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/18487

This PR will detect different Istio version installed (istioctl, control plan version) and display warning.

When Istio is not installed.

```
$ ./out/linux_amd64/istioctl install
This will install the Istio 1.8.0 profile into the cluster. Proceed? (y/N)
```

When a revision is not passed
```
$ ./out/linux_amd64/istioctl install --set hub=gcr.io/istio-testing -d manifests/
! Istio control planes installed: 1.6.8, 1.7.2.
! Use --revision or --force to install Istio.
This will install the Istio 1.8.0 profile into the cluster. Proceed? (y/N)
```

When a revision is passed.
```
$ ./out/linux_amd64/istioctl install --revision=1-8-0 --set hub=gcr.io/istio-testing -d manifests/
! Istio is being upgraded from 1.7.2 -> 1.8.0.
! Before upgrading, you may wish to 'istioctl analyze' to check for IST0002 deprecation warnings.
This will install the Istio 1.8.0 profile into the cluster. Proceed? (y/N)
```

### CODE REVIEW

**Review by esnible — CHANGES_REQUESTED** [review]
We don't want to use `log.Warn()`.  Logging is really only for server components.  Istioctl must deal with it because we call into libraries that are used by both server and CLI.  Please only output using cmd.Print...

```
2020-06-01T13:11:36.842366Z     warn    istioctl version 1.7.0 and the control plane version 1.6.0 are different
```

**Comment by shamsher31** [comment]
Sure, thanks for taking quick look @esnible.

File: operator/cmd/mesh/manifest-apply.go [hunk 1]
```diff
@@ -133,9 +139,13 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
 
 func runApplyCmd(cmd *cobra.Command, rootArgs *rootArgs, maArgs *manifestApplyArgs, logOpts *log.Options) error {
 	l := clog.NewConsoleLogger(cmd.OutOrStdout(), cmd.ErrOrStderr(), installerScope)
+
+	obv := version.OperatorBinaryVersion.String()
+	detectIstioVersionDiff(obv, maArgs)
 	// Warn users if they use `manifest apply` without any config args.
 	if len(maArgs.inFilenames) == 0 && len(maArgs.set) == 0 && !rootArgs.dryRun && !maArgs.skipConfirmation {
-		if !confirm("This will install the default Istio profile into the cluster. Proceed? (y/N)", cmd.OutOrStdout()) {
+		prompt := fmt.Sprintf("This will install the default profile of Istio %s into the cluster. Proceed? (y/N)", obv)
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:147]: not from your PR, but this is clearly wrong "the default profile"? It is hardcoded. I would just remove that and say "This will install Istio 1.x into the cluster"

**Review by howardjohn — COMMENTED** [review]
This seems like a god idea to me. I would prefer to completely replace `istioctl upgrade` with just auto detection like this as well if possible. We should be declarative, apply == upgrade. Not suggesting to do it right here, but maybe a followup - that will need more consideration

Thanks!

File: operator/cmd/mesh/manifest-apply.go (hunk 1 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: Simple and easy to understand. Thanks for your suggestion.

File: operator/cmd/mesh/manifest-apply.go [hunk 2]
```diff
@@ -213,3 +225,32 @@ func ApplyManifests(setOverlay []string, inFilenames []string, force bool, dryRu
...
+	return nil
+}
+
+// GetVersionInfo returns control plan version
+func GetVersionInfo(kubeConfigPath string, context string, opts clioptions.ControlPlaneOptions) (*istioVersion.MeshInfo, error) {
+	kubeClient, err := kubernetes.NewExtendedClient(kubeConfigPath, context, opts)
+	if err != nil {
+		return nil, err
+	}
+	return kubeClient.GetIstioVersions(controller.IstioNamespace)
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:255]: This command is super slow on anything other than the smallest clusters. Like over 30s

File: operator/cmd/mesh/manifest-apply.go [hunk 3]
```diff
@@ -213,3 +225,32 @@ func ApplyManifests(setOverlay []string, inFilenames []string, force bool, dryRu
...
+func DetectIstioVersionDiff(cmd *cobra.Command, obv string, maArgs *manifestApplyArgs) error {
+	var opts clioptions.ControlPlaneOptions
+	icps, err := GetVersionInfo(maArgs.kubeConfigPath, maArgs.context, opts)
+	if err != nil {
+		return err
+	}
+	if len(*icps) != 0 {
+		var icpVer string
+		for _, icp := range *icps {
+			icpVer = icp.Info.Version
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:240]: This won't work in the case there are different versions

**Review by howardjohn — DISMISSED** [review]
If we can do this in an efficient way I think its useful, but I would rather the install be fast. We could just compare the in cluster IOP or image of `istiod` for example?

File: operator/cmd/mesh/manifest-apply.go (hunk 3 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:240]: Do we want to compare it with all the control plan version? 
OR
Only one different version will be enough to display warning?

File: operator/cmd/mesh/manifest-apply.go (hunk 2 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:255]: I see, but I'm not sure if there is another better alternative available. `GetIstioVersions` is currently used for.
1. istioctl [version cmd](https://github.com/istio/istio/blob/master/istioctl/cmd/version.go#L70)
2. istioctl [upgrade cmd](https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L273). 

> We must use the Control Plane Version reported by istioctl version in the message.

It's also recommended by @esnible in [the comment](https://github.com/istio/istio/issues/18487#issuecomment-593441401)

File: operator/cmd/mesh/manifest-apply.go (hunk 3 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:240]: Is it ok to use `[0].version` for comparison?

eg: [retrieveControlPlaneVersion](https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L340) and [waitUpgradeComplete](https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L345) uses it.

Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: This will consider if at least one different control plan version is installed and will display a warning.
@howardjohn PTAL ?

File: operator/cmd/mesh/manifest-apply.go (hunk 2 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: I believe there is a bit of performance improvement due to a recent update https://github.com/istio/istio/pull/24903 in getting the control plan version using `:15014/version` on pilot ?

**Comment by shamsher31** [comment]
@howardjohn @esnible PTAL ?

**Comment by shamsher31** [comment]
@howardjohn Looking at some old PR's this caught my eyes, can you PTAL ?

File: operator/cmd/mesh/manifest-apply.go [hunk 4]
```diff
@@ -206,3 +220,37 @@ func ApplyManifests(setOverlay []string, inFilenames []string, force bool, dryRu
...
+		if obv != icpVer {
+			cmd.Printf("! istioctl version %s and the control plane version %s are different.\n", obv, icpVer)
+		}
+	}
+	return nil
+}
+
+// GetVersionInfo returns control plan version
+func GetVersionInfo(kubeconfig string, configContext string, opts clioptions.ControlPlaneOptions) (*istioVersion.MeshInfo, error) {
+	kubeClient, err := kube.NewExtendedClient(kube.BuildClientCmd(kubeconfig, configContext), opts.Revision)
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:251]: Why are we creating a new client just for this? We should have 1 kube client at the top of the command and use it throughout

Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: Moved `kubeclient` to the top level. But I think `ApplyManifests`  need different set of params and requires more refactoring. I want to get this merged and I can do refactoring in separate PR?

File: releasenotes/notes/24263.yaml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+apiVersion: release-notes/v2
+kind: feature
+area: istioctl
+issue:
+  - https://github.com/istio/istio/issues/18487
```
Comment (brian-avery) [inline releasenotes/notes/24263.yaml:5]: Second time I've seen this pattern today, so adding some clarification. There are two different ways of referencing PRs. Number only implies the Istio repo. Having a URL directs to the actual PR. Both work.

File: releasenotes/notes/24263.yaml [hunk 6]
```diff
@@ -0,0 +1,9 @@
...
+  - 24263
+releaseNotes: |
+  *Added*
```
Comment (brian-avery) [inline releasenotes/notes/24263.yaml:8]:
```suggestion
  *Added* istioctl install will detect different Istio version installed (istioctl, control plan version) and display warning.
```

**Review by brian-avery — APPROVED** [review]

**Comment by brian-avery** [comment]
Minor comments regarding the release notes. Approving based on those contents.

File: releasenotes/notes/24263.yaml (hunk 5 above)
Comment (shamsher31) [reply releasenotes/notes/24263.yaml:5]: Thanks for the clarification @brian-avery .

I have added 2 things here. Let me know if this is right?
1. The actual issue reported https://github.com/istio/istio/issues/18487
2. PR to resolve that issue 24263

I think resolved PR should be enough to be included because it will have an issue link mentioned?

Comment (brian-avery) [reply releasenotes/notes/24263.yaml:5]: This should only reference issues resolved in this PR.

End result will be that it generates a line like: 

Improved the sidecar injection control based on revision at a per-pod level (Issue 24801)

Comment (shamsher31) [reply releasenotes/notes/24263.yaml:5]: Perfect. Thanks

**Review by esnible — APPROVED** [review]

**Comment by shamsher31** [comment]
@howardjohn PTAL?

**Review by howardjohn — COMMENTED** [review]
I think the implementation is ok now (was worried about perf previously) but I am worried about the correctness and error messages. I don't think there errors are very user friendly or give the user an indication of what to do. For example, if I deploy a different version I get a message saying "versions are different", then 10ms later its too late because we have already deployed it.

File: operator/cmd/mesh/manifest-apply.go [hunk 7]
```diff
@@ -134,9 +140,19 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
...
 func runApplyCmd(cmd *cobra.Command, rootArgs *rootArgs, maArgs *manifestApplyArgs, logOpts *log.Options) error {
 	l := clog.NewConsoleLogger(cmd.OutOrStdout(), cmd.ErrOrStderr(), installerScope)
+	var opts clioptions.ControlPlaneOptions
+	kubeClient, err := kube.NewExtendedClient(kube.BuildClientCmd(maArgs.kubeConfigPath, maArgs.context), opts.Revision)
+	if err != nil {
+		return err
+	}
+	obv := version.OperatorBinaryVersion.String()
+	if err := DetectIstioVersionDiff(cmd, obv, kubeClient); err != nil {
+		cmd.Println(err)
```
[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:150]: Do you suggest to ignore this error?

File: operator/cmd/mesh/manifest-apply.go [hunk 8]
```diff
@@ -134,9 +140,19 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
 
 func runApplyCmd(cmd *cobra.Command, rootArgs *rootArgs, maArgs *manifestApplyArgs, logOpts *log.Options) error {
 	l := clog.NewConsoleLogger(cmd.OutOrStdout(), cmd.ErrOrStderr(), installerScope)
+	var opts clioptions.ControlPlaneOptions
+	kubeClient, err := kube.NewExtendedClient(kube.BuildClientCmd(maArgs.kubeConfigPath, maArgs.context), opts.Revision)
+	if err != nil {
+		return err
+	}
+	obv := version.OperatorBinaryVersion.String()
+	if err := DetectIstioVersionDiff(cmd, obv, kubeClient); err != nil {
```
[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:149]: Looks like version striping does not return last part properly. I will verify this.

[the remark this answers is not in the document]
Comment (howardjohn) [reply operator/cmd/mesh/manifest-apply.go:149]: I think it may be more fundamental problem that OperatorBinaryVersion != istio version mentioned below?

File: operator/cmd/mesh/manifest-apply.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (howardjohn) [reply operator/cmd/mesh/manifest-apply.go:150]: Yes

[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: Done

File: operator/cmd/mesh/manifest-apply.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: `OperatorBinaryVersion` is useful in the following situation.

1. Users already have istio version `1.6.0` running in the cluster from the last 2 months where `OperatorBinaryVersion=1.6.0`
2. New version of istio `1.7.0` is released. The user wants to upgrade to the latest version where `OperatorBinaryVersion=1.7.0` 

In this scenario, different version detection will work properly as the comparison happens between `1.7.0 != 1.6.0` which is expected.

As `1.8.0` is not released, I think it only returns `1.8` from the control plan.

I have tested the comparison with `1.6.5` and it returns following.

```
$ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl install
! istioctl version 1.8.0 and the control plane version 1.6.5 are different.
This will install Istio 1.8.0 into the cluster. Proceed? (y/N)
```

File: operator/cmd/mesh/manifest-apply.go [hunk 9]
```diff
@@ -134,9 +140,19 @@ func InstallCmd(logOpts *log.Options) *cobra.Command {
 
 func runApplyCmd(cmd *cobra.Command, rootArgs *rootArgs, maArgs *manifestApplyArgs, logOpts *log.Options) error {
 	l := clog.NewConsoleLogger(cmd.OutOrStdout(), cmd.ErrOrStderr(), installerScope)
+	var opts clioptions.ControlPlaneOptions
+	kubeClient, err := kube.NewExtendedClient(kube.BuildClientCmd(maArgs.kubeConfigPath, maArgs.context), opts.Revision)
+	if err != nil {
+		return err
+	}
+	obv := version.OperatorBinaryVersion.String()
```
[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:148]: Right, see my comment https://github.com/istio/istio/pull/24263#discussion_r460984521

**Comment by shamsher31** [comment]
> I don't think there errors are very user friendly or give the user an indication of what to do. For example, if I deploy a different version I get a message saying "versions are different", then 10ms later its too late because we have already deployed it.

I agree we can improve the error message which can be more useful to take better decisions whether to install it or not.

File: operator/cmd/mesh/manifest-apply.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (howardjohn) [reply operator/cmd/mesh/manifest-apply.go]: OperatorBinaryVersion is NOT the same as Istio version though, as far as I know. I don't agree with the entire operator versioning at all, but that is the way it is. For example, at `1.6.5` tag, `OperatorCodeBaseVersion = "1.6.0"`

**Comment by brian-avery** [comment]
@shamsher31 I *think* this should have a release note.

**Comment by shamsher31** [comment]
Sure @brian-avery I will add a release note.

File: operator/cmd/mesh/manifest-apply.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: Got it, so with all the patch releases, `OperatorCodeBaseVersion` is not updated. I will revisit this and see if I can use tags.

[the remark this answers is not in the document]
Comment (howardjohn) [reply operator/cmd/mesh/manifest-apply.go]: Don't check tags vs version either. We can only compare identical things. Tag != Version != OperatorCodeBaseVersion, none of the 3 should be compared against any others. Many users build custom images with things like 1.6.5-foobar. We can compare tags to tags though

[the remark this answers is not in the document]
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: @howardjohn I have updated code to use the tag instead of version.

It uses [DockerBuildInfo.Tag](https://github.com/istio/pkg/blob/master/version/version.go#L59) for comparison and if the tag is `unknow` (in case of unreleased version 1.8) then it fallbacks to [OperatorVersionString](https://github.com/istio/istio/blob/master/operator/version/version.go#L30). Fallback is required otherwise it throws [this error](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/24263/integ-pilot-k8s-tests_istio/17166).

**Comment by shamsher31** [comment]
@howardjohn @esnible I have also updated the warning message. Let me know if this sounds ok ?

```
$ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl install
! istioctl version 1.8.0 and the control plane version 1.6.5 are different.
! Proceed with caution because after installation the cluster may misbehave.

This will install Istio 1.8.0 into the cluster. Proceed? (y/N)
```

**Comment by esnible** [comment]
@shamsher31 Can you get your final approver on this?

**Comment by shamsher31** [comment]
> @shamsher31 Can you get your final approver on this?

@esnible Yes, waiting for @howardjohn feedback.

File: operator/cmd/mesh/manifest-apply.go [hunk 10]
```diff
@@ -183,3 +202,41 @@ func InstallManifests(setOverlay []string, inFilenames []string, force bool, dry
...
+			if err != nil {
+				return err
+			}
+			if tag != tagVer {
+				icpTag = tagVer
+			}
+		}
+		if tag != icpTag {
+			cmd.Printf("! istioctl version %s and the control plane version %s are different.\n"+
+				"! Proceed with caution because after installation the cluster may misbehave.\n\n", tag, icpTag)
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:226]: nit: extra new line at end

> after installation the cluster may misbehave.

This warning doesn't seem great. How is a user supposed to upgrade then? It sounds like we are saying if you upgrade your cluster is going to break

**Review by howardjohn — DISMISSED** [review]
```
$ go run ./istioctl/cmd/istioctl install -d manifests -y
! istioctl version 1.8.0 and the control plane version 1359334.0.0-dirty-1359334ea3d6c4e105b7527a81a0eaeed2a0d00f are different.
! Proceed with caution because after installation the cluster may misbehave.

✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                  
$ go run ./istioctl/cmd/istioctl install -d manifests -y
! istioctl version 1.8.0 and the control plane version  are different.
! Proceed with caution because after installation the cluster may misbehave.
```

We still have no solved the issue that we are comparing two "versions" which are not derived from the same source

File: operator/cmd/mesh/manifest-apply.go (hunk 10 above)
Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go]: > nit: extra new line at end

Removed.

> This warning doesn't seem great. How is a user supposed to upgrade then? It sounds like we are saying if you upgrade your cluster is going to break

I'm not really good at writing. Please suggest better wording so after noticing different versions user should be able to take necessary actions to avoid any future problems.

**Comment by shamsher31** [comment]
> We still have no solved the issue that we are comparing two "versions" which are not derived from the same source

As far as I understood, I think we need to compare the `Istio Control Plan` installed in a running cluster with the latest `istioctl` installed on the user machine.

**Comment by sdake** [comment]
@shamsher31 our policy bot has a mind of its own. Would you care to continue work on this PR?

**Comment by sdake** [comment]
@howardjohn - there are many new pushes since your blocking review. I have not reviewed this PR - is there still a blocking problem?

Cheers,
-steve

**Comment by sdake** [comment]
@ericvn approximately 30 days seems a little aggressive for closure of a PR that has had a bunch of pushes without further followup review. Do you know how to improve the bot to add improved logic?

Cheers,
-steve

**Comment by sdake** [comment]
cc @istio/wg-test-and-release-maintainers

**Comment by ericvn** [comment]
@sdake I'd have to go back and find the design doc (I believe this was done by Martin as part of Code Mauve), but I believe 30 days to make stale and 15 days to close was the approved values.

**Review by esnible — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by shamsher31** [comment]
@howardjohn I spent a lot of time rebasing this (almost 400 commits since this PR) and finally decided to delete and re-create the local branch with handpicked changes.

File: operator/cmd/mesh/install.go [hunk 11]
```diff
@@ -190,3 +209,41 @@ func savedIOPName(iop *v1alpha12.IstioOperator) string {
...
+		return err
+	}
+	if len(*icps) != 0 {
+		var icpTag string
+		for _, icp := range *icps {
+			tagVer, err := GetTagVersion(icp.Info.GitTag)
+			if err != nil {
+				return err
+			}
+			if tagVer != "" && tag != tagVer {
```
Comment (richardwxn) [inline operator/cmd/mesh/install.go:227]: how to handle multiple control plane versions? seems like we are warning only one here?

**Review by esnible — COMMENTED** [review]
Is this error message too strong?
```
! istioctl version 1.7.0 and the control plane version 1.6.4 are different.
! Proceed with caution because after installation the cluster may misbehave.
```

What kind of caution should the user use? 
- When downgrading this message is extremely important and we should keep it.
- When upgrading this message looks too strong.  Perhaps something like "Istio is being upgraded from X -> Y.  Before upgrading, you may wish to 'istioctl analyze' to check for IST0002 deprecation warnings"
- When there are multiple control planes, and does not supply `--set revision=`, the message might better read "Istio control planes installed: X,Y.  Use `--set revision=` or `--force` to install Istio.

**Comment by shamsher31** [comment]
@esnible Hope this is what you suggested.

When there is a multiple control plane already installed.
```
$ kubectl get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-6994d999bb-72wxs   1/1     Running   0          16s
istiod-1-6-8-69cd9dd85d-jpnsf           1/1     Running   0          54s
istiod-1-7-2-545654f869-vsvxc           1/1     Running   0          20s
prometheus-7dd7f7c65-kxbjg              2/2     Running   0          48s
```

> When there are multiple control planes, and does not supply --set revision=, the message might better read "Istio control planes installed: X,Y. Use --set revision= or --force to install Istio.

When a revision is not passed
```
$ ./out/linux_amd64/istioctl install --set hub=gcr.io/istio-testing -d manifests/
! Istio control planes installed: 1.6.8, 1.7.2.
! Use --revision=1.8.0 or --force to install Istio.
This will install the Istio 1.8.0 profile into the cluster. Proceed? (y/N)
```

> When upgrading this message looks too strong. Perhaps something like "Istio is being upgraded from X -> Y. Before upgrading, you may wish to 'istioctl analyze' to check for IST0002 deprecation warnings"

When a revision is passed.
```
$ ./out/linux_amd64/istioctl install --revision=1-8-0 --set hub=gcr.io/istio-testing -d manifests/
! Istio is being upgraded from 1.7.2 -> 1.8.0.
! Before upgrading, you may wish to 'istioctl analyze' to check for IST0002 deprecation warnings.
This will install the Istio 1.8.0 profile into the cluster. Proceed? (y/N)
```

**Comment by shamsher31** [comment]
@esnible @howardjohn any idea why tests are failing?

File: operator/cmd/mesh/install.go (hunk 11 above)
Comment (shamsher31) [reply operator/cmd/mesh/install.go]: please see https://github.com/istio/istio/pull/24263#issuecomment-707629340

**Comment by shamsher31** [comment]
@ostromart I think I found why tests is failing. It is because of `--set values.global.tag=istio-testing-distroless` in the integration test.

```
Running istio control plane on cluster cluster-0 [install --skip-confirmation -f /home/prow/go/src/istio.io/istio/tests/integration/iop-integration-test-defaults.yaml -f /logs/artifacts/security-d34ed5d85ba94bcaa6717a/_suite_context/istio-deployment-455539552/iop.yaml
--set values.global.imagePullPolicy=IfNotPresent
--manifests /home/prow/go/src/istio.io/istio/manifests 
--set values.global.imagePullPolicy=IfNotPresent
--set values.global.hub=localhost:5000
--set values.global.tag=istio-testing-distroless]
```

If I pass `tag=istio-testing-distroless` it throws error.
```
$ ./out/linux_amd64/istioctl install --set hub=gcr.io/istio-testing --set tag=istio-testing-distroless -d manifests/
Error: Malformed version: istio-testing-distroless
```

**Comment by shamsher31** [comment]
@ostromart PTAL.

**Review by ostromart — APPROVED** [review]

**Review by esnible — APPROVED** [review]
