### PR TITLE
skip initializing webhook if no WebhookConfigFile provided

### LINKED ISSUE #8756: Galley should fast fail if Validation enabled but no WebhookConfigFile provided
**Describe the bug**
Currently, if EnableValidation is set to true, we'll try to init validation webhook anyway.
And if no WebhookConfigFile provided, we'll get a webhook keep running there, but does nothing in fact.

**Expected behavior**
Fast fail when Validation is enabled but no WebhookConfigFile provided,
or treat the scenario as Validation disabled.

/cc @ozevren @ayj 
/assign

### PR DESCRIPTION
**Pull request by lichuqiang**
Fix #8756 

/assign @ozevren @ayj

### CODE REVIEW

File: galley/cmd/galley/cmd/root.go [hunk 1]
```diff
@@ -82,6 +82,10 @@ func GetRootCmd(args []string, printf, fatalf shared.FormatFn) *cobra.Command {
 			if !serverArgs.EnableServer && !validationArgs.EnableValidation {
 				fatalf("Galley must be running under at least one mode: server or validation")
 			}
+			if validationArgs.EnableValidation && validationArgs.WebhookConfigFile == "" {
```
Comment (ozevren) [inline galley/cmd/galley/cmd/root.go]: This should be an error instead. We should have a .Validate() method on validationArgs and check for such inconsistencies.

Comment (lichuqiang) [reply galley/cmd/galley/cmd/root.go]: Hmm, I meant to, but on the other hand I'm afraid that would break backwards compatibility (as we didn't consider this an error before).

**Comment by ozevren** [comment]
There is no backward compat concern at this point. We should fix this
before the next release.

**Comment by lichuqiang** [comment]
> There is no backward compat concern at this point. We should fix this
before the next release.

Okay, I'll have an update

File: galley/cmd/galley/cmd/root.go [hunk 2]
```diff
@@ -82,6 +82,9 @@ func GetRootCmd(args []string, printf, fatalf shared.FormatFn) *cobra.Command {
 			if !serverArgs.EnableServer && !validationArgs.EnableValidation {
 				fatalf("Galley must be running under at least one mode: server or validation")
 			}
+			if err := validationArgs.Validate(); err != nil {
```
Comment (ozevren) [inline galley/cmd/galley/cmd/root.go]: Minor nit: please leave some spaces around logically separate blocks (i.e. setup, validation, execution).

File: galley/pkg/crd/validation/validation.go [hunk 3]
```diff
@@ -95,3 +106,52 @@ func DefaultArgs() *WebhookParameters {
...
 }
+
+// IsDNS1123Label tests for a string that conforms to the definition of a label in
+// DNS (RFC 1123).
+func IsDNS1123Label(value string) bool {
+	return len(value) <= dns1123LabelMaxLength && dns1123LabelRegexp.MatchString(value)
+}
+
+// ValidatePort checks that the network port is in range
+func ValidatePort(port int) error {
```
Comment (ozevren) [inline galley/pkg/crd/validation/validation.go]: Do these methods need to be exported?

File: galley/pkg/crd/validation/validation_test.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+			expectedError: "CA cert file not specified",
+		},
+		"invalid port": {
+			wrapFunc:      func(args *WebhookParameters) { args.Port = 100000 },
+			expectedError: "port number 100000 must be in the range 1..65535",
+		},
+	}
+
+	for name, scenario := range scenarios {
+		args := DefaultArgs()
```
Comment (ozevren) [inline galley/pkg/crd/validation/validation_test.go]: Please run these in a sub-test with ```t.RunTest(name, func(t *testing.T){...})```
