### PR TITLE
Fix local install, add integration tests

### LINKED ISSUE #22368: Use --set install_package_path to select external charts,  will get profile path error
**Bug description**

Follow version `1.5.0` document to select external charts with `--set installPackagePath={charts-path}`. But it doesn't work.

Should  replace `installPackagePath` with `install_package_path`.
```
istioctl manifest apply \
--set install_package_path=$PWD/install/kubernetes/operator/charts
```
But this will get an error:
```
Error: open {install_package_path}/profiles/default.yaml: no such file or directory
```
Must set `profile` to a local file system path at the same time.

Use it correctly like this:
```
istioctl manifest apply \
--set profile=$PWD/install/kubernetes/operator/profiles/default.yaml \
--set install_package_path=$PWD/install/kubernetes/operator/charts
```

**Expected behavior**

`istioctl manifest apply --set install_package_path=` should use the `default` profile.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (2 proxies)
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by ostromart**
Fixes https://github.com/istio/istio/issues/22368 and https://github.com/istio/istio/issues/21889.
A fix also needs to go into 1.5 also but in a more minimal form.

### CODE REVIEW

File: operator/cmd/mesh/manifest-generate_test.go [hunk 1]
```diff
@@ -256,6 +257,54 @@ func TestBareSpec(t *testing.T) {
...
+			// --force is needed for version mismatch.
+			desc:       "github_1.5",
+			diffSelect: "Deployment:*:istiod",
+			flags:      "--force",
+		},
+		{
+			// Same path, using --set.
+			desc:       "github_1.5",
+			diffSelect: "Deployment:*:istiod",
+			flags:      "--force --set installPackagePath=https://github.com/istio/istio/releases/download/1.5.0/istio-1.5.0-linux.tar.gz",
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-generate_test.go]: I don't really think we should have unit tests pulling from github. Or integration tests, if it can be avoided

Comment (ostromart) [reply operator/cmd/mesh/manifest-generate_test.go]: I also have an instinctive aversion to doing this but the downside is a fully hermetic test is quite contrived (i.e. it ends up testing that the internal server & package are correctly set up in the test). The downsides to pulling from an URL (flakiness, brittle tests) are not particularly severe in this case, is there any other downside I'm missing?

**Review by howardjohn — CHANGES_REQUESTED** [review]
This test takes 57s, which is not really ok for a unit test. I don't like the external call either, but external call + 1 minute I think isn't acceptable

File: operator/cmd/mesh/manifest-generate_test.go (hunk 1 above)
Comment (dgn) [reply operator/cmd/mesh/manifest-generate_test.go]: what is this actually testing though? Let's assume the flag is broken and ignored by istioctl. Won't there still be an istiod deployment?

Comment (ostromart) [reply operator/cmd/mesh/manifest-generate_test.go]: It's testing an installation path for the charts - both local filesystem and github. We can set installPackagePath=/tmp/istio-1.5.0 or https://github.com/istio/istio/releases/download/1.5.0/istio-1.5.0-linux.tar.gz.
My point about the github test is that to set up a server and create a fake release tar to serve from it leaves plenty of room to mess up the test and have the test be passing while the real thing is failing.  Anyway, I'm happy to go with the consensus on this one because I also feel uneasy about it on principle.

**Comment by ostromart** [comment]
Ok, @howardjohn you've convinced me!

File: operator/cmd/mesh/manifest-generate_test.go (hunk 1 above)
Comment (dgn) [reply operator/cmd/mesh/manifest-generate_test.go]: My question was more about the `diffSelect` - my point was that if we're testing against 1.5.0 charts we should at least test on something that is included in those charts, but not in `master` anymore, so we know it actually pulled them down

**Comment by howardjohn** [comment]
It will have a different image for 1.5, right?

**Review by howardjohn — APPROVED** [review]

**Comment by ostromart** [comment]
1.5.0 will also work for release-1.5 branch

File: operator/cmd/mesh/manifest-generate_test.go (hunk 1 above)
Comment (ostromart) [reply operator/cmd/mesh/manifest-generate_test.go]: Yes, if we pull externally I agree there would be value, but with the latest change we are just testing our fake test build so I'm not sure it's worth checking more than basic function.
