### PR TITLE
Fix invalid XDS configuration for wildcard Ingress HTTP path

### LINKED ISSUE #44882: Invalid XDS generated when specifying wildcard http path for an Ingress rule
### Bug Description

When applied, the following Ingress spec results in the subsequent Envoy proxy error due to an invalid xDS.

image

`value does not match regex pattern: "^[^?#]+[^?#/]$"`

The above Envoy regex is documented [here](https://github.com/envoyproxy/envoy/blob/23168f3cc7ea9693e12cfda065268c5e4957c570/api/envoy/config/route/v3/route_components.proto#L596). Istio converts the /* `path` with `pathType` `ImplementationSpecific` into an empty string `Prefix` match for the Istio VirtualService. https://github.com/istio/istio/blob/ccbfc41d616a1c440a9eb4cc143d10134f909bf2/pilot/pkg/config/kube/ingress/conversion.go#L337 Subsequently, the route match is translated. https://github.com/istio/istio/blob/ccbfc41d616a1c440a9eb4cc143d10134f909bf2/pilot/pkg/networking/core/v1alpha3/route/route.go#L886 An empty string prefix does not match the above regex.  If the /* `path` in an Ingress resource is equivalent to a wildcard path the corresponding VirtualService must be configured to match on all paths.

### Version

```Text
v1.17
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by jaellio**
**Please provide a description of this PR:**

Updates Ingress to VirtualService translation to not create an HTTPRequestMatch when the URI is nil. The URI is nil when the path is a wildcard or is empty and the pathType is nil or ImplementationSpecific. This change prevents an Envoy failure. Envoy regex fails when the path separated prefix is empty or has a trailing "/".

Resolves #44882

**Reproducing Error:**

Reproduced the error seen in #44882 by applying the following Ingress after installing Istio with the demo profile:

```yaml
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: httpbin.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpbin
            port:
              number: 8000
EOF
```

Following the [Kubernetes Ingress tutorial](https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/), the httpbin resources were deployed in the default ns. The following curl command failed:

```sh
curl -s -I -HHost:httpbin.example.com "http://$INGRESS_HOST:$INGRESS_PORT/status/200"
```

The ingress-gateway resource had the following error in the logs:

```txt
warning envoy config external/envoy/source/common/config/grpc_subscription_impl.cc:128  gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Match: embedded message failed validation | caused by RouteMatchValidationError.PathSeparatedPrefix: value does not match regex pattern "^[^?#]+[^?#/]$"): name: "http.8080"
```

**Validation:**

Validated the changes included in this PR result in a valid XDS configuration in the same setup.

```sh
$ curl -s -I -HHost:httpbin.example.com "http://$INGRESS_HOST:$INGRESS_PORT/headers"

HTTP/1.1 200 OK
server: istio-envoy
date: Mon, 15 May 2023 16:46:46 GMT
content-type: application/json
content-length: 599
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3

```

### CODE REVIEW

File: pilot/pkg/config/kube/ingress/conversion.go [hunk 1]
```diff
@@ -319,7 +329,8 @@ func shouldProcessIngressWithClass(mesh *meshconfig.MeshConfig, ingress *knetwor
 }
 
 func createFallbackStringMatch(s string) *networking.StringMatch {
-	if s == "" {
+	// If the string is empty or a wildcard, return nil
```
Comment (howardjohn) [inline pilot/pkg/config/kube/ingress/conversion.go:332]: I think in the current state `//*` was also broken. do you know if this resolve that as well?

File: pilot/pkg/config/kube/ingress/conversion.go [hunk 2]
```diff
@@ -203,8 +207,14 @@ func ConvertIngressVirtualService(ingress knetworking.Ingress, domainSuffix stri
 		// see https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches
 		vs := ingressByHost[host].Spec.(*networking.VirtualService)
 		sort.SliceStable(vs.Http, func(i, j int) bool {
-			r1Len, r1Ex := getMatchURILength(vs.Http[i].Match[0])
-			r2Len, r2Ex := getMatchURILength(vs.Http[j].Match[0])
+			var r1Len, r2Len int
+			var r1Ex, r2Ex bool
+			if vs.Http[i].Match != nil || len(vs.Http[i].Match) != 0 {
```
Comment (howardjohn) [inline pilot/pkg/config/kube/ingress/conversion.go:212]: nit: it might be simpler to just make the `nil` ones `Prefix: /` to make things simpler. I think it will end up the same in Envoy in the end, so just a matter of which is simpler in the code

**Review by howardjohn — COMMENTED** [review]
Looks good! Just one comment about the `//*` case

File: pilot/pkg/config/kube/ingress/conversion.go (hunk 1 above)
Comment (jaellio) [reply pilot/pkg/config/kube/ingress/conversion.go:332]: What was the error you were seeing when specifying //* as the path? Was it the same error? I think this path would have worked previously. The suffix /* would have been removed in `createFallbackStringMatch` and the remaining / would have been converted to a prefix match rather than a path-separated prefix match.

Comment (howardjohn) [reply pilot/pkg/config/kube/ingress/conversion.go:332]: oh sorry! it was "//.*"

File: pilot/pkg/config/kube/ingress/conversion.go (hunk 2 above)
Comment (jaellio) [reply pilot/pkg/config/kube/ingress/conversion.go:212]: Good point, that would work too! My only hesitation with that approach is that requires all URLs to have the trailing slash. In the case where there is no slash, I believe `Prefix: /` would fail. If /* means all paths including empty paths then I am not sure `Prefix: /` is sufficient. Is `Prefix: ` allowed?

Comment (howardjohn) [reply pilot/pkg/config/kube/ingress/conversion.go:212]: `prefix: /` is the end result in envoy config for all configs - even a plain HTTP service without a route. it will match all traffic. `http://example.com` is treated as `path=/` (not sure if that is an Envoy thing or some HTTP RFC, but that is how it ends up working in the end)

**Review by howardjohn — APPROVED** [review]
LGTM! Thanks! I just put a hold for the `//.*` discussion and the prefix=/. i don't mind merging as is though

File: pilot/pkg/config/kube/ingress/conversion.go (hunk 1 above)
Comment (jaellio) [reply pilot/pkg/config/kube/ingress/conversion.go:332]: //.* is not addressed by the change. It would be converted to / which would fail the path separated prefix regex. It might be simplest to add a check to specifically handle this in route.go (similar to the single forward slash check), but I don't love this option. I'll try to come up with an alternative, but I don't want it to get too complicated.

**Comment by jaellio** [comment]
> LGTM! Thanks! I just put a hold for the `//.*` discussion and the prefix=/. I don't mind merging as is though

I'm going to merge this as is and create a separate issue to track `//.*`.
