### PR TITLE
[Ambient] Authz Destination Port Handling

### LINKED ISSUE #41204: [ambient] authz port matching not respected
### Bug Description

Following the Get Started Ambient [guide](https://istio.io/latest/blog/2022/get-started-ambient/#secure-application-access), it looks like the port match is not respected. 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  generation: 2
  name: productpage-viewer
  namespace: default
  resourceVersion: "20035695"
  uid: 50c8e232-2b6b-4137-b93e-06350502383a
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/sleep
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    to:
    - operation:
        ports:
        - "9080"
  selector:
    matchLabels:
      app: productpage
```

# this is supposed to work
❯ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1
command terminated with exit code 52
# this should fail with an empty reply
❯ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/
command terminated with exit code 52

Logs from the ztunnel: 
```
istio-proxy [2022-09-27T18:28:59.313Z] "- - -" 0 - - rbac_access_denied_matched_policy[none] "-" 233 0 1 - "-" "-" "-" "-" "-" - - 10.64.135:15008 10.64.3.51:45702 - - capture inbound listener
```

### Version

```prose
istioctl version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (2 proxies)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dhawton**
**Please provide a description of this PR:**

Pre-calculate the RBAC rules based upon the port extracted from the listener name while respecting the other L7 (if present) rules.

Closes #41204 and #42208

### CODE REVIEW

File: pilot/pkg/networking/core/v1alpha3/listener_builder.go [hunk 1]
```diff
@@ -411,7 +414,14 @@ func (lb *ListenerBuilder) buildHTTPConnectionManager(httpOpts *httpListenerOpts
 		filters = extension.PopAppend(filters, wasm, extensions.PluginPhase_AUTHN)
 		filters = append(filters, lb.authnBuilder.BuildHTTP(httpOpts.class)...)
 		filters = extension.PopAppend(filters, wasm, extensions.PluginPhase_AUTHZ)
-		filters = append(filters, lb.authzBuilder.BuildHTTP(httpOpts.class)...)
+
+		var httpauthz []*hcm.HttpFilter
+		if lb.node.Type == model.Waypoint {
+			httpauthz = lb.authzBuilder.BuildHTTPWithListener(httpOpts.class, httpOpts.routeConfig.Name)
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/listener_builder.go:420]: `routeConfig.Name` as "Listener" param seems unexpected. Maybe correct, though

File: pilot/pkg/security/authz/builder/builder.go [hunk 2]
```diff
@@ -96,6 +99,16 @@ func New(trustDomainBundle trustdomain.Bundle, push *model.PushContext, policies
 	}
 }
 
+func (b Builder) BuildHTTPAmbient(listener string) []*hcm.HttpFilter {
+	b.AmbientListenerName = listener
```
Comment (howardjohn) [inline pilot/pkg/security/authz/builder/builder.go:103]: Isn't the builder used beyond a single call? Modifying the entire struct may be problematic?

File: pilot/pkg/security/authz/model/model.go [hunk 3]
```diff
@@ -160,6 +164,52 @@ func (m *Model) MigrateTrustDomain(tdBundle trustdomain.Bundle) {
...
 
+// Update rules for ambient based on listener name. Because the Waypoint Proxy receives
+// the destination as envoy://listener_name/, Envoy will not have a port to evaluate. This
+// will precalculate the RBAC rules with regard to destination port for any matches and replace
+// as necessary. For not matches, we add an `any: true` as it will always match. For value match,
+// we replace with a nil, which the generator replaces with an `any: true` if there are no other
+// rules to evaluate. We leave non-matching ports so they do not match any requests.
+func (m *Model) AmbientDestinationPortAdapations(listener_name string) {
+	// Extract port from listener name (e.g. inbound-pod|80||10.244.2.4)
+	listener := strings.Split(listener_name, "|")
```
Comment (howardjohn) [inline pilot/pkg/security/authz/model/model.go:175]: model.ParseSubsetKey can do this

File: pilot/pkg/security/authz/model/model.go [hunk 4]
```diff
@@ -160,6 +164,52 @@ func (m *Model) MigrateTrustDomain(tdBundle trustdomain.Bundle) {
 	}
 }
 
+// Update rules for ambient based on listener name. Because the Waypoint Proxy receives
+// the destination as envoy://listener_name/, Envoy will not have a port to evaluate. This
+// will precalculate the RBAC rules with regard to destination port for any matches and replace
+// as necessary. For not matches, we add an `any: true` as it will always match. For value match,
+// we replace with a nil, which the generator replaces with an `any: true` if there are no other
+// rules to evaluate. We leave non-matching ports so they do not match any requests.
+func (m *Model) AmbientDestinationPortAdapations(listener_name string) {
```
Comment (howardjohn) [inline pilot/pkg/security/authz/model/model.go:173]: This is pretty complex. We have golden file tests (in Yossi's PR, I think specifically for Ambient mode if you want to copy); may be useful to include these.

Comment (dhawton) [reply pilot/pkg/security/authz/model/model.go:173]: I am looking at those unit tests, I need to be able to pass a listener name.

File: pilot/pkg/security/authz/model/model.go (hunk 3 above)
Comment (dhawton) [reply pilot/pkg/security/authz/model/model.go:175]: Thanks, will look into

File: pilot/pkg/networking/core/v1alpha3/listener_builder.go (hunk 1 above)
Comment (dhawton) [reply pilot/pkg/networking/core/v1alpha3/listener_builder.go:420]: That was the param I found that had the listener name that also matched the dynamic_listeners[].name attribute from the config dump.

File: pilot/pkg/security/authz/builder/builder.go (hunk 2 above)
Comment (dhawton) [reply pilot/pkg/security/authz/builder/builder.go:103]: I haven't found it to be problematic.

File: pilot/pkg/security/authz/model/generator.go [hunk 5]
```diff
@@ -182,8 +182,17 @@ func (requestPresenterGenerator) principal(key, value string, forTCP bool, useAu
 
 type requestHeaderGenerator struct{}
 
-func (requestHeaderGenerator) permission(_, _ string, _ bool) (*rbacpb.Permission, error) {
-	return nil, fmt.Errorf("unimplemented")
+func (requestHeaderGenerator) permission(key, value string, forTCP bool) (*rbacpb.Permission, error) {
```
Comment (howardjohn) [inline pilot/pkg/security/authz/model/generator.go:185]: do we need this change now?

File: tests/integration/ambient/baseline_test.go [hunk 6]
```diff
@@ -632,6 +640,14 @@ spec:
     - operation:
         paths: ["/allowed-identity"]
         methods: ["GET"]
+  - from:
+    - source:
+        principals: ["cluster.local/ns/istio-system/sa/{{.Source}}"]
+    to:
+    - operation:
+        ports: ["80", "18080", "18081", "18085"]
```
Comment (howardjohn) [inline tests/integration/ambient/baseline_test.go:648]: should we add a notPorts as well

File: tests/integration/ambient/baseline_test.go [hunk 7]
```diff
@@ -692,6 +720,17 @@ spec:
 				overrideCheck(&opt)
 				src.CallOrFail(t, opt)
 			})
+			t.NewSubTest("port allow").Run(func(t framework.TestContext) {
+				opt = opt.DeepCopy()
+				opt.HTTP.Path = "/allowed-port"
+				opt.Check = check.OK()
+				// sidecar-uncaptured is failing this check
```
Comment (howardjohn) [inline tests/integration/ambient/baseline_test.go:727]: we already SKipped it above, do we need both?

File: pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-ambient-in.yaml [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+            ipBlocks: ["1.2.3.4", "5.6.0.0/16"]
+            remoteIpBlocks: ["1.2.3.4", "5.6.0.0/16"]
+            notPrincipals: ["not-principal", "not-principal-prefix-*", "*-not-suffix-principal", "*"]
+            notRequestPrincipals: ["not-requestPrincipals", "not-requestPrincipals-prefix-*", "*-not-suffix-requestPrincipals", "*"]
+            notNamespaces: ["not-ns", "not-ns-prefix-*", "*-not-ns-suffix", "*"]
+            notIpBlocks: ["9.0.0.1", "9.2.0.0/16"]
+            notRemoteIpBlocks: ["9.0.0.1", "9.2.0.0/16"]
+      to:
+        - operation:
+            methods: ["method", "method-prefix-*", "*-suffix-method", "*"]
```
Comment (howardjohn) [inline pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-ambient-in.yaml:26]: nit: can you jut put port matches (and maybe 1 other) to reduce noise

**Review by howardjohn — COMMENTED** [review]
mostly LGTM, just minor comment - thanks!

File: pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-ambient-in.yaml (hunk 8 above)
Comment (dhawton) [reply pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-ambient-in.yaml:26]: Yup. Wasn't sure if we should/need to verify all with the ambient flag enabled but I can reduce that to just the destination port rules

File: tests/integration/ambient/baseline_test.go (hunk 7 above)
Comment (dhawton) [reply tests/integration/ambient/baseline_test.go:727]: I can't run the tests locally.. I'm hoping my check above will properly skip the sidecar test and then I was going to clean that up

**Comment by dhawton** [comment]
Removed unit tests after discussion with Lin. See this comment: https://github.com/istio/istio/issues/42208#issuecomment-1411135468

**Review by howardjohn — APPROVED** [review]

File: pilot/pkg/security/authz/model/model.go [hunk 9]
```diff
@@ -160,6 +165,52 @@ func (m *Model) MigrateTrustDomain(tdBundle trustdomain.Bundle) {
 	}
 }
 
+// Update rules for ambient based on listener name. Because the Waypoint Proxy receives
+// the destination as envoy://listener_name/, Envoy will not have a port to evaluate. This
+// will precalculate the RBAC rules with regard to destination port for any matches and replace
+// as necessary. For not matches, we add an `any: true` as it will always match. For value match,
+// we replace with a nil, which the generator replaces with an `any: true` if there are no other
+// rules to evaluate. We leave non-matching ports so they do not match any requests.
+func (m *Model) AmbientDestinationPortAdapations(listenerName string) {
```
Comment (linsun) [inline pilot/pkg/security/authz/model/model.go:174]: A typo here? s/Adapations/Adaptaions ?

File: pilot/pkg/networking/plugin/authz/authorization.go [hunk 10]
```diff
@@ -58,6 +58,17 @@ func NewBuilderSkipIdentity(actionType ActionType, push *model.PushContext, prox
 	return &Builder{builder: b}
 }
 
+// NewBuilderWithOptions allows a builder with custom defined options
+func NewBuilderWithOptions(actionType ActionType, push *model.PushContext, proxy *model.Proxy, option builder.Option) *Builder {
+	tdBundle := trustdomain.NewBundle(push.Mesh.TrustDomain, push.Mesh.TrustDomainAliases)
+	policies := push.AuthzPolicies.ListAuthorizationPolicies(proxy.ConfigNamespace, proxy.Labels)
+	if !util.IsIstioVersionGE117(proxy.IstioVersion) {
```
Comment (linsun) [inline pilot/pkg/networking/plugin/authz/authorization.go:65]: Can you pls add a comment on why this check is needed? I assume it is prior to 1.17, it can't support HBONE properly?

Comment (dhawton) [reply pilot/pkg/networking/plugin/authz/authorization.go:65]: NewBuilderWithOptions is pretty much the same as NewBuilderSkipIdentity, where that conditional exists. The conditional comes from: https://github.com/istio/istio/pull/42666 -- seems to affect using io.istio.peer_principle vs RBAC principle.
