### PR TITLE
Another attempt for the cache fix

### LINKED ISSUE #5588: EDS race misses service instances
If two goroutines are updating an EDS cluster load assignment, we use locks to prevent them both from doing so at the same time.

https://github.com/istio/istio/blob/3bea9a15cbcef19f21b87eb5245c4aa340f76410/pilot/pkg/proxy/envoy/v2/eds.go#L189

But, we don't have any way to enforce the "newer" update is processed later, meaning we could end with stale load assignments on the cluster, and no indication that the cluster needs recomputation. The stale load assignments persist until something triggers a full recalculation.

### PR DESCRIPTION
**Pull request by costinm**
Fixes #5588 - the root problem was that events were squashed, but nothing triggered a push for the last events. So change #1 was pushed immediately, change #2 triggered a callback after (squash time).
Instead the callback is now after 1 second, and we evaluate if in the last second we received any event.
If not - push. Otherwise, keep waiting until the batch of changes settles down.

### CODE REVIEW

File: pilot/pkg/proxy/envoy/discovery.go [hunk 1]
```diff
@@ -112,10 +112,21 @@ var (
...
+
+	// lastClearCacheEvent is the time of the last config event
+	lastClearCacheEvent time.Time
+
+	// clearCacheTimerSet is true if we are in squash mode, and a timer is already set
 	clearCacheTimerSet bool
-	clearCacheMutex    sync.Mutex
-	clearCacheTime     = 1
+
+	clearCacheMutex sync.Mutex
```
Comment (ZackButcher) [inline pilot/pkg/proxy/envoy/discovery.go]: Put the mutex at the top of this `var` block since it protects all of the variables here (mirroring the pattern that a mutex struct field should come before the other struct fields it guards).

File: pilot/pkg/proxy/envoy/discovery.go [hunk 2]
```diff
@@ -432,23 +442,40 @@ func (ds *DiscoveryService) clearCache() {
...
-			clearCacheTimerSet = true
-			time.AfterFunc(time.Duration(clearCacheTime)*time.Second, func() {
-				clearCacheMutex.Lock()
-				clearCacheTimerSet = false
-				clearCacheMutex.Unlock()
-				ds.clearCache() // it's after time - so will clear the cache
-			})
-		}
+	// If last config change was > 1 second ago, push.
+	if time.Since(lastClearCacheEvent) > 1*time.Second {
```
Comment (ZackButcher) [inline pilot/pkg/proxy/envoy/discovery.go]: How/why did we pick 1 second as the flush interval? Second, please make this a variable called something like `maxCacheClearInterval` and store it above with the cache vars.

Comment (costinm) [reply pilot/pkg/proxy/envoy/discovery.go]: Good point - I'll do both on follow-up PRs (since the bot and CI are taking many hours to run, and we're trying to get this into the monthly ) - I don't think either change are critical (or worse than the bug )
