### PR TITLE
[release-1.29] Source and destination waypoint tags

### LINKED ISSUE #58874: [release-1.29] Set source tags in Waypoint spans
Manual cherrypick required.

#58872 failed to apply on top of branch "release-1.29":
```
Applying: set source waypoint span tags
Using index info to reconstruct a base tree...
M	pilot/pkg/networking/core/tracing.go
M	pilot/pkg/networking/core/tracing_test.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/networking/core/tracing_test.go
CONFLICT (content): Merge conflict in pilot/pkg/networking/core/tracing_test.go
Auto-merging pilot/pkg/networking/core/tracing.go
CONFLICT (content): Merge conflict in pilot/pkg/networking/core/tracing.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
hint: When you have resolved this problem, run "git am --continue".
hint: If you prefer to skip this patch, run "git am --skip" instead.
hint: To restore the original branch and stop patching, run "git am --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Patch failed at 0001 set source waypoint span tags

```

### PR DESCRIPTION
**Pull request by Stevenjin8**
**Please provide a description of this PR:**

Joint cherry pick of #58872, #58866, #58818.

resolves #58874, #58867, #58851

We need these because otherwise,
we would change the default telemetry tags emitted by waypoints in 1.30.

cc @PetrMc

### CODE REVIEW

**Comment by Stevenjin8** [comment]
I dont think this needs rebase

File: pilot/pkg/networking/core/tracing.go [hunk 1]
```diff
@@ -549,6 +549,54 @@ var optionalPolicyTags = []*tracing.CustomTag{
...
+// Uses Envoy FILTER_STATE FIELD accessor to extract all available fields from downstream_peer_obj.
+// The peer_metadata filter stores WorkloadMetadataObject under downstream_peer_obj key,
+// while CelState is stored under downstream_peer key for CEL expression compatibility.
+// All fields are extracted individually to support dynamic addition of new fields in WorkloadMetadataObject.
+func buildWaypointSourceTags() []*tracing.CustomTag {
+	buildDownstreamFilterStateTag := func(tagName, fieldName string) *tracing.CustomTag {
+		return &tracing.CustomTag{
+			Tag: tagName,
+			Type: &tracing.CustomTag_Value{
+				Value: fmt.Sprintf("%%FILTER_STATE(downstream_peer_obj:FIELD:%s)%%", fieldName),
```
Comment (PetrMc) [inline pilot/pkg/networking/core/tracing.go:562]: for this to properly work we need istio/proxy#6775 merged in 1.29. Otherwise the FIELD accessor syntax won't be recognized and tags will be empty.
