### PR TITLE
Reuse the upstream connection

### LINKED ISSUE #27877: 1.8 Pilot regression: high CPU/memory usage from grpc.(*Server).useTransportAuthenticator
[pprof.pilot-discovery.samples.cpu.243.pb.gz](https://github.com/istio/istio/files/5362244/pprof.pilot-discovery.samples.cpu.243.pb.gz)
[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.100.pb.gz](https://github.com/istio/istio/files/5362246/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.100.pb.gz)

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix #27877

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

File: pkg/istio-agent/xds_proxy.go [hunk 1]
```diff
@@ -210,7 +215,7 @@ func (p *XdsProxy) StreamAggregatedResources(downstream discovery.AggregatedDisc
 				proxyLog.Warnf("upstream terminated with unexpected error %v", err)
 			}
 			_ = upstream.CloseSend()
-			return err
+			goto RecreateUpstream
```
Comment (howardjohn) [inline pkg/istio-agent/xds_proxy.go:218]: Can we add some tests? I am not sure this will work properly. When `upstreamError` is hit, this may be from the server closing. But we will try to reuse the connection, which will fail.

We either need more robust handling of connection errors, or we should just recreate the connection like current code but make sure we close the old one

File: pkg/istio-agent/xds_proxy.go [hunk 2]
```diff
@@ -140,11 +140,39 @@ func (p *XdsProxy) StreamAggregatedResources(downstream discovery.AggregatedDisc
...
+				// fire off an initial NDS request
+				ndsRequestChan <- &discovery.DiscoveryRequest{
+					TypeUrl: v3.NameTableType,
+				}
+				firstNDSSent = true
+			}
+		}
+	}()
+
+	go p.healthChecker.PerformApplicationHealthCheck(healthEventsChan, p.stopChan)
```
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pkg/istio-agent/xds_proxy.go:168]: good catch,  i will fix it

File: pkg/istio-agent/xds_proxy.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pkg/istio-agent/xds_proxy.go:218]: I think the grpc client will always reconnect to the server when any error occur.

https://github.com/grpc/grpc-go/blob/3c400e7fcc8719ba3d133563f9c9d126f03a80c0/clientconn.go#L825

Comment (hzxuzhonghu) [reply pkg/istio-agent/xds_proxy.go:218]: >When upstreamError is hit, this may be from the server closing. But we will try to reuse the connection, which will fail.

We may receive some error at this point and we will recreate a new stream. 

>Can we add some tests? 

I am not sure what kind of test you mean. I think this requires long-running test.

File: pkg/istio-agent/xds_proxy.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pkg/istio-agent/xds_proxy.go]: fixed

**Comment by hzxuzhonghu** [comment]
Ah. it seems the bot goes wrong, how could it merge without @howardjohn approval

**Comment by howardjohn** [comment]
I think Rama's approval got it in. I will take a look though

File: pkg/istio-agent/xds_proxy.go [hunk 3]
```diff
@@ -140,11 +140,42 @@ func (p *XdsProxy) StreamAggregatedResources(downstream discovery.AggregatedDisc
...
+				// fire off an initial NDS request
+				ndsRequestChan <- &discovery.DiscoveryRequest{
+					TypeUrl: v3.NameTableType,
+				}
+				firstNDSSent = true
+			}
+		}
+	}()
+
+	// health check stop channel
```
Comment (howardjohn) [inline pkg/istio-agent/xds_proxy.go:168]: :+1:

**Review by howardjohn — COMMENTED** [review]
I think this looks good. I am going to see if we can add some unit tests and will run it in my long running cluster
