### PR TITLE
preserve header case for passthrough clusters

### LINKED ISSUE #57331: PreserveHeaderCase does not configure PassthroughCluster
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

In current implementation, PreserveHeaderCase option does not take PasshthroughCluster into consideration, when I try to send requests to a host not defined in mesh, header case will not be preserved.

### Version

```Text
istio 1.25.3
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Kuromesi**
**Please provide a description of this PR:**
This resolve #57331.

### CODE REVIEW

File: pilot/pkg/networking/core/cluster_builder.go [hunk 1]
```diff
@@ -722,7 +741,7 @@ func (cb *ClusterBuilder) setUpstreamProtocol(cluster *clusterWrapper, port *mod
 		options.UpstreamProtocolOptions = &http.HttpProtocolOptions_ExplicitHttpConfig_{
 			ExplicitHttpConfig: &http.HttpProtocolOptions_ExplicitHttpConfig{
 				ProtocolConfig: &http.HttpProtocolOptions_ExplicitHttpConfig_HttpProtocolOptions{
-					HttpProtocolOptions: preserveCaseFormatterConfig,
+					HttpProtocolOptions: httpProtocolOptions(cb),
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/cluster_builder.go]: For regular clusters, can the old implementation (i.e. predefined `preserveCaseFormatterConfig` be retained to avoid building proto message unnecessarily?

File: pilot/pkg/networking/core/cluster_waypoint.go [hunk 2]
```diff
@@ -63,7 +63,7 @@ func buildInternalUpstreamCluster(name string, internalListener string, h2 bool)
 
 	if h2 {
 		c.TypedExtensionProtocolOptions = map[string]*anypb.Any{
-			v3.HttpProtocolOptionsType: passthroughHttpProtocolOptions,
+			v3.HttpProtocolOptionsType: passthroughHttpProtocolOptions(nil),
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/cluster_waypoint.go]: Same here. Can we retain the existing var?

File: pilot/pkg/networking/core/listener_builder.go [hunk 3]
```diff
@@ -326,7 +326,7 @@ func (lb *ListenerBuilder) buildHTTPConnectionManager(httpOpts *httpListenerOpts
 	// Preserve HTTP/1.x traffic header case
 	if ph.GetPreserveHttp1HeaderCase().GetValue() {
 		// This value only affects HTTP/1.x traffic
-		connectionManager.HttpProtocolOptions = preserveCaseFormatterConfig
+		connectionManager.HttpProtocolOptions = applyPreserveCaseFormatterConfig(&core.Http1ProtocolOptions{})
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/listener_builder.go]: same here

File: pilot/pkg/networking/core/cluster_builder.go (hunk 1 above)
Comment (Kuromesi) [reply pilot/pkg/networking/core/cluster_builder.go]: Ah you are right, I'll fix this and add ut later!

File: pilot/pkg/networking/core/cluster_builder.go [hunk 4]
```diff
@@ -57,20 +57,25 @@ var maxSecondsValue = int64((math.MaxInt64 - 999999999) / (1000 * 1000 * 1000))
...
 // revive:disable-next-line
-var passthroughHttpProtocolOptions = protoconv.MessageToAny(&http.HttpProtocolOptions{
-	CommonHttpProtocolOptions: &core.HttpProtocolOptions{
-		IdleTimeout: durationpb.New(5 * time.Minute),
-	},
-	UpstreamProtocolOptions: &http.HttpProtocolOptions_UseDownstreamProtocolConfig{
-		UseDownstreamProtocolConfig: &http.HttpProtocolOptions_UseDownstreamHttpConfig{
-			HttpProtocolOptions:  &core.Http1ProtocolOptions{},
-			Http2ProtocolOptions: http2ProtocolOptions(),
+var passthroughHttpProtocolOptions = func(cb *ClusterBuilder) *anypb.Any {
```
Comment (howardjohn) [inline pilot/pkg/networking/core/cluster_builder.go]: I don't think there is a need to make this a var instead of just a function?

Comment (Kuromesi) [reply pilot/pkg/networking/core/cluster_builder.go]: I agree

File: pilot/pkg/networking/core/cluster_builder.go [hunk 5]
```diff
@@ -54,10 +54,10 @@ import (
 
 var maxSecondsValue = int64((math.MaxInt64 - 999999999) / (1000 * 1000 * 1000)) // 9223372035, which is about 292 years.
 
-// passthroughHttpProtocolOptions are http protocol options used for pass through clusters.
+// defaultPassthroughHttpProtocolOptions are http protocol options used for pass through clusters.
 // nolint
 // revive:disable-next-line
-var passthroughHttpProtocolOptions = protoconv.MessageToAny(&http.HttpProtocolOptions{
+var defaultPassthroughHttpProtocolOptions = protoconv.MessageToAny(&http.HttpProtocolOptions{
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/cluster_builder.go]: Sorry for not being clear. But can we also have additional var preserveCasePassthroughHttpProtocolOptions and use that or default based Mesh config flag is enabled so that we do not build preserveCaseConfig again and again for passthrough clusters?

Comment (Kuromesi) [reply pilot/pkg/networking/core/cluster_builder.go]: I got your point, I'm just worrying about that maybe in the future there may be other options for passthrough cluster so I tried to make it configurable. But for now I think adding a new var is good enough. I'll fix this.

**Review by ramaraochavali — APPROVED** [review]
Thank you
