### PR TITLE
Fix pilot using wrong readinessprobe check, should check if /validate and /inject endpoints are ready.

### LINKED ISSUE #44157: Validation endpoint downtime during restart/upgrade
### Bug Description

Hi,
I think I may have found  a problem which happens during restart/upgrade of istiod deployment.
Basically, when I restart/upgrade /validate endpoint is affected by some downtime.
From what I see this has led, in my cluster, to custom resources not being validated by istiod during upgrade, which in turn led to the failure of the "helm upgrade" command.
It seems that the downtime is very short but that can occasionally lead to failures when I upgrade with telemetry enabled (due to EnvoyFilters being deployed).
Sadly, I cannot give the steps to reproduce the "helm upgrade failure" but I can provide some steps to show the downtime validate endpoint is affected by:

1. Deploy istio 1.17.1
2. Deploy a fortio pod which is out of the mesh in a namespace named "test" and start sending request to the "/validate" endpoint of istiod from fortio pod using following command: `fortio load -k -t 0 -allow-initial-errors -c 20 -qps 200 https://istiod.istio-system.svc.cluster.local:443/validate`
3. While requests are being sent, restart/upgrade istiod using following command: `kubectl rollout restart deployment istiod -n istio-system`
4. Wait until the new istiod pod is running again and stop the fortio. You should see some "connection refused" log messages as follows:

> 09:11:41 W http_client.go:795> [5] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [16] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [7] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 E http_client.go:653> [5] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [0] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [13] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [11] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [12] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [3] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [2] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [15] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [18] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [19] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [6] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [4] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 W http_client.go:795> [7] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [17] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [10] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [9] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [8] Non ok http code 400 (HTTP/1.1 400)
> 

Is that downtime expected behavior of istiod? Is there a way to overcome the occasionally failures when deploying CRs as part of the upgrade procedure.
Thank you in advance

### Version

```prose
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (1 proxies)
$ kubectl version --short
Client Version: v1.20.1
Server Version: v1.24.7
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11100383/bug-report.tar.gz)

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/44157

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I think the proper fix is in `s.addReadinessProbe("Secure Webhook Server", s.webhookReadyHandler)`

The issue with this is we start some bogus handler that always returns OK, then probe it.

This is over complex (why do we HTTPS call ourselves? Its historical from pre-Istiod microservice days) and wrong (we don't wait until the real endpoints are ready).

What we actually want is to wait for the HTTP server for /inject and /validate to be ready, not the controllers, and not the fake /httpsReady endpoint.

I would remove the `httpsReady` thing, and add readiness checks that we have added /inject and /validate to the mux (in initConfigValidation and initSidecarInjector)

**Comment by kfaseela** [comment]
> I think the proper fix is in `s.addReadinessProbe("Secure Webhook Server", s.webhookReadyHandler)`
> 
> The issue with this is we start some bogus handler that always returns OK, then probe it.
> 
> This is over complex (why do we HTTPS call ourselves? Its historical from pre-Istiod microservice days) and wrong (we don't wait until the real endpoints are ready).
> 
> What we actually want is to wait for the HTTP server for /inject and /validate to be ready, not the controllers, and not the fake /httpsReady endpoint.
> 
> I would remove the `httpsReady` thing, and add readiness checks that we have added /inject and /validate to the mux (in initConfigValidation and initSidecarInjector)

I agree to this !

File: pkg/webhooks/validation/controller/controller.go [hunk 1]
```diff
@@ -202,6 +202,10 @@ func (c *Controller) readyForFailClose() bool {
 	return true
 }
 
+func (c *Controller) Ready() bool {
+	return c.readyForFailClose()
```
[the remark this answers is not in the document]
Comment (hanxiaop) [reply pkg/webhooks/validation/controller/controller.go:206]: I see, thanks for the explaination!

**Comment by hanxiaop** [comment]
Tested with the fortio pod:

The fortio pod log:
```
07:58:26 E http_client.go:895> [8] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34134->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [9] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34130->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [0] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34148->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [6] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34114->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [0] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34268->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [9] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34222->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [6] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34264->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [5] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34248->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [7] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34232->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [8] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34240->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [4] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34220->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [3] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34216->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [2] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34196->10.96.220.98:443: read: connection reset by peer
07:58:26 E http_client.go:895> [1] Unable to TLS connect to 10.96.220.98:443 : read tcp 10.244.1.174:34194->10.96.220.98:443: read: connection reset by peer
07:58:26 W http_client.go:1058> [8] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [1] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [0] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [3] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [7] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [5] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [4] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [2] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [9] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [6] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [8] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [0] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [3] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [5] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [7] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [9] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [1] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [4] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [6] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [2] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [4] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [6] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [9] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [7] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [8] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [0] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [1] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [2] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [5] Non ok http code 400 (HTTP/1.1 400)
07:58:26 W http_client.go:1058> [3] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [7] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [5] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [6] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [2] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [4] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [0] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [8] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [1] Non ok http code 400 (HTTP/1.1 400)
07:58:27 W http_client.go:1058> [9] Non ok http code 400 (HTTP/1.1 400)
```

Istiod ready status:
```
kubectl -n istio-system get pods --watch-only | while read line ; do echo -e "$(date +"%Y-%m-%d %H:%M:%S.%3N")\t pods\t $line" ; done

2023-04-27 15:56:48.818	 pods	 NAME                      READY   STATUS    RESTARTS   AGE
2023-04-27 15:56:48.818	 pods	 istiod-799b94d859-spdwm   1/1     Running   0          2m42s
2023-04-27 15:57:24.817	 pods	 istiod-799b94d859-spdwm   0/1     Running   0          3m18s

2023-04-27 15:58:27.817	 pods	 istiod-799b94d859-spdwm   1/1     Running   0          4m21s
```

**Comment by howardjohn** [comment]
Does that fortio log indicate it worked...? it seems like its getting errors?

**Comment by kfaseela** [comment]
> Does that fortio log indicate it worked...? it seems like its getting errors?

I think @hanxiaop has restarted the same pod? May be I can try out the rollout scenario as mentioned in the issue and verify the behavior

File: pilot/pkg/bootstrap/server.go [hunk 2]
```diff
@@ -1347,6 +1352,29 @@ func (s *Server) serveHTTP() error {
 	return nil
 }
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/server.go:1354]: One note - in testing I did still see errors but I think its from istiod shutting down too fast instead of becoming ready too soon. So kube-proxy was too slow.

File: pilot/pkg/bootstrap/server.go [hunk 3]
```diff
@@ -1347,6 +1352,29 @@ func (s *Server) serveHTTP() error {
...
+func (s *Server) initReadinessProbes() {
+	probes := map[string]readinessProbe{
+		"discovery": func() (bool, error) {
+			return s.XDSServer.IsServerReady(), nil
+		},
+		"sidecarInjector": func() (bool, error) {
+			if s.readinessFlags.sidecarInjectorReady {
+				return true, nil
+			}
+			return false, fmt.Errorf("sidecar injector not ready")
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/server.go:1364]: On L1358 we return `ready, nil`. But here we return error. Should they be consistent?

File: pilot/pkg/bootstrap/validation.go [hunk 4]
```diff
@@ -39,6 +39,8 @@ func (s *Server) initConfigValidation(args *PilotArgs) error {
 		return err
 	}
 
+	s.readinessFlags.configValidationReady = true
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/validation.go:42]: I think this is racy, should be atomic bool?

File: pilot/pkg/bootstrap/server.go (hunk 3 above)
Comment (howardjohn) [reply pilot/pkg/bootstrap/server.go:1364]: I think we can just make them return a `bool`, then we can use the `name` which we already have to make the error useful.

**Comment by kfaseela** [comment]
@hanxiaop I built this change, and did a `k rollout restart deployment istiod -n istio-system` while fortio requests were ongoing.

I still have connection refused in the logs for a short duration:

$ k logs -n fortio traffic-generator -f | grep -i unable

20:03:32 E http_client.go:895> [12] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [6] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [17] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [2] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [10] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [18] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [5] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
20:03:32 E http_client.go:895> [9] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused

**Comment by howardjohn** [comment]
> @hanxiaop I built this change, and did a `k rollout restart deployment istiod -n istio-system` while fortio requests were ongoing.
> 
> I still have connection refused in the logs for a short duration:
> 
> $ k logs -n fortio traffic-generator -f | grep -i unable
> 
> 20:03:32 E http_client.go:895> [12] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [6] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [17] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [2] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [10] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [18] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [5] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [9] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused

I think its from the old pods shutting down too quickly. If  you add a prestop hook it goes away

**Comment by kfaseela** [comment]
> > @hanxiaop I built this change, and did a `k rollout restart deployment istiod -n istio-system` while fortio requests were ongoing.
> > I still have connection refused in the logs for a short duration:
> > $ k logs -n fortio traffic-generator -f | grep -i unable
> > 20:03:32 E http_client.go:895> [12] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [6] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [17] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [2] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [10] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [18] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [5] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [9] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
> 
> I think its from the old pods shutting down too quickly. If you add a prestop hook it goes away

From this output, old put is terminating only after the new one is up and running?

faseelak@Faseelas-MBP istio.io % kubectl -n istio-system get pods --watch-only | while read line ; do echo -e "$(date +"%Y-%m-%d %H:%M:%S.%3N")\t pods\t $line" ; done
2023-04-27 22:04:23.3N	 pods	 NAME                      READY   STATUS    RESTARTS   AGE
2023-04-27 22:04:23.3N	 pods	 istiod-59765dc864-dg8gm   0/1     Pending   0          0s
2023-04-27 22:04:23.3N	 pods	 istiod-59765dc864-dg8gm   0/1     Pending   0          0s
2023-04-27 22:04:23.3N	 pods	 istiod-59765dc864-dg8gm   0/1     ContainerCreating   0          0s
2023-04-27 22:04:25.3N	 pods	 istiod-59765dc864-dg8gm   0/1     Running             0          2s
2023-04-27 22:04:25.3N	 pods	 istiod-59765dc864-dg8gm   1/1     Running             0          2s
2023-04-27 22:04:25.3N	 pods	 istiod-546f48c4b5-l8x9v   1/1     Terminating         0          56s
2023-04-27 22:04:26.3N	 pods	 istiod-546f48c4b5-l8x9v   0/1     Terminating         0          57s
2023-04-27 22:04:26.3N	 pods	 istiod-546f48c4b5-l8x9v   0/1     Terminating         0          57s
2023-04-27 22:04:26.3N	 pods	 istiod-546f48c4b5-l8x9v   0/1     Terminating         0          57s

**Comment by howardjohn** [comment]
it takes kube-proxy a while to notice the pod is removed though so it connects to a non-existing pod (https://learnk8s.io/graceful-shutdown)

File: pilot/pkg/bootstrap/validation.go (hunk 4 above)
Comment (hanxiaop) [reply pilot/pkg/bootstrap/validation.go]: revised, thanks

**Comment by hanxiaop** [comment]
> > @hanxiaop I built this change, and did a `k rollout restart deployment istiod -n istio-system` while fortio requests were ongoing.
> > I still have connection refused in the logs for a short duration:
> > $ k logs -n fortio traffic-generator -f | grep -i unable
> > 20:03:32 E http_client.go:895> [12] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [6] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [17] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [2] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [10] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [18] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [5] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused 20:03:32 E http_client.go:895> [9] Unable to TLS connect to 10.111.180.237:443 : dial tcp 10.111.180.237:443: connect: connection refused
> 
> I think its from the old pods shutting down too quickly. If you add a prestop hook it goes away


I've tested, by adding a pre-stop hook, there won't be any downtime anymore when doing the rollout.

File: pilot/pkg/bootstrap/server.go (hunk 2 above)
Comment (hanxiaop) [reply pilot/pkg/bootstrap/server.go:1355]: I've also noticed the same behavior. Without this fix, if adding the prestop hook, there won't be any downtime as well.

**Comment by hanxiaop** [comment]
Deleted the releasenotes since this doesn't really fix the ready issue I think. However this makes the readinessprobe more clear.

**Comment by kfaseela** [comment]
> dg8gm

I was wondering how easy it is to have a preStopHook, especially the value to be used can vary, and we dont have such a preStopHook provided by default. How about disabling the validation while upgrade is in progress, so that upgrade won't fail? The issue is critical only in upgrade scenarios.

**Comment by howardjohn** [comment]
IMO its not the big of a deal to have the shutdown issue... its a race condition so its annoying to just `sleep 10` - it makes a variety of things way slower. I think we made our tests 2x faster (like 1hr to 30min) by fixing a bug that took 30s to shutdown Istiod. Note the `helm upgrade` issue is far less important now as (1) revisions are recommended anyways (2) we don't install any Istio CRDs as part of install anymore.

**Review by howardjohn — APPROVED** [review]

**Comment by calikonur** [comment]
Hi,
I think this preStopHook would introduce redundant time to the old pod to be terminated, because the termination duration may be different depending on the cluster environment, which may not be an optimal solution.
To solve the issue, I agree disabling the validation during upgrade would be better.

**Review by kfaseela — APPROVED** [review]

**Comment by calikonur** [comment]
Hi,

As stated, Istio CRDs are not installed as part of install anymore. However during upgrade process with helm, CustomResources (such as EnvoyFilter CR) themselves are applied again not the CRDs.
Due to that, this PR unfortunately still does not solve the encountered problem. 
It is still possible that the instant a CustomResource is applied during the "helm upgrade" process coincide in a time frame from the old pod is removed until kube-proxy understands that old pod is removed. This will return helm upgrade failure again.

So I am wondering if it would be possible to find a solution that will cover the upgrade procedures which are not using revision. 
What do you think? Could we maybe develop any idea for this?

Best regards

**Comment by kfaseela** [comment]
> > As stated, Istio CRDs are not installed as part of install anymore. However during upgrade process with helm, CustomResources (such as EnvoyFilter CR) themselves are applied again not the CRDs.
> 
> In the above description when I said CRDs I meant CRs. In the install of Istio now there is no CRs applied, including EnvoyFilters.
> 
> of course the user may have their own they apply.
> 
> > What do you think? Could we maybe develop any idea for this?
> 
> At the very least you could add a `preStop` hook to Istiod using https://istio.io/v1.14/docs/setup/additional-setup/customize-installation-helm/

@howardjohn As per https://github.com/istio/istio/issues/44157 looks like there are no custom EnvoyFilters, but just Istio with telemetry enabled? Do we have EnvoyFilters in that case?

**Comment by howardjohn** [comment]
Not anymore
