### PR TITLE
fix file controller flake

### LINKED ISSUE #59112: test flake: kube/file controller TestController
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/59111/unit-tests_istio/2023746382032015360

### PR DESCRIPTION
**Pull request by stevenctl**
**Please provide a description of this PR:**

The file controller might take slightly longer O(~50ms) and our test harness has pretty aggressive timeouts. This causes easy to replicate flakes (use `stress` against the tests in this package). 

fixes #59112

### CODE REVIEW

File: pilot/pkg/config/kube/file/controller_test.go [hunk 1]
```diff
@@ -30,8 +31,14 @@ import (
 	"istio.io/istio/pkg/test"
 	"istio.io/istio/pkg/test/util/assert"
 	"istio.io/istio/pkg/test/util/file"
+	"istio.io/istio/pkg/test/util/retry"
 )
 
+// fileEventOpts uses a longer timeout than the default 1s for the event tracker,
+// since file watcher events pass through fsnotify debouncing (50ms) and multiple
+// levels of async krt event processing before reaching the handler.
+var fileEventOpts = []retry.Option{retry.Timeout(5 * time.Second), retry.BackoffDelay(time.Millisecond)}
```
Comment (ilrudie) [inline pilot/pkg/config/kube/file/controller_test.go]: Given the slowness of this file events we're trying to handle, should our backoff be less aggressive too? maybe 50-100ms or something?

Comment (stevenctl) [reply pilot/pkg/config/kube/file/controller_test.go]: yeah 50 would make sense.

**Review by ilrudie — APPROVED** [review]
lgtm
