### PR TITLE
istio-discovery: validate keepaliveMaxServerConnectionAge duration

### LINKED ISSUE #27257: Istiod discovery should validate its flags (panic)
To reproduce, install Istio with `istioctl install --set values.pilot.keepaliveMaxServerConnectionAge="-30m"`

The logs show a **panic** and backtrace that does not include any Istio code.  A user would not be able to figure this out.  Istiod SHOULD fail on bad flag values, but it should log the reason and exit, not panic inside `google.golang.org/grpc/internal/transport.NewServerTransport(...)`

A related Issue to fix it so that the user gets this feedback from _istioctl_ or as a Status on the operator's IOP resource. https://github.com/istio/istio/issues/21473 .  This issue is just to make Pilot output meaningful logs when it is misconfigured.

I am willing to do this work if no one else wants it.  I prefer if someone from @istio/wg-networking-maintainers triages it with a Priority first.

### PR DESCRIPTION
**Pull request by shamsher31**
Attempt to fix https://github.com/istio/istio/issues/27257
 
Installing Istio with `keepaliveMaxServerConnectionAge` negative duration fails.
```
$ istioctl install --set values.pilot.keepaliveMaxServerConnectionAge="-30m"
```

```
$ kubectl logs -l app=istiod -n istio-system
google.golang.org/grpc/internal/transport.NewServerTransport(...)
        google.golang.org/grpc@v1.33.1/internal/transport/transport.go:537
google.golang.org/grpc.(*Server).newHTTP2Transport(0xc001396fc0, 0x32a2760, 0xc0011a7240, 0x320b9c0, 0xc0026ea840, 0x320b9c0, 0xc0026ea840)
        google.golang.org/grpc@v1.33.1/server.go:837 +0x18b
google.golang.org/grpc.(*Server).handleRawConn(0xc001396fc0, 0x32a3f00, 0xc0024bea28)
        google.golang.org/grpc@v1.33.1/server.go:804 +0x47e
google.golang.org/grpc.(*Server).Serve.func3(0xc001396fc0, 0x32a3f00, 0xc0024bea28)
        google.golang.org/grpc@v1.33.1/server.go:774 +0x3f
created by google.golang.org/grpc.(*Server).Serve
        google.golang.org/grpc@v1.33.1/server.go:773 +0x81e
```

After the validation:

```
$ kubectl logs -l app=istiod -n istio-system
2020-11-03T07:28:09.467922Z     error   invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts positive duration eg: 30m
Error: invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts positive duration eg: 30m
```

```
$ pilot-discovery discovery --keepaliveMaxServerConnectionAge="-30m"
Error: invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts positive duration eg: 30m
2020-11-02T05:09:41.836884Z     error   invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts positive duration eg: 30m
```

### CODE REVIEW

**Comment by shamsher31** [comment]
@howardjohn How to make sure that newly created template functions compiled correctly?


```
$ make gen
Error: parse error at (istio-discovery/templates/deployment.yaml:91): function "formatNegativeDuration" not defined
Makefile.core.mk:358: recipe for target 'gen-kustomize' failed
make[1]: *** [gen-kustomize] Error 1
make: *** [Makefile:46: gen] Error 2
```

**Review by howardjohn — CHANGES_REQUESTED** [review]
I don't think this is the right approach

* Adding new functions to the injection template is painful because if you somehow get a mismatch in pilot version and template it will fail. Not the end of the world, but not ideal
* Pushes complexity into the template when it should be processed in the pilot code
* Silently accepts invalid inputs from the user, and with extremely dangerous defaults (1s)

**Comment by shamsher31** [comment]
I'm not really familiar with the pilot codebase, but I will give it a try tomorrow.

**Comment by shamsher31** [comment]
>  it should be processed in the pilot code


```
$ pilot-discovery discovery --keepaliveMaxServerConnectionAge="-30m"
...
2020-10-30T06:44:10.278504Z     info    FLAG: --keepaliveInterval="30s"
2020-10-30T06:44:10.278507Z     info    FLAG: --keepaliveMaxServerConnectionAge="-30m0s"
2020-10-30T06:44:10.278510Z     info    FLAG: --keepaliveTimeout="10s"
...

Error: failed to create discovery service: invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts postive duration eg: 30m
2020-10-30T06:44:10.297091Z     error   failed to create discovery service: invalid duration: -30m0s: --keepaliveMaxServerConnectionAge only accepts postive duration eg: 30m
```

@howardjohn I'm still not able to get errors in istiod logs.

File: pkg/config/validation/validation.go [hunk 1]
```diff
@@ -1235,6 +1235,23 @@ func ValidateProtocolDetectionTimeout(timeout *types.Duration) error {
 	return nil
 }
 
+// ValidateMaxServerConnectionAge validate positive duration
+func ValidateMaxServerConnectionAge(in time.Duration) error {
```
Comment (hzxuzhonghu) [inline pkg/config/validation/validation.go:1239]: This is not the right place. The flag should be validated during bootstrap under `pilot/cmd`

Comment (shamsher31) [reply pkg/config/validation/validation.go:1239]: This is a common validation, calling now from `pilot/cmd`

Comment (hzxuzhonghu) [reply pkg/config/validation/validation.go:1239]: The package is mostly used mostly for admission webhook to validate the API, for flags they belong to process startup

Comment (hzxuzhonghu) [reply pkg/config/validation/validation.go:1239]: We may need to validate other flags in the future

File: pilot/cmd/pilot-discovery/main.go [hunk 2]
```diff
@@ -66,6 +67,12 @@ var (
 			// Create the stop channel for all of the servers.
 			stop := make(chan struct{})
 
+			// If keepaliveMaxServerConnectionAge is negative, istiod crash
+			// https://github.com/istio/istio/issues/27257
+			if err := validation.ValidateMaxServerConnectionAge(serverArgs.KeepaliveOptions.MaxServerConnectionAge); err != nil {
```
Comment (howardjohn) [inline pilot/cmd/pilot-discovery/main.go:72]: I think you should call this in a PreRun or similar cobra section, not RunE. Not a cobra expert, @esnible probably knows more

File: pkg/config/validation/validation.go [hunk 3]
```diff
@@ -1235,6 +1235,23 @@ func ValidateProtocolDetectionTimeout(timeout *types.Duration) error {
...
+	if err := IsNegativeDuration(in); err != nil {
+		return fmt.Errorf("%v: --keepaliveMaxServerConnectionAge only accepts positive duration eg: 30m", err)
+	}
+	return nil
+}
+
+// IsNegativeDuration check if the duration is negative
+func IsNegativeDuration(in time.Duration) error {
```
[the remark this answers is not in the document]
Comment (shamsher31) [reply pkg/config/validation/validation.go:1247]: I don't think so, all the defaults I saw are `30m`. Probably we should also decide what should be the minimum duration user can pass?

File: pilot/cmd/pilot-discovery/main.go (hunk 2 above)
Comment (shamsher31) [reply pilot/cmd/pilot-discovery/main.go:72]: Agree, will do that.

File: pkg/config/validation/validation.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (howardjohn) [reply pkg/config/validation/validation.go:1247]: I mean, instead of outputing to a string and looking for `-`, just do an integer comparison. a `time.Duration` is just an alias for `int64`

[the remark this answers is not in the document]
Comment (shamsher31) [reply pkg/config/validation/validation.go:1247]: Done

File: pilot/cmd/pilot-discovery/main.go (hunk 2 above)
Comment (shamsher31) [reply pilot/cmd/pilot-discovery/main.go]: Done.

**Review by howardjohn — APPROVED** [review]
