### PR TITLE
Fix a test flake.

### LINKED ISSUE #11020: mixer/adapter/list TestRefreshAndPurge is flaky
Example: https://gubernator.k8s.io/build/istio-prow/logs/istio-postsubmit/4176

```
env.go:117: Fetching list from http://127.0.0.1:41126
env.go:117: Installing updated list with 1 entries
env.go:117: Fetching list from http://127.0.0.1:41126
env.go:117: Fetched list is unchanged
env.go:117: Purging list due to inability to refresh it in time
list_test.go:533: Got success, expected error
```

Basically the same as https://github.com/istio/istio/issues/3686, which was never fixed.

### PR DESCRIPTION
**Pull request by geeknoid**
The test was inherently time-dependent. If the list was purge due to not being to be refreshed fast enough, instead of failing due to the conditions the test setup, then the test would not see the results it expected. We now wait for the right conditions explicitly before allowing things to move forward.

Fixes #11020

### CODE REVIEW

File: mixer/adapter/list/list_test.go [hunk 1]
```diff
@@ -503,7 +503,8 @@ func TestRefreshAndPurge(t *testing.T) {
 	// wait for the list to have been populated
 	for {
 		time.Sleep(1 * time.Millisecond)
-		if h.hasData() {
+		result, _ := h.hasData()
+		if result {
```
Comment (douglas-reid) [inline mixer/adapter/list/list_test.go]: do we care about timing out at some point?  or are we fine with the default timeout on tests?

Comment (geeknoid) [reply mixer/adapter/list/list_test.go]: Do you think it's needed for reliability of the test? I thought the timescales involved should work out well (refresh is in a few milliseconds, test timeout is a few seconds)

**Comment by geeknoid** [comment]
All tests were passing previously, too many flakes however. So I'm force pushing.
