### PR TITLE
pilot-agent support reload ROOTCA

### LINKED ISSUE #36723: question about istio-ca-root-cert configmap
### Bug Description

There's something wired, reproduce steps as following:

- create an cluster with kind 
```bash
kind create cluster --name istio
```
- install istio via istioctl
```bash
kubectl create ns istio-system
istioctl install --set profile=minimal -y
```
- label default namespace and deploy a sleep pod
```bash
kubectl label namespace default istio-injection=enabled


kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.12/samples/sleep/sleep.yaml
```
- uninstall istio
```bash
istioctl x uninstall --purge -y
kubectl delete secret istio-ca-secret -nistio-system
```
- install istio again
```bash
istioctl install --set profile=minimal -y
```

you can find some warning log from sleep pod:
```bash
2022-01-06T01:36:33.183753Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed since 54s ago: 14, connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"cluster.local\")"
2022-01-06T01:36:33.888300Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed since 54s ago: 14, connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"cluster.local\")"

```

Is this mechanism expected? 
Do we need to support pilot-agent reload `istio-ca-root-cert` configmap?

@howardjohn PTAL

### Version

```prose
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12-dev (1 proxies)

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

this PR will fix https://github.com/istio/istio/issues/36723, add a mechanism allow pilot-agent to reload ca file once the ROOTCA changed.

```shell
2022-01-13T14:27:18.657508Z	info	Envoy proxy is ready
2022-01-13T14:28:17.949238Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed since 31s ago: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.96.0.10:53: no such host"
2022-01-13T14:28:22.473133Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed since 36s ago: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.96.0.10:53: no such host"
2022-01-13T14:28:28.059480Z	info	Receive file var/run/secrets/istio/root-cert.pem event "var/run/secrets/istio/..2022_01_13_14_28_28.461962497": CHMOD
2022-01-13T14:28:28.059585Z	info	citadelclient	Citadel client using custom root cert: var/run/secrets/istio/root-cert.pem
2022-01-13T14:28:28.060340Z	info	ads	XDS: Incremental Pushing:0 ConnectedEndpoints:2 Version:
2022-01-13T14:28:28.060363Z	info	ads	XDS: Incremental Pushing:0 ConnectedEndpoints:2 Version:
2022-01-13T14:28:28.060573Z	info	cache	returned workload trust anchor from cache	ttl=23h58m48.939433951s
2022-01-13T14:28:28.060643Z	info	ads	SDS: PUSH for node:httpbin-74fb669cc6-g2svb.default resources:1 size:1.1kB resource:ROOTCA
2022-01-13T14:28:28.060763Z	info	cache	returned workload certificate from cache	ttl=23h58m48.939242047s
2022-01-13T14:28:28.060815Z	info	ads	SDS: PUSH for node:httpbin-74fb669cc6-g2svb.default resources:1 size:4.0kB resource:default
2022-01-13T14:28:33.647786Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed since 47s ago: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.96.0.10:53: no such host"
2022-01-13T14:28:43.764632Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012

```

### CODE REVIEW

File: pkg/istio-agent/agent.go [hunk 1]
```diff
@@ -205,6 +210,35 @@ func NewAgent(proxyConfig *mesh.ProxyConfig, agentOpts *AgentOptions, sopts *sec
...
+			log.Infof("Receive file %s event %v", a.tlsOpts.RootCert, gotEvent)
+			if a.caClient != nil {
+				err := a.caClient.InitClient()
+				if err != nil {
+					log.Warnf("Failed to init CA client")
+					continue
+				}
+
+				a.secretCache.CallUpdateCallback(security.RootCertReqResourceName)
+				a.secretCache.CallUpdateCallback(security.WorkloadKeyCertResourceName)
```
Comment (howardjohn) [inline pkg/istio-agent/agent.go:231]: Why do we need to update this one?

File: pkg/istio-agent/agent.go [hunk 2]
```diff
@@ -205,6 +210,35 @@ func NewAgent(proxyConfig *mesh.ProxyConfig, agentOpts *AgentOptions, sopts *sec
...
+		case gotEvent := <-a.watcher.Events(a.tlsOpts.RootCert):
+			log.Infof("Receive file %s event %v", a.tlsOpts.RootCert, gotEvent)
+			if a.caClient != nil {
+				err := a.caClient.InitClient()
+				if err != nil {
+					log.Warnf("Failed to init CA client")
+					continue
+				}
+
+				a.secretCache.CallUpdateCallback(security.RootCertReqResourceName)
```
Comment (howardjohn) [inline pkg/istio-agent/agent.go:230]: Strictly speaking, `a.tlsOpts.RootCert` and `RootCertReqResourceName` are not the same thing. The former is the root cert of *istiod*, and the latter the root cert *of the mesh* - they may be different.

And we already have a mechanism to update the latter - https://github.com/istio/istio/blob/3083ead98573a5305e98566650d3637fb6b4ae39/pilot/pkg/xds/pcds.go#L67. So we may need to consider if we want 2 ways to do this. I think its reasonable but curious of @shankgan opinion

File: pkg/istio-agent/agent.go [hunk 3]
```diff
@@ -205,6 +210,35 @@ func NewAgent(proxyConfig *mesh.ProxyConfig, agentOpts *AgentOptions, sopts *sec
...
+	}
+}
+
+func (a *Agent) watcherHandler(ctx context.Context) {
+	for {
+		select {
+		case gotEvent := <-a.watcher.Events(a.tlsOpts.RootCert):
+			log.Infof("Receive file %s event %v", a.tlsOpts.RootCert, gotEvent)
+			if a.caClient != nil {
+				err := a.caClient.InitClient()
```
Comment (howardjohn) [inline pkg/istio-agent/agent.go:224]: Not strictly related to this PR but seems like `InitClient` has data races as there is no locking at all.. Do we have sufficient test coverage?

File: pkg/istio-agent/agent.go [hunk 4]
```diff
@@ -205,6 +210,35 @@ func NewAgent(proxyConfig *mesh.ProxyConfig, agentOpts *AgentOptions, sopts *sec
...
+				if err != nil {
+					log.Warnf("Failed to init CA client")
+					continue
+				}
+
+				a.secretCache.CallUpdateCallback(security.RootCertReqResourceName)
+				a.secretCache.CallUpdateCallback(security.WorkloadKeyCertResourceName)
+
+				err = a.xdsProxy.InitIstiodDialOptions(a)
```
Comment (howardjohn) [inline pkg/istio-agent/agent.go:233]: same concern about data race with the citadel client, except this one is introduce in this PR

**Review by howardjohn — COMMENTED** [review]
One overall concern - Do we actually need to do the full gRPC connection recreation?

For Client/Server certs, tls.Config has GetClientCertificate and GetCertificate. But there is no GetRootCAs.

However, RootCAs is an `*x509.CertPool`. In theory we can add to the pool after creating it... but looking at the code it doesn't seem to be threadsafe so maybe would not work

File: pkg/istio-agent/agent.go (hunk 3 above)
Comment (zirain) [reply pkg/istio-agent/agent.go:224]: I'll review all things about data race.

File: pkg/istio-agent/agent.go (hunk 1 above)
Comment (zirain) [reply pkg/istio-agent/agent.go]: removed

File: pkg/istio-agent/agent.go (hunk 3 above)
Comment (zirain) [reply pkg/istio-agent/agent.go]: after reviewed the entire flow, it's unnecessary to `InitClient`.

File: pkg/istio-agent/agent.go (hunk 2 above)
Comment (zirain) [reply pkg/istio-agent/agent.go:224]: I'm confused on this point. After restart istiod pod, the connection with sidecar is terminated.  can xds work on that time?

Comment (hzxuzhonghu) [reply pkg/istio-agent/agent.go:224]: You can safely rely on pcds then

File: security/pkg/nodeagent/caclient/providers/citadel/client.go [hunk 5]
```diff
@@ -61,14 +62,20 @@ type TLSOptions struct {
...
+func NewCitadelClient(opts *security.Options, tlsOpts *TLSOptions, watcher filewatcher.FileWatcher) (*CitadelClient, error) {
 	c := &CitadelClient{
 		tlsOpts:   tlsOpts,
 		opts:      opts,
 		provider:  caclient.NewCATokenProvider(opts),
 		usingMtls: atomic.NewBool(false),
 	}
 
+	if watcher != nil && c.tlsOpts.RootCert != "" {
+		if err := watcher.Add(c.tlsOpts.RootCert); err != nil {
```
Comment (hzxuzhonghu) [inline security/pkg/nodeagent/caclient/providers/citadel/client.go:74]: I think you need to watch xds_proxy used root cert as well, that one may not equal to this one

**Comment by zirain** [comment]
@howardjohn fix some concerns, request a new review.

File: pkg/istio-agent/xds_proxy.go [hunk 6]
```diff
@@ -345,6 +347,13 @@ func (p *XdsProxy) handleStream(downstream adsStream) error {
 	return p.HandleUpstream(ctx, con, xds)
 }
 
+func (p *XdsProxy) buildUpstreamConn(ctx context.Context) (*grpc.ClientConn, error) {
+	p.optsMutex.Lock()
```
Comment (shankgan) [inline pkg/istio-agent/xds_proxy.go:351]: nit: perhaps an RLock() ?

**Comment by shankgan** [comment]
cool fix - pretty useful even in scenarios when control plane remains unchanged and just the ca certs are changed. A test in xds_proxy_test.go would help to confirm that writes into the cacert file are picked up by the xds proxy in new connections to control plane

File: pkg/istio-agent/xds_proxy.go (hunk 6 above)
Comment (howardjohn) [reply pkg/istio-agent/xds_proxy.go:351]: can we fetch `p.istiodDialOptions` in lock, then call `grpc.DialContext` out of the lock? Otherwise we can block the lock for a long time

**Review by howardjohn — COMMENTED** [review]
Nice! Just one small fix and a test in TestAgent and this LGTM

**Comment by zirain** [comment]
> Nice! Just one small fix and a test in TestAgent and this LGTM

fixed, please review again.

File: pkg/istio-agent/agent_test.go [hunk 7]
```diff
@@ -489,6 +489,39 @@ func TestAgent(t *testing.T) {
...
+		meta := proxyConfigToMetadata(t, a.ProxyConfig)
+		err := retry.Until(func() bool {
+			err := test.Wrap(func(t test.Failer) {
+				conn := setupDownstreamConnectionUDS(t, a.AgentConfig.XdsUdsPath)
+				xdsc := xds.NewAdsTest(t, conn).WithMetadata(meta)
+				_ = xdsc.RequestResponseAck(t, nil)
+			})
+
+			return err == nil
+		}, retry.Timeout(time.Second*5), retry.Delay(time.Millisecond*200))
```
Comment (howardjohn) [inline pkg/istio-agent/agent_test.go:514]: This is not great since it means the test always takes at LEAST 5s. IIUC, we are expecting a failure, so do we really need to check it failed 5s/200ms=25x in a row? Seems like we can just bring the test.Wrap outside of retry.Until? Then its one attempt and very quick

File: pkg/istio-agent/xds_proxy.go (hunk 6 above)
Comment (howardjohn) [reply pkg/istio-agent/xds_proxy.go:351]: Ping

**Review by howardjohn — COMMENTED** [review]
LGTM if we fix the lock and the small change in the test. This is great, thanks!

File: pkg/istio-agent/agent_test.go (hunk 7 above)
Comment (zirain) [reply pkg/istio-agent/agent_test.go]: agree that.

**Comment by zirain** [comment]
@howardjohn fix the slow UT and RLock.

**Review by howardjohn — APPROVED** [review]
