### PR TITLE
fix uninstall args validation.

### LINKED ISSUE #30002: istioctl uninstall --set revision doesn't work
```
$ ik x uninstall --set revision=new
Error: at least one of the --revision, --filename or --purge flags must be set
```

I shouldn't need to pass --revision, when --set revision=new (or, I assume, -f) already provides this info. This makes it inconsistent with `istioctl install`

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/30002

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: operator/cmd/mesh/uninstall.go [hunk 1]
```diff
@@ -104,8 +104,8 @@ func UninstallCmd(logOpts *log.Options) *cobra.Command {
   # Uninstall all control planes and shared resources
   istioctl x uninstall --purge`,
 		Args: func(cmd *cobra.Command, args []string) error {
-			if uiArgs.revision == "" && uiArgs.filename == "" && !uiArgs.purge {
-				return fmt.Errorf("at least one of the --revision, --filename or --purge flags must be set")
+			if uiArgs.revision == "" && getRevisionFromSetFlags(uiArgs.set) == "" && uiArgs.filename == "" && !uiArgs.purge {
```
Comment (shamsher31) [inline operator/cmd/mesh/uninstall.go:107]: I think you can use the following so you don't have to write your own method just to find `revision`. 
https://github.com/istio/istio/blob/96f0b401cdc7794817187334bcbee44ff1193d48/operator/pkg/manifest/shared.go#L494

Comment (morvencao) [reply operator/cmd/mesh/uninstall.go]: Thanks @shamsher31 
Applied your comments.

**Review by shamsher31 — APPROVED** [review]
Thanks.

**Review by howardjohn — APPROVED** [review]
