### PR TITLE
simplify validatingwebhookconfiguration management

### LINKED ISSUE #20944: istioctl manifest apply appears to fail
There are a bunch of errors and it's not clear if this is transient or we are left in a bad state:

```bash
$ go run istioctl/cmd/istioctl/main.go manifest apply
go: downloading istio.io/api v0.0.0-20200206183506-a8a00652fd05
This will install the default Istio profile into the cluster. Proceed? (y/N) y
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
2020-02-07T18:22:44.217894Z	error	installer	error running kubectl: exit status 1
2020-02-07T18:22:47.513588Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component Pilot.
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
Deployment is not ready: istio-system/istiod
Waiting for resources ready with timeout of 5m0s
- Applying manifest for component AddonComponents...
- Applying manifest for component IngressGateways...
✔ Finished applying manifest for component AddonComponents.
✔ Finished applying manifest for component IngressGateways.

Component Pilot - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Error from server (InternalError): error when applying patch: (repeated 1 times)
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"authentication.istio.io/v1alpha1\",\"kind\":\"MeshPolicy\",\"metadata\":{\"annotations\":{},\"labels\":{\"operator.istio.io/component\":\"Pilot\",\"operator.istio.io/managed\":\"Reconcile\",\"operator.istio.io/version\":\"1.5.0\",\"release\":\"istio\"},\"name\":\"default\"},\"spec\":{\"peers\":[{\"mtls\":{\"mode\":\"PERMISSIVE\"}}]}}\n"},"labels":{"operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.5.0"}}} (repeated 1 times)
to: (repeated 1 times)
Resource: "authentication.istio.io/v1alpha1, Resource=meshpolicies", GroupVersionKind: "authentication.istio.io/v1alpha1, Kind=MeshPolicy" (repeated 1 times)
Name: "default", Namespace: "" (repeated 1 times)
Object: &{map["apiVersion":"authentication.istio.io/v1alpha1" "kind":"MeshPolicy" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"authentication.istio.io/v1alpha1\",\"kind\":\"MeshPolicy\",\"metadata\":{\"annotations\":{},\"labels\":{\"release\":\"istio\"},\"name\":\"default\"},\"spec\":{\"peers\":[{\"mtls\":{\"mode\":\"PERMISSIVE\"}}]}}\n"] "creationTimestamp":"2020-01-29T19:54:38Z" "generation":'\x01' "labels":map["release":"istio"] "name":"default" "resourceVersion":"319450" "selfLink":"/apis/authentication.istio.io/v1alpha1/meshpolicies/default" "uid":"7c447b02-81e1-44c5-8b0c-9c44c9e59a55"] "spec":map["peers":[map["mtls":map["mode":"PERMISSIVE"]]]]]} (repeated 1 times)
for: "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found (repeated 1 times)

Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found (repeated 6 times)


clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system configured
clusterrole.rbac.authorization.k8s.io/istiod-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istiod-pilot-istio-system unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured

serviceaccount/istio-pilot-service-account created
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-galley configured
configmap/istio created
configmap/istio-sidecar-injector created
configmap/istio-validation created
configmap/pilot-envoy-config created
deployment.apps/istiod created
poddisruptionbudget.policy/istio-pilot created
horizontalpodautoscaler.autoscaling/istio-pilot created
service/istio-pilot created
service/istiod created




✘ Errors were logged during apply operation. Please check component installation logs above.

Error: failed to generate and apply manifests, error: errors were logged during apply operation
exit status 1


```

### PR DESCRIPTION
**Pull request by ayj**
The validatingwebhookconfiguration has historically had many problems
during install and uninstall. More and more logic has been added to
the control plane to migate the problem without complete success. This
PR takes the opposite approach. Here's how it works:

1- The validatingwebhookconfiguration YAML is added to the manifests
   applied directly by istioctl and the operator. istiod no longer
   creates the validatingwebhookconfiguration from a template in a
   configmap.

2- The initial failure policy has been changed to FAIL-OPEN. Any Istio
   configuration applied during install should not be blocked by
   istiod not being ready.

3- istiod will update the caBundle and change the failure policy to
   FAIL-CLOSED when it is validation endpoint is ready.

4- un-installed and re-installing istio will reset the failure policy
   back to FAIL-OPEN. The only requirement here is that the
   validatingwebhookconfiguration be applied earlier in the install
   sequence before Istio CRs.

5- Reverting back to FAIL-OPEN during an upgrade creates a small
   window where invalid configuration could be created. This may be
   undesirable for some production users. They can use a k8s overlay
   to modify the default failure policy in the
   validatingwebhookconfiguration YAML to FAIL-CLOSE.

fixes https://github.com/istio/istio/issues/20944
related: https://github.com/istio/istio/issues/18900#issuecomment-581558183

### CODE REVIEW

File: operator/pkg/manifest/installer.go [hunk 1]
```diff
@@ -495,39 +495,55 @@ func buildComponentApplyOutput(stdout string, stderr string, objects object.K8sO
...
+		case gk == "/ServiceAccount" || gk == "rbac.authorization.k8s.io/ClusterRole":
 			return 1
-		case "rbac.authorization.k8s.io/ClusterRoleBinding":
+		case gk == "rbac.authorization.k8s.io/ClusterRoleBinding":
 			return 2
 
-			// Validation webook maybe impact CRs applied later
-		case "admissionregistration.k8s.io/ValidatingWebhookConfiguration":
+			// install Istio API before we apply the validatingwebhookconfiguration
+		case istioCustomResourceDefinition(o.Group):
```
Comment (ayj) [inline operator/pkg/manifest/installer.go]: note to self: swap case 3 and 4 here so the webhook configuration is always installed first.

**Comment by howardjohn** [comment]
Sorry I haven't looked at the code yet, so this may be answered. Is this a problem:
* 1.4 has fail close
* We install 1.5, it is fail open
* 1.4 marks it as fail close
* some config breaks
* 1.5 install completes, marks it as fail close with new caBundle 

Or do we have a way to prevent 1.4 from making it fail close again? By pruning or the cluster override or what not?

**Comment by howardjohn** [comment]
Also, if we delete istio, will we need to manually delete the webhook? Is there any tricks we can (or you did) do?

**Comment by ayj** [comment]
- 1.4 uses istio-galley validatingwebhookconfiguration
- 1.5 uses istiod-istio-system validating webhookconfiguration
- 1.4 isn't aware of the 1.5 config. There shouldn't be a problem if we make this simplification between 1.4 and 1.5. The issue you described would be a problem if we pushed this simplification in 1.6 since both versions would try to update the same istiod-istio-system config.

> Also, if we delete istio, will we need to manually delete the webhook? Is there any tricks we can (or you did) do?

IMO the less trickery the better. Everything we've tried has  worked for some users but led to confusion for others. 

With this PR someone will need to delete the config during uninstall. This shouldn't be a problem in practice if we set the correct expectation.

The validatingwebhookconfiguration shouldn't cause any immediate problems if the user is completely removing Istio. They shouldn't be creating Istio CRs anyway. For a prestine uninstall they need to manually remove the other cluster-scoped resources as well (e.g. clusterrole, CRDs). If they use something like `kubectl delete -f <istio.yaml>` then the webhook config will be removed. If they manually delete the config nothing will re-create it. `istioctl uninstall` and the operator are better places to solve this problem IMO.

If the user is downgrading to 1.4 then will also need to manually uninstall the config. `istioctl downgrade` could help here. The only ways I could think of to make this work auto-magically wouldn't be reliable, e.g. users won't remove the istiod clusterrole. (they forget) or istio-system namespace (they can't since 1.4 is using it). We can document this as part of the downgrade instructions. Fortunately, nothing will automatically re-create the config when the user tries to delete it as was the case in <=1.4. 

Going forward downgrading from 1.6+ to 1.5 won't be a problem because applying the older version will reset the failure policy to FAIL-OPEN until Istio is ready to serve requests.

**Comment by howardjohn** [comment]
> The validatingwebhookconfiguration shouldn't cause any immediate problems if the user is completely removing Istio. They shouldn't be creating Istio CRs anyway. For a prestine uninstall they need to manually remove the other cluster-scoped resources as well (e.g. clusterrole, CRDs). If they use something like kubectl delete -f <istio.yaml> then the webhook config will be removed. If they manually delete the config nothing will re-create it. istioctl uninstall and the operator are better places to solve this problem IMO.

Good point, I forgot about this part. I agree with you, its good how it is.

I am still not quite sure on an upgrade to 1.5 how do we ensure that istio-galley validatingwebhookconfiguration either is deleted or is made a NOP, or points to the istiod deployment?

other than that question lgtm

**Comment by ayj** [comment]
> I am still not quite sure on an upgrade to 1.5 how do we ensure that istio-galley validatingwebhookconfiguration either is deleted or is made a NOP, or points to the istiod deployment?

We do three things today:

1) We remove Galley's permissions to update the webhook config.
2) We immediately apply the same no-op webhook to the cluster. 
3) We update the desired istio-galley validatingwebhookconfiguration in the configmap to be a no-op. Galley will try to use this updated config once it detects the change.

(1) and (2) likely sufficient for simple cases where the kube-apiserver isn't replicated (e.g. non-GKE regional clusters). Galley won't be able to revert (2) if (1) happens first.

(3) is an insurance policy. Galley won't be able to apply it if (1) is applied first.

A more robust method would include completely disabling Galley's reconciliation logic before the upgrade. Scaling the deployment to zero is one option. Reconfiguring Galley is another. Scaling down might be simplest.

**Comment by howardjohn** [comment]
Got it, looks good to me then. Needs a rebase though

File: operator/pkg/manifest/installer.go [hunk 2]
```diff
@@ -495,39 +495,56 @@ func buildComponentApplyOutput(stdout string, stderr string, objects object.K8sO
...
+		"security.istio.io",
+		"authentication.istio.io",
+		"networking.istio.io":
+		return true
+	}
+	return false
+}
+
 // DefaultObjectOrder is default sorting function used to sort k8s objects.
 func DefaultObjectOrder() func(o *object.K8sObject) int {
```
[the remark this answers is not in the document]
Comment (ayj) [reply operator/pkg/manifest/installer.go]: https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#organizing-resource-configurations

kubectkl will be created in the order they appear in the file.

[the remark this answers is not in the document]
Comment (howardjohn) [reply operator/pkg/manifest/installer.go]: Wow, I am very surprised by this. Well, I am surprised they recommend it rather, since even if its in order its still eventually consistent so I am surprised it has a real impact. Thanks for the reference

**Comment by ayj** [comment]
I need to manually cherry-pick this change into 1.5 since galley manifests in master have diverged.

**Review by howardjohn — APPROVED** [review]

**Comment by ayj** [comment]
I updated the webhook integration test and needed to add a helper function to the test framework. This now requires T&R approval.

**Comment by howardjohn** [comment]
My approval retroactively applies for T&R. Ill take a lookat the changes though as well

File: tests/integration/galley/webhook_test.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+			if err := verifyValidatingWebhookConfiguration(got); err != nil {
+				t.Fatal(err)
+			}
+
+			// clear the updated fields and verify istiod updates them
+			updated := got.DeepCopyObject().(*kubeApiAdmission.ValidatingWebhookConfiguration)
+			updated.Webhooks[0].ClientConfig.CABundle = nil
+			updated.Webhooks[0].FailurePolicy = &([]kubeApiAdmission.FailurePolicyType{kubeApiAdmission.Ignore}[0])
+
+			if err := env.UpdateValidatingWebhookConfiguration(updated); err != nil {
```
Comment (howardjohn) [inline tests/integration/galley/webhook_test.go]: nit: is there any race here where it will fail because the resourceVersion doesn't match if the controller is modifying it concurrently? And if there is, is it common enough we  need a workaround?

File: tests/integration/galley/webhook_test.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+				t.Fatalf("error getting initial webhook: %v", err)
+			}
+			if err := verifyValidatingWebhookConfiguration(got); err != nil {
+				t.Fatal(err)
+			}
+
+			// clear the updated fields and verify istiod updates them
+			updated := got.DeepCopyObject().(*kubeApiAdmission.ValidatingWebhookConfiguration)
+			updated.Webhooks[0].ClientConfig.CABundle = nil
+			updated.Webhooks[0].FailurePolicy = &([]kubeApiAdmission.FailurePolicyType{kubeApiAdmission.Ignore}[0])
```
Comment (howardjohn) [inline tests/integration/galley/webhook_test.go]: Is this some weird hack around `&kubeApiAdmission.Ignore` not working?

File: tests/integration/galley/webhook_test.go [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+
+			if err := env.UpdateValidatingWebhookConfiguration(updated); err != nil {
+				t.Fatalf("could not clear reconciled fields in config: %v", err)
+			}
+
+			timeout := time.After(30 * time.Second)
```
Comment (howardjohn) [inline tests/integration/galley/webhook_test.go]: nit: you could use retry.UntilSuccess here I think

**Review by howardjohn — APPROVED** [review]
test changes lgtm just a few tiny comments

File: tests/integration/galley/webhook_test.go (hunk 3 above)
Comment (ayj) [reply tests/integration/galley/webhook_test.go]: Good point. I wrapped it in a retry.UntilSuccess.

File: tests/integration/galley/webhook_test.go (hunk 4 above)
Comment (ayj) [reply tests/integration/galley/webhook_test.go]: Yes. I replaced with the simpler and more obvious equivalent

File: tests/integration/galley/webhook_test.go (hunk 5 above)
Comment (ayj) [reply tests/integration/galley/webhook_test.go]: done

**Comment by ayj** [comment]
TestClientSink  flake

/retest
