### PR TITLE
Avoid unnecesary service target logs

### LINKED ISSUE #57103: Istio generates spam logs when using ServiceEntry selecting pods
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Whenever using ServiceEntry selection Pods and not using Services at all, istio generates the following logs:
```
2025-07-22T15:20:14.754812Z     warn    kube    GetProxyServiceTargetsFromMetadata for X failed: no instances found for X
```

For every pod that needs pushing Istio attempts to find the service targets using `aggregate.GetProxyServiceTargets`, this ends up calling the same method on every service controller, this includes standard kube controllers. These standard kube controllers [log a warning](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/controller.go#L887) whenever [they don't find a matching service for the proxy](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/controller.go#L1014), but in a context of using ServiceEntry these logs don't really make sense since we don't even expect services to be present for the proxies.

It should probably be better to just remove this log, pull it into aggregate controller or make it only log whenever `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` is disabled.

### Version

```Text
1.22.5
```

### Additional Information

Disabling `warn` logs on scope `kube` is an option, but it also disable other logs that I think are important.

### PR DESCRIPTION
**Pull request by sschepens**
**Please provide a description of this PR:**
Avoids unnecessary missing service target logs whenever `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` is enabled.
Fixes #57103

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 1]
```diff
@@ -883,7 +883,7 @@ func (c *Controller) GetProxyServiceTargets(proxy *model.Proxy) []model.ServiceT
 		// If we cannot accurately construct ServiceEndpoints from just the metadata, this will return an error and we can
 		// attempt to read the real pod.
 		out, err := c.GetProxyServiceTargetsFromMetadata(proxy)
-		if err != nil {
+		if err != nil && !features.EnableServiceEntrySelectPods {
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller.go]: I think this is not completely correct to skip this based on this feature flag. This may be needed for regular services. It might be better to move this to aggregate controller and possibly change to debug?

Comment (sschepens) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: @ramaraochavali  this is not directly movable to aggregate, because this checks for an "internal" error, this error does not bubble up to aggregate controller because `GetProxyServiceTargets` does not return errors.
On aggregate controller the only thing we can really check is if we haven't got any `ServiceTargets` from the service controllers, but I don't think that should be an error, even kube service controller can return an empty slice of ServiceTargets without returning an error if it finds services but no matching target within them.

Comment (ramaraochavali) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: Here also we throwing error based on instance count only right? We can log a debug message in aggregate controller based on instance count or converr this to debug message?

Comment (sschepens) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: done, let me know what you think

**Review by ramaraochavali — APPROVED** [review]
Thank you
