### PR TITLE
multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array

### LINKED ISSUE #54820: Istio require istio-cni NetworkAttachmentDefinition reside in 'default' namespace
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Hello, 

I am trying to spin up a pod connecting it to Istio mesh and to an additional secondary network (using Multus).
Specifying the following Multus network selection annotation in the pod yaml:
```
    k8s.v1.cni.cncf.io/networks: br-net
```
The pod fails to created with the following related event:
```
  Warning  FailedCreatePodSandBox  0s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_pod1_test_8420b697-beef-4ef7-bacf-a76859c088db_0(bf2e66a91011a67af49f966f1aaa5229c40fe70a82515ec6922a4fc63e32f445): error adding pod test_pod1 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): Multus: [test/pod1]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: cannot find a network-attachment-definition (istio-cni) in namespace (default): network-attachment-definitions.k8s.cni.cncf.io "istio-cni" not found
```
Looking into the pod state we see the networks annotation has `default/istio-cni`, instead of `istio-cni` (w/o the default namespace).

This  behavior firstly introduced on istio-1.19 [[1]](https://github.com/istio/istio/commit/a0f89a9d06f4d123d9410df6bfa499ee072afe26).

Multus consider the default namespaces as a "global namespaces", meaning an pod in the cluster can connect to a `NetworkAttachmentDefinition` reside in the default namespace [[2]](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/configuration.md#allow-specific-namespaces-to-be-used-across-namespaces-when-using-namespace-isolation).

Previous versions,v1.18 and  below, used to append `istio-cni` w/o the namespace name.
Allowing isolation between different namespaces.

[1] https://github.com/istio/istio/commit/a0f89a9d06f4d123d9410df6bfa499ee072afe26
[2] https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/configuration.md#allow-specific-namespaces-to-be-used-across-namespaces-when-using-namespace-isolation

### Version

```Text
$ ./istioctl version 
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (3 proxies)
$ kubectl version 
selecting podman as container runtime
Client Version: v1.30.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.8
```

### Additional Information

The env is k8s-1.30 cluster, it has Calico as default CNI, Multus CNI and istio 1.23.4.
The same behavior occurs using istio versions 1.24-1.19.

I couldn't find istio-cni NAD has to reside in default namespaces in the docs.

### Affected product area

- [ ] Ambient
- [x] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by yskopets**
Fixes #54820

**Please provide a description of this PR:**

Fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array.

### CODE REVIEW

**Comment by zirain** [comment]
@yskopets I think this need to backport?

**Comment by yskopets** [comment]
@zirain yes, we would like to back port it

**Comment by zirain** [comment]
1.22 is EOL, remove it.

**Review by zirain — APPROVED** [review]
LGTM

**Comment by yskopets** [comment]
I tested this patch on `Istio 1.22`.

The issue in longer reproducible and Istio CNI works successfully.

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM

Can you also update the test file hello-existing-cncf-networks-json.yaml to include namespace

**Comment by yskopets** [comment]
@hzxuzhonghu done

File: pkg/kube/inject/template.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ import (
 	"google.golang.org/protobuf/types/known/durationpb"
 	corev1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	kstrings "k8s.io/utils/strings"
```
Comment (bleggett) [inline pkg/kube/inject/template.go:30]: nit: Do we really need a new import for a 5 line string util func?

https://github.com/kubernetes/utils/blob/24370beab75816ab1d2b33fba9e288ee667530dd/strings/strings.go#L26

File: pkg/kube/inject/template.go [hunk 2]
```diff
@@ -195,12 +196,25 @@ func appendMultusNetwork(existingValue, istioCniNetwork string) string {
 			log.Warnf("Unable to unmarshal Multus Network annotation JSON value: %v", err)
 			return existingValue
 		}
+		istioCniNetworkNs, istioCniNetworkName := kstrings.SplitQualifiedName(istioCniNetwork)
 		for _, net := range networks {
-			if net["name"] == istioCniNetwork {
-				return existingValue
+			if net["name"] == istioCniNetworkName {
+				ns := net["namespace"]
```
Comment (bleggett) [inline pkg/kube/inject/template.go:202]: nit:

this reads a little easier if the comparison is `if ns["namespace"] == istioCniNetworkNs`

If the `nil` check is critical, then `if ns := ns["namespace"]; ns != nil && ns == istioCniNetworkNs`

File: pkg/kube/inject/template.go [hunk 3]
```diff
@@ -195,12 +196,25 @@ func appendMultusNetwork(existingValue, istioCniNetwork string) string {
 			log.Warnf("Unable to unmarshal Multus Network annotation JSON value: %v", err)
 			return existingValue
 		}
+		istioCniNetworkNs, istioCniNetworkName := kstrings.SplitQualifiedName(istioCniNetwork)
```
Comment (ormergi) [inline pkg/kube/inject/template.go:199]: I think it worth adding unit tests to have coverage for this chage

Comment (dgn) [reply pkg/kube/inject/template.go:199]: what case is missing? for me the testdata looks like it covers exactly what you're describing in the issue

**Review by dgn — APPROVED** [review]

**Comment by jewertow** [comment]
@hzxuzhonghu could you approve it now? We also need this fix.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by jewertow** [comment]
@yskopets could you rebase the PR or push an empty commit to trigger `windowsbuildcheck_istio`?
