### PR TITLE
don't elide the connmark rule when ingressmode is enabled

### LINKED ISSUE #58546: Ambient Mode ambient.istio.io/bypass-inbound-capture annotation breaks for mesh workloads (breaks with mesh workload + works with non-mesh callers only)
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

In Istio Ambient Mode, it is currently impossible for a pod to accept traffic from both:

Mesh workloads → which send mTLS-encrypted traffic (all outbound is intercepted by ztunnel)

Non-mesh workloads → which send plaintext HTTP traffic

The reason is:

Ambient bypass inbound capture ON → only non-mesh i accepted; mtls callers fail

ambient.istio.io/bypass-inbound-capture: "true" → disables all inbound capture; mesh callers fail (mTLS cannot be decrypted)

Sidecar-mode annotations such as
traffic.istio.io/exclude-inbound-ports
have no effect in Ambient Mode, so port-level selective bypass is not possible.

This results in a situation where:

A pod cannot simultaneously serve plaintext on one port (for non-mesh) and mTLS on another port (for mesh workloads)

The only current workaround is duplicating the deployment or disabling Ambient for the workload entirely.

This is a functional limitation that breaks Prometheus scraping, internal health checks, and mixed-mode workloads when migrating incrementally to Ambient.

### Version

```Text
istio:
client version: 1.28.0
control plane version: 1.28.0
data plane version: 1.28.0

Client Version: v1.32.0
Kustomize Version: v5.4.2
Server Version: v1.32.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ilrudie**
**Please provide a description of this PR:**

fixes #58546

supersedes #58564

This PR changes the behavior of setting `ambient.istio.io/bypass-inbound-capture: "true"` so that the inbound (HBONE on 15008) listener still functions correctly. Presently when bypass in enabled we elide the connmark rule, this causes inbound hbone traffic to timeout because we don't correctly handle the ztunnel mark. 

With the PR, "inbound hbone" works as expected and "inbound passthrough" traffic continues to completely bypass ztunnel, optimizing for the 3rd party ingress use case.

### CODE REVIEW

**Comment by ilrudie** [comment]
cc @jaellio, @sridhargaddam @howardjohn @stevenctl @keithmattix for thoughts

**Comment by howardjohn** [comment]
ah good, tests do fail

File: cni/pkg/iptables/iptables.go [hunk 1]
```diff
@@ -275,15 +275,15 @@ func (cfg *IptablesConfigurator) AppendInpodRules(podOverrides config.PodLevelOv
...
-		//
-		// DESC: If we have a packet mark, set a connmark.
-		iptablesBuilder.AppendRule(ChainInpodPrerouting, "mangle", "-m", "mark",
-			"--mark", inpodMark,
-			"-j", "CONNMARK",
-			"--set-xmark", inpodTproxyMark)
+	// CLI: -A ISTIO_PRERT -m mark --mark 0x539/0xfff -j CONNMARK --set-xmark 0x111/0xfff
+	//
+	// DESC: If we have a packet mark, set a connmark.
+	iptablesBuilder.AppendRule(ChainInpodPrerouting, "mangle", "-m", "mark",
```
Comment (sridhargaddam) [inline cni/pkg/iptables/iptables.go:281]: Thanks @ilrudie for the fix! We would need a similar change in the nftables code as well [here](https://github.com/istio/istio/blob/513e752759ef71a807115011c70de80fb3ad91c2/cni/pkg/nftables/nftables.go#L202). Can you include the nftables changes as well? Happy to help if needed.

Comment (ilrudie) [reply cni/pkg/iptables/iptables.go:281]: Thanks for the info. I'll take a look and be in touch if I need.

Comment (ilrudie) [reply cni/pkg/iptables/iptables.go:281]: @sridhargaddam, I think the nft bit is done and looking ok now. Can you double check an lmk before we merge this though? tyia
