### PR TITLE
Fix EnvoyFilter listener portNumber match

### LINKED ISSUE #19549: EnvoyFilter inbound doesn't work
**Bug description**

adding this config doesn't work

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-calling-service-inbound
spec:
  workloadSelector:
    labels:
      app: echo-ping
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       config:
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:headers():add("x-foo", "bar")
           end
```

**Expected behavior**

Lua code will be called for every incoming service call. 

**Steps to reproduce the bug**

apply the filter and check headers on the receiving end 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$> istioctl version
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (3 proxies)

$> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl manifest apply`

**Environment where bug was observed (cloud vendor, OS, etc)**

`microk8s`

[istio-dump.tar.gz](https://github.com/istio/istio/files/3956042/istio-dump.tar.gz)

Thanks in advance

### PR DESCRIPTION
**Pull request by waynz0r**
This PR is proposed solution for `portNumber` matching in EnvoyFilters for `virtualInbound` and `virtualOutbound` listeners.

We are writing several WASM filters and in our testing we've found that the `portNumber` filter specified for the listener match in the `EnvoyFilter` custom resource isn't properly handled right now, resulting in the hooks not being invoked on our filter.

The proposed fix has been applied and tested in our own Istio environment at Banzai Cloud and seem to be working fine, let me know if this is acceptable going upstream or there are proposed changes. Also I am about to make a test as well.

Fixes #19549

[x] Networking

### CODE REVIEW

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go [hunk 1]
```diff
@@ -33,6 +33,14 @@ import (
 	"istio.io/istio/pilot/pkg/util/runtime"
 )
 
+const (
+	// VirtualOutboundListenerName is the name for traffic capture listener
+	VirtualOutboundListenerName = "virtualOutbound"
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go:38]: These are already defined in `listener.go`. Please use them rather than redefining here

Comment (waynz0r) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go:38]: Unfortunately is not possible right now, the `envoyfilter` package is imported in `v1alpha3` where `listener.go` is.

Comment (waynz0r) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go:38]: However, I can remove them from `listener.go` and use it from `envoyfilter` package in `v1alpha3`.

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go [hunk 2]
```diff
@@ -527,6 +542,14 @@ func filterChainMatch(fc *xdslistener.FilterChain, cp *model.EnvoyFilterConfigPa
 			return false
 		}
 	}
+
+	// check match for destination port within the FilterChainMatch
+	if cMatch.PortNumber > 0 &&
+		fc.FilterChainMatch != nil && fc.FilterChainMatch.DestinationPort != nil &&
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go:548]: nit: proto generated libraries add `.GetX` which will allow chaining of `nil` fields like `fc.GetFilterChainMatch().GetDestinationPort().GetValue()`
