### PR TITLE
remove TESTONLY tars, daily builds point to gcr.io

### LINKED ISSUE #2904: Remove TESTONLY artifacts, and make istioctl work out of the box for pre-releases
Having two sets of tar balls and istioctl directories is problematic. 
More context: https://groups.google.com/forum/#!topic/istio-dev/qo13rpC2FiA

1. It is confusing and people often picks up the wrong one.
2. The artifacts that we are releasing does not work out of the box.
3. People are testing different artifacts that the one we are releasing.

Instead, can we just push pre-releases also to docker hub, and make pre-release istioctl work out of the box?

### PR DESCRIPTION
**Pull request by rkpagadala**
fixes #2904

### CODE REVIEW

File: release/publish_release.sh [hunk 1]
```diff
@@ -220,8 +220,8 @@ if [[ -n "${GCS_SOURCE}" ]]; then
     gsutil -m cp "gs://${GCS_SOURCE}/manifest.xml" "${UPLOAD_DIR}/"
   fi
   if [[ "${DO_GITHUB_REL}" == "true" ]]; then
-    gsutil -m cp "gs://${GCS_SOURCE}/istio*.zip" "${UPLOAD_DIR}/"
-    gsutil -m cp "gs://${GCS_SOURCE}/istio*.gz"  "${UPLOAD_DIR}/"
+    gsutil -m cp "gs://${GCS_SOURCE}/docker.io/istio*.zip" "${UPLOAD_DIR}/"
```
Comment (mattdelco) [inline release/publish_release.sh]: Now that the "-" and "_" has been made uniform it could be worthwhile to add a "-" after "istio" in case somebody adds more files that they didn't intend to get published to github.  There's a similar story for the "for FILE in ${2}/istio*.${4}" line in release/create_github_release.sh.

**Comment by ldemailly** [comment]
want to update the wiki after the first of those such build show up ?

**Comment by rkpagadala** [comment]
@ldemailly I will update the wiki
