### PR TITLE
set USER env varible

### LINKED ISSUE #2230: postsubmit failure on "user: Current not implemented on linux/amd64"
See: https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/242
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2225/e2e-smoke/808/

Several tests failed due to the same error: `user: Current not implemented on linux/amd64`. This would mean that the Go runtime on prow are built without cgo, and some info are missing: https://github.com/golang/go/blob/master/src/os/user/lookup_stubs.go#L21

Those tests want to get the current user's home directory for finding the kubernetes config file (typically in `~/.kube/config`).

The code has been there for a while, so this is very rare, but we should minimize its effect.

### PR DESCRIPTION
**Pull request by yutongz**
fixes #2230

### CODE REVIEW

File: prow/e2e-suite.sh [hunk 1]
```diff
@@ -27,6 +27,8 @@ set -u
 set -x
 
 if [ "${CI:-}" == 'bootstrap' ]; then
+  export USER=Prow
```
Comment (jmuk) [inline prow/e2e-suite.sh]: What will happen if `$CI` isn't `bootstrap`? Does it inherit `$USER` for some cases?

Comment (yutongz) [reply prow/e2e-suite.sh]: These scripts are mainly for Prow, so the CI would be set to `bootstrap`. Otherwise, when people run these scripts on their own machine, we don't want to override the USER there.

Comment (jmuk) [reply prow/e2e-suite.sh]: ah, I see. It's always set to be bootstrap on prow. Thanks for the info.
