### PR TITLE
Operator: Fix webhooks reconciled by operator are inconsistent with istioctl install's

### LINKED ISSUE #43893: `istiod-default-validator` missing if use operator installed istio
### Bug Description

The operator and istioctl do not have the same behavior for processing validatingwebhookconfigurations during installation

These logics missing in opetator logic:

https://github.com/istio/istio/blob/c919dbeb67423e148625969488f3654f5caf5286/operator/cmd/mesh/install.go#L204-L225

### Version

```prose
master
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/43893

### CODE REVIEW

**Comment by hanxiaop** [comment]
@istio/wg-environments-maintainers PTAL, thanks

File: operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go [hunk 1]
```diff
@@ -407,6 +414,130 @@ func (r *ReconcileIstioOperator) Reconcile(_ context.Context, request reconcile.
...
+				return false, err
+			}
+		}
+		processed = true
+	}
+	return processed, nil
+}
+
+func applyManifests(kubeClient kube.CLIClient, manifests string) error {
+	yamls := strings.Split(manifests, "---")
```
Comment (kebe7jun) [inline operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go:448]: use Separator instead?

File: releasenotes/notes/43897.yaml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+apiVersion: release-notes/v2
+kind: bug-fix
+area: installation
+issue:
+  - 43893
+releaseNotes:
+  - |
+    **Fixed** `ValidatingWebhookConfiguration` is not generated correctly with operator installation when the revision is not set.
```
Comment (dhawton) [inline releasenotes/notes/43897.yaml:8]:
```suggestion
    **Fixed** `ValidatingWebhookConfiguration` not being generated correctly with operator installation when the revision is not set.
```

**Comment by kebe7jun** [comment]
@istio/wg-environments-maintainers PTAL, thanks, looking forward to this fix.

**Comment by hanxiaop** [comment]
not stale

File: operator/cmd/mesh/install.go [hunk 3]
```diff
@@ -190,38 +189,14 @@ func Install(rootArgs *RootArgs, iArgs *InstallArgs, logOpts *log.Options, stdOu
...
 	iop, err = InstallManifests(iop, iArgs.Force, rootArgs.DryRun, kubeClient, client, iArgs.ReadinessTimeout, l)
 	if err != nil {
 		return fmt.Errorf("failed to install manifests: %v", err)
 	}
-
-	if !operatorManageWebhooks && (!exists || isDefaultInstallation) {
+	if processed, err := istiocontrolplane.ProcessDefaultWebhook(kubeClient, iop, ns); err != nil {
+		return fmt.Errorf("failed to process default webhook: %v", err)
+	} else if processed {
 		p.Println("Making this installation the default for injection and validation.")
```
Comment (howardjohn) [inline operator/cmd/mesh/install.go:199]: nit: technically we already made it the default at this point, but we say we are "Making..."

File: operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go [hunk 4]
```diff
@@ -407,6 +414,130 @@ func (r *ReconcileIstioOperator) Reconcile(_ context.Context, request reconcile.
...
+func processDefaultWebhookAfterReconcile(iop *iopv1alpha1.IstioOperator, client kube.Client) error {
+	var ns string
+	if configuredNamespace := iopv1alpha1.Namespace(iop.Spec); configuredNamespace != "" {
+		ns = configuredNamespace
+	} else {
+		ns = constants.IstioSystemNamespace
+	}
+	rc := client.RESTConfig()
+	// operator controller requires high privileges, so can use the CLIClient to apply yamls.
+	kubeClient, err := kube.NewCLIClient(kube.NewClientConfigForRestConfig(rc), "")
```
Comment (howardjohn) [inline operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go:512]: I don't think this makes sense. Note `kube.Client` and `kube.CLIClient` are the same struct under the hood, just different interfaces to prevent things like Istiod from using functions it should not.

This code is actually making a new client, which is a new connection to api-server, etc. And possibly many times.

Probably we can just make it use a CLIClient by updating `Add` to make the new cli client instead.

Comment (hanxiaop) [reply operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go:512]: Thanks for reviewing this. I think `kube.CLIClient` is no longer needed here. Originally, it was used for applying tag webhook YAMLs with `ApplyYAMLFiles`. However, the operator is read-only, which means the creation of webhook yamls before applying will fail. As a result, I revised the process to use the client to create the configs. I'm going to revise the client usage.

File: releasenotes/notes/43897.yaml (hunk 2 above)
Comment (hanxiaop) [reply releasenotes/notes/43897.yaml]: Fixed, thanks

File: tests/integration/pilot/webhook_test.go [hunk 5]
```diff
@@ -83,8 +83,10 @@ func TestWebhook(t *testing.T) {
 			if t.Settings().Revisions.Default() != "" {
 				revision = t.Settings().Revisions.Default()
 			}
-			verifyRejectsInvalidConfig(t, revision, true)
-			verifyRejectsInvalidConfig(t, "", true)
+			if !cluster.IsRemote() {
```
[the remark this answers is not in the document]
Comment (hanxiaop) [reply tests/integration/pilot/webhook_test.go]: I was thinking the remote cluster didn't need to test validation, since if I didn't specify remote cluster, `integ-pilot-istiodremote_istio` and `integ-pilot-istiodremote-mc_istio` failed with TestValidation function.

[the remark this answers is not in the document]
Comment (howardjohn) [reply tests/integration/pilot/webhook_test.go]: I think we should still have validation in these modes. The test may be testing the wrong thing but we should have _some_ validation. Not an expert here though

File: istioctl/pkg/tag/generate.go [hunk 6]
```diff
@@ -269,6 +270,10 @@ istiodRemote:
 		decodedWh.Name = webhookName
 	}
 
+	for k, v := range config.Labels {
+		decodedWh.Labels[k] = v
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:274]: Just curious what prompted adding this? Seems like a good idea just wasn't sure the motvation. Wondering if annotations are useful as well

Comment (howardjohn) [reply istioctl/pkg/tag/generate.go:274]: can `decodedWh.Labels` ever be nil?

File: operator/pkg/helmreconciler/reconciler.go [hunk 7]
```diff
@@ -581,3 +587,100 @@ func (h *HelmReconciler) networkName() string {
...
+		if obj.GetKind() == name.MutatingWebhookConfigurationStr {
+			ogvr = gvr.MutatingWebhookConfiguration
+		} else if obj.GetKind() == name.ValidatingWebhookConfigurationStr {
+			ogvr = gvr.ValidatingWebhookConfiguration
+		}
+
+		_, err := kubeClient.Dynamic().Resource(ogvr).Namespace(obj.GetNamespace()).Patch(
+			context.TODO(), obj.GetName(), types.ApplyPatchType, []byte(yml), metav1.PatchOptions{
+				Force:        nil,
+				FieldManager: "install",
```
Comment (howardjohn) [inline operator/pkg/helmreconciler/reconciler.go:643]: For consistency with other objects we may want to use https://github.com/istio/istio/blob/d0705cf0ed5591cc26c08001f3faab0a880aec48/operator/pkg/helmreconciler/apply.go#L36?

**Review by howardjohn — APPROVED** [review]

File: tests/integration/pilot/webhook_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (howardjohn) [reply tests/integration/pilot/webhook_test.go]: cc @frankbu

[the remark this answers is not in the document]
Comment (frankbu) [reply tests/integration/pilot/webhook_test.go]: I can't see how `IsRemote()` would ever return true here, since this test is skipped for anything other than a single primary cluster topology: https://github.com/istio/istio/blob/f5a906e02c64c38500afc2d231c2f74d9ac36574/tests/integration/pilot/webhook_test.go#L40

That said, I think that maybe it could/should also be run in the istiodremote topology. In that case I think the check might need to be `if cluster.IsConfig()` instead of `if !cluster.IsRemote()`

[the remark this answers is not in the document]
Comment (hanxiaop) [reply tests/integration/pilot/webhook_test.go]: Thanks for the help, I'm going to look into it and have a try

File: istioctl/pkg/tag/generate.go (hunk 6 above)
Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:274]: > can `decodedWh.Labels` ever be nil?

It should not be nil since it has the tag label already, but I think it's better to add the nil check to prevent potential panic.

> Just curious what prompted adding this? Seems like a good idea just wasn't sure the motvation. Wondering if annotations are useful as well

I found that the uninstallation process for the operator is slightly different from istioctl, which requires specific labels. Then, I realized that the labels of the deactivated webhook are not consistent with the generated one. I think it's also a good idea to add the annotation, but I'm not sure if it is useful for the webhook mechanism though.

File: tests/integration/pilot/webhook_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (hanxiaop) [reply tests/integration/pilot/webhook_test.go]: Not sure if the clusters' orders will change here, but after I revised `t.Clusters().Default()` (first cluster in the list) to explicitly be the config cluster, the tests passed.

**Comment by hanxiaop** [comment]
@howardjohn Could you please take another look, particularly at the last commit https://github.com/istio/istio/pull/43897/commits/788e15b926428c209bb5fc0f69b50eed15166222? In this commit, I added some logic to prevent the operator from pruning the generated webhook resources, as it's not present in the manifest map. Without this change, the generated webhook would be pruned during a new reconciliation cycle. I'm not pretty sure if this approach to resource ignoring is optimal. Aside from this, the rest of the code remains largely unchanged from before.

File: istioctl/pkg/tag/generate.go [hunk 8]
```diff
@@ -309,13 +334,22 @@ func tagWebhookConfigFromCanonicalWebhook(wh admitv1.MutatingWebhookConfiguratio
 		return nil, fmt.Errorf("could not find sidecar-injector webhook in canonical webhook %q", wh.Name)
 	}
 
+	filteredLabels := make(map[string]string)
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:337]: can we comment why we filter these?

File: operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go [hunk 9]
```diff
@@ -402,6 +410,27 @@ func (r *ReconcileIstioOperator) Reconcile(_ context.Context, request reconcile.
...
 
+func processDefaultWebhookAfterReconcile(iop *iopv1alpha1.IstioOperator, client kube.Client, exists bool) error {
+	var ns string
+	if configuredNamespace := iopv1alpha1.Namespace(iop.Spec); configuredNamespace != "" {
+		ns = configuredNamespace
+	} else {
+		ns = constants.IstioSystemNamespace
+	}
+	ignorePruneLabel := map[string]string{
+		helmreconciler.OwningResourceNotPruned: "true",
```
Comment (howardjohn) [inline operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go:421]: why don't we prune this one? seems like this logic only applies to in-cluster operator as well - is that expected? 

since part of the goal was to make them consistent, we should probably comment in the code why we are inconsistent here?

Comment (hanxiaop) [reply operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go:421]: > why don't we prune this one

Other installed manifests are not pruned since here the manifests are being excluded for pruning. https://github.com/istio/istio/blob/9b7c62b698cd2ac8a7db4e5578e7c820265e3ac2/operator/pkg/helmreconciler/prune.go#L125

https://github.com/istio/istio/blob/9b7c62b698cd2ac8a7db4e5578e7c820265e3ac2/operator/pkg/helmreconciler/prune.go#L426

However the generated webhooks are not in the manifest list, as a result, if operator is doing a new reconcilation cycle, it will perform like `deleting generated webhooks -> watch a deletion event and trigger new iop reconcile -> install generated webhooks again -> deleting generated webhooks...` forever. 

> seems like this logic only applies to in-cluster operator as well - is that expected

This is expected, istioctl uninstall or IOP CR deletion are same as before, this is only to prevent webhooks being pruned during new reconcilation cycles like other installed resources.

Will add some comments.

File: istioctl/pkg/tag/generate.go (hunk 8 above)
Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:340]: Added.

**Comment by hanxiaop** [comment]
@istio/wg-user-experience-maintainers PTAL, thanks

File: istioctl/pkg/tag/generate.go [hunk 10]
```diff
@@ -214,9 +221,22 @@ base:
...
 
+func mergeMaps(m1, m2 map[string]string) map[string]string {
+	if m1 == nil {
+		return m2
+	}
+	if m2 == nil {
+		return m1
+	}
+	for k, v := range m2 {
+		m1[k] = v
```
Comment (GregHanson) [inline istioctl/pkg/tag/generate.go:232]: does precedence matter here? if there is overlap between m1 and m2, m2 overrides m1.  Or maybe just renaming the function inputs to something like `base` and `override` to make it clear?

Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go]: Thanks, revised. `base` and `override` are much better.

**Review by GregHanson — APPROVED** [review]

**Comment by triffer** [comment]
@hanxiaop 
Hi,
I saw that this has not been merged with 1.18 yet. Will this be merged to 1.18 and released in an upcoming version?
