### PR TITLE
fix TestZtunnelCRL race by checking workload enrollment before testing

### LINKED ISSUE #59677: TestZtunnelCRL has intermittent failure
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

The TestZtunnelCRL test has a timing issue which will cause it to fail.

```
=== RUN   TestZtunnelCRL
2026-03-30T22:42:53.389221Z	info	tf	=== BEGIN: Test: 'ambient_crl[TestZtunnelCRL]' ===
    crl_test.go:59: testing initial call before CRL update
    crl_test.go:61: initial call succeeded
    crl_test.go:64: revoking intermediate certificate
    crl_test.go:64: CRL updated successfully with revoked intermediate certificate
    crl_test.go:67: waiting for ztunnel to reload CRL...
    crl_test.go:67: ztunnel CRL reload confirmed via logs
2026-03-30T22:42:53.547374Z	info	tf	=== BEGIN: Create namespace ambient-client-revoked ===
2026-03-30T22:42:53.549455Z	info	tf	=== SUCCEEDED: Create namespace ambient-client-revoked in 2.07565ms ===
2026-03-30T22:42:53.549479Z	info	tf	=== BEGIN: Create namespace ambient-server-revoked ===
2026-03-30T22:42:53.551746Z	info	tf	=== SUCCEEDED: Create namespace ambient-server-revoked in 2.262148ms ===
2026-03-30T22:42:53.569623Z	info	tf	=== BEGIN: Deploy echo instances ===
2026-03-30T22:42:53.589305Z	info	klog	Waiting for caches to sync	controller=echo
2026-03-30T22:42:53.591190Z	info	klog	Waiting for caches to sync	controller=echo
2026-03-30T22:42:53.596101Z	info	sync complete	name=pod controller attempt=3 time=6.75383ms
2026-03-30T22:42:53.597879Z	info	sync complete	name=pod controller attempt=3 time=6.66647ms
2026-03-30T22:42:53.689517Z	info	klog	Caches are synced	controller=echo
2026-03-30T22:42:53.691652Z	info	klog	Caches are synced	controller=echo
2026-03-30T22:42:56.795221Z	info	tf	=== SUCCEEDED: Deploy echo instances in 3.225589976s ===
    crl_test.go:100: testing call with revoked apps, expecting failure
    crl_test.go:102: failed calling ambient-client-revoked (cluster=cluster-0)->'http://ambient-server-revoked.ambient-server-revoked-4-73306.svc.cluster.local:80': call failed from ambient-client-revoked (cluster=cluster-0) to http://ambient-server-revoked.ambient-server-revoked-4-73306.svc.cluster.local:80 (using http): expected error, but none occurred
2026-03-30T22:43:26.796298Z	info	tf	=== DONE (failed):  Test: 'ambient_crl[TestZtunnelCRL] (33.407073351s)' ===
```

### Version

```Text
master (1.30) and 1.29
```

### Additional Information

The ztunnel logs show the timing issue:

the crl is properly reloaded but the client attempts to access the server before its enrolled:
```
2026-03-30T22:42:39.165551Z	debug	tls::crl	crl directory events detected	event_count=1
2026-03-30T22:42:39.165566Z	debug	tls::crl	crl directory changed, reloading	
2026-03-30T22:42:39.165615Z	debug	tls::crl	crl loaded successfully	path="/var/run/secrets/istio/crl/ca-crl.pem" format="PEM" count=2
2026-03-30T22:42:39.165623Z	debug	tls::crl	crl reloaded successfully after file change
....
2026-03-30T22:42:53.398743Z	info	http access	request complete	src.addr=10.244.1.117:58606 src.workload="ambient-client-v1-6dd7bbd87f-nplg4" src.namespace="ambient-client-2-25282" src.identity="spiffe://cluster.local/ns/ambient-client-2-25282/sa/ambient-client" dst.addr=10.244.1.118:15008 dst.hbone_addr=10.244.1.118:8080 dst.service="ambient-server.ambient-server-1-42887.svc.cluster.local" dst.workload="ambient-server-v1-5646c68cf-g4tfl" dst.namespace="ambient-server-1-42887" dst.identity="spiffe://cluster.local/ns/ambient-server-1-42887/sa/ambient-server" direction="inbound" method=GET path="/" protocol=HTTP1 response_code=200 host="ambient-server.ambient-server-1-42887.svc.cluster.local" user_agent="go-http-client/1.1" duration="0ms"
2026-03-30T22:42:53.399054Z	info	access	connection complete	src.addr=10.244.1.117:58606 src.workload="ambient-client-v1-6dd7bbd87f-nplg4" src.namespace="ambient-client-2-25282" src.identity="spiffe://cluster.local/ns/ambient-client-2-25282/sa/ambient-client" dst.addr=10.244.1.118:15008 dst.hbone_addr=10.244.1.118:8080 dst.service="ambient-server.ambient-server-1-42887.svc.cluster.local" dst.workload="ambient-server-v1-5646c68cf-g4tfl" dst.namespace="ambient-server-1-42887" dst.identity="spiffe://cluster.local/ns/ambient-server-1-42887/sa/ambient-server" direction="inbound" bytes_sent=452 bytes_recv=155 duration="0ms"
...
2026-03-30T22:42:53.965692Z	debug	inpod::workloadmanager	received message: AddWorkload(WorkloadData { netns: OwnedFd { fd: 47 }, workload_uid: WorkloadUid("5e8fc526-7512-49ca-a389-91b38cf3a184"), workload_info: Some(WorkloadInfo { name: "ambient-server-revoked-v1-6d47d9749c-55c9h", namespace: "ambient-server-revoked-4-73306", service_account: "ambient-server-revoked" }) })	
2026-03-30T22:42:53.965696Z	info	inpod::statemanager	pod received, starting proxy	uid="5e8fc526-7512-49ca-a389-91b38cf3a184" name="ambient-server-revoked-v1-6d47d9749c-55c9h" 
...
2026-03-30T22:42:54.072867Z	debug	inpod::workloadmanager	received message: AddWorkload(WorkloadData { netns: OwnedFd { fd: 57 }, workload_uid: WorkloadUid("44ae4b64-2e94-4e26-b40e-820a9e7e33b6"), workload_info: Some(WorkloadInfo { name: "ambient-client-revoked-v1-c8d9fbc89-mqkfp", namespace: "ambient-client-revoked-3-70619", service_account: "ambient-client-revoked" }) })	

```

### PR DESCRIPTION
**Pull request by PetrMc**
before enrollment ztunnel doesn't intercept traffic so connections go direct pod-to-pod (fail-open), meaning CRL is never checked and the test sees a success when it expects a failure.

previous sequence:
  revoke -> wait for crl reload -> deploy apps -> test (race: server not enrolled yet)

new sequence:
  revoke -> deploy apps -> wait for crl reload -> wait for enrollment -> test

Fixes #59677

### CODE REVIEW

File: tests/integration/ambient/crl/crl_test.go [hunk 1]
```diff
@@ -143,6 +147,43 @@ func waitForZtunnelCRLReload(t framework.TestContext) {
...
+			if err != nil {
+				return fmt.Errorf("failed to list ztunnel pods: %w", err)
+			}
+
+			for _, pod := range pods.Items {
+				logs, err := c.PodLogs(t.Context(), pod.Name, systemNS.Name(), "istio-proxy", false)
+				if err != nil {
+					return fmt.Errorf("failed to get logs from %s: %w", pod.Name, err)
+				}
+				if strings.Contains(logs, fmt.Sprintf("namespace: \"%s\"", ns)) {
```
Comment (jaellio) [inline tests/integration/ambient/crl/crl_test.go:172]: Do we want to return here? I think we want to verify the presence of logs in all pods not just one.

Comment (PetrMc) [reply tests/integration/ambient/crl/crl_test.go:172]: only one `ztunnel` will enroll a given workload (the same node). the other ztunnel pods won't have an `AddWorkload` for this namespace. if not returning will cause timeout.

File: tests/integration/ambient/crl/crl_test.go [hunk 2]
```diff
@@ -143,6 +147,43 @@ func waitForZtunnelCRLReload(t framework.TestContext) {
...
+	t.Logf("waiting for ztunnel to enroll workload in namespace %s...", ns)
+
+	systemNS, err := istio.ClaimSystemNamespace(t)
+	if err != nil {
+		t.Fatalf("failed to get system namespace: %v", err)
+	}
+
+	retry.UntilSuccessOrFail(t, func() error {
+		for _, c := range t.AllClusters() {
+			pods, err := c.Kube().CoreV1().Pods(systemNS.Name()).List(
```
Comment (sridhargaddam) [inline tests/integration/ambient/crl/crl_test.go]: On some platforms, `ztunnel` could be installed in its own namespace and the test framework allows overriding the namespace using the `-istio.test.kube.ztunnelNamespace` field. Please update the code to use the configured namespace.
 
For reference: https://github.com/istio/istio/blob/f4cad55d44c09e41270312d3fae05d45f86777db/tests/integration/ambient/baseline_test.go#L3775

File: tests/integration/ambient/crl/crl_test.go (hunk 1 above)
Comment (sridhargaddam) [reply tests/integration/ambient/crl/crl_test.go:172]: The `deployRevokedApps` test sets up a single client and a single server. Since `waitForWorkloadEnrollment` is called using the server’s namespace, there’s only one pod to enroll on a single node, so this is good.

Comment (jaellio) [reply tests/integration/ambient/crl/crl_test.go:172]: Just feels odd to iterate over a list of pods if only 1 is expected and the test could change in the future (maybe just add a comment saying only 1 pod is expected). Not going to block on this though.

Comment (PetrMc) [reply tests/integration/ambient/crl/crl_test.go:172]: thanks both! added the comment.

File: tests/integration/ambient/crl/crl_test.go (hunk 2 above)
Comment (PetrMc) [reply tests/integration/ambient/crl/crl_test.go]: thank you for the pointer @sridhargaddam !  adjusted accordingly in the last commit.

**Review by jaellio — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]
LGTM, thanks @PetrMc

**Comment by PetrMc** [comment]
@keithmattix @howardjohn @Stevenjin8 @stevenctl - would you be able to approve as CRL tests are currently failing? thank you!

**Review by keithmattix — APPROVED** [review]
