### PR TITLE
Gateways render once the push context is loaded

### LINKED ISSUE #59709: Waypoints restart when istiod restarts
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

If you deploy a waypoint, and restart istiod, the waypoint will restart up to 2 times.

### Version

```Text
master (1.30)
```

### Additional Information

When istiod restarts, the gateway deploymentcontroller starts to Reconcile any existing gateway. There are no proxy configs loaded yet so an empty ProxyConfig is used to render the gateway templates.
After some time, the first initProxyContext occurs and Reconcile happens but this time the ProxyConfig actually has content so we generate the previously matching Deployment.
You will see 2 Replicasets per Deployment, and the PROXY_CONFIG environment variables will differ.

### PR DESCRIPTION
**Pull request by fraenkel**
**Please provide a description of this PR:**

Do not attempt to render when the proxy configs have not be initialized. The ProxyConfig will bounce between {} and some content. This will cause any existing Gateway to have its deployment re-configured twice.

fixes #59709

### CODE REVIEW

File: pilot/pkg/config/kube/gatewaycommon/deploymentcontroller.go [hunk 1]
```diff
@@ -373,6 +376,10 @@ func (d *DeploymentController) configureIstioGateway(log *istiolog.Scope, gw gat
 		log.Debug("skip disabled gateway")
 		return nil
 	}
+	if !d.env.PushContext().InitDone.Load() {
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gatewaycommon/deploymentcontroller.go:379]: I thought the issue was ProxyConfig not being available (not PushContext)?

Comment (fraenkel) [reply pilot/pkg/config/kube/gatewaycommon/deploymentcontroller.go:379]: It is but this is the only way you know it was initialized unfortunately.
If there is a better way I would switch.

Comment (keithmattix) [reply pilot/pkg/config/kube/gatewaycommon/deploymentcontroller.go:379]: We can do This until #59715 goes through

**Review by keithmattix — APPROVED** [review]

**Comment by zirain** [comment]
@fraenkel can you do a manual cherry pick to release-1.27?

**Comment by fraenkel** [comment]
Plan to do them all

**Comment by zirain** [comment]
Thanks, cause we're close to trigger the build of 1.27.9
