### PR TITLE
fix converservices test race

### LINKED ISSUE #59905: data race - TestConvertService
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

```
serviceentry: TestConvertService expand_less	0s
{Failed  ==================
WARNING: DATA RACE
Write at 0x0000090c0c78 by goroutine 2657:
  istio.io/istio/pkg/test.SetForTest[go.shape.bool]()
      /home/prow/go/src/istio.io/istio/pkg/test/util.go:27 +0x55
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.TestConvertService()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/conversion_test.go:743 +0x4a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:2036 +0x21c
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:2101 +0x38

Previous read at 0x0000090c0c78 by goroutine 2568:
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.convertServices()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/conversion.go:294 +0xe64
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.services.func1()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/conversion.go:584 +0x473
  istio.io/istio/pkg/kube/krt.(*manyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]).handleChangedPrimaryInputEvents()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:439 +0x6f7
  istio.io/istio/pkg/kube/krt.(*manyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]).onSecondaryDependencyEvent()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:702 +0xee6
  istio.io/istio/pkg/kube/krt.(*collectionDependencyTracker[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]).registerDependency.func1.1()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:818 +0xb5
  istio.io/istio/pkg/queue.(*queueImpl).processNextItem()
      /home/prow/go/src/istio.io/istio/pkg/queue/instance.go:141 +0x61
  istio.io/istio/pkg/queue.(*queueImpl).Run()
      /home/prow/go/src/istio.io/istio/pkg/queue/instance.go:180 +0x264
  istio.io/istio/pkg/kube/krt.(*manyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]).runQueue()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:660 +0x1b5
  istio.io/istio/pkg/kube/krt.newManyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }].gowrap1()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:635 +0x38

Goroutine 2657 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:2101 +0xb12
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2585 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:2036 +0x21c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2583 +0x9e9
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2443 +0xf4b
  istio.io/istio/tests/util/leak.CheckMain()
      /home/prow/go/src/istio.io/istio/tests/util/leak/check.go:198 +0x35
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.TestMain()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/leak_test.go:25 +0x17c
  main.main()
      _testmain.go:110 +0x16d

Goroutine 2568 (finished) created at:
  istio.io/istio/pkg/kube/krt.newManyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:635 +0xcbc
  istio.io/istio/pkg/kube/krt.NewManyCollection[go.shape.struct { istio.io/istio/pkg/config.Meta; Spec istio.io/istio/pkg/config.Spec; Status istio.io/istio/pkg/config.Status; Extra map[string]interface {} },go.shape.struct { Service *istio.io/istio/pilot/pkg/model.Service; TargetPorts []uint32; Instances []*istio.io/istio/pilot/pkg/model.ServiceInstance; IsPeered bool }]()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/collection.go:580 +0x444
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.services()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/conversion.go:572 +0x275
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.(*Controller).buildCollections()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller.go:268 +0x45c
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.newController()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller.go:234 +0x930
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.NewController()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller.go:184 +0x124
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.initServiceDiscoveryWithOpts()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller_test.go:152 +0x8aa
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.initServiceDiscovery()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller_test.go:89 +0x7d
  istio.io/istio/pilot/pkg/serviceregistry/serviceentry.TestPeeringSeWESelectionGuard.func1()
      /home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/serviceentry/controller_test.go:2615 +0x60
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:2036 +0x21c
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:2101 +0x38
==================
    testing.go:1712: race detected during execution of test}

### Version

```Text
master
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/59905

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Review by sridhargaddam — APPROVED** [review]
lgtm

File: pilot/pkg/serviceregistry/serviceentry/conversion_test.go [hunk 1]
```diff
@@ -737,7 +737,7 @@ func makeInstance(cfg *config.Config, workloadName string, addresses []string, p
 
 func TestConvertService(t *testing.T) {
 	testConvertServiceBody(t)
-	test.SetForTest(t, &features.CanonicalServiceForMeshExternalServiceEntry, true)
+	test.SetAtomicBoolForTest(t, features.CanonicalServiceForMeshExternalServiceEntry, true)
```
Comment (keithmattix) [inline pilot/pkg/serviceregistry/serviceentry/conversion_test.go]: Does this actually solve the problem though? If these tests are running concurrently, one test's completion could unset the flag before the code we're testing evaluates it

Comment (ramaraochavali) [reply pilot/pkg/serviceregistry/serviceentry/conversion_test.go]: This would solve the "race" part of the problem - But you are right the test can still be flaky depending when the first test reads and we set here before the second test starts. The simpler way is to split the test in to two

**Comment by fraenkel** [comment]
So this isn't the only feature that is causing the data race. I have hit another one that I haven't reported.
I believe the issue is that we don't know when the queues are done processing after a stop is invoked from the test case. There doesn't seem to be a good way to know this.

There are different approaches to fix this. make all features an atomic which seems to be a bit heavy handed, or do what has been done in the past by capturing the feature as part of the controller so an instance variable can be used instead.

**Comment by keithmattix** [comment]
> or do what has been done in the past by capturing the feature as part of the controller so an instance variable can be used instead.

This seems like the right answer to me; in practice, these vars can't change once set so capturing them in the controller seems safe.

**Comment by ramaraochavali** [comment]
Makes sense. Changed

**Comment by ramaraochavali** [comment]
@keithmattix PTAL when you get chance?

**Review by keithmattix — APPROVED** [review]
