### PR TITLE
istio-cni: improve binary detection lock contention

### LINKED ISSUE #58507: `istio-cni` plugin: can't lock `/run/xtables.lock` resource temporarily unavailable
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

From the upgrade of Istio `v1.25.3` to `v1.26.6` I've been observing few errors on `istio-cni-node-*` pods.

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "49233c7821409ba966ed4360a02c89e5a1f913d3b2dc43b5d530a6f776a76395": plugin type="istio-cni" name="istio-cni" failed (add): iptables binary iptables has no loaded kernel support and cannot be used, err: exit status 4 out: Can't lock /run/xtables.lock: Resource temporarily unavailable
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```
and

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8b7ea56d0b36d2a32eced1575102c2039f3f58836c69215063295b8b93496ecd": plugin type="istio-cni" name="istio-cni" failed (add): iptables binary ip6tables has no loaded kernel support and cannot be used, err: exit status 4 out: Can't lock /run/xtables.lock: Resource temporarily unavailable
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```

Both are similar, just the binaries are different `iptables` and `ip6tables`. Even with these errors, everything seems to work, at least I was unable to correlate any strange behaviours with the aforementioned errors.

### Version

```Text
$ istioctl version
client version: 1.26.2
control plane version: 1.26.6
data plane version: 1.25.3 (8 proxies), 1.26.3 (2 proxies), 1.26.4 (2 proxies), 1.26.6 (361 proxies)
$ kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.32.9-eks-3cfe0ce
$ helm version --short
v3.17.1+g980d8ac
```

### Additional Information

Debug logs:

```
2025-12-04T11:18:02.417630Z	info	cni-plugin	============= Start iptables configuration for test-servce-846f445c64-vbtgj =============
2025-12-04T11:18:02.432869Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was <nil>: {DetectedBinary:iptables-legacy DetectedSaveBinary:iptables-legacy-save DetectedRestoreBinary:iptables-legacy-restore Version:1.8.11 Legacy:true ExistingRules:false}
2025-12-04T11:18:02.432925Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was failed to execute iptables-nft-save: exec: "iptables-nft-save": executable file not found in $PATH : {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}
2025-12-04T11:18:02.439665Z	info	cni-plugin	============= End iptables configuration for test-servce-846f445c64-vbtgj =============
2025-12-04T11:18:02.439706Z	error	cni-plugin	istio-cni cmdAdd error: iptables binary iptables has no loaded kernel support and cannot be used, err: exit status 4 out: Can't lock /run/xtables.lock: Resource temporarily unavailable
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
2025-12-04T11:18:02.439721Z	error	cni-plugin	istio-cni failed with: iptables binary iptables has no loaded kernel support and cannot be used, err: exit status 4 out: Can't lock /run/xtables.lock: Resource temporarily unavailable
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
2025-12-04T11:18:02.583363Z	debug	controllers	handling update: [REDACTED_NS]/test-servce-846f445c64-vbtgj	controller=repair pods
2025-12-04T11:18:03.402850Z	debug	controllers	handling update: [REDACTED_NS]/fluent-fluent-bit-4x7vd	controller=repair pods
2025-12-04T11:18:03.424329Z	debug	controllers	handling update: [REDACTED_NS]/fluent-fluent-bit-4x7vd	controller=repair pods
2025-12-04T11:18:03.448174Z	debug	controllers	handling update: [REDACTED_NS]/test-servce-568597cf87-9tfq8	controller=repair pods
2025-12-04T11:18:03.490094Z	debug	controllers	handling update: [REDACTED_NS]/test-servce-846f445c64-vbtgj	controller=repair pods
2025-12-04T11:18:03.605220Z	debug	cni-plugin	istio-cni CmdAdd config: &{NetConf:{CNIVersion:0.4.0 Name:aws-cni Type:istio-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:0xc000226210 ValidAttachments:[]} PluginLogLevel:debug CNIAgentRunDir:/var/run/istio-cni AmbientEnabled:false ExcludeNamespaces:[kube-system] PodNamespace:istio-system}	if=eth0
2025-12-04T11:18:03.605358Z	debug	cni-plugin	istio-cni CmdAdd previous result: &{CNIVersion:1.1.0 Interfaces:[{Name:enif521de70451 Mac: Mtu:0 Sandbox: SocketPath: PciID:} {Name:eth0 Mac:[REDACTED_MAC] Mtu:0 Sandbox:[REDACTED_NETNS] SocketPath: PciID:} {Name:dummyf521de70451 Mac:0 Mtu:0 Sandbox:0 SocketPath: PciID:}] IPs:[{Interface:0xc0003b7cb0 Address:{IP:[REDACTED_IPV4] Mask:ffffffff} Gateway:<nil>}] Routes:[] DNS:{Nameservers:[] Domain: Search:[] Options:[]}}
2025-12-04T11:18:03.616261Z	debug	cni-plugin	Pod [REDACTED_NS]/test-servce-846f445c64-vbtgj info: 
  Containers: [test-servce istio-proxy istio-validation]
  Labels: map[app:test-servce app.kubernetes.io/managed-by:Helm app.kubernetes.io/version:0.0.0 [REDACTED_INTERNAL_LABELS] helm.sh/chart:test-servce-0.0.0 pod-template-hash:846f445c64 security.istio.io/tlsMode:istio service.istio.io/canonical-name:test-servce service.istio.io/canonical-revision:0.0.0 sidecar.istio.io/inject:true]
  Annotations: map[configmap.reloader.stakater.com/reload:test-servce-env-vars,cm-aimodel-config,cm-aisearchsystems-config istio.io/rev:default kubectl.kubernetes.io/default-container:test-servce kubectl.kubernetes.io/default-logs-container:test-servce prometheus.io/path:/stats/prometheus prometheus.io/port:15020 prometheus.io/scrape:true reloader.stakater.com/last-reloaded-from:[REDACTED] secret.reloader.stakater.com/reload:test-servce-secret-env-vars sidecar.istio.io/interceptionMode:REDIRECT sidecar.istio.io/status:[REDACTED] traffic.sidecar.istio.io/excludeInboundPorts:15020 traffic.sidecar.istio.io/includeInboundPorts:* traffic.sidecar.istio.io/includeOutboundIPRanges:* vpc.amazonaws.com/pod-ips:[REDACTED_IPV4]]
  Envs: map[AWS_DEFAULT_REGION:[REDACTED_REGION] AWS_REGION:[REDACTED_REGION] AWS_ROLE_ARN:[REDACTED_ARN] AWS_STS_REGIONAL_ENDPOINTS:regional AWS_WEB_IDENTITY_TOKEN_FILE:/var/run/secrets/eks.amazonaws.com/serviceaccount/token BOOTSTRAP_XDS_AGENT:true CA_ADDR:[REDACTED_ENDPOINT] EXIT_ON_ZERO_ACTIVE_CONNECTIONS:true GOMAXPROCS: GOMEMLIMIT: HOST_IP:[REDACTED_IPV4] INSTANCE_IP:[REDACTED_IPV4] ISTIO_CPU_LIMIT: ISTIO_KUBE_APP_PROBERS:{"/app-health/test-servce/livez":{"httpGet":{"path":"/liveness","port":8000,"scheme":"HTTP"},"timeoutSeconds":8},"/app-health/test-servce/readyz":{"httpGet":{"path":"/readiness","port":8000,"scheme":"HTTP"},"timeoutSeconds":8},"/app-health/test-servce/startupz":{"httpGet":{"path":"/startup","port":8000,"scheme":"HTTP"},"timeoutSeconds":8}} ISTIO_META_APP_CONTAINERS:test-servce ISTIO_META_CLUSTER_ID:Kubernetes ISTIO_META_DNS_AUTO_ALLOCATE:true ISTIO_META_DNS_CAPTURE:true ISTIO_META_INTERCEPTION_MODE:REDIRECT ISTIO_META_MESH_ID:[REDACTED_DOMAIN] ISTIO_META_NODE_NAME: ISTIO_META_OWNER:kubernetes://apis/apps/v1/namespaces:[REDACTED_NS]/deployments:test-servce ISTIO_META_POD_PORTS:[
    {"name":"http","containerPort":8000,"protocol":"TCP"}
] ISTIO_META_WORKLOAD_NAME:test-servce PILOT_CERT_PROVIDER:istiod POD_NAME: POD_NAMESPACE: PROXY_CONFIG:[REDACTED]]
  ProxyConfig: map[AWS_DEFAULT_REGION:[REDACTED_REGION] AWS_REGION:[REDACTED_REGION] AWS_ROLE_ARN:[REDACTED_ARN] AWS_STS_REGIONAL_ENDPOINTS:regional AWS_WEB_IDENTITY_TOKEN_FILE:/var/run/secrets/eks.amazonaws.com/serviceaccount/token BOOTSTRAP_XDS_AGENT:true CA_ADDR:[REDACTED_ENDPOINT] EXIT_ON_ZERO_ACTIVE_CONNECTIONS:true GOMAXPROCS: GOMEMLIMIT: HOST_IP:[REDACTED_IPV4] INSTANCE_IP:[REDACTED_IPV4] ISTIO_CPU_LIMIT: ISTIO_KUBE_APP_PROBERS:{"/app-health/test-servce/livez":{"httpGet":{"path":"/liveness","port":8000,"scheme":"HTTP"},"timeoutSeconds":8},"/app-health/test-servce/readyz":{"httpGet":{"path":"/readiness","port":8000,"scheme":"HTTP"},"timeoutSeconds":8},"/app-health/test-servce/startupz":{"httpGet":{"path":"/startup","port":8000,"scheme":"HTTP"},"timeoutSeconds":8}} ISTIO_META_APP_CONTAINERS:test-servce ISTIO_META_CLUSTER_ID:Kubernetes ISTIO_META_DNS_AUTO_ALLOCATE:true ISTIO_META_DNS_CAPTURE:true ISTIO_META_INTERCEPTION_MODE:REDIRECT ISTIO_META_MESH_ID:[REDACTED_DOMAIN] ISTIO_META_NODE_NAME: ISTIO_META_OWNER:kubernetes://apis/apps/v1/namespaces:[REDACTED_NS]/deployments:test-servce ISTIO_META_POD_PORTS:[
    {"name":"http","containerPort":8000,"protocol":"TCP"}
] ISTIO_META_WORKLOAD_NAME:test-servce PILOT_CERT_PROVIDER:istiod POD_NAME: POD_NAMESPACE: PROXY_CONFIG:[REDACTED]]
2025-12-04T11:18:03.616321Z	debug	cni-plugin	contains inject annotation: true	pod=[REDACTED_NS]/test-servce-846f445c64-vbtgj
2025-12-04T11:18:03.616331Z	debug	cni-plugin	Setting up redirect	pod=[REDACTED_NS]/test-servce-846f445c64-vbtgj
2025-12-04T11:18:03.616505Z	info	cni-plugin	============= Start iptables configuration for test-servce-846f445c64-vbtgj =============
2025-12-04T11:18:03.621216Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was <nil>: {DetectedBinary:iptables-legacy DetectedSaveBinary:iptables-legacy-save DetectedRestoreBinary:iptables-legacy-restore Version:1.8.11 Legacy:true ExistingRules:false}
2025-12-04T11:18:03.621259Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was failed to execute iptables-nft-save: exec: "iptables-nft-save": executable file not found in $PATH : {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}
2025-12-04T11:18:03.624784Z	debug	cni-plugin	found existing rules for iptables-save	binary=iptables
2025-12-04T11:18:03.628003Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was <nil>: {DetectedBinary:ip6tables-legacy DetectedSaveBinary:ip6tables-legacy-save DetectedRestoreBinary:ip6tables-legacy-restore Version:1.8.11 Legacy:true ExistingRules:false}
2025-12-04T11:18:03.628060Z	debug	cni-plugin	did not find (or cannot use) iptables binary, error was failed to execute ip6tables-nft-save: exec: "ip6tables-nft-save": executable file not found in $PATH : {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}
2025-12-04T11:18:03.632424Z	debug	cni-plugin	found existing rules for ip6tables-save	binary=ip6tables
2025-12-04T11:18:03.632450Z	info	cni-plugin	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=
2025-12-04T11:18:03.632465Z	info	cni-plugin	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020,15021,15090
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=15020
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DUAL_STACK=false
DNS_CAPTURE=true
DROP_INVALID=false
CAPTURE_ALL_DNS=true
DNS_SERVERS=[],[]
NETWORK_NAMESPACE=[REDACTED_NETNS]
CNI_MODE=true
EXCLUDE_INTERFACES=
RECONCILE=false
CLEANUP_ONLY=false
FORCE_APPLY=false
2025-12-04T11:18:03.632593Z	debug	cni-plugin	Generated check-rules: [{chain:ISTIO_INBOUND table:nat params:[-C ISTIO_INBOUND -p tcp --dport 15008 -j RETURN]} {chain:ISTIO_REDIRECT table:nat params:[-C ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001]} {chain:ISTIO_IN_REDIRECT table:nat params:[-C ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006]} {chain:PREROUTING table:nat params:[-C PREROUTING -p tcp -j ISTIO_INBOUND]} {chain:ISTIO_INBOUND table:nat params:[-C ISTIO_INBOUND -p tcp --dport 15020 -j RETURN]} {chain:ISTIO_INBOUND table:nat params:[-C ISTIO_INBOUND -p tcp --dport 15021 -j RETURN]} {chain:ISTIO_INBOUND table:nat params:[-C ISTIO_INBOUND -p tcp --dport 15090 -j RETURN]} {chain:ISTIO_INBOUND table:nat params:[-C ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT]} {chain:OUTPUT table:nat params:[-C OUTPUT -j ISTIO_OUTPUT]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -p udp --dport 15020 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp -m multiport ! --dports 53,15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN]} {chain:OUTPUT table:raw params:[-C OUTPUT -j ISTIO_OUTPUT_DNS]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -j ISTIO_OUTPUT_DNS]} {chain:ISTIO_OUTPUT_DNS table:nat params:[-C ISTIO_OUTPUT_DNS -p tcp --dport 53 -j REDIRECT --to-ports 15053]} {chain:ISTIO_OUTPUT_DNS table:nat params:[-C ISTIO_OUTPUT_DNS -p udp --dport 53 -j REDIRECT --to-port 15053]} {chain:ISTIO_OUTPUT_DNS table:raw params:[-C ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1]} {chain:ISTIO_OUTPUT_DNS table:raw params:[-C ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2]} {chain:ISTIO_OUTPUT_DNS table:raw params:[-C ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1]} {chain:ISTIO_OUTPUT_DNS table:raw params:[-C ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2]} {chain:PREROUTING table:raw params:[-C PREROUTING -j ISTIO_INBOUND]} {chain:ISTIO_OUTPUT_DNS table:raw params:[-C ISTIO_OUTPUT_DNS -p udp --dport 53 -j CT --zone 2]} {chain:ISTIO_INBOUND table:raw params:[-C ISTIO_INBOUND -p udp --sport 53 -j CT --zone 1]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN]} {chain:ISTIO_OUTPUT table:nat params:[-C ISTIO_OUTPUT -j ISTIO_REDIRECT]}]
2025-12-04T11:18:03.632615Z	debug	cni-plugin	Generated check-rules: []
2025-12-04T11:18:03.632632Z	debug	cni-plugin	Running command (sandboxed without lock): iptables-save
2025-12-04T11:18:03.633146Z	warn	cni-plugin	failed to setup execution environment, attempting to continue anyways: failed to remount /: permission denied
2025-12-04T11:18:03.633986Z	debug	cni-plugin	Command output: 
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
2025-12-04T11:18:03.634042Z	debug	cni-plugin	[IPv4] Current iptables state: map[string]map[string][]string{"filter":map[string][]string{}, "mangle":map[string][]string{}, "nat":map[string][]string{}, "raw":map[string][]string{}}
2025-12-04T11:18:03.634070Z	debug	cni-plugin	[IPv4] Expected iptables state: map[string]map[string][]string{"filter":map[string][]string{}, "mangle":map[string][]string{}, "nat":map[string][]string{"ISTIO_INBOUND":[]string{"-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN", "-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN", "-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN", "-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN", "-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT"}, "ISTIO_IN_REDIRECT":[]string{"-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006"}, "ISTIO_OUTPUT":[]string{"-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN", "-A ISTIO_OUTPUT -p udp --dport 15020 -j RETURN", "-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN", "-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp -m multiport ! --dports 53,15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT", "-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN", "-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN", "-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT", "-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN", "-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN", "-A ISTIO_OUTPUT -j ISTIO_OUTPUT_DNS", "-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN", "-A ISTIO_OUTPUT -j ISTIO_REDIRECT"}, "ISTIO_OUTPUT_DNS":[]string{"-A ISTIO_OUTPUT_DNS -p tcp --dport 53 -j REDIRECT --to-ports 15053", "-A ISTIO_OUTPUT_DNS -p udp --dport 53 -j REDIRECT --to-port 15053"}, "ISTIO_REDIRECT":[]string{"-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001"}, "OUTPUT":[]string{"-A OUTPUT -j ISTIO_OUTPUT"}, "PREROUTING":[]string{"-A PREROUTING -p tcp -j ISTIO_INBOUND"}}, "raw":map[string][]string{"ISTIO_INBOUND":[]string{"-A ISTIO_INBOUND -p udp --sport 53 -j CT --zone 1"}, "ISTIO_OUTPUT_DNS":[]string{"-A ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1", "-A ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2", "-A ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1", "-A ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2", "-A ISTIO_OUTPUT_DNS -p udp --dport 53 -j CT --zone 2"}, "OUTPUT":[]string{"-A OUTPUT -j ISTIO_OUTPUT_DNS"}, "PREROUTING":[]string{"-A PREROUTING -j ISTIO_INBOUND"}}}
2025-12-04T11:18:03.634109Z	debug	cni-plugin	Running command (sandboxed without lock): ip6tables-save
2025-12-04T11:18:03.634411Z	warn	cni-plugin	failed to setup execution environment, attempting to continue anyways: failed to remount /: permission denied
2025-12-04T11:18:03.635805Z	debug	cni-plugin	Command output: 
# Generated by ip6tables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
2025-12-04T11:18:03.635833Z	debug	cni-plugin	[IPv6] Current iptables state: map[string]map[string][]string{"filter":map[string][]string{}, "mangle":map[string][]string{}, "nat":map[string][]string{}, "raw":map[string][]string{}}
2025-12-04T11:18:03.635839Z	debug	cni-plugin	[IPv6] Expected iptables state: map[string]map[string][]string{"filter":map[string][]string{}, "mangle":map[string][]string{}, "nat":map[string][]string{}, "raw":map[string][]string{}}
2025-12-04T11:18:03.635854Z	debug	cni-plugin	iptables state verification summary: [{residueExists:false deltaExists:true plannedIstioRules:true versionName:IPv4} {residueExists:false deltaExists:false plannedIstioRules:false versionName:IPv6}]
2025-12-04T11:18:03.635863Z	info	cni-plugin	Clean-state detected, new iptables are needed
2025-12-04T11:18:03.635867Z	info	cni-plugin	Applying iptables chains and rules
2025-12-04T11:18:03.635922Z	info	cni-plugin	Running iptables restore with: iptables-restore and the following input:
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-N ISTIO_OUTPUT_DNS
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -p udp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp -m multiport ! --dports 53,15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_OUTPUT_DNS -p tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT_DNS -p udp --dport 53 -j REDIRECT --to-port 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
* raw
-N ISTIO_OUTPUT_DNS
-N ISTIO_INBOUND
-A OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2
-A ISTIO_OUTPUT_DNS -p udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2
-A PREROUTING -j ISTIO_INBOUND
-A ISTIO_OUTPUT_DNS -p udp --dport 53 -j CT --zone 2
-A ISTIO_INBOUND -p udp --sport 53 -j CT --zone 1
COMMIT
2025-12-04T11:18:03.635954Z	debug	cni-plugin	Running command (sandboxed local lock by env and nss): iptables-restore --noflush --wait=30
2025-12-04T11:18:03.636266Z	warn	cni-plugin	failed to setup execution environment, attempting to continue anyways: failed to remount /: permission denied
2025-12-04T11:18:03.638520Z	info	cni-plugin	Running iptables restore with: ip6tables-restore and the following input:
2025-12-04T11:18:03.638559Z	debug	cni-plugin	Running command (sandboxed local lock by env and nss): ip6tables-restore --noflush --wait=30
2025-12-04T11:18:03.638909Z	warn	cni-plugin	failed to setup execution environment, attempting to continue anyways: failed to remount /: permission denied
2025-12-04T11:18:03.640130Z	debug	cni-plugin	Running command (sandboxed without lock): iptables-save
2025-12-04T11:18:03.640386Z	warn	cni-plugin	failed to setup execution environment, attempting to continue anyways: failed to remount /: permission denied
2025-12-04T11:18:03.642176Z	debug	cni-plugin	Command output: 
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_OUTPUT_DNS - [0:0]
-A PREROUTING -j ISTIO_INBOUND
-A OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_INBOUND -p udp -m udp --sport 53 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -j CT --zone 2
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_OUTPUT_DNS - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -p udp -m udp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m multiport ! --dports 53,15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_OUTPUT_DNS -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
2025-12-04T11:18:03.642211Z	info	cni-plugin	Final iptables state (IPv4):
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_OUTPUT_DNS - [0:0]
-A PREROUTING -j ISTIO_INBOUND
-A OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_INBOUND -p udp -m udp --sport 53 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1
-A ISTIO_OUTPUT_DNS -p udp -m udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -j CT --zone 2
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_OUTPUT_DNS - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -p udp -m udp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m multiport ! --dports 53,15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 15008 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_OUTPUT_DNS
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_OUTPUT_DNS -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT_DNS -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
# Generated by iptables-save v1.8.11 on Thu Dec  4 11:18:03 2025
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Thu Dec  4 11:18:03 2025
2025-12-04T11:18:03.642246Z	info	cni-plugin	============= End iptables configuration for test-servce-846f445c64-vbtgj =============
```

### PR DESCRIPTION
**Pull request by pau1ocampos**
**Please provide a description of this PR:**

When checking if the `iptables` binary should be used, check if the binary supports the `--wait` flag. If yes, use the flag to reduce the errors around the binary not being available because is locked by another application.

The flag is passed with `30` seconds, because is what is already used in the code - in the `executeXTables` function.

Resolves #58507

### CODE REVIEW

**Comment by pau1ocampos** [comment]
Tagging @bleggett as you added some of this logic. I'm not 100% sure of the impacts on this, so if you can take a look it would be nice.

@howardjohn + @leosarra as you reviewed [PR](https://github.com/istio/istio/pull/55281).

🙇‍♂️

File: tools/istio-iptables/pkg/dependencies/implementation_linux.go [hunk 1]
```diff
@@ -105,6 +105,11 @@ func shouldUseBinaryForCurrentContext(iptablesBin string) (IptablesVersion, erro
 	// so try to add a no-op rule to that table, and make sure it doesn't fail - if it does, we can't use this version
 	// as the host is missing kernel support for it.
 	// (255 is a nonexistent protocol number, IANA reserved, see `cat /etc/protocols`, so this rule will never match anything)
+	// should use the wait flag if supported to avoid lock contention whenever possible
+	needLock := !isNft && !parsedVer.LessThan(IptablesRestoreLocking)
+	if needLock {
+		testRuleAdd = append(testRuleAdd, "--wait=30")
```
Comment (sridhargaddam) [inline tools/istio-iptables/pkg/dependencies/implementation_linux.go]: The `DetectIptablesVersion()` method calls `shouldUseBinaryForContext()` API couple of times (f.e., for legacy, nft, and plain binaries). Here we are modifying the global variable `testRuleAdd` by appending `--wait=30` for each invocation. Please fix it by making it a local copy.

Comment (sridhargaddam) [reply tools/istio-iptables/pkg/dependencies/implementation_linux.go]: We probably need a `--wait=30` even for the delete operation as well (at Line 128)

File: releasenotes/notes/58507.yaml [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+# issue is a list of GitHub issues resolved in this note.
+# If issue is not in the current repo, specify its full URL instead.
+issue:
+  - 58507
+
+# releaseNotes is a markdown listing of any user facing changes. This will appear in the
+# release notes.
+releaseNotes: |
+  **Fixed** an issue where `iptables` command where not waiting to acquire a lock on
+  `/run/xtables.lock`, causing some misleading errors on logs.
```
Comment (sridhargaddam) [inline releasenotes/notes/58507.yaml]:
```suggestion
  **Fixed** an issue where `iptables` command was not waiting to acquire a lock on
  `/run/xtables.lock`, causing some misleading errors in the logs.
```

File: tools/istio-iptables/pkg/dependencies/implementation_linux.go (hunk 1 above)
Comment (OS-paulocampos) [reply tools/istio-iptables/pkg/dependencies/implementation_linux.go]: Thank you for your feedback.

You are right, I fixed that by making a local copy of the slice.

**Review by leosarra — APPROVED** [review]
Ty! LGTM as well :)

**Comment by pau1ocampos** [comment]
Hi @howardjohn,

Sorry to tag you again, I got the approvals, anything else I should do for getting this merged? I read the documentation, but it's not 100% clear and this is the first I contribute for this project. Thank you and apologies again. 🙇‍♂️
