### PR TITLE
use allowed audiences instead of default audience

### LINKED ISSUE #33722: sidecar authenticate error if use `first-party-jwt` policy
**Bug description**
When I use first-party-jwt as JWT_POLICY, sidecar can not access istiod.

istiod logs:

```logs
2021-06-30T04:47:53.344303Z	warn	serverca	Authentication failed for 10.244.1.53:37692: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT from cluster "cluster1": the service account authentication returns an error: [invalid bearer token, token audiences ["https://kubernetes.default.svc.cluster.local"] is invalid for the target audiences ["istio-ca"]].
2021-06-30T04:47:53.494182Z	warn	serverca	Authentication failed for 10.244.1.53:37692: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT from cluster "cluster1": the service account authentication returns an error: [invalid bearer token, token audiences ["https://kubernetes.default.svc.cluster.local"] is invalid for the target audiences ["istio-ca"]].
```

[X] Security

**Expected behavior**
sidecar connect istiod successfully.

**Steps to reproduce the bug**
kind create cluster
install istio with `--set values.global.jwtPolicy=first-party-jwt`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
latest.

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix: https://github.com/istio/istio/issues/33722

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Do we need to do this? first-party-jwt has been deprecated for 2 years. If users are already customizing the default audience they should probably just not use first-party-jwt? Is there a case where that is not acceptable?

**Comment by kebe7jun** [comment]
> Do we need to do this? first-party-jwt has been deprecated for 2 years. If users are already customizing the default audience they should probably just not use first-party-jwt? Is there a case where that is not acceptable?

Although we don't use it much now, it does cause an unusable bug.
I think we should provide users with this choice.

File: security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go [hunk 1]
```diff
@@ -74,8 +74,6 @@ func (a *KubeJWTAuthenticator) AuthenticatorType() string {
 	return KubeJWTAuthenticatorType
 }
 
-const DefaultKubernetesAudience = "kubernetes.default.svc"
```
Comment (howardjohn) [inline security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go:77]: should we just allow `kubernetes.default.svc` OR `kubernetes.default.svc.cluster.local`? 

I think that we should work out of the box with common environments (like https://github.com/istio/istio/issues/33744), and for bespoke cases they should use third-party-jwt. WDYT?

Comment (kebe7jun) [reply security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go:77]: Ok, fixed.

File: security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go [hunk 2]
```diff
@@ -112,18 +127,18 @@ func (a *KubeJWTAuthenticator) authenticate(targetJWT string, clusterID cluster.
...
 				// For backwards compatibility, if first-party-jwt is used and they don't require 3p, allow it but warn
 				// This is intended to support first-party-jwt on Kubernetes 1.21+, where BoundServiceAccountTokenVolume
-				// became default and started setting an audience to DefaultKubernetesAudience.
+				// became default and started setting an audience to one of defaultAllowedKubernetesAudiences.
 				// Users should disable first-party-jwt, but we don't want to break them on upgrade
 				log.Warnf("Insecure first-party-jwt option used to validate token; use third-party-jwt")
 				aud = nil
 			} else {
-				log.Warnf("Received token with aud %q, but expected %q. BoundServiceAccountTokenVolume, "+
+				log.Warnf("Received token with aud %q, but expected on of %q. BoundServiceAccountTokenVolume, "+
```
Comment (howardjohn) [inline security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go:139]:
```suggestion
				log.Warnf("Received token with aud %q, but expected one of %q. BoundServiceAccountTokenVolume, "+
```

File: security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go [hunk 3]
```diff
@@ -112,18 +127,18 @@ func (a *KubeJWTAuthenticator) authenticate(targetJWT string, clusterID cluster.
 	// tolerate the unbound tokens.
 	if !util.IsK8SUnbound(targetJWT) || security.Require3PToken.Get() {
 		aud = security.TokenAudiences
-		if tokenAud, _ := util.ExtractJwtAud(targetJWT); len(tokenAud) == 1 && tokenAud[0] == DefaultKubernetesAudience {
+		if tokenAud, _ := util.ExtractJwtAud(targetJWT); isAllowedAudiences(tokenAud) {
```
Comment (howardjohn) [inline security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go:130]: can we keep the len check? Then isAllowedAudiences can be simpler, like:

```go
if _, f := DefaultKubernetesAudience[tokenAud[0]; f {
 ....
}
```

And change DefaultKubernetesAudience to a map instead of a slice, then we can easily lookup.

**Review by howardjohn — COMMENTED** [review]
lgtm! just minor nits then I will approve. Thanks!

File: security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go (hunk 3 above)
Comment (kebe7jun) [reply security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go]: Thanks! Updated.

**Review by howardjohn — APPROVED** [review]
