### PR TITLE
[release-1.23] Fix Ambient Peer Authn flake (#54566)

### LINKED ISSUE #54572: [release-1.23] Fix Ambient Peer Authn flake
Manual cherrypick required.

#54566 failed to apply on top of branch "release-1.23":
```
Applying: Peer authn flake fix
Using index info to reconstruct a base tree...
M	pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
M	tests/integration/ambient/baseline_test.go
Falling back to patching base and 3-way merge...
Auto-merging tests/integration/ambient/baseline_test.go
CONFLICT (content): Merge conflict in tests/integration/ambient/baseline_test.go
Auto-merging pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
hint: When you have resolved this problem, run "git am --continue".
hint: If you prefer to skip this patch, run "git am --skip" instead.
hint: To restore the original branch and stop patching, run "git am --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Patch failed at 0001 Peer authn flake fix

```

### PR DESCRIPTION
**Pull request by keithmattix**
Fixes #54572 and #54593

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go [hunk 1]
```diff
@@ -25,6 +25,8 @@ import (
 	"istio.io/istio/pilot/pkg/model"
 	"istio.io/istio/pkg/config/schema/kind"
 	"istio.io/istio/pkg/log"
+	"istio.io/istio/pkg/maps"
+	"istio.io/istio/pkg/slices"
```
Comment (mikemorris) [inline pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go:29]: Noticed this wasn't needed in the corresponding 1.24 backport, #54616 - is there any other relevant divergence that should be backported to 1.23 too?

Comment (keithmattix) [reply pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go:29]: It's there: https://github.com/istio/istio/pull/54616/files#diff-5a6209247b2b9eadf04b73f00ce5513e147b01950b08d974240a4f05650732c3R28. Slices is just already imported in that branch because we have status reporting in 1.24 - https://github.com/keithmattix/istio/blob/f28c58c066fdfad0b0fa3197e8611893a6c9e258/pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go#L452

**Review by mikemorris — APPROVED** [review]
