### PR TITLE
Refresh oop handler with connection config update

### LINKED ISSUE #12488: When only address is changed, mixer handler isn't refreshed
**Describe the bug**
change the address of out-process-adapter when mixer is running doesn't work.

**Expected behavior**
mixer server change the handler address to a new one that config yaml specifies.

**Steps to reproduce the bug**
Define an out-of-process adapter like this:
```yaml
# handler for adapter mygrpcadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: h1
  namespace: istio-system
spec:
  adapter: java-adapter
  connection:
    address: "java-adapter:8888"
  params:
    file_path: "out.txt"
```

start mixer server.

change `spec.connection.address` to another one. For example, from a wrong address to a right address.

the handler still doesn't works.

**Version**
mixer build from master branch

**Environment**
MacOS

**Cluster state**
run from command.

PR: #12512

### PR DESCRIPTION
**Pull request by bianpengyuan**
Supersedes #12512, Thanks @zhranklin for the great work!

This fixes #12488

### CODE REVIEW

File: mixer/pkg/runtime/handler/table_test.go [hunk 1]
```diff
@@ -108,6 +110,38 @@ func TestNew_NoReuse_DifferentConfig(t *testing.T) {
...
+	adapters := map[string]*adapter.Info{}
+
+	// Load base dynamic config, which includes listentry template and listbackend adapter config
+	dynamicConfig, err := data.ReadConfigs("../../../template/listentry/template.yaml", "../../../test/listbackend/nosession.yaml")
+	dynamicConfig = data.JoinConfigs(dynamicConfig, data.InstanceDynamic, data.RuleDynamic)
+
+	// Join base dynamic config with dynamic handler
+	config1 := data.JoinConfigs(dynamicConfig, data.ListHandler3)
+	if err != nil {
+		t.Fatalf("Fail to load dynamic config: %v", err)
```
Comment (kyessenov) [inline mixer/pkg/runtime/handler/table_test.go]: lower case errors please

File: mixer/pkg/runtime/handler/table_test.go [hunk 2]
```diff
@@ -108,6 +110,38 @@ func TestNew_NoReuse_DifferentConfig(t *testing.T) {
...
+
+	// Join base dynamic config with dynamic handler which has different connection address
+	config2 := data.JoinConfigs(dynamicConfig, data.ListHandler3Addr)
+	// NewTable again using the slightly different config
+	s, _ = config.GetSnapshotForTest(templates, adapters, data.ServiceConfig, config2)
+
+	table2 := NewTable(table, s, nil)
+
+	if len(table2.entries) != 1 {
+		t.Fatal("size")
```
Comment (kyessenov) [inline mixer/pkg/runtime/handler/table_test.go]: can you write something more descriptive than `size`?

File: mixer/pkg/runtime/handler/table_test.go [hunk 3]
```diff
@@ -108,6 +110,38 @@ func TestNew_NoReuse_DifferentConfig(t *testing.T) {
...
+	}
+
+	if table2.entries[data.FqdnListHandler3] == table.entries[data.FqdnListHandler3] {
+		t.Fail()
```
Comment (kyessenov) [inline mixer/pkg/runtime/handler/table_test.go]: add an error message: signature for modified handler has not changed

**Comment by kyessenov** [comment]
Thanks for taking it on! I added a few comment to improve error messaging, but other than that it looks good. I also discovered #2539 while reviewing this.

File: mixer/pkg/runtime/handler/table_test.go (hunk 3 above)
Comment (bianpengyuan) [reply mixer/pkg/runtime/handler/table_test.go]: Done.

File: mixer/pkg/runtime/handler/table_test.go (hunk 2 above)
Comment (bianpengyuan) [reply mixer/pkg/runtime/handler/table_test.go]: Done.

File: mixer/pkg/runtime/handler/table_test.go (hunk 1 above)
Comment (bianpengyuan) [reply mixer/pkg/runtime/handler/table_test.go]: Done.

**Comment by bianpengyuan** [comment]
@mandarjog @duderino  Can we merge this into release-1.1? This is a bug fix for out of process adapter.
