### PR TITLE
Fix getting pod of hostnetwork

### LINKED ISSUE #28981: Subset cluster has no endpoints
**Bug description**

Our customers have a DestinationRule with subset like this:
```
 apiVersion: networking.istio.io/v1beta1
 kind: DestinationRule
 metadata:
   name: myapp
 spec:
   host: myapp
   trafficPolicy:
     loadBalancer:
       simple: LEAST_CONN
   subsets:
    - name: testversion
      labels:
       version: v3
     trafficPolicy:
       loadBalancer:
         simple: ROUND_ROBIN
```

However, `myapp` service are deployed with hostNetwork and without sidecar.  And after sometime, we found that the subset cluster's endpoints are all gone.

After some diagnosing, I think i found the cause. For hostNework pods, they may have same pod ip. In istio, we heavily depend on podip as a unique key to select pod.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fix #28981

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
ping @ramaraochavali @howardjohn

File: pilot/pkg/serviceregistry/kube/controller/pod.go [hunk 1]
```diff
@@ -222,9 +222,14 @@ func (pc *PodCache) getPodByIP(addr string) *v1.Pod {
 	if !exists {
 		return nil
 	}
-	item, exists, err := pc.informer.GetStore().GetByKey(key)
-	if !exists || err != nil {
-		return nil
+	return pc.getPodByKey(key)
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/pod.go:225]: Isn't getPodByIP fundamentally broken? I would expect this to be completely removed?

Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:225]: Fundamentally broken as in we should index by a combo of network & address?

Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:225]: Its not just network, in the "IP reach-ability" sense. If you are run as hostNetwork, the pod runs without its own dedicated pod network, and the IP of the node. For example:
```
kindnet-vhk6w                                1/1     Running   0          4h44m   172.17.0.3   kind-control-plane   <none>           <none>
kube-apiserver-kind-control-plane            1/1     Running   0          4h44m   172.17.0.3   kind-control-plane   <none>           <none>
kube-controller-manager-kind-control-plane   1/1     Running   0          4h44m   172.17.0.3   kind-control-plane   <none>           <none>
kube-proxy-kbdp9                             1/1     Running   0          4h44m   172.17.0.3   kind-control-plane   <none>           <none>
kube-scheduler-kind-control-plane            1/1     Running   0          4h44m   172.17.0.3   kind-control-plane   <none>           <none>
```

You can see they all have the same IP

Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:225]: So this PR fixes one specific instance, but we still lookup other things by IP. This means, for example, we may see the wrong service account for an endpoint.

We also don't inject host network pods so most of this may not matter as much as it would otherwise

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:225]: I understand that, will file another commit. This is to make it  as smaller as possible

**Comment by hzxuzhonghu** [comment]
/retest

@howardjohn @stevenctl ptal

File: pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go [hunk 2]
```diff
@@ -113,37 +113,40 @@ func updateEDS(c *Controller, epc kubeEndpointsController, ep interface{}, event
...
+		return pod, true
+	}
+	// This means the endpoint is manually controlled
+	// TODO: this may be not correct because of the hostnetwork pods may have same ip address
+	// Do we have a way to get the pod from only endpoint?
+	pod := c.pods.getPodByIP(ip)
+	if pod != nil {
+		// This prevents selecting a pod in another different namespace
+		if pod.Namespace != ep.Namespace {
+			pod = nil
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go:148]: When we fail here, we are now missing the `endpointsWithNoPods` logic on L130-L137. This means if the endpoint is later created it will remain broken

File: pilot/pkg/serviceregistry/kube/controller/pod.go [hunk 3]
```diff
@@ -222,9 +222,32 @@ func (pc *PodCache) getPodByIP(addr string) *v1.Pod {
...
+}
+
+// getPodByKey returns the pod or nil if pod not found or an error occurred
+func (pc *PodCache) getPodByKey(key string) *v1.Pod {
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/pod.go:229]: nit: would be nice to add a comment about what the key format is

File: pilot/pkg/serviceregistry/kube/controller/pod.go [hunk 4]
```diff
@@ -222,9 +222,32 @@ func (pc *PodCache) getPodByIP(addr string) *v1.Pod {
...
+	item, _, _ := pc.informer.GetStore().GetByKey(key)
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/pod.go:230]: is it safe to ignore the last two return params and just check item != nil?

File: pilot/pkg/serviceregistry/kube/controller/pod.go [hunk 5]
```diff
@@ -222,9 +222,32 @@ func (pc *PodCache) getPodByIP(addr string) *v1.Pod {
...
+	if key != "" {
+		pod = pc.getPodByKey(key)
+		if pod != nil {
+			return pod
+		}
+	}
+
+	// only need to fetch the corresponding pod through the first IP, although there are multiple IP scenarios,
+	// because multiple ips belong to the same pod
+	proxyIP := proxy.IPAddresses[0]
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/pod.go:250]: This may panic if we have no IPs? Not sure if that is possible at this point though

File: pilot/pkg/serviceregistry/kube/controller/util.go [hunk 6]
```diff
@@ -189,3 +190,13 @@ func isNodePortGatewayService(svc *v1.Service) bool {
 	_, ok := svc.Annotations[kube.NodeSelectorAnnotation]
 	return ok && svc.Spec.Type == v1.ServiceTypeNodePort
 }
+
+// Get the proxy pod key which can be used to get pod from the informer cache
+func proxyPodKey(proxy *model.Proxy) string {
+	parts := strings.Split(proxy.ID, ".")
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/util.go:196]: This is leaking implementation details IMO. In the metadata parsing code we even say getting info from proxy.ID is legacy and we push all info into NodeMetadata. At the very least, we should not be doing strings.Split here and instead should have some sort of field in model.Proxy so we don't have to parse it here every time

Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/util.go:196]: Also I am worried this is backwards incompatible, I know there are many tools I have written that will be broken by this change

File: pilot/pkg/serviceregistry/kube/controller/util.go [hunk 7]
```diff
@@ -189,3 +190,13 @@ func isNodePortGatewayService(svc *v1.Service) bool {
...
+	if len(parts) == 2 && proxy.Metadata.Namespace != parts[1] {
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/util.go:197]: what is `proxy.Metadata.Namespace != parts[1]` for?

File: pilot/pkg/serviceregistry/kube/controller/endpoints.go [hunk 8]
```diff
@@ -121,11 +120,12 @@ func (e *endpointsController) InstancesByPort(c *Controller, svc *model.Service,
 		return nil
 	}
 	ep := item.(*v1.Endpoints)
+	hostname := kube.ServiceHostname(ep.Name, ep.Namespace, e.c.domainSuffix)
 	var out []*model.ServiceInstance
 	for _, ss := range ep.Subsets {
 		for _, ea := range ss.Addresses {
 			var podLabels labels.Instance
-			pod := c.pods.getPodByIP(ea.IP)
+			pod, _ := getPod(c, ea.IP, &ep.ObjectMeta, ea.TargetRef, hostname)
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/endpoints.go:128]: Calling this function may have side effects of queueEndpointEventOnPodArrival which is unexpected here

**Review by howardjohn — COMMENTED** [review]
I like the idea of this but have concerns since this is such a critical code path

File: pilot/pkg/serviceregistry/kube/controller/pod.go (hunk 5 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:250]: It is not possible, such usage is widely in this repo

File: pilot/pkg/serviceregistry/kube/controller/util.go (hunk 6 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/util.go:196]: Agree for some customized proxy, they may be formatted, so i leave the legacy getPodByIP and if it fails here, it does not matter.

File: pilot/pkg/serviceregistry/kube/controller/util.go (hunk 7 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/util.go:197]: This is to exclude some bad ID (`a.b`) maybe from some tools

File: pilot/pkg/serviceregistry/kube/controller/endpoints.go (hunk 8 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/endpoints.go:128]: Yeah, i realized that, will look into if there is another way.

File: pilot/pkg/serviceregistry/kube/controller/pod.go (hunk 4 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:230]: yes

File: pilot/pkg/serviceregistry/kube/controller/pod.go (hunk 3 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go:229]: make sense

File: pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go:148]: When it comes in this clause, this is the endpoint created manually not by k8s controllers. In most case, these endpoint has no associated pods.  For the other very rare case(may be < 0.01%), we could not know whether this ep has an associated pod or not.  I donot mind enqueue endpoint on pod arrival in this case, but have a concern about when we should delete the element if there is no pod at all.

File: pilot/pkg/serviceregistry/kube/controller/endpoints.go (hunk 8 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/endpoints.go:128]: After a close look and analysis, there is no harm for queueEndpointEventOnPodArrival twice. Actually, it can be called many times before. But i can create another function to get ride of `queueEndpointEventOnPodArrival ` though.
With regard to the issue: pod comes later than endpoint, i do not change anything. It seems not correct if we can not get the pod here. We need pod labels/serviceacccount/workloadname. If these are missing, the intermediate xds configuration maybe not right. I will file an issue here.

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/endpoints.go:128]: @howardjohn take a look at the legacy bug https://github.com/istio/istio/issues/29405

File: pilot/pkg/serviceregistry/kube/controller/util.go (hunk 7 above)
Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/util.go:197]: shouldn't it be `==` not `!=`?

**Comment by hzxuzhonghu** [comment]
ping @howardjohn @stevenctl

File: pilot/pkg/serviceregistry/kube/controller/util.go (hunk 7 above)
Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/util.go:197]: And can we have a test covering this case?

**Review by howardjohn — COMMENTED** [review]
looks 99% good to me, just one more comment

File: pilot/pkg/serviceregistry/kube/controller/util.go (hunk 7 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/util.go:197]: Sorry i missed the above comment 11days ago.

**Review by howardjohn — APPROVED** [review]
