### PR TITLE
Fix bad validatingwebhookconfiguration gen

### LINKED ISSUE #38599: istioctl install generates bad validatingwebhookconfiguration
### Bug Description

Installing a gateway using an empty profile [like this](https://istio.io/latest/docs/setup/install/external-controlplane/#enable-gateways) on a config cluster (with an external control plane) creates a `istiod-default-validator` `ValidatingWebhookConfiguration` using the injection URL (`<external-host>/inject/cluster=...`), instead of the validation URL (`<external-host>/validate`) for the `clientConfig.url`.

I think there are two problems here:

1. Creating a gateway using an empty profile should not trigger webhook generation.
2. The webhook needs to use the proper URL for the validator.

### Version

```prose
1.13.2
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by frankbu**
**Please provide a description of this PR:**

Fixed #38599

### CODE REVIEW

File: operator/cmd/mesh/install.go [hunk 1]
```diff
@@ -204,7 +204,7 @@ func Install(rootArgs *RootArgs, iArgs *InstallArgs, logOpts *log.Options, stdOu
 		return fmt.Errorf("failed to install manifests: %v", err)
 	}
 
-	if !exists || rev == "" {
+	if !exists || rev == "" && pilotEnabled {
```
Comment (frankbu) [inline operator/cmd/mesh/install.go:207]: This prevents webhook manipulation from being an unexpected side effect for things like simply deploying a gateway with an empty profile.

File: istioctl/pkg/tag/generate.go [hunk 2]
```diff
@@ -130,6 +131,13 @@ func Generate(ctx context.Context, client kube.ExtendedClient, opts *GenerateOpt
 		// TODO(Monkeyanator) should extract the validationURL from revision's validating webhook here. However,
 		// to ease complexity when pointing default to revision without per-revision validating webhook,
 		// instead grab the endpoint information from the mutating webhook. This is not strictly correct.
+		if tagWhConfig.URL != "" {
+			webhookURL, err := url.Parse(tagWhConfig.URL)
+			if err == nil {
+				webhookURL.Path = "/validate"
+				tagWhConfig.URL = webhookURL.String()
```
Comment (frankbu) [inline istioctl/pkg/tag/generate.go:138]: @Monkeyanator This fix is still "not strictly correct" either, but the original code is incorrect. At some point I think this should really be fixed properly.

Comment (litong01) [reply istioctl/pkg/tag/generate.go:138]: feel that the fix will make the logic even more complex. don't we have some kind of very clear logic to indicate if the webhook should be touched? such as check if istiod is included or this is a remote cluster install or some other conditions? I have tried this case, install remote cluster which has webhook installed and the external istiod also injected the caBundles to the webhook, then when I install a gateway, it completely messed up the webhook, it made the external istiod think there is a leader election with different root ca and produced unauthorized requests. After awhile digging, I figured it was due to the install messing with the webhooks. was not easy to figure out why.

Comment (frankbu) [reply istioctl/pkg/tag/generate.go:138]: @litong this change has nothing to do with what you're describing. It's simply fixing the incorrect URL in the default validating webhook configuration. Line 207 in the other file is trying to prevent generating the webhook when all that's being installed is a gateway.

Comment (litong01) [reply istioctl/pkg/tag/generate.go:138]: @frankbu ok.

**Review by howardjohn — COMMENTED** [review]
Any tests?

**Review by howardjohn — COMMENTED** [review]
Test comment was not just about adding coverage - I do not understand how it can possibly work in any circumstances today?

The issue describes a very isolated case of Gateway only in config cluster, but doesn't this always use the MWH url in the VWH which is always wrong (currently)?

**Comment by frankbu** [comment]
> The issue describes a very isolated case of Gateway only in config cluster, but doesn't this always use the MWH url in the VWH which is always wrong (currently)?

This should be tested in the istiodremote integration tests. Even though it's a bad webhook, the other installed one (which, unlike injection webhooks, is not deactivated) works. I think there may be more issues with this code, but this PR is just trying to just get it sortof correct but also disable generating it in the config cluster for now.

**Comment by frankbu** [comment]
@howardjohn Actually, I see that we use injectionPath, not injectionURL, for the external control plane integration test, so this does not get tested. I noticed it when setting up an external control plane manually using the documented procedure, which does use the injectionURL (for a remote public DNS gateway). The doc test doesn't test validation, so it might not be working thanks to this bug?

**Review by howardjohn — COMMENTED** [review]
Please add unit tests to generate_test.go. This is super complex, hard to tell what is going on without before/after test diff.

File: operator/cmd/mesh/install.go (hunk 1 above)
Comment (howardjohn) [reply operator/cmd/mesh/install.go:207]: Webhook injection is required for (some) gateways though, so this might cause issues...?

File: istioctl/pkg/tag/generate_test.go [hunk 3]
```diff
@@ -141,6 +143,14 @@ func TestGenerateValidatingWebhook(t *testing.T) {
...
 			istioNamespace: "istio-system",
 			webhook:        revisionCanonicalWebhookRemote,
+			whURL:          remoteValidationURL,
+			whSVC:          "",
+			whCA:           "ca",
+		},
+		{
+			name:           "webhook-configured-with-bad-url",
+			istioNamespace: "istio-system",
+			webhook:        revisionCanonicalWebhookRemote,
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate_test.go:153]: I don't understand this test. The inputs are the same as `webhook-pointing-to-url` but the expectations are different and both pass... I don't understand why we conditionally skip the test on L200

Comment (frankbu) [reply istioctl/pkg/tag/generate_test.go:153]: The URL field is different in this test: `whURL:          remoteInjectionURL,`. The `webhook-pointing-to-url` test uses: `remoteValidationURL`, which is a proper validation URL. This PR is needed because the code is incorrectly using an injection URL, which this PR is correcting. As Sam's TODO on line 131 points out, this is not strictly correct, but fixing the code to do it properly is a bigger effort (so I left Sam's TODO).

Comment (howardjohn) [reply istioctl/pkg/tag/generate_test.go:153]: But the whURL is the _expected output_ of the test, not the inputs...? So what we are saying, in my understanding is for the same inputs, we expected 2 different outputs, and both tests pass. That only works since the test is not actually testing the expected output due to skippiung it on L200?

File: operator/cmd/mesh/install.go (hunk 1 above)
Comment (frankbu) [reply operator/cmd/mesh/install.go:207]: IIUC this should get done when an istiod is installed, not when just a gateway is being installed. Note that this isn't done at all when `istioctl manifest generate` is used instead of `istioctl install`, so it really should never matter? I must admit that this default webhook code seems pretty complicated and I'm not sure I understand if it's really working properly in all cases

File: istioctl/pkg/tag/generate_test.go (hunk 3 above)
Comment (frankbu) [reply istioctl/pkg/tag/generate_test.go]: You're right ... my brain isn't working so well today. I wanted to quickly test the case of a good URL, but that would require an injection webhook configured with a validation url, which never happens anyway. I think the only thing that matters is that this fix is changing injection URLs (which are always wrong), into a validation URLs. I changed the test. PTAL

File: operator/cmd/mesh/install.go (hunk 1 above)
Comment (howardjohn) [reply operator/cmd/mesh/install.go:207]: Yeah fair point on generate vs install. My concern was

control cluster: install full
remote cluster: install just gateway

But is the 'remote cluster' case still meeting `pilotEnabled` and it is just not literally setting up the Istiod deployment?

**Review by howardjohn — APPROVED** [review]

File: operator/cmd/mesh/install.go (hunk 1 above)
Comment (frankbu) [reply operator/cmd/mesh/install.go:207]: Hmm, not sure. In the docs, we are using `istioctl manifest generate` on the remote cluster, not sure why. Maybe workaround for another issue? If I have some spare cycles next week, I'll look into this some more.

**Review by esnible — APPROVED** [review]
LGTM
