### PR TITLE
Account for the service scope when generating EDS

### LINKED ISSUE #58139: Ambient MC Test Failure RemoveAddWaypoint
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

TestRemoveAddWaypoint fails with: pstream connect error or disconnect/reset before headers. reset reason: connection termination

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/57644/integ-ambient-mc_istio/1984022343852232704

### Version

```Text
master
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by krinkinmu**
**Please provide a description of this PR:**

Running ambient tests in multi-network environment I realized that when we generate EDS for waypoints in multi-network setups we always include endpoints from remote clusters/networks, regardless of the service scope. That's why we've never actually check service scope in the EDS code.

This change adds ServiceScope function to AmbientIndexes interface. The function returns the service scope for a given service. I then use that function when when we create EndpointBuilder to find and cache service scope.

And finally, I use the service scope, when it's set, to filter out endpoints from remote clusters when the service scope is not Global.

Fixes #58139

+cc @therealmitchconnors @keithmattix @jaellio

### CODE REVIEW

File: pilot/pkg/xds/endpoints/endpoint_builder.go [hunk 1]
```diff
@@ -175,6 +180,18 @@ func (b *EndpointBuilder) populateFailoverPriorityLabels() {
...
 
+func (b *EndpointBuilder) populateAmbientServiceInfo() {
+	if !b.ServiceFound() {
+		return
+	}
+
+	svc := fmt.Sprintf("%s/%s", b.service.Attributes.Namespace, b.hostname)
+	b.serviceInfo = b.push.ServiceInfo(svc)
+	if b.serviceInfo == nil {
+		log.Debugf("can not find service scope for %s while operating with ambient multicluster enabled", svc)
```
Comment (keithmattix) [inline pilot/pkg/xds/endpoints/endpoint_builder.go]:
```suggestion
		log.Debugf("can not find ServiceInfo for %s while operating with ambient multicluster enabled", svc)
```

File: pilot/pkg/xds/endpoints/ep_filters_test.go [hunk 2]
```diff
@@ -678,6 +678,7 @@ func TestEndpointsByNetworkFilter_SkipLBWithHostname(t *testing.T) {
 }
 
 func TestEndpointsByNetworkFilter_AmbientMuiltiNetwork(t *testing.T) {
+	test.SetForTest(t, &features.EnableAmbient, true)
 	test.SetForTest(t, &features.EnableAmbientMultiNetwork, true)
 	test.SetForTest(t, &features.EnableAmbientWaypointMultiNetwork, true)
```
Comment (keithmattix) [inline pilot/pkg/xds/endpoints/ep_filters_test.go:683]: How did these flag take effect before without EnableAmbient?

Comment (krinkinmu) [reply pilot/pkg/xds/endpoints/ep_filters_test.go:683]: The code does not check the dependencies between the flags. E.g., when we trying to figure out if it's an multinetwork ambient or not, we just check EnableAmbientMultiNetwork flag and don't check the EnableAmbient flag. The same for EnableAmbientWaypointMultiNetwork.

So for code to work, you often don't need all the flags to be set, just those that enable the code you're testing.

The reason why I had to test this flag now is because I added a bit to the EndpointBuilder that depends on ambient index being available. When EnableAmbient isn't set, the initialization code will not set up ambient index, and as a result this code will fail with some nil pointer dereference.

Comment (keithmattix) [reply pilot/pkg/xds/endpoints/ep_filters_test.go:683]: Ahh right; the dependencies are in the env var layer
