### PR TITLE
Transform destination port rules to header rules

### LINKED ISSUE #41204: [ambient] authz port matching not respected
### Bug Description

Following the Get Started Ambient [guide](https://istio.io/latest/blog/2022/get-started-ambient/#secure-application-access), it looks like the port match is not respected. 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  generation: 2
  name: productpage-viewer
  namespace: default
  resourceVersion: "20035695"
  uid: 50c8e232-2b6b-4137-b93e-06350502383a
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/sleep
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    to:
    - operation:
        ports:
        - "9080"
  selector:
    matchLabels:
      app: productpage
```

# this is supposed to work
❯ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1
command terminated with exit code 52
# this should fail with an empty reply
❯ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/
command terminated with exit code 52

Logs from the ztunnel: 
```
istio-proxy [2022-09-27T18:28:59.313Z] "- - -" 0 - - rbac_access_denied_matched_policy[none] "-" 233 0 1 - "-" "-" "-" "-" "-" - - 10.64.135:15008 10.64.3.51:45702 - - capture inbound listener
```

### Version

```prose
istioctl version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (2 proxies)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ymesika**
**Please provide a description of this PR:**

Fixes #41204 when Waypoint proxy is deployed.
Tranforming destination port permission rules to header rules that checks the suffix of the authority header's value.

### CODE REVIEW

File: pilot/pkg/security/authz/model/generator.go [hunk 1]
```diff
@@ -181,8 +181,17 @@ func (requestPresenterGenerator) principal(key, value string, forTCP bool) (*rba
 
 type requestHeaderGenerator struct{}
 
-func (requestHeaderGenerator) permission(_, _ string, _ bool) (*rbacpb.Permission, error) {
-	return nil, fmt.Errorf("unimplemented")
+func (requestHeaderGenerator) permission(key, value string, forTCP bool) (*rbacpb.Permission, error) {
```
Comment (howardjohn) [inline pilot/pkg/security/authz/model/generator.go:184]: does this impact non-ambient cases?

File: pilot/pkg/networking/plugin/authz/authorization.go [hunk 2]
```diff
@@ -50,6 +50,7 @@ func NewBuilderSkipIdentity(actionType ActionType, push *model.PushContext, prox
 		IsCustomBuilder: actionType == Custom,
 		Logger:          &builder.AuthzLogger{},
 		SkippedIdentity: skipped,
+		IsAmbient:       proxy.IsAmbient(),
```
Comment (howardjohn) [inline pilot/pkg/networking/plugin/authz/authorization.go:53]: is it for all ambient? or only ztunnel?

**Review by howardjohn — COMMENTED** [review]
Seems reasonable, can we add some tests though?

File: pilot/pkg/networking/plugin/authz/authorization.go (hunk 2 above)
Comment (ymesika) [reply pilot/pkg/networking/plugin/authz/authorization.go:53]: Only the waypoint adds the authz as an http filter which is the case covered by this PR.

File: pilot/pkg/security/authz/model/generator.go (hunk 1 above)
Comment (ymesika) [reply pilot/pkg/security/authz/model/generator.go:184]: No, the header generator is added in non-ambient under the prinicipals rules.

File: pilot/pkg/networking/plugin/authz/authorization.go (hunk 2 above)
Comment (ymesika) [reply pilot/pkg/networking/plugin/authz/authorization.go:53]: So although flag is true for ztunnel the generators are not executed because for Ztunnel it's listener filter.

**Comment by ymesika** [comment]
Still relevant

**Review by dhawton — APPROVED** [review]
LGTM

**Review by howardjohn — COMMENTED** [review]
This makes sense but there should be a test in `tests/integration/` that failed without this PR and passes with it. Can you add one in a followup maybe?

**Comment by linsun** [comment]
Thanks John!  I was thinking the same too - opened https://github.com/istio/istio/issues/42208 to track it
