### PR TITLE
consolidate k8s registry bootstrap

### LINKED ISSUE #28715: ServiceEntry cannot select Pod in other clusters
**Bug description**

Given two (primary) clusters, a Pod in each cluster labeled `app: helloworld`, and a ServiceEntry like this in each cluster:

```yaml
kind: ServiceEntry
metadata:
  name: cluster-select-se
spec:
  resolution: STATIC
  location: MESH_INTERNAL
  hosts:
  - helloworld.multicluster
  ports:
  - number: 5000
    name: https
    protocol: TLS
  workloadSelector:
    labels:
      app: helloworld
```

A `sleep` pod in each cluster only has endpoints for the `helloworld` Pod in the local cluster. The same behavior can be expected in a primary-remote scenario. 

We only setup the WorkloadHandler on the "primary" k8s registry:

https://github.com/istio/istio/blob/89850ae760e3fefb80955b3318a0d41b633dd09f/pilot/pkg/bootstrap/servicecontroller.go#L62-L65

but do not create this coupling for multi-cluster registries: 

https://github.com/istio/istio/blob/89850ae760e3fefb80955b3318a0d41b633dd09f/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L128-L132

A WIP PR: #28538 (also have a local-only branch that puts this into the aggregate serviceregistry)

**Expected behavior**

`workloadSelector` selects Pods from all clusters.

**Steps to reproduce the bug**

1.8-alpha.9bf204e92d

**How was Istio installed?**

Following latest 1.8 multicluster guide. 

**Environment where bug was observed (cloud vendor, OS, etc)**
 
GKE

### LINKED ISSUE #28779: Multicluster: namespace controller should be run only by leader istiod
**Bug description**

Currently, for the primary cluster, namespace controller is only run by leader to maintain root-certificate. However, for multicluster scenario, it is run by all istiod instances, there maybe some conflicts.

### PR DESCRIPTION
**Pull request by stevenctl**
The "local" or "config" cluster should not be treated specially. This PR:
* Consolidates bootstrap logic
* Wires up WorkloadInstances handlers for all clusters (helps fix #28715)
  * additional work is needed to handle:
    * multi-network; the cross-registry indexes are by IP but not network
    * cluster removal

fixes #28779

This bootstrap is more consistent with what we do in our unit tests:
https://github.com/istio/istio/blob/2d751a53587296991bf6961910c3b40c741471e7/pilot/pkg/xds/fake.go#L197-L208

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 1]
```diff
@@ -51,107 +52,111 @@ type kubeController struct {
...
+
+	// TODO move instance cache out of registries
+	if m.serviceEntryStore != nil && features.EnableServiceEntrySelectPods {
+		// Add an instance handler in the kubernetes registry to notify service entry store about pod events
+		_ = kubeRegistry.AppendWorkloadHandler(m.serviceEntryStore.WorkloadInstanceHandler)
+	}
+
+	if m.serviceEntryStore != nil && features.EnableK8SServiceSelectWorkloadEntries {
+		// Add an instance handler in the service entry store to notify kubernetes about workload entry events
+		_ = m.serviceEntryStore.AppendWorkloadHandler(kubeRegistry.WorkloadInstanceHandler)
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:143]: We support SE/WLE only in primary cluster now

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 2]
```diff
@@ -51,107 +52,111 @@ type kubeController struct {
...
 		secretNamespace:       secretNamespace,
-		endpointMode:          opts.EndpointMode,
 		syncInterval:          opts.GetSyncInterval(),
 	}
 	mc.initSecretController(kc)
 
 	return mc, nil
 }
 
+func (m *Multicluster) EnableCertPatch(caBundlePath string, fetchCaRoot func() map[string]string) {
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:106]: add some comments

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Looks this is a good direction, but the registry order matters

File: pilot/pkg/bootstrap/servicecontroller.go [hunk 3]
```diff
@@ -35,6 +35,10 @@ func (s *Server) ServiceController() *aggregate.Controller {
 // initServiceControllers creates and initializes the service controllers
 func (s *Server) initServiceControllers(args *PilotArgs) error {
 	serviceControllers := s.ServiceController()
+
+	s.serviceEntryStore = serviceentry.NewServiceDiscovery(s.configController, s.environment.IstioConfigStore, s.XDSServer)
+	serviceControllers.AddRegistry(s.serviceEntryStore)
```
[the remark this answers is not in the document]
Comment (stevenctl) [reply pilot/pkg/bootstrap/servicecontroller.go:40]: Can you explain why?

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 1 above)
Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:143]: What is the reason? Shouldn't SE be able to select a Pod in any cluster?

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 4]
```diff
@@ -51,107 +52,112 @@ type kubeController struct {
...
+
+	if m.serviceEntryStore != nil && features.EnableK8SServiceSelectWorkloadEntries {
+		// Add an instance handler in the service entry store to notify kubernetes about workload entry events
+		_ = m.serviceEntryStore.AppendWorkloadHandler(kubeRegistry.WorkloadInstanceHandler)
+	}
 
-	go kubectl.Run(stopCh)
+	go kubeRegistry.Run(stopCh)
 	webhookConfigName := strings.ReplaceAll(validationWebhookConfigNameTemplate, validationWebhookConfigNameTemplateVar, m.secretNamespace)
 	if m.fetchCaRoot != nil {
```
Comment (stevenctl) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:148]: This logic to only create the namespace controller for remote clusters shouldn't be necessary. We can consolidate `initNamespaceController` + `initSidecarInjector` as well. Might be different for the cert patch though.. not sure why these things are coupled together.. seems like`caBundlePath` corresponds to patch cert, and `fetchCaRoot` is for namespace controller. 

Also:

https://github.com/istio/istio/blob/d49931e2e89093cefcfe2ab58d928ed190539bd5/pilot/pkg/bootstrap/server.go#L1037

do we need to do leader election for the multicluster namespace controllers as well? In a multi-primary setup we're currently having all primaries perform this for all other clusters (regardless if the other clusters are primary or remote).  

cc @irisdingbj can you provide some clarity?

File: pilot/pkg/bootstrap/servicecontroller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (stevenctl) [reply pilot/pkg/bootstrap/servicecontroller.go:41]: Yeah after looking at the usages of the registries slice in the aggregate controller... the _only_ possible reason is precedence for `GetProxyWorkloadLabels` – but really everything at the aggregate should just be merged.

[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/bootstrap/servicecontroller.go:40]: Also `GetService` serviceentry store will be selected first.  Ideally, this order should not matter, but it is risky to do this change atm.

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 4 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:147]: We do need leader protect for this as well. Since it is there, i do not point it here. Just filed a bug yesterday. https://github.com/istio/istio/issues/28779

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:142]: Yeah, the se should be able to select pods across clusters. What i mean is that we only watch SE/WLE from the primary cluster, so these handlers should be applied once rather than multi times. it may generate multiple duplicate service instances.

File: pilot/pkg/bootstrap/servicecontroller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (stevenctl) [reply pilot/pkg/bootstrap/servicecontroller.go:40]: Are you saying we don't want ServiceEntry store to be selected first? If I'm reading correctly, the current logic puts the service entry store after the "main" kube registry..

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 1 above)
Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:142]: We definitely need all the kube registries to have a handler so the SE store can read the Pods. 

Good point about all the kube controllers having the workload entry instances.. could cause dupes.

File: pilot/pkg/bootstrap/servicecontroller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/bootstrap/servicecontroller.go:40]: Yes

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:142]: Yeah, feel free to ping me when this is resolved

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 5]
```diff
@@ -51,107 +53,142 @@ type kubeController struct {
 
 // Multicluster structure holds the remote kube Controllers and multicluster specific attributes.
 type Multicluster struct {
-	WatchedNamespaces string
-	DomainSuffix      string
-	ResyncPeriod      time.Duration
+	// serverID of this pilot instance used for leader election
+	serverID string
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:57]: nit:  we can use `hostname+uid` either

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 6]
```diff
@@ -51,107 +53,142 @@ type kubeController struct {
...
+
 	serviceController *aggregate.Controller
+	serviceEntryStore *serviceentry.ServiceEntryStore
 	XDSUpdater        model.XDSUpdater
-	metrics           model.Metrics
-	endpointMode      EndpointMode
 
 	m                     sync.Mutex // protects remoteKubeControllers
 	remoteKubeControllers map[string]*kubeController
 	networksWatcher       mesh.NetworksWatcher
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:71]: do we still need this? check others as well

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 7]
```diff
@@ -51,107 +53,142 @@ type kubeController struct {
...
-	kubectl := NewController(clients, options)
+	kubeRegistry := NewController(client, options)
 
-	remoteKubeController.Controller = kubectl
-	m.serviceController.AddRegistry(kubectl)
+	remoteKubeController.Controller = kubeRegistry
+	m.serviceController.AddRegistry(kubeRegistry)
 
 	m.remoteKubeControllers[clusterID] = &remoteKubeController
+	firstCluster := len(m.remoteKubeControllers) == 1
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:138]: Compare `clusterID` to determine if this is primary cluster. We have passed the Options when constructing Multicluster

**Review by hzxuzhonghu — COMMENTED** [review]
@howardjohn @ramaraochavali need more eyes on it

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 6 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:71]: I looked wrong

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 8]
```diff
@@ -51,107 +53,145 @@ type kubeController struct {
...
-	remoteKubeController.Controller = kubectl
-	m.serviceController.AddRegistry(kubectl)
+	log.Infof("Initializing Kubernetes service registry %q", options.ClusterID)
+	kubeRegistry := NewController(client, options)
+	m.serviceController.AddRegistry(kubeRegistry)
+	m.remoteKubeControllers[clusterID] = &kubeController{
+		Controller: kubeRegistry,
+		stopCh:     stopCh,
+	}
+	localCluster := m.opts.ClusterID == clusterID
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:137]: local cluster is confusing, we can make istiod deployed anywhere, and provide a kubeconfig for it.

**Review by hzxuzhonghu — COMMENTED** [review]
Is the test failure related?

**Comment by stevenctl** [comment]
It's pretty consistent so it must be. Going to try to side by side with master because this shouldn't change single cluster behavior

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go (hunk 8 above)
Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:137]: Yeah, the other name would be "configCluster" I guess? Not sure how to capture that this is the "main" cluster istiod is configured to use. It can't be called primaryCluster since that has other implications https://istio.io/latest/docs/ops/deployment/deployment-models/#control-plane-models

**Comment by hzxuzhonghu** [comment]
Sorry for the delay

**Review by hzxuzhonghu — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

File: pilot/pkg/serviceregistry/kube/controller/multicluster.go [hunk 9]
```diff
@@ -51,107 +53,147 @@ type kubeController struct {
...
+	// Patch cert if a webhook config name is provided.
+	// This requires RBAC permissions - a low-priv Istiod should not attempt to patch but rely on
+	// operator or CI/CD
 	webhookConfigName := strings.ReplaceAll(validationWebhookConfigNameTemplate, validationWebhookConfigNameTemplateVar, m.secretNamespace)
-	if m.fetchCaRoot != nil {
-		nc := NewNamespaceController(m.fetchCaRoot, clients)
-		go nc.Run(stopCh)
-		go webhooks.PatchCertLoop(features.InjectionWebhookConfigName.Get(), webhookName, m.caBundlePath, clients.Kube(), stopCh)
-		valicationWebhookController := webhooks.CreateValidationWebhookController(clients, webhookConfigName,
+	if features.InjectionWebhookConfigName.Get() != "" && m.caBundlePath != "" && !localCluster {
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: @stevenctl @hzxuzhonghu Should n't this patching happen only for centralIstiod or externalIstiod model? With out that condition, multi cluster installation with control plane in primary cluster is trying to patch webhook in secondary cluster. This is not used to be like that earlier. Is it intentional?

Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: We're trying to make our remote clusters be "istiodless", our integration tests are setup to run in this way. I think we need more work to do that properly, like specifying that the cluster is a remote by some annotation in the remote secret.

Comment (ramaraochavali) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: Ok. So for now, what do you suggest? We are trying to upgrade to the new version and it is trying to patch. Should we provide the necessary permissions and let it patch? Is there any work around?

Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: We can probably guard this with `features.ExternalIstioD || features.CentralIstioD` for now, AFAIK nobody is focused on istiod-less remotes for 1.9, and it will probably require one of those flags anyway.

Comment (stevenctl) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: Also, are you trying to upgrade a multi-cluster setup?

Comment (ramaraochavali) [reply pilot/pkg/serviceregistry/kube/controller/multicluster.go:185]: Yes
