### PR TITLE
Fix ENABLE_ENHANCED_RESOURCE_SCOPING bug

### LINKED ISSUE #42173: CR is sometime ignored when controller is deployed with enhanced resource scoping feature
### Bug Description

Hello everyone,
While I was tinkering with the new enhanced resource scoping feature of Istio 1.16.0 I noticed one issue.
I suspect that there is a race condition which leads to some custom resources to be ignored under certain circumstances.
So far, I managed to pinpoint the issue to this scenario:
1. Create istio-system namespace without any label
2. Do in parallel:
    - Deploy of Istio controller with ENABLE_ENHANCED_RESOURCE_SCOPING=true in istio-system. Use discovery selector match-labels on "test=true"
    - Deploy of Istio Ingress GW in istio-system
    - Deploy of EF on listener to add socket options to GW listener (I have an EnvoyFilter but I presume it can be reproduced with other CR too).
    - Label istio-system namespace with the same selector we use in Istio discovery selector config ("test=true")
3. After the parallel steps have ended, deploy a GW CR just to trigger the creation of the listeners in proxies.
4. If you are unlucky you end up with a deployment where the EF CR was ignored. ingressgw proxy-config did not receive socket_options patch.
I have verified that:
    - Restarting the IngressGW deployment does not fix the issue.
    - Restarting the controller will fix the issue and the socket options patch will now be applied 
correctly to the gw listener.
    - Triggering a full-push does not fix the issue.
    -  Removing and reapplying the CR fixes the issue

Controller log:  [log_controller2.log](https://github.com/istio/istio/files/10104613/log_controller2.log)

Keep in mind that if the namespace is already labelled before the deployment took place or if the enhanced resource scoping feature is disabled then the issue will not be there.

I'm trying to come up with some easy steps/script to reproduce it, but it is taking some time. I will add the steps asap.
In the meantime, I'm opening this issue to see if someone already has any idea on what is going on here.

### Version

```prose
client version: 1.15.3
control plane version: 1.16
data plane version: 1.16.0 (1 proxies)

kubectl version --short
Client Version: v1.19.2
Server Version: v1.25.2
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Fix #42173

when ENABLE_ENHANCED_RESOURCE_SCOPING enabled, namespace selected/deselected we should  trigger full push so that the CRs within the namespace will be handled correctly

### CODE REVIEW

**Comment by LithiumSR** [comment]
Thank you @hzxuzhonghu :)
I will verify the fix on my end and let you know asap

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go [hunk 1]
```diff
@@ -54,6 +55,12 @@ func (c *Controller) initDiscoveryNamespaceHandlers(
 			if discoveryNamespacesFilter.NamespaceCreated(ns.ObjectMeta) {
 				c.queue.Push(func() error {
 					c.handleSelectedNamespace(endpointMode, ns.Name)
+					if features.EnableEnhancedResourceScoping {
+						c.opts.XDSUpdater.ConfigUpdate(&model.PushRequest{
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: why do we need to push for a new namespace? isn't there nothing in the namespace to begin with anyways?

**Review by howardjohn — COMMENTED** [review]
Can we add tests

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: >why do we need to push for a new namespace? isn't there nothing in the namespace to begin with anyways?

Look into it, deeper I agree with you, I did this just to keep consistent with `handleSelectedNamespace`. Seems handleSelectedNamespace is also redundant

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: Ah, the reason it was here is because namespace handler can take sometime.

If removed TestController_ServiceWithFixedDiscoveryNamespaces flakes

Comment (dddddai) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: I'm not sure if triggering a full push is enough
For example ServiceEntry has its own controller for managing state, I think we should trigger events for SE(like service/pod/endpoints) as well to make the controller reconcile

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: I think so, need to do that in both handle selected and deselected function

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:59]: @dddddai Added

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 2]
```diff
@@ -233,7 +233,8 @@ type Controller struct {
 	imports serviceImportCache
 	pods    *PodCache
 
-	handlers model.ControllerHandlers
+	handlers                   model.ControllerHandlers
+	namespaceDiscoveryHandlers []func(ns string, event model.Event)
```
Comment (dddddai) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:237]: Where do the handlers get called?

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/controller.go:237]: done

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go [hunk 3]
```diff
@@ -72,12 +76,18 @@ func (c *Controller) initDiscoveryNamespaceHandlers(
 			membershipChanged, namespaceAdded := discoveryNamespacesFilter.NamespaceUpdated(oldNs.ObjectMeta, newNs.ObjectMeta)
 			if membershipChanged {
 				handleFunc := func() error {
+					var event model.Event
 					if namespaceAdded {
+						event = model.EventAdd
 						c.handleSelectedNamespace(endpointMode, newNs.Name)
 					} else {
+						event = model.EventAdd
```
Comment (kfaseela) [inline pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:83]: hope this is correct? same event for both the cases?

**Comment by howardjohn** [comment]
Sorry didn't get a chance to take a look yet, maybe @ramaraochavali can. Or I should be less busy next week (oncall this week)

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go [hunk 4]
```diff
@@ -64,17 +74,25 @@ func (c *Controller) initDiscoveryNamespaceHandlers(
...
 						c.handleSelectedNamespace(endpointMode, newNs.Name)
-						return nil
-					}
-				} else {
-					handleFunc = func() error {
+					} else {
+						event = model.EventDelete
 						c.handleDeselectedNamespace(kubeClient, endpointMode, newNs.Name)
-						return nil
 					}
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:85]: This should be abstracted in to a function and call it from both places.

May be should we call this from handleSelectedNamespace and handleDeselectedNamespace so that we do not miss calling this?

File: pilot/pkg/serviceregistry/kube/controller/controller_test.go [hunk 5]
```diff
@@ -1504,6 +1505,207 @@ func TestController_ServiceWithChangingDiscoveryNamespaces(t *testing.T) {
 	}
 }
 
+func TestController_ENABLE_RESOURCE_SCOPING(t *testing.T) {
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller_test.go:1508]: nit: TestController_ENABLE_RESOURCE_SCOPING -> TestControllerEnableResourceScoping?

File: pilot/pkg/serviceregistry/serviceentry/namespace_handler.go [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+// NamespaceDiscoveryHandler is to handle namespace selected or deselected because of discoverySelectors change,
+// rather than namespace add/update/delete event triggered from namespace informer.
+func (s *Controller) NamespaceDiscoveryHandler(namespace string, event model.Event) {
+	if event == model.EventDelete {
+		log.Debugf("Handle event namespace %s deselected", namespace)
+	} else {
+		log.Debugf("Handle event namespace %s selected", namespace)
+	}
+
+	cfgs, _ := s.store.List(gvk.WorkloadEntry, namespace)
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/serviceentry/namespace_handler.go:31]: Should this be moved to else block?

File: releasenotes/notes/42173.yaml [hunk 7]
```diff
@@ -0,0 +1,12 @@
...
+area: traffic-management
+
+# issue is a list of GitHub issues resolved in this note.
+issue:
+  - https://github.com/istio/istio/issues/42173
+  - 42173
+
+releaseNotes:
+  - |
+    **Fixed** bug when set `ENABLE_ENHANCED_RESOURCE_SCOPING=true`, istio and k8s gateway api resources will not be handled correctly when namespace selected or deselected by discovery selector or namespace label change.
```
Comment (ramaraochavali) [inline releasenotes/notes/42173.yaml:12]: nit: or namespace label change -> or namespace label is changed

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go (hunk 4 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:85]: >May be should we call this from handleSelectedNamespace and handleDeselectedNamespace so that we do not miss calling this?

This will introduce redundant push triggered when multi namespaces need to be handled in case  discoverySelectors changed

File: pilot/pkg/serviceregistry/serviceentry/namespace_handler.go (hunk 6 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/serviceentry/namespace_handler.go:31]: Why? We need to handle this for delete as well, so could remove the cached instances.

File: releasenotes/notes/42173.yaml (hunk 7 above)
Comment (hzxuzhonghu) [reply releasenotes/notes/42173.yaml:12]: ok

File: pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go (hunk 4 above)
Comment (ramaraochavali) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:85]: But, they will be merged any way because of debouncing. But you can leave it but better to abstract it in to a func and call it.

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:85]: Would think about abstraction

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go:81]: moved `namespaceDiscoveryHandlers`

**Review by ramaraochavali — COMMENTED** [review]
LGTM @howardjohn to take a look

**Review by kfaseela — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Thanks for all your reviews
