### PR TITLE
Fix user gateway k8s setting, add extended UTs

### LINKED ISSUE #20033: Istioctl enable ILB Gateway
**Bug description**

**Expected behavior**

`istioctl manifest generate --set values.gateways.istio-ilbgateway.enabled=true` creates the appropriate config

**Steps to reproduce the bug**

`istioctl manifest generate --set values.gateways.istio-ilbgateway.enabled=true`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.3

**How was Istio installed?**

`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS

Additionally,  using `--set unvalidatedValues.gateways.istio-ilbgateway.enabled=true` does not create an ILB configuration as well.

### PR DESCRIPTION
**Pull request by ostromart**
Fixes https://github.com/istio/istio/issues/20033.
@howardjohn lmk if the gateways.yaml test input is realistic or missing something, especially for ILB.

### CODE REVIEW

File: operator/pkg/component/component.go [hunk 1]
```diff
@@ -653,7 +653,7 @@ func renderManifest(c IstioComponent, cf *CommonComponentFields) (string, error)
 		scope.Infof("Initial manifest with merged values:\n%s\n", my)
 	}
 	// Add the k8s resources from IstioOperatorSpec.
-	my, err = cf.Translator.OverlayK8sSettings(my, cf.InstallSpec, cf.componentName, cf.index)
+	my, err = cf.Translator.OverlayK8sSettings(my, cf.InstallSpec, cf.componentName, cf.resourceName, cf.index)
```
Comment (richardwxn) [inline operator/pkg/component/component.go]: where is the resource name populated? I can see we populate that when we create the gateway components, what about other components?

**Review by howardjohn — APPROVED** [review]

File: operator/pkg/component/component.go (hunk 1 above)
Comment (ostromart) [reply operator/pkg/component/component.go]: if it's not populated we end up getting the default from the translate config file.
