### PR TITLE
Guard pilot debug api against indefinite locks

### LINKED ISSUE #18519: debug/config_distribution is not guarded against empty string
in certain scenarios, the pilot debug/config_distribution api can cause pilot to crash.  This happens when the AckedNonce string is shorter than 12 characters.

### PR DESCRIPTION
**Pull request by therealmitchconnors**
Fixes #18519

### CODE REVIEW

File: pilot/pkg/proxy/envoy/v2/debug.go [hunk 1]
```diff
@@ -230,17 +230,22 @@ func (s *DiscoveryServer) distributedVersions(w http.ResponseWriter, req *http.R
...
-				// TODO: handle skipped nodes
-				results = append(results, SyncedVersions{
-					ProxyID:         con.node.ID,
-					ClusterVersion:  s.getResourceVersion(con.ClusterNonceAcked, resourceID, knownVersions),
-					ListenerVersion: s.getResourceVersion(con.ListenerNonceAcked, resourceID, knownVersions),
-					RouteVersion:    s.getResourceVersion(con.RouteNonceAcked, resourceID, knownVersions),
-				})
-			}
-			con.mu.RUnlock()
+			// wrap this in independent scope so that panic's don't bypass Unlock...
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/debug.go]: won't a panic crash the whole program anyways? or it's just in the handler which catches the panic?

File: pilot/pkg/proxy/envoy/v2/debug.go [hunk 2]
```diff
@@ -230,17 +230,22 @@ func (s *DiscoveryServer) distributedVersions(w http.ResponseWriter, req *http.R
...
+			func() {
+				con.mu.RLock()
+				defer con.mu.RUnlock()
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/debug.go]: this seems a bit weird to me. We will still hold the con lock if we crash anyways right?

There is no reason we should panic in this code, so it seems like this func() thing is an unnecessary safeguard?

File: pilot/pkg/proxy/envoy/v2/debug.go (hunk 1 above)
Comment (therealmitchconnors) [reply pilot/pkg/proxy/envoy/v2/debug.go]: yes, just the handler thread panics, but it keeps the read lock open, which is bad.  Theoretically, the string guarding added in this PR should make panic impossible, but I'd rather be safe here, since a panic in any of these routines will stop traffic.

File: pilot/pkg/proxy/envoy/v2/debug.go (hunk 2 above)
Comment (therealmitchconnors) [reply pilot/pkg/proxy/envoy/v2/debug.go]: I have covered the only known source of panics.  This is guarding against the unknown ones...

File: pilot/pkg/proxy/envoy/v2/debug.go (hunk 1 above)
Comment (howardjohn) [reply pilot/pkg/proxy/envoy/v2/debug.go]: you could say the same about 95% of the pilot code though , including every other debug function, which makes me feel like this is not needed here

Comment (therealmitchconnors) [reply pilot/pkg/proxy/envoy/v2/debug.go]: I removed the func wrapper.
