### PR TITLE
Reject invalid jwks and add integration test for jwt rules

### LINKED ISSUE #24629: Istio generates invalid JWT authentication filter config when remote JWKS endpoint is unavailable
**Bug description**

When istiod attempted to fetch the JWKS for an issuer specified in a JWT rule, the issuer service responded with a 502.

The istio-proxy pod on our service is now rejecting the LDS config with the error

```
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected:
Error adding/updating listener(s) virtualInbound:
Proto constraint validation failed (JwtAuthenticationValidationError.Providers[key]: ["embedded message failed validation"]
| caused by JwtProviderValidationError.LocalJwks: ["embedded message failed validation"]
| caused by DataSourceValidationError.InlineString: ["value length must be at least " '\x01' " bytes"])
```

The offending config is

```
    local_jwks {
      inline_string: ""
    }
```

This is particularly problematic because now the proxy container cannot become ready, so restarting the deployment hangs.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Istio uses the last good JWKS fetched from that URL. If no good JWKS has been fetched, Istio applies a valid config that results in no JWTs from that issuer being validated. I would say this could be an empty JWKS `{"keys":[]}` except that I seem to remember (in 1.4, at least) these also break the JWT authentication filter - that may have been fixed since though!

**Steps to reproduce the bug**

On a fresh cluster I ran

```console
$ istioctl install

$ kubectl label namespace default istio-injection=enabled

$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.6/samples/httpbin/httpbin.yaml

$ kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: https://example.com
EOF

$ istioctl proxy-status
NAME                                 CDS        LDS                            EDS        RDS          PILOT                       VERSION
httpbin-78b9f6c986-gg55q.default     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-7599c64cb4-lj2qs     1.6.2
...

$ kubectl logs deployment/httpbin istio-proxy
...
2020-06-12T11:00:22.402775Z	warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) virtualInbound: Proto constraint validation failed (JwtAuthenticationValidationError.Providers[key]: ["embedded message failed validation"] | caused by JwtProviderValidationError.LocalJwks: ["embedded message failed validation"] | caused by DataSourceValidationError.InlineString: ["value length must be at least " '\x01' " bytes"]): providers {
  key: "origins-0"
  value {
    issuer: "https://example.com"
    local_jwks {
      inline_string: ""
    }
    payload_in_metadata: "https://example.com"
  }
}
rules {
  match {
    prefix: "/"
  }
  requires {
    requires_any {
      requirements {
        provider_name: "origins-0"
      }
      requirements {
        allow_missing {
        }
      }
    }
  }
}

$ kubectl rollout restart deployment/httpbin
deployment.apps/httpbin restarted

$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-6db444f69-45w8t    1/2     Running   0          41s
httpbin-78b9f6c986-gg55q   2/2     Running   0          37m
```

The new pod never becomes ready because the istio-proxy container is not ready.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```console
$ istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (4 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```console
$ istioctl install
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Initially observed in EKS, but reproduced easily on Docker for Mac.

### PR DESCRIPTION
**Pull request by xulingqing**
Fix of [#24629](https://github.com/istio/istio/issues/24629)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: tests/integration/security/jwt_test.go [hunk 1]
```diff
@@ -270,6 +270,84 @@ func TestRequestAuthentication(t *testing.T) {
 		})
 }
 
+func TestRequestAuthenticationWithInvalidJwks(t *testing.T) {
```
Comment (howardjohn) [inline tests/integration/security/jwt_test.go:273]: Why not just extend TestRequestAuthentication? Then we don't need a new namespace, 2 new pods, spin everything up, tear down, etc. Adds  a lot of test time

File: pilot/pkg/security/authn/v1beta1/policy_applier.go [hunk 2]
```diff
@@ -258,6 +258,7 @@ func convertToEnvoyJwtConfig(jwtRules []*v1beta1.JWTRule) *envoy_jwt.JwtAuthenti
 			jwtPubKey, err = model.GetJwtKeyResolver().GetPublicKey(jwtRule.JwksUri)
 			if err != nil {
 				log.Errorf("Failed to fetch jwt public key from %q: %s", jwtRule.JwksUri, err)
+				jwtPubKey = `{"keys":[ {"e":"AQAB","kid":"abc","kty":"RSA","n":"failedToFetchJwtPubKey"}]}`
```
Comment (howardjohn) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:261]: What is this?

Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:261]: This is a fake jwt to resolve the envoy hanging when inline_jwks is empty. The problem is mentioned [here](https://github.com/istio/istio/issues/24629) Thanks.

Comment (howardjohn) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:261]: Introducing some magic bad jwt seems problematic. It at least needs a huge comment in the code explaining why we are doing it, and why its safe.

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:261]: Add a comment about why we need this fake jwks (it doesn't block envoy start but would reject all requests with JWT token), and also add a TODO with your github username that this is a short or mid-term fix until we find a better way to handle this case.

File: pilot/pkg/security/authn/v1beta1/policy_applier_test.go [hunk 3]
```diff
@@ -727,6 +727,7 @@ func TestConvertToEnvoyJwtConfig(t *testing.T) {
 			in: []*v1beta1.JWTRule{
 				{
 					Issuer: "https://secret.foo.com",
+					Jwks: "",
```
Comment (yangminzhu) [inline pilot/pkg/security/authn/v1beta1/policy_applier_test.go:730]: why do we need this?

File: tests/integration/security/jwt_test.go (hunk 1 above)
Comment (yangminzhu) [reply tests/integration/security/jwt_test.go:273]: yes, as you're creating the new workload `f`, you can just put it in the existing TestRequestAuthentication.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 2 above)
Comment (howardjohn) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:261]: Why don't we just inject a deny?

**Comment by yangminzhu** [comment]
Can you include the issue id in the description so that it's clear what is being fixed here. thanks.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 2 above)
Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: I think @xulingqing did some investigation but the current Envoy JWT API doesn't provide an way to just deny a request without setting the jwks. And here is using a fake jwks to "workaround" this to achieve the effect of denying a request.

Comment (howardjohn) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: Is this a temporary workaround or permanent?

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: a temporary workaround.

@xulingqing can you update the comment to make it clear this is a temporary workaround, and the TODO is to find out a better way to solve this.

Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: Sure, working on it

Comment (incfly) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: `kid` can also be named to something more meaningful rather than `abc`? making debugging life easier.

**Review by yangminzhu — APPROVED** [review]

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 2 above)
Comment (fpesce) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: Hey @xulingqing could you make "n" be dynamic (not always same default value) and also more complex?
I'm afraid of an attacker being able to generate key material from the base64 decoding of the relatively some number that the modulo "n" would turn once "failedToFetchJwtPubKey" would be base64 decoded.

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: Thanks Francois! To make it more complex, you can encode the jwtRule.JwksUri or even the err in it, this also gives a nicer debugging message.

Comment (howardjohn) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: We should not make it dynamic on every push or it will result in draining in envoy. But agree with @fpesce in general

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: it should be the same on every push if we only include JwksUri

Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:263]: Sure, Thanks for pointing it out, Francois. I'm working on it.

File: pilot/pkg/model/test/mockopenidserver.go [hunk 4]
```diff
@@ -62,6 +62,8 @@ const (
 
 	JwtPubKeyExtraElements = `{ "keys": [ { "kid": "fakeKey1_1", "alg": "RS256", "kty": "RSA", "n": "abc", "e": "def", "bla": "blah" },
 			{ "kid": "fakeKey1_2", "alg": "RS256", "kty": "RSA", "n": "123", "e": "456", "bla": "blah" } ] }`
+
+	JwtPubKeyFakeJwks = `{"keys":[ {"e":"AQAB","kid":"abc","kty":"RSA","n":"failedToFetchJwtPubKey"}]}`
```
Comment (yangminzhu) [inline pilot/pkg/model/test/mockopenidserver.go:66]: this should be removed now.

File: tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+metadata:
+  name: "request-authn-for-f"
+  namespace: {{ .Namespace }}
+spec:
+  selector:
+    matchLabels:
+      app: f
+  jwtRules:
+  - issuer: "test-issuer-1@istio.io"
+    jwks: '{ "keys":[ {"e":"AQAB","kid":"abc","kty":"RSA","n":"failedToFetchJwtPubKey"}]}'
```
Comment (yangminzhu) [inline tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl:13]: Use example jwks URI here to make sure it is the same as if it's generated from the code, e.g. `"failedToFetchJwksForhttps://raw.githubusercontent.com/istio/istio/release-1.6/security/tools/jwt/samples/jwks.json"`

**Review by yangminzhu — CHANGES_REQUESTED** [review]

File: pilot/pkg/model/test/mockopenidserver.go (hunk 4 above)
Comment (xulingqing) [reply pilot/pkg/model/test/mockopenidserver.go:66]: sure

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 2 above)
Comment (williamaronli) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go]: Maybe in the future we can add salt (like. a random number with fixed seed)

Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go]: Hi Francois @fpesce and Yangmin @yangminzhu , I've tried to make the jwks dynamic by directly append issuer or jwksURI. But those none letter character like "/" will influence the parsing of jwks. Error logs is like:
```
2020-07-31T15:29:12.362507Z     warning envoy config    [external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) virtualInbound: Issuer 'test-issuer-1@istio.io' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error
```

Here are some methods I'm thinking of to make it dynamic.
1. extract letters from policy Name or Issuer field
2. encode any field to base64 and append

Do you have any suggestion?

Comment (fpesce) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go]: base64 encoding seems the best (as this field is ultimately base64 decoded). You can add random content in it too.

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go]: Can we use base64 here, you can add an extra `_` between `failedToFetchJwksFor` and the base64 string to make it a little more readable.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go [hunk 6]
```diff
@@ -216,6 +218,14 @@ func NewPolicyApplier(rootNamespace string,
 	}
 }
 
+// Remove all Non-Alphanumeric Characters from a jwksURI and append to "n"
+func createFakeJwks(jwksURI string) string {
+	encodedString := b64.URLEncoding.EncodeToString([]byte(jwksURI))
+	reg := regexp.MustCompile("[^a-zA-Z0-9]+")
```
Comment (yangminzhu) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: No need to replace if you're already using base64.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go [hunk 7]
```diff
@@ -216,6 +218,14 @@ func NewPolicyApplier(rootNamespace string,
...
+	processedString := reg.ReplaceAllString(encodedString, "")
+	return fmt.Sprintf(`{"keys":[ {"e":"AQAB","kid":"abc","kty":"RSA","n":"failedToFetchJwksFor%s"}]}`, processedString)
```
Comment (yangminzhu) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:226]: can we insert an extra `_`, i.e. `"failedToFetchJwksFor_%s"` to make it a bit more readable.

File: tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl [hunk 8]
```diff
@@ -0,0 +1,14 @@
...
+metadata:
+  name: "request-authn-for-f"
+  namespace: {{ .Namespace }}
+spec:
+  selector:
+    matchLabels:
+      app: f
+  jwtRules:
+  - issuer: "test-issuer-1@istio.io"
+    jwks: '{ "keys":[ {"e":"AQAB","kid":"abc","kty":"RSA","n":"failedToFetchJwtPubKeyhttpsrawgithubusercontentcomistioistiorelease16securitytoolsjwtsamplesjwksjson"}]}'
```
Comment (yangminzhu) [inline tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl:13]: Can you update to use an non-exist jwksUri instead of using jwks?

Comment (xulingqing) [reply tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl:13]: working on it. Thanks!

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 6 above)
Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: But I noticed base64 encoded string will still contains special character https://gobyexample.com/base64-encoding. it's safe to guarantee jwks n filed with only Alphanumeric Characters.

**Comment by yangminzhu** [comment]
On Mon, Aug 3, 2020 at 3:15 PM Linggg <notifications@github.com> wrote:

> *@xulingqing* commented on this pull request.
> ------------------------------
>
> In pilot/pkg/security/authn/v1beta1/policy_applier.go
> <https://github.com/istio/istio/pull/25934#discussion_r464690522>:
>
> > @@ -216,6 +218,14 @@ func NewPolicyApplier(rootNamespace string,
>  	}
>  }
>
> +// Remove all Non-Alphanumeric Characters from a jwksURI and append to "n"
> +func createFakeJwks(jwksURI string) string {
> +	encodedString := b64.URLEncoding.EncodeToString([]byte(jwksURI))
> +	reg := regexp.MustCompile("[^a-zA-Z0-9]+")
>
> But I noticed base64 encoded string will still contains special character
> https://gobyexample.com/base64-encoding. it's safe to guarantee jwks n
> filed with only Alphanumeric Characters.
>
Isn't `-` and `_` allowed in `n`?

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 6 above)
Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: `-` and `_` is allowed in `n` but not sure if it's valid if an `n` ends with dash.

File: tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl [hunk 9]
```diff
@@ -0,0 +1,14 @@
...
+metadata:
+  name: "request-authn-for-f"
+  namespace: {{ .Namespace }}
+spec:
+  selector:
+    matchLabels:
+      app: f
+  jwtRules:
+  - issuer: "test-issuer-1@istio.io"
+    jwksUri: "https://raw.githubusercontent.com/istio/istio/master/tests/common/jwt/jwksfake.json"
```
Comment (yangminzhu) [inline tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl:13]: Add a comment that this file is expected to not exist, better to rename the `jwksfake.json` to `jwks-not-exist.json`.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 6 above)
Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: Can you test if it is allowed to be end of `n`? I'm surprised if it doesn't support this...

And if you're doing this replacement, why would you need base64 anyway?

File: tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl (hunk 9 above)
Comment (xulingqing) [reply tests/integration/security/testdata/requestauthn/f-authn.yaml.tmpl:13]: Sure. Thanks for pointing it out.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 6 above)
Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: @xulingqing this is still not updated, have you tested it?

Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:224]: I've tested it and the n field can end with "-". I'm surperised why it didn't get  updated..

File: pilot/pkg/security/authn/v1beta1/policy_applier.go [hunk 10]
```diff
@@ -216,6 +217,12 @@ func NewPolicyApplier(rootNamespace string,
 	}
 }
 
+// Remove all Non-Alphanumeric Characters from a jwksURI and append to "n"
```
Comment (yangminzhu) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:220]: the comment is out-dated.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go [hunk 11]
```diff
@@ -15,6 +15,7 @@
 package v1beta1
 
 import (
+	b64 "encoding/base64"
```
Comment (yangminzhu) [inline pilot/pkg/security/authn/v1beta1/policy_applier.go:18]: just use "encoding/base64", no need to rename if it doesn't have any conflict.

File: tests/integration/security/jwt_test.go [hunk 12]
```diff
@@ -259,6 +261,75 @@ func TestRequestAuthentication(t *testing.T) {
...
+						Options: echo.CallOptions{
+							Target:   f,
+							PortName: "http",
+							Scheme:   scheme.HTTP,
+						},
+					},
+					ExpectResponseCode: response.StatusCodeOK,
+				},
+				{
+					Name: "invalid-jwks-expired-token-noauthz",
```
Comment (yangminzhu) [inline tests/integration/security/jwt_test.go:307]: this one and the following one is duplicated with aboves.

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 10 above)
Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:220]: Sure. then do I need to comment the base64 encoding here?

Comment (yangminzhu) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go:220]: No need, but you can comment inside the function about why it uses base64 instead of using jwksURI directly.

**Review by yangminzhu — APPROVED** [review]
thanks for fixing this!

File: pilot/pkg/security/authn/v1beta1/policy_applier.go (hunk 10 above)
Comment (xulingqing) [reply pilot/pkg/security/authn/v1beta1/policy_applier.go]: Fixed. Thanks a lot!
