### PR TITLE
First round or mutex fixing

### LINKED ISSUE #9043: Connection problems with large deployments (1200+ pods)
**Updated Issue (12/30/18)**
---
_(Issue has been updated to reflect the current understanding of this problem, which is much improved since it was originally opened. See 10/1/18 edit in history for original text.)_

**Describe the bug**
Deployments become unstable as they grow in size with sidecars deployed. This manifests as one of the following 3 errors:
```
Readiness probe failed: HTTP probe failed with statuscode: 503
Liveness probe failed: HTTP probe failed with statuscode: 503
Liveness probe failed: Get http://10.41.128.12:9080/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
This appears to only happen on very large `Deployment` (1200+ pods), but it is regardless of instance count or size available in the cluster. I have tried with 15x m4.large, 20x m4.xlarge, 20x r4.xlarge, etc. The threshold for failure does not change. The other key point here is that the issue does not occur if there is no k8s `Service` on the deployment.

**Expected behavior**
Large Deployments do not have problems handling requests

**Steps to reproduce the bug**
1. Have a cluster that should easily handle 1500 pods (15-20 m4.xlarge is fine)
2. Install istio with the following values.yaml:
```
global:
  proxy:
    # Disable Mixer logging every request
    accessLogFile: ""
mixer:
  replicaCount: 3
  autoscaleMin: 3
  autoscaleMax: 10
pilot:
  replicaCount: 3
  autoscaleMin: 3
  autoscaleMax: 10
```
3. Label the `default` namespace with `istio-injection=enabled`
4. Create a simple http-listener deployment/service; I'll use bookinfo to keep it simple.
a. This should have 100 replicas, liveness/readiness probes, and set the resource claims to 0 to make things simple to test
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
spec:
  replicas: 100
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.8.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0
            memory: 0
        ports:
        - containerPort: 9080
        livenessProbe: &probe
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 9080
        readinessProbe:
          <<: *probe
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-v1
  labels:
    app: productpage-v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
    version: v1
```
5. Apply the manifest to create the deployment and service
6. Wait for the pods to become `Running` and passing health checks
7. Increase the deployments by 100 and apply changes; repeat until 1200-1500 where you will see health checks start to fail on both old and new pods.

I want to go ahead and note here that separating the deployments into 100-200 pod chunks (I went to 9 deployments of 200 each for 1800 pods) seems to address the issue.

**Version**
Istio: 1.0.5
Kubernetes: 1.10.11

**Environment**
- New kops-built clusters to validate this issue on AWS (no other traffic) with Weave overlay
- Various instance sizes up to 20x r4.xlarge
- mTLS disabled
- All pods have `httpGet` liveness/readiness probes

** Other Notes**
- Liveness/Readiness probes are a way to see the problem reliably, but I imagine it would be similar for end-users hitting a service
- Removing Istio addresses stability problems
- Removing the `Service` from the deployments addresses stability problems
- Running 18 separate deployments of 100 pods each addresses stability problems (though I didn't test a shared service on all of them)
- Once a cluster gets into a busted state from a large deployment, scaling down won't fix it until I restart the masters
- Toying with the mixer HPA numbers does seem to alleviate the issue -- perhaps a larger deployment is heavier on mixer? With all the moving parts, I haven't nailed down a good test here... just speculation.

### PR DESCRIPTION
**Pull request by costinm**
Smoking gun:
```
goroutine 107 [semacquire, 182 minutes]:
sync.(*Mutex).Lock(0x2503008)
	/usr/local/go/src/sync/mutex.go:134 +0x108
istio.io/istio/pilot/pkg/proxy/envoy.(*DiscoveryService).ConfigUpdate(0xc42078c580, 0x18d4c01)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/discovery.go:480 +0x3f
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).WorkloadUpdate(0xc4200e8510, 0xc43390d2a0, 0xb, 0xc43d16dda0, 0xc43d16de00)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:491 +0x1c9
istio.io/istio/pilot/pkg/serviceregistry/kube.(*PodCache).event(0xc42078c500, 0x189b2c0, 0xc425850000, 0x1, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/cache.go:97 +0x61f
```

The root cause: we frequently use the pattern 'mutex.Lock()/defer mutex.Unlock(), and in many cases
this holds the lock longer than needed to protect the structures. 

I went over some of the other mutex uses and reduced the scope of the mutexes - there are others to review/fix, but this first PR should fix  #9043

Testing wise - we need more coverage for the 'deleted pods' cases, the stability tests are focused on stable config under load, only few pods are 'flipping' (bad health). Since this bug affects k8s registry it won't be caught by the tests using the fake registry, and we moved the local apiserver unit tests to integration/e2e where we don't have the racetest.

### CODE REVIEW

**Comment by mandarjog** [comment]
@costinm can you specify the actual deadlock ? Which resources were being held by which go routines forming a cycle.

File: pilot/pkg/proxy/envoy/v2/eds.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ var (
 // all clusters until we support on-demand cluster loading.
 type EdsCluster struct {
 	// mutex protects changes to this cluster
-	mutex sync.Mutex
+	mutex sync.RWMutex
```
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v2/eds.go]: you do realize that we literally made the same comment (use rw mutex instead of mutex) when you first wrote the incremental EDS, right?
:). Better late than never

File: pilot/pkg/serviceregistry/kube/cache.go [hunk 2]
```diff
@@ -92,14 +92,18 @@ func (pc *PodCache) event(obj interface{}, ev model.Event) error {
...
+				pc.rwMu.Lock()
 				pc.keys[ip] = key
+				pc.rwMu.Unlock()
 				if pc.c.EDSUpdater != nil {
 					pc.c.EDSUpdater.WorkloadUpdate(ip, pod.ObjectMeta.Labels, pod.ObjectMeta.Annotations)
 				}
 			default:
 				// delete if the pod switched to other states and is in the cache
-				if pc.keys[ip] == key {
+				if k, _ := pc.getPodKey(ip); k == key {
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/cache.go]: doesn't this need a lock?

File: pilot/pkg/proxy/envoy/v2/eds.go (hunk 1 above)
Comment (costinm) [reply pilot/pkg/proxy/envoy/v2/eds.go]: Yes, I remembered the comment and updated it - won't make a huge difference.

The problem is 'defer mutex.Unlock' and having method calls with a mutex held.

File: pilot/pkg/serviceregistry/kube/cache.go (hunk 2 above)
Comment (costinm) [reply pilot/pkg/serviceregistry/kube/cache.go]: getPodKey has a lock.

Comment (costinm) [reply pilot/pkg/serviceregistry/kube/cache.go]: And in general - we should move code using locks in short getter/setter methods to further reduce the risk.

**Comment by costinm** [comment]
/test istio-pilot-e2e-envoyv2-v1alpha3

Lint: failing on unmodified file

File: pilot/pkg/proxy/envoy/discovery.go [hunk 3]
```diff
@@ -454,15 +454,16 @@ func (ds *DiscoveryService) doPush() {
 	// more config update events may happen while doPush is processing.
 	// we don't want to lose updates.
 	clearCacheMutex.Lock()
-
 	clearCacheTimerSet = false
 	lastClearCache = time.Now()
 	full := ds.fullPush
+	clearCacheMutex.Unlock()
+
 	edsUpdates := BeforePush()
```
Comment (hzxuzhonghu) [inline pilot/pkg/proxy/envoy/discovery.go]: Can we put it before lock? So we no need lock twice

**Comment by hzxuzhonghu** [comment]
This pr makes critical section small, but introduces more Lock&Unlock ops, so i am not sure how much performance improved indeed.

File: pilot/pkg/proxy/envoy/discovery.go (hunk 3 above)
Comment (costinm) [reply pilot/pkg/proxy/envoy/discovery.go]: Not sure what you mean, more details please.

**Comment by costinm** [comment]
Locking is not even visible on flame graphs and very far from any performance concern. Dead-locks on the other side are a problem. Keep in mind in java it's super common to use sync methods and classes - it may be an issue on latency critical code, but Pilot is killed by memory allocations and json/protobuf conversions.

**Comment by costinm** [comment]
@mandarjog  - can you take another look and maybe merge, so it can make it in tomorrow build ?
We'll need to keep it for few days on the stress cluster - but maybe @Stono  can try the next build as well.

I can address additional locks and changes in separate PRs - I found other places where locks were held more than needed. 

(we also need to port this to 1.1)

**Comment by Stono** [comment]
If you can provide me a 1.0.5 compatible pilot I'm happy to run it on our prod like cluster for a few days

**Comment by mandarjog** [comment]
Addresses #10360

**Comment by mandarjog** [comment]
@hzxuzhonghu the core problem here was that 
cache.go#event was grabbing a long running lock on the pod cache lock and then contending on globalLock `clearCacheMutex`

discovery.go@doPush grabs a lock on clearCacheMutex  and then contends on `DiscoveryServer.mutex`  cache.go is holding onto this lock.

So removing defers makes it such that these locks are not concurrently held.

**Comment by jaygorrell** [comment]
I see this is in 1.0 but should it be in any of the 1.1 snapshots?

**Comment by jaygorrell** [comment]
Sorry, but any info here? I'd love to test this but it's unclear to me how/when things like this that get merged into 1.0 make it into a 1.1 snapshot. I don't think 1.0 is regularly ported to 1.1 is it?

**Comment by linsun** [comment]
@mandarjog @costin can you check if this is merged also in release-1.1?  (unless we don't need it in 1.1)

cc @hklai

**Comment by jaygorrell** [comment]
@linsun @mandarjog @costinm Anything on the above?
