### PR TITLE
[istioctl] add version check to tag set command

### LINKED ISSUE #30701: [istioctl] tag set command doesn't work on older Istio versions
Newer Istio versions patch all webhooks with a matching `istio.io/rev` tag (1.9+), older versions do not do this. This means we won't patch tags pointing to 1.8- revisions.

Short term, we need to add a version check making sure the specified version is new enough to handle the patching so it doesn't fail silently. 

Long term, we should try and make newer versions patch tag webhook pointing to older revisions (maybe adding `--legacy-revision` flag to `istioctl tag set` that adds a special label that newer versions can then look out for and patch).

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

### PR DESCRIPTION
**Pull request by Monkeyanator**
Fixes #30701, makes it so that users are prompted for confirmation when creating a revision tag pointed to a revision that's too old to patch it

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: istioctl/cmd/tag.go [hunk 1]
```diff
@@ -41,6 +43,7 @@ const (
 	defaultRevisionName         = "default"
 	pilotDiscoveryChart         = "istio-control/istio-discovery"
 	revisionTagTemplateName     = "revision-tags.yaml"
+	minRevisionTagIstioVersion  = "1.10"
```
Comment (shamsher31) [inline istioctl/cmd/tag.go:46]: Can you use the version number from the following? Good to avoid hardcoding versions at many places.
 
```suggestion
	minRevisionTagIstioVersion  = version.OperatorCodeBaseVersion
```

Comment (shamsher31) [reply istioctl/cmd/tag.go:46]: If not please add a comment above the `minRevisionTagIstioVersion` why it's needed.

Comment (Monkeyanator) [reply istioctl/cmd/tag.go]: Right, revision tags depend on [this commit](https://github.com/istio/istio/pull/29583) which is first in 1.10, added a comment to that effect :+1:

**Comment by Monkeyanator** [comment]
@shamsher31 addressed comments, could you take another look when you have the chance?

**Review by shamsher31 — APPROVED** [review]
Thanks. LGTM.

**Review by howardjohn — APPROVED** [review]
