### PR TITLE
fix data race in krt conformance test

### LINKED ISSUE #59884: Data race - krt conformance testing
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

```
 --- FAIL: TestConformance/files (0.97s)
=== RUN   TestIndex
==================
WARNING: DATA RACE
Read at 0x00c000c5c953 by goroutine 914:
  testing.(*common).destination()
      /usr/local/go/src/testing/testing.go:1064 +0x1cc
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:1036 +0xbe
  testing.(*common).Fatalf()
      /usr/local/go/src/testing/testing.go:1227 +0x8e
  istio.io/istio/pkg/test/util/assert.NoError()
      /home/prow/go/src/istio.io/istio/pkg/test/util/assert/assert.go:149 +0xe5
  istio.io/istio/pkg/kube/krt_test.(*fileRig).CreateObject()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:166 +0x218
  istio.io/istio/pkg/kube/krt_test.runConformance[go.shape.struct { Namespace string; Name string }].func2()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:369 +0x94

Previous write at 0x00c000c5c953 by goroutine 655:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:2023 +0x904
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:668 +0x5d
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:2101 +0x38

Goroutine 914 (running) created at:
  istio.io/istio/pkg/kube/krt_test.runConformance[go.shape.struct { Namespace string; Name string }]()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:367 +0x1055
  istio.io/istio/pkg/kube/krt_test.TestConformance.func6()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:291 +0x34
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:2036 +0x21c
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:2101 +0x38

Goroutine 655 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:2101 +0xb12
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2585 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:2036 +0x21c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2583 +0x9e9
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2443 +0xf4b
  istio.io/istio/tests/util/leak.CheckMain()
      /home/prow/go/src/istio.io/istio/tests/util/leak/check.go:198 +0x35
  istio.io/istio/pkg/kube/krt.TestMain()
      /home/prow/go/src/istio.io/istio/pkg/kube/krt/leak_test.go:25 +0x17c
  main.main()
      _testmain.go:128 +0x16d
==================
panic: Fail in goroutine after TestConformance has completed

goroutine 817 [running]:
testing.(*common).Fail(0xc000c5c908)
	/usr/local/go/src/testing/testing.go:969 +0x179
testing.(*common).Fail(0xc001644008)
	/usr/local/go/src/testing/testing.go:963 +0x79
testing.(*common).FailNow(0xc001644008)
	/usr/local/go/src/testing/testing.go:998 +0x4b
testing.(*common).Fatalf(0xc001644008, {0x5a11a05, 0x1d}, {0xc000986340, 0x1, 0x1})
	/usr/local/go/src/testing/testing.go:1228 +0x99
istio.io/istio/pkg/test/util/assert.NoError({0x5cecba8, 0xc001644008}, {0x5c5ba60, 0xc001559530})
	/home/prow/go/src/istio.io/istio/pkg/test/util/assert/assert.go:149 +0xe6
istio.io/istio/pkg/kube/krt_test.(*fileRig).CreateObject(0xc0008f3860, {0xc00094af9d, 0x3})
	/home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:166 +0x219
istio.io/istio/pkg/kube/krt_test.runConformance[...].func2()
	/home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:369 +0x95
created by istio.io/istio/pkg/kube/krt_test.runConformance[...] in goroutine 209
	/home/prow/go/src/istio.io/istio/pkg/kube/krt/conformance_test.go:367 +0x1056
FAIL	istio.io/istio/pkg/kube/krt	4.581s
```

### Version

```Text
1.30
```

### Additional Information

Looks like we are missing a WaitGroup.

### PR DESCRIPTION
**Pull request by shivansh-gohem**
**Fix data race in krt conformance test**

Fixes #59884

### Root Cause

The goroutine spawned in `runConformance` to test race conditions can outlive the parent test. For the `fileRig` implementation, `CreateObject` calls `assert.NoError(r.t, err)`, which accesses the `*testing.T` after it has been cleaned up by the test runner — causing a data race and panic: `"Fail in goroutine after TestConformance has completed"`.

`WaitUnordered` waits for the *events* to arrive, but doesn't guarantee the goroutine has *returned* — the file watcher emits events asynchronously after the file is written, so `WaitUnordered` can complete while `CreateObject` is still on the stack.

This only affects the `files` subtest because `fileRig` is the only rig whose `CreateObject` calls `assert` on the test's `*testing.T`.

### Fix

Add a `sync.WaitGroup` around the goroutine to ensure it completes before `runConformance` returns.

### CODE REVIEW

**Comment by shivansh-gohem** [comment]
@fraenkel @keithmattix ptal!

File: pkg/kube/krt/conformance_test.go [hunk 1]
```diff
@@ -364,7 +367,10 @@ func runConformance[T any](t *testing.T, factory func(t *testing.T) Rig[T]) {
 		keys = append(keys, fmt.Sprintf("a/%v", n))
 	}
 	raceHandler := assert.NewTracker[string](t)
+	var wg sync.WaitGroup
```
Comment (fraenkel) [inline pkg/kube/krt/conformance_test.go]: why all the extra spaces?
I realized the waitgroup is overkill and this could be done with a channel that we close. But either way works.

**Comment by shivansh-gohem** [comment]
@fraenkel thank you for your feedback !!! ptal

File: pkg/kube/krt/conformance_test.go [hunk 2]
```diff
@@ -280,6 +280,7 @@ func TestConformance(t *testing.T) {
 					return nil
 				}
 				return &res
+
```
Comment (fraenkel) [inline pkg/kube/krt/conformance_test.go]: why was this added?

**Comment by shivansh-gohem** [comment]
pushed the change!! @fraenkel

**Review by fraenkel — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]

**Comment by PetrMc** [comment]
is this `release-1.30` cherrypick candidate? the branch code freeze is Monday, May 4th
