### PR TITLE
Fix: Merge Extra field during VirtualService merge for multiple Infer…

### LINKED ISSUE #58392: [Bug]: Multiple InferencePools on same Gateway - ext_proc lost for all but first
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

## Summary
When deploying multiple HTTPRoutes referencing different InferencePools to the same Gateway, only the first InferencePool's ext_proc filter configuration is applied. Subsequent InferencePools' external processor configurations are lost during VirtualService merge, causing requests to bypass the endpoint picker service (EPP) and route directly to backend pods.

## Environment
- **Istio Version**: [1.28-alpha.89f30b26ba71bf5e538083a4720d0bc2d8c06401](https://github.com/llm-d/llm-d/blob/main/guides/prereq/gateway-provider/istio.helmfile.yaml#L4)
- **Kubernetes Version**: v1.33.3
- **llm-d version**: v0.3.1

## What I Tried
Deployed the following configuration:

```yaml
# Single Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infra-inference-gateway
  namespace: test
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP

---
# First InferencePool
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: gaie-1st
  namespace: test
spec:
  extensionRef:
    kind: Service
    name: gaie-1st-epp
    portNumber: 9002
    failureMode: FailClose
  selector:
    llm-d.ai/model: ms-1st-llm-d-modelservice
  targetPortNumber: 8000

---
# Second InferencePool
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: gaie-2nd
  namespace: test
spec:
  extensionRef:
    kind: Service
    name: gaie-2nd-epp
    portNumber: 9002
    failureMode: FailClose
  selector:
    llm-d.ai/model: ms-2nd-llm-d-modelservice
  targetPortNumber: 8000

---
# First HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-d-qwen-7b
  namespace: test
spec:
  parentRefs:
  - name: infra-inference-gateway
  rules:
  - matches:
    - headers:
      - name: X-Gateway-Model-Name
        type: Exact
        value: Qwen/Qwen-7B
      path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      name: gaie-1st
      port: 8000

---
# Second HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-d-llama-8b
  namespace: test
spec:
  parentRefs:
  - name: infra-inference-gateway
  rules:
  - matches:
    - headers:
      - name: X-Gateway-Model-Name
        type: Exact
        value: Llama/Llama-8B
      path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      name: gaie-2nd
      port: 8000
```

## What I Expected
Both InferencePools should have their ext_proc filter configurations applied:

**Expected Envoy Config:**
```json
{
  "name": "test.llm-d-qwen-7b.0",
  "typed_per_filter_config": {
    "envoy.filters.http.ext_proc": { /* gaie-1st-epp config */ }
  }
}
{
  "name": "test.llm-d-llama-8b.0",
  "typed_per_filter_config": {
    "envoy.filters.http.ext_proc": { /* gaie-2nd-epp config */ }
  }
}
```

**Expected Request Flow:**
```
Request with X-Gateway-Model-Name: Qwen/Qwen-7B
  → Gateway → Route Match → gaie-1st-epp (EPP) → gaie-1st-pod

Request with X-Gateway-Model-Name: Llama/Llama-8B
  → Gateway → Route Match → gaie-2nd-epp (EPP) → gaie-2nd-pod
```

## What Actually Happened
Only the first InferencePool's ext_proc configuration is applied:

**Actual Envoy Config:**
```json
{
  "name": "test.llm-d-qwen-7b.0",
  "typed_per_filter_config": {
    "envoy.filters.http.ext_proc": { /* gaie-1st-epp config */ }
  }
}
{
  "name": "test.llm-d-llama-8b.0",
  "typed_per_filter_config": null  // -> Missing!
}
```

**Actual Request Flow:**
```
Request with X-Gateway-Model-Name: Qwen/Qwen-7B
  → Gateway → Route Match → gaie-1st-epp (EPP) → gaie-1st-pod  -> Works

Request with X-Gateway-Model-Name: Llama/Llama-8B  
  → Gateway → Route Match → gaie-2nd-pod (Direct!)  -> Bypasses EPP
```

**Istiod Logs:**
```
INFO gateway InferencePool test/gaie-1st: successfully configured ext_proc, dst=gaie-1st-epp.test.svc.cluster.local, port=9002
INFO gateway InferencePool test/gaie-2nd: successfully configured ext_proc, dst=gaie-2nd-epp.test.svc.cluster.local, port=9002
INFO ads XDS: Pushing...
```

Both InferencePools show successful configuration in logs, but the second one's configuration is missing in the final Envoy config.

## Reproduction Steps

1. Deploy a Gateway with Gateway API
2. Deploy two InferencePools with different selectors
3. Deploy two HTTPRoutes referencing different InferencePools, both attached to the same Gateway
4. Check Envoy configuration:
   ```bash
   kubectl exec -n <namespace> <gateway-pod> -c istio-proxy -- \
     curl -s localhost:15000/config_dump | \
     jq '.configs[] | select(.["@type"] == "type.googleapis.com/envoy.admin.v3.RoutesConfigDump") | 
         .dynamic_route_configs[].route_config.virtual_hosts[].routes[] | 
         {name: .name, has_ext_proc: (.typed_per_filter_config["envoy.filters.http.ext_proc"] != null)}'
   ```
5. Observe that only the first route has `has_ext_proc: true`

## Root Cause Analysis

I've identified two bugs:

### Bug 1: VirtualService Merge Loses Extra Field (Primary Issue)

**Location:** `pilot/pkg/config/kube/gateway/route_collections.go`

When multiple HTTPRoutes are attached to the same Gateway, they are converted into separate VirtualService configs and then merged. The merge logic combines:
- (O) HTTP routes (`baseVS.Http`)
- (O) Annotations (`base.Annotations`)
- (X) **Extra field is NOT merged** (lost!)

The InferencePool configuration is stored in `config.Extra["perRouteRuleInferencePoolConfigs"]`, which is a map of route names to EPP configurations. During merge, only the first VirtualService's Extra field is retained.

**Existing Code:**
```go
// in route_collections.go
sortRoutesByCreationTime(configs)
base := configs[0].DeepCopy()  // First VirtualService
baseVS := base.Spec.(*istio.VirtualService)
for _, config := range configs[1:] {  // Remaining VirtualServices
    thisVS := config.Spec.(*istio.VirtualService)
    baseVS.Http = append(baseVS.Http, thisVS.Http...)  // Merge routes
    base.Annotations[constants.InternalParentNames] = fmt.Sprintf("%s,%s",
        base.Annotations[constants.InternalParentNames], 
        config.Annotations[constants.InternalParentNames])  // Merge annotations
    // config.Extra is ignored - second InferencePool config is lost!
}
```

**Result:**
```
VirtualService-1.Extra = {"test.llm-d-qwen-7b.0": {EPP config}}
VirtualService-2.Extra = {"test.llm-d-llama-8b.0": {EPP config}}
                    ↓ Merge (bug)
Merged.Extra = {"test.llm-d-qwen-7b.0": {EPP config}}  // Only first one!
```

### Bug 2: Shadow Service Lookup Timing Issue (Secondary Issue)

**Location:** `pilot/pkg/config/kube/gateway/conversion.go`

When converting an InferencePool backendRef, the code looks up the shadow service to read EPP information from labels. The existing code uses `ctx.LookupHostname()`, which queries the GatewayContext's PushContext. However, PushContext is updated asynchronously and may not contain the newly created shadow service yet.

**Existing Code:**
```go
// in conversion.go
hostname := inferencePoolServiceName + "." + namespace + ".svc." + ctx.DomainSuffix
svc := ctx.LookupHostname(hostname, namespace)  // Queries PushContext
if svc == nil {
    invalidBackendErr = &ConfigError{...}
    return &istio.Destination{}, nil, invalidBackendErr
}
```

### Version

```Text
# istio version
[1.28-alpha.89f30b26ba71bf5e538083a4720d0bc2d8c06401](https://github.com/llm-d/llm-d/blob/main/guides/prereq/gateway-provider/istio.helmfile.yaml#L4)
$ kubectl version
Client Version: v1.33.3
Kustomize Version: v5.6.0
Server Version: v1.33.3
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jazzsir**
**Please provide a description of this PR:**

**What this PR does:**
Fixes VirtualService merge to preserve InferencePool ext_proc configurations 
when multiple HTTPRoutes are attached to the same Gateway.

**Which issue(s) this PR fixes:**
Fixes #58392

**Why:**
When multiple HTTPRoutes reference different InferencePools on the same Gateway,
only the first InferencePool's external processor configuration was applied.
The mergeHTTPRoutes() function merged routes and annotations but ignored the
Extra field where InferencePool configurations are stored.

**How:**
1. Merge Extra field during VirtualService merge in route_collections.go
2. Properly merge InferencePool config maps instead of overwriting
3. Improve shadow service lookup in conversion.go with KRT collection fallback
4. Add comprehensive logging for debugging and verification

**Testing:**
- [x] Unit tests pass (existing tests)
- [x] Verified with 2 InferencePools on 1 Gateway
- [x] Both routes have ext_proc in Envoy config
- [x] Confirmed via config_dump and istiod logs

### CODE REVIEW

File: pilot/pkg/config/kube/gateway/conversion.go [hunk 1]
```diff
@@ -1092,12 +1092,31 @@ func buildDestination(ctx RouteContext, to k8s.BackendRef, ns string,
 		}
 		inferencePoolServiceName, _ := InferencePoolServiceName(string(to.Name))
 		hostname := inferencePoolServiceName + "." + namespace + ".svc." + ctx.DomainSuffix
-		svc := ctx.LookupHostname(hostname, namespace)
-		if svc == nil {
+
+		// Look up shadow service directly from ctx.Services
+		// to ensure we get the latest shadow service even if PushContext hasn't been updated yet
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/conversion.go]: Wouldn't this be eventually consistent though? I'm not sure we need the extra fetch?

File: pilot/pkg/config/kube/gateway/conversion.go [hunk 2]
```diff
@@ -1092,12 +1092,31 @@ func buildDestination(ctx RouteContext, to k8s.BackendRef, ns string,
...
+		svc := ctx.LookupHostname(hostname, namespace)
+		if svc == nil {
+			log.Infof("InferencePool %s/%s: shadow service found in K8s but not in GatewayContext yet, using K8s labels", namespace, to.Name)
+		}
+
+		// Get labels from either model.Service (if available) or K8s service
+		var labels map[string]string
+		if svc != nil && svc.Attributes.Labels != nil {
+			labels = svc.Attributes.Labels
+		} else if k8sSvc.Labels != nil {
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/conversion.go]: Why would the krt collection's reference to the shadow service have these labels but not the service registry's? The labels should always be there from creation time

File: pilot/pkg/config/kube/gateway/conversion.go [hunk 3]
```diff
@@ -1092,12 +1092,31 @@ func buildDestination(ctx RouteContext, to k8s.BackendRef, ns string,
 		}
 		inferencePoolServiceName, _ := InferencePoolServiceName(string(to.Name))
 		hostname := inferencePoolServiceName + "." + namespace + ".svc." + ctx.DomainSuffix
-		svc := ctx.LookupHostname(hostname, namespace)
-		if svc == nil {
+
+		// Look up shadow service directly from ctx.Services
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/conversion.go]: Did you come across a bug in the wild that prompted this change?

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 4]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
-		for _, config := range configs[1:] {
+		for i, config := range configs[1:] {
 			thisVS := config.Spec.(*istio.VirtualService)
 			baseVS.Http = append(baseVS.Http, thisVS.Http...)
 			// append parents
 			base.Annotations[constants.InternalParentNames] = fmt.Sprintf("%s,%s",
 				base.Annotations[constants.InternalParentNames], config.Annotations[constants.InternalParentNames])
+			// Merge Extra field (especially for InferencePool configs)
+			if config.Extra != nil {
+				if base.Extra == nil {
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Can we pull this out a level and do a check like this?
```suggestion
				if base.Extra == nil && config.Extra != nil { base.Extra = make(map[string]any) }
```

We would still need the `if config.Extra != nil` check above, but I think it would be easier to read with even one less level of nested ifs

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 5]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+					base.Extra = make(map[string]any)
+				}
+				for k, v := range config.Extra {
+					// For InferencePool configs, merge the maps
+					if k == constants.ConfigExtraPerRouteRuleInferencePoolConfigs {
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: We should exit early here with something like:
```suggestion
					if k != constants.ConfigExtraPerRouteRuleInferencePoolConfigs {
					  continue
					}
```

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 6]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+						if baseMap, ok := base.Extra[k].(map[string]kube.InferencePoolRouteRuleConfig); ok {
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Would be more readable if you saved these to two different vars and did one conditional instead of two

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 7]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+							if configMap, ok := v.(map[string]kube.InferencePoolRouteRuleConfig); ok {
+								log.Infof("Merging InferencePool configs: adding %d route configs from VirtualService %d to base (namespace=%s)",
+									len(configMap), i+1, config.Namespace)
+								for routeName, routeConfig := range configMap {
+									baseMap[routeName] = routeConfig
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Maybe add a comment for why we don't have to worry about conflicts (e.g. "route names are composed of the HTTPRoute/VirtualService namespaced name so they can't possibly conflict").

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 8]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+					} else {
+						base.Extra[k] = v
+					}
+				}
+			}
+		}
+		// Log final merged InferencePool configs
+		if base.Extra != nil {
+			if ipConfigs, ok := base.Extra[constants.ConfigExtraPerRouteRuleInferencePoolConfigs].(map[string]kube.InferencePoolRouteRuleConfig); ok {
+				log.Infof("Final merged VirtualService for key %s has %d InferencePool route configs", object.Key, len(ipConfigs))
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Should be a debug log

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 9]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+						if baseMap, ok := base.Extra[k].(map[string]kube.InferencePoolRouteRuleConfig); ok {
+							if configMap, ok := v.(map[string]kube.InferencePoolRouteRuleConfig); ok {
+								log.Infof("Merging InferencePool configs: adding %d route configs from VirtualService %d to base (namespace=%s)",
+									len(configMap), i+1, config.Namespace)
+								for routeName, routeConfig := range configMap {
+									baseMap[routeName] = routeConfig
+								}
+							}
+						} else {
+							log.Infof("Creating new InferencePool config map from VirtualService %d (namespace=%s)", i+1, config.Namespace)
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Should be a debug log

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 10]
```diff
@@ -771,12 +771,43 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+			if config.Extra != nil {
+				if base.Extra == nil {
+					base.Extra = make(map[string]any)
+				}
+				for k, v := range config.Extra {
+					// For InferencePool configs, merge the maps
+					if k == constants.ConfigExtraPerRouteRuleInferencePoolConfigs {
+						if baseMap, ok := base.Extra[k].(map[string]kube.InferencePoolRouteRuleConfig); ok {
+							if configMap, ok := v.(map[string]kube.InferencePoolRouteRuleConfig); ok {
+								log.Infof("Merging InferencePool configs: adding %d route configs from VirtualService %d to base (namespace=%s)",
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: Probably should be a debug log?

File: pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden [hunk 11]
```diff
@@ -272,6 +288,54 @@ status:
...
+status:
+  parents:
+  - conditions:
+    - lastTransitionTime: fake
+      message: Route was valid
+      reason: Accepted
+      status: "True"
+      type: Accepted
+    - lastTransitionTime: fake
+      message: backend(infpool-model1-ip-aaaaf2d6.default.svc.domain.suffix) not found
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden]: I don't think we expect this?

Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden]: You're right. I've updated the test logic

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 8 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Done! changed from Info to Debug level.

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 7 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Done! Added

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 6 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Done! much more readable

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 5 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Done! Changed to early exit pattern

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 4 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Done!, I applied the change to simplify

File: pilot/pkg/config/kube/gateway/conversion.go (hunk 1 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/conversion.go]: You're right!!, The KRT dependency tracking automatically triggers HTTPRoute recomputation when the shadow service is created. The initial failures resolve within milliseconds through automatic reconciliation.

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 12]
```diff
@@ -770,12 +770,57 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
 				base.Annotations[constants.InternalParentNames], config.Annotations[constants.InternalParentNames])
+			// Merge Extra field (especially for InferencePool configs)
+			if base.Extra == nil && config.Extra != nil {
+				base.Extra = make(map[string]any)
+			}
+			if config.Extra != nil {
+				for k, v := range config.Extra {
+					// Early return for non-InferencePool configs
+					if k != constants.ConfigExtraPerRouteRuleInferencePoolConfigs {
+						base.Extra[k] = v
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: So we constantly overwrite the extra field for non-inferencepool configs? That doesn't seem right; we probably want the oldest one for stability purposes

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 13]
```diff
@@ -770,12 +770,57 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+					if baseOk && configOk {
+						log.Debugf("Merging InferencePool configs: adding %d route configs from VirtualService %d to base (namespace=%s)",
+							len(configMap), i+1, config.Namespace)
+						// Route names are composed of the HTTPRoute/VirtualService namespaced name so they can't possibly conflict
+						for routeName, routeConfig := range configMap {
+							baseMap[routeName] = routeConfig
+						}
+					} else {
+						log.Debugf("Creating new InferencePool config map from VirtualService %d (namespace=%s)", i+1, config.Namespace)
+						base.Extra[k] = v
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/route_collections.go]: What if `config.Extra` is not the right type? I think this would replace whatever's in base regardless

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 12 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: Good catch! Changed to preserve the first value for consistency instead of overwriting on each iteration.

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 13 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go]: You're right! Added type check to only update when configOk is true

File: pilot/pkg/config/kube/gateway/route_collections.go [hunk 14]
```diff
@@ -770,12 +770,61 @@ func mergeHTTPRoutes(baseVirtualServices krt.Collection[RouteWithKey], opts ...k
...
+						// Route names are composed of the HTTPRoute/VirtualService namespaced name so they can't possibly conflict
+						for routeName, routeConfig := range configMap {
+							baseMap[routeName] = routeConfig
+						}
+					} else if configOk {
+						if _, exists := base.Extra[k]; !exists {
+							log.Debugf("Creating new InferencePool config map from VirtualService %d (namespace=%s)", i+1, config.Namespace)
+							base.Extra[k] = v
+						}
+					}
```
Comment (jaellio) [inline pilot/pkg/config/kube/gateway/route_collections.go:821]: Should we add a log here to indicate `v` is an unexpected type?

**Review by keithmattix — APPROVED** [review]
LGTM - thank you!

**Comment by keithmattix** [comment]
@jazzsir Looks like this just needs a rebase onto master and then a `make gen`

File: pilot/pkg/config/kube/gateway/route_collections.go (hunk 14 above)
Comment (jazzsir) [reply pilot/pkg/config/kube/gateway/route_collections.go:821]: Good suggestion! Added debug log to help diagnose when unexpected types are encountered.
