### PR TITLE
fix(bootstrap): add time-bounded platform detection logic with fail-fast

### LINKED ISSUE #19868: Proxy startup takes 20s due to AWS metadata lookup
Steps to reproduce:

```
kind create cluster
istioctl manifest apply
```

Then run any pod. Look at proxy logs, there is 20s between "Epoch 0 starting" and it actually starting. Additional logging will show this is from the AWS metadata

This does NOT effect GCP (because it will match the gcp one first), and I assume doesn't impact AWS since the check will be fast. However, any other provider is likely to run into this 20s delay.

This is very similar to https://github.com/istio/istio/issues/17357

I marked this as a release blocker since this is a pretty large regression for non GCP/AWS platforms

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR attempts to update the platform-detection logic in the bootstrap in a way that should avoid serialized long waits on platforms other than GCP and AWS.

The AWS platform detection logic that was added had the unintended side effect of causing a `20s` delay in sidecar start for non-AWS and non-GCP platforms (local with [kind](https://github.com/kubernetes-sigs/kind), for instance).

This PR does a number of things towards that end:
- parallelizes the platform discovery with goroutines
- allows for a hard upper-limit to be spent on platform discovery (`5s`, but configurable)
- adds some quick fail logic to AWS platform discovery, based on a rubric from AWS docs and otehr implementations.

With this PR, I observed a delay in Envoy startup of ~`5ms` (or less) in local testing and on a GKE cluster, with the correct platform behavior observed in both environments. I, unfortunately, don't have a good way to verify in AWS.

Example proxy logs:

```
2020-01-07T18:51:36.488124Z	info	Epoch 0 starting
...
2020-01-07T18:51:36.494013Z	info	Envoy command:
```

Fixes https://github.com/istio/istio/issues/19868

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pkg/bootstrap/platform/discovery.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+	go func() {
+		if IsAWS() {
+			plat <- NewAWS()
+		}
+		wg.Done()
+	}()
+
+	go func() {
+		wg.Wait()
+		done <- true
```
Comment (howardjohn) [inline pkg/bootstrap/platform/discovery.go]: Just sanity checking, is it possible for there to be a race when `done` is ahead of `plat`? Or is the write to channel+read in select synchronous so it will always be correct?

Comment (douglas-reid) [reply pkg/bootstrap/platform/discovery.go]: I was worried about this race condition as well. I ran a ton of iterations of the same logic in a throwaway test, however, and could not trigger it. 

The contract for `select` is as:

> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection. Otherwise, if there is a default case, that case is chosen. If there is no default case, the "select" statement blocks until at least one of the communications can proceed.

Looking at this again now, maybe the better thing to do is to surround the `Done()`s with `else` and then in a `defer` (or similar), just call `Done()` twice to ensure the goroutine is cleaned up.

Thoughts?

Comment (douglas-reid) [reply pkg/bootstrap/platform/discovery.go]: Instead, added a nested select in `<- done` case that should quickly check the `plat` chan again to ensure no race issues are involved.

**Review by howardjohn — APPROVED** [review]
