### PR TITLE
istioctl: Emit a warning if k8s version is not minimum

### LINKED ISSUE #26141: istioctl install should present a helpful error message when installing in an old k8s
```
ceposta@postamaclab(gke (master)) $ istioctl1.7 install
This will install the default Istio profile into the cluster. Proceed? (y/N) y
- Processing resources for Istio core.                                                                                                                         
2020-08-04T19:29:30.394282Z     error   installer       failed to verify CRD creation; the server could not find the requested resource
✘ Istio core encountered an error: failed to wait for resource: failed to verify CRD creation: the server could not find the requested resource  
```

It should present the user with a helpful message like: _You are using an old, not supported kubernetes version 1.15. Istio 1.7 requires at least 1.16_.

### PR DESCRIPTION
**Pull request by jwendell**
This is to avoid proceed with the installation and present the user
with criptograpyic messages like

`Istio core encountered an error: failed to wait for resource: failed to verify CRD creation: the server could not find the requested resource`

Closes #26141.

### CODE REVIEW

**Comment by jwendell** [comment]
I tried to keep the changes minimum possible. Had to move some functions from pre-check.go to another [new] package to avoid cyclic import error.

File: operator/cmd/mesh/manifest-apply.go [hunk 1]
```diff
@@ -139,6 +140,21 @@ func InstallManifests(setOverlay []string, inFilenames []string, force bool, dry
...
+	if err != nil {
+		return fmt.Errorf("error getting k8s version: %w", err)
+	}
+	ok, err := k8sversion.CheckKubernetesVersion(serverVersion)
+	if err != nil {
+		return fmt.Errorf("error comparing k8s version: %w", err)
+	}
+	if !ok {
+		return fmt.Errorf(
+			"the kubernetes version is not supported by this version of Istio. The minimum supported kubernetes version is %s",
```
Comment (howardjohn) [inline operator/cmd/mesh/manifest-apply.go:154]: Can we add a warning instead? I don't like to have a hard limit without a way to override.

nit: kubernetes/k8s -> Kubernetes

Comment (nschhina) [reply operator/cmd/mesh/manifest-apply.go:154]: +1 on warning instead of error. Regardless this is great, I was so confused the first time it happened to me

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go:154]: Does it make sense to have a confirm prompt as well? `Are you sure you want to proceed?(y/N)`?

Comment (shamsher31) [inline operator/cmd/mesh/manifest-apply.go:154]: I think the following message will make more sense?
```
the Kubernetes version 1.15 is not supported by Istio 1.7.  The minimum supported Kubernetes version is 1.17.
```

Comment (shamsher31) [reply operator/cmd/mesh/manifest-apply.go:154]: > Does it make sense to have a confirm prompt as well? `Are you sure you want to proceed?(y/N)`?

`istioctl install` already have confirm prompt so I think we don't need another confirm prompt.

https://github.com/istio/istio/blob/0739d2669cd613145c432809f03da5505f94a625/operator/cmd/mesh/manifest-apply.go#L114-L119

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go:154]: @shamsher31 yeah, I know that :) I was just wondering, because the user is going to proceed with an unsupported installation he should explicitly opt in for it. Perhaps a simple warning may not caught their attention. Let me change it to a warning and we can easily add a confirmation in a follow-up, if we decide it's needed later.

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go:154]: Agreed.

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go]: @howardjohn @nschhina @shamsher31 done.

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go]: @shamsher31 done.

File: operator/cmd/mesh/manifest-apply.go [hunk 2]
```diff
@@ -139,6 +141,22 @@ func InstallManifests(setOverlay []string, inFilenames []string, force bool, dry
 	if err != nil {
 		return err
 	}
+
+	serverVersion, err := clientset.Discovery().ServerVersion()
```
Comment (shamsher31) [inline operator/cmd/mesh/manifest-apply.go:145]: @jwendell  I'm thinking if this warning message can be moved as a function in `pkg/install/k8sversion/version.go`? 
That might be useful at other places where incompatible version warning is required.

Comment (jwendell) [reply operator/cmd/mesh/manifest-apply.go:145]: I think this is valid, but in a follow-up, for example, while dealing with https://github.com/istio/istio/issues/22740. I'm trying to keep this PR minimum for a backport to 1.7.

**Review by shamsher31 — APPROVED** [review]
LGTM, Thanks.

File: operator/cmd/mesh/install.go [hunk 3]
```diff
@@ -139,6 +141,22 @@ func InstallManifests(setOverlay []string, inFilenames []string, force bool, dry
...
+	if err != nil {
+		return fmt.Errorf("error getting Kubernetes version: %w", err)
+	}
+	ok, err := k8sversion.CheckKubernetesVersion(serverVersion)
+	if err != nil {
+		return fmt.Errorf("error checking if Kubernetes version is supported: %w", err)
+	}
+	if !ok {
+		l.LogAndPrintf("\nThe Kubernetes version %s is not supported by Istio %s. The minimum supported Kubernetes version is %s.\n"+
+			"Proceeding with the installation, but you might experience problems. "+
```
Comment (elfinhe) [inline operator/cmd/mesh/install.go:155]: Why proceed? In K8s <=1.15, the Istio 1.7 CRDs cannot be installed. So proceeding will cause some problem.

I'd suggest default to abort. And if users really want to proceed, use --force.

Comment (jwendell) [reply operator/cmd/mesh/install.go:155]: @howardjohn what do you think about this approach?

**Review by esnible — APPROVED** [review]

File: operator/cmd/mesh/install.go (hunk 3 above)
Comment (howardjohn) [reply operator/cmd/mesh/install.go:155]: I am fine with make it require force. I am not ok with not having a way to install on an unsupported version

File: istioctl/pkg/install/k8sversion/version.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	}
+	numbers := parts[1]
+	components := strings.Split(numbers, ".")
+	if len(components) <= 1 {
+		return "", fmt.Errorf("the version %q is invalid", versionInfo.GitVersion)
+	}
+	v := strings.Join([]string{components[0], components[1]}, ".")
+	return v, nil
+}
+func parseVersion(s string, width int) int64 {
```
Comment (howardjohn) [inline istioctl/pkg/install/k8sversion/version.go:54]: any kind of parsing type function could really use tests

File: istioctl/pkg/install/k8sversion/version.go [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+
+// CheckKubernetesVersion checks if this Istio version is supported in the k8s version
+func CheckKubernetesVersion(versionInfo *version.Info) (bool, error) {
+	v, err := extractKubernetesVersion(versionInfo)
+	if err != nil {
+		return false, err
+	}
+	return parseVersion(MinK8SVersion, 4) <= parseVersion(v, 4), nil
+}
+func extractKubernetesVersion(versionInfo *version.Info) (string, error) {
```
Comment (howardjohn) [inline istioctl/pkg/install/k8sversion/version.go:40]: Can we add tests for this? with common versions variances like `v1.16.11-gke.5`? I think we have this somewhere already, so maybe it can be reused

**Review by howardjohn — APPROVED** [review]

File: istioctl/pkg/install/k8sversion/version.go (hunk 5 above)
Comment (shamsher31) [reply istioctl/pkg/install/k8sversion/version.go:40]: I think this might be useful ?
https://github.com/istio/istio/blob/master/istioctl/pkg/install/pre-check_test.go#L41
