### PR TITLE
Refine GetProxyServiceInstances

### LINKED ISSUE #17337: Can not get the proxy locality info from node label
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

IN release1.3 and master branch, we found locality loadbalancer works unexpected. And after a diagnose , the root cause we found is that #16483 introduced a regression. It resolves the case pod comes up later than proxy connects to pilot. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

This is to fix #17337

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/pod.go [hunk 1]
```diff
@@ -82,42 +82,58 @@ func (pc *PodCache) event(obj interface{}, ev model.Event) error {
...
 		}
 	}
 	return nil
 }
 
+func (pc *PodCache) configUpdates(ip string) {
+	if pc.c != nil && pc.c.XDSUpdater != nil {
+		pc.c.XDSUpdater.ConfigUpdate(&model.PushRequest{
+			Full:          true,
+			TargetProxies: map[string]struct{}{pc.c.ClusterID + ip: {}},
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/pod.go]: why not just directly enqueue the single proxy to the push queue? I think we do that in other places

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go]: Nope, `TargetProxies` is a new field i added, the reason i add clusterID here is to distinguish multi cluster proxies.

**Comment by hzxuzhonghu** [comment]
@howardjohn For node labels, we can not use something like downward api. We must get node by the k8s api, and then get its labels.  We can do this in pilot-agent, I am sure this is also not what you want.

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 2]
```diff
@@ -555,7 +557,7 @@ func (s *DiscoveryServer) pushConnection(con *XdsConnection, pushEv *XdsEvent) e
 	// TODO: update the service deps based on NetworkScope
 
 	if pushEv.edsUpdatedServices != nil {
-		if !ProxyNeedsPush(con.modelNode, pushEv.targetNamespaces, pushEv.configTypesUpdated) {
+		if !ProxyNeedsPush(con.modelNode, pushEv.targetNamespaces, pushEv.targetProxies, pushEv.configTypesUpdated) {
```
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v2/ads.go]: why cant we pass pushEv as it is?

File: pilot/pkg/model/push_context.go [hunk 3]
```diff
@@ -152,6 +152,12 @@ type PushRequest struct {
 	// If this is present, then only proxies that import this namespace will get an update
 	TargetNamespaces map[string]struct{}
 
+	// TargetProxies contains a list of proxies that should be pushed to.
+	// The key is clusterID + proxy ip address.
+	// If this is empty, then all proxies will get an update.
+	// If this is present, then only proxies in the list will get an update.
+	TargetProxies map[string]struct{}
+
```
Comment (rshriram) [inline pilot/pkg/model/push_context.go]: do we need target namespaces and target proxies? cant we just have target proxies alone such that
 we have a map like this:

targetProxies:
` clusterID -> [namespaces -> [proxies] ]`
if map is empty, we push to all
if proxies is empty, we push to all proxies in that namespace in that cluster [if clusterId is *, then we push to all proxies in that namespace across all clusters].
if cluster Id is present, then we push only to proxies with that clusterID
and so on.

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 4]
```diff
@@ -525,35 +519,46 @@ func (c *Controller) GetProxyServiceInstances(proxy *model.Proxy) ([]*model.Serv
...
-		if ep.Namespace != proxyNamespace {
-			endpoints = &endpointsForPodInDifferentNS
+		// 2. The pod is not present when this is called
+		// due to eventual consistency issues. However, we have a lot of information about the pod from the proxy
+		// metadata already. Because of this, we can still get most of the information we need.
+		// If we cannot accurately construct ServiceInstances from just the metadata, this will return an error and we can
+		// attempt to read the real pod.
+		instances, err := c.getProxyServiceInstancesFromMetadata(proxy)
+		if err == nil {
+			return instances, nil
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/controller/controller.go]: why flip this? the idea was to look at proxy metadata first and then ask k8s as asking k8s is costly

File: pilot/pkg/serviceregistry/kube/controller/pod.go (hunk 1 above)
Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/pod.go]: is it feasible to change this? it makes it a lot more complicated to have 2 ways to trigger a push to a single proxy

File: pilot/pkg/serviceregistry/kube/controller/controller.go (hunk 4 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: We need to get locality from node labels.

It is not that costly compared to proxy meta. I looked carefully at `getProxyServiceInstancesFromMetadata`, it does also check service, which is the most costly procedure i think.

File: pilot/pkg/model/push_context.go (hunk 3 above)
Comment (hzxuzhonghu) [reply pilot/pkg/model/push_context.go]: The `TargetNamespaces` is to specify the updated services.  However, the `TargetProxies` specifies the proxies that need a push.

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/ads.go]: will do

**Comment by hzxuzhonghu** [comment]
BTW, if we want to restore the pod label support in the most direct and fast way, we can base on this.

File: pilot/pkg/model/push_context.go (hunk 3 above)
Comment (rshriram) [reply pilot/pkg/model/push_context.go]: ugh.. then can we rename the TargetNamespaces to UpdatedNamespaces ?

File: pilot/pkg/serviceregistry/kube/controller/pod.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go]: I searched and find no send to pushQueue directly now, I think removed with WorkloadUpdate.

Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/pod.go]: Hm.. can we just extend the XDSUpdater api with ProxyUpdate that does the pushQueue.Enquueue? I don't think it makes sense to add all this plumbing to push to a single proxy?

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller/pod.go]: ok, this can reduce the node labels locality latency. And i will try to think how we can get rid of direct dependency on k8s.

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 5]
```diff
@@ -643,6 +643,32 @@ func adsClientCount() int {
...
+			connection = v
+			break
+		}
+
+	}
+	adsClientsMutex.RUnlock()
+
+	currentlyPending := s.pushQueue.Pending()
+	if currentlyPending != 0 {
+		adsLog.Infof("Starting new push while %v were still pending", currentlyPending)
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads.go]: nit - I think this is misleading, this happens during the middle of pushed at any time so it's not uncommon for this to occur

File: pilot/pkg/proxy/envoy/v2/ads_common_test.go [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+package v2
+
+import (
+	"testing"
+
+	"istio.io/istio/pilot/pkg/model"
+	"istio.io/istio/pkg/config/schemas"
+)
+
+func TestProxyNeedsPush(t *testing.T) {
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads_common_test.go]: I think we already have some tests, can we extend these or do they need to be separate for some reason?

Comment (howardjohn) [reply pilot/pkg/proxy/envoy/v2/ads_common_test.go]: nevermind I see you moved it

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 5 above)
Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/ads.go]: I copied from the previous one, i will use debug here

**Comment by hzxuzhonghu** [comment]
ping @howardjohn any other comments?

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 7]
```diff
@@ -643,6 +643,38 @@ func adsClientCount() int {
 	return n
 }
 
+func (s *DiscoveryServer) ProxyUpdate(clusterID, ip string) {
+	var connection *XdsConnection
+
+	adsClientsMutex.RLock()
+	// Create a temp map to avoid locking the add/remove
+	for _, v := range adsClients {
+		if v.modelNode.ClusterID == clusterID && v.modelNode.IPAddresses[0] == ip {
```
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v2/ads.go]: nit for future: cant we have a map of ip-cluster: connection ?

Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/ads.go]: Yes, first we need the clusterID for the node.

**Comment by hzxuzhonghu** [comment]
After looking at the calling stack, if proxy.IPAddress is empty, it will crash. But as you know, basically this field can not be empty. And the `if check` is added recently. So this is just in case.

**Comment by ericvn** [comment]
Does this need to get cherry-picked back into 1.3.x as well?

**Comment by hzxuzhonghu** [comment]
Let me commit a cherry pick by hand.
