### PR TITLE
Retrigger ADS push when inbound listeners change

### LINKED ISSUE #13106: Sidecar envoys gets wrong initial config
**Describe the bug**

Sometimes it takes a long time for injected sidecar envoy proxies to be healthy, because the initial config from Pilot is not contains the necessary listeners with the pod IP

```
kind: Deployment
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      k8s-app: echo
  template:
    metadata:
      labels:
        k8s-app: echo
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: echo-service
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  ports:
  - name: http
    port: 8000
  selector:
    k8s-app: echo

NAME                   READY   STATUS    RESTARTS   AGE
echo-5d495b548f-2ws66   1/2     Running   0          1m
echo-5d495b548f-4cw8s   2/2     Running   0          1m
echo-5d495b548f-59hfg   1/2     Running   0          1m
echo-5d495b548f-5cfkt   2/2     Running   0          1m
echo-5d495b548f-6l699   1/2     Running   0          1m
echo-5d495b548f-7hfd2   1/2     Running   0          1m
echo-5d495b548f-7wkcs   2/2     Running   0          1m
echo-5d495b548f-92wlg   1/2     Running   0          1m
echo-5d495b548f-96cnj   2/2     Running   0          1m
echo-5d495b548f-hf529   2/2     Running   0          1m
echo-5d495b548f-j6qhd   1/2     Running   0          1m
echo-5d495b548f-kx59c   2/2     Running   0          1m
echo-5d495b548f-l7n8f   1/2     Running   0          1m
echo-5d495b548f-lkkq6   1/2     Running   0          1m
echo-5d495b548f-qhv9b   2/2     Running   0          1m
echo-5d495b548f-rjvgz   1/2     Running   0          1m
echo-5d495b548f-rkmqm   1/2     Running   0          1m
echo-5d495b548f-scsqg   1/2     Running   0          1m
echo-5d495b548f-vmpwc   1/2     Running   0          1m
echo-5d495b548f-x2qjr   1/2     Running   0          1m

$ k logs -f echo-5d495b548f-j6qhd -c istio-proxy

* failed checking application ports. listeners="0.0.0.0:15090","10.0.9.253:443","10.0.14.181:443","10.0.14.62:14268","10.0.13.140:443","10.0.0.10:53","10.0.14.181:15443","10.0.15.199:16686","10.0.11.84:8443","10.0.15.190:15030","10.0.15.190:15443","10.0.7.215:42422","10.0.15.190:443","10.0.5.139:15011","10.0.3.222:80","10.0.15.190:31400","10.0.15.190:15020","10.0.0.1:443","10.0.15.190:15029","10.0.4.88:443","10.0.5.201:443","10.0.8.138:443","10.0.15.190:15031","10.0.15.190:15032","10.0.14.62:14267","0.0.0.0:15014","0.0.0.0:15010","0.0.0.0:80","0.0.0.0:8060","0.0.0.0:8000","0.0.0.0:3000","0.0.0.0:9901","0.0.0.0:9090","0.0.0.0:8080","0.0.0.0:9411","0.0.0.0:9091","0.0.0.0:20001","0.0.0.0:15004","0.0.0.0:15001"
* envoy missing listener for inbound application port: 8000
```

**Expected behavior**

The initial envoy config should contain `podIP:8000` and goes healthy right after it gets the inital config from Pilot

**Steps to reproduce the bug**

Fresh GKE cluster with upstream Istio 1.1.x

**Version**

```
Istio version

client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
egressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```

```
K8s version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.5", GitCommit:"a9aff9e146595b2843839905a8fb6d1cf206f97b", GitTreeState:"clean", BuildDate:"2019-03-13T11:18:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**

`kubectl apply -f install/kubernetes/istio-demo.yaml`

**Environment**

GKE, upstream Istio 1.1.1

### PR DESCRIPTION
**Pull request by zcahana**
**Please provide a description for what this PR is for.**

This PR addresses a situation in which the proxy connects to the Pilot and receives an initial LDS configuration, before the Pilot managed to learn (e.g., via a kube API event) about the pod/service endpoint. This results with the proxy container (and hence, its pod) being stuck in an unready state, until an updated LDS configuration arrives (which seems to be taking a long and even unbounded amount of time).

This PR adds an event handler that subscribes to `model.ServiceInstance` changes, and detects whenever an LDS update is needed for the proxy associated with the `ServiceInstance`. When such update is detected, the handler triggers a full ADS push, to that particular proxy.

Fixes #13106.

P.S. - I've marked _Performance and Scalability_ below because this change may have performance impact and should probably be more carefully examined.

**And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/proxy/envoy/v2/discovery.go [hunk 1]
```diff
@@ -194,6 +199,13 @@ func NewDiscoveryServer(
 		return nil
 	}
 
+	instanceUpdateHandler := func(instance *model.ServiceInstance, event model.Event) {
+		out.updateProxyServiceInstances(instance)
```
Comment (golangcibot) [inline pilot/pkg/proxy/envoy/v2/discovery.go]: Error return value of `out.updateProxyServiceInstances` is not checked (from `errcheck`)

**Comment by rshriram** [comment]
welcome back @zcahana .. long time :)

**Comment by zcahana** [comment]
> welcome back @zcahana .. long time :)

thanks @rshriram :-) indeed a long time!

**Comment by hzxuzhonghu** [comment]
It's too late here, I will have a look tomorrow morning.

File: pilot/pkg/proxy/envoy/v2/discovery.go [hunk 2]
```diff
@@ -194,6 +199,13 @@ func NewDiscoveryServer(
...
+	}
+	if err := ctl.AppendInstanceHandler(instanceUpdateHandler); err != nil {
```
Comment (hzxuzhonghu) [inline pilot/pkg/proxy/envoy/v2/discovery.go]: Why do we need another Instance handler  to trigger push as we already have one in line 197, which will trigger a full push.

**Comment by hzxuzhonghu** [comment]
SO i donot think this can really resolve your issue @zcahana

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 3]
```diff
@@ -670,17 +670,59 @@ func (s *DiscoveryServer) startPush(push *model.PushContext, full bool, edsUpdat
...
+	if reflect.DeepEqual(instances, proxy.ServiceInstances) {
+		// no changes detected - nothing to update
+		return nil
+	}
+
+	// Update proxy node's service instances
+	err = proxy.SetServiceInstances(s.Env)
+	if err != nil {
+		adsLog.Errorf("Error setting proxy %s service instances: %v", proxy.ID, err)
+		return err
```
[the remark this answers is not in the document]
Comment (zcahana) [reply pilot/pkg/proxy/envoy/v2/ads.go]: Right. I'll add an error check with an appropriate log message.

File: pilot/pkg/proxy/envoy/v2/discovery.go (hunk 2 above)
Comment (zcahana) [reply pilot/pkg/proxy/envoy/v2/discovery.go]: Well, up until now the instance handler wasn't even invoked (see 3fdd00e). It's possible that the fix in 3fdd00e is sufficient to resolve the issue (I'm not sure what's the outcome of `DiscoveryServer.clearCache()`), and the additional instance handler added in 4da238e is redundant. I'll test and report back.

**Comment by zcahana** [comment]
> SO i donot think this can really resolve your issue @zcahana

Manual testing suggests that it does resolve the issue. Will try to come up with some automated test to recreate the issue and demonstrate resolution.

P.S. sorry for the long time to respond, had to attend some personal matters in the past week.

**Comment by zcahana** [comment]
Rebased and fixed compiled error.

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 4]
```diff
@@ -771,6 +804,11 @@ func (c *Controller) AppendInstanceHandler(f func(*model.ServiceInstance, model.
 
 		c.updateEDS(ep, event)
 
+		instances := c.getServiceInstanceByEndpoint(*ep)
+		for _, instance := range instances {
+			f(instance, event)
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/controller.go]: I realize the code is horrible, but I think this is going to trigger full pushes on endpoint changes now

@rshriram

Comment (rshriram) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: Oh yeah.. if you call the appendInstanceHandlers, it will trigger full push. Costin removed it but did not put in an alternative :(. Are you looking to handle the case where a new inbound listener appears? or the case where the inbound listener changes?

Comment (zcahana) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: I'm looking to handle the case of a new inbound listener. The instance handler I've added tries to trigger a push only for the proxy instance co-located with the new endpoint. Are you saying that the other instance handler, the one that simply calls `DiscoveryServer.clearCache()`, will trigger a full push to all proxies? If so, should it just be removed?

File: pilot/pkg/proxy/envoy/v2/discovery.go [hunk 5]
```diff
@@ -183,6 +187,16 @@ func NewDiscoveryServer(
 		return nil
 	}
 
+	instanceUpdateHandler := func(instance *model.ServiceInstance, event model.Event) {
+		err := out.updateProxyServiceInstances(instance)
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/discovery.go]: seems this will be called for every ip:port even though we only really care about IPs (I assume kubernetes will always created all ports at the same time as IPs but maybe not?). Shouldn't be a big issue though

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 6]
```diff
@@ -705,17 +705,59 @@ func proxyNeedsPush(con *XdsConnection, targetNamespaces map[string]struct{}) bo
...
+	}
+
+	// Trigger an update to that particular proxy
+	s.pushQueue.Enqueue(con, &model.PushRequest{Full: true, Push: s.globalPushContext()})
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads.go]: Can you add `Start: time.Now()`

File: pilot/pkg/proxy/envoy/v2/discovery.go (hunk 2 above)
Comment (howardjohn) [reply pilot/pkg/proxy/envoy/v2/discovery.go]: We cannot call clearCache if it wasn't already being called. clearCache triggers a full push to the entire cluster. That means any time a new instances comes up a full push goes to every proxy

File: pilot/pkg/serviceregistry/kube/controller/controller.go (hunk 4 above)
Comment (howardjohn) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: I think we could just remove it. That is the only usage right?

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 7]
```diff
@@ -705,17 +705,59 @@ func proxyNeedsPush(con *XdsConnection, targetNamespaces map[string]struct{}) bo
...
+		return err
+	}
+
+	if reflect.DeepEqual(instances, proxy.ServiceInstances) {
+		// no changes detected - nothing to update
+		return nil
+	}
+
+	// Update proxy node's service instances
+	err = proxy.SetServiceInstances(s.Env)
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads.go]: in SetServiceInstances we call GetProxyServiceInstances, but we just called this before (as `instances`). Should we just do `proxy.ServiceInstances = instances`?

Comment (howardjohn) [reply pilot/pkg/proxy/envoy/v2/ads.go]: Also, I suspect this will cause a race condition, because ServiceInstances is not protected by a mutex -- none of the fields in model.Proxy are because we always call them from a single goroutine, but this would break that

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 8]
```diff
@@ -655,6 +655,39 @@ func (c *Controller) getEndpoints(ip string, endpointPort int32, svcPort *model.
...
+	out := make([]*model.ServiceInstance, 0)
+
+	hostname := kube.ServiceHostname(endpoints.Name, endpoints.Namespace, c.domainSuffix)
+	c.RLock()
+	svc := c.servicesMap[hostname]
+	c.RUnlock()
+
+	if svc != nil {
+		for _, ss := range endpoints.Subsets {
+			for _, port := range ss.Ports {
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/controller/controller.go]: do we need all ip:port or just a all unique IPs? I don't know if there are cases where the distinction matters. Maybe we keep it like this to be safe, as I doubt it has tangible performance impacts

**Comment by hzxuzhonghu** [comment]
Rethink about the issue, maybe the root cause is: the pod occurs later than endpoint.

So even though we record the proxies that need full push in the next push epoch, but no endpoint update event occurs.

**Comment by howardjohn** [comment]
One interesting thing is this problem is that it is very consistent in our lb integration test (maybe because it created about 12 pods all at once), but only on kubernetes 1.12 and 1.13, on 14 and 15 it's fixed.

See https://testgrid.k8s.io/istio-postsubmits-master#integ-k8s-113-postsubmit-master&exclude-non-failed-tests=

File: pilot/pkg/serviceregistry/kube/controller/controller.go (hunk 4 above)
Comment (zcahana) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: Yap, that's the only usage. Will remove.

File: pilot/pkg/proxy/envoy/v2/discovery.go (hunk 5 above)
Comment (zcahana) [reply pilot/pkg/proxy/envoy/v2/discovery.go]: Right, will be called for every ip:port resolved by the endpoint's subsets. However, it'll quickly realize there's no change in the proxy's service instances, and will therefore avoid a redundant push.

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 6 above)
Comment (zcahana) [reply pilot/pkg/proxy/envoy/v2/ads.go]: Done.

File: pilot/pkg/serviceregistry/kube/controller/controller.go (hunk 8 above)
Comment (zcahana) [reply pilot/pkg/serviceregistry/kube/controller/controller.go]: For our specific case, we only need the IPs, but it seems correct for `Controller.AppendInstanceHandler()` to invoke the callback for every ServiceInstance (==> ip:port). Given that the penalty is (supposedly) low (see [comment](https://github.com/istio/istio/pull/15950#discussion_r314970646)), I think we can just leave it like that.

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 7 above)
Comment (zcahana) [reply pilot/pkg/proxy/envoy/v2/ads.go]: Done regarding `proxy.ServiceInstances = instances`.
And yes, good observation about the race condition. That single goroutine you mentioned is the one that runs `StreamAggregatedResources()`, right? If so, I'll work on adding it another input channel that will be populated by the above handler func.

**Comment by zcahana** [comment]
> Rethink about the issue, maybe the root cause is: the pod occurs later than endpoint.

@hzxuzhonghu 
This seems like another potential issue to be addressed, but probably a separate one?

> One interesting thing is this problem is that it is very consistent in our lb integration test (maybe because it created about 12 pods all at once), but only on kubernetes 1.12 and 1.13, on 14 and 15 it's fixed.

@howardjohn 
Could be due to a timing difference between 1.13 and 1.14 in how API updates are delivered?

**Comment by howardjohn** [comment]
this broke race tests https://prow.istio.io/view/gcs/istio-prow/logs/istio-integ-race-native-tests-master/759

We should make that a presubmit test instead of postsubmit

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 9]
```diff
@@ -705,17 +705,55 @@ func proxyNeedsPush(con *XdsConnection, targetNamespaces map[string]struct{}) bo
...
+		return err
+	}
+
+	if reflect.DeepEqual(instances, proxy.ServiceInstances) {
+		// no changes detected - nothing to update
+		return nil
+	}
+
+	// Update proxy node's service instances
+	proxy.ServiceInstances = instances
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads.go]: (on my phone so based on memory) in pushConnection do we already do SetServiceInstances? if so we can remove this and get around the race issue?

Ideally all proxy modifications are done in pushConnection do we only have one thread modifying it and avoid races

**Comment by howardjohn** [comment]
Opened https://github.com/istio/istio/pull/16367 to hopefully fix the race

File: pilot/pkg/serviceregistry/kube/controller/controller.go (hunk 4 above)
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller/controller.go]: @zcahana @howardjohn @rshriram This may duplicate with L809 and also not that efficient, would rather suggest having a careful look at #16338.
