### PR TITLE
endpoints: use gateway for network-specific endpoints when local proxy network is unset

### LINKED ISSUE #58612: Gateway address for `istio-remote` not applied when local network is undefined
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

**Use case:**

I have 2 clusters working in single network mode, and I want to enable manual service discovery in cluster 1 to connect to services from cluster 2. So I create `istio-remote` gateway to define address of remote ingress gateway, then I apply ServiceEntries and WorkloadEntries, which define only network name pointing to the istio-remote gateway, e.g.
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: remote-gateway-network-us-east-1
  namespace: istio-system
  labels:
    topology.istio.io/network: network-us-east-1
spec:
  gatewayClassName: istio-remote
  addresses:
  - value: 1.1.1.1
  listeners:
  - name: cross-network
    port: 15443
    protocol: TLS
    tls:
      mode: Passthrough
      options:
        gateway.istio.io/listener-protocol: auto-passthrough
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-mesh-global
spec:
  hosts:
  - httpbin.mesh.global
  location: MESH_INTERNAL
  ports:
  - number: 8000
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: httpbin-mesh-global
---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: httpbin-mesh-global-us-east-1
  labels:
    app: httpbin-mesh-global
    security.istio.io/tlsMode: istio
spec:
  network: network-us-east-1
```

**What happens:**

Sidecars do not receive endpoints for `httpbin.mesh.global`.

**Root cause:**

The local network was not specified in `values.global.network`.

**Solution:**

Set `values.global.network` and restart all pods, which need the missing endpoint.

**Desired behavior:**

Users should not be required to restart workloads when they want to connect to services from other networks.

### Version

```Text
1.28.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

Fixes #58612

### CODE REVIEW

File: pilot/pkg/xds/endpoints/ep_filters_test.go [hunk 1]
```diff
@@ -677,6 +677,108 @@ func TestEndpointsByNetworkFilter_SkipLBWithHostname(t *testing.T) {
...
+	b := endpoints.NewEndpointBuilder(cn, proxy, ds.PushContext())
+	filtered := b.BuildClusterLoadAssignment(shards).Endpoints
+
+	want := []xdstest.LocLbEpInfo{
+		{
+			LbEps: []xdstest.LbEpInfo{
+				{Address: workloadIP, Weight: 1}, // Case 1
+				{Address: network1IP, Weight: 1}, // Case 2
+				{Address: network2IP, Weight: 1}, // Case 3
+				// Case 4 not included
```
Comment (jewertow) [inline pilot/pkg/xds/endpoints/ep_filters_test.go:774]: Without the new condition in `EndpointsByNetworkFilter` the result would be:
```
				{Address: workloadIP, Weight: 1}, // Case 1
				{Address: 10.10.10.10, Weight: 1}, // Case 2
				// Case 3 not included
				// Case 4 not included
```

**Comment by jewertow** [comment]
Hey @keithmattix @Stevenjin8, could you take a look at this PR and the related issue?

**Review by keithmattix — COMMENTED** [review]
Is it too much to change InNetwork to have this logic?

**Comment by jewertow** [comment]
That was my first thought, but when I've read other functions, which rely on `IsNetwork` I've realized that I can't do that, because that would break those functions.

**Comment by Stevenjin8** [comment]
@jewertow At a high level I'm pretty pro this change, but I know there are a nonzero number of users relying on this bug/feature, so I would ask for a feature flag, even if it defaults to true.

**Comment by Stevenjin8** [comment]
@jewertow

Thanks for the ping. I have some questions

I'm not convinced that this solves

> Users should not be required to restart workloads when they want to connect to services from other networks.

My understanding is that networks configured on proxies via environment variables. Proxies then use that environment variable to report their network to istiod, which uses it in it for endpoint discovery.

https://github.com/istio/istio/blob/ec64c6713f2147b3530261d4bb5a57278bfe3c40/pkg/kube/inject/inject.go#L438-L448

So it feels like its inherently necessary to restart workloads to update network information. This just solves the specific case where the network is `""`. Even then, you could run into cases where you restart/add some workload, but not others, and you end up using an E/W gateway for communication within the cluster.

I'm think the change in itself is fine, but maybe we put it behind a feature flag? I could be convinced otherwise, but this could chance the source IP when connecting across networks, which might trigger some RBAC/Auth rule.

**Comment by jewertow** [comment]
> and you end up using an E/W gateway for communication within the cluster.

That would be true if istiod didn't know endpoint addresses of a workload from the local cluster.

I can only imagine this issue when a user creates a WorkloadEntry with empty addresses and the local network, which makes no sense at all and wouldn't work anyway.

> I'm think the change in itself is fine, but maybe we put it behind a feature flag?

Instead of adding a feature flag I would prefer to identify the actual problems and fix them. Having a feature flag requires users to be aware of the issue in the first place, so it does not improve the overall experience.

**Comment by Stevenjin8** [comment]
Oh I see what you mean. Users shouldn't have to change the network at all because for that change to propagate, you need to restart workloads. that's fair.
