### PR TITLE
Fix for flakes in TestSource_MangledNames

### LINKED ISSUE #11532: Flaky Test: istio.io/istio/galley/pkg/source/kube/dynamic TestSource_MangledNames
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/11528/istio-unit-tests/20534

### PR DESCRIPTION
**Pull request by nmittler**
The source of the panic appeared to be access to the labels, which were not being explicitly set on the Unstructured object. This PR sets them directly, so that should no longer be an issue.

Fixes #11532

### CODE REVIEW

File: galley/pkg/source/kube/dynamic/source_test.go [hunk 1]
```diff
@@ -152,6 +152,8 @@ func TestEvents(t *testing.T) {
 				"name":            "f1",
 				"namespace":       "ns",
 				"resourceVersion": "rv1",
+				"labels": map[string]interface{} {},
```
Comment (golangcibot) [inline galley/pkg/source/kube/dynamic/source_test.go]: File is not `goimports`-ed (from `goimports`)

**Comment by ozevren** [comment]
It doesn't look like a test problem then? I believe the unstructured objects will have annotations/labels as nil if not set.

**Comment by nmittler** [comment]
@ozevren I'm actually guessing as to what the issue is ... I can't reproduce it.

**Comment by nmittler** [comment]
@ozevren PTAL ... I think the issue is multithreaded access to the unstructured object.  I've re-arranged things so that it shouldn't be an issue.

**Comment by nmittler** [comment]
@wenchenglu mind merging?

**Comment by nmittler** [comment]
@wenchenglu the test passed .... merge at your leisure :)

**Comment by wenchenglu** [comment]
@nmittler thanks for pinging me 👍
