### PR TITLE
istioctl/dashboard: add option to support skip browser open

### LINKED ISSUE #29022: istioctl unit tests open up http://localhost:3456/ in browser
**Bug description**
Running istioctl unit tests opens http://localhost:3456/ in my browser

**Expected behavior**

Do not open my brwosers

**Steps to reproduce the bug**

`go test ./istioctl/...`

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

Fix #29022

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: istioctl/cmd/dashboard.go [hunk 1]
```diff
@@ -409,11 +412,16 @@ func closePortForwarderOnInterrupt(fw kube.PortForwarder) {
...
 	}()
 }
-func openBrowser(url string, writer io.Writer) {
+func openBrowser(url string, writer io.Writer, skipOpen bool) {
 	var err error
 
 	fmt.Fprintf(writer, "%s\n", url)
 
+	if skipOpen {
+		fmt.Println("skip open browser due to disable by skipOpen option")
```
Comment (carolynhu) [inline istioctl/cmd/dashboard.go:421]: nit: "skip opening browser due to it is disabled by the --skipOpen option"

File: istioctl/cmd/dashboard.go [hunk 2]
```diff
@@ -451,6 +458,7 @@ func dashboard() *cobra.Command {
 		"Address to listen on. Only accepts IP address or localhost as a value. "+
 			"When localhost is supplied, istioctl will try to bind on both 127.0.0.1 and ::1 "+
 			"and will fail if neither of these address are available to bind.")
+	dashboardCmd.PersistentFlags().BoolVar(&skipOpen, "skipOpen", false, "skip open browser or not")
```
Comment (carolynhu) [inline istioctl/cmd/dashboard.go:461]: if your default value is false, how could your dashboard_test.go work?

Comment (daixiang0) [reply istioctl/cmd/dashboard.go:461]: Since it is a bool flag, if you set it, it pass value as `true`:
```
root:[istio]$ go run a.go
Bool Arg: false
root:[istio]$ go run a.go -arg1
Bool Arg: true
root:[istio]$ cat a.go
package main

import (
    "flag"
    "fmt"
)

func main() {
    // Define a bool flag
    boolArgPtr := flag.Bool("arg1", false, "This is a bool argument")

    // Parse command line
    // into the defined flags
    flag.Parse()

    fmt.Println("Bool Arg:", *boolArgPtr)
}
```

Comment (carolynhu) [reply istioctl/cmd/dashboard.go:461]: ok, i'm not familiar with the, but if you tested, it's pass

Comment (shamsher31) [inline istioctl/cmd/dashboard.go:461]:
```suggestion
	dashboardCmd.PersistentFlags().BoolVar(&skipOpen, "skipOpen", false, "When --skipOpen is supplied, istioctl dashboard will not open the browser. Default is false which means istioctl dashboard will always open a browser to view the dashboard.")
```

File: releasenotes/notes/29032.yaml [hunk 3]
```diff
@@ -0,0 +1,9 @@
+apiVersion: release-notes/v2
+kind: feature
+area: istioctl
+issue:
+  - 29022
+
+releaseNotes:
+- |
+  **Added** `istioctl dashboard` add a new option, `--skipOpen`, support skip browser open.
```
Comment (shamsher31) [inline releasenotes/notes/29032.yaml:9]:
```suggestion
  **Added** `--skipOpen` flag to `istioctl dashboard`, which controls whether you want to open a browser to view the dashboard.
```

File: istioctl/cmd/dashboard.go [hunk 4]
```diff
@@ -409,11 +412,16 @@ func closePortForwarderOnInterrupt(fw kube.PortForwarder) {
...
 	}()
 }
-func openBrowser(url string, writer io.Writer) {
+func openBrowser(url string, writer io.Writer, skipOpen bool) {
 	var err error
 
 	fmt.Fprintf(writer, "%s\n", url)
 
+	if skipOpen {
+		fmt.Println("skip opening browser due to it is disabled by the --skipOpen option")
```
Comment (shamsher31) [inline istioctl/cmd/dashboard.go:421]: Prefer to write to standard `io.Writer`.

```suggestion
		fmt.Fprint(writer, "skipping opening a browser")
```

File: istioctl/cmd/dashboard.go [hunk 5]
```diff
@@ -409,11 +412,16 @@ func closePortForwarderOnInterrupt(fw kube.PortForwarder) {
 		fw.Close()
 	}()
 }
-func openBrowser(url string, writer io.Writer) {
+func openBrowser(url string, writer io.Writer, skipOpen bool) {
```
Comment (esnible) [inline istioctl/cmd/dashboard.go:415]: Rename this function.  It now does two things, either printing the URL or print+open.

File: istioctl/cmd/dashboard.go [hunk 6]
```diff
@@ -451,6 +458,9 @@ func dashboard() *cobra.Command {
 		"Address to listen on. Only accepts IP address or localhost as a value. "+
 			"When localhost is supplied, istioctl will try to bind on both 127.0.0.1 and ::1 "+
 			"and will fail if neither of these address are available to bind.")
+	dashboardCmd.PersistentFlags().BoolVar(&skipOpen, "skipOpen", false,
+		"When --skipOpen is supplied, istioctl dashboard will not open the browser. "+
+			"Default is false which means istioctl dashboard will always open a browser to view the dashboard.")
```
Comment (esnible) [inline istioctl/cmd/dashboard.go:463]: It might make more sense to call the new CLI argument `--browser` and have the default `true`.  Thus, users who don't want one could say `--browser=false`.  "skipOpen" is awkward to document.

**Review by esnible — CHANGES_REQUESTED** [review]
Please always open an Issue when opening a PR that requires a release note.  The discussion of the new flag should take place in an issue, rather than a PR.

**Comment by daixiang0** [comment]
@esnible I see, at the very beginning, i just consider it as an option for test.

File: istioctl/cmd/dashboard.go (hunk 5 above)
Comment (daixiang0) [reply istioctl/cmd/dashboard.go:415]: I think they are parts of one thing.

**Comment by daixiang0** [comment]
@howardjohn WDYT?

**Comment by howardjohn** [comment]
@daixiang0 I am not a UX owner so I cannot approve this

**Comment by esnible** [comment]
> @howardjohn WDYT?

I will approve if you change `--skipOpen` to `--browser=false` or something similar.

**Comment by daixiang0** [comment]
@esnible done.

**Review by carolynhu — COMMENTED** [review]
Also, once this is approved, we need to make it reflect here: https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-dashboard

**Comment by daixiang0** [comment]
@carolynhu thanks for the quick response, where can i update it?

**Review by howardjohn — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]

**Review by carolynhu — APPROVED** [review]

**Review by esnible — APPROVED** [review]

**Comment by esnible** [comment]
@carolynhu : @daixiang0 does not need to update the documentation.  It will be done automatically, first to https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-dashboard and when 1.9 is released to the main site.
