### PR TITLE
Fix Service and WorkloadEntry updates

### LINKED ISSUE #27151: bug: workloadentry + service stay on incorrect port
The following config does not appear to work:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    asm_resource_type: VM
  name: kuat-xxx-vm
  namespace: xxx-bugbash-vm-3
spec:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: kuat-xxx-vm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: kuat-xxx-vm
  namespace: xxx-bugbash-vm-3
spec:
  address: xxxxxxx
  labels:
    app: kuat-xxx-vm
  serviceAccount: xxxxx
```

istioctl pc endpoint shows:
```
SERVICE_VIP:80                    HEALTHY     OK                outbound|8090||kuat-asm-vm.asm-bugbash-vm-3.svc.cluster.local
```

Note that port 80 is used instead of the desired 8090.

cc @howardjohn

### LINKED ISSUE #27183: Update workload entry causes duplicate address
```
$ ik pc ep `kp shell` | rg echo
1.1.1.1:8080                     HEALTHY     OK                outbound|8080||echo.default.svc.cluster.local
$ kaf /tmp/wle.yml
service/echo unchanged
workloadentry.networking.istio.io/vm-0 configured
$ ik pc ep `kp shell` | rg echo
1.1.1.1:8080                     HEALTHY     OK                outbound|8080||echo.default.svc.cluster.local
1.1.1.2:8080                     HEALTHY     OK                outbound|8080||echo.default.svc.cluster.local
```

### PR DESCRIPTION
**Pull request by howardjohn**
PR is split into many commits
1. does some testing refactoring to support this, and adds 2 failing tests
2. Fixes #27151, enables the test
3. Fixes #27183, enables the test
4. Fixes pod updates for SE selects pod
5. Fixes SE updates for SE selects pod
6. Fixes https://github.com/istio/istio/issues/27185

Somehow we managed to have 4 different bugs covering all 4 update scenarios. They should be all fixed and tested now.

cc @kyessenov @JimmyCYJ

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 1]
```diff
@@ -206,10 +206,12 @@ type Controller struct {
 	// we run through the label selectors here to pick only ones that we need.
 	// Only nodes with ExternalIP addresses are included in this map !
 	nodeInfoMap map[string]kubernetesNode
-	// externalNameSvcInstanceMap stores hostname ==> instance, is used to store instances for ExternalName k8s services
+	// externalNameSvcInstanceMap stores hostname ==2> instance, is used to store instances for ExternalName k8s services
```
Comment (kyessenov) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:209]: typo?

File: pilot/pkg/xds/fake.go [hunk 2]
```diff
@@ -140,6 +139,27 @@ func NewFakeDiscoveryServer(t test.Failer, opts FakeOptions) *FakeDiscoveryServe
...
+		}
+		s.ConfigUpdate(pushReq)
+	}
+	if err := cg.Registry.AppendServiceHandler(serviceHandler); err != nil {
+		t.Fatalf("append service handler failed: %v", err)
+	}
+	if err := cg.ServiceEntryRegistry.AppendWorkloadHandler(k8s.WorkloadInstanceHandler); err != nil {
+		t.Fatal(err)
+	}
+	if err := k8s.AppendWorkloadHandler(cg.ServiceEntryRegistry.WorkloadInstanceHandler); err != nil {
```
Comment (stevenctl) [inline pilot/pkg/xds/fake.go:160]: You will may need to call `SyncAll` again after this. We call `k8s.Run()` inside of its constructor, so the WorkloadHandler could miss the initial `SyncAll` from inside the k8s controller.

Comment (howardjohn) [reply pilot/pkg/xds/fake.go:160]: This ended up causing a race so I think Ill pass it the handler in the constructor

Comment (stevenctl) [reply pilot/pkg/xds/fake.go:160]: Either that, or fake kube controller should have `Run` called and share the same stop chan as the other controllers.

**Comment by iandyh** [comment]
https://github.com/istio/istio/issues/25110

**Comment by howardjohn** [comment]
/retest

too see if its a flake

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 3]
```diff
@@ -708,8 +712,9 @@ func (c *Controller) serviceInstancesFromWorkloadInstances(svc *model.Service, r
 	workloadInstancesExist = len(c.workloadInstancesByIP) > 0
 	c.RUnlock()
 
+	// Only select internal Kubernetes services with selectors
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:715]: nit: This comment and code below is little confusing. It took a while for me to understand we are doing an exclusion here rather than selecting

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 4]
```diff
@@ -904,7 +909,14 @@ func (c *Controller) WorkloadInstanceHandler(si *model.WorkloadInstance, event m
 	case model.EventDelete:
 		delete(c.workloadInstancesByIP, si.Endpoint.Address)
 	default: // add or update
+		// Check to see if the workload entry changed. If it did, clear the old entry
+		k := si.Name + "~" + si.Namespace
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:913]: Not related to this but - We are using "~" separator at multiple places in the code, May be we should move that to some constant like `ISTIO_SEPARATOR`  :-) or some thing and use it every where so that in future for some odd reason if we have to change, we can change easilt

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 5]
```diff
@@ -210,6 +210,8 @@ type Controller struct {
 	externalNameSvcInstanceMap map[host.Name][]*model.ServiceInstance
 	// workload instances from workload entries  - map of ip -> workload instance
 	workloadInstancesByIP map[string]*model.WorkloadInstance
+	// Stores a map of workload instance name/namespace to address
+	workloadInstancesIPsByName map[string]string
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:214]: nit: workloadInstancesIPsByName-> workloadInstanceIPByName /workloadInstanceAddressByName?

File: pilot/pkg/serviceregistry/kube/controller/controller.go [hunk 6]
```diff
@@ -904,7 +909,14 @@ func (c *Controller) WorkloadInstanceHandler(si *model.WorkloadInstance, event m
 	case model.EventDelete:
 		delete(c.workloadInstancesByIP, si.Endpoint.Address)
 	default: // add or update
+		// Check to see if the workload entry changed. If it did, clear the old entry
+		k := si.Name + "~" + si.Namespace
+		existing := c.workloadInstancesIPsByName[k]
+		if existing != si.Endpoint.Address {
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/kube/controller/controller.go:915]: nit: I think in add case, delete will always be executed which is redundant may be only do this for update case?.

File: pilot/pkg/serviceregistry/serviceentry/servicediscovery.go [hunk 7]
```diff
@@ -506,7 +531,13 @@ func (s *ServiceEntryStore) edsUpdate(instances []*model.ServiceInstance, push b
 	for _, i := range instances {
 		keys[makeInstanceKey(i)] = struct{}{}
 	}
+	s.edsUpdateByKeys(keys, push)
+}
 
+func (s *ServiceEntryStore) edsUpdateByKeys(keys map[instancesKey]struct{}, push bool) {
+	// must call it here to refresh s.instances if necessary
+	// otherwise may get no instances or miss some new addes instances
```
Comment (ramaraochavali) [inline pilot/pkg/serviceregistry/serviceentry/servicediscovery.go:539]: nit: /addes/ address

**Review by ramaraochavali — APPROVED** [review]
LGTM with some minor comments. @hzxuzhonghu Can you also PTAL?

**Review by jwendell — APPROVED** [review]
