### PR TITLE
Handle out-of-order ztunnel connection removals correctly.

### LINKED ISSUE #54544: CNI gets stuck in `no ztunnel connection` state
Running into an issue on master ambient where CNI gets into a broken state where it has no ztunnel connections. Debug info forthcoming

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**

I had actually fixed this in passing ages ago in internal builds as part of unrelated work, but forgot to backport when that work was dropped.

Should fix https://github.com/istio/istio/issues/54544 and (I bet) https://github.com/istio/istio/issues/53843

Moves ztunnel conns to an ordered slice so we can keep track of what the "previous" connection was and revert back to that, if we happen to get out-of-order `deleteConn` calls due to restart timing variances.

### CODE REVIEW

**Review by keithmattix — COMMENTED** [review]
Looks ~right - what's the desired impact of moving from a map of empty structs to a slice?

**Comment by bleggett** [comment]
> Looks ~right - what's the desired impact of moving from a map of empty structs to a slice?

Because it's slightly messy, it's not necessary, and I want ordering guarantees and simple indexing.

Using conn pointers as map keys was originally done to preclude yanking the wrong connection out of the collection and getting mixed up, by relying on key uniqueness.

But that's not a big deal, it only matters for Add and Delete, which can cover that pretty simply, and we don't mutate the connection collection anywhere except here, in ConnManager, under mutex lock.

**Comment by bleggett** [comment]
Hold, I had some addl unit tests around `ztunnelserver_test.go` in a very old branch to support N ztunnel clients, gonna repurpose those to cover this better.

File: cni/pkg/nodeagent/ztunnelserver.go [hunk 1]
```diff
@@ -85,9 +85,22 @@ func (c *connMgr) deleteConn(conn *ZtunnelConnection) {
...
+		if existingConn != conn {
+			retainedConns = append(retainedConns, existingConn)
+		}
+	}
+	c.connectionSet = retainedConns
+	newSize := len(c.connectionSet)
+	if newSize == 0 {
 		c.latestConn = nil
+	} else {
+		c.latestConn = c.connectionSet[newSize-1]
```
Comment (howardjohn) [inline cni/pkg/nodeagent/ztunnelserver.go:103]: nit: might be easier to just drop `c.latestCon` and make LatestConn() do `c.connectionSet[len(c.connectioSet)-1]`?

**Review by howardjohn — APPROVED** [review]
LGTM

File: cni/pkg/nodeagent/ztunnelserver.go (hunk 1 above)
Comment (bleggett) [reply cni/pkg/nodeagent/ztunnelserver.go:103]: yep, good call.
