### PR TITLE
fix EndpointShardsByService concurrent access

### LINKED ISSUE #12339: 1.1-RC2: Pilot SIGSEGV due to concurrent map access
`EndpointShardsByService` is left unprotected in `loadAssignmentsForClusterIsolated()`

```
fatal error: concurrent map read and map write

goroutine 14483 [running]:
runtime.throw(0x1c12d2d, 0x21)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:608 +0x72 fp=0xc01dcb6e98 sp=0xc01dcb6e68 pc=0x42c0c2
runtime.mapaccess2_faststr(0x194d5c0, 0xc0005d6c00, 0xc0047f348e, 0x32, 0xc00751b5c0, 0x1)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/map_faststr.go:110 +0x458 fp=0xc01dcb6f08 sp=0xc01dcb6e98 pc=0x412368
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).loadAssignmentsForClusterIsolated(0xc000345c30, 0xc008ec3340, 0xc005eb0600, 0xc0047f3480, 0x40, 0x0, 0xc0047f348e)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:708 +0x197 fp=0xc01dcb7268 sp=0xc01dcb6f08 pc=0x170b8f7
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushEds(0xc000345c30, 0xc005eb0600, 0xc00906e8c0, 0x0, 0x19, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:797 +0xc98 fp=0xc01dcb74a8 sp=0xc01dcb7268 pc=0x170d078
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushConnection(0xc000345c30, 0xc00906e8c0, 0xc01507b710, 0x0, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:735 +0x5aa fp=0xc01dcb7560 sp=0xc01dcb74a8 pc=0x16fd43a
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc000345c30, 0x1e51aa0, 0xc0081b4890, 0x0, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:597 +0x2fe6 fp=0xc01dcb7c10 sp=0xc01dcb7560 pc=0x16fc956
```

### PR DESCRIPTION
**Pull request by mandarjog**
Fixes #12339

1. Protects EndpointShardsByService using mutex read lock
2. Opportunistically updates bucketization for convergence time metric.

### CODE REVIEW

**Comment by mandarjog** [comment]
@duderino simple fix, but necessary.

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 1]
```diff
@@ -148,7 +148,7 @@ var (
 	proxiesConvergeDelay = prometheus.NewHistogram(prometheus.HistogramOpts{
 		Name:    "pilot_proxy_convergence_time",
 		Help:    "Delay between config change and all proxies converging.",
-		Buckets: []float64{.01, .1, 1, 3, 5, 10, 30},
+		Buckets: []float64{1, 3, 5, 10, 20, 30, 50, 100},
```
Comment (mandarjog) [inline pilot/pkg/proxy/envoy/v2/ads.go]: Our data so far shows that our bucketization was too fine grained below 30 and had no coverage above 30, which was a problem. @douglas-reid

**Comment by rshriram** [comment]
How come this tweaking doesn't require a FLAG? if data can be used as basis of tweaking then the CDS change clearly has tons of data from multiple independent testers, while this obscure fix changing numbers, adding locks has NO data on perf impact.
Also, the sigsev is not consistent. Occurs only during high load situations. Just like the CDS issue. So to be fair, this needs a flag guard

File: pilot/pkg/proxy/envoy/v2/eds.go [hunk 2]
```diff
@@ -705,7 +705,9 @@ func (s *DiscoveryServer) loadAssignmentsForClusterIsolated(proxy *model.Proxy,
 	}
 
 	// The service was never updated - do the full update
+	s.mutex.RLock()
```
Comment (sbezverk) [inline pilot/pkg/proxy/envoy/v2/eds.go]: It looks like EndpointShardsByService has a method to Lock/Unlock why not to use it?`s.EndpointShardsByService[string(hostname)].mutex.Lock()`

Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/eds.go]: @sbezverk It is to protect `EndpointShardsByService` here, not its field.

**Comment by duderino** [comment]
> Also, the sigsev is not consistent. Occurs only during high load situations. Just like the CDS issue. So to be fair, this needs a flag guard

I think that this bottoms out on minimizing risk and there are two big ways we can do that.

1) test the crap out of something, ideally with an automated test that prevents future regressions, but in case of issues like this that are caught in more prod-like tests we'll accept results from a manual load test, etc.

2) a feature flag to make a more speculative/less tested fix less risky.

So if you look at https://github.com/istio/istio/pull/12278#discussion_r263121336, I think @costinm got it right there.  He said tests || feature flag.

In the case of this PR, I believe @mandarjog reproduced this and verified the fix in a perf cluster, but he should say that and give us some data.  Without that, then, yes, this should be guarded by a flag.

**Comment by mandarjog** [comment]
I was able to reproduce this problem 4 times before I opened the PR. I updated the cluster with a pilot image from this PR, and did not see the problem.
