### PR TITLE
Fixes #15250. Add support for HTTP1.0 for sidecar inbound listeners

### LINKED ISSUE #15250: HTTP 1.0 requests are rejected with HTTP 426 from pods without sidecar to pods with sidecar
**Bug description**

Recently support for HTTP 1.0 was added for sidecar to sidecar (#11511) communication and for gateways (#14448).
However HTTP 1.0 requests are still rejected with HTTP 426, Upgrade Required, from pods without a sidecar even though pilot is running with the env var `PILOT_HTTP10=1`.
This seems to come from the fact that the protocol option `AcceptHttp_10` is only set for the sidecar outbound listeners, but not for the sidecar inbound listeners.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When sidecar to sidecar communication supports HTTP 1.0, clients that do not have a sidecar yet should be able to use HTTP 1.0 too.
Running with a sidecar is not an either/or decision in a cluster.

**Steps to reproduce the bug**

Apply the following manifest that installs one httpbin service and one client deployment with sidecar, and one without:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: server
  labels:
    istio-injection: enabled
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: server
spec:
  peers:
    - mtls:
        mode: PERMISSIVE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  namespace: server
spec:
  selector:
    matchLabels:
      app: testserver
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http-testserver
---
apiVersion: v1
kind: Service
metadata:
  name: testserver
  namespace: server
spec:
  selector:
    app: testserver
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: client-plain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: client-plain
spec:
  selector:
    matchLabels:
      app: client-plain
  replicas: 1
  template:
    metadata:
      labels:
        app: client-plain
    spec:
      containers:
        - name: client
          image: tutum/curl
          command:
            - sleep
            - "1000000"
---
apiVersion: v1
kind: Namespace
metadata:
  name: client-istio
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: client-istio
spec:
  selector:
    matchLabels:
      app: client-istio
  replicas: 1
  template:
    metadata:
      labels:
        app: client-istio
    spec:
      containers:
        - name: client
          image: tutum/curl
          command:
            - sleep
            - "1000000"
```

Send a HTTP 1.0 request from the client with sidecar and see that the request succeeds:
```
k exec -ti -n client-istio client-5d9b5bd996-gp4wk bash 
Defaulting container name to client.
Use 'kubectl describe pod/client-5d9b5bd996-gp4wk -n client-istio' to see all of the containers in this pod.
root@client-5d9b5bd996-gp4wk:/# curl -v testserver.server/get -0
* Hostname was NOT found in DNS cache
*   Trying 10.107.242.213...
* Connected to testserver.server (10.107.242.213) port 80 (#0)
> GET /get HTTP/1.0
> User-Agent: curl/7.35.0
> Host: testserver.server
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< server: envoy
< date: Mon, 01 Jul 2019 06:50:16 GMT
< content-type: application/json
< content-length: 610
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 2
< connection: close
< 
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "testserver.server", 
    "User-Agent": "curl/7.35.0", 
    "X-B3-Parentspanid": "2fc63abf92ccc128", 
    "X-B3-Sampled": "1", 
    "X-B3-Spanid": "c82d141c678a053f", 
    "X-B3-Traceid": "69c363c913fb6e702fc63abf92ccc128", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/server/sa/default;Hash=04477fc671bfccb369eb2d325af5d6e7505b2f322b7a891f4d87a3256f1193c8;Subject=\"\";URI=spiffe://cluster.local/ns/client-istio/sa/default"
  }, 
  "origin": "127.0.0.1", 
  "url": "http://testserver.server/get"
}
* Closing connection 0
```

Now do the same in the pod without sidecar:
```
k exec -ti -n client-plain client-786f7cb968-kgggj bash 
root@client-786f7cb968-kgggj:/# curl -v testserver.server/get  -0
* Hostname was NOT found in DNS cache
*   Trying 10.107.242.213...
* Connected to testserver.server (10.107.242.213) port 80 (#0)
> GET /get HTTP/1.0
> User-Agent: curl/7.35.0
> Host: testserver.server
> Accept: */*
> 
< HTTP/1.1 426 Upgrade Required
< date: Mon, 01 Jul 2019 06:51:22 GMT
* Server istio-envoy is not blacklisted
< server: istio-envoy
< content-length: 0
< 
* Connection #0 to host testserver.server left intact
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ ~/istio/istio-1.2.2/bin/istioctl version 
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
sidecar-injector version: 1.2.2
$ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
helm install ~/istio/istio-1.2.2/install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/istio/values.yaml
helm install ~/istio/istio-1.2.2/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system -f ~/istio/values.yaml
```

Global and pilot part of the values.yaml are
```yaml
global:
  tracing:
    enabled: true 
  useMCP: true
  mtls:
    enabled: true
  disablePolicyChecks: true
  controlPlaneSecurityEnabled: true

pilot:
  traceSampling: 100.0
  resources: ""
  env:
    PILOT_HTTP10: "1"
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Running locally on Docker for Mac.

### PR DESCRIPTION
**Pull request by robertpanzer**
This PR is the same as #15253, just for master.

This PR should be a fix for #15250.
The problem reported there is that even when pilot is started with support for HTTP 1.0 or the node explicitly asks for HTTP 1.0 support with its metadata, Pilot does not configure the HTTP connection manager to accept HTTP 1.0 on the inbound listeners for sidecars.
This results in HTTP 1.0 not being supported for calls from clients in the local cluster that don't have a sidecar.

The logic is pretty much the same as for the gateway and the sidecar outbound listeners.
It might make sense to only support HTTP 1.0 for the "plain" filter chain and keep it unsupported for the Istio mTLS filter chain as the consumer seems to already upgrade to HTTP 1.1, but that would require more changes to the existing logic.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/networking/core/v1alpha3/listener.go [hunk 1]
```diff
@@ -566,6 +566,12 @@ func (configgen *ConfigGeneratorImpl) buildSidecarInboundListenerForPortOrUDS(li
 				}
 			}
 
+			if pilot.HTTP10 || node.Metadata[model.NodeMetadataHTTP10] == "1" {
```
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/listener.go]: undeclared name: `pilot` (from `typecheck`)

Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/listener.go]: changed packages, now under pilot/features or something similar

Comment (robertpanzer) [reply pilot/pkg/networking/core/v1alpha3/listener.go]: Oops, apparently just cherry-picking didn't work.
