### PR TITLE
Disable Envoy's panic mode as default

### LINKED ISSUE #13682: Outlier detection with maxEjectionPercent 100 minHealthPercent 0 not allowing to evict all replicas
**Bug description**
Given this outlier detection config:

```
spec:
  host: customer-rating-service
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 1m
      consecutiveErrors: 1
      maxEjectionPercent: 100
      minHealthPercent: 0
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
```
Let' suppose I have 2 replicas of an application and both always fail with a 502 error. I want that all replicas failing more than once are evicted from the pool. What I was expecting was that the circuit breaker would be open and a 503 response (open circuit breaker) is returned for every request at this service. However what I see is the failing replicas are always called.

**maxEjectionPercent 100 should let me evict 100% of the failing replicas** 

**minHealthPercent 0 shoud prevent outlier detection from being disabled**

**Expected behavior**
All two replicas of the application should be evicted from the pool and the 503 response should be returned

**Steps to reproduce the bug**
Setup a DestinationRule as shown above and configure it service to have two replicas that always answer with a 502 status.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.1.2

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-04T19:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istio on OKD following the OpenShift setup guide and the usual install process.

**Environment where bug was observed (cloud vendor, OS, etc)**
centos

### PR DESCRIPTION
**Pull request by mnktsts2**
Please provide a description for what this PR is for.

Fixes #13682

* By the Envoy's change [#7478](https://github.com/envoyproxy/envoy/pull/7478), we will be abel to disable panic mode by setting `CommonLbConfig.HealthyPanicThreshold` to 0.
* However, the pilot doesn't generate the `HealthyPanicThreshold` field if its value is 0.
* In this case, Envoy interprets that the field value is the default value (50).

---

* when `DestinationRule` with `outlierDetection.minHealthPercent = 0` created

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    name: orders
    namespace: sock-shop
spec:
  host: orders
  trafficPolicy:
    outlierDetection:
      minHealthPercent: 0
```

* a releated sidecar got configuration without `"common_lb_config.healthy_panic_threshold`

```json
{
  "cluster": {
    "common_lb_config": {
      "locality_weighted_lb_config": {}
    }
```

* pilot should generate `healthy_panic_threshold` with `Percent` type value.

```json
{
  "cluster": {
    "common_lb_config": {
      "healthy_panic_threshold": {},
      "locality_weighted_lb_config": {}
    }
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
doesn't this make the default disabled now? I think we have a problem that we can't distinguish between it being unset or being explicitly set to 0

**Comment by mnktsts2** [comment]
> doesn't this make the default disabled now? 

No.
The default value of `outlierDetection.minHealthPercent` is `50[%]`.
So Envoy's panic mode is disabled only when users explicitly set `outlierDetection.minHealthPercent` to `0[%]`.

> I think we have a problem that we can't distinguish between it being unset or being explicitly set to 0

Yes, I think so.
Especially, in the case that the default value isn't `0`, it's difficult to set the Envoy's config field to `0` via gRPC (protoc).

**Comment by mnktsts2** [comment]
@howardjohn Sorry, I mistaken the meaning of "the default value" between the doc and protoc.
`minHealthPercent` is a just `int32` type field.
As you said, this change make the default disabled. umm...

https://github.com/istio/api/blob/99722f53e70c724a43544b1c685b1dcb8a6eef4e/networking/v1alpha3/destination_rule.pb.go#L1529-L1534

**Comment by rshriram** [comment]
fix the comment. Its okay to disable panic threshold by default as its not typically applicable in k8s environments with few pods per service

File: pilot/pkg/networking/core/v1alpha3/cluster_test.go [hunk 1]
```diff
@@ -713,6 +713,33 @@ func TestConditionallyConvertToIstioMtls(t *testing.T) {
 	}
 }
 
+func TestDisablePanicThresholdAsDefault(t *testing.T) {
+	g := NewGomegaWithT(t)
+
+	outliers := []*networking.OutlierDetection{
+		// Unset MinHealthPercent
+		&networking.OutlierDetection{},
```
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/cluster_test.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
		{},
```

**Comment by mnktsts2** [comment]
@rshriram I've fixed it for trial.
But...
* it need to fix some comments in istio.io/api/networking/v1alpha3/destination_rule.proto too.
* it might be a high-risk to change the default behavior.

File: pilot/pkg/networking/core/v1alpha3/cluster.go [hunk 2]
```diff
@@ -846,13 +846,15 @@ func applyOutlierDetection(cluster *apiv2.Cluster, outlier *networking.OutlierDe
 
 	cluster.OutlierDetection = out
 
-	// Set the healthy_panic_threshold field even if its value is 0.
-	// If not the field is set to the default value (50) in Envoy.
+	// Disable panic threshold by default as pod ejection not typically applicable in k8s environments
+	// with few pods per service. (see https://github.com/istio/istio/pull/15609)
```
Comment (rshriram) [inline pilot/pkg/networking/core/v1alpha3/cluster.go]: remove link.

Comment (mnktsts2) [reply pilot/pkg/networking/core/v1alpha3/cluster.go]: OK. I've removed it now.

**Comment by mnktsts2** [comment]
test failure is related to #15769 .. ?
