### PR TITLE
Fix #11818 fix workloadSelector for Sidecars

### LINKED ISSUE #11818: Sidecar resource with workloadSelector only match Services
**Describe the bug**
When registering a Sidecar resource to restrict what a certain Pod can see, the restrictions are not applied if the spec contains a `workloadSelector`.

**Expected behavior**
When a Sidecar resource has a `workloadSelector`, it should be used to select pods for which the restrictions should be applied.

**Steps to reproduce the bug**
Take an empty Kubernetes cluster with Istio 1.1.0-snapshot.6.
Then apply this minimal configuration of one consumer – testcurl – and 2 provider services – testserver and testserver2 – in the namespaces `consumer` and `provider`, respectively:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: consumer

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: provider

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcurl
  namespace: consumer
  labels:
    app: testcurl
spec:
  selector:
    matchLabels:
      app: testcurl
  replicas: 1
  template:
    metadata:
      labels:
        app: testcurl
    spec:
      containers:
        - name: testcurl
          image: tutum/curl
          command:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: testserver
  namespace: provider
  labels:
    app: testserver
spec:
  selector:
    app: testserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver2
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver2
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver2
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: testserver2
  namespace: provider
  labels:
    app: testserver2

spec:
  selector:
    app: testserver2
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
```

Open a shell in the testcurl container and test that a curl command to both providers return HTTP 200:
```
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

Now create this sidecar resource:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: testcurl
  namespace: consumer
spec:
  egress:
    - hosts:
        - "provider/testserver2.provider.svc.cluster.local"
```

After that testcurl is able to only connect to testserver2:
```
# This returns HTTP 404
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get 
# This returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

Now update the same sidecar resource so that it explicitly selects the consumer workload:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: testcurl
  namespace: consumer
spec:
  workloadSelector:
    labels:
      app: testcurl
  egress:
    - hosts:
        - "provider/testserver2.provider.svc.cluster.local"
```
(I added the label `app=testcurl` to the Pod and Deployment just to make sure I didn't miss anything, I would expect though that the label on the Pod would be sufficient.)

Now try the same commands again:
```
# This should still return HTTP 404, but now it returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get 
# This returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

I expected the workloadSelector to still apply the restriction on egress traffic for the testcurl Pod, but as the result of the curl shows, it looks like traffic is not restricted anymore.

**Version**
Istio 1.1.0-snapshot.6 on Kubernetes 1.10.11 on Docker for Mac

**Installation**
```
helm install . --name istio --namespace istio-system \
  -f values-istio-auth-mcp.yaml  \
  --set global.mtls.enabled=true \
  --set global.tracing.enabled=true \
  --set pilot.traceSampling=100.0 \
  --set tracing.enabled=true \
  --set grafana.enabled=true
```

**Environment**
Local, Docker for Mac

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

### PR DESCRIPTION
**Pull request by robertpanzer**
This is a second attempt to fix #11818.
In comparison to the simple/naive attempt in #12620 this PR extends `ServiceDiscovery` with a new function `GetProxyWorkloadLabels(*model.Proxy)` that should return the labels associated with the workload that should be associated with the given proxy.

This way it should also be possible to define Sidecar instances for workloads coming from Consul, or even MCP (Idk if this makes sense though)

In my local, manual tests associating Sidecars worked for K8s Deployments with and without Services.

While going through the code I was also wondering if there is an error here:
https://github.com/istio/istio/blob/release-1.1/pilot/pkg/proxy/envoy/v2/ads.go#L669-L697

First EDS is pushed, and after that the SidecarScope I set. 
But pushing EDS depends on the SidecarScope. So wouldn't it make more sense to set the sidecar scope first and then push EDS?

### CODE REVIEW

File: pilot/pkg/model/service.go [hunk 1]
```diff
@@ -460,6 +460,7 @@ type ServiceAttributes struct {
 }
 
 // ServiceDiscovery enumerates Istio service instances.
+//go:generate $GOPATH/src/istio.io/istio/bin/counterfeiter.sh -o $GOPATH/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/fakes/fake_service_discovery.go --fake-name ServiceDiscovery . ServiceDiscovery
```
Comment (golangcibot) [inline pilot/pkg/model/service.go]: line is 206 characters (from `lll`)

File: pilot/pkg/model/context.go [hunk 2]
```diff
@@ -106,6 +106,10 @@ type Proxy struct {
 
 	// service instances associated with the proxy
 	ServiceInstances []*ServiceInstance
+
+	// labels associated with the workload
+	WorkloadLabels LabelsCollection
+
```
Comment (golangcibot) [inline pilot/pkg/model/context.go]: File is not `goimports`-ed (from `goimports`)

File: pilot/pkg/model/service.go (hunk 1 above)
Comment (kyessenov) [reply pilot/pkg/model/service.go]: add `// nolint: lll` on a line above

Comment (robertpanzer) [reply pilot/pkg/model/service.go]: Thanks!

**Comment by duderino** [comment]
codecov check failed three times in a row

```
--- FAIL: TestCheckCoverage (7.79s)
    main_test.go:216: Coverage dropped:
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/fakes/fake_service_accounts.go:-46.300000% (46.300000% to 0.000000%)
        istio.io/istio/pilot/pkg/serviceregistry/consul/controller.go:-16.100000% (80.300000% to 64.200000%)
```

I doubt we care about the first one (though it could be a clue), but the second one looks significant

**Comment by robertpanzer** [comment]
@duderino I added tests for the consul registry, the code coverage error for that one went away:
```
--- FAIL: TestCheckCoverage (9.71s)
    main_test.go:216: Coverage dropped:
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/fakes/fake_service_accounts.go:-46.300000% (46.300000% to 0.000000%)
=== RUN   TestGoPath
```
I am not sure though how I could have affected code coverage of the service accounts fake, in particular to 0.

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 3]
```diff
@@ -396,6 +398,94 @@ func TestLDS(t *testing.T) {
...
+
+	adsResponse.DumpCfg = true
+	adsResponse.Watch()
+
+	_, err = adsResponse.Wait("lds", 10000*time.Second)
+	if err != nil {
+		t.Fatal("Failed to receive LDS response", err)
+		return
+	}
+	_, err = adsResponse.Wait("lds", 10000*time.Second)
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/lds_test.go]: I realize the other tests do the same, but we probably shouldn't wait for 3 hours

**Comment by howardjohn** [comment]
/lgtm at a high level, but I am not very familiar with this part of the code, you'll need approval from owners as well 

Thanks for working on this

**Comment by robertpanzer** [comment]
I was just looking at the code for adding the EnvoyFilter, and it seems like using the workload labels instead of the Service labels should be trivial now.

**Comment by robertpanzer** [comment]
@duderino Regarding the drop in coverage to 0 in fake_service_accounts.go it looks like the corresponding interface was removed in c4c2baddf61c3f72a0cbeb088c991c8899d8ddc2.

The coverage without this PR seems to come from the fact that fakes.ServiceAccounts was a nested struct in fakes.ServiceDiscovery. I can't tell how that came, if it was really generated by counterfeiter like this or if this was a manual change.

However the method fakes.ServiceDiscovery.GetServiceAccounts() is called.

**Comment by robertpanzer** [comment]
Add a fix for #12957: Make EnvoyFilter also match against Pod Labels instead of Service labels.

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 4]
```diff
@@ -396,6 +403,208 @@ func TestLDS(t *testing.T) {
...
+	server, tearDown := util.EnsureTestServer(func(args *bootstrap.PilotArgs) {
+		args.Plugins = bootstrap.DefaultPlugins
+		args.Config.FileDir = env.IstioSrc + "/tests/testdata/networking/envoyfilter-without-service"
+		args.Mesh.MixerAddress = ""
+		args.Mesh.RdsRefreshDelay = nil
+		args.Mesh.ConfigFile = env.IstioSrc + "/tests/testdata/networking/envoyfilter-without-service/mesh.yaml"
+		args.Service.Registries = []string{}
+	})
+	registry := memServiceDiscovery(server, t)
+	registry.AddWorkload("98.1.1.1", model.Labels{"app": "envoyfilter-test-app", "some": "otherlabel"}) // These labels must match the envoyfilter workload selector
```
Comment (golangcibot) [inline pilot/pkg/proxy/envoy/v2/lds_test.go]: line is 161 characters (from `lll`)

**Comment by howardjohn** [comment]
Test failures look related to the change to EnvoyFilter? @robertpanzer

**Comment by robertpanzer** [comment]
@howardjohn I have no real clue why these are failing. The tests are stable locally, and the test output doesn't really show much.
In fact there should be a lot more, locally I have some info logs, in the logs on k8s-gubernator I see nothing but a lot of empty whitespace.
Also I cannot view the full logs.
I would be glad for any help, in particular as I cannot run these specific test scripts like `prow/istio-unit-tests.sh` locally. `make` works for me.

**Comment by robertpanzer** [comment]
@howardjohn I found the logs now and found out that I forgot to check in the test configuration.
prow/istio-unit-tests.sh is green now.

File: pilot/pkg/model/context.go [hunk 5]
```diff
@@ -199,6 +202,17 @@ func (node *Proxy) SetServiceInstances(env *Environment) error {
 	return nil
 }
 
+func (node *Proxy) SetWorkloadLabels(env *Environment) error {
+	labels, err := env.GetProxyWorkloadLabels(node)
+	if err != nil {
+		log.Errorf("failed to get service proxy workload labels: %v", err)
+		return err
```
Comment (rshriram) [inline pilot/pkg/model/context.go]: I dont think you should bail here. We have had umpteen races where the workload connected to Pilot before Pilot could receive the pod info from kubernetes. You should default to using the workload labels supplied as part of the node metadata [I think its encoded as ISTIO_METAJSON_ or ISTIO_META_..].. cc @GregHanson who did some similar work for the Gateways. In fact the way this is written, it will undo the Gateway bug fix that @GregHanson did to solve some production issues.

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 6]
```diff
@@ -666,6 +669,10 @@ func (s *DiscoveryServer) DeltaAggregatedResources(stream ads.AggregatedDiscover
 func (s *DiscoveryServer) pushConnection(con *XdsConnection, pushEv *XdsEvent) error {
 	// TODO: update the service deps based on NetworkScope
 
+	if err := con.modelNode.SetWorkloadLabels(s.Env); err != nil {
+		return err
+	}
```
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v2/ads.go]: why do you need this during the push?

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 7]
```diff
@@ -396,6 +403,209 @@ func TestLDS(t *testing.T) {
 	// TODO: dynamic checks ( see EDS )
 }
 
+// TestLDS using default sidecar in root namespace
+func TestLDSWithSidecarForWorkloadWithoutService(t *testing.T) {
+	server, tearDown := util.EnsureTestServer(func(args *bootstrap.PilotArgs) {
+		args.Plugins = bootstrap.DefaultPlugins
+		args.Config.FileDir = env.IstioSrc + "/tests/testdata/networking/sidecar-without-service"
```
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v2/lds_test.go]: nice!

**Comment by rshriram** [comment]
@robertpanzer this PR is in the right direction but I am afraid simply fetching the workload labels for the purpose of fixing sidecar/envoyfilter is not sufficient. The proxyServiceInstances is deeply tied to various other parts of the pilot plugin system. RBAC/AuthN plugins rely on the service instance to obtain the appropriate configs for the workloads based on the service attached. We need to ensure that these plugins dont segfault if the service instance is nil.

For example in pilot/plugin/authn/authentication.go: OnInboundFilterChains
```
	port := in.ServiceInstance.Endpoint.ServicePort
	authnPolicy := model.GetConsolidateAuthenticationPolicy(in.Env.IstioConfigStore, in.ServiceInstance.Service, port)
	return setupFilterChains(authnPolicy, in.Env.Mesh.SdsUdsPath, in.Env.Mesh.EnableSdsTokenMount, in.Env.Mesh.SdsUseK8SSaJwt, in.Node.Metadata)
```

Even the sidecar code has some dependency on the service instances. It wont create ingress listeners if there are no service instances attached to the sidecar. 

This is part of the thing that we want to fix and I am working on it.

File: pilot/pkg/model/context.go (hunk 5 above)
Comment (robertpanzer) [reply pilot/pkg/model/context.go]: Sounds good. Will add that rescue.

**Comment by robertpanzer** [comment]
@rshriram: I don't fully understand your point:
> The proxyServiceInstances is deeply tied to various other parts of the pilot plugin system. RBAC/AuthN plugins rely on the service instance to obtain the appropriate configs for the workloads based on the service attached.

If I understand you correctly you are saying that Deployments that don't have a Service are generally not supported by Istio. I can hardly believe given that I am running this locally all the time.
The PR also doesn't change the way how Proxy.ServiceInstances is set.

Also a plugin method like `OnInboundFilterChains()` is called by `ConfigGeneratorImpl.buildSidecarInboundListenerForPortOrUDS()`.
Now a consumer only application does not get an InboundListener, so it should also not fail here, right?

The test `TestLDSWithSidecarForWorkloadWithoutService` should already show that this actually does not segfault, it uses the plugins you mentioned and it uses a Proxy without ServiceInstance.
Or did I miss sth that you mentioned?

>Even the sidecar code has some dependency on the service instances. It wont create ingress listeners if there are no service instances attached to the sidecar.

> This is part of the thing that we want to fix and I am working on it.

But this is a general thing that is not working right now and unrelated to this PR, right?
I added 2 tests to make check that no listeners are created for proxies without services, both with and without Sidecars, these were missing.

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 6 above)
Comment (robertpanzer) [reply pilot/pkg/proxy/envoy/v2/ads.go]: You mean it should go low the check for the EDS-only update?
Makes sense.

**Comment by robertpanzer** [comment]
@rshriram Thinking more about this I guess you could have meant that Pilot could Segfault if the Sidecar contains an Ingress specification.
Therefore I extended the test configuration to have an Ingress.

But I still could not get it to Segfault: 
If the SidecarScope has an Ingress, but there is no Service, there's no Ingress Listener generated:
https://github.com/istio/istio/blob/497c85e7f4e0a0783991d015023a1393a60d4731/pilot/pkg/networking/core/v1alpha3/listener.go#L393-L401

So could you please explain what problems you see?
At the moment I don't see how the code you linked above could be called.

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 8]
```diff
@@ -19,6 +19,13 @@ import (
 	"testing"
 	"time"
 
+	xdsapi "github.com/envoyproxy/go-control-plane/envoy/api/v2"
+
+	xdsapi_listener "github.com/envoyproxy/go-control-plane/envoy/api/v2/listener"
+	xdsapi_http_connection_manager "github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2"
+
+	v2 "istio.io/istio/pilot/pkg/proxy/envoy/v2"
+
```
[the remark this answers is not in the document]
Comment (robertpanzer) [reply pilot/pkg/proxy/envoy/v2/lds_test.go]: Removed the lines according to your recommendation.

**Comment by duderino** [comment]
The ci/circleci: e2e-pilot-noauth-v1alpha3-v2 failure looks like a flake/infra problem:

```
Failed
The connection to the server 10.142.7.32:8443 was refused - did you specify the right host or port?
error: the path "/tmp/istio.e2e.577923725/yaml/istio.yaml" does not exist
```

Rerunning the circleci workflow to see if it occurs again.

**Comment by hzxuzhonghu** [comment]
/lgtm 

Should have more eyes on it

File: pilot/pkg/model/context.go [hunk 9]
```diff
@@ -199,6 +202,17 @@ func (node *Proxy) SetServiceInstances(env *Environment) error {
 	return nil
 }
 
+func (node *Proxy) SetWorkloadLabels(env *Environment) error {
+	labels, err := env.GetProxyWorkloadLabels(node)
+	if err != nil {
+		log.Warnf("failed to get service proxy workload labels: %v, defaulting to proxy metadata", err)
+		labels = LabelsCollection{node.Metadata}
```
Comment (rshriram) [inline pilot/pkg/model/context.go]: @robertpanzer this is not the right way to collect labels.. all the node labels are under the metadata with ISTIO_META_LABELS_... prefix or something like that.  If you simply use all metadata, it will accumulate a lot of junk.

Comment (howardjohn) [reply pilot/pkg/model/context.go]: I would have to double check, but I think node.Metadata contains k8s labels, k8s annotations, and ISTIO_META_LABELS_... but with the `ISTIO_META_LABELS_` prefix already stripped?

File: pilot/pkg/serviceregistry/aggregate/controller.go [hunk 10]
```diff
@@ -242,6 +242,31 @@ func (c *Controller) GetProxyServiceInstances(node *model.Proxy) ([]*model.Servi
...
+			errs = multierror.Append(errs, err)
+		} else if len(labels) > 0 {
+			out = append(out, labels...)
+			break
+		}
+	}
+
+	if len(out) > 0 {
+		if errs != nil {
+			log.Warnf("GetProxyWorkloadLabels() found match but encountered an error: %v", errs)
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/aggregate/controller.go]: this is going to be super noisy. make it debug..

File: pilot/pkg/model/context.go (hunk 9 above)
Comment (rshriram) [reply pilot/pkg/model/context.go]: It also contains non label stuff like HTTP10, interception_mode, etc.. doesn't it?

Comment (howardjohn) [reply pilot/pkg/model/context.go]: Yeah since it pulls in the annotations. it is pretty confusing what gets thrown in there and the code isn't easy to follow, we may need to clean it up/test it/document it later

File: pilot/pkg/serviceregistry/aggregate/controller.go (hunk 10 above)
Comment (robertpanzer) [reply pilot/pkg/serviceregistry/aggregate/controller.go]: Ok, I aligned with GetProxyServiceInstances which also warns in that case.
So is it normal that a Registry returns an error?
My understanding is that a registry returns nil when the proxy is unknown, and an error in case of a real error.

I'll change it to debug.

File: pilot/pkg/model/context.go (hunk 9 above)
Comment (robertpanzer) [reply pilot/pkg/model/context.go]: I just debugged into the code, and the labels – at least for me – are flat key values pairs in node.Metadata.
Also it doesn't look like there's anything stripped:
Screen Shot 2019-04-10 at 6 14 18 PM
To me it's just the plain Metadata map that is in the Node.Metadata of the Envoy configuration. (So the name really makes sense)

Comment (rshriram) [reply pilot/pkg/model/context.go]: image

where are these going?

Comment (rshriram) [reply pilot/pkg/model/context.go]: never mind. they are all flattened into one big kv struct.. this is not good. but its not your problem either. So, lets go with whatever you currently have

File: pilot/pkg/serviceregistry/aggregate/controller.go (hunk 10 above)
Comment (robertpanzer) [reply pilot/pkg/serviceregistry/aggregate/controller.go]: Updated the PR and changed to debug.

**Comment by duderino** [comment]
Will be in 1.1.3 which should be published on 4/15
