### PR TITLE
Generate baggage peer metadata filters in all proxies that talk HBONE

### LINKED ISSUE #59117: Enabling AMBIENT_ENABLE_BAGGAGE causes Protocol Errors (1.29.0)
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I'm testing out the multi-cluster functionality of Ambient, and everything works as it did before (pre-1.29.0) except when I set `AMBIENT_ENABLE_BAGGAGE: 'true'` like the 1.29.0 release notes suggest. The ingress gateway starts to throw errors to all services that are ambient-enabled.

Browsers show this error:
`upstream connect error or disconnect/reset before headers. reset reason: protocol error`

Ingress gateway:
`[2026-02-17T15:29:47.131Z] "GET / HTTP/1.1" 502 UPE upstream_reset_before_response_started{protocol_error} - "-" 0 87 6 - "10.0.10.200,192.168.71.132" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36" "f53d7263-9298-9763-9f29-5ab7d025b66a" "echo.dev1.<my-domain>" "envoy://connect_originate/10.73.1.123:9000" outbound|9000||e
cho.echo.svc.cluster.local envoy://internal_client_address/ 10.73.1.205:443 192.168.71.132:48470 echo.dev1.<my-domain> echo.echo.0 traceID=00-c52a1a795ba6f2085a08cd3927dbe58b-06d77977431838bd-01`

ZTunnel doesn't show errors

Here's my istiod values

```yaml
---
# https://artifacthub.io/packages/helm/istio-official/istiod?modal=values
.custom:
  image:
    repository: &repository istio/pilot
    tag: &tag 1.29.0
profile: ambient
hub: harbor.<my-domain>/docker.io/istio
tag: *tag
variant: distroless
resources:
  requests:
    cpu: 25m
    memory: 250Mi
  limits:
    memory: 976M
autoscaleEnabled: false
autoscaleMin: 2
autoscaleMax: 6
replicaCount: 2
global:
  meshID: ${environment,,}
  network: ${clusterName,,}
  multiCluster:
    enabled: true
    clusterName: ${clusterName,,}
  proxy:
    holdApplicationUntilProxyStarts: true
  variant: distroless
meshConfig:
  accessLogFile: /dev/stdout
  # identical to default, except put traceID=<id> on the end
  accessLogFormat: |
    [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER_RAW% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(TRACEPARENT)%
  enableTracing: true
  defaultConfig:
    tracingServiceName: CANONICAL_NAME_ONLY
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: 'true'
      ISTIO_META_ENABLE_HBONE: 'true'
  extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317  # grpc
        service: otel-lb-collector.monitoring.svc.cluster.local
        resource_detectors:
          environment: {}
    - name: authentik
      envoyExtAuthzHttp:
        service: ${authentikExtAuthHttp}
        port: '9000'
        pathPrefix: /outpost.goauthentik.io/auth/envoy
        headersToDownstreamOnAllow: [cookie]
        headersToUpstreamOnAllow:
          - set-cookie
          - x-authentik-*
        # Add authorization headers to the allow list if you need proxy providers which
        # send a custom HTTP-Basic Authentication header based on values from authentik
          - authorization
        # Tracing headers
          - tracecontext
          - baggage
          - x-request-id
          - traceparent
          - tracestate
        includeRequestHeadersInCheck: [cookie]
  serviceScopeConfigs:
    - servicesSelector:
        matchExpressions:
          - key: istio.io/global
            operator: In
            values: ['true']
      scope: GLOBAL
env:
  ENABLE_NATIVE_SIDECARS: 'true'
  PILOT_ENABLE_AMBIENT: 'true'
  PILOT_ENABLE_AMBIENT_WAYPOINTS: 'true'
  ENABLE_INGRESS_WAYPOINT_ROUTING: 'true'
  AMBIENT_ENABLE_MULTI_NETWORK: 'true'
  AMBIENT_ENABLE_BAGGAGE: 'true'  # seems to be an issue here in ingress gateway
```

### Version

```Text
❯ istioctl version
client version: 1.28.3
control plane version: 1.29.0
data plane version: 1.28.3 (1 proxies), 1.29.0 (6 proxies)
❯ kubectl version
Client Version: v1.35.0
Kustomize Version: v5.7.1
Server Version: v1.35.1
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by krinkinmu**
**Please provide a description of this PR:**

This is a second PR required to fix
https://github.com/istio/istio/issues/59117 (the other one is https://github.com/istio/proxy/pull/6851).

Basically it was reported that enabling baggage-based metadata discovery breaks ingress gateways. That's because when baggage-based peer metadata discovery is enabled we add `peer_metadata` filter to the `connect_originate` and `inner_connect_originate` listeners.

However, for non-waypoints we didn't add a corresponding upstream `peer_metadata` filter to the clusters that route to those internal listeners.

And because those two filters communicate by injecting things into data stream it broke things, as the filters have to come in pairs.

This PR fixes the issue by generating upstream `peer_metadata` filters in the clusters that route to `connect_originate` and `inner_connect_originate` listeners.

Why did we miss this before? We forgot to enable baggage-based peer metadata discovery in the ambient multi-cluster integration tests - those tests would have caught this issue (and more).

So this PR also enables baggage-based peer metadata discovery in ambient multi-cluster tests to make sure that the feature is tested in all kinds of configurations.

Enabling the tests reveals another issue that we overlooked - it's possible to configure traffic policies using `DestinationRule` that would make waypoint create a TLS connection inside HBONE or use PROXY protocol for traffic inside HBONE.

Because peer metadata filters communicate by injecting into data stream it breaks configuration that create TLS sessions and/or use PROXY protocol, because that's done using upstream transport sockets.

We are working on a complete solution for this (basically we want those filters communicate via shared memory instead of relying on injecting into data stream), but in the meantime we want to disable baggage-based peer metadata discovery in some cases.

For now, we do that on cluster-by-cluster basis, so we annontate clusters that have use TLS or PROXY upstream transport sockets for HBONE with metadata.

The metadata key is `istio.peer_metadata` and the field we populate to disable baggage-based peer metadata discovery is
`disable_baggage_discovery`.

NOTE: We use key `istio.peer_metadata` instead of re-using existing `istio` key, because `InternalUpstreamTransport` socket does not merge metadata from multiple sources, so if you have metadata at the host level with the key `istio` and metadata at the cluster level with key `istio`, only one of those can be propagated upstream. While it's possible to disable baggage-based peer metadata discovery on endpoint-by-endpoint basis - it's not really necessary, because whether we use TLS/PROXY for HBONE or not is defined on the cluster level. Therefore we have to pick a different key to avoid endpoint-level metadata overriding cluster-level metadata and vice versa.

Fixes #59117

+cc @grnmeira @keithmattix

### CODE REVIEW

File: pilot/pkg/networking/core/cluster_builder.go [hunk 1]
```diff
@@ -404,6 +406,45 @@ func (cb *ClusterBuilder) applyMetadataExchange(c *cluster.Cluster) {
...
+}
+
+func (cb *ClusterBuilder) maybeDisableBaggageDiscovery(c *cluster.Cluster) {
+	if cb.sendHbone {
+		addDisableBaggageDiscoveryMetadata(c)
+	}
+}
+
+func applyBaggageMetadataDiscovery(c *cluster.Cluster) {
+	if features.EnableAmbientBaggage {
```
Comment (keithmattix) [inline pilot/pkg/networking/core/cluster_builder.go:422]: nit: can we put the feature flag checks in the "maybe" functions? Feels a bit cleaner

File: pilot/pkg/networking/core/cluster_builder.go [hunk 2]
```diff
@@ -404,6 +406,45 @@ func (cb *ClusterBuilder) applyMetadataExchange(c *cluster.Cluster) {
...
+				FilterMetadata: map[string]*structpb.Struct{},
+			}
+		}
+		if _, ok := c.Metadata.FilterMetadata[util.IstioPeerMetadataKey]; !ok {
+			c.Metadata.FilterMetadata[util.IstioPeerMetadataKey] = &structpb.Struct{
+				Fields: map[string]*structpb.Value{},
+			}
+		}
+		m := c.Metadata.FilterMetadata[util.IstioPeerMetadataKey]
+		m.Fields["disable_baggage_discovery"] = &structpb.Value{
```
Comment (keithmattix) [inline pilot/pkg/networking/core/cluster_builder.go]: Just double checking that `m` is a pointer and this actually takes effect?

File: pilot/pkg/networking/core/cluster_waypoint.go [hunk 3]
```diff
@@ -66,6 +65,7 @@ func buildInternalUpstreamCluster(name string, internalListener string, h2 bool)
 		c.TypedExtensionProtocolOptions = map[string]*anypb.Any{
 			v3.HttpProtocolOptionsType: passthroughHttpProtocolOptions,
 		}
+		applyBaggageMetadataDiscovery(c)
```
Comment (keithmattix) [inline pilot/pkg/networking/core/cluster_waypoint.go]: Do we want baggage discovery on every internal cluster? E.g. the forwarder cluster in the e/w gateway?

File: pilot/pkg/networking/core/cluster_waypoint.go [hunk 4]
```diff
@@ -263,13 +264,19 @@ func (cb *ClusterBuilder) buildWaypointInboundVIPCluster(
...
 		}
+		disableBaggageDiscovery = true
 	}
 	// no TLS, we are just going to internal address
 	localCluster.cluster.TransportSocketMatches = nil
 
 	// Wrap the transportSocket with internal listener upstream. Note this could be a raw buffer, PROXY, TLS, etc
 	localCluster.cluster.TransportSocket = util.WaypointInternalUpstreamTransportSocket(transportSocket)
 
+	cb.maybeApplyBaggageMetadataDiscovery(localCluster.cluster)
```
Comment (keithmattix) [inline pilot/pkg/networking/core/cluster_waypoint.go:273]: Is the reason we sometimes both apply discovery and then disable discovery because we might have a transport socket match that doesn't do TLS?

File: pilot/pkg/networking/core/cluster_waypoint.go (hunk 3 above)
Comment (keithmattix) [reply pilot/pkg/networking/core/cluster_waypoint.go]: Oh is this why we don't do the EnableBaggage check in the maybe?

File: pilot/pkg/networking/util/internal_upstream.go [hunk 5]
```diff
@@ -50,50 +51,75 @@ var DefaultInternalUpstreamTransportSocket = InternalUpstreamTransportSocket("in
...
+		},
+		{
+			Kind: &metadata.MetadataKind{Kind: &metadata.MetadataKind_Host_{Host: &metadata.MetadataKind_Host{}}},
+			Name: "istio",
+		},
+	}
+
+	if features.EnableAmbientBaggage {
+		passthroughMetadata = append(passthroughMetadata,
+			&internalupstream.InternalUpstreamTransport_MetadataValueSource{
```
Comment (keithmattix) [inline pilot/pkg/networking/util/internal_upstream.go:67]: Meant to ask this on the proxy PR but any reason we need both cluster and host metadata?

File: pilot/pkg/networking/core/cluster_waypoint.go (hunk 3 above)
Comment (krinkinmu) [reply pilot/pkg/networking/core/cluster_waypoint.go]: Yes, that's why we don't do it in maybe functions, but looking at this code again, I think it might be adding upstream filter to more clusters than needed.

From all the clusters handled by thins function we really only need to add the baggage upstream filter in the encap cluster only. I will move it to GetEncapCluster function that calls this one.

File: pilot/pkg/networking/core/cluster_builder.go (hunk 1 above)
Comment (krinkinmu) [reply pilot/pkg/networking/core/cluster_builder.go:422]: I can do that, but I'd have to do a feature check explicitly when creating encap cluster then. I don't feel strongly either way, so if you prefer to do the check in the maybe function, I can do that - just wanted to clarify why it is done this way currently.

File: pilot/pkg/networking/core/cluster_builder.go (hunk 2 above)
Comment (krinkinmu) [reply pilot/pkg/networking/core/cluster_builder.go]: Yes, it does, but to make it easier for the reader, changed it a bit.

File: pilot/pkg/networking/core/cluster_waypoint.go (hunk 4 above)
Comment (krinkinmu) [reply pilot/pkg/networking/core/cluster_waypoint.go:273]: We need two filters for discovery - upstream and the regular network filter. This part is only responsible for the upstream filter set on the cluster level.

We don't have to generate the filter here if we intend to disable discovery anyways, but we still will have to generate metadata - because we still have a filter on the connect_originate/inner_connect_originate listener that we need to disable using that metadata.


So why did I opt to generate the filter here even though it will be disabled anyways?

In this case it's obvious that we don't need an upstream filter because we configure transport sockets in the same function.

However, in other places in this PR, where we generate outbound clusters for non-waypoints logic is spread a bit more, so we generate upstream filters in one place (the peer metadata filter has to be last filter in the upstream filter list), while transport sockets are configured in another place.

Because those things are spread like that, it's easier to add upstream filter unconditionally - because we don't know what transport socket is configured. And in the code that configures transport sockets we just add metadata when TLS or PROXY transport socket is used to disable discovery.

So I'm generating the upstream filter here even though it's not strictly needed for consistency with other places. This way when we enable baggage-based metadata discovery, the upstream filter will always be there, but it will sometimes be disabled via metadata.

File: pilot/pkg/networking/util/internal_upstream.go (hunk 5 above)
Comment (krinkinmu) [reply pilot/pkg/networking/util/internal_upstream.go:67]: For now we only use the cluster level metadata, but when it comes to proxy implementation - supporting host level metadata does not make things more complicated, so I figured that I'd add both.

I can drop propagation of the host level metadata in this PR given that we don't depend on it at the moment, but I don't think that it's harmful even if we keep it in.

Comment (keithmattix) [reply pilot/pkg/networking/util/internal_upstream.go:67]: Yeah doesn't feel too burdensome to keep it. Just curious

File: pilot/pkg/networking/core/cluster_waypoint.go (hunk 4 above)
Comment (keithmattix) [reply pilot/pkg/networking/core/cluster_waypoint.go:273]: Ack, makes total sense; you're right that it's not as straightforward for non-waypoints. SGTM

File: pilot/pkg/networking/core/cluster_builder.go (hunk 1 above)
Comment (keithmattix) [reply pilot/pkg/networking/core/cluster_builder.go:422]: Ack, this makes sense then
