### PR TITLE
Fix TestController (serviceregistry) Test by making it non racy

### LINKED ISSUE #14760: TestController (serviceregistry) is flaky
--- FAIL: TestController (20.00s)
    controller_test.go:113: timeout while waiting (last error: got 0 notifications from controller, want 7)
FAIL
FAIL	istio.io/istio/pilot/pkg/serviceregistry/external	20.110s
=== RUN   TestServices

https://circleci.com/gh/istio/istio/441428?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by mandarjog**
Fixes #14760

Test relied on getCountAndReset() and incrementCount() never interleaving.
If incrementCount->getCountAndReset->incrementCount is called in that order the exit condition is never satisfied.

Fixed using a non resetting counter.

### CODE REVIEW

File: pilot/pkg/serviceregistry/external/controller_test.go [hunk 1]
```diff
@@ -97,19 +83,19 @@ func TestController(t *testing.T) {
...
 
 	_, err = configController.Create(cfg)
 	if err != nil {
 		t.Fatalf("error occurred crearting ServiceEntry config: %v", err)
 	}
 
 	if err := retry.UntilSuccess(func() error {
-		if c := getCountAndReset(); c != expectedCount {
-			return fmt.Errorf("got %d notifications from controller, want %d", c, 7)
+		if gotcount := atomic.AddInt64(&count, 0); gotcount != expectedCount {
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/external/controller_test.go]: Before we set this to 0, now we just add 0? Should we set this to 0 here?

/hold

**Comment by howardjohn** [comment]
Feel free to remove my hold if I misunderstood, just didn't want it to get automerged if it should be setting to 0

File: pilot/pkg/serviceregistry/external/controller_test.go (hunk 1 above)
Comment (mandarjog) [reply pilot/pkg/serviceregistry/external/controller_test.go]: setting it to `0` was the problem :-)

**Comment by mandarjog** [comment]
@nmittler should this be in 1.2 as well? I have not checked that code closely, but it has less number of lines.

File: pilot/pkg/serviceregistry/external/controller_test.go (hunk 1 above)
Comment (howardjohn) [reply pilot/pkg/serviceregistry/external/controller_test.go]: We have the retry though. So the test expects 7. What if the first time it gives 3, then the second time it gives 4. Now the test passes?

Or if it fails once and got 1, then succeeds and gets 7 more, now it will be at 8 and never pass?

I may be misunderstanding it though

File: pilot/pkg/serviceregistry/external/controller_test.go [hunk 2]
```diff
@@ -97,19 +83,19 @@ func TestController(t *testing.T) {
...
+			return fmt.Errorf("got %d notifications from controller, want %d", gotcount, expectedCount)
 		}
 		return nil
-	}, retry.Delay(1*time.Second), retry.Timeout(20*time.Second)); err != nil {
+	}, retry.Delay(50*time.Millisecond), retry.Timeout(5*time.Second)); err != nil {
```
Comment (nmittler) [inline pilot/pkg/serviceregistry/external/controller_test.go]: Let's make the retry timeout a bit higher ... we have a lot of issues with sluggishness on prow.  Maybe 10?

**Comment by nmittler** [comment]
@mandarjog yeah let's get it into 1.2

File: pilot/pkg/serviceregistry/external/controller_test.go (hunk 1 above)
Comment (nmittler) [reply pilot/pkg/serviceregistry/external/controller_test.go]: @howardjohn I think the new code is correct. The retry loop is really just getting the current value (it should probably be replaced with `atomic.LoadInt64` for clarity). There should only be 7 events total and we're waiting up to the timeout for all 7 to occur.

Or am I missing something?

Comment (howardjohn) [reply pilot/pkg/serviceregistry/external/controller_test.go]: Ok yeah I think you are right. I was thinking we reran the whole test. Thanks
/hold-cancel

**Comment by mandarjog** [comment]
@duderino @geeknoid please merge this.
It only updates the test code that it deflakes 
We don’t need to babysit this PR anymore.

**Comment by mandarjog** [comment]
@nmittler 5s is plenty. Previously test failed because of a race, and more time could not help.
