### PR TITLE
re-add enableAnalysis feature to istiod

### LINKED ISSUE #21074: enableAnalysis doesn't work with 1.5 galley
To reproduce, using Master, `istioctl manifest generate --set values.galley.enableAnalysis=true | grep -i analysis`.  There will be no `--enableAnalysis` output.

The Istiod deployment does not get the `--enableAnalysis=true` flag.

The Installer _operator/pkg/vfs/assets.gen.go_ is generated from _install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml_ which does include the flag generation, but only for the istio-galley Deployment.  The Istiod Deployment does not have it.

### LINKED ISSUE #21341: move status update controller from Galley to IstioD
Istio 1.4 had an experimental feature to set .Status fields on Istio CRDs.

This feature was part of Galley and did not make it into IstioD.

Ideally it would not be experimental, it would be beta, and always enabled.

### PR DESCRIPTION
**Pull request by therealmitchconnors**
add analyzer to istiod/galley
Add enableAnalysis flag to Pilot.

fixes #21341 
prerequisite to fixing #21074

### CODE REVIEW

File: pilot/cmd/pilot-discovery/main.go [hunk 1]
```diff
@@ -153,6 +153,8 @@ func init() {
 		"The domain serves to identify the system with spiffe")
 	discoveryCmd.PersistentFlags().StringVar(&serverArgs.Service.Consul.ServerURL, "consulserverURL", "",
 		"URL for the Consul server")
+	discoveryCmd.PersistentFlags().BoolVar(&serverArgs.Config.EnableConfigAnalysis, "enableAnalysis", serverArgs.Config.EnableConfigAnalysis,
+		"Enable config analysis service")
```
Comment (ayj) [inline pilot/cmd/pilot-discovery/main.go]: Instead of a flag can you use the [feature package ]( pilot/pkg/features/pilot.go) for this purpose?

File: pilot/pkg/bootstrap/configcontroller.go [hunk 2]
```diff
@@ -64,6 +67,11 @@ const (
 // initConfigController creates the config controller in the pilotConfig.
 func (s *Server) initConfigController(args *PilotArgs) error {
 	meshConfig := s.environment.Mesh()
+	if args.Config.EnableConfigAnalysis {
+		if err := s.initInprocessAnalysisController(args); err != nil {
+			return err
+		}
+	}
```
Comment (ayj) [inline pilot/pkg/bootstrap/configcontroller.go]: Move lines 70-74 to the else conditional at line 93 since CRD status depends on kube-apiserver.

File: pilot/pkg/bootstrap/configcontroller.go [hunk 3]
```diff
@@ -268,6 +276,41 @@ func mcpSecurityOptions(ctx context.Context, configSource *meshconfig.ConfigSour
...
+	processingArgs.Liveness.UpdateInterval = 0
+	processingArgs.Readiness.UpdateInterval = 0
+	processingArgs.Insecure = true // TODO - use sidecar?
+	processingArgs.EnableServer = false
+	processingArgs.MeshConfigFile = args.Mesh.ConfigFile
+	processingArgs.EnableConfigAnalysis = true
+
+	processing := components.NewProcessing(processingArgs)
+
+	s.addStartFunc(func(stop <-chan struct{}) error {
```
Comment (ayj) [inline pilot/pkg/bootstrap/configcontroller.go]: Only one controller instance (pod) should be updated CRD status at a time. You can use s.leaderElection.AddRunFunction instead which will integrate with the existing leader election logic.

**Comment by howardjohn** [comment]
What I mean is does it really make sense to spin up a whole MCP server just for this? And if it does, does it at least align with the in process MCP stuff so when we do merge that it will use that?

File: pilot/pkg/bootstrap/configcontroller.go (hunk 3 above)
Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: Are we starting a full on gRPC server here?

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: @howardjohn no, we are starting a status controller.

@ayj my understanding is that the galley status controller already solves for the leader election problem by debouncing status updates and only writing updates when there is actually a change.  This was functional in 1.4, with galley scaled horizontally, so I don't think anything should need to be changed to support horizontal scale in istiod.

File: pilot/cmd/pilot-discovery/main.go (hunk 1 above)
Comment (therealmitchconnors) [reply pilot/cmd/pilot-discovery/main.go]: I thought using pflags and viper was  the approved design (https://docs.google.com/document/d/1M-qqBMNbhbAxl3S_8qQfaeOLAiRqSBpSgfWebFBRuu8/edit#heading=h.qex63c29z2to).

Has this design been replaced?

**Comment by therealmitchconnors** [comment]
> Shouldn't we be relying on the MCP work that @ayj and @nmittler have been working on for this?

This is a copy of @ayj 's work to get galley running inside pilot, trimmed down specifically to analyzers.  There is a lot of optimization possible if the Networking team has time, but this will at least undo the dropped features from 1.5.

File: pilot/pkg/bootstrap/configcontroller.go (hunk 2 above)
Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: done.

File: pilot/pkg/bootstrap/configcontroller.go (hunk 3 above)
Comment (ayj) [reply pilot/pkg/bootstrap/configcontroller.go]: NewProcessing() will start a gRPC server which isn't needed to enable status updates. You could update processing.Start() to not start the server if EnableServer is false.

As istiod scales we don't need each replica watching and updating status in parallel.

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: As we add config distribution status to istiod in 1.6, every istiod instance will be required to participate in status updates, as each istiod will have distribution information for a fraction of the envoy proxies.  I don't see any way around this...

With leader election, how do you handle the lead istiod being shut down?  Is there a become_leader event?

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: leader election is already fully handled by the library and handles shutdown, etc.

if I have 3 istiods, which have different views of distribution, all 3 are going to write to the same CR? How does that work?

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: Each of them writes only a part of the status - the part they are familiar with.  Because the envoys are divided among the three istiod's, they each have a part of the picture.  Each one writes the number of envoys which have acked the changed and the number of envoys which have not.  These numbers are added up using a pessimistic concurrency model to come up with the total config distribution status.

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: Can you link an design about what they are writing? I can't wrap my head around how this can work (yet)

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: I am digging through history to find the doc.  Since this particular doc is for config distribution status, which this PR does not achieve, can we continue this part of the conversation in a different channel?

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: Sure.

I don't status controller should have multiple replicas though. We had issues with split brain in the past where they fight each other and get into a reconcile loop. From other projects I have seen leader election always used for status. Are there any reasons why we should not do it here?

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: I can implement it here, if that is what it takes to get this PR merged, but it will need to be undone in the next week to facilitate Config Distribution Status.  I am generally not in favor of implementing throw away code, but it does look like it's only a few lines...

When you reference past split brain issues, are you referring to Status Controllers?  I am not as familiar with implementation as I'd like, but Oz and Martin designed the status controller to specifically avoid such a scenario... Unfortunately, we no longer have them to weigh in...

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: Yes. We have had a status controller in pilot for a very long time.

If we are going to make decisions based on  Config Distribution Status then that is in scope for this PR and I would like to see the design before deciding anything.

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: Also my gRPC concerns were not addressed I believe, just want to make sure they do not get lost in the thread here

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: Re: Status Controller.  I understand now.  The Status Controller used here is not Pilot's Status Controller (istio.io/pilot/pkg/config/kube/ingress/StatusUpdater), but Galley's (istio.io/galley/pkg/config/source/kube/apiserver/status/Controller), which has built in protection against dual brain.  I will see if I can find an old design doc from Oz or Martin describing how that works.

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: My most recent commit is intended to address the GRPC concern.

File: pilot/cmd/pilot-discovery/main.go (hunk 1 above)
Comment (ayj) [reply pilot/cmd/pilot-discovery/main.go]: envvars are easier to patch with kustomize. It also fails more gracefully if we remove an option.

cc @costinm @howardjohn

Comment (howardjohn) [reply pilot/cmd/pilot-discovery/main.go]: The design was never implemented, as far as I know. The current model we have been using is:
* Temporary flags (like this) are under feature package
* Permanent settings are in mesh config

File: pilot/pkg/bootstrap/configcontroller.go (hunk 3 above)
Comment (ayj) [reply pilot/pkg/bootstrap/configcontroller.go]: We only need one instance to perform CRD analysis. Leader election is a suitable solution to that problem and we already have support.  Use `s.leaderElection.AddRunFunction` instead of `s.addStartFunc`.

For config status distribution, in addition to any split brain issues, it also puts additional load on the kube-apiserver. This could be particularly bad in larger clusters, e.g. lots of config x lots of istiod instances.

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: Based on video chat with Jason and John, moving analysis to istiod's leader election so as only to run one.  Will need different solution for distribution status.

File: pilot/pkg/bootstrap/configcontroller.go [hunk 4]
```diff
@@ -268,6 +276,41 @@ func mcpSecurityOptions(ctx context.Context, configSource *meshconfig.ConfigSour
...
+	processingArgs.MeshConfigFile = args.Mesh.ConfigFile
+	processingArgs.EnableConfigAnalysis = true
+
+	processing := components.NewProcessing(processingArgs)
+
+	s.leaderElection.AddRunFunction(func(stop <-chan struct{}) {
+		if err := processing.Start(); err != nil {
+			log.Errorf("error starting galley analysis server: %v", err)
+			// TODO: if we can't start analysis, we should un-elect ourselves, but pilot's API doesn't provide that
+			// should we add an unelect interface to pilot?
```
Comment (therealmitchconnors) [inline pilot/pkg/bootstrap/configcontroller.go]: This concerns me.  And the stop ctx for leader election is the istiod server stop context, so the only way to release the leader lock is to die altogether...

Comment (ayj) [reply pilot/pkg/bootstrap/configcontroller.go]: The context is re-created after election is lost (see https://github.com/istio/istio/blob/5ea7387905082ab0374d4184b06deced86d72ba4/pilot/pkg/leaderelection/leaderelection.go#L55). I think the only change required is to pass the context (or the cancel function) to the leader election run functions so that they have the option to give up election.

Comment (howardjohn) [reply pilot/pkg/bootstrap/configcontroller.go]: I think with everything else we just exit if we fail on startup, not sure we need to do anything fancy here?

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: Should I just write to stop?

Comment (therealmitchconnors) [reply pilot/pkg/bootstrap/configcontroller.go]: @ayj unfortunately, the cancel function does not cause the leader lock to be released.  See https://github.com/istio/istio/blob/5ea7387905082ab0374d4184b06deced86d72ba4/pilot/pkg/leaderelection/leaderelection.go#L103

If I am reading this correctly, this also means that pilot never gracefully releases the leader lock.  When the leader shuts down (even gracefully), it simply stops renewing the lease, and 30 seconds may elapse before the lease expires and another leader takes its place.  Am I understanding this correctly?

Comment (ayj) [reply pilot/pkg/bootstrap/configcontroller.go]: Ah, then I'd just exit with the appropriate error message and revisit later when ReleaseOnCancel is fixed.
