### PR TITLE
Handling Istiod DNS cert rotation for k8s CA

### LINKED ISSUE #42170: Istiod server and webhooks DNS certs are not being rotated for k8s CA with legacy/custom signer
### Bug Description

When Istiod's DNS certificate is signed by [ANY non-istiod CA](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/pilot/pkg/bootstrap/certcontroller.go#L108), we don't track the lifetime of the DNS cert issued to ensure that it doesn't expire. This presents a problem - Istio might present expired cert to clients talking to it and TLS communication will not happen.

Though we are passing CITADEL_SELF_SIGNED_CA_CERT_TTL as [ttl](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/pilot/pkg/bootstrap/certcontroller.go#L111) while calling k8s provider for cert but it may not be honoured as we are only adding it as [annotation](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/security/pkg/k8s/chiron/utils.go#L218) which is only valid for cert manager based implementation. We can not guarantee if CA server will honour the TTL requested.

The proposal is to track TTL from the response of CA server while signing the CSR and renew the DNS cert according to grace period for legacy and custom signer for k8s cert provider.

This issue does not happen for istiod cert provider because :-
1. Lifetime of DNS cert is [same](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/pilot/pkg/bootstrap/certcontroller.go#L144) as lifetime of istiod CA cert.
2. CA cert will be refreshed according to [grace period percentile](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/pilot/pkg/bootstrap/istio_ca.go#L109) and DNS certs are [watching](https://github.com/istio/istio/blob/d9a190cb5cedf4700a6cac6cd53a669329f7fa37/pilot/pkg/bootstrap/certcontroller.go#L162) CA cert so when CA cert is renewed then DNS certs will also be renewed. 

### Version

```prose
master branch
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hemendrateli**
**Please provide a description of this PR:**
Handling Istiod DNS cert rotation for k8s CA
resolve #42170

- Tested manually for k8sCA (k8s v1.21) and custom signer for cert rotation. Also tested connectivity between sleep and httpbin pods.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/bootstrap/certcontroller.go [hunk 1]
```diff
@@ -205,6 +225,26 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
 	}
 }
 
+func (s *Server) watchDNSCertForK8sCA(pollingInterval time.Duration, stop <-chan struct{}, defaultCACertPath string, signerName string, approveCsr bool, requestedLifetime time.Duration) {
+	certUtil := certutil.NewCertUtil(int(defaultCertGracePeriodRatio * 100))
+	for {
+		if !sleep.Until(stop, pollingInterval) {
```
Comment (hzxuzhonghu) [inline pilot/pkg/bootstrap/certcontroller.go:231]: why poll instead of using the waitTime?

Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:231]: Using waitTime will restrict us to only one cert monitoring(if we want to extend this function to poll more than one cert). In WaitTime also we will need to sleep for 'waitTime' duration.
Also in other implementations in istio I have seen checking in particular interval for CA cert monitoring.

Comment (howardjohn) [reply pilot/pkg/bootstrap/certcontroller.go:236]: We don't need to poll more than one cert ever. If we are just trying to renew a cert before it expires seems like we can do things a lot simpler

File: pilot/pkg/bootstrap/server_test.go [hunk 2]
```diff
@@ -627,6 +630,57 @@ func TestInitOIDC(t *testing.T) {
...
+		dnsNames:                []string{"abc.xyz"},
+	}
+
+	for _, tt := range tests {
+		stop := make(chan struct{})
+		t.Run(tt.name, func(t *testing.T) {
+			s.istiodCertBundleWatcher.SetAndNotify(testcerts.ServerKey, tt.certToWatch, testcerts.CACert)
+
+			go s.watchDNSCertForK8sCA(2*time.Second, stop, "", "test-signer", true, time.Duration(0))
+			sleep.Until(stop, 10*time.Second)
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/server_test.go:672]: sleep() is not appropriate in tests, see https://github.com/istio/istio/wiki/test%20flakes

Comment (shankgan) [reply pilot/pkg/bootstrap/server_test.go:672]: IMO: one way is to keep periodically polling the newer cert to compare with the older cert to see if there is a diff and report an error if they are the same after timeout

File: pilot/pkg/bootstrap/certcontroller.go (hunk 1 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go]: Calculating waitTime and sleeping for waitTime before renewing the cert.

File: pilot/pkg/bootstrap/server_test.go (hunk 2 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/server_test.go]: Now we are not having any specific timeInterval for sleep. We are using already expired cert so watchDNSCertForK8sCA should not sleep and execute cert rotation with fake client. I am adding sleep of 500 ms in test before sending stop signal to watchDNSCertForK8sCA to let watchDNSCertForK8sCA complete once.

File: pilot/pkg/bootstrap/certcontroller.go [hunk 3]
```diff
@@ -205,6 +222,27 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
...
+	for {
+		waitTime, _ := certUtil.GetWaitTime(s.istiodCertBundleWatcher.GetKeyCertBundle().CertPem, time.Now(), time.Duration(0))
+		if !sleep.Until(stop, waitTime) {
+			return
+		}
+		certChain, keyPEM, _, err := chiron.GenKeyCertK8sCA(s.kubeClient.Kube(),
+			strings.Join(s.dnsNames, ","), defaultCACertPath, signerName, approveCsr, requestedLifetime)
+		if err != nil {
+			log.Fatalf("failed regenerating key and cert for istiod by kubernetes: %v", err)
+		}
```
Comment (hzxuzhonghu) [inline pilot/pkg/bootstrap/certcontroller.go:241]: should we also have a retry, as you know it is very common to have error because of network transient  issue or ratelimited

Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:241]: Retries are already being handled in GenKeyCertK8sCA while submitting CSR and getting signed certificate.

Comment (hzxuzhonghu) [reply pilot/pkg/bootstrap/certcontroller.go:241]: I am concerned the fatal will cause process exit

Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:241]: got it...I can change it to log.Errorf to not exit the process.

Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:241]: I changed the log level, @hzxuzhonghu Please have a look.

Comment (hzxuzhonghu) [reply pilot/pkg/bootstrap/certcontroller.go:241]: Still need continue

Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:242]: oops..sorry, missed it. @hzxuzhonghu  Added it now, thank you.

File: pilot/pkg/bootstrap/server_test.go (hunk 2 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/server_test.go]: I have added sleep of 1 sec in test to wait for watchDNSCertForK8sCA to complete before we send stop signal, I agree it might be flaky sometimes.
@howardjohn @shankgan  We can do few things :-
1. Remove 'valid cert no rotation' test scenario from unit test and add retry untill cert changes with 10sec timeout. It will work for 'expired cert rotation' scenario as cert will be changed.
2. Take out whatever is inside for loop in watchDNSCertForK8sCA and create a new function for that. Now test this new function for unit testing for both test scenarios as this new function will run only once if called directly. Combine this with 1st point to test watchDNSCertForK8sCA for expired cert rotation using retryUntill.
3. Let it be, observe if test is flaky and fix if test is flaky in future.

File: pilot/pkg/bootstrap/certcontroller.go [hunk 4]
```diff
@@ -205,6 +222,28 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
 	}
 }
 
+func (s *Server) watchDNSCertForK8sCA(stop <-chan struct{},
+	defaultCACertPath string,
+	signerName string,
+	approveCsr bool,
```
Comment (hzxuzhonghu) [inline pilot/pkg/bootstrap/certcontroller.go:228]: nit: i can see all the caller set it true, so can remove it

File: pilot/pkg/bootstrap/certcontroller.go [hunk 5]
```diff
@@ -205,6 +222,28 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
 	}
 }
 
+func (s *Server) watchDNSCertForK8sCA(stop <-chan struct{},
```
Comment (hzxuzhonghu) [inline pilot/pkg/bootstrap/certcontroller.go:225]: nit: rename to be more obvious. maybe call something like `RotateDNSCertForK8sCA`

**Review by howardjohn — COMMENTED** [review]
Test is flaky: `1159 runs so far, 14 failures (98.81% pass rate). 2.227272046s avg, 3.00710853s max, 2.155422613s min`

**Comment by hemendrateli** [comment]
> 
@howardjohn Planning to add only expired cert rotation scenario in unit test by having retryUntill with 10sec timeout. This should work faster in most cases and flakiness would be minimal as timeout is 10sec.

File: pilot/pkg/bootstrap/certcontroller.go (hunk 4 above)
Comment (shankgan) [reply pilot/pkg/bootstrap/certcontroller.go:228]: this value is set false in some scenarios in non-OSS code. Want to keep it to minimize diff.

File: pilot/pkg/bootstrap/server_test.go (hunk 2 above)
Comment (shankgan) [reply pilot/pkg/bootstrap/server_test.go]: "expired cert rotation" appears to be the flaky test with a 1 sec timeout. IMO, we could add two separate timeouts - 10 sec for expired cert rotation and 1 sec for  'valid cert no rotation'. In former case we can use retryUntil to keep polling until cert has rotated. In later case, it makes sense to sleep for 1 sec and just check that cert has not rotated.

File: pilot/pkg/bootstrap/server_test.go [hunk 6]
```diff
@@ -627,6 +630,57 @@ func TestInitOIDC(t *testing.T) {
...
+
+			go s.watchDNSCertForK8sCA(stop, "", "test-signer", true, time.Duration(0))
+			sleep.Until(stop, 1*time.Second)
+			close(stop)
+
+			st := string(s.istiodCertBundleWatcher.GetKeyCertBundle().CertPem)
+			certRotated := st != string(tt.certToWatch)
+			if certRotated != tt.certRotated {
+				t.Fatalf("expect certRotated is %v while actual certRotated is %v", tt.certRotated, certRotated)
+			}
```
Comment (shankgan) [inline pilot/pkg/bootstrap/server_test.go:679]: nit: wondering if for the expired cert-test case, could we add a few more validations on the returned cert? for instance, just ensure that the new cert has a valid lifetime?

File: pilot/pkg/bootstrap/certcontroller.go (hunk 4 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:228]: Resolving this comment in the favour of Shankar's comment, Please feel free to open the discussion again if changes are needed.

File: pilot/pkg/bootstrap/certcontroller.go (hunk 5 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go]: Done, thank you.

File: pilot/pkg/bootstrap/server_test.go (hunk 6 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/server_test.go:686]: Done.

File: pilot/pkg/bootstrap/server_test.go (hunk 2 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/server_test.go]: @howardjohn @shankgan 
Added retryUntil for 10sec timeout with adding sleep for 1sec in starting of validation of cert changed.

1. For Expired cert case

- It will retry in every 1 second for total 10 seconds. In most cases cert should be changed in 1 sec so test will not take much time. 10 second timeout minimise test flakiness.

2. For valid cert no rotation case

- After 1st run (in one second) the flow will come out of RetryUntill block as cert is same, so this should complete in one second.

**Review by shankgan — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

File: pilot/pkg/bootstrap/certcontroller.go [hunk 7]
```diff
@@ -205,6 +222,28 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
...
 
+func (s *Server) RotateDNSCertForK8sCA(stop <-chan struct{},
+	defaultCACertPath string,
+	signerName string,
+	approveCsr bool,
+	requestedLifetime time.Duration,
+) {
+	certUtil := certutil.NewCertUtil(int(defaultCertGracePeriodRatio * 100))
+	for {
+		waitTime, _ := certUtil.GetWaitTime(s.istiodCertBundleWatcher.GetKeyCertBundle().CertPem, time.Now(), time.Duration(0))
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/certcontroller.go:233]: is there any risk that GenKeyCertK8sCA somehow returns a cert that makes GetWaitTime return 0s and we spin in an infinite loop?

File: pilot/pkg/bootstrap/certcontroller.go [hunk 8]
```diff
@@ -205,6 +222,28 @@ func (s *Server) watchRootCertAndGenKeyCert(stop <-chan struct{}) {
 	}
 }
 
+func (s *Server) RotateDNSCertForK8sCA(stop <-chan struct{},
+	defaultCACertPath string,
+	signerName string,
+	approveCsr bool,
+	requestedLifetime time.Duration,
+) {
+	certUtil := certutil.NewCertUtil(int(defaultCertGracePeriodRatio * 100))
```
Comment (howardjohn) [inline pilot/pkg/bootstrap/certcontroller.go:231]: does this mean we only refresh when its already expired? Shouldn't we refresh before its expired?

**Review by howardjohn — APPROVED** [review]

File: pilot/pkg/bootstrap/certcontroller.go (hunk 8 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:231]: It will be refreshed according to grace period ratio before expiry, for this case grace period ratio is 0.5 so will be refreshed in half time of TTL.

File: pilot/pkg/bootstrap/certcontroller.go (hunk 7 above)
Comment (hemendrateli) [reply pilot/pkg/bootstrap/certcontroller.go:233]: I can't think of that case unless k8s CA does not behave as expected and returns expired certs.
