### PR TITLE
Separate CNI agent network namespace from host

### LINKED ISSUE #54821: Istio CNI in ambient mode should not run in the hostNetwork
Running in hostNetwork is problematic because it means any ports we bind are in the host resources. This can lead to port conflicts.

Interestingly, we don't fail when we bind to the readiness port, leading to repeated strange behaviors like https://github.com/istio/istio/issues/54726 where we get random status codes as we probe random processes that happened to take our port.

All of this can be avoided by not using hostNetwork. While we need to interact with the host namespace, that is fine -- we can change namespaces to do so, like we do for other pods.

This can be done via `nsenter  --net=/host/proc/1/ns/net` and the Go equivilents.

I believe there are a few places we would need to wrap with namespaces:

* ipset stuff
* host iptables manipulation
* the iptables detection

cc @bleggett @leosarra

### PR DESCRIPTION
**Pull request by leosarra**
**Please provide a description of this PR:**

Fixes #54821 and #54726

### CODE REVIEW

File: cni/pkg/nodeagent/server.go [hunk 1]
```diff
@@ -66,6 +68,46 @@ type Server struct {
...
 
+// runWithHostNs executes the provided function within the host network namespace
+func runWithHostNs(f func() error) error {
+	if f == nil {
+		return nil
+	}
+	runtime.LockOSThread()
+	defer runtime.UnlockOSThread()
+
+	currentNS, err := netns.GetCurrentNS()
```
Comment (leosarra) [inline cni/pkg/nodeagent/server.go:79]: It is probably better if use netNs.WithNetNSPath/Do instead of re-implementing the switch logic

File: cni/pkg/nodeagent/server.go [hunk 2]
```diff
@@ -380,21 +429,24 @@ func (s *meshDataplane) addPodToHostNSIpset(pod *corev1.Pod, podIPs []netip.Addr
 	var addedIps []netip.Addr
```
Comment (leosarra) [inline cni/pkg/nodeagent/server.go:429]: I like the idea of wrapping the lowest-level calls in this file (e.g. addPodToHostNSIpset) to run in the host namespace. It looks tidy and logical, but it may not always be the best approach. During the initial sync, we will jump in and out of the namespace for each pod.
https://github.com/istio/istio/blob/ee0fd9fa25592f24963b0d7c284bd556a14f3905/cni/pkg/nodeagent/server.go#L380-L397

I'm a bit conflicted on this one, I need to think about it

File: cni/pkg/nodeagent/server.go [hunk 3]
```diff
@@ -66,6 +68,52 @@ type Server struct {
...
 }
 
+// runWithHostNs executes the provided function within the host network namespace
+func runWithHostNs(f func() error) error {
+	if f == nil {
+		return nil
+	}
+
+	if _, err := os.Stat("/host/proc/1/ns/net"); os.IsNotExist(err) {
+		log.Warnf("Path %s does not exist, running function with switching to host network namespace\n", "/host/proc/1/ns/net")
```
Comment (leosarra) [inline cni/pkg/nodeagent/server.go:78]: There is no good reason for this scenario to occurr, unless it is a unit test

File: cni/pkg/nodeagent/server.go [hunk 4]
```diff
@@ -66,6 +67,22 @@ type Server struct {
...
 }
 
+// runWithHostNs executes the provided function within the host network namespace
+func runWithHostNs(f func() error) error {
+	if f == nil {
+		return nil
+	}
+	hostNs := "/host/proc/1/ns/net"
+	if _, err := os.Stat(hostNs); os.IsNotExist(err) {
+		log.Warnf("Path %s does not exist, running function without switching to host network namespace\n", hostNs)
```
Comment (howardjohn) [inline cni/pkg/nodeagent/server.go:77]: Hmm, this seems potentionally dangerous. We might want to fail hard. Otherwise we will not configure the network right.

Plausibly at the startup, we can open the file descriptor and store it and pass it around. Then we have 1 point of failure at startup vs on every operation? I guess the `setns` can fail at anytime though

File: cni/pkg/nodeagent/server.go (hunk 2 above)
Comment (howardjohn) [reply cni/pkg/nodeagent/server.go:437]: My intuition was going to be even lower level -- at the `AddIP` level. But agree on the in-and-out issue..

File: manifests/charts/istio-cni/templates/daemonset.yaml [hunk 5]
```diff
@@ -55,10 +55,6 @@ spec:
 {{ toYaml .Values.podAnnotations | indent 8 }}
         {{- end }}
     spec:
-{{if .Values.ambient.enabled }}
```
Comment (howardjohn) [inline manifests/charts/istio-cni/templates/daemonset.yaml:58]: I am wondering if we want to keep this as an optional thing (permanently or for a few releases while we validate things)...
I cannot come up with many great reasons though

**Review by howardjohn — COMMENTED** [review]
Nice! Looks good at a high level, the hard part will be making sure we capture everything and find the right level to apply the nsenter at

File: manifests/charts/istio-cni/templates/daemonset.yaml (hunk 5 above)
Comment (leosarra) [reply manifests/charts/istio-cni/templates/daemonset.yaml:58]: I think we can keep a  "shareHostNetwork" option for some releases, I added it to the compatibility profiles as part of the deprecation process.
If someone comes up during the deprecation process with a good reason to keep it then we could retain it

File: cni/pkg/nodeagent/server.go (hunk 4 above)
Comment (leosarra) [reply cni/pkg/nodeagent/server.go]: Removed the check, as there was no good reason for this scenario to occurr, unless it is a unit test.
Now the hostNS Fd is created at boot and carried over to the netserver (which has the duty of closing the fd when stopping).
During boot I'm also checking if hostNS == currentNS by comparing the inodes, if they are the same then I will disable the network switching logic and the old behavior will be used instead

File: cni/pkg/iptables/iptables.go [hunk 6]
```diff
@@ -616,7 +617,6 @@ func (cfg *IptablesConfigurator) DeleteHostRules() {
 }
 
 func (cfg *IptablesConfigurator) AppendHostRules() *builder.IptablesRuleBuilder {
-	log.Info("configuring host-level iptables rules (healthchecks, etc)")
```
Comment (leosarra) [inline cni/pkg/iptables/iptables.go:619]: unrelated to the issue:
During testing, I noticed that we were printing this log line twice since it is used to create the IptablesRuleBuilder for both the creation and deletion of the rules. I moved it to only print during creation to ensure consistency with the in-pod rules handling.

File: cni/pkg/nodeagent/server.go (hunk 2 above)
Comment (leosarra) [reply cni/pkg/nodeagent/server.go:473]: I have updated the logic to include a flag, allowing syncHostIPSets to perform a single namespace jump while disabling the jumps in the lower-level calls. syncHostIPSets was the only scenario were this optmization made sense.

Before settling on this compromise, I tried moving the responsibility of switching away from the lower-level calls, but in the end, I didn’t like it and reverted :p

**Comment by leosarra** [comment]
The changes should now be mostly finalized :)
I'll perform some manual verification next week before removing the draft status.

File: cni/pkg/nodeagent/server.go [hunk 7]
```diff
@@ -87,12 +122,23 @@ func NewServer(ctx context.Context, ready *atomic.Value, pluginSocket string, ar
 		Reconcile:              args.ReconcilePodRulesOnStartup,
 	}
 
+	// Create Fd for host network namespace
```
Comment (bleggett) [inline cni/pkg/nodeagent/server.go:125]: I'd move all this inside `createHostsideProbeIpset` - if we have funcs with `hostside` in the name, they should explicitly internalize the "get to hostside" bits (or we shouldn't have them).

File: cni/pkg/nodeagent/server.go [hunk 8]
```diff
@@ -111,10 +157,14 @@ func NewServer(ctx context.Context, ready *atomic.Value, pluginSocket string, ar
 	}
 
 	// Create hostprobe rules now, in the host netns
-	hostIptables.DeleteHostRules()
-
-	if err := hostIptables.CreateHostRulesForHealthChecks(); err != nil {
-		return nil, fmt.Errorf("error initializing the host rules for health checks: %w", err)
+	if err := runAsNs(hostNetNS, func() error {
+		hostIptables.DeleteHostRules()
+		if err := hostIptables.CreateHostRulesForHealthChecks(); err != nil {
```
Comment (bleggett) [inline cni/pkg/nodeagent/server.go:162]: Ditto - it's called `hostside`, let's take care of the host stuff inside

(also we should hold the host netns FD as briefly as possible, like for closure-duration - not as top-level state)

File: cni/pkg/nodeagent/server.go [hunk 9]
```diff
@@ -130,6 +180,7 @@ func NewServer(ctx context.Context, ready *atomic.Value, pluginSocket string, ar
 			netServer:          netServer,
 			hostIptables:       hostIptables,
 			hostsideProbeIPSet: set,
+			hostNetNS:          hostNetNS,
```
Comment (bleggett) [inline cni/pkg/nodeagent/server.go:183]: If we can always `stat` this from our `proc` mount, then we don't need to carry a live FD around as state.

File: cni/pkg/nodeagent/server.go [hunk 10]
```diff
@@ -226,17 +278,23 @@ func (s *meshDataplane) Stop(skipCleanup bool) {
 	if !skipCleanup {
 		log.Info("CNI ambient server terminating, cleaning up node net rules")
 
-		log.Debug("removing host iptables rules")
-		s.hostIptables.DeleteHostRules()
+		_ = runAsNs(s.hostNetNS, func() error {
+			log.Debug("removing host iptables rules")
+			s.hostIptables.DeleteHostRules()
```
Comment (bleggett) [inline cni/pkg/nodeagent/server.go:283]: ditto - `host` funcs should obscure all `host` namespace jumps (or they aren't much use)

File: cni/pkg/nodeagent/server.go [hunk 11]
```diff
@@ -66,6 +71,36 @@ type Server struct {
 	cniServerStopFunc func()
 }
 
+// runAsNs executes the function in the given network namespace or the current one if netNs is nil.
+func runAsNs(netNs netns.NetNS, f func() error) error {
```
Comment (bleggett) [inline cni/pkg/nodeagent/server.go:75]: really, all we need is a closure that gets the FD from the known `/proc` path and does `netns.Do`, and we just call that closure from inside `hostXXX` funcs.

File: cni/pkg/nodeagent/server.go [hunk 12]
```diff
@@ -66,6 +71,36 @@ type Server struct {
...
+	if err != nil {
+		return false, fmt.Errorf("failed to stat current network namespace: %w", err)
+	}
+	hostStat, err := os.Stat(hostNetNSPath)
+	if err != nil {
+		return false, fmt.Errorf("failed to stat host network namespace: %w", err)
+	}
+
+	// Compare the inode numbers
+	return currentStat.Sys().(*syscall.Stat_t).Ino == hostStat.Sys().(*syscall.Stat_t).Ino, nil
```
[the remark this answers is not in the document]
Comment (leosarra) [reply cni/pkg/nodeagent/server.go:101]: You're right; although it is unlikely for the two namespaces to be on different devices, having a stricter check is better.

Currently, I'm planning to remove the isHostNamespace check entirely. In the worst case, if values.shareHostNetwork is enabled, we might perform a unix.setns to a namespace we're already in. This won't fail, though there will be a small overhead from executing the logic.

File: cni/pkg/nodeagent/server.go (hunk 11 above)
Comment (leosarra) [reply cni/pkg/nodeagent/server.go:75]: This is how it worked in the PR before I started iterating on it.
I will restore the logic with netns.WithNetNSPath(path, f) , it will take care of lifecycle of the fd

File: cni/pkg/nodeagent/server.go (hunk 7 above)
Comment (leosarra) [reply cni/pkg/nodeagent/server.go:125]: I think it makes sense to internalize all the host-related functions within the server, as it is the most logical approach, I mentioned the same in an old comment. I will change that.
However, we also need to consider that this will lead to more context switching than necessary. Although this is likely fine since it primarily affects the initial snapshot, which will end up switching context back and forth from the host for each pod.

Regarding the iptables class, I'm a bit conflicted about internalizing the logic. Given that the in-pod rules functions of iptables assume they are already running in the pod namespace, I assumed that "host" in CreateHostHealthChecks was just an indication of the use case rather than the actual network namespace they are running in. Wouldn't it be confusing to have network switch logic for the host but not for the pod?

File: cni/pkg/nodeagent/server.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (bleggett) [reply cni/pkg/nodeagent/server.go:101]: yeah - the only "jump" that's in the pod add hotpath anyway (versus startup) is the ipset one, that seems fine to me.

File: cni/pkg/nodeagent/server.go (hunk 7 above)
Comment (bleggett) [reply cni/pkg/nodeagent/server.go:125]: > However, we also need to consider that this will lead to more context switching than necessary. Although this is likely fine since it primarily affects the initial snapshot, which will end up switching context back and forth from the host for each pod.

Yep. I am not very worried about the overhead tho, I am more worried about holding a `LockOSThread` over (effectively) a very large closure.

I'd rather lock the current goroutine's thread for the least amount of time required - per operation - by default.

If that becomes a major perf problem we can figure out what to do at that point. Also, if that's where we end up, I'd be more inclined to drop the hostside ipset anyway, and then we basically don't have to worry about it.


> I assumed that "host" in CreateHostRulesForHealthChecks (or the delete func) was just an indication of the use case rather than the actual network namespace they are running in.

Ideally the caller wouldn't (have to) care about that distinction (or "expect" anything), which is mostly an implementation detail of the function (in my head). 


In general, when it comes to netns, I prefer a more defensive approach - locking the goroutine to the current thread and moving netns should be 1. a shortly-held lock 2. transparent to the caller 3. unlocked before control is returned to the caller.

But if you feel very conflicted, I won't insist, author's choice.

Comment (leosarra) [reply cni/pkg/nodeagent/server.go]: Thank you for the clarification. I have implemented the changes. The file descriptor and thread lock are now minimized to each host-related function (including iptables). If we find that multiple context switches significantly impact performance, we can always revise it later.

**Review by bleggett — COMMENTED** [review]
LGTM, few questions.

File: cni/pkg/iptables/main_test.go [hunk 13]
```diff
@@ -0,0 +1,31 @@
...
+	"testing"
+
+	pconstants "istio.io/istio/cni/pkg/constants"
+)
+
+func TestMain(m *testing.M) {
+	// Override host NS path globally for all tests
+	originalHostNetNSPath := pconstants.HostNetNSPath
+	defer func() { pconstants.HostNetNSPath = originalHostNetNSPath }()
+	pconstants.HostNetNSPath = "/proc/self/ns/net"
```
[the remark this answers is not in the document]
Comment (leosarra) [reply cni/pkg/iptables/main_test.go:27]: In order to break the devhost, the user would also need to have the host filesystem with proc mounted in /host/proc/, similarly to what the daemonset is doing.
While mounting /host/ is a common pattern for certain scenarios, I'm not sure how common that is for something like development-related containers.
Anyway, this can be remedied as you suggested, I'll add some comments to explain this choice, as it might seem unusual to those without the full context.

[the remark this answers is not in the document]
Comment (leosarra) [reply cni/pkg/iptables/main_test.go]: I tried two approaches.
First, I tied the value of the "constant" to the Server lifecycle. NodeServer changed the value to the actual host at boot and then reverted it back at Stop(). https://github.com/istio/istio/pull/54845/commits/2b6583b301889d98fb1579ded62b7334933c4845
While it worked, I did not like the idea of nodeserver being responsible of the value.

I then changed it to add an environment variable in the DaemonSet that I can rely on to know when the "constant" needs to change to the actual /host/proc/... value. If the env is set then the `hostNetNsPath` variable is changed at init https://github.com/istio/istio/pull/54845/commits/efcb422c423bb23cd1500fcb935e1096f3ccb073 .
It would be extremely weird if someone is setting the exact same env variable outside of the cni daemonset, this should make it goofproof enough.
I think this approach looks a bit cleaner, and it will also have the positive side-effect of preventing unnecessary netns calls if the legacy `shareHostNetworkNamespace` is set to true.
WDYT?

btw I'm adding a do-not-merge-label while I verify that everything works fine in a live deployment

[the remark this answers is not in the document]
Comment (bleggett) [reply cni/pkg/iptables/main_test.go]: I don't love the idea of creating yet-another-env-var for this - but 

> and it will also have the positive side-effect of preventing unnecessary netns calls if the legacy shareHostNetworkNamespace is set to true.

is a good point, so I'm OK with this approach.

**Review by bleggett — APPROVED** [review]
This LGTM, approving with hold so you can test/John can look.

**Comment by bleggett** [comment]
Given that 1.25 is in freeze ATM we may or may not want to backport this for a 1.25 patch release, and instead and save it for 1.26, but it does improve security posture a bit so either works.

File: manifests/charts/istio-cni/templates/daemonset.yaml [hunk 14]
```diff
@@ -160,6 +160,10 @@ spec:
               value: "true"
             - name: REPAIR_SIDECAR_ANNOTATION
               value: "sidecar.istio.io/status"
+            {{- if and .Values.ambient.enabled .Values.ambient.shareHostNetworkNamespace }}
```
Comment (howardjohn) [inline manifests/charts/istio-cni/templates/daemonset.yaml:163]: This condition is inverted I think, needs a `not`.

Rather concerningly, no e2e tests fail at all from this! I guess we do not have anything testing readiness probes + STRICT mode which should be the only host network usage.

File: releasenotes/notes/54726.yaml [hunk 15]
```diff
@@ -0,0 +1,9 @@
+apiVersion: release-notes/v2
+kind: feature
+area: traffic-management
+issue:
+- 54726
+releaseNotes:
+- |
+  **Fixed** The CNI agent always sharing the network namespace with the host. Dynamic switching to the host network is now performed whenever necessary.
+  The old behavior can temporarily be restored by setting the `ambient.shareHostNetworkNamespace` field in the `istio-cni` chart.
```
Comment (howardjohn) [inline releasenotes/notes/54726.yaml:9]:
```suggestion
  **Improved** The CNI agent to no longer require `hostNetwork`, improving compatibility. Dynamic switching to the host network is now performed whenever necessary.
  The old behavior can temporarily be restored by setting the `ambient.shareHostNetworkNamespace` field in the `istio-cni` chart.
```

**Review by howardjohn — COMMENTED** [review]
Awesome!!! LGTM sans the one comment

**Review by howardjohn — APPROVED** [review]
Actually will approve since there is a DNM, just make sure we fix the issue before merging. Maybe we should open a followup to track testing improvements.

If we backport to 1.25.1 we should make sure its off-by-default I think

File: manifests/charts/istio-cni/templates/daemonset.yaml (hunk 14 above)
Comment (leosarra) [reply manifests/charts/istio-cni/templates/daemonset.yaml]: Yes, definitely a mistake.
I have fixed it now and performed a live deployment to verify that ipsets and iptables rules don't end up in the wrong namespace.
I suspect the reason why the tests did not fail is that, while we have integration tests that deploy with PA in strict mode, the PA is deployed after the application becomes ready and is deleted before the liveness probe fails for long enough to trigger a restart.
I will open an issue to keep track of this

**Comment by leosarra** [comment]
The chart flag issue is fixed, and I have manually verified the behavior in a deployment. Therefore, I'm removing the DNM.
Additionally, I have included the compatibility profile for 1.25 in this commit, as it marks the first "1.26 behavior change."
I will follow up on removing the 1.22 compatibility profile and the related flags for master.

Last but not least, I will open a ticket to improve probe testing.

**Comment by howardjohn** [comment]
thank you!!

**Comment by leosarra** [comment]
@bleggett @howardjohn I see some widespread flakiness in the TestTrafficWithCNIUpgrade of the latest post-submit runs, looks like the cni container is not getting [scheduled](https://storage.googleapis.com/istio-prow/logs/integ-k8s-124_istio_postsubmit/1892979830903803904/artifacts/ambient-cniupgrade-1e1f325a389b/TestTrafficWithCNIUpgrade-0/_test_context/istio-state1696336370/primary-0/istio-cni-node-7q5n6_pod-events.yaml) (???).
Not sure if any of you has any idea on what could be going.

**Comment by bleggett** [comment]
> @bleggett @howardjohn I see some widespread flakiness in the TestTrafficWithCNIUpgrade of the latest post-submit runs, looks like the cni container is not getting [scheduled](https://storage.googleapis.com/istio-prow/logs/integ-k8s-124_istio_postsubmit/1892979830903803904/artifacts/ambient-cniupgrade-1e1f325a389b/TestTrafficWithCNIUpgrade-0/_test_context/istio-state1696336370/primary-0/istio-cni-node-7q5n6_pod-events.yaml) (???). Not sure if any of you has any idea on what could be going.

Yep, I just noticed that. I'll open an issue, not sure yet.

**Comment by bleggett** [comment]
OH wait, no - I _do_ know the problem, now I remember.

This PR is interacting with https://github.com/istio/istio/pull/54180

```
  message: 'Failed to create pod sandbox: rpc error: code = Unknown desc = failed
    to setup network for sandbox "5cdcc5ef0e7bd1b08290e79b1568aeb1658b7b3be8ad59b477a18151a7943bf2":
    plugin type="istio-cni" name="istio-cni" failed (add): Unauthorized'
  metadata:
```

https://storage.googleapis.com/istio-prow/logs/integ-ambient-calico_istio_postsubmit/1893011821703467008/artifacts/ambient-cniupgrade-6d8ad3835546/TestTrafficWithCNIUpgrade/_test_context/istio-state211495795/primary-0/istio-cni-node-glzkv_pod-events.yaml


Before this change, the `istio-cni` plugin we left on the node during upgrade would not block `istio-cni` itself from (re)starting, because `istio-cni` ran as hostnet, and thus was skipped by the plugin - the plugin would (not) contact the (not present) `istio-cni` server and the replacement `istio-cni` pod would spawn just fine.

Now that we aren't running in `hostnet` - that no longer holds true and the replacement `istio-cni` pod is getting stalled by its predecessor's CNI plugin.

**Comment by leosarra** [comment]
Thank you @bleggett for looking into the failures!
To be honest, I’d feel more comfortable if you handled the changes. Since this is blocking tests for multiple people, I don’t want to hold things up while I figure it out :sweat_smile:
