### PR TITLE
Fix data races in galley/pkg/config/source

### LINKED ISSUE #16699: Galley TestAddUpdateDelete Unit Test Failure
Failure: https://prow.k8s.io/view/gcs/istio-prow/logs/istio-unit-tests-master/6413

### PR DESCRIPTION
**Pull request by ozevren**
Fixes #16699

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: galley/pkg/config/source/kube/fs/source.go [hunk 1]
```diff
@@ -86,7 +87,7 @@ func (s *source) Start() {
 					scope.Source.Infof("[%s] Triggering reload in response to: %v", s.name, trigger.Source)
 					s.reload()
 				}
-			case <-s.done:
+			case <- done:
```
Comment (golangcibot) [inline galley/pkg/config/source/kube/fs/source.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
			case <-done:
```
