### PR TITLE
istiod.enableAnalysis

### LINKED ISSUE #21074: enableAnalysis doesn't work with 1.5 galley
To reproduce, using Master, `istioctl manifest generate --set values.galley.enableAnalysis=true | grep -i analysis`.  There will be no `--enableAnalysis` output.

The Istiod deployment does not get the `--enableAnalysis=true` flag.

The Installer _operator/pkg/vfs/assets.gen.go_ is generated from _install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml_ which does include the flag generation, but only for the istio-galley Deployment.  The Istiod Deployment does not have it.

### PR DESCRIPTION
**Pull request by therealmitchconnors**
Fixes #21074

Takes changes from #22270 and makes them available in the operator and install experience, off by default.

Still need to add e2e tests.

### CODE REVIEW

File: tests/integration/pilot/analysis/main_test.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    enabled: true
+  ingressGateways:
+addonComponents:
+  prometheus:
+    enabled: false
+revision: canary
+values:
+  global:
+    istiod:
+      enableAnalysis: true
```
Comment (therealmitchconnors) [inline tests/integration/pilot/analysis/main_test.go]: The addition of these lines to values seems to cause pilot to be installed twice, which causes problems.  Does anyone know why this is happening?

Comment (howardjohn) [reply tests/integration/pilot/analysis/main_test.go]: You are calling `istio.Setup` twice, which installs it twice. Copying from the pilot main test was a bad example because its doing something it shouldn't (changed in https://github.com/istio/istio/pull/22336).

File: tests/integration/pilot/analysis/main_test.go [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+// TestMain defines the entrypoint for pilot tests using a standard Istio installation.
+// If a test requires a custom install it should go into its own package, otherwise it should go
+// here to reuse a single install across tests.
+func TestMain(m *testing.M) {
+	framework.
+		NewSuite("pilot_analysis_test", m).
+		RequireSingleCluster().
+		RequireEnvironment(environment.Kube).
+		SetupOnEnv(environment.Kube, istio.Setup(&i, nil)).
```
Comment (nmittler) [inline tests/integration/pilot/analysis/main_test.go]: I suspect you coped this from the pilot tests .... this will cause Istio to be installed twice. I suspect you don't want that.

File: tests/integration/pilot/analysis/main_test.go (hunk 1 above)
Comment (howardjohn) [inline tests/integration/pilot/analysis/main_test.go]:
```suggestion
		SetupOnEnv(environment.Kube, istio.Setup(&i, func(cfg *istio.Config) {
values:
  global:
    istiod:
      enableAnalysis: true
```

File: tests/integration/pilot/analysis/analysis_test.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+)
+
+func TestAnalysisWritesStatus(t *testing.T) {
+	framework.NewTest(t).Run(func(ctx framework.TestContext) {
+		ns := setupModifiedBookinfo(t, ctx)
+		doTest(t, ctx, ns)
+	})
+}
+
+func setupModifiedBookinfo(t *testing.T, ctx framework.TestContext) namespace.Instance {
```
Comment (nmittler) [inline tests/integration/pilot/analysis/analysis_test.go]: @gargnupur mind reviewing for general usage of bookinfo and its gateway.

Comment (therealmitchconnors) [reply tests/integration/pilot/analysis/analysis_test.go]: just to be clear, this is still WIP, even after the multiple pilot issue is resolved, I need to mutate bookinfo somehow to trigger an Analyzer message. My plan was to misspell the gateway name, but now that I look at it, these virtualservices don't directly reference gateways...

Comment (howardjohn) [reply tests/integration/pilot/analysis/analysis_test.go]: Why do you even need to deploy bookinfo? Can't you just directly run

```
applyconfig(`some-broken-config`)
```

and then check the status? We do not need to deploy any pods?

Comment (therealmitchconnors) [reply tests/integration/pilot/analysis/analysis_test.go]: That is true.  I figured it would be easier to use an existing reference application than to spend time authoring and maintaining custom config just for this test.

File: tests/integration/pilot/analysis/main_test.go (hunk 1 above)
Comment (therealmitchconnors) [reply tests/integration/pilot/analysis/main_test.go]: Thank you for clarifying!

File: tests/integration/pilot/analysis/analysis_test.go (hunk 3 above)
Comment (howardjohn) [reply tests/integration/pilot/analysis/analysis_test.go]: I would agree in general but you are already not doing something standard (invalid config), applying a config is a simple one line, and deploying bookinfo has a runtime cost which doesn't seem to benefit at all here

Comment (therealmitchconnors) [reply tests/integration/pilot/analysis/analysis_test.go]: ok, I'll modify my test.

File: tests/integration/pilot/analysis/analysis_test.go [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+        host: reviews
+        subset: v1
+`
+	_, err := deployment.New(ctx, deployment.Config{
+		Name:      "bogus-virtualservice",
+		Namespace: ns,
+		Yaml:      badVS,
+	})
+	if err != nil {
+		t.Fatalf("TODO: make a better failure message: %v", err)
```
Comment (howardjohn) [inline tests/integration/pilot/analysis/analysis_test.go]: may want to update?

File: tests/integration/pilot/analysis/analysis_test.go [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+		Group:    "networking.istio.io",
+		Version:  "v1alpha3",
+		Resource: "virtualservices",
+	}, ns.Name(), "reviews")
+	if err != nil {
+		t.Fatalf("TODO: another error message here: %v", err)
+	}
+
+	if x.Object["status"] == nil {
+		return fmt.Errorf("object is missing expected status field.  Actual object is: %v", x)
```
Comment (howardjohn) [inline tests/integration/pilot/analysis/analysis_test.go]: Should we actually look at the status? aside from just checking for nil?

**Review by howardjohn — APPROVED** [review]

File: tests/integration/pilot/analysis/analysis_test.go (hunk 5 above)
Comment (therealmitchconnors) [reply tests/integration/pilot/analysis/analysis_test.go]: Eventually, yes, but the format of this field needs to change substantially before release, so it didn't make much sense to tie this test to the specific schema, when that should be changing next week.
