### PR TITLE
fix mesh network flakes

### LINKED ISSUE #26048: TestMeshNetworking test flake
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26016/unit-tests_istio/17932

### PR DESCRIPTION
**Pull request by stevenctl**
Fixes #26048

go test with -race -count=50 passes. 

* The global push context needs to be reinitialized after the force-sync. 
  * it passes sometimes because ConfigUpdate calls Push which re-init PushContext but debounce may delay that. If theres a way to check that debounce has settled we could do that instead of `InitContext`. 
* Cleaned up the ForceResync to check all resources. This was not necessary to fix the flake but may prevent future ones. 
* Fix race in aggregate controller for merging services across multiple registries

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: pilot/pkg/xds/fake.go [hunk 1]
```diff
@@ -249,12 +243,21 @@ func NewFakeDiscoveryServer(t test.Failer, opts FakeOptions) *FakeDiscoveryServe
...
+	s.updateMutex.Lock()
+	defer s.updateMutex.Unlock()
+	ctx := model.NewPushContext()
+	if err := ctx.InitContext(env, env.PushContext, nil); err != nil {
+		t.Fatal(err)
+	}
+	if err := s.UpdateServiceShards(ctx); err != nil {
 		t.Fatal(err)
 	}
+	env.PushContext = ctx
```
Comment (hzxuzhonghu) [inline pilot/pkg/xds/fake.go:259]: Do we really need this?

Comment (stevenctl) [reply pilot/pkg/xds/fake.go:259]: Yes. Without this we get the flakes. If I just call InitContext on the existing one, there are races.
