### PR TITLE
optimize: proxy updated config filtering

### LINKED ISSUE #55471: Unnecessary proxy pushes
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

There seems to be subtle cases in how Istio handles `PushRequest.ConfigsUpdated` to infer if it has to push certain configs.
The current process seems to be:
- for each proxy, chech if the proxy depends on any of the given `ConfigsUpdated`, this is only valid for `VirtualService`, `DestinationRule` and `ServiceEntry` since they're the only configs tracked by `SidecarScope`. It's also sort of valid for some configs that don't affect different types of proxies and in the case of `SidecarProxy` it's extended to only consider `EnvoyFilter`, `AuthorizationPolicy`, `RequestAuthentication`, `WasmPlugin` which are either in the `rootNamespace` or in the `proxyNamespace`. If we find any `ConfigsUpdated` that are depended upon or that are not filter by the above conditions, then the we consider the proxy needs a push and we proceed.
  Reference: https://github.com/istio/istio/blob/master/pilot/pkg/xds/proxy_dependencies.go#L93-L112
  
- for each `TypeURL` we call Generate and each generator is responsible for checking if it **really needs** to generate and push configs, for this, each generator implements different filtering logic, but basically they perform some basic checks and then skip certain types of Configs, if any there remain any `ConfigsUpdated` that don't match the skipped, then the generator considers the proxy **really needs** a push.
  Reference for CDS: https://github.com/istio/istio/blob/master/pilot/pkg/xds/cds.go#L66-L102

It might not be too straight forward to see the issue here, but imagine this case:
- Proxy P depends on config `{kind: VirtualService, namespace: ns1, name: vs1}`
- PushRequest contains `ConfigsUpdated: [{kind: VirtualService, namespace: ns2, name: vs2}, {kind: Secret, namespace: ns, name: secret1}]`
- Proxy is deemed it needs a push because `kind: Secret` is not tracked by `SidecarScope` even though this proxy does not depend on `vs2`
- Generators are called with **the same** `ConfigsUpdated`, so CDS generator skips `Secret` because it doesn't affect Clusters, but it finds a `ConfigsUpdated` that is a `VirtualService` (which is considered affects Clusters), so the generator considers the proxy needs a push, **even though the only remaining config is not really depended on by the proxy**. This can happen with every generator.

The above case can happen a lot in a large deployment where a lot of changes happen all the time, and probably most changes should probably not be pushed to all proxies.

I would expect each Proxy to have it's own copy of ConfigsUpdated that they can filter before passing into Generators, this way Generators can receive a list of Configs which are known to affect the proxy and then only filter those to know if it affects the generated resources or not. But this is kind of tricky also, because we currently use a single `*PushRequest` for all proxies and also `len(ConfigsUpdated) == 0` is considered for push always.

### Version

```Text
istio 1.24
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sschepens**
**Please provide a description of this PR:**
This PR builds upon #55479 and makes `ProxyNeedsPush` filter configs relevant to the current proxy, this means that it returns a new `PushRequest` with a new set of `ConfigsUpdated` containing only the configs relevant to the proxy.
This enables skipping unnecessary config pushing at the Generators, they will now only generate and push configs if any supported configuration by the Generator has been updated and is considered relevant for the proxy.

I also modified `cds` code to filter configs based on relevant configs for CDS generation, because [Cluster Generator checks updated config types](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/cluster.go#L288-L296) and disables Delta if some config type is not `ServiceEntry` or `DestinationRule`, and if we do not filter other types, then we may end up disabling delta without need.

Fixes #55471

### CODE REVIEW

**Comment by sschepens** [comment]
@howardjohn this are the other changes I had planned, which depend on #55479, without those changes, this would be very difficult to achieve, since empty `ConfigsUpdated` has another meaning.

File: pilot/pkg/xds/proxy_dependencies.go [hunk 1]
```diff
@@ -89,24 +108,19 @@ func proxyDependentOnConfig(proxy *model.Proxy, config model.ConfigKey, push *mo
...
-			}
-		}
+	if proxy.IsWaypointProxy() || proxy.IsZTunnel() {
+		// Optimizations do not apply since scoping uses different mechanism
+		// TODO: implement ambient aware scoping
+		return req, true
 	}
 
-	return false
+	req = filterRelevantUpdates(proxy, req)
```
Comment (howardjohn) [inline pilot/pkg/xds/proxy_dependencies.go:124]: Hmm. I do wonder if we may be better served moving this filtering up to this level: https://github.com/istio/istio/blob/91bcb0eb045d30c843817d0c2aba80a12a6531f2/pilot/pkg/xds/ads.go#L591. Doesn't need to block the PR.

Maybe its a bit harder due to the ServiceTargets aspect

File: pilot/pkg/xds/proxy_dependencies.go [hunk 2]
```diff
@@ -30,26 +30,45 @@ var UnAffectedConfigKinds = map[model.NodeType]sets.Set[kind.Kind]{
...
-			return true
+			relevantUpdates.Insert(config)
+		} else {
+			// we have filtered out a config
+			changed = true
 		}
 	}
 
-	return false
+	// If the proxy's service updated, need push for it.
```
Comment (howardjohn) [inline pilot/pkg/xds/proxy_dependencies.go:51]: This is different than the old logic.

Before: if a proxies' ServiceTarget is in ConfigUpdate, we always push
Now: always consider all servicetargets as changed.

TBH on the before, I am not entirely sure why its needed. I guess even if something isn't in its sidecarScope it may be a serviceTarget so we need to incude it? its basically a bug fix for `proxyDependentOnConfig` which probably should have lived in `proxyDependentOnConfig`.

But with the new logic, IIUC, say I have a pod with `service a` selecting it. Now service b changes. I will push service a.

Comment (howardjohn) [reply pilot/pkg/xds/proxy_dependencies.go:51]: Upon further reading: I am wrong, that is not what this is doing and the behavior looks right. It does still seem like maybe proxyDependentOnConfig should have this check, though, but NBD

File: pilot/pkg/xds/proxy_dependencies.go [hunk 3]
```diff
@@ -30,26 +30,45 @@ var UnAffectedConfigKinds = map[model.NodeType]sets.Set[kind.Kind]{
 	model.SidecarProxy: sets.New(kind.Gateway, kind.KubernetesGateway),
 }
 
-// ConfigAffectsProxy checks if a pushEv will affect a specified proxy. That means whether the push will be performed
-// towards the proxy.
-func ConfigAffectsProxy(req *model.PushRequest, proxy *model.Proxy) bool {
-	// Empty changes means "all" to get a backward compatibility.
+// filterRelevantUpdates filters PushRequest.ConfigsUpdated so that only configs relevant to the proxy are included,
+// and returns a new PushRequest with the filtered configs.
+func filterRelevantUpdates(proxy *model.Proxy, req *model.PushRequest) *model.PushRequest {
```
Comment (howardjohn) [inline pilot/pkg/xds/proxy_dependencies.go:35]: nit: I would mention the returned PushRequest is not necessarily a copy so should not be mutated

**Review by howardjohn — COMMENTED** [review]
Overall looks like a good improvement :+1: 

Do you have any real world performance numbers from before/after?

cc @stevenctl @ramaraochavali

**Comment by sschepens** [comment]
> Do you have any real world performance numbers from before/after?

planning on spinning up a test environment for this tomorrow or friday, but on our productive environment we have 25k connected sidecars from ~7k different services, and all Proxies are being updated on every single debounce cycle, I've seen a proxy get 5 updates in a minute that contained no effective change for the Proxy. So we run a pretty big cluster and there are lots of changes all the time, sometimes like ~100 config updates on a single debounce, but configurations are very scoped and almost never affect all proxies, so I figured there was something wrong with how Istio was handling the scoping.
It's hard to tell exactly how much this will impact without fully deploying this in our productive environment, I'm hoping it will probably reduce XDS Pushes by a factor of 10, or maybe more. In the case of the Proxy that was receiving 5 updates per minute, it should probably get down to just a couple an hour, so it would be like a 100x improvement.

File: pilot/pkg/xds/proxy_dependencies.go (hunk 1 above)
Comment (sschepens) [reply pilot/pkg/xds/proxy_dependencies.go:124]: You mean performing the filtering before enqueuing?

It could be useful to avoid enqueuing altogether, but on the other side, the filtering would be done in a single threaded fashion, while currently it's being done concurrently (limited by push concurrency)

File: pilot/pkg/xds/proxy_dependencies.go (hunk 3 above)
Comment (sschepens) [reply pilot/pkg/xds/proxy_dependencies.go:36]: done

**Comment by ramaraochavali** [comment]
I think filterRelevantUpdates looks like a good change. 

>  planning on spinning up a test environment for this tomorrow or friday, but on our productive environment we have 25k connected sidecars from ~7k different services

Curious is this multi cluster or all of these services and sidecars on single cluster?

> , and all Proxies are being updated on every single debounce cycle, I've seen a proxy get 5 updates in a minute that contained no effective change for the Proxy.

Wonder do we know based on logs what is triggering those pushes?

We probably should know how many of these pushes are empty config pushes (forced pushes in this PR) - Should we add a metric for it?

> t's hard to tell exactly how much this will impact without fully deploying this in our productive environment, I'm hoping it will probably reduce XDS Pushes by a factor of 10, or maybe more. In the case of the Proxy that was receiving 5 updates per minute, it should probably get down to just a couple an hour, so it would be like a 100x improvement.

It would be good to get this data also how much does istiod cpu/memory improvements we see with this skipped pushes?

**Comment by sschepens** [comment]
> Curious is this multi cluster or all of these services and sidecars on single cluster?

Multi Cluster, we do External Controlplane.

> Wonder do we know based on logs what is triggering those pushes
>
> We probably should know how many of these pushes are empty config pushes (forced pushes in this PR) - Should we add a metric for it?

From what I can gather in logs, we almost never have *forced pushes* (empty configs), our lgos always show a whole bunch of config changes, but what I can see is that Istiod is not correctly filtering configs, more info is in https://github.com/istio/istio/issues/55471 . When doing MultiCluster, istio watches for `Secrets` (I think this is done to perform pod authentication, but we're watching and receiving updates from all secrets) and aparently we're having those updated frecuently and `Secret` updates mixed with other changes (`VS`, `DestinationRule`, `ServiceEntry`) are causing Istio do consider it needs to push to all Proxies. It's further explained in the issue, but basically `ProxyNeedsPush` does not know about `Secrets` so whenever a secret is present it would consider a Push is Needed, then Generators would receive a whole bunch of ConfigUpdates that are probably not even scoped to the Proxy. It also hinders Delta usage because Delta CDS generator always receives a bunch of mixed configs.

> It would be good to get this data also how much does istiod cpu/memory improvements we see with this skipped pushes?

Currently our CPU usage is dominated by Config Generation: 26% RDS Generator, 19% LDS Generator, 7% CDS Generator (unable to use Delta), so in total ~50% CPU usage is config generation. There's also a lot of GC time that is probably related to this excessive configuration generation. So I'm guessing in our case we can reduce this CPU usage drastically.

**Comment by ramaraochavali** [comment]
it would be good to see how much it improves with this?

**Comment by sschepens** [comment]
So I've tested this in a separate revision in our productive cluster, this seems to be working great, a Pod connected to this new revision almost never receives a update, It's been about 20 minutes since it's last received an update, while a Pod connected to the new revision continues to receive about 5 updates per minute. Not only this, but the latter also never receives Delta updates (because of the issue described) while the former does whenever it receives a update (unless it's reconnecting to another ControlPlane instance)

We're planning on rolling this out to our productive environment next week, will bring an update once we do and have information on the impact of this change.

**Comment by sschepens** [comment]
So, last night we deployed this change to our production cluster and here I post some screenshots with the results. One general comment, in graphs that show time-based metrics, we graph Max (Yellow), p95(Purple) and Avg (Blue).
We can see that immediately upon deployment CPU goes down from ~50% to 15%, Memory Usage is also slightly lower.
Screenshot 2025-03-18 at 10 14 29
Screenshot 2025-03-18 at 10 14 35

What's more interesting though is that our Convergence Time, Queue Time, Push Time are significantly reduced, this is because before we were pushing all proxies on every single debounce period and there was significant queueing and contention. The difference is so big that it's hard to see, but previously the **avg convergence time** was **~2s**, now it's **~100ms**, **p95** was **~4.7s**, no it's **~300ms**.
Screenshot 2025-03-18 at 10 14 58

Debounce Time is mostly unchanged, seems more stable, probably because there's less queuing while pushing and we can finish a debounce faster. WorkQueue Latency is very impacted as well because of the general contention reduction and because I included  #55476
Screenshot 2025-03-18 at 10 15 11

Here you can see that Itsiod is receiving the same **Inbound Updates** and **Push Triggers** but it's generating **an order of magnitude less XDS Pushes** than before, it's correctly filtering those updates only to the affected proxies.
Screenshot 2025-03-18 at 10 15 21

Here you can also see that we have the same Proxies connected to the controlplane as before.
Screenshot 2025-03-18 at 10 15 32

**Comment by howardjohn** [comment]
Awesome. Amazing work and thanks for the detailed before/after analysis. Will review today and hopefully we can get this merged. I've looked through it a few times already, just want to inspect very closely to make sure there aren't any edge cases we may be introducing where we accidentally skip an event, etc.

**Comment by ramaraochavali** [comment]
+1 to what @howardjohn . Great improvement

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
awesome job

File: pilot/pkg/serviceregistry/serviceentry/controller.go [hunk 4]
```diff
@@ -345,11 +345,15 @@ func (s *Controller) workloadEntryHandler(old, curr config.Config, event model.E
 	// update eds cache only
 	s.edsUpdate(allInstances, false)
 
+	// TODO: if len(configsUpdated) == 0 we're firing a Forced push for compatibility because no configs have been updated,
+	// we should actually skip the push.
 	pushReq := &model.PushRequest{
 		Full:           true,
 		ConfigsUpdated: configsUpdated,
 		Reason:         model.NewReasonStats(model.EndpointUpdate),
+		Forced:         len(configsUpdated) == 0,
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/serviceentry/controller.go:354]: Not sure why cannot skip push if = 0

Comment (sschepens) [reply pilot/pkg/serviceregistry/serviceentry/controller.go:354]: Previously it wasn't skipped, I didn't want to introduce unnecessary changes to this PR and also I think it's not really safe to currently skip pushing

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/serviceentry/controller.go:354]: Yeah, i guess you must met something wrong, just wanna to know what is it

File: pilot/pkg/model/push_context.go [hunk 5]
```diff
@@ -390,6 +390,9 @@ type PushRequest struct {
 	// Delta defines the resources that were added or removed as part of this push request.
 	// This is set only on requests from the client which change the set of resources they (un)subscribe from.
 	Delta ResourceDelta
+
+	// Forced defines that configs should be generated and pushed regardless if they have changed or not.
+	Forced bool
```
Comment (wulianglongrd) [inline pilot/pkg/model/push_context.go:395]: Awesome! Can we name it `sidecarScoped`? That way, we don't have to write `Forced: true` everywhere.
