### PR TITLE
Fix Custom CA Integration using K8s CSR

### LINKED ISSUE #42977: Custom CA Integration with K8s CSR fails with cert-manager self-signed CA
### Bug Description
**Bug report**: [bug-report.tar.gz](https://github.com/istio/istio/files/10494770/bug-report.tar.gz)

When working through the [Custum CA Integration with k8s CSR demo](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/), istiod failed to provide a certificate to istio-ingressgateway resulting in istiod and istio-ingressgateway failures. This issue occurred after [deploying istio with the default cert signer information](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/#deploy-istio-with-default-cert-signer-info) as specified in the demo. 

**Demo environment**:
- AKS cluster

**Errors in Istiod**:
```bash
2023-01-24T20:41:14.904656Z     error   serverca        CSR signing error (failed to find root cert from signed cert-chain (found root cert is not a ca type cert: &{[...]} spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account))
```
**Errors in istio-ingressgateway**:
```bash
2023-01-24T22:44:47.922416Z     info    ads     ADS: new connection for node:istio-ingressgateway-7c946df4ff-4pjkt.istio-system-902
2023-01-24T22:44:47.956442Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.0.215.14:15012: connect: connection refused"
2023-01-24T22:44:48.196471Z     warn    ca      ca request failed, starting attempt 1 in 107.722649ms
2023-01-24T22:44:48.305036Z     warn    ca      ca request failed, starting attempt 2 in 210.596616ms
2023-01-24T22:44:48.516831Z     warn    ca      ca request failed, starting attempt 3 in 379.315277ms
2023-01-24T22:44:48.897101Z     warn    ca      ca request failed, starting attempt 4 in 755.246519ms
```

**Verifications**:
I verified the specifications for the demo were successfully applied. istiod recieved the correct environment variables:
```yaml
 env:
    - name: CERT_SIGNER_DOMAIN
      value: clusterissuers.cert-manager.io
    - name: EXTERNAL_CA
      value: ISTIOD_RA_KUBERNETES_API
    - name: REVISION
      value: default
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: k8s.io/clusterissuers.cert-manager.io/istio-system
```
istiod successfully picked up on the environement variables and correctly used the istio-system cert-manager issuer to issue its own certificate:
```bash
2023-01-24T22:51:11.045175Z     info    Generating K8S-signed cert for [istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc] using signer clusterissuers.cert-manager.io/istio-system
2023-01-24T22:51:11.337886Z     info    x509 cert - Issuer: "CN=istio-system", Subject: "O=", SN: 368c7ba0d9aaa81e09060977f266bd09, NotBefore: "2023-01-24T22:51:11Z", NotAfter: "2033-01-21T22:51:11Z"
```
Cert-manager was also install using the correct feature gate:
```bash
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --set featureGates=ExperimentalCertificateSigningRequestControllers=true
```
```yaml
Containers:
  cert-manager-controller:
    Container ID:  containerd://48338bbf7cf9d056d0cfc373da42665c66b985b8d5e9d1ae8e34401d34d23a06
    Image:         quay.io/jetstack/cert-manager-controller:v1.11.0
    Image ID:      quay.io/jetstack/cert-manager-controller@sha256:d429b6d696e0ef47cff1d15241c6ffaac351e38ac22664b82fafa771d615b89a
    Port:          9402/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --cluster-resource-namespace=$(POD_NAMESPACE)
      --leader-election-namespace=kube-system
      --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.11.0
      --feature-gates=ExperimentalCertificateSigningRequestControllers=true
      --max-concurrent-challenges=60
```

**Findings**:
The error log in istiod (`failed to find root cert from signed cert-chain`) was generated by `[SignWithCertChain()](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L115)` in `k8s_ra.go`. The method is described as follows:
```go
// SignWithCertChain is similar to Sign but returns the leaf cert and the entire cert chain.
// root cert comes from two sources, order matters:
// 1. Specified in mesh config
// 2. Extract from the cert-chain signed by the CSR signer.
```
However, the ordering of the checks to find the cert chain in the code did not match the description:
```go
rootCertFromCertChain, err = util.FindRootCertFromCertificateChainBytes(cert)
if err != nil {
	return nil, raerror.NewError(raerror.CSRError, fmt.Errorf("failed to find root cert from signed cert-chain (%v)", err.Error()))
}
rootCertFromMeshConfig, err = r.GetRootCertFromMeshConfig(certSigner)
if err != nil {
	pkiRaLog.Infof("failed to find root cert from mesh config (%v)", err.Error())
}
```
To obtain the root cert, the cert chain is checked first before checking the MeshConfig. Additionally, if the root is not found in the cert chain, an error is returned rather than also checking if the root is in the MeshConfig.

**Current Hypothesis**:
When calling [`Sign` on the `csrPem`](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L116) cert-manager creates a certificate using the `istio-system` Issuer (created in the demo) created from a self-signed Issuer. Istio expects that the returned cert contains the certificate chain. In this case, the certificate does not contain the certificate chain and therefore does not contain the root certificate. The subsequent call to `FindRootCertFromCertificateChainBytes(cert)` will return an error and [`SignWithCertChain` will return `failed to find root cert from signed cert-chain`](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L130).

**Proposal**:
- Update the ordering of `FindRootCertFromCertificateChainBytes` and `GetRootCertificateFromMeshConfig`
- Do not return an error in `SignWithCertChain` when `FindRootCertificateFromCertificateChainBytes` returns an error
- Write unit or e2e tests to verify this functionality

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0

$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.6
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jaellio**
**Please provide a description of this PR:**

Updates SignWithCertChain to check MeshConfig for the root ca
before the cert chain. Also, updated the error handling when
FindRootCertFromCertificateChainBytes. SignWithCertChain should
not return an error when FindRootCertFromCertificateChainBytes
fails.

Adds unit tests for SignWithCertChain where the root is not in the
MeshConfig.

Resolves #42977 

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: security/pkg/pki/ra/k8s_ra.go [hunk 1]
```diff
@@ -125,14 +125,14 @@ func (r *KubernetesRA) SignWithCertChain(csrPEM []byte, certOpts ca.CertOpts) ([
 	var possibleRootCert, rootCertFromMeshConfig, rootCertFromCertChain []byte
 	certSigner := r.certSignerDomain + "/" + certOpts.CertSigner
 	if len(r.GetCAKeyCertBundle().GetRootCertPem()) == 0 {
-		rootCertFromCertChain, err = util.FindRootCertFromCertificateChainBytes(cert)
-		if err != nil {
```
Comment (irisdingbj) [inline security/pkg/pki/ra/k8s_ra.go:129]: we should  just log the info that no root cert found in cert chain instead of return error out.

Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra.go:129]: Should we check the MeshConfig for the root cert before checking the cert chain? If not, I'll update the comment for the method.

File: security/pkg/pki/ra/k8s_ra_test.go [hunk 2]
```diff
@@ -92,14 +92,19 @@ func TestK8sSignWithMeshConfig(t *testing.T) {
 			updatedRootCertForMeshConfig: TestCACertFile,
 			expectedFail:                 true,
 		},
+		{
+			name:      "Root cert is not specified in mesh config and cert chain contains only intermediate CA(only leaf cert + intermediate CA)",
```
Comment (jaellio) [inline security/pkg/pki/ra/k8s_ra_test.go:96]: Should these tests be added in a separate test function called `TestK8sSignWithCertChain`?

File: security/pkg/pki/ra/k8s_ra.go (hunk 1 above)
Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra.go:129]: we already set final root cert as the one from meshconfig if both exists,   see below line 136.

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 2 above)
Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra_test.go:96]: We can just add a TC in this function to test that  the cert in certchain is not a CA cert

File: security/pkg/pki/ra/k8s_ra.go (hunk 1 above)
Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra.go:129]: Got it! Reverted change to the original ordering of checking the cert chain and then the MeshConfig.

File: security/pkg/pki/ra/k8s_ra_test.go [hunk 3]
```diff
@@ -92,14 +92,19 @@ func TestK8sSignWithMeshConfig(t *testing.T) {
...
+			certChain: path.Join(env.IstioSrc, "samples/certs", "workload-foo-cert.pem"),
+		},
+		{
+			name:         "Root cert is not specified in mesh config and Root cert from cert chain is empty(only one leaf cert)",
+			certChain:    path.Join(env.IstioSrc, "samples/certs", "cert-chain.pem"),
```
Comment (irisdingbj) [inline security/pkg/pki/ra/k8s_ra_test.go:101]: This cert-chain is also a CA type cert which can not test the failure scenario fixed in this PR,  it is better to get a cert-chain which contains only a non-ca type cert.

Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:101]: I decoded and inspected cert-chain.pem and I believe it only contains a leaf certificate.

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 2 above)
Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:96]: Does the root certificate have to be included in either the MeshConfig or the cert chain or is it sufficient to have only the intermediate certificate in the cert chain (and in this case be considered a root cert)? If the intermediate cert cannot be considered a root, should this method return an error if a root certificate isn't found in either location? From  the method description:
```go
If no root cert can be found from either of the two sources, error returned.
```
I think this test scenario should be included since none of the previous cases tested the case where the root cert is not specified in the MeshConfig, but an intermediate cert is included in the cert chain. Is it possible for this configuration to occur?

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 3 above)
Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra_test.go:101]: hmm...  are you inspecting the one from `[samples/certs/cert-chain.pem](https://raw.githubusercontent.com/istio/istio/master/samples/certs/cert-chain.pem)`  ?   tried `openssl x509 -in samples/certs/cert-chain.pem -noout -text` and it gives 

'X509v3 Basic Constraints:
    CA:TRUE'

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 2 above)
Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra_test.go:96]: The current test cases are focuing on getting root cert from mesh config, as root cert from cert chain is the default behaviour.  Yep, it will be helpful if you can add more cases to root cert from cert chain only.

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 3 above)
Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:101]: Ah, you're right, I was looking at the wrong `cert-chain.pem` file. The above test case https://github.com/istio/istio/pull/42980/files#diff-9eb462ac51166aef4fdb4ca1198d23865c737c5a1a2bd8a7b4f8da9f6e1bab27R79-R81 uses the `cert-chain.pem` as an empty cert chain or leaf certificate, but it is a CA. Is that correct?

File: security/pkg/pki/ra/k8s_ra_test.go [hunk 4]
```diff
@@ -132,14 +133,13 @@ func TestK8sSignWithMeshConfig(t *testing.T) {
 				TTL:        60 * time.Second, ForCA: false,
 				CertSigner: "kube-apiserver-client",
 			}
-			// expect to sign back successfully
 			_, err = ra.SignWithCertChain(csrPEM, certOptions)
-			if err != nil && !tc.expectedFail {
-				t.Fatal(err)
+			if (tc.expectedFail && err == nil) || (!tc.expectedFail && err != nil) {
```
Comment (jaellio) [inline security/pkg/pki/ra/k8s_ra_test.go:137]: Updated this conditional to check if an expected error didn't occur.

File: security/pkg/pki/ra/k8s_ra_test.go [hunk 5]
```diff
@@ -78,27 +79,27 @@ func TestK8sSignWithMeshConfig(t *testing.T) {
 		{
 			name:                  "Root cert is specified in mesh config and Root cert from cert chain is empty(only one leaf cert)",
 			rootCertForMeshConfig: path.Join(env.IstioSrc, "samples/certs", "root-cert.pem"),
-			certChain:             path.Join(env.IstioSrc, "samples/certs", "cert-chain.pem"),
+			certChain:             path.Join(env.IstioSrc, "samples/certs", "leaf-workload-foo-cert.pem"),
```
Comment (jaellio) [inline security/pkg/pki/ra/k8s_ra_test.go:82]: With the update to only include the leaf certificate in the in certChain rather than use `cert-chain.pem` which is a CA, this test is now failing with the following error:

```bash
root cert from signed cert-chain is invalid failed to verify certificate: x509: certificate signed by unknown authority
```

Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra_test.go:82]: put root cert + intermediate ca cert into one pem and used it for root certs to verify the leaf cert, similar like below: 
`cp "$certchain"  "$FINAL_DIR/workload-$sa-root-certs.pem"
cat "$rootcert" >> "$FINAL_DIR/workload-$sa-root-certs.pem"
`
name:                  "Root cert is specified in mesh config and Root cert from cert chain is empty(only one leaf cert)",
			rootCertForMeshConfig: path.Join(env.IstioSrc, "samples/certs", "worklaod-foo-root-certs.pem"),
			certChain:             path.Join(env.IstioSrc, "samples/certs", "leaf-workload-foo-cert.pem")
`

Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:82]: Is this a valid scenario? What external ca configuration would this be used for?

Comment (irisdingbj) [reply security/pkg/pki/ra/k8s_ra_test.go:82]: Basically what we need to test here is to make sure the root cert comming from mesh config and the leaf workload only cert comes from signed cert chain.   The original failure reason for your TC is you have not make the intermediat CA in the root certs.  So to make this work,  make the root cert + intermediate ca cert as root certs in meshconfig.

Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:82]: I believe that scenario is covered by the subsequent test `Root cert is specified in mesh config and cert chain contains only intermediate CA(only leaf cert + intermediate CA) `.

File: security/pkg/pki/ra/k8s_ra_test.go [hunk 6]
```diff
@@ -111,24 +117,29 @@ func TestK8sSignWithMeshConfig(t *testing.T) {
 			}
 			signer := "kubernates.io/kube-apiserver-client"
 			ra.certSignerDomain = "kubernates.io"
```
[the remark this answers is not in the document]
Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go]: Updated `kubernates` to `kubernetes`.

File: security/pkg/pki/ra/k8s_ra_test.go (hunk 5 above)
Comment (jaellio) [reply security/pkg/pki/ra/k8s_ra_test.go:82]: Okay, I added a test with the root and intermediate CA specified in the MeshConfig and leaf in the cert chain. I also kept the test with just the root in the MeshConfig and the leaf in the cert chain.

**Review by irisdingbj — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]

File: samples/certs/README.md [hunk 7]
```diff
@@ -14,6 +14,10 @@ The included sample files are:
 - `cert-chain-alt.pem`: alternative certificate chain.
 - `workload-foo-[cert|key].pem`: workload certificate and key for URI SAN `spiffe://trust-domain-foo/ns/foo/sa/foo` signed by `ca-cert.key`.
 - `workload-bar-[cert|key].pem`: workload certificate and key for URI SAN `spiffe://trust-domain-bar/ns/bar/sa/bar` signed by `ca-cert.key`.
+- `workload-foo-root-certs.pem`: root and intermediate CA certificates for foo workload certificate.
+- `workload-bar-root-certs.pem`: root and intermediate CA certificates for bar workload certificate.
+- `leaf-workload-foo-cert.pem`: leaf workload certificate
+- `leaf-workload-bar-cert.pem`: leaf workload certificate
```
Comment (ericvn) [inline samples/certs/README.md:20]: Can we add a period to the end of the sentences. Also we mention foo and bar in the above sentences but not these.

Comment (jaellio) [reply samples/certs/README.md]: Updated!

**Review by ericvn — APPROVED** [review]
LGTM 

Thanks.
