### PR TITLE
Fix validation cert rotation

### LINKED ISSUE #20147: TestWebhook/key/cert_reload test flaky
Example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20146/integ-galley-k8s-tests_istio/6014

Its failed many times today

@ayj may be from your changes?

### PR DESCRIPTION
**Pull request by howardjohn**
When kubernetes updates a secretMount, it is not always (ever? not
exactly sure why this ever works) a "modify" event. Generally its a
move, since its a symlink we are looking at. This changes the file
watching to be more liberal, which seems aligned with the rest of our
file watchers.

Fixes https://github.com/istio/istio/issues/20147

### CODE REVIEW

File: pkg/webhooks/validation/server/server.go [hunk 1]
```diff
@@ -273,14 +263,10 @@ func (wh *Webhook) Run(stopCh <-chan struct{}) {
...
 			wh.reloadKeyCert()
-		case event, more := <-wh.keyCertWatcher.Events(wh.keyFile):
-			if more && isModify(event) && keyCertTimerC == nil {
-				keyCertTimerC = time.After(watchDebounceDelay)
-			}
-		case event, more := <-wh.keyCertWatcher.Events(wh.certFile):
-			if more && isModify(event) && keyCertTimerC == nil {
-				keyCertTimerC = time.After(watchDebounceDelay)
-			}
+		case <-wh.keyCertWatcher.Events(wh.keyFile):
```
Comment (ayj) [inline pkg/webhooks/validation/server/server.go]: The `keyCertTimerC == nil` check needs to be retained to preserve the debounce behavior.

**Review by ayj — COMMENTED** [review]
The generalized check looks ogod. I had (incorrectly) assumed that the istio.io/pkg/filewatcher was handling this since it was watching the parent directory of the file.

File: pkg/webhooks/validation/server/server.go (hunk 1 above)
Comment (howardjohn) [reply pkg/webhooks/validation/server/server.go]: Thanks, fixed

**Review by ayj — APPROVED** [review]
Thanks for fixing this.
