### PR TITLE
Fix ambient mc test flake

### LINKED ISSUE #58780: test flake: integ-ambient-mc TestServices has many failures
Tests including:

```
TestServices/from_primary_workload-addressed-waypoint
TestServices/from_primary_service-addressed-waypoint
TestServices/from_primary_sidecar
TestServices/from_primary_captured
```

Instances:

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/58766/integ-ambient-mc_istio/2011176893105049600

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/58770/integ-ambient-mc_istio/2011220997964828672

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/58743/integ-ambient-mc_istio/2011141920100716544

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/58590/integ-ambient-mc_istio/2011518050255245312

cc @keithmattix @Stevenjin8

### PR DESCRIPTION
**Pull request by krinkinmu**
**Please provide a description of this PR:**

Part of the multicluster setup is to mark services as global. It takes some time for the labels to get noticed, but it's usually happens pretty quickly. However, pilot implements batching of xDS updates - it does not try to push a change immediately when it sees it, but waits for a bit for potential other changes to arrive, so that all of the changes are pushed together in one batch saving some effort.

There are two time limits involved into this batching process:

1. How long we are willing to wait for new events after the last event we received before we decide to push - DebounceAfter
2. What is the maximum total time we can delay the push of an event, even if we have new events coming all the time - DebounceMax

With those two in mind, after we label services as global, we might want to wait for DebounceMax time to make sure that those changes were pushed. DebounceMax by default is set at 10s, which is a bit too long.

Given that we control the test environment reasonably well, I think we can get away with waiting for just DebounceAfter, which is by default just 100ms, assuming that no changes that will require an xDS push happen during the wait.

Naturally, waiting for some time does not completely eliminate the race condition in the tests, so I'm doubling DebounceAfter to account for reasonable levels of variablity.

Also, I noted that in the tests we label the same services as global twice. I think it was the mistake, and the actual intention was not to lable the services second time, but to label waypoints used by those services and workloads. So I fix that along the way here.

Fixes #58780

### CODE REVIEW

File: tests/integration/ambient/baseline_test.go [hunk 1]
```diff
@@ -2844,23 +2845,31 @@ func runTestContextForCalls(
...
+		// Pilot delays pushing changes to be able to batch multiple incoming changes together and push them
+		// all at once. That means that there is a delay after the last detect change and the push of that
+		// change to the all the relevant nodes.
+		//
+		// We don't expect any changes that should trigger the push in parallel, so it should be enough to
+		// wait for the DebounceAfter time, after the pilot sees the update. Naturally, just because we updated
+		// service labels it does not mean that pilot will immediately see them - there is a race condition here,
+		// but we do expect pilot to notice the update rather quickly, so we double the DebounceAfter time here
+		// to account for this issue.
+		time.Sleep(2 * features.DebounceAfter)
```
Comment (keithmattix) [inline tests/integration/ambient/baseline_test.go:2872]: Rather than sleep, should we change denounce after in the test environment via this env var?

Comment (krinkinmu) [reply tests/integration/ambient/baseline_test.go:2872]: I don't have strong feelings about it, but here are arguments against overriding debounce paramters for tests:

1. I'm under the impression that tunning debounce timeouts is not typical user behavior, so we'd be running integration tests with atypical configuration
2. I think that the point of this batching mechanism is to improve efficiency a bit (even if it comes at the cost of increasing latency of pushing metadata), so reducing debounce timeout would mean that pilot in tests will operate in a less efficient way - it could introduce flakines under resource pressure.

All-in-all, I'd prefer the tests to run successfully with the default parameters rather than tuning pilot for tests, but if you think that changing debounce timeouts for tests is better, then I'm fine with tackling it in a different way.

Comment (keithmattix) [reply tests/integration/ambient/baseline_test.go:2872]: Yeah I think that's reasonable; just wanted to have it articulated

**Comment by keithmattix** [comment]
Looks like we had to run retest a couple of times? Were those flakes for a different issue?

**Comment by krinkinmu** [comment]
> Looks like we had to run retest a couple of times? Were those flakes for a different issue?

@keithmattix integ-ambient and unit-tests-arm64 flaked (one time each), but those are not multicluster test suites and are not related to the issue this PR fixes. I run integ-ambient-mc several times specifically to see if it's going to flake on the CI, so far it didn't. It's hard to see because the history of the failed tests is not preseved in the GitHub comments, but I can see it from the email notifications.

**Comment by keithmattix** [comment]
@krinkinmu I see a `/test integ-ambient-mc` call above.

**Review by keithmattix — APPROVED** [review]
