### PR TITLE
ext-authz: return error for invalid extension provider only when it is being used

### LINKED ISSUE #30824: The ext-authz extension provider meshconfig should not cause error if not used
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
If some extension provider is not used by any authz policy, it should not cause errors even if it might be invalid.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

### PR DESCRIPTION
**Pull request by yangminzhu**
Fixes #30824 

If some extension provider is not used by any authz policy, it should not cause errors even if it might be invalid.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: pilot/pkg/security/authz/builder/extauthz.go [hunk 1]
```diff
@@ -94,16 +91,17 @@ func processExtensionProvider(in *plugin.InputParams) (map[string]*builtExtAuthz
 		if err != nil {
 			errs = multierror.Append(errs, multierror.Prefix(err, fmt.Sprintf("failed to parse extension provider %q:", config.Name)))
 		}
+		if parsed == nil {
```
Comment (incfly) [inline pilot/pkg/security/authz/builder/extauthz.go:94]: couldn't you init parsed as &buildExtAuthz in line 80?

**Review by incfly — APPROVED** [review]

**Comment by incfly** [comment]
is the error in the original issue coming from the validation webhook when applying the meshconfig updaets? I didn't see other unit test updates other than validation-test.go

**Comment by yangminzhu** [comment]
> is the error in the original issue coming from the validation webhook when applying the meshconfig updaets? I didn't see other unit test updates other than validation-test.go

@incfly not from validation webhook but directly from the authz plugin in pilot, it emits the error every time it is called when pushing xDS configs to proxy.

File: pilot/pkg/security/authz/builder/extauthz.go (hunk 1 above)
Comment (yangminzhu) [reply pilot/pkg/security/authz/builder/extauthz.go:94]: the buildExtAuthzHTTP/buildExtAuthzGRPC might return nil, I didn't want to change those 2 functions as it seems nicer to keep the convention of returning nil on errors in that scope.

**Review by howardjohn — APPROVED** [review]
