### PR TITLE
fix: `istioctl install --set` and `istioctl manifest generate --set` boolean var failed

### LINKED ISSUE #43355: Bug for istioctl installation when setting a boolean environment variable in meshConfig.defaultConfig.proxyMetadata
### Bug Description

There is error output when setting a boolean environment variable in `meshConfig.defaultConfig.proxyMetadata` to install Istio, 
Installation:
```
$ istioctl install --set values.pilot.env.ISTIO_DUAL_STACK=true --set meshConfig.defaultConfig.proxyMetadata.ISTIO_AGENT_DUAL_STACK=true -y
```

Output:
```
Run the command with the --force flag if you want to ignore the validation error and proceed.
Error: generate config: failed to unmarshall mesh config: json: cannot unmarshal bool into Go value of type string
```

It's okay if the value is put into an istio installation yaml file

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_AGENT_DUAL_STACK: "true"
  values:
    pilot:
      env:
        ISTIO_DUAL_STACK: true
```

### Version

```prose
client version: 1.17-dev
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Xunzhuo**
**Please provide a description of this PR:**

No matter we pass bool value to be enclosed quotes and escaped with a backslash or not, it will fail in both two situations.

We can now just pass true or false, no need to be enclosed quotes and escaped with a backslash.

```shell
istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.ISTIO_AGENT_DUAL_STACK=true

istioctl install --set meshConfig.defaultConfig.proxyMetadata.ISTIO_AGENT_DUAL_STACK=true --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT=false
```

Fixes: https://github.com/istio/istio/issues/43355

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
do we have testing for this case?

File: operator/pkg/manifest/shared.go [hunk 1]
```diff
@@ -517,6 +524,85 @@ func overlaySetFlagValues(iopYAML string, setFlags []string) (string, error) {
...
+// containParentPath checks if setFlags contain parent path.
+func containParentPath(setFlags []string, parentPath string) bool {
+	ret := false
+	for _, sf := range setFlags {
+		p, _ := getPV(sf)
+		if strings.Contains(p, parentPath) {
+			ret = true
+			break
+		}
+		// if set multiple times, return last set value
```
Comment (zhlsunshine) [inline operator/pkg/manifest/shared.go:601]: so according to current implementation, it seems that there still be bug if multiple `meshConfig.defaultConfig.proxyMetadata` environment variables setting with boolean, am I right?

Comment (Xunzhuo) [reply operator/pkg/manifest/shared.go:601]: No, this comment is a bit misleading, I am going to remove this comment, currently all bool values in proxyMeta will be unmarshalled correctly.

File: operator/pkg/manifest/shared.go [hunk 2]
```diff
@@ -517,6 +524,84 @@ func overlaySetFlagValues(iopYAML string, setFlags []string) (string, error) {
...
+						case int64:
+							convertedProxyMetadata[key] = strconv.FormatInt(value.(int64), 10)
+						case bool:
+							convertedProxyMetadata[key] = strconv.FormatBool(value.(bool))
+						case float64:
+							convertedProxyMetadata[key] = strconv.FormatInt(int64(value.(float64)), 10)
+						case string:
+							convertedProxyMetadata[key] = value.(string)
+						default:
+							return outYAML, fmt.Errorf("not supported type %s", t)
```
Comment (zhlsunshine) [inline operator/pkg/manifest/shared.go:572]: I suggest that it should not be returned error here, but follow the original logic instead, because this switch does not  contains all the types for yaml file.

Comment (Xunzhuo) [reply operator/pkg/manifest/shared.go]: Done

**Review by zhlsunshine — APPROVED** [review]
LGTM, thanks @Xunzhuo

File: operator/pkg/manifest/shared.go [hunk 3]
```diff
@@ -517,6 +525,84 @@ func overlaySetFlagValues(iopYAML string, setFlags []string) (string, error) {
...
+
+			if err := yaml.Unmarshal([]byte(outYAML), &converter); err != nil {
+				return outYAML, err
+			}
+			originMap, ok := converter["spec"].(map[string]any)
+			if !ok {
+				return outYAML, nil
+			}
+
+			for index, subPath := range subPaths {
```
Comment (nmittler) [inline operator/pkg/manifest/shared.go:555]: @howardjohn this logic feels rather boilerplate ... are you aware of any existing utilities that we could leverage here?

File: releasenotes/notes/43355.yaml [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+# issue is a list of GitHub issues resolved in this note.
+# If issue is not in the current repo, specify its full URL instead.
+issue:
+  - 43355
+
+# releaseNotes is a markdown listing of any user facing changes. This will appear in the
+# release notes.
+releaseNotes:
+  - |-
+    **Fixed** `istioctl install --set <boolvar>=<bool>` or `istioctl manifests generate --set <boolvar>=<bool>` returns `Error: generate config: failed to unmarshall mesh config: json: cannot unmarshal bool into Go value of type string`.
```
Comment (dhawton) [inline releasenotes/notes/43355.yaml:34]:
```suggestion
    **Fixed** `istioctl install --set <boolvar>=<bool>` and `istioctl manifests generate --set <boolvar>=<bool>` improperly converting a boolean into a strong.
```

**Review by dhawton — CHANGES_REQUESTED** [review]

File: releasenotes/notes/43355.yaml (hunk 4 above)
Comment (dhawton) [reply releasenotes/notes/43355.yaml:34]: Probably good to include tests

**Review by nmittler — APPROVED** [review]

**Review by dhawton — APPROVED** [review]
Release note looks good.
