### PR TITLE
Ingressrule fixes for gRPC and URLs with dots.

### LINKED ISSUE #1772: Ingress doesn't work for ACME ( or any path with .)
I was trying to setup an Ingress to kube-lego, to automate getting TLS cert.
It requires a rule like: 

  /.well-known/acme-challenge/.*
Also tried
  /\\.well-known/acme-challenge/.*

It seems there are several problems:
- the detection of regex is based on isRegularExpression() using regexp.QuoteMeta - but that method
doesn't take into account escape characters. 
- even if the path would be treated as regex, it doesn't appear that Ingress gets any configuration.
I haven't seen any tests for ingress with regex - so this may be a broader problem.

The ingress spec says: 
        // Path is an extended POSIX regex as defined by IEEE Std 1003.1,
	// (i.e this follows the egrep/unix syntax, not the perl syntax)
	// matched against the path of an incoming request. Currently it can
	// contain characters disallowed from the conventional "path"
	// part of a URL as defined by RFC 3986. Paths must begin with
	// a '/'. If unspecified, the path defaults to a catch all sending
	// traffic to the backend.

### PR DESCRIPTION
**Pull request by costinm**
GRPC and ACME ( and other ) URLs include dots.

The Istio doc is clear that we support only prefix and exact matches - and we don't support regex.
A gRPC URL is an exact matach - that happens to include dots, and should work. Silently dropping valid exact/prefix matches because they look like regex is not useful.

fixes #1772

**Release note**:

```release-note
- Istio Ingress will accept paths containing dots and the common /path/* for prefix matches.

```

### CODE REVIEW

File: pilot/adapter/config/ingress/conversion.go [hunk 1]
```diff
@@ -93,15 +93,14 @@ func createIngressRule(name, host, path, domainSuffix string,
...
-			} else {
-				rule.Match.Request.Headers[model.HeaderURI] = &routing.StringMatch{
-					MatchType: &routing.StringMatch_Regex{Regex: path},
-				}
+		if strings.HasSuffix(path, ".*") {
+			rule.Match.Request.Headers[model.HeaderURI] = &routing.StringMatch{
+				MatchType: &routing.StringMatch_Prefix{Prefix: strings.TrimSuffix(path, ".*")},
+			}
+		} else if strings.HasSuffix(path, "/*") {
+			// Common pattern used by go, java, etc
```
Comment (rshriram) [inline pilot/adapter/config/ingress/conversion.go]: Can we just stick with .* ? It is in line with standard regex format, foo.* .. The /* does not fit with what people use in the proxies, AFAIK, and I don't want to introduce new istio-isms that we have to maintain (we don't have any of this stuff in gateway or route rule).

**Comment by kyessenov** [comment]
I'm generally OK de-supporting regexes. The check for regex always looked fishy to me. I think we should pick one of `.*` or `/*`. Doing both is going to be difficult to support in the future, once wildcards or regexes are introduced.

File: pilot/test/integration/testdata/ingress.yaml.tmpl [hunk 2]
```diff
@@ -41,6 +41,22 @@ spec:
...
           servicePort: 80
+      - path: /javastyle/*
+          backend:
+            serviceName: a
+            servicePort: 80
+      - path: /.well_known/foo
+          backend:
+            serviceName: a
+            servicePort: 80
+      - path: /.well_known/foo/prefix/*
```
Comment (rshriram) [inline pilot/test/integration/testdata/ingress.yaml.tmpl]: This might interpolate well in the shell, but in regex world, this has strange semantics. 0 or more occurrences of `/` ..

File: pilot/adapter/config/ingress/conversion.go (hunk 1 above)
Comment (costinm) [reply pilot/adapter/config/ingress/conversion.go]: Well - we are saying that we don't support regex, but for prefix we use a regex ? I've been hit by this, and I'm
pretty sure most developers are more familiar with the java or go syntax or prefix mapping ( I'm happy with either ).  

/example/ - go 
/example/* - java
/example.* - current istio "we don't support regex except in the end". 

I don't know what 'people use for proxies' - apache also uses prefix, Istio ingress is the only one to use a regex syntax for  a prefix mapping.

**Comment by kyessenov** [comment]
There's no pretty answer here. It's a mess across all ingress controllers. We're just concerned how this is going to work out in the future once we _do_ add regex or wildcard.

File: pilot/adapter/config/ingress/conversion.go [hunk 3]
```diff
@@ -93,15 +93,14 @@ func createIngressRule(name, host, path, domainSuffix string,
...
-		if isRegularExpression(path) {
-			if strings.HasSuffix(path, ".*") && !isRegularExpression(strings.TrimSuffix(path, ".*")) {
-				rule.Match.Request.Headers[model.HeaderURI] = &routing.StringMatch{
-					MatchType: &routing.StringMatch_Prefix{Prefix: strings.TrimSuffix(path, ".*")},
-				}
-			} else {
-				rule.Match.Request.Headers[model.HeaderURI] = &routing.StringMatch{
-					MatchType: &routing.StringMatch_Regex{Regex: path},
-				}
+		if strings.HasSuffix(path, ".*") {
```
Comment (ldemailly) [inline pilot/adapter/config/ingress/conversion.go]: I'd delete this one and be clear we don't do regex and don't pretend to anymore

Comment (kyessenov) [reply pilot/adapter/config/ingress/conversion.go]: We do support regex. The problem is how to do both prefix and regex given a random string in the path.

File: pilot/test/integration/testdata/ingress.yaml.tmpl (hunk 2 above)
Comment (costinm) [reply pilot/test/integration/testdata/ingress.yaml.tmpl]: That's actually a feature :-), since multiple // in URLs are not good.

But the syntax is what Java Servlet spec has used for >10 years.  
I don't mind using the go ServeMux syntax ( with just "url/" ) - since it's easy to differentiate
from the exact match not ending with '/'

The real problem is that it's very easy to get it wrong and send to the wrong place - regex are 
very powerful, but in majority of cases a prefix mapping is easier to understand and harder to get 
wrong. Golang and java don't support regex at all by default - so at least for services using 
standard java  or default golang it'll be more confusing to use one style of rules in the code, 
and a different one in the istio ingress.

File: pilot/adapter/config/ingress/conversion.go (hunk 3 above)
Comment (costinm) [reply pilot/adapter/config/ingress/conversion.go]: We can't just delete it without deprecation, but I'm +1 on deprecating the regex form of prefix matching, and eventually remove it.

One way to add regex support is to use an explicit tag ( instead of Path use Regex), or use 
a prefix 
Path: 
  regex:/.*[a-z]

**Comment by costinm** [comment]
Kuat: our doc explicitly states that Istio ingress doesn't support regex. And my change is removing code that is rejecting anything that looks like a regex.
I have no problem with adding support for regex in ingress - but we need to make the the 'simple case'
of prefix mapping as easy and intuitive  as possible.

**Comment by kyessenov** [comment]
Ah, that was @rshriram who removed it in the last release since he refused
to write regex intersection code :P

**Comment by costinm** [comment]
Well, it is perfectly reasonable to not support regex in ingress - Servlet spec has refused to support it, 
for good reasons ( it would be catastrophic to mess an auth rule with a bad regex, and between the
many regex syntaxes, and the weirdness of escaping -  it's pretty easy to make mistakes ).

And it is also reasonable to support it for very advanced users :-)

My only concern is that developers familiar with go and java - and needing only simple prefix mapping - 
to not have to worry about regex. Remember that some characters need to be escaped - and sometimes
the escape character itself needs escaping. Do we expect anyone writing prefix rules to know all
the details and the specific syntax of regex we use ?

**Comment by costinm** [comment]
No problem with supporting it - but having a good UX where the 'simple cases' are easy is important. 
Maybe some people are driven to nginx for regex - maybe others are driven to use less compex
mappings.  Forcing everyone to use regex just because nginx happens to support it is not a good argument. 

Both java and golang decided they're not needed in the standard library - I think it's reasonable to 
treat regex as a feature for advanced users and optimize the UX for the common case.

**Comment by costinm** [comment]
BTW: envoy has clear separation between 'regex', prefix and exact, so I really don't see any reason 
to say that Istio ingress should force everything to be a regex, and either only generate Envoy regex mappings or attempt to map a regex into a prefix or path that envoy expects.

Exact and prefix are easy to diss-ambiguate in the path - using a special attribute or prefix for regex
seems cleaner for both users and implementation.

File: pilot/adapter/config/ingress/conversion.go (hunk 3 above)
Comment (kyessenov) [reply pilot/adapter/config/ingress/conversion.go]: I'm ok with it, but we should be careful to document that `/a.b/.*` does not match `/axb/`.

**Comment by kyessenov** [comment]
You need to update the e2e tests that exercise regexes/prefixes, since the feature is no longer supported.

**Comment by ldemailly** [comment]
having .* only working at the end, and "." not being the real . regex in the middle doesn't teach anything useful - it should either be a real regexp or not a regexp at all

**Comment by costinm** [comment]
I started a thread to discuss the broader issue and prefix syntax, better
than PR comments :-)

Kuat: which tests do I need to update ?  I didn't find any test for regex
in ingress, and there is no feature that is 'no longer supported'.

**Comment by kyessenov** [comment]
Pending the discussion resolution on the mailing list, and fixing all tests. I added regex tests awhile ago, which I assume causes e2e failure. Those tests might have been removed though awhile ago, In any case, you need to make sure tests pass before merging.
