### PR TITLE
autoregistration: fix marking entries as connected after disconnect

### LINKED ISSUE #44640: TestAutoregistrationLifecycle test flake
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44637/unit-tests-arm64_istio/1652049625789501440

### PR DESCRIPTION
**Pull request by stevenctl**
fixes #44640

The race:
* Start processing a WorkloadGroup Add
* Start processing a proxy disconnect
* If the disconnect update is written first, the WG Add event overwrites it

User impact:

If a user connects their VM, has a WorkloadEntry created then quickly disconnects their VM shortly after the initial WorkloadGroup is created, they will wait for the "periodic" cleanup (based on maxConnectionAge) rather than getting quick cleanup. 

The fix:
* Check that the connection timestamp is newer than the disconnect
* Use `Update` instead of `Patch` to make sure we knew about the timestamps before writing

We're relying on timestamps from different controllers which isn't great, but I don't see a better option. For the case where we have one controller, we could hold locks for longer or lock changes for individual connections/proxies but we will still hit issues with  >  1 istiod. 

```
5s: 48 runs so far, 0 failures
10s: 96 runs so far, 0 failures
15s: 144 runs so far, 0 failures
20s: 216 runs so far, 0 failures
25s: 264 runs so far, 0 failures
30s: 312 runs so far, 0 failures
35s: 384 runs so far, 0 failures
40s: 432 runs so far, 0 failures
45s: 480 runs so far, 0 failures
50s: 531 runs so far, 0 failures
55s: 600 runs so far, 0 failures
1m0s: 648 runs so far, 0 failures
1m5s: 696 runs so far, 0 failures
1m10s: 768 runs so far, 0 failures
1m15s: 816 runs so far, 0 failures
1m20s: 865 runs so far, 0 failures
1m25s: 936 runs so far, 0 failures
1m30s: 984 runs so far, 0 failures
```

### CODE REVIEW

File: pilot/pkg/autoregistration/controller.go [hunk 1]
```diff
@@ -358,16 +359,27 @@ func (c *Controller) changeWorkloadEntryStateToConnected(entryName string, proxy
...
 	// the proxy has reconnected to another pilot, not belong to this one.
 	if conTime.Before(lastConTime) {
 		return false, nil
 	}
 	// Try to patch, if it fails then try to create
-	_, err := c.store.Patch(*wle, func(cfg config.Config) (config.Config, kubetypes.PatchType) {
-		setConnectMeta(&cfg, c.instanceID, conTime)
-		return cfg, kubetypes.MergePatchType
-	})
+	updated := wle.DeepCopy()
```
Comment (shashankram) [inline pilot/pkg/autoregistration/controller.go:380]: nit: misleading comment about patching in L379

**Review by shashankram — APPROVED** [review]
Would be nice if

File: pilot/pkg/autoregistration/controller.go (hunk 1 above)
Comment (stevenctl) [reply pilot/pkg/autoregistration/controller.go:380]: Good catch

**Review by howardjohn — APPROVED** [review]
