### PR TITLE
Fix errors for in-place upgrade 1.6.0 

### LINKED ISSUE #23205: Error for in-place upgrade 1.6.0 alpha.2
**Bug description**
Testing https://preliminary.istio.io/docs/setup/upgrade/#in-place-upgrades for Istio 1.6 Community Testing.

```
$ istioctl160a2 manifest versions

Operator version is 1.6.0-alpha.2.

This version of istioctl can:
  Install Istio 1.5.0
  Update Istio from >=1.4.0 to 1.5.0
  Update Istio from  <1.6 to 1.5.0
```

```
$ istioctl160a2 upgrade
Control Plane - ingressgateway pod - istio-ingressgateway-749468d8cd-4cdlv - version: 1.5.1
Control Plane - pilot pod - istiod-58696868d5-cjzpn - version: 1.5.1

Upgrade version check passed: 1.5.1 -> 1.6.0.

Run the command with the --force flag if you want to ignore the validation error and proceed.
Error: failed to generate Istio configs from file [] for the current version: 1.5.1, error: unknown field "kubevirtInterfaces" in v1alpha1.ProxyConfig
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by elfinhe**
Fix https://github.com/istio/istio/issues/23205: Error for in-place upgrade 1.6.0 

1. Convert tag to the version string.
2. During upgrade, skip validation and warning for old configs

### CODE REVIEW

File: operator/cmd/mesh/profile-common.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ func GenerateConfig(inFilenames []string, setOverlayYAML string, force bool, kub
 	}
 
 	errs, warning := validation.ValidateConfig(false, iops.Values, iops)
-	if warning != "" {
+	if !force && warning != "" {
```
Comment (howardjohn) [inline operator/cmd/mesh/profile-common.go:66]: I think we should still see warnings even if force is enabled

File: operator/version/version.go [hunk 2]
```diff
@@ -41,7 +41,10 @@ func init() {
 	// If dockerinfo has a tag (e.g., specified by LDFlags), we will use it as the version of operator
 	tag := buildversion.DockerInfo.Tag
 	if pkgversion.IsVersionString(tag) {
-		OperatorVersionString = tag
+		OperatorVersionString, err = pkgversion.TagToVersionString(tag)
+		if err != nil {
+			panic(err)
```
Comment (howardjohn) [inline operator/version/version.go:46]: why panic instead of proper handling?

File: operator/cmd/mesh/profile-common.go (hunk 1 above)
Comment (elfinhe) [reply operator/cmd/mesh/profile-common.go:66]: otherwise, we may need to add one parameter for this function to prevent warnings on generating the old (installed) version configs.

File: operator/version/version.go (hunk 2 above)
Comment (elfinhe) [reply operator/version/version.go:46]: ideally we should return error, but this is an init(). I am not quite sure what to do, so just followed the same pattern in other places of this function.

File: operator/cmd/mesh/profile-common.go (hunk 1 above)
Comment (howardjohn) [reply operator/cmd/mesh/profile-common.go:66]: isn't that desired? If my old settings now produce warnings seems like I should know about it?

File: operator/version/version.go (hunk 2 above)
Comment (howardjohn) [reply operator/version/version.go:46]: Seems like this is actualy impossible to trigger. TagToVersionString can only error if its not a semver and we check it is in IsVersionString before hand. Maybe we should just make a function that is safe and never returns an error - instead returning the original tag if its not semver? seeing `panic` is a red flag

File: operator/cmd/mesh/profile-common.go (hunk 1 above)
Comment (elfinhe) [reply operator/cmd/mesh/profile-common.go:66]: not in this scenario. Here during upgrade, we get the current installed version 1.5.1.
Then we use the binary version (1.6.0) code to validate IOP for installed version (1.5.1) default configs by downloading the 1.5.1's packages. Those defaults are built-in the 1.5.1 package, not from the user input.

File: operator/version/version.go (hunk 2 above)
Comment (elfinhe) [reply operator/version/version.go:46]: agree.

**Comment by elfinhe** [comment]
@howardjohn ptal, comments have been addressed.

**Review by howardjohn — APPROVED** [review]

**Comment by ostromart** [comment]
@elfinhe does this need to be cherry-picked into 1.6?

**Comment by elfinhe** [comment]
Adding cherry-pick... Thanks Martin
