### PR TITLE
[release-1.24] Fix Ambient Peer Authn flake (#54566)

### LINKED ISSUE #54570: [release-1.24] Fix Ambient Peer Authn flake
Manual cherrypick required.

#54566 failed to apply on top of branch "release-1.24":
```
Applying: Peer authn flake fix
Using index info to reconstruct a base tree...
M	pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
M	tests/integration/ambient/baseline_test.go
Falling back to patching base and 3-way merge...
Auto-merging tests/integration/ambient/baseline_test.go
CONFLICT (content): Merge conflict in tests/integration/ambient/baseline_test.go
Auto-merging pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
hint: When you have resolved this problem, run "git am --continue".
hint: If you prefer to skip this patch, run "git am --skip" instead.
hint: To restore the original branch and stop patching, run "git am --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Patch failed at 0001 Peer authn flake fix

```

### PR DESCRIPTION
**Pull request by keithmattix**
Fixes #54570 and #54619

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go [hunk 1]
```diff
@@ -265,18 +267,39 @@ func convertPeerAuthentication(rootNamespace string, cfg, nsCfg, rootCfg *securi
 	// Note that this doesn't actually attach the policy to any workload; it just makes it available
 	// to ztunnel in case a workload needs it.
 	foundNonStrictPortmTLS := false
-	for port, mtls := range pa.PortLevelMtls {
+	keys := slices.Sort(maps.Keys(pa.PortLevelMtls))
+	for _, port := range keys {
+		mtls := pa.PortLevelMtls[port]
```
Comment (mikemorris) [inline pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go:272]: This is the backported logic from #54584 for versions of Go before support for iterators, which looks correct to me.

**Review by mikemorris — APPROVED** [review]
