### PR TITLE
Idempotency for istio-iptables apply flow

### LINKED ISSUE #30393: panic in istio-init
```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1611663316986592165.txt253404344
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1611663316986592165.txt253404344
iptables-restore: line 2 failed
iptables-save
# Generated by iptables-save v1.6.1 on Tue Jan 26 12:15:16 2021
*nat
:PREROUTING ACCEPT [1549:92940]
:INPUT ACCEPT [2432:145920]
:OUTPUT ACCEPT [2242:151685]
:POSTROUTING ACCEPT [3116:204125]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Tue Jan 26 12:15:16 2021
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x3cb0a30, 0x26101e9, 0x10, 0xc001505e60, 0x2, 0x2)
        istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00133fd68, 0x3c7da01, 0x0, 0x0)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:554 +0x38a
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc00133fd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:561 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00133fd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:499 +0x2b7b
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x3c58c20, 0xc0014a2600, 0x0, 0x10)
        istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:58 +0x150
github.com/spf13/cobra.(*Command).execute(0x3c58c20, 0xc00021bf00, 0x10, 0x10, 0x3c58c20, 0xc00021bf00)
        github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3c58ec0, 0x0, 0x0, 0x0)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        istio.io/istio/pilot/cmd/pilot-agent/main.go:487 +0x31     
```           

[ ] Docs
[ ] Installation
[X ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
vinemish:/tmp
⚡ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (6 proxies)

vinemish:/tmp
⚡ kubectl version --short
Client Version: v1.17.0
Server Version: v1.18.15+IKS
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM cloud

Also FIRST attempted run of istio-init in the pod is always good but next attempt fails while restroing the iptables. Attaching logs of the first run.

```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1611660216882762309.txt988125463
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
iptables-restore --noflush /tmp/iptables-rules-1611660216882762309.txt988125463
Writing following contents to rules file:  /tmp/ip6tables-rules-1611660217252646072.txt032735626

ip6tables-restore --noflush /tmp/ip6tables-rules-1611660217252646072.txt032735626
iptables-save
# Generated by iptables-save v1.6.1 on Tue Jan 26 11:23:37 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Tue Jan 26 11:23:37 2021
```

Also I have observed that whenever packet and byte counter increases init pod crashes.. 
```
:PREROUTING ACCEPT [1549:92940]
:INPUT ACCEPT [2432:145920]
:OUTPUT ACCEPT [2242:151685]
:POSTROUTING ACCEPT [3116:204125]
```
If you see good run log packet and byte counters are 0. Can somebody please help me and let me know what is missing here ?

### PR DESCRIPTION
**Pull request by leosarra**
**Please provide a description of this PR:**
Fixes #30393 and #42792 .

Current behavior on master will make a re-execution of istio-init container likely to fail due to the possibility of having existing ISTIO_* chains (and/or rules).
If, for whatever reason, the init containers are getting re-executed, we should make sure that they do not fail because the settings are already in effect. This is also one of the recommendation of the k8s doc about init containers:

> Because init containers can be restarted, retried, or re-executed, init container code should be idempotent. In particular, code that writes to files on EmptyDirs should be prepared for the possibility that an output file already exists.
> -- https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

With these changes `pilot-agent ip-tables` will remove rules that would end up being duplicated + existing istio chains.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 1]
```diff
@@ -170,6 +170,45 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
 	return output
 }
 
+func (rb *IptablesRuleBuilder) buildCleanupRules(rules []*Rule) [][]string {
```
Comment (bleggett) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:173]: Nice! TY!

If all our rules are in custom chains, does this

- simply drop the entire chain on removal, as well as all jumps to the chain?
or
- run _exactly_ in reverse and remove every rule from the chain as well as the chain itself and all jumps?

the first is all we need really if we stick to the right conventions internally, but if this is an automated inversion of rules creation that doesn't rely on convention to reliably reverse any input, I wouldn't say no to it.

File: tools/istio-iptables/pkg/cmd/root.go [hunk 2]
```diff
@@ -136,6 +136,8 @@ func bindCmdlineFlags(cfg *config.Config, cmd *cobra.Command) {
 		&cfg.NetworkNamespace)
 
 	flag.BindEnv(fs, constants.CNIMode, "", "Whether to run as CNI plugin.", &cfg.CNIMode)
+
+	flag.BindEnv(fs, constants.PreemptiveCleanup, "", "Whether to run a preemptive cleanup to prevent duplicated rules and chains", &cfg.PreemptiveCleanup)
```
Comment (bleggett) [inline tools/istio-iptables/pkg/cmd/root.go:140]: Asking, because I haven't formed an opinion yet - does this need to be optional? Why would you not want to always just do this as a pre-step?

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 1 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:173]: Also, for init containers, upgrades are not a concern (AFAICT), so reversing your created rules exactly will always work for cleanup.

For things like ambient, we might need to contend with cleanup after an upgrade, where rules might have changed subtly between releases - so reversing the 1.21 hardcoded rules might not 100% match the reversed 1.20 rules, and such.

That's a scenario where I wonder if dropping chains and jumps with a given prefix might be more robust than strict mirror-reversal.

File: tools/istio-iptables/pkg/cmd/root.go (hunk 2 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/cmd/root.go:140]: I was not sure if it should be performed all the time. I put it as opt-in for now in order to not impact the VM usecase (usecase of which I don't know much about).
I'm investigating if there could be an impact there by doing a preemptive cleanup which deletes the ISTIO_* chains and every rule in them.

Anyway, I'm still doing some manual tests and I need to add proper coverage for this cleanup.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 1 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:173]: (Sorry, forgot to respond here)



>     ISTIO_* Chain Jump Rule: If a rule is created to jump to an ISTIO_* chain, reverse it. This would cover also an hypothetical jump from an ISTIO_CHAIN to another ISTIO_CHAIN.
>     
>     Non-ISTIO_* Chain Rule: If a rule is created in a non-ISTIO_* chain, reverse it (should I care about this outside of the jump-rules to istio chains?) yes I should since we also apply those under certain circumstances
>     
>     ISTIO_* Chain Rule: If a rule is created inside an ISTIO_* chain, ignore it (it will be deleted later with the chain).
>     Delete ISTIO_* Chains: At the end, all ISTIO_* chains are deleted regardless.

This sounds good to me, for the following reasons.

1. `istio-iptables` is used by both `istio-init` sidecars and `ambient`, so new stuff we add must be something that can work for both.

2. I want to discourage people/ourselves from adding Istio rules to non-prefixed chains - in sidecar and ambient. 
We should never add anything to main tables but jumps. If we are, we should tag those with TODO and/or WARN on remove for those rules.

To facilitate #2, can you add a WARN log to the cleanup if it finds a non-jump rule in the main table, as a nag to us to eventually remove those?

File: releasenotes/notes/50328.yaml [hunk 3]
```diff
@@ -0,0 +1,10 @@
+apiVersion: release-notes/v2
+kind: feature
```
Comment (bleggett) [inline releasenotes/notes/50328.yaml:2]:
```suggestion
kind: bugfix
```

IMO this is just something that didn't work correctly before, and should have, and thus this is a bugfix - do you have any objection to classifying it as such?

File: tools/istio-iptables/pkg/cmd/root.go (hunk 2 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/cmd/root.go:140]: I would prefer _not_ to make this a flag, and simply do it every time, which should be fine if it is idempotent.

If we did have to make it an option, the option should be an opt-out, not an opt-in.

File: tools/istio-iptables/pkg/capture/run_test.go [hunk 4]
```diff
@@ -337,6 +337,43 @@ func TestSeparateV4V6(t *testing.T) {
...
+		config func(cfg *config.Config)
+	}{
+		{
+			"cleanup-empty",
+			func(cfg *config.Config) {
+				cfg.PreemptiveCleanup = true
+			},
+		},
+		{
+			"cleanup-dns",
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/run_test.go:352]: Given my comments elsewhere, could we add another test (here or elsewhere) that validates that IF an `ISTIO_xxx` chain + jump exists, the jump and chain are removed even if the rules inside the chain are not exactly what we expect?

File: releasenotes/notes/50328.yaml (hunk 3 above)
Comment (leosarra) [reply releasenotes/notes/50328.yaml]: No objections, changed.

File: tools/istio-iptables/pkg/capture/run_test.go (hunk 4 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run_test.go:353]: I will add a test case for this.
Right now I'm struggling with the existing .golden files that needs to be updated to due the cleanup being enabled by default.
Do you know if the .golden files for tools/istio-iptables are supposed to be generated via `make refresh-goldens` ? It looks like the content has to be manually updated  :|

Comment (bleggett) [reply tools/istio-iptables/pkg/capture/run_test.go]: > Do you know if the .golden files for tools/istio-iptables are supposed to be generated via `make refresh-goldens` ? It looks like the content has to be manually updated :|

For iptables they are manually created, yes. Which is good, since it helps catch problems where expectation does not match reality :D

File: tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden [hunk 5]
```diff
@@ -1,3 +1,51 @@
...
+iptables -t raw -D OUTPUT -p udp --dport 53 -m owner --gid-owner 1 -j CT --zone 1
+iptables -t raw -D OUTPUT -p udp --sport 15053 -m owner --uid-owner 4 -j CT --zone 2
+iptables -t raw -D OUTPUT -p udp --dport 53 -m owner --uid-owner 4 -j CT --zone 1
+iptables -t raw -D OUTPUT -p udp --sport 15053 -m owner --uid-owner 3 -j CT --zone 2
+iptables -t raw -D OUTPUT -p udp --dport 53 -m owner --uid-owner 3 -j CT --zone 1
+iptables -t nat -D OUTPUT -p udp --dport 53 -d 127.0.0.53/32 -j REDIRECT --to-port 15053
+iptables -t nat -D OUTPUT -p udp --dport 53 -m owner --gid-owner 2 -j RETURN
+iptables -t nat -D OUTPUT -p udp --dport 53 -m owner --gid-owner 1 -j RETURN
+iptables -t nat -D OUTPUT -p udp --dport 53 -m owner --uid-owner 4 -j RETURN
+iptables -t nat -D OUTPUT -p udp --dport 53 -m owner --uid-owner 3 -j RETURN
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden:15]: (not related to your PR, general comment)

Yeah - see stuff like this should be in `ISTIO_XX` chains, not hanging out in `OUTPUT`.

I will open an issue.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 1 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go]: I will open an issue to fix them - I would rather have the nag than not :D

EDIT: https://github.com/istio/istio/issues/50532

File: tools/istio-iptables/pkg/capture/run_test.go (hunk 4 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/capture/run_test.go]: > I guess that, considering the way the reverse logic operates, we are always placed in a sort-of-scenario where "rules inside the chain are not exactly what we expect" simply because the "reverser" ignores them and continues to remove the custom chains regardless of the rules inside them.

Yep, I just want to add a test that would explicitly fail if someone in the future breaks that behavior, since it's a bit subtle.

**Comment by bleggett** [comment]
Looking good, TY!

**Review by howardjohn — CHANGES_REQUESTED** [review]
doesn't delete+apply cause downtime if we are to actually apply this somewhere with rules already? Thinking of VMs, etc?

Or in the pod case as well actually. This seems dangerous

**Comment by howardjohn** [comment]
> Well, in the case he's trying to fix, traffic disruption already is unavoidable and it shouldn't be unsafe:
> 
> >

In this case "Because init containers can be restarted, retried, or re-executed, init container code should be idempotent. In particular, code that writes to files on EmptyDirs should be prepared for the possibility that an output file already exists."

traffic is 100% fine. Kubernetes/the container runtime is being silly and re-running the init container for no reason, but the application containers are perfectly fine. TBH I don't know how it is acceptable for k8s to do this, but :shrug:

**Comment by bleggett** [comment]
> In this case "Because init containers can be restarted, retried, or re-executed, init container code should be idempotent. In particular, code that writes to files on EmptyDirs should be prepared for the possibility that an output file already exists."
> 
> traffic is 100% fine. Kubernetes/the container runtime is being silly and re-running the init container for no reason, but the application containers are perfectly fine. TBH I don't know how it is acceptable for k8s to do this, but 🤷

Maybe we should just stop running `iptables` in init containers then. I don't think it is possible to run iptables and maintain both idempotency and traffic disruption guarantees.

**Comment by leosarra** [comment]
Oooh, I assumed that init containers would not be re-executed while the application is running but I was wrong, it does indeed look like it can happen...

Yes, the iptables operation are not atomic so the delete will lead to a shortly downtime to the iptables coverage.
On the other end, as Ben mentioned, the rerunning of the iptables command on master is not working at all due to failures in case of pre-existing chains/rules. This will lead to permanent traffic loss unless the pod is recreated.

I think we can find a middle-ground to reduce the impact on existing rules in case of reruns.
Instead of doing a cleanup I could a step that check for existing chains/rules via iptables -L (chains) and iptables -C (rules), if an existing chain/rules is found then the single iptables -N/-A will be skipped.
This should prevent a downtime of the istio-iptables rules in case they are re-applied while the application is running.

Keep in mind that checking chain/rules existance is not race-condition safe so running multiple istio-iptables cmd in parallel can lead to the usual shenanigans. In case of race condition:
- best case: chain are assumed to not exists while in reality they are -> error raised
- worst_case: chain are assumed to not exists while in reality they are -> rule are created twice.
I assume that is fine since we don't expect parallel executions of istio-iptables.

Regarding the current cleanup logic of PR this could go behind a flag --reverse flag which, while it will not be used for providing idempotency, it could still provide a simple way to reverse changes performed via istio-iptables.

What do you think :) ?

**Comment by bleggett** [comment]
One thing to keep in mind - the iptables library we have is used in 3 spots. 1 of which is run as a CLI binary in a sidecar context. The other 2 spots use it as a straight library, and may or may not use it in a sidecar context, as the README mentions: https://github.com/istio/istio/tree/master/tools/istio-iptables/pkg#readme

Whatever we do here has to work equally well for all 3 spots - it cannot be _just_ for init containers or just for invocations of the library's CLI wrapper.

> I think we can find a middle-ground to reduce the impact on existing rules in case of reruns. Instead of doing a cleanup I could a step that check for existing chains/rules via iptables -L (chains) and iptables -C (rules), if an existing chain/rules is found then the single iptables -N/-A will be skipped. This should prevent a downtime of the istio-iptables rules in case they are re-applied while the application is running.

This is still not an upgrade-safe reversal, outside of the `init` container scenario it would fail if we changed rules between releases (maybe a security hole was found in a set of rules in a prev. release,  etc).

If you do it per-rule, we need 2 modes 

- _error_ if existing rule does not exactly match the expected rule, even if it exists.
- _warn and replace_ if existing rule does not exactly match the expected rule

otherwise skip if the rule is already there and is exactly what we expect.

**Comment by bleggett** [comment]
Another thing we could do is say that there are no traffic disruption guarantees for init containers, because as per kube init containers can be restarted.

And that if people are concerned about that, they should use istio CNI and the cni plugin instead of the init container.

**Comment by bleggett** [comment]
> :-1: 
> 
> It is 100% unacceptable for us to take a working, running sidecar and suddenly stop capturing traffic. That is a critical CVE.

Yes, it is also not what I'm suggesting.

I'm suggesting traffic disruption, not traffic escape.


> Especially when the motivation for it is mostly cosmetic (the init container restarting issue just results in it crashlooping, **which has no effect** on the app).

That's true here, but does it change the fact that we will still need a cleanup mechanism, either way, that works in all contexts?

We should at least document that we ignore the K8S spec for our init containers, then, and tell people to ignore the crashlooping Istio containers.


> Also I don't really see why we cannot pick all 3. You can update iptables rules without "delete+add". Also, we probably don't even need to update them at all, just see they are already what we want and bail out without doing anything?

Yes, if they are all correct, we can do nothing. The complications enter if they are not all correct (because they got mangled, or are outdated, or otherwise not in a known-good state) - what do we do?

**Comment by leosarra** [comment]
Hey all,
Thank you for all the feedback, I did some rework based on it :)
In the new version the cleanup-apply of iptables is only performed if residue of previous executions are found and those residues are not compatible with the iptables that are planned to be applied.
If the cleanup is needed, now some "temporarily safeguards" are added to stop traffic while the cleanup-apply step is being performed.
This would allow to have no traffic loss in case of reruns when the initial state was already correct, on the other cases a minor downtime of traffic is expected (which is anyway more desirable than the current behavior of master).
Here is a photo of the overall flow:
image

There is one important thing to mention about the code that verifies if the current state is "compatible" with the desired iptables.
The implemented code verifies exact rule/chain matches but it DOES NOT compare the order of the rules within chains.

In my initial testing, I tried to perform checks on ordering by directly comparing the overview captured by iptables-save with the intended rules. This proved to be unreliable as the internal representation of iptables rules can be different from the original iptables that are applied. 
For example flags can slightly change name after the rules are appended, representation of marks can change (integer to hexadecimal), new flags may be added by default, some flags may be removed as redundant.
This makes a comparison quite hard to pull off, and it may get influenced also by the kernel version.

The current approach still relies on iptables-save to get the current state to verify which chains/rules are defined but par of the verification is done via iptables -C which does not check rule ordering. Not sure if I should consider this a deal-breaker for the whole verification logic.

The testing is mostly in place, I need to add some "unexpected rules" to verify that those are also properly cleanup as expected.

**Comment by howardjohn** [comment]
Nice, the new check sounds like it could be a lot more reliable.

One thing I worry about is the init container case in Kubernetes. Its important to consider in this case **there is nothing wrong with their pod today**. All traffic works fine. 

I worry we will have a false-positive, rewrite the rules, and cause a small outage for these users; all of this for a change that wasn't actually fixing real traffic issues.

Is there some way we can only do this outside of k8s or something?

Also, kube-proxy has some updating of iptables, they may have some good patterns for this

**Comment by bleggett** [comment]
> There is one important limitation to mention about the code that verifies if the current state is "compatible" with the desired iptables. The implemented code verifies exact rule/chain matches but it does not compare the order of the rules within chains.
> The current approach still relies on iptables-save to get the current state to verify which chains/rules are defined but par of the verification is done via iptables -C which does not check rule ordering. Not sure if I should consider this a deal-breaker for the whole verification logic.

I don't think it is. At-worst, if we upgrade and intentionally change the order of rules to fix something, but do not change the rules themselves, this logic would not be upgrade-proof in that specific scenario - which I can live with.

In all other cases it should be just fine, and `iptables -C` is a smarter check than diffing `iptables-save` anyway I think.



> Nice, the new check sounds like it could be a lot more reliable.
> 
> One thing I worry about is the init container case in Kubernetes. Its important to consider in this case **there is nothing wrong with their pod today**. All traffic works fine.
> 
> I worry we will have a false-positive, rewrite the rules, and cause a small outage for these users; all of this for a change that wasn't actually fixing real traffic issues.

This is something we can exercise with unit tests. Any false-positive would be an `istio-iptables` expected state computation bug. Especially for non-upgrade scenarios (sidecars/init containers) - if the actual state != expected state, then either our expected state is miscomputed (`istio-iptables` bug we need to fix) or the actual state is wrong (problem we need to correct), there are no other legitimate variables, and any illegitimate variables are bugs in our code.

> Is there some way we can only do this outside of k8s or something?
We need this logic generally for `istio-iptables`, in various contexts. If it's broken in one context, it will be broken in all of them.

> Also, kube-proxy has some updating of iptables, they may have some good patterns for this
Worth checking yep.

**Comment by howardjohn** [comment]
> This is something we can exercise with unit tests. Any false-positive would be an istio-iptables expected state computation bug. Especially for non-upgrade scenarios (sidecars/init containers) - if the actual state != expected state, then either our expected state is miscomputed (istio-iptables bug we need to fix) or the actual state is wrong (problem we need to correct), there are no other legitimate variables, and any illegitimate variables are bugs in our code.

Or user added their own rules that work with Istio, etc. There is so much 'unknown unknown' risk when doing anything with iptables, and the impact of being wrong is so high. I really do not want to add risk here -- where there is ~none currently -- for a trivial benefit. It is super high risk, very low reward.

> We need this logic generally for istio-iptables, in various contexts. If it's broken in one context, it will be broken in all of them.

Yes, but in k8s there is never a legitimate reason to re-run the init container. We could have "if there are rules, exit 0".

VMs are different since it can legitimately run multiple times. Also, on VMs we already (via systemd) do delete+recreate on restart (which also is problematic, but....)

**Comment by leosarra** [comment]
> I worry we will have a false-positive, rewrite the rules, and cause a small outage for these users; all of this for a change that wasn't actually fixing real traffic issues.

> This is something we can exercise with unit tests. Any false-positive would be an `istio-iptables` expected state computation bug. Especially for non-upgrade scenarios (sidecars/init containers) - if the actual state != expected state, then either our expected state is miscomputed (`istio-iptables` bug we need to fix) or the actual state is wrong (problem we need to correct), there are no other legitimate variables, and any illegitimate variables are bugs in our code.

Normally, the detection of leftovers in istio-init is where I expect it to work best, as there is no risk for rules order to change between reruns.
What can happen in istio-init reruns is that either the current rules are a subset of the expected ones (due to failure in the previous run) or they are exactly the ones that are required (the previous run succeded). If, for some reason, the detection of leftovers does not lead to the expected outcome, then it is a bug that we can handle from our side. I already ran the validation against all existing iptables use cases in the unit test to provide good coverage for this.

Of course, if the application starts tinkering with iptables rules as well, then the cleanup will be triggered even when not needed.
If we are concerned about false positives and we want to play it safe, then I could add a `--skip-cleanup` flag (controlled via the charts) which would make istio-init only perform the leftover-check with an early exit if no changes are needed. We would end up having istio-init running with `--skip-cleanup`  by default.
This would allow for istio-init to rerun if the previous execution was successful and if the application did not perform any additional changes to iptables in the meantime (likely the majority of reruns of istio-inits will fall into this scenario).

If, instead, incompatible leftovers are found, they will not be deleted and istio-init will proceed with applying the new chains/rules without a cleanup -> failure due to chains already existing (same as current behavior on the master branch).

The trade-off of disabling the cleanup for istio-init is that if the previous istio-init execution was only partially successful (or if "extra changes" were performed by the application), then re-runs will fail, leading to istio-init going into a crash-loop and traffic will never start working.

If we accept the trade-off, then I will update the flow and implement it together with the remaining test cases.

> I don't think it is. At-worst, if we upgrade and intentionally change the order of rules to fix something, but do not change the rules themselves, this logic would not be upgrade-proof in that specific scenario - which I can live with, since this is far better than current state.
> 
> In all other cases it should be just fine, and `iptables -C` is a smarter check than diffing `iptables-save` anyway I think.

Yes, upgrade is the place where the limitation will show up, and it is a bummer...
I don't think there is a way to easily take care of that without getting into an unmaintainable mess :(
A possible mitigation would be to add an option to force the cleanup, but in order for that to be useful, we need the caller of the CLI/library to know when that is needed or not.

> VMs are different since it can legitimately run multiple times. Also, on VMs we already (via systemd) do delete+recreate on restart (which also is problematic, but....)

Yes, I noticed that as well, the restart of the istio service does not provide any mitigation for potential traffic escape (nor I think it is documented).

**Comment by bleggett** [comment]
> Yes, upgrade is the place where the limitation will show up, and it is a bummer...

To be clear, I am not very worried about this limitation, changing the order of rules without changing the rules isn't something we have ever had to do and is vanishingly unlikely.

**Comment by bleggett** [comment]
> We only want to accept the tradeoff when istio-init spuriously restarts not if it failed previously. For any other case I think we need a "no tradeoffs" solution...
> 
> I don't know how to do it, but I don't see how we can compromise otherwise...
> 
> Basically this piece of code is the foundation of Istio and the most critical from a security and reliability standpoint.

What kinds of false positives are you concerned with, exactly? There are only a few ways this can happen AFAICT, and all of them would be our bugs (which we would need to fix either way) if they happened.

> What can happen in istio-init reruns is that either the current rules are a subset of the expected ones (due to failure in the previous run) or they are exactly the ones that are required (the previous run succeded). If, for some reason, the detection of leftovers does not lead to the expected outcome, then it is a bug that we can handle from our side. I already ran the validation against all existing iptables use cases in the unit test to provide good coverage for this.

Right, this false-positive case I am not worried about, it is easy to prove correctness and prevent regressions with simple unit tests, which we mostly we already have.


> Of course, if the application starts tinkering with iptables rules as well, then the cleanup will be triggered even when not needed.

If something else is tinkering with _our_ rules, which are the only ones we would trigger on anyway, we _have_ to trigger - that's not a false-positive, that's a true-positive. We have to fix that and it's a security bug not to.


So I'm not sure where false positives enter here? Either they come from bugs we can write simple unit tests around, or they aren't false positives at all.

**Comment by howardjohn** [comment]
@bleggett my concern is our contract is "We will initialize iptables at pod startup". We do this through CNI or init-containers.

Kubernetes has a ~bug (maybe they don't call it that, but its silly IMO) that they will re-trigger init containers. When we use init containers to actuate our contract, we run into some _not important_ issues by this: kubernetes will crashloop the container **which has no impact on the system**.

So this PR proposes to fix it. But its not making it so we don't crashloop on Kubernetes doing silly things, instead its making it so we are now ~dynamically reconciling iptables at semi-arbitrary intervals.

We should either remain "we initialize at startup" or become "we continuously reconcile". But "if Kubernetes does something silly every month or so for a random node, we maybe do something super dangerous" is a pretty poor state to be in. Its really important that we are consistent in behavior, and not triggering changes inconsistently IMO. A past analogy would be protocol detection - we used to have a timeout of 5s. What ended up happening was sometimes a pod would get super throttled (or slow network) and the connection took 6s and suddenly behaved totally differently. These inconsistent issues led to ~0.01% of traffic failing which is super hard to debug, and at worst causes cascading failures if something starts triggering it consistently. Our fix was to never timeout: this meant users with server first applications **hard failed**, but they did so 100% of the time (which is fine; its obvious because its consistent and can be fixed), instead of normal traffic failing 0.01% of the time

We have three cases with this PR:
1) We detect there _really were_ changes and dynamically change the iptables: this is bad because it happens ~randomly, not consistently. 
2) We have a bug, and accidentally think we need to make changes. This basically causes a small period of downtime, for 0 benefit. Given the complexities of iptables, I would give us a 75% chance of having a bug -- not a diss of any programmer here, iptables just has an absurd number of subtle edge cases.
3) We detect no changes and do nothing

Only case (3) is desirable. So why not just do that?

**Comment by bleggett** [comment]
> @bleggett my concern is our contract is "We will initialize iptables at pod startup". We do this through CNI or init-containers.
> 
> Kubernetes has a ~bug (maybe they don't call it that, but its silly IMO) that they will re-trigger init containers. When we use init containers to actuate our contract, we run into some _not important_ issues by this: kubernetes will crashloop the container **which has no impact on the system**.
> 
> So this PR proposes to fix it. But its not making it so we don't crashloop on Kubernetes doing silly things, instead its making it so we are now ~dynamically reconciling iptables at semi-arbitrary intervals. We should either remain "we initialize at startup" or become "we continuously reconcile".

I agree those are the two options, but in reality there is only one we can pick. 

We must dynamically/continuously reconcile in all spots where we use `iptables` - this is either current state (CNI sidecar repair), or near-state (CNI ambient upgrade/repair). We can't avoid that.

The _only_ place where until now we have gotten away with _not_ doing that so far without it being a basic security gap/source of traffic escape bugs is sidecar init containers, because we can lean on K8S invariant around init containers and pod restarts.

Except, we can't lean on that as we've seen, because it doesn't work that way in K8S, and will (likely) never work that way.

> Its really important that we are consistent in behavior, and not triggering changes inconsistently IMO. 

I agree, which is why we should trigger changes anytime actual state != required state, for the purposes of our traffic capture guarantees. The only other option is to do it once and hope it never breaks, which is a nonstarter in every other spot we use `iptables`. And, strictly speaking, is a nonstarter here too, with init containers.

> A past analogy would be protocol detection - we used to have a timeout of 5s. What ended up happening was sometimes a pod would get super throttled (or slow network) and the connection took 6s and suddenly behaved totally differently. These inconsistent issues led to ~0.01% of traffic failing which is super hard to debug, and at worst causes cascading failures if something starts triggering it consistently. Our fix was to never timeout: this meant users with server first applications **hard failed**, but they did so 100% of the time (which is fine; its obvious because its consistent and can be fixed), instead of normal traffic failing 0.01% of the time

I am fine with a hard-fail/don't-fix mode as an optional extension of the detect-and-repair mode, and I am fine turning on the don't-fix-hard-fail mode for sidecar init containers by default. But the detect and repair mode will be necessary in every other spot we use iptables, so we can't not have it.

> We have three cases with this PR:
> 
>     1. We detect there _really were_ changes and dynamically change the iptables: this is bad because it happens ~randomly, not consistently.

Yes, it is also bad if we don't detect and don't fix, because (we or something else) broke the rules and traffic escapes, or is otherwise mangled. We are the only ones that know what the expected correct state is, we are the only ones that can detect and fix. To your earlier point about traffic escape - we have a responsibility to prevent it if we can. And we can.

>     2. We have a bug, and accidentally think we need to make changes. This basically causes a small period of downtime, for 0 benefit. Given the complexities of iptables, I would give us a 75% chance of having a bug -- not a diss of any programmer here, iptables just has an absurd number of subtle edge cases.

We use this library all over. It's security critical, to your point.  Sidecar init containers is _one_ spot where we use it - a spot where we currently fail (philosophically legit or not, it doesn't matter. K8S does X, and we do Y, which is broken). We need repair and idempotency in _all_ the other spots - we will hit these bugs now, or later. We cannot avoid these bugs (some of which might already be present in the current code). We have to write tests around them.

I am fine with a hard-fail/don't-fix mode as an optional flag - especially if we can enable this in tests. As we saw with sidecar repair, fail-don't-fix is necessary for CI.

>     3. We detect no changes and do nothing
> 
> 
> Only case (3) is desirable. So why not just do that?

It's only desirable (and arguably ~safe) in 1 of the 4 spots we use this library. For that one spot where it is desirable and ~safe, it's not desirable for users or K8S, and it's not safe in all scenarios.

**Comment by leosarra** [comment]
Added the "release-notes-none" label even though the PR includes a release notes.

It looks that the "gh pr view" command that is executed by the pipeline is capped to 100 files (https://github.com/cli/cli/discussions/5359) which makes the check fails if none of those files ends up being the newly added release notes :smiling_face_with_tear:

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 6]
```diff
@@ -170,6 +177,120 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
...
+			continue
+		}
+
+		output = append(output, &Rule{
+			chain:  r.chain,
+			table:  r.table,
+			params: modifiedParams,
+		})
+	}
+	return output
```
Comment (bleggett) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:216]: For any func (like this and `checkRules` and `cleanupRules`) that mutates the rules, can you debug-log-dump the result?

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 7]
```diff
@@ -170,6 +177,120 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
...
+				chainTableLookupSet.Insert(chainTable)
+			}
+		}
+	}
+	return output
+}
+
+func (rb *IptablesRuleBuilder) buildGuardrails() []*Rule {
+	rules := make([]*Rule, 0)
+	rb.insertInternal(&rules, iptableslog.UndefinedCommand, constants.INPUT, constants.FILTER, 1, "-p", "tcp", "-j", "DROP")
```
Comment (bleggett) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:288]: Please add `DROP`s for UDP as well - we also mutate UDP rules in some spots.

File: tools/istio-iptables/pkg/capture/run.go [hunk 8]
```diff
@@ -754,38 +756,215 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
+	type ParsedCmd struct {
+		flag  string
+		value string
+	}
+	result := make(map[string]map[string][]string)
+	for _, defaultTable := range []string{constants.FILTER, constants.NAT, constants.MANGLE, constants.RAW} {
+		result[defaultTable] = make(map[string][]string)
+	}
+
+	flagRegex := regexp.MustCompile(`-([^\s]+)(?:\s+([^-\s]+))?`)
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/run.go:782]: Describe with a comment what the purpose and function of this regex is, please.

File: tools/istio-iptables/pkg/cmd/root.go [hunk 9]
```diff
@@ -136,6 +136,11 @@ func bindCmdlineFlags(cfg *config.Config, cmd *cobra.Command) {
 		&cfg.NetworkNamespace)
 
 	flag.BindEnv(fs, constants.CNIMode, "", "Whether to run as CNI plugin.", &cfg.CNIMode)
+
+	flag.BindEnv(fs, constants.SkipCleanup, "", "Skip cleanup of pre-existing and incompatible iptables rules", &cfg.SkipCleanup)
```
Comment (bleggett) [inline tools/istio-iptables/pkg/cmd/root.go:140]:
```suggestion
	flag.BindEnv(fs, constants.NoReconcile, "", "Skip reconciliation of pre-existing and incompatible iptables rules, failing instead if drift detected", &cfg.NoReconcile)
```

cleanup != reconciliation so better to use different names.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 10]
```diff
@@ -170,6 +177,120 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
 	return output
 }
 
+func reverseRules(rules []*Rule) []*Rule {
```
Comment (bleggett) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:180]: I know we have 1-2 bigger scoped tests that you added, and the existing golden-based checks, but I would like (smaller, simpler, direct) unit tests around these specific mutative funcs, directly testing the logic branches present in each.


Especially since all these helper funcs are 

- Critical
- Have no hard OS deps/are all string manip

it would be much better to describe the behavior of these functions in tighter unit tests with no deps/mocks/extra layers.

File: tools/istio-iptables/pkg/capture/run.go [hunk 11]
```diff
@@ -754,38 +756,215 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
+		if guardrails {
+			log.Info("Removing guardrails")
+			guardrailsCleanup := cfg.ruleBuilder.BuildCleanupGuardrails()
+			_ = cfg.executeIptablesCommands(iptVer, guardrailsCleanup)
+			_ = cfg.executeIptablesCommands(ipt6Ver, guardrailsCleanup)
+		}
+	}()
+
+	residueFound, applyRequired := cfg.VerifyRerunStatus(iptVer, ipt6Ver)
+	// Cleanup Step
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/run.go:924]: We need to explicitly error if residue == true && reconcile == false.

The three modes should be

1. Remove all without recreate
2. Apply without reconcile (error if delta - this is basically current state)
3. Apply with reconcile (warn if delta)

To represent those states we need 2 flags - `removeonly = true|false` and `reconcile = true|false`

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 6 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:217]: Added debug dumps and also some additional debug messages for the verification logic that determines whether a delta is found and reconciliation is needed

File: tools/istio-iptables/pkg/capture/run.go (hunk 11 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:935]: Done,
We now have all three as follow:
- Simply remove all without (re)create: --cleanup-only flag
- Apply all without reconcile (error if delta is found): --no-reconcile. This will: (1) "fast-fail" if delta is found and reconciliation is needed, (2) it will "fast-exit" if delta is found and no reconcilation is needed, (3) apply rules as normal if no delta is found.
- Apply all with reconcile (implies cleanup - warn if delta, then fix): default behavior, cleanup is only performed if incompatible delta is found.

btw I refactored the code to use the deltaExists, reconcile variables instead of the old leftoverFound, applyRequired

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 10 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:180]: Sure, makes sense. I will work on adding those :+1:

File: tools/istio-iptables/pkg/capture/run.go [hunk 12]
```diff
@@ -862,51 +864,57 @@ check_loop:
...
+		log.Info("Clean-state detected, no reconciliation needed")
+		return false, false
 	}
 
-	if residueFound && !applyRequired {
-		log.Info("Found compatible iptables rules/chains, no additional changes are needed")
-	} else if residueFound {
-		log.Info("Found residue of old iptables rules/chains, cleanup is needed")
+	if deltaExists && !reconcile {
+		log.Info("Found compatible iptables rules/chains, no reconciliation needed")
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/run.go]: This log line doesn't seem to be correct anymore, should be "Found residue, reconciliation disabled"?

File: tools/istio-iptables/pkg/capture/run.go [hunk 13]
```diff
@@ -846,9 +847,10 @@ func (cfg *IptablesConfigurator) getStateFromSave(data string) map[string]map[st
 	return result
 }
 
-func (cfg *IptablesConfigurator) VerifyRerunStatus(iptVer, ipt6Ver *dep.IptablesVersion) (bool, bool) {
-	applyRequired := false
-	residueFound := false
+func (cfg *IptablesConfigurator) VerifyIptablesState(iptVer, ipt6Ver *dep.IptablesVersion) (bool, bool) {
+	// These variables track the status of iptables installation
+	deltaExists := false // Flag to indicate if a difference is found between expected and current state
+	reconcile := false   // Flag to indicate if a reconciliation via cleanup is needed
```
Comment (bleggett) [inline tools/istio-iptables/pkg/capture/run.go:853]: Why does this function set/return `reconcile`?  I don't think this function needs to return two bools anyway, it can just report `deltaFound true|false` to the caller, which can decide what to do.

**Review by bleggett — COMMENTED** [review]
few comments, looking better, ty!

File: tools/istio-iptables/pkg/capture/run.go (hunk 13 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:853]: Ah yes, you are right. I unintentionally used the deltaFound as the old leftoverFound.
I will change it to convey the proper intention and simplyfy the function return value

Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:853]: On second thought, I believe the function should  return both `residueExists` and `deltaExists`.
Returning only deltaExists wouldn't allow us to distinguish between the first execution and reruns that might require cleanup. This would lead to guardrails+cleanup for the first run, which is not desirable.

"reconcile" on the other end, I agree that should not belong to this function.

File: tools/istio-iptables/pkg/capture/run.go (hunk 12 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go]: My bad here, the reconcile variable was not supposed to be mentioned in VerifyIptablesState().
Code has been adjusted now to mention residueExists and deltaExists

Fast-fail based on reconcile enabled/disabled is here: https://github.com/istio/istio/blob/cad8700a8e6d6cddcdb47eaf0ca61767e045c8af/tools/istio-iptables/pkg/capture/run.go#L931-L933

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 14]
```diff
@@ -170,6 +177,125 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
...
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:180]: Can we add comments? not great to have esoteric parsing logic without explaining what it does

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 15]
```diff
@@ -170,6 +177,125 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
...
+				cmd = []string{"-t", r.table, "-X", r.chain}
+				output = append(output, cmd)
+				chainTableLookupSet.Insert(chainTable)
+			}
+		}
+	}
+	return output
+}
+
+func (rb *IptablesRuleBuilder) buildGuardrails() []*Rule {
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:288]: I don't get this guardrails concept. isn't the point of iptables-save and restore to allow doing transactions? Why do we need to do delete+add when we can just reconcile the state in one go under a lock?

Do other implementations do this?

File: tools/istio-iptables/pkg/capture/run.go [hunk 16]
```diff
@@ -754,38 +756,225 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
 	// --noflush to prevent flushing/deleting previous contents from table
 	return cfg.ext.Run(constants.IPTablesRestore, iptVer, strings.NewReader(data), "--noflush")
 }
 
-func (cfg *IptablesConfigurator) executeCommands(iptVer, ipt6Ver *dep.IptablesVersion) error {
-	if cfg.cfg.RestoreFormat {
-		// Execute iptables-restore
-		if err := cfg.executeIptablesRestoreCommand(iptVer, true); err != nil {
-			return err
+func (cfg *IptablesConfigurator) getStateFromSave(data string) map[string]map[string][]string {
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/capture/run.go:771]: I don't think this is safe. 

There is a rich history in Kubernetes of "parsing iptables-save is broken". https://github.com/kubernetes/kubernetes/issues/112477 and many links from there are good history.

Calico is in a similar boat: https://github.com/projectcalico/calico/blob/23ae58b62765b14aa2c5952b2fc6c40155731a79/felix/iptables/table.go#L141

**Review by howardjohn — CHANGES_REQUESTED** [review]
I feel extremely uncomfortable with this. It seems like we are trying to solve a problem that has been solved in numerous projects in the space already, but doing it in a way they all have decided is broken and moved away from?

I don't think I can approve this unless we either move to a proven-safe (via prior art in another project) way to idempotently update iptables rules, or have a very compelling reason why our needs are different than other projects.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 14 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:180]: :+1: I also asked for more explicit/behaviorally-descriptive unit tests around these mutative funcs, it should be easy to fence these very tightly as there are no OS deps.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 15 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:288]: The guardrails I believe are in place because `iptables-save` output is _not_ relied upon, and we have to go rule-by-rule with `iptables -C` as per https://github.com/istio/istio/pull/50328#issuecomment-2098281216

So, we have to DIY transactions, basically.

File: tools/istio-iptables/pkg/capture/run.go (hunk 16 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/capture/run.go:771]: I agree we can't rely on that, I believe that is why @leosarra moved to `iptables- C` instead in https://github.com/istio/istio/pull/50328#issuecomment-2098281216, but I will let them reply.

Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:771]: Yes, what Calico comment said is correct.
Parsing the rules provided by iptables-save is unsafe because the rules, as represented in the kernel, are different from how they were originally applied (although both representation are obviously equivalent).
In some scenarios the changes can be easily accounted for (e.g: ordering of flags) while in other cases are really hard to take care of (e.g: flags being removed/added/changed, values being represented differently decimal->hexadecimal). For this reason I rely on iptables-save only for two things: obtaining *table and chain of rules

I use that information to decide whatever a delta exists using the following logic:
- every istio chain in the expected state must exists also in the current state
- every istio chain must have the same number of elements in both current and expected state
- every rule in expected state (may it be in istio or non-istio chains) must exists in the current state, the verification is carried over by using "iptables -C" on the rule produced by our iptables builder. No comparison of the parsed rules is performed.

If all 3 conditions are satisfied then the delta is not present and no new tables/chains have to be applied.

Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:769]: I've taken a look at how kubeproxy, Linkerd, and Kuma fares with respect to the reconciliation of iptables and iptables-save usage.

- Kubeproxy: Kubeproxy utilize iptables-save and its nft-equivalent to find chain names in a table, some of the chains are then flushed and deleted. Chains are categorized as either active or stale, with only stale chains being deleted during runtime (https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1412-L1428). Kubeproxy does not perform any rule-level checks or parse the rules. During the proxy's startup, all pre-existing rules are considered stale and are cleaned up before new ones are created (https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L381).

- Linkerd: In the init container, Linkerd uses iptables-save to dump rules and relies on a regex check to determine if any rule that resembles "-A standard_chain ... -j linkerd_chain" exists. If so, jump rules are not recreated. On the other end, existing Linkerd-made chains are flushed and recreated in a single transaction, the operation is atomic as all the rules are contained in the nat table. https://github.com/linkerd/linkerd2-proxy-init/pull/164

- Kuma: By looking at the code it seems that the init container is not idempotent.

Overall it looks like our use of the iptables-save output appears to be similar to that of kubeproxy, with the exception that we also count the number of rules in a chain.
Linkerd is also behaving similarly to the PR although there is no check if compatible iptables are found before performing a cleanup. I don't think there is the need for any guardrails in Linkerd as all the rules resides in one table and it can be updated atomically with one transaction of iptables-restore, this keeps the logic quite simple.

Comment (bleggett) [reply tools/istio-iptables/pkg/capture/run.go:769]: >  I use that information to decide whatever a delta exists using the following logic:
> 
>     every istio chain in the expected state must exists also in the current state
>     every istio chain must have the same number of elements in both current and expected state
>     every rule in expected state (may it be in istio or non-istio chains) must exists in the current state, the verification is carried over by using "iptables -C" on the rule produced by our iptables builder. No comparison of the parsed rules is performed.
> 
> If all 3 conditions are satisfied then the delta is not present and no new tables/chains have to be applied.

Can you put this blurb in the `istio-iptables` README? This logic specifically is important to articulate.

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 14 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:180]: I added comments to the reverse and check logic, same for the higher-level functions verifying the state of iptables.
Fine-grained tests for reverse and check were also added in iptables_builder_test.go

File: tools/istio-iptables/pkg/capture/run.go (hunk 16 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:773]: > Can you put this blurb in the `istio-iptables` README? This logic specifically is important to articulate.
 
 Done
 https://github.com/istio/istio/blob/fb83abec12b2a9449e926fac6541d0f9abba0c23/tools/istio-iptables/pkg/capture/run.go#L832-L841

**Review by bleggett — COMMENTED** [review]
This looks broadly good to me and makes sense. I don't care as much about init container idempotency personally (beside broadly agreeing we have to deal with the hand k8s deals us), but I do generally want a robust/tested `iptables` repair logic - which we don't have ATM, and which this adds.

> I feel extremely uncomfortable with this. It seems like we are trying to solve a problem that has been solved in numerous projects in the space already, but doing it in a way they all have decided is broken and moved away from?
> 
> I don't think I can approve this unless we either move to a proven-safe (via prior art in another project) way to idempotently update iptables rules, or have a very compelling reason why our needs are different than other projects.

I think @leosarra addressed this in https://github.com/istio/istio/pull/50328#discussion_r1610127413 - we are doing it how other projects do it, sometimes a little more carefully.

Short of dropping `istio-iptables` as an internal dependency and using a non-istio impl (which ATM sadly doesn't exist, if it did would be happy to do that - I don't enjoy reinventing the wheel but `istio-iptables` existed long before @leosarra showed up with this PR) we likely aren't going to better this. This is the space we play in.

I'm good on this and the testing around it, and will defer to @howardjohn if he has residual concerns.

**Comment by briansonnenberg** [comment]
@howardjohn What do you think of the current state of this now that the comments have been addressed?  We've been seeing more and more issues cropping up around init-containers rerunning for whatever reason, so idempotency would be a pretty big value-add for users I feel.  I agree we wouldn't want to compromise security for that, but this seems safe from my read through.

File: tools/istio-iptables/pkg/capture/run_test.go [hunk 17]
```diff
@@ -337,6 +351,159 @@ func TestSeparateV4V6(t *testing.T) {
...
+			var stdout, stderr bytes.Buffer
+			if cfg.OwnerGroupsExclude != "" {
+				cfg.OwnerGroupsInclude = "0"
+			}
+			if cfg.OwnerGroupsInclude != "" {
+				cfg.OwnerGroupsInclude = "0"
+			}
+
+			defer func() {
+				// Final Cleanup
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/capture/run_test.go:442]: is this supposed to bundle all of these to all run AFTER all the commonCases iterations?

File: tools/istio-iptables/pkg/cmd/root.go [hunk 18]
```diff
@@ -136,6 +136,12 @@ func bindCmdlineFlags(cfg *config.Config, cmd *cobra.Command) {
 		&cfg.NetworkNamespace)
 
 	flag.BindEnv(fs, constants.CNIMode, "", "Whether to run as CNI plugin.", &cfg.CNIMode)
+
+	flag.BindEnv(fs, constants.NoReconcile, "", "Skip reconciliation of pre-existing and incompatible iptables rules, failing instead if drift detected",
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/cmd/root.go:140]: I am not sure I fully understand. Looks like we did all of this work, and then turned it off. Are there plans to turn it on by default once its more tested? Is it supposed to be on-by-default for VMs?

File: tools/istio-iptables/pkg/capture/run.go (hunk 16 above)
Comment (howardjohn) [reply tools/istio-iptables/pkg/capture/run.go:773]: I don't get why we need buildGuardrails. Can we not just reconcile each chain like kubeproxy?

File: tools/istio-iptables/pkg/capture/run.go [hunk 19]
```diff
@@ -754,38 +754,219 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
+			_, ok := result[table][chain]
+			if !ok {
+				result[table][chain] = []string{}
+			}
+			continue
+		}
+
+		rule := strings.Split(line, " ")
+		ruleChain := ""
+		if chain == "" {
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/capture/run.go:810]: This is broken I think. `chain` is always `""` since L800 is ineffective. This implies we don't have sufficient testing

**Review by howardjohn — COMMENTED** [review]
I do not think it will ever be accepted to have the guard rails solution on Kubernetes.

The problem we are trying to fix is effectively noisy logs. Any solution that adds either downtime or bypass are unacceptable, even if very rare, very short, etc.

File: tools/istio-iptables/pkg/cmd/root.go (hunk 18 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/cmd/root.go:140]: The reconciliation is currently disabled for sidecars and enabled for all other use cases. This decision was made because (1) reconciliation is not really relevant for sidecars, and (2) to adopt a safer approach in rolling out this feature.
In the case of sidecars, we don't need to handle the transition from old rules to new rules because if we were to change the args of istio-iptables, Kubernetes would simply recreate the pod. We just need to have checks to prevent reapply rules if existing rules are found and they are the same as the ones the rerun would apply.
Therefore, the behavior for sidecars that this commit introduced is as follows:

- If no "leftover" rules/chains are found (first run): Create rules/chains as usual. Exit 0.
- If "leftovers" compatible with the planned rules/chains are found: Skip applying new rules/chains and print some logs. Exit 0.
- If incompatible "leftovers" are found: Print logs and exit 1. If reconciliation were enabled, then this scenario would have led to: apply_guardrails -> remove_old_rules -> apply_new_rules -> remove_guardrails.

Scenario 3 would only occur in sidecars if the initial istio-init execution was unsuccessful, leading to incomplete rules/chains (a very niche scenario).

File: tools/istio-iptables/pkg/capture/run_test.go (hunk 17 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run_test.go:442]: No, the cleanup is performed after each iteration has finished.
The defer is inside an anonymous function representing a single subtest and the cleanup will be performed at the end of the subtest so that the next subtest can start from with a clean state.

File: tools/istio-iptables/pkg/capture/run.go (hunk 19 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:810]: This is dead-code left over from previous iterations of the PR.
The chain value at the loop level should be removed because it didn't work as intended. The 'chain' variable is incorrect because having :CHAIN in the iptables-save output doesn't guarantee that all subsequent rules (at least until the next :CHAIN) belong to that chain.

The tests didn't fail because this variable is always ignored in favor of the correct 'ruleChain' variable. I will clean up the variable and remove the useless if condition.

File: tools/istio-iptables/pkg/capture/run.go (hunk 16 above)
Comment (bleggett) [reply tools/istio-iptables/pkg/capture/run.go:773]: What if the application is actively sending packets, we reconcile one chain, but the others are in a broken state that allows packets to escape?

We can't guarantee they won't without guardrails. We either risk packets escaping (a non-negotiable) or we actively set up packet blocks until we know the state is good). Which gets back to the "you can drop packets or let them escape, pick one" problem.


K8S doesn't reconcile or repair rules at all, but they also don't have the inherent dependency on rules existing within running pods that we do.

Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:773]: Just to add to what Ben said, since I was in process of writing my response.

In theory, I could reconcile each chain by performing delete and apply operations in the same iptables-restore pass. However, this doesn't necessarily eliminate the need for guardrails due to the limited atomicity property of iptables-restore.

Guardrails are not required in two circumstances:
- When all rules related to a specific feature (e.g., redirection) occur in the same table (e.g., nat).
Since iptables-restore performs an atomic transaction at the chain level, you could transition from the old state to the new one without risking unintended behavior.
Linkerd falls into this category as it only modifies one table.
I suspect this also applies to kube-proxy, which tinkers with nat and filter tables. I think its features are self-contained in one table each. I will have to check the code to have a better understanding of this.
- When using nftables, which can guarantee atomicity regardless of how many tables are manipulated in one pass. Note that the [k8s wrapper for nftables](https://github.com/kubernetes-sigs/knftables) doesn't utilize this capability, as it performs one transaction for each chain (similar atomicity guarantee as iptables-restore). 

For the first case, given the number of Istio rules and their configurability, I wasn't comfortable assuming that all Istio rules could be reconciled safely with chain-level atomicity guarantees (especially for future upgrade scenarios). Hence, I felt guardrails were necessary.
I believe switching to nftables would be beneficial, but that's a very long-term goal that comes with its own fair share of challenges.

File: tools/istio-iptables/pkg/capture/run.go (hunk 19 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go]: Removed

**Comment by leosarra** [comment]
Commits have been squashed into one for simplicity's sake.

**As discussed in the latest WG meeting:**
- The reconcile option is off by default, so sidecars and VM deployments will not use it.
- Reconcile is now opt-in and is controlled by the "--reconcile" flag.
- Idempotency is still ensured, as the apply step is skipped if compatible iptables rules/chains are found. An error is raised if incompatible iptables are found.

As a consequence Sidecars will be able to rerun unless the first run led to an incomplete or failed state.
VMs will anyway never trigger reconciliation, as the systemd service already triggers a cleanup every time the Istio service is restarted or stopped.

**To-do in a separate commit:**
- Enable the --reconcile option for Istio CNI. The necessary components are made available by this commit, but CNI has its own executeCommands(), which needs to be adjusted.
I will start working on it after this commit.
- Evaluate if istio-clean iptables tools can be removed as it is now redundant with the --cleanup-only option that automatically computes which rules/chains needs to be removed

**Comment by briansonnenberg** [comment]
@howardjohn @bleggett @leosarra Can we merge this?

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 20]
```diff
@@ -172,6 +179,135 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
 	return output
 }
 
+func reverseRules(rules []*Rule) []*Rule {
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:182]: can we add comments to the function? Given a function signature `reverseRules(rules []*Rule) []*Rule` without comments, I would assume it reverse the order of the rules -- which is not what it does at all

**Comment by howardjohn** [comment]
I don't think what is said in https://github.com/istio/istio/pull/50328#issuecomment-2260706361 is implemented yet

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 20 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:187]: Added comments to both reverseRules() and checkRules()

**Comment by leosarra** [comment]
> I don't think what is said in [#50328 (comment)](https://github.com/istio/istio/pull/50328#issuecomment-2260706361) is implemented yet

All the changes mentioned in the comment are already part of the PR

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go [hunk 21]
```diff
@@ -172,6 +179,144 @@ func (rb *IptablesRuleBuilder) buildRules(rules []*Rule) [][]string {
 	return output
 }
 
+// reverseRules generates the minimal set of rules that are necessary to reverse the changes made by the input rules.
+// The function transforms -A/--append and -I/--insert flags into -D/--delete flags while preserving the
+// structure of other parameters.
+// Non-jump rules in ISTIO_* chains are skipped as these chains will be flushed, but jump rules are retained to ensure proper reversal.
+// Note: This function does not support converting -D/--delete flags back to -A/-I flags.
+func reverseRules(rules []*Rule) []*Rule {
```
Comment (bleggett) [inline tools/istio-iptables/pkg/builder/iptables_builder_impl.go:187]:
```suggestion
func undoRules(rules []*Rule) []*Rule {
```
or 

```suggestion
func buildUndoRules(rules []*Rule) []*Rule {
```


(very ignorable nit/suggestion in light of the above + comments that this is a "one way reverse")

**Review by bleggett — APPROVED** [review]
This LGTM in current state. 

The logic makes sense, the feature is opt-in, and we have tests.

File: tools/istio-iptables/pkg/capture/run.go [hunk 22]
```diff
@@ -752,38 +752,156 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
+			_ = cfg.executeIptablesCommands(ipt6Ver, guardrailsCleanup)
 		}
-		// Execute ip6tables commands
-		if err := cfg.executeIptablesCommands(ipt6Ver, cfg.ruleBuilder.BuildV6()); err != nil {
-			return err
+	}()
+
+	residueExists, deltaExists := cfg.VerifyIptablesState(iptVer, ipt6Ver)
+	if residueExists && deltaExists && !cfg.cfg.Reconcile {
+		return fmt.Errorf("reconcile is needed but no-reconcile flag is set. Can't recover from this state")
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/capture/run.go:859]: To retain the old behavior, we should log this as a warning but attempt to execute as well. This ensures if there is logic in VerifyIptablesState that is overly restrictive it does not cause issues for users. Which is fairly plausible since we are doing `iptables-save` parsing which is, historically, hard to do right.

File: releasenotes/notes/50328.yaml [hunk 23]
```diff
@@ -0,0 +1,18 @@
...
+releaseNotes:
+- |
+  **Fixed** Allow for re-executions of istio-iptables by skipping apply step if existing rules are compatible.
+---
+apiVersion: release-notes/v2
+kind: feature
+area: networking
+releaseNotes:
+- |
+  **Added** `--cleanup-only` option to istio-iptables to perform a cleanup of chains/rules without creating new ones.
```
Comment (howardjohn) [inline releasenotes/notes/50328.yaml:16]: Why do we have `istio-clean-iptables` and `istio-iptables --cleanup-only`? What is the difference?

File: tools/istio-iptables/pkg/capture/run.go (hunk 22 above)
Comment (howardjohn) [reply tools/istio-iptables/pkg/capture/run.go:859]: Or maybe even just skip VerifyIptablesState entirely in this case. That way we have the exact same behavior as before

File: tools/istio-iptables/pkg/capture/run.go [hunk 24]
```diff
@@ -752,38 +752,156 @@ func (cfg *IptablesConfigurator) executeIptablesCommands(iptVer *dep.IptablesVer
...
+			}
+		}
+		// Remove old iptables
+		log.Info("Performing cleanup of existing iptables")
+		cfg.tryExecuteIptablesCommands(iptVer, cfg.ruleBuilder.BuildCleanupV4())
+		cfg.tryExecuteIptablesCommands(ipt6Ver, cfg.ruleBuilder.BuildCleanupV6())
+	}
+
+	// Apply Step
+	if deltaExists && !cfg.cfg.CleanupOnly {
```
Comment (howardjohn) [inline tools/istio-iptables/pkg/capture/run.go:883]: Can we keep the backwards compatible behavior of always running it?

**Review by howardjohn — COMMENTED** [review]
Sorry about my previous comment - I maybe somehow got a stale commit I was reviewing or something

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 21 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go:187]: I like undoRules(). I will update the name/comments/logs based on that

File: releasenotes/notes/50328.yaml (hunk 23 above)
Comment (leosarra) [reply releasenotes/notes/50328.yaml:16]: Both utilities clean iptables, but their approaches differ.
The `istio-clean-iptables` utility (used only in the VM service as far as I know), come with its own CLI that has only a subset of the arguments of the `istio-iptables` args.
On top of that, the `istio-clean-iptables` cmd relies on a set of hardcoded rules and chains to perform the cleanup. This approach requires attention from developers that everything that is added in istio-iptables is also properly cleaned by `istio-clean-iptables`. This creates the risk that clean-iptables and istio-iptables will diverge over time, which is enabled by the fact that the effectivess of clean-iptables is not tested.

For example I see that https://github.com/istio/istio/pull/41431 added the cleaning of non-jump rules in non-Istio chains which were previously missing in istio-clean-iptables.

In contrast, istio-iptables with the `--cleanup-only` option performs the cleaning by reversing/undoing the rules that istio-iptables would have applied if the cleanup flag was not used.
The rules are not hardcoded and they are generated at runtime by the reverse function, also `--cleanup-only` is tested to make sure that the resulting state is clean.
This "dynamic" approach allows to easily support all possible configurations.

I feel that it would be great to deprecate the `istio-clean-iptables` in the future and update the VM to just use the new cleanup flag.

File: tools/istio-iptables/pkg/capture/run.go (hunk 22 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:859]: I'll update the code to raise a warning but still attempt the apply step as before. I will do it tomorrow as it is getting late here :)

However, there will be a small tradeoff by having the old behavior.
There will be an issue can be seen with this example:

```
*raw
iptables -A OUTPUT -dport 123 -m owner --uid-owner 0 ...etc...
*nat
iptables -N ISTIO
iptables -A INPUT --jump ISTIO
```

In this scenario, even though the rerun fails due to a pre-existing ISTIO chain, iptables-restore will still apply changes to the *raw table completely (due to its partial atomicity guarantee). This results in rules in the raw table being applied repeatedly with each rerun.

For this issue to occur, our iptables-restore input must meet two conditions:
1. Changes to one table consist only of appending/inserting rules to default chains.
2. These changes are placed in the input before any other table changes that create new chains.

I don't think this is a problem right now as we don't satisfy these conditions.
Right now, it makes more sense to be more backwards compatible, but we may need to reevaluate this in the future if the conditions for this issue to show up ends up being satisfied.

File: releasenotes/notes/50328.yaml (hunk 23 above)
Comment (bleggett) [reply releasenotes/notes/50328.yaml:16]: > I feel that it would be great to deprecate the istio-clean-iptables in the future and update the VM to just use the new cleanup flag.

+ 1 on that, we got a bug against `istio-clean-iptables` recently anyway that this would have fixed: https://github.com/istio/istio/issues/52835

File: tools/istio-iptables/pkg/builder/iptables_builder_impl.go (hunk 21 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/builder/iptables_builder_impl.go]: Done

File: tools/istio-iptables/pkg/capture/run.go (hunk 22 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go]: Done. I changed the behavior to perform the apply step even if reconciliation is disabled and the current iptables state is "tainted"

File: tools/istio-iptables/pkg/capture/run.go (hunk 24 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:883]: Done

Comment (howardjohn) [reply tools/istio-iptables/pkg/capture/run.go:883]: This is still not done, its skipping the run when deltaExists == false, which may be a false positive?

**Review by howardjohn — APPROVED** [review]
One small comment but don't want to hold this up more, can we fix in a followup?

**Comment by howardjohn** [comment]
Thanks for all the efforts here!

File: tools/istio-iptables/pkg/capture/run.go (hunk 24 above)
Comment (leosarra) [reply tools/istio-iptables/pkg/capture/run.go:883]: Sorry, I thought the comment was related to "fail if no reconciliation and pre-existing iptables are found" and marked it as solved.

The"skip if delta exists" is intended to prevent reruns when all iptables are detected as already in place, such as in istio-init reruns. I cannot force a rerun exactly as it was before this commit because that behavior is problematic.
Perhaps, if we detect no delta, we could still rerun the apply step but ignore the error that will likely be raised. While not very clean, this approach would be more backward compatible. WTDY?

On the other end, a false negative on deltaExists would be difficult because it would require meeting two conditions:
- Having the same number of rules in every chain between the "expected state" and "current state"
- Having no failures in any of the "iptables -C ..." commands that are executed
If there's an issue in the parser, it's more likely to lead to missfire on reconciliation (residueExists && deltaExists) rather than this skip.

Comment (howardjohn) [reply tools/istio-iptables/pkg/capture/run.go:883]: We can keep it on by default but at least should have a feature flag to turn it off, since this is very tricky behavior. We have ~never made an iptables change that didn't have a bug in it in some obscure environment, so probably there is some weird edge cases that this will matter. Having a way to opt-out of that would be a good safety mechanism

**Comment by leosarra** [comment]
Thank you, @bleggett and @howardjohn, for all the feedback and time you have invested in the review. I really appreciate it :)
Tomorrow, I will work on the remaining items we discussed above and add them in a separate, smaller PR.
