### PR TITLE
nds: fix missing IP addresses in headless nametable entries when pods have multiple IPs

### LINKED ISSUE #58397: NDS nametable missing multi-family Pod IPs
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When you have a headless service and Istio NDS builds the NameTable, it does not properly account for the scenario where there are multiple instances with different IPs for the same pod in the same cluster.

See the dump from /debug/ndsz, and note how simple-internal-httpd-server-0.simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local only provides a single IP for the pod (statefulset, even though it has multiple addresses.

```
{
    "configs": [
        {
            "@type": "type.googleapis.com/istio.networking.nds.v1.NameTable",
            "table": {
                "httpbin.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42:1::f91a",
                        "10.105.116.27"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "httpbin",
                    "namespace": "istio-mt-esarleo-0"
                },
                "istio-egressgateway.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "10.107.38.157"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istio-egressgateway",
                    "namespace": "istio-mt-esarleo-0"
                },
                "istio-ingressgateway.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42:1::21ce"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istio-ingressgateway",
                    "namespace": "istio-mt-esarleo-0"
                },
                "istiod.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "10.108.47.127"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istiod",
                    "namespace": "istio-mt-esarleo-0"
                },
                "simple-internal-httpd-server-0.simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "10.244.0.47"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "simple-internal-httpd-server-0.simple-internal-httpd-server-headless",
                    "namespace": "istio-mt-esarleo-0"
                },
                "simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42::2f",
                        "10.244.0.47"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "simple-internal-httpd-server-headless",
                    "namespace": "istio-mt-esarleo-0"
                },
                "sleep.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42:1::eaf6"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "sleep",
                    "namespace": "istio-mt-esarleo-0"
                }
            }
        }
    ]
}
```

### Version

```Text
control plane version: 1.28.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosarra**
**Please provide a description of this PR:**
Fixes #58397

In case we have multiple endpoints for a specific pod, the old implementation always preferred the last one when creating the headless entries in the nametable. This led to only the last endpoint IP making into the table, the impact was quite noticeable when it comes to DualStack support.
With these changes the following will happen:
- When creating pod entries for headless svc, multiple IPs can be returned for the same headless nametable entry.
- If there are multiple IPs coming from local and remote clusters for the same pod host, local is preferred for pod entries.

### CODE REVIEW

**Comment by leosarra** [comment]
istiod /debug/ndsz output after the changes (note the `simple-internal-httpd-server-0.simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local` entry when compared to the output pasted in the original issue):


```
{
    "configs": [
        {
            "@type": "type.googleapis.com/istio.networking.nds.v1.NameTable",
            "table": {
                "istio-egressgateway.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "10.103.17.86"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istio-egressgateway",
                    "namespace": "istio-mt-esarleo-0"
                },
                "istio-ingressgateway.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42:1::2b9e"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istio-ingressgateway",
                    "namespace": "istio-mt-esarleo-0"
                },
                "istiod.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "10.97.28.17"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "istiod",
                    "namespace": "istio-mt-esarleo-0"
                },
                "simple-internal-httpd-server-0.simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42::5c",
                        "10.244.0.92"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "simple-internal-httpd-server-0.simple-internal-httpd-server-headless",
                    "namespace": "istio-mt-esarleo-0"
                },
                "simple-internal-httpd-server-headless.istio-mt-esarleo-0.svc.cluster.local": {
                    "ips": [
                        "2001:db8:42::5c",
                        "10.244.0.92"
                    ],
                    "registry": "Kubernetes",
                    "shortname": "simple-internal-httpd-server-headless",
                    "namespace": "istio-mt-esarleo-0"
                }
            }
        }
    ]
}
```

File: pkg/dns/server/name_table.go [hunk 1]
```diff
@@ -119,6 +120,28 @@ func BuildNameTable(cfg Config) *dnsProto.NameTable {
 						// TODO: should we skip the node's own IP like we do in listener?
 						addressList = append(addressList, instance.Addresses...)
 					}
+					// Write local cluster entries first
```
Comment (leosarra) [inline pkg/dns/server/name_table.go:119]: In theory we could let the entry list all addresses, with local ones first.

I am not sure if the old behavior of returning the local address first came from a limitation at the time, when the nametable did not support multiple IPs and preferring local was simply the obvious choice, or if there was some other reason behind it.
For now, I played it safe and made the code return local addresses over the remote ones when they are available.

File: pkg/dns/server/name_table.go [hunk 2]
```diff
@@ -62,6 +62,12 @@ func BuildNameTable(cfg Config) *dnsProto.NameTable {
 				// The IP will be unspecified here if its headless service or if the auto
 				// IP allocation logic for service entry was unable to allocate an IP.
 				if svc.Resolution == model.Passthrough && len(svc.Ports) > 0 {
+					localAddresses := make(map[string][]string)
+					remoteAddresses := make(map[string][]string)
+					hostMetadata := make(map[string]struct {
```
Comment (ramaraochavali) [inline pkg/dns/server/name_table.go]: Can we use NamespacedName or define a new struct and use it here and below?

File: pkg/dns/server/name_table.go [hunk 3]
```diff
@@ -119,6 +120,28 @@ func BuildNameTable(cfg Config) *dnsProto.NameTable {
...
+						out.Table[host] = &dnsProto.NameTable_NameInfo{
+							Ips:       ips,
+							Registry:  string(svc.Attributes.ServiceRegistry),
+							Namespace: metadata.namespace,
+							Shortname: metadata.shortName,
+						}
+					}
+					// Write remote cluster entries only if local doesn't exist
+					for host, ips := range remoteAddresses {
+						if _, exists := out.Table[host]; !exists {
```
Comment (ramaraochavali) [inline pkg/dns/server/name_table.go]: Can we move this outside of this loop and only iterate remoteAddresses if local is not added i.e. out.Table[host] does not exist?

File: pkg/dns/server/name_table.go (hunk 2 above)
Comment (leosarra) [reply pkg/dns/server/name_table.go]: Sure makes sense, updated with NamespacedName.

File: pkg/dns/server/name_table.go (hunk 3 above)
Comment (leosarra) [reply pkg/dns/server/name_table.go]: If you mean moving the out.Table[host] check outside the loop, I can’t do that because each iteration checks a different host.
On the other hand, I noticed that instead of the output table (out.Table[host]), I can use the smaller localAddress map, but the efficiency gain is peanuts.
