### PR TITLE
Fix windows tar ext name

### LINKED ISSUE #34081: Upgrade 1.9.2 to 1.10.2 failed because script's URL is incorrect
I have ISTIO 1.9.2 installed on windows 10. I have downloaded 1.10.2 from github and tried to upgrade executing the commands below.

```
PS C:\> istioctl version   
client version: 1.10.2
control plane version: 1.9.2
data plane version: 1.9.2 (2 proxies)

PS C:\> istioctl x precheck
✔ No issues found when checking the cluster. Istio is safe to install or upgrade!
  To get started, check out https://istio.io/latest/docs/setup/getting-started/

PS C:\> istioctl upgrade --set profile=default -y --set meshConfig.accessLogFile="/dev/stdout"
2021-07-15T13:58:45.526648Z     info    proto: tag has too few fields: "-"
Control Plane - istiod pod - istiod-db9f9f86-ppfsq - version: 1.9.2
Control Plane - istio-ingressgateway pod - istio-ingressgateway-7cc49dcd99-757t7 - version: 1.9.2

Upgrade version check passed: 1.9.2 -> 1.10.2.

2021-07-15T13:58:46.376193Z     info    Error: failed to generate Istio configs from file [] for the current version: 1.9.2, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.9.2/istio-1.9.2-windows.zip : 404 Not Found

Error: failed to generate Istio configs from file [] for the current version: 1.9.2, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.9.2/istio-1.9.2-windows.zip : 404 Not Found
```

Script tries to download "istio-1.9.2-windows.zip" but the correct file on the web is "istio-1.9.2-win.zip"

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix https://github.com/istio/istio/issues/34081

[X] Installation

### CODE REVIEW

File: operator/cmd/mesh/upgrade.go [hunk 1]
```diff
@@ -273,7 +273,7 @@ func platformBasedTar() (tarExtension string) {
 	case "linux":
 		tarExtension = runtime.GOOS + "-" + runtime.GOARCH + ".tar.gz"
 	case "windows":
-		tarExtension = runtime.GOOS + ".zip"
+		tarExtension = "win.zip"
```
Comment (morvencao) [inline operator/cmd/mesh/upgrade.go:276]: How do we the `fetchUrl` in the original issue, can we share the same constant?

Comment (howardjohn) [reply operator/cmd/mesh/upgrade.go:276]: Its in istio/release-builder, so not easy to share

**Review by howardjohn — APPROVED** [review]
