### PR TITLE
Mixer: delete unix socket before calling listen

### LINKED ISSUE #7050: Telemetry fails to restart
This morning my cluster had nothing in grafana, traced it back to telemetry job.

Logs from mixer:

```
 Mixer started with
MaxMessageSize: 1048576
MaxConcurrentStreams: 1024
APIWorkerPoolSize: 1024
AdapterWorkerPoolSize: 1024
APIPort: 9091
APIAddress: unix:///sock/mixer.socket
MonitoringPort: 9093
EnableProfiling: true
SingleThreaded: false
NumCheckCacheEntries: 1500000
ConfigStoreURL: k8s://
ConfigDefaultNamespace: istio-system
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"default:info", logCallers:"", stackTraceLevels:"default:none"}
TracingOptions: tracing.Options{ZipkinURL:"http://zipkin:9411/api/v1/spans", JaegerURL:"", LogTraceSpans:false}
IntrospectionOptions: ctrlz.Options{Port:0x2694, Address:"127.0.0.1"}
Unable to initialize Mixer: unable to listen: listen unix /sock/mixer.socket: bind: address already in use 
```

kublectl describe:

```
 Mixer started with
MaxMessageSize: 1048576
MaxConcurrentStreams: 1024
APIWorkerPoolSize: 1024
AdapterWorkerPoolSize: 1024
APIPort: 9091
APIAddress: unix:///sock/mixer.socket
MonitoringPort: 9093
EnableProfiling: true
SingleThreaded: false
NumCheckCacheEntries: 1500000
ConfigStoreURL: k8s://
ConfigDefaultNamespace: istio-system
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"default:info", logCallers:"", stackTraceLevels:"default:none"}
TracingOptions: tracing.Options{ZipkinURL:"http://zipkin:9411/api/v1/spans", JaegerURL:"", LogTraceSpans:false}
IntrospectionOptions: ctrlz.Options{Port:0x2694, Address:"127.0.0.1"}
Unable to initialize Mixer: unable to listen: listen unix /sock/mixer.socket: bind: address already in use 
```

### PR DESCRIPTION
**Pull request by mandarjog**
Mixer listens on a unix socket. If Mixer is restarted, if the UDS file is not removed mixer fails to start with ```Unable to initialize Mixer: unable to listen: listen unix /sock/mixer.socket: bind: address already in use```
Fixes #7050

### CODE REVIEW

**Comment by mandarjog** [comment]
Addresses #7050

**Comment by costinm** [comment]
A bit ironic that code coverage is at 100% yet it seems to leak, OOM and doesn't restart :-)

**Comment by costinm** [comment]
Merging to unblock testing - I think test can be done in separate PR.

File: mixer/pkg/server/server.go [hunk 1]
```diff
@@ -26,6 +26,8 @@ import (
 	ot "github.com/opentracing/opentracing-go"
 	"google.golang.org/grpc"
 
+	"os"
```
Comment (douglas-reid) [inline mixer/pkg/server/server.go]: this should have caused linter issues, no?

Comment (kyessenov) [reply mixer/pkg/server/server.go]: Linter is completely broken...

**Comment by mandarjog** [comment]
Doug, it does seem odd. ⭕️ Ci lint passed though.

**Comment by kyessenov** [comment]
@geeknoid to get a unit test for this, we would need to either stub out syscalls (quite a bit of work), or create physical UDS sockets in a test which does not work on windows.

**Comment by geeknoid** [comment]
@sebastienvas How come a PR that regresses code coverage can be checked in? I thought we prevented this systematically?

@costinm Yes, 100% code coverage doesn't imply 100% defect free. But <100% code coverage implies ~100% there are defects.

@kyessenov A unit test can easily be constructor to verify that the new code path doesn't lead to failures. This can be done in a platform-independent way. Verifying that the semantic of this new code does what it should requires an integration test, which is a separable concern.

This failure mode seems to indicate a substantial flaw in the execution environment. The fact it's possible for one instance of the process to leave turd behind that prevent a subsequent instance of the process from running is broken. Is the solution to fix it in Mixer in this way, or should be this addressed outside of Mixer?

**Comment by kyessenov** [comment]
FWIW some very common code such as syslogd perform the same trick of
deleting UDS file before binding to it.

**Comment by mandarjog** [comment]
This is the standard way to deal with UDS, I will add unit test to bring up coverage.
