### PR TITLE
Set alpnOverride depending on TLS Mode

### LINKED ISSUE #40680: ALPN filter incorrectly applies to non-Istio TLS traffic
### Bug Description

setup:
- ssl terminating on istio gateway
- backend app listens on https with istio sidecar injected
- destination rule has tls mode as SIMPLE

curl accessing gateway's https port:

1.  with 1.13.x
- works
2. with 1.14.x
- fails with `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error
- works - when mTLS is disabled in peer authentication
- works - when istio sidecar isnt injected to the app

### Version

```prose
$ istioctl version
client version: 1.14.1
istiod version: 1.13.5
istiod version: 1.14.1
data plane version: 1.14.1 (1 proxies)

$ k version --short
Client Version: v1.23.5
Server Version: v1.21.11
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

### Additional Information

a very basic [golang server](https://github.com/deepakdeore2004/istio-bug-1-14/blob/main/server.go) is used to reproduce the problem

how to reproduce:

- install istio 1.13 and 1.14 as canary revision
- install `istioctl` (1.13.x or 1.14.x) on local and make it available in PATH to deploy gateway
- clone git@github.com:deepakdeore2004/istio-bug-1-14.git and change directory to k8
- ./run.sh, provide istio revision to deploy gw and app with istio sidecar
- curl -k https://gateway-lb
- delete the namespace and repeat same test with another revision

in 1.14, disabling mTLS with peer authentication OR removing istio sidecar from the app works fine

alpn has some difference with the version

1.13:

1.14:

tcpdump is installed on app pod so kubectl sniff can be used like this:
```
k sniff -n test-1-13-5-20220827 test-http-server-8080-and-8443-746f8679f5-d6sgl
```

### PR DESCRIPTION
**Pull request by ksubrmnn**
**Please provide a description of this PR:**

By setting tls.mode SIMPLE, the user is signaling that they want to opt out of mTLS, Istio managed or otherwise. Since ALPN rewrite exists solely for the purpose of starting Istio mTLS, it violates the user’s intent to perform said rewrite.

This PR checks if the TLS mode is simple and then adds a field to the filter metadata to indicate whether the proxy should proceed with the alpn header rewrite.

Partially fixes #40680

Istio/proxy change: https://github.com/istio/proxy/pull/4783

### CODE REVIEW

**Comment by howardjohn** [comment]
should add the test in https://github.com/istio/istio/pull/42902

**Comment by ksubrmnn** [comment]
> was there some istio/proxy change to enable this?



> #42902

Updated PR description to reflect that istio/proxy changes are to follow

**Comment by ksubrmnn** [comment]
> #42902

I've included just a unit test for this change to verify that the filtermetada is set correctly. I will follow up with integration testing after the proxy changes.

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go [hunk 1]
```diff
@@ -556,7 +586,27 @@ func TestApplyDestinationRule(t *testing.T) {
...
 
+			// Validate that alpn_override is configured on cluster correctly.
+			if tt.destRule != nil && tt.destRule.TrafficPolicy != nil {
+				md := tt.cluster.Metadata
+				istio := md.FilterMetadata[util.IstioMetadataKey]
+				if alpnOverride, found := istio.Fields["alpn_override"]; found {
+					if tt.destRule.TrafficPolicy.Tls.Mode == networking.ClientTLSSettings_SIMPLE {
+						if alpnOverride.GetStringValue() == "true" {
+							t.Errorf("alpn_override should be false for TLS mode SIMPLE")
+						} else if alpnOverride.GetStringValue() != "false" {
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:599]: This should just be an else; if for whatever reason another value is added (or alpn_override becomes a full-fleged enum field), we don't want to silently pass

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go [hunk 2]
```diff
@@ -556,7 +586,27 @@ func TestApplyDestinationRule(t *testing.T) {
...
+							t.Errorf("unexpected value for alpn_override: %s", alpnOverride.GetStringValue())
+						}
+					} else {
+						if alpnOverride.GetStringValue() == "false" {
+							t.Errorf("alpn_override should be true when TLS mode is not SIMPLE")
+						} else if alpnOverride.GetStringValue() != "true" {
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:605]: Same as above; should just be an else

File: pilot/pkg/networking/util/util.go [hunk 3]
```diff
@@ -435,6 +435,24 @@ func AddSubsetToMetadata(md *core.Metadata, subset string) {
...
+// AddALPNOverrideToMetadata adds whether the the ALPN prefix should be added to the header
+// to the given core.Metadata struct, if metadata is not initialized, build a new metadata.
+func AddALPNOverrideToMetadata(metadata *core.Metadata, alpnOverride bool) {
+	if metadata == nil {
+		metadata = &core.Metadata{
+			FilterMetadata: map[string]*structpb.Struct{},
+		}
+	}
+
+	if istioMeta, ok := metadata.FilterMetadata[IstioMetadataKey]; ok {
```
Comment (keithmattix) [inline pilot/pkg/networking/util/util.go:447]: If `IstioMetadataKey` doesn't exist in the map, we probably want to create it right? As written, the alpn_override wouldn't be added

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go (hunk 1 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:599]: The following clause checks to see if it's a value other than true or false

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go (hunk 2 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go]: I reworked the if and removed the else entirely

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go (hunk 1 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go]: I reworked the if and removed the else entirely

File: pilot/pkg/networking/util/util.go (hunk 3 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/util/util.go]: Added

**Review by keithmattix — APPROVED** [review]
LGTM

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go [hunk 4]
```diff
@@ -294,6 +294,13 @@ func (cb *ClusterBuilder) applyDestinationRule(mc *MutableCluster, clusterMode C
 
 	if destRule != nil {
 		mc.cluster.Metadata = util.AddConfigInfoMetadata(mc.cluster.Metadata, destRule.Meta)
+
+		// ALPN header rewrite starts mTLS. Skip if TLS mode is SIMPLE.
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder.go:298]: I think we probably want MUTUAL as well?

File: pilot/pkg/networking/util/util.go [hunk 5]
```diff
@@ -435,6 +435,30 @@ func AddSubsetToMetadata(md *core.Metadata, subset string) {
 	}
 }
 
+// AddALPNOverrideToMetadata adds whether the the ALPN prefix should be added to the header
+// to the given core.Metadata struct, if metadata is not initialized, build a new metadata.
+func AddALPNOverrideToMetadata(metadata *core.Metadata, alpnOverride bool) *core.Metadata {
```
Comment (howardjohn) [inline pilot/pkg/networking/util/util.go:440]: can we just only include the metadata if alpnOverride is true (or false, I am not sure which one means "do not set it")?

Its not free to add the metadata, actually surprisingly high cost

**Review by howardjohn — COMMENTED** [review]
Overall looks good, a few small comments. Its a bit hard to properly review without the istio/proxy changes though, ideally we merge those first.

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 4 above)
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:298]: FWIW, the original design doc was scoped to SIMPLE. MUTUAL probably makes sense semantically, but what's the existing mechanism for a tlsMode MUTUAL to indicate that it expects a client cert (outside of ALPN)? My concern is that it only works because we don't remove the alpn rewrite today

**Comment by howardjohn** [comment]
MUTUAL aspect is a TLS message: ClientCertificateType
https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.4

It should not be tied to ALPN

**Comment by jewertow** [comment]
Hey @ksubrmnn, are you going to continue to work on this PR? I am interested in this change and I wonder if it will end up in master.

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go [hunk 6]
```diff
@@ -294,6 +294,13 @@ func (cb *ClusterBuilder) applyDestinationRule(mc *MutableCluster, clusterMode C
...
+		trafficPolicy := destinationRule.GetTrafficPolicy()
```
[the remark this answers is not in the document]
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:299]: what is the difference between `destinationRule.GetTrafficPolicy()` and `opts.policy`?

[the remark this answers is not in the document]
Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:299]: It is the result of MergeTrafficPolicy which does some merging logic

File: pilot/pkg/networking/util/util.go (hunk 5 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/util/util.go:440]: Added return metadata if alpnOverride is true

**Comment by ksubrmnn** [comment]
@jewertow Yes I'm working on this PR. Had some delay with proxy changes, but you can find them at https://github.com/istio/proxy/pull/4783

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: for applyTrafficPolicy, would we want to modify the opts.mutable.cluster.Metadata. If so, then we need to modify the return type

**Comment by ksubrmnn** [comment]
WIP tests will fail since still working on applyTrafficPolicy part

File: pilot/pkg/networking/util/util.go (hunk 5 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/util/util.go:440]: added logic to configureALPNOverride

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go [hunk 7]
```diff
@@ -1432,3 +1441,14 @@ func (cb *ClusterBuilder) buildExternalSDSCluster(addr string) *cluster.Cluster
 	}
 	return c
 }
+
+// configureALPNOverride determines whether alpn_override should be added to metadata
+func configureALPNOverride(tlsMode networking.ClientTLSSettings_TLSmode, md *core.Metadata) *core.Metadata {
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder.go:1446]: I think you added a comment somewhere on the issue, but do you even need to return anything here since you're passing a pointer to md? In fact `AddALPNOverrideToMetadata` probably doesn't need a return value either if you're manipulating a pointer value

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go [hunk 8]
```diff
@@ -479,6 +479,51 @@ func TestApplyDestinationRule(t *testing.T) {
...
+			destRule: &networking.DestinationRule{
+				Host: "foo.default.svc.cluster.local",
+				TrafficPolicy: &networking.TrafficPolicy{
+					Tls: &networking.ClientTLSSettings{Mode: networking.ClientTLSSettings_MUTUAL},
+				},
+			},
+			expectedSubsetClusters: []*cluster.Cluster{},
+		},
+		{
+			name:        "destination rule with tls mode ISTIO_MUTUAL",
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:513]: May as well test DISABLE too right?

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go [hunk 9]
```diff
@@ -556,6 +601,42 @@ func TestApplyDestinationRule(t *testing.T) {
...
+							t.Errorf("alpn_override:%s tlsMode:%s, should be false for either TLS mode SIMPLE or MUTUAL", alpnOverride, tlsMode)
+						}
+					} else {
+						t.Errorf("alpn_override metadata should be written for either TLS mode SIMPLE or MUTUAL")
+					}
+				} else {
+					// If TLS settings are not found, alpn_override metadata should not be written
+					md := tt.cluster.Metadata
+					istio, ok := md.FilterMetadata[util.IstioMetadataKey]
+					t.Logf("istiofound:%t", ok)
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:630]: nit: you probably don't want this in the final version of your tests

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go [hunk 10]
```diff
@@ -556,6 +601,42 @@ func TestApplyDestinationRule(t *testing.T) {
...
+					if ok {
+						alpnOverride, found := istio.Fields["alpn_override"]
```
Comment (keithmattix) [inline pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:632]: I'd prefer to see this extracted to a constant somewhere to reduce the chance of it being mistyped

**Review by keithmattix — CHANGES_REQUESTED** [review]

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 7 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:1446]: Yes you do because if the metadata is nil, we want to return a new metadata with the headers. That's the only reason. Empty metadata can be modified and set, but not nil.

Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:1446]: Then why pass a pointer in the first place?

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 4 above)
Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: It is part of TLS spec, it sends the "request client cert" bit during the tls handshake.

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: Why do we need to modify any return ttpes? Can't we just just set `opts.mutable.cluster.metadata = util.AddALPNOverrideToMetadata(mc.cluster.Metadata, alpnOverride)`?

[the remark this answers is not in the document]
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: In case someone passes in nil opts

[the remark this answers is not in the document]
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: In case `opts.mutable.cluster.metadata` is nil

File: pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go (hunk 8 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go:514]: This doesn't offer any additional test coverage, but I can add it if you want.

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go (hunk 7 above)
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:1457]: Isn't that less memory on the stack?

Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go:1457]: That's how it's stored in the mutable cluster.

**Comment by ksubrmnn** [comment]
@howardjohn I've removed the changes to apply traffic policy. The PR was getting to be a bit large and unwieldy for me. I prefer to add those changes in a followup

File: pilot/pkg/networking/core/v1alpha3/cluster_builder.go [hunk 11]
```diff
@@ -759,22 +764,26 @@ func (cb *ClusterBuilder) setH2Options(mc *MutableCluster) {
 	}
 }
 
-func (cb *ClusterBuilder) applyTrafficPolicy(opts buildClusterOpts) {
+func (cb *ClusterBuilder) applyTrafficPolicy(opts *buildClusterOpts) {
+	// ALPN header rewrite starts mTLS. Skip if TLS mode is SIMPLE or MUTUAL
+	if opts.policy != nil && opts.policy.Tls != nil {
```
[the remark this answers is not in the document]
Comment (ksubrmnn) [reply pilot/pkg/networking/core/v1alpha3/cluster_builder.go]: will do in follow up pr when I reintroduce changes to applyTrafficPolicy()

**Review by howardjohn — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]
Approving since changes are coming in a follow up PR
