### PR TITLE
Fix bug where analyzer suppressed cluster-level resource messages.

### LINKED ISSUE #18934: istioctl analyze doesn't emit messages on cluster-level resources
**Bug description**

Running `istioctl x analyze` does not produce messages on Cluster-level resources. This is likely due to the code we added to suppress messages not related to the current namespace (which cluster-level resources do not have).

### PR DESCRIPTION
**Pull request by selmanj**
Closes #18934

### CODE REVIEW

File: galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go [hunk 1]
```diff
@@ -214,3 +250,13 @@ func getTestSnapshot(names ...string) *Snapshot {
 		set: coll.NewSetFromCollections(c),
 	}
 }
+
+var _ resource.Origin = fakeOrigin{}
```
Comment (selmanj) [inline galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go]: I'd love feedback on how to avoid having to define this type at the bottom of this file. I don't know if there's a way to do it inside the test itself.

Comment (sushicw) [reply galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go]: I'd put it at the top of the file, otherwise this is consistent with how we're handling test objects elsewhere.
