### PR TITLE
Fix NACKS when service addresses partially overlap

### LINKED ISSUE #51747: Listeners missing for service entries with TCP ports and multiple addresses [1.22]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgrading from 1.21 to 1.22 listeners are missing for second and consecutive addresses listed in `addresses` block in service entry definition when resolution is `NONE` and protocol is `TCP`.

If I change protocol from `TCP` to `TLS` additional listeners get added to match the number of hosts specified in the spec but only the first address entry is used.

### Version

```Text
$ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (18 proxies)

$ kubectl version
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b

$ helm version --short
v3.14.3+gf03cc04
```

### Istio 1.21 and Kubernetes 1.29
Added this for comparison. Configuration is taken from an identical cluster that runs Istio 1.21 and Kubernetes 1.29.
As you can see three listeners have been created - one for each address entry. The sample-app can communicate with the external service (all three AWS MSK brokers).
```
$ kubectl --context=cluster-02 get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.8.192/28
  - 10.123.8.208/28
  - 10.123.8.224/28
exportTo:
  - .
hosts:
  - b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-2.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-3.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: tcp
    number: 9092
    protocol: TCP
  - name: tcp-2
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9092
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9092 Addr: 10.123.8.192/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.208/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.224/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 ALL                   Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9098
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9098 Addr: 10.123.8.192/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.208/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.224/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 ALL                   Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TCP` protocol

Only one listener gets created in this case. The sample-app can talk to only one MSK broker, other requests end up being BlackHole'd.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TCP
  - name: msk-iam-auth
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9092 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9092 Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9098 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9098 Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TLS` protocol

Not sure if this is relevant, since Istio seems to be using SNI only and probably ignores addresses block. The sample-app can communicate with all MSK brokers.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TLS
  - name: msk-iam-auth
    number: 9098
    protocol: TLS
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9092 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9092 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9098 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9098 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### PR DESCRIPTION
**Pull request by howardjohn**
This has a very long history of back-and-forth on bugs/fixes/regressions. Ill try to capture the history accurately...

Istio 1.22 introduced a regression: https://github.com/istio/istio/issues/51747 causing SE with multiple addresses to get some of their addresses ignored. I cannot actually find the PR that broke things but the issue has plenty of detail.

From that investigation, we found this occurs only when there is no Sidecar object -- otherwise its fine. 

Meanwhile, https://github.com/istio/istio/pull/51967 was merged and cherrypicked to 1.22 and 1.23. This fixed the issue, but caused 2 new ones:
* https://github.com/istio/istio/issues/52847
* https://github.com/istio/istio/issues/52944

This was reverted in 1.22 https://github.com/istio/istio/pull/52952 and 1.23 https://github.com/istio/istio/pull/53000 but left on 1.24.

In 1.24, https://github.com/istio/istio/pull/51776 was merged. This fixes #51747 (the original bug we were trying to fix!!) and #52944 but **does not fix** #52847. Since we did not revert the original fix in 1.24, that leaves 1.24 susceptible to #52847.

I think this was simply a mistake; I had intended to merge a fix like this in 1.24 but lost track.

This PR _partially_ reverts https://github.com/istio/istio/pull/51967. There were still some good changes included in that PR, but the change to collapse a SE with multiple IPs into a single model.Service (rather than multiple model.Services) is the root cause and which is removed.

In addition, tests covering #51967 are added.

Tagging reviewers:
* @keithmattix @hzxuzhonghu - original PR reviewers
* @ilrudie - this slightly touches some of the auto-allocation stuff. I think its fine but more :eyes: is better
* @jewertow - this reverts a subset of your changes

---

DNS code has some new fixes, and a similar long history.

Consider if I have a SE with [ipv4-1, ipv4-2, ipv6]...

Istio 1.20: only ipv4-1

master:
  Kubernetes pods: [ipv4-1, ipv4-2]
  VMs: [ipv4-1] (this behavior is wrong)

master with dual stack: 
  Kubernetes pods: [ipv4-1, ipv4-2, ipv6]
  VMs: [ipv4-1, ipv6] (this behavior is wrong)

This PR:
  Single stack: [ipv4-1, ipv4-2]
  Dual stack: [ipv4-1, ipv4-2, ipv6]

This is done by replacing .SidecarScope (which picks a **single service**) with .EgressListeners iteration which includes all the services, mirroring how LDS code works

### CODE REVIEW

File: pilot/pkg/serviceregistry/serviceentry/conversion.go [hunk 1]
```diff
@@ -50,7 +49,7 @@ func convertPort(port *networking.ServicePort) *model.Port {
 
 type HostAddress struct {
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/serviceentry/conversion.go:50]: Note: every change in this file and conversion_test.go is done by reverting the original PR and fixing merge conflicts.

The rest of the PR is net-new code.

**Review by ilrudie — APPROVED** [review]
LGTM from the perspective of auto-allocate. 1 super minor nit.

File: tests/integration/pilot/common/routing.go [hunk 2]
```diff
@@ -3600,8 +3594,11 @@ spec:
 				address += "&server=" + tt.server
 			}
 			var checker echo.Checker = func(result echo.CallResult, _ error) error {
+				if len(result.Responses) == 0 {
+					return fmt.Errorf("no responses")
+				}
 				for _, r := range result.Responses {
-					if !reflect.DeepEqual(r.Body(), tt.expected) {
+					if !sets.New(r.Body()...).Equals(sets.New(tt.expected...)) {
```
Comment (howardjohn) [inline tests/integration/pilot/common/routing.go:3601]: Two bug fixes here unrelated to the change:
1. Fail if we get no response. Right now we succeed! So its a race, we basically skip this test often
2. Compare unordered. Right now we do in-order, so it may take a few attempts for the random order to match up

File: pkg/dns/server/name_table.go [hunk 3]
```diff
@@ -41,120 +41,122 @@ func BuildNameTable(cfg Config) *dnsProto.NameTable {
...
-		for _, svcAddress := range svc.GetAllAddressesForProxy(cfg.Node) {
-			if svcAddress == constants.UnspecifiedIP {
-				headless = true
-				break
-			}
-			// Filter out things we cannot parse as IP. Generally this means CIDRs, as anything else
-			// should be caught in validation.
-			if !netutil.IsValidIPAddress(svcAddress) {
-				continue
+	for _, el := range cfg.Node.SidecarScope.EgressListeners {
```
Comment (ramaraochavali) [inline pkg/dns/server/name_table.go:44]: Is this the only change in this file?  What is the purpose of this change instead of accessing services directly from sidecar? The diff is difficult to parse

Comment (howardjohn) [reply pkg/dns/server/name_table.go:44]: yes it is. The .services is a single service per hostname already flattened. so 2 vips on a SE means you only end up with 1 breaking dual stack SE. 

The egress listener is not fully filtered like that - mirroring how LDS works

**Review by ramaraochavali — APPROVED** [review]
