### PR TITLE
Fix undefined “IOPS” wording and confusing validation in upgrade

### LINKED ISSUE #22907: istioctl upgrade: undefined “IOPS” wording and confusing validation on the current versions
https://discuss.istio.io/t/warnings-during-istio-upgrade-1-4-1-5/6083

**Bug description**
there might be 2 issues here in the upgrade code.

1. the “IOPS” word should be replaced because it is an implementation detail;
2. the upgrade function can skip the version match check for the current version.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by elfinhe**
Fix https://github.com/istio/istio/issues/22907

### CODE REVIEW

File: operator/cmd/mesh/upgrade.go [hunk 1]
```diff
@@ -192,9 +192,9 @@ func upgrade(rootArgs *rootArgs, args *upgradeArgs, l *Logger) (err error) {
 	if ysf, err = yamlFromSetFlags(currentSets, args.force, l); err != nil {
 		return err
 	}
-	currentProfileIOPSYaml, _, err := GenerateConfig(nil, ysf, args.force, nil, l)
+	currentProfileIOPSYaml, _, err := GenerateConfig(nil, ysf, true, nil, l)
```
Comment (howardjohn) [inline operator/cmd/mesh/upgrade.go:195]: won't the warning still show up? And doesn't force do more than just remove the version check?

Comment (elfinhe) [reply operator/cmd/mesh/upgrade.go:195]: The warning code is at: operator/cmd/mesh/profile-common.go: rewriteURLToLocalInstallPath(). The version check inside is used by all GenerateConfig() callers, and I think it is useful because it can prevent incompatible remote profile CR is used, e.g., using 1.4 built-in profile in 1.5 installation.

However, in the current master we support 1.5->1.6, i also makes sense that we remove the version check inside  rewriteURLToLocalInstallPath().

**Review by howardjohn — APPROVED** [review]

**Comment by elfinhe** [comment]
Tests failures probably caused by auto rebase. I will rebase manually.
