### PR TITLE
Fix TestIngress update flake

### LINKED ISSUE #34359: `TestIngress/update-class-not-istio` flake
Example failures: [https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34346/integ-pilot-multicluster-tests_istio/1419908128928960512](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34346/integ-pilot-multicluster-tests_istio/1419908128928960512) 
[https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34312/integ-pilot-multicluster-tests_istio/1419976967003836416](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34312/integ-pilot-multicluster-tests_istio/1419976967003836416)

Likely from #34295

### PR DESCRIPTION
**Pull request by Monkeyanator**
Fixes #34359.

Before we'd expect a `404` when hitting an ingress endpoint where the corresponding `Ingress` resource had a bogus ingress class. This is wrong since when the Ingress class doesn't match we shouldn't get a response at all (should not even have a generated Gateway). The test relies on a race condition and only passing when the new `Ingress` has not yet taken effect.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: tests/integration/pilot/ingress_test.go [hunk 1]
```diff
@@ -538,7 +538,7 @@ spec:
 						Headers: map[string][]string{
 							"Host": {"server"},
 						},
-						Validator: echo.ExpectCode("404"),
+						Validator: echo.ExpectError(),
```
Comment (howardjohn) [inline tests/integration/pilot/ingress_test.go:541]: seems like we may want error or 404? 

I think this only works under the assumption there are zero other Gateways in the entire cluster. Not sure how safe that assumption is...

Comment (Monkeyanator) [reply tests/integration/pilot/ingress_test.go]: Makes sense, added `echo.Or` and used here.

**Review by howardjohn — APPROVED** [review]
