### PR TITLE
Fix the metric and log reports for the dryrun gateway config

### LINKED ISSUE #28372: Validation config errors when enabling the validation webhook
**Bug description**
Hi, 
We're attempting to enable the validation config webhook.  This should have been an non-event for us as we've been using `istioctl validate -f` in our pipelines for months.  

However once enabled we were a alerted to a failure in `apiserver_admission_webhook_admission_duration_seconds_count`.

Looking into the `istiod` logs we see a single line: 
```
{"level":"info","time":"2020-10-28T17:26:10.966351Z","scope":"validationServer","msg":"configuration is invalid: gateway must have at least one server"}
```

But no context.

It seems to come from: https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L321

**But we don't use gateways**, we have no gateway crds, we never have:
```
❯ kubectl get gateways.networking.istio.io --all-namespaces
No resources found
```

Therefore I've no idea what is failing? 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Expected behavior**
More context about the failure.

**Steps to reproduce the bug**
Unknown

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.16.12

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/28372

### CODE REVIEW

File: pkg/webhooks/validation/server/monitoring.go [hunk 1]
```diff
@@ -72,7 +72,10 @@ func init() {
 	)
 }
 
-func reportValidationFailed(request *kube.AdmissionRequest, reason string) {
+func reportValidationFailed(request *kube.AdmissionRequest, reason string, dryRun bool) {
+	if dryRun {
```
Comment (howardjohn) [inline pkg/webhooks/validation/server/monitoring.go:76]: Users may actually expect dryrun metrics. Although probably not

**Review by howardjohn — APPROVED** [review]
