### PR TITLE
Fix logging bug and turn off zone aware routing for pilot/mixer

### LINKED ISSUE #3347: Istio component (Pilot/Mixer/etc.) proxy agents shouldn't use zone aware routing
This is not a breaking bug, just unnecessary.
Discussed here - https://groups.google.com/d/msg/istio-users/y7mcC76Adyc/6oo5Y-BaAwAJ

Opening this issue to track a fix.

### PR DESCRIPTION
**Pull request by liamawhite**
Resolves #3347

### CODE REVIEW

File: pilot/pkg/proxy/envoy/v1/watcher.go [hunk 1]
```diff
@@ -117,8 +117,9 @@ func (w *watcher) Reload() {
 // retrieveAZ will only run once and then exit because AZ won't change over a proxy's lifecycle
 // it has to use a reload due to limitations with envoy (az has to be passed in as a flag)
 func (w *watcher) retrieveAZ(ctx context.Context, delay time.Duration, retries int) {
-	if w.config.AvailabilityZone == "" {
-		log.Info("Availability zone not set, proxy will default to not using zone aware routing. To manually override use the --availabilityZone flag.")
+	if w.role.Type == "mixer" || w.role.Type == "pilot" {
```
Comment (costinm) [inline pilot/pkg/proxy/envoy/v1/watcher.go]: How about a flag ? Maybe off by default - with the new kube-inject it is easier to modify 
the template, and we should recommend that AZ is set by inject when possible, and enabled
when needed (and pilot has this info - I'm still not clear how does pilot know the AZ)

File: pilot/pkg/proxy/envoy/v1/watcher.go [hunk 2]
```diff
@@ -142,6 +143,9 @@ func (w *watcher) retrieveAZ(ctx context.Context, delay time.Duration, retries i
 		}
 		attempts++
 	}
+	if w.config.AvailabilityZone == "" {
+		log.Info("Availability zone not set, proxy will default to not using zone aware routing. To manually override use the --availabilityZone flag.")
```
Comment (costinm) [inline pilot/pkg/proxy/envoy/v1/watcher.go]: Users don't typically have ability to set flags - we recommend they use kube-inject or auto-injection. Could you instead point to the istio docs about injection, and make sure there is some example or info on how to do it ?

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 1 above)
Comment (liamawhite) [reply pilot/pkg/proxy/envoy/v1/watcher.go]: I'm not sure I follow. The AZ can't be injected in Kube because the IP and AZ aren't known until after the pod has been created.

We have an issue open against envoy to configure zone aware routing natively via the xDS APIs so this retrieval is just a stop-gap solution until Envoy implements that feature.

Pilot retrieves the AZ but looking up which node the pods is on and then looking at the node labels for the region and zone labels. In Consul, it uses the datacenter field for the given service instance.

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 2 above)
Comment (liamawhite) [reply pilot/pkg/proxy/envoy/v1/watcher.go]: We could but I'm not sure we would expect users to set the flag manually because it's not really viable especially in Kube. Maybe we should remove the manual override phrase from the log?

**Comment by costinm** [comment]
On Feb 10, 2018 12:57, "Liam White" <notifications@github.com> wrote:

*@liamawhite* commented on this pull request.
------------------------------

In pilot/pkg/proxy/envoy/v1/watcher.go
<https://github.com/istio/istio/pull/3396#discussion_r167410840>:

> @@ -117,8 +117,9 @@ func (w *watcher) Reload() {
 // retrieveAZ will only run once and then exit because AZ won't
change over a proxy's lifecycle
 // it has to use a reload due to limitations with envoy (az has to be
passed in as a flag)
 func (w *watcher) retrieveAZ(ctx context.Context, delay
time.Duration, retries int) {
-	if w.config.AvailabilityZone == "" {
-		log.Info("Availability zone not set, proxy will default to not
using zone aware routing. To manually override use the
--availabilityZone flag.")
+	if w.role.Type == "mixer" || w.role.Type == "pilot" {

I'm not sure I follow. The AZ can't be injected in Kube because the IP and
AZ aren't known until after the pod has been created.


Why ? The zone can be set in the inject template for auto-inject. I suppose
it could be passed as a param to kubeinject as well.


We have an issue open against envoy to configure zone aware routing
natively via the xDS APIs so this retrieval is just a stop-gap solution
until Envoy implements that feature

Sure, but setting it as a flag is much simpler, in particular for multiple
clusters and more complicated networks.

.

Pilot retrieves the AZ but looking up which node the pods is on and then
looking at the node labels for the region and zone labels. In Consul, it
uses the datacenter field for the given service instance.


Who sets the labels ? Any docs I can check ? Is it a k8s api that could be
used by injector ?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/istio/istio/pull/3396#discussion_r167410840>, or mute
the thread

**Comment by liamawhite** [comment]
> Why? The zone can be set in the inject template for auto-inject. I suppose
it could be passed as a param to kube-inject as well.

It can't be predetermined because Kube could and should schedule it anywhere it knows about. Unless I'm missing the point and you're saying that the inject template is going to tell Kube which machine to deploy the pod on? That sounds like something Istio shouldn't be concerned about because that's Kube's responsibility. Even so, we would then have to potentially support 10s of orchestrators for users with Consul service discovery.

> Sure, but setting it as a flag is much simpler, in particular for multiple
clusters and more complicated networks.

I disagree. Setting a flag is much more complicated than using the underlying service discovery that already knows the answer and set it for the user. The current method works regardless of how many clusters and networks an Istio instance may have.

>Who sets the labels? Any docs I can check? Is it a k8s API that could be
used by injector?

The cloud provider sets the labels on each Kube node. The pod is only aware of which node it is on, not which region/zone it is in. Again though, you can't determine the pod AZ until after it is running. This is why we have to reload the proxy with updated config rather than set it at start up.

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 2 above)
Comment (rshriram) [reply pilot/pkg/proxy/envoy/v1/watcher.go]: Don't remove the manual override. If we have docs for the pilot agent, lets point to it. If not, its high time that we had docs for pilot agent, just like other auto generated docs in istioctl.

**Comment by rshriram** [comment]
@costinm Kube has a failure domain label per node. Pods can inspect the node level flags using the kube client (its not available as an environment variable unfortunately). I don't think GKE uses this at all (since the model there is one cluster per AZ). IBM cloud uses this multi-az cluster thing, where nodes are annotated.
As Liam says, we don't have this info before hand (I wish we did). We simply read it from the service registry for every instance (Consul has a nicer way of going about this). We didn't want to embed this functionality in the pilot agent because it requires having a kube client in the pilot agent, which takes about 40Mb+, bringing the size of the agent alone to 50+Mb. Hence the clunky workaround to supplying the AZ via an API, and doing a hot restart of Envoy. Once we get the ability to dynamically update an Envoy's local AZ, we would essentially be getting rid of this API and everything else. But that is a long term goal.

@liamawhite I think costin's underlying concerns is that this whole thing will break when you enable mTLS between envoys and the control plane. What you need to do in the agent is to use the mTLS certificate in the pod and talk to the control plane using that certificate.

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 1 above)
Comment (rshriram) [inline pilot/pkg/proxy/envoy/v1/watcher.go]: nit.. Invert this selection.. if role.type != sidecar/router/ingress ...

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 2 above)
Comment (rshriram) [reply pilot/pkg/proxy/envoy/v1/watcher.go]: is this going to repeat on the console over and over? If so, kill this printout. If not, simply stop with "not using zone aware routing".

**Comment by liamawhite** [comment]
>  I think Costin's underlying concerns is that this whole thing will break when you enable mTLS between envoys and the control plane. What you need to do in the agent is to use the mTLS certificate in the pod and talk to the control plane using that certificate.

Ok, I will address this in a separate PR.

File: pilot/pkg/proxy/envoy/v1/watcher.go (hunk 2 above)
Comment (liamawhite) [reply pilot/pkg/proxy/envoy/v1/watcher.go]: No. This is outside the for loop and indicates that the agent is giving up trying to enable zone aware routing.

**Comment by costinm** [comment]
There are other concerns - on raw vms /mesh expansion there is no
annotation, but the flag will work.

And for all features we should have a way to enable/disable.

I actually like the idea of agent making an initial request to pilot - was
thinking we can extend it, we could get initial set of listeners before
first start, with v2 they are merged with lds. We could also get defaults
for refresh interval and other settings from the cluster.

**Comment by rshriram** [comment]
I think what Costin is saying is to have flag to disable az.

**Comment by liamawhite** [comment]
@rshriram @costinm Ok, these are all good points but out of scope for this PR. What I would suggest is I create a separate issue where we can discuss the design and documentation of the Availability Zone functionality and flag(s); with a specific focus on use cases that aren't Consul or Kube. Does this sound reasonable?
