### PR TITLE
Use k8s strategic merge lib for IOP overlays

### LINKED ISSUE #24432: Configuring components.ingressGateways.k8s.service.externalTrafficPolicy breaks ingress gateways
**Bug description**

Setting `externalTrafficPolicy` to `Local` wipes out all the default configuration for the ingressgateway service, including the ports.

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A valid service is generated with a mix of configured values and defaults.
When generating a manifest with the following configuration:

**Steps to reproduce the bug**

Generate a manifest using the following IstioOperator:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  hub: gcr.io/cf-routing
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
             externalTrafficPolicy: Local
```

**Observed:**
The istio-ingressgateway service lacks any ports:

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports: null
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

**Desired:**
A valid service is produced:

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: tls
    port: 15443
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
17:48 $ istioctl version
client version: 1.6.0
```

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

### PR DESCRIPTION
**Pull request by ostromart**
Fixes https://github.com/istio/istio/issues/24432.

### CODE REVIEW

File: operator/pkg/util/merge_iop.go [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/util/strategicpatch"
+
+	v1alpha13 "istio.io/api/mesh/v1alpha1"
+	"istio.io/api/networking/v1alpha3"
+	"istio.io/api/operator/v1alpha1"
+	v1alpha12 "istio.io/istio/operator/pkg/apis/istio/v1alpha1"
+)
+
+// Partially mirrored from istio/api and operator/pkg/api (for values).
```
Comment (richardwxn) [inline operator/pkg/util/merge_iop.go:32]: Do we need to manually keep this in sync with what is in apis?

Comment (ostromart) [reply operator/pkg/util/merge_iop.go:32]: yes, to some extent. these are only top level structs that aren't likely to change, most fields are not required. structs can be removed from api and remain here without any harm. last of all, we have good test coverage for any potential breaking changes because the merge function is in line with everything.

Comment (morvencao) [reply operator/pkg/util/merge_iop.go:32]: Does it make sense that we can add json tags for the patchStrategy to the api generated by proto?

Comment (ostromart) [reply operator/pkg/util/merge_iop.go:32]: no, this is not possible, because as i mentioned in the comment, the values and meshconfig fields are defined as map[string]interface rather than structs. therefore strategic merge fails with an error if IOP contains any fields for those subtrees that require patchStrategy to be defined.

File: operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml [hunk 2]
```diff
@@ -11,9 +11,5 @@ spec:
       k8s:
         service:
           externalTrafficPolicy: Local
-          ports:
```
Comment (howardjohn) [inline operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml:14]: Can we have a test with ports and without ports? there is some issue somewhere around how the ports override is inconsistent

File: operator/pkg/util/merge_iop.go [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+	DefaultConfig                  *v1alpha13.ProxyConfig                                    `json:"defaultConfig" patchStrategy:"merge"`
+	ConfigSources                  []*v1alpha13.ConfigSource                                 `json:"configSources" patchStrategy:"merge"`
+	TrustDomainAliases             []string                                                  `json:"trustDomainAliases" patchStrategy:"merge"`
+	DefaultServiceExportTo         []string                                                  `json:"defaultServiceExportTo" patchStrategy:"merge"`
+	DefaultVirtualServiceExportTo  []string                                                  `json:"defaultVirtualServiceExportTo" patchStrategy:"merge"`
+	DefaultDestinationRuleExportTo []string                                                  `json:"defaultDestinationRuleExportTo" patchStrategy:"merge"`
+	LocalityLbSetting              *v1alpha3.LocalityLoadBalancerSetting                     `json:"localityLbSetting" patchStrategy:"merge"`
+	Certificates                   []*v1alpha13.Certificate                                  `json:"certificates" patchStrategy:"merge"`
```
Comment (howardjohn) [inline operator/pkg/util/merge_iop.go:122]: does this mean we cannot replace these lists?

Comment (howardjohn) [reply operator/pkg/util/merge_iop.go:122]: This seems not desirable - but also not a big deal since we don't have defaults anyways...

**Review by howardjohn — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Review by richardwxn — APPROVED** [review]

File: operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml (hunk 2 above)
Comment (kyessenov) [reply operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml:14]: The merge should use merge key name in this case. We should have a test with some strategic merge example.

**Review by kyessenov — COMMENTED** [review]
LGTM.

**Review by elfinhe — APPROVED** [review]

**Review by JimmyCYJ — APPROVED** [review]

**Review by mandarjog — APPROVED** [review]
lgtm
