### PR TITLE
Fix bug report missing all logs for json logs

### LINKED ISSUE #44788: bug-report: json log lines can be excluded
`getTimeRange` attempts to filter on time. This doesn't take JSON format into account, leading to missing logs

### PR DESCRIPTION
**Pull request by syw14**
Fixes #44788

### CODE REVIEW

File: tools/bug-report/pkg/processlog/processlog.go [hunk 1]
```diff
@@ -52,16 +53,28 @@ func (s *Stats) Importance() int {
...
+func getTimeRange(logStr string, start, end time.Time, isLogAsJson bool) string {
 	var sb strings.Builder
 	write := false
 	for _, l := range strings.Split(logStr, "\n") {
-		t, _, _, valid := processLogLine(l)
+		var t *time.Time
+		var valid bool
+
+		if isLogAsJson {
+			t, _, _, valid = parseJsonLog(l)
```
Comment (howardjohn) [inline tools/bug-report/pkg/processlog/processlog.go:73]: If we are already processing line-by-line, maybe we should just detect json on a per-line basis as well instead of for the entire function?

Comment (howardjohn) [reply tools/bug-report/pkg/processlog/processlog.go:73]: I mean in processLogLine

File: tools/bug-report/pkg/processlog/processlog.go [hunk 2]
```diff
@@ -52,16 +53,28 @@ func (s *Stats) Importance() int {
 
 // Process processes logStr based on the supplied config and returns the processed log along with statistics on it.
 func Process(config *config.BugReportConfig, logStr string) (string, *Stats) {
```
Comment (howardjohn) [inline tools/bug-report/pkg/processlog/processlog.go:55]: Can we add some testing for this function?

File: tools/bug-report/pkg/processlog/processlog.go [hunk 3]
```diff
@@ -52,16 +53,28 @@ func (s *Stats) Importance() int {
...
+	}
+	out := getTimeRange(logStr, config.StartTime, config.EndTime, isLogAsJson)
+	return out, getStats(config, out, isLogAsJson)
 }
 
 // getTimeRange returns the log lines that fall inside the start to end time range, inclusive.
-func getTimeRange(logStr string, start, end time.Time) string {
+func getTimeRange(logStr string, start, end time.Time, isLogAsJson bool) string {
 	var sb strings.Builder
 	write := false
```
Comment (howardjohn) [inline tools/bug-report/pkg/processlog/processlog.go:67]: If start and end are not set (99% of te time this is the case), can we just entirely skip processing and return the logs as-is? This will be faster (although its not clear that really matters), simpler, and impossible to lose logs.

**Review by howardjohn — COMMENTED** [review]
Can we add some testing for

File: tools/bug-report/pkg/processlog/processlog.go (hunk 3 above)
Comment (syw14) [reply tools/bug-report/pkg/processlog/processlog.go:67]: There's some filtering logic inside `getTimeRange' for example: omit the log if there's no time / level specified; or if the log contains specified ignored-info, ignore the log (https://github.com/istio/istio/blob/2e0a7351c705eae8f87b5cf0eef65cfc5e51b5d2/tools/bug-report/pkg/processlog/processlog.go#L90). Not sure if could bypass these logic / how frequently these are used.

Comment (howardjohn) [reply tools/bug-report/pkg/processlog/processlog.go:67]: I mean if they filters are not set though - which I think they are pretty rare (could consider removing entirely)

Comment (hanxiaop) [reply tools/bug-report/pkg/processlog/processlog.go:67]: +1 for either skipping the processing or removing it entirely, as we don't need it most of the time.

File: tools/bug-report/pkg/processlog/processlog.go (hunk 2 above)
Comment (syw14) [reply tools/bug-report/pkg/processlog/processlog.go:55]: added

File: tools/bug-report/pkg/processlog/processlog.go (hunk 3 above)
Comment (syw14) [reply tools/bug-report/pkg/processlog/processlog.go:66]: Added the skip filtering logic

File: tools/bug-report/pkg/config/config.go [hunk 4]
```diff
@@ -162,6 +162,10 @@ type BugReportConfig struct {
 	// If set, StartTime must be unset.
 	Since Duration `json:"since,omitempty"`
 
+	// TimeFilterApplied stores if user has provided any time filtering flags.
+	// If Since, StartTime, EndTime are all not applied by the user, set TimeFilterApplied as false; Otherwise set true
+	TimeFilterApplied bool `json:"timeFilterApplied,omitempty"`
```
Comment (hanxiaop) [inline tools/bug-report/pkg/config/config.go:167]: I believe these are configurations that are set by user-facing command flags. It will be better to assign them to a global variable or use a function instead of including them in the `BugReportConfig`.

Comment (syw14) [reply tools/bug-report/pkg/config/config.go:167]: I thought the [flags.go](https://github.com/istio/istio/blob/fe62d5b332a18bf183803702b17487584193227d/tools/bug-report/pkg/bugreport/flags.go#L31) is for user facing flags while the config.go is more for internal use. Is it not?

File: tools/bug-report/pkg/bugreport/flags.go [hunk 5]
```diff
@@ -145,6 +145,12 @@ func parseConfig() (*config2.BugReportConfig, error) {
 }
 
 func parseTimes(config *config2.BugReportConfig, startTime, endTime string, duration time.Duration) error {
+	if (startTime == "" && endTime == "" && config.Since == 0) {
```
Comment (howardjohn) [inline tools/bug-report/pkg/bugreport/flags.go:148]: config.since is always 0 here I think. its only set on L155

File: tools/bug-report/pkg/config/config.go (hunk 4 above)
Comment (howardjohn) [reply tools/bug-report/pkg/config/config.go:167]: I think its reasonable here. Slight preference to make it method on BugReportConfig though (since it is derived from the rest)

File: tools/bug-report/pkg/processlog/processlog.go [hunk 6]
```diff
@@ -61,7 +65,15 @@ func getTimeRange(logStr string, start, end time.Time) string {
...
 	for _, l := range strings.Split(logStr, "\n") {
-		t, _, _, valid := processLogLine(l)
+		var t *time.Time
+		var valid bool
+
+		if isJSONLog(logStr) {
```
Comment (howardjohn) [inline tools/bug-report/pkg/processlog/processlog.go:71]: nit: make a parseLog function that does this for us so we don't need this on both calls

File: tools/bug-report/pkg/config/config.go (hunk 4 above)
Comment (syw14) [reply tools/bug-report/pkg/config/config.go:167]: In flag.go they would alter the startTime and endTime value the user passes in, so it might hard to make it a method on BugReportConfig because BugReportConfig don't have the original startTime and endTime maintained there.

**Review by howardjohn — APPROVED** [review]
