### PR TITLE
Set standard alpns as well in outbound traffic

### LINKED ISSUE #24619: http alpn override applied to external services breaks connections
### Describe the bug 
Connections to external HTTP services configured with SIMPLE_TLS destination rules are aborted by the external server or envoy due to non-negotiated alpn errors.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### Expected behavior
Envoy and the external service should connect using http 1.1. or h2. Istio/envoy should not send an ALPN list consisting entirely of unsupported protocols (ie, ["istio-http1.1", "istio"]). Unsupported protocols are not ignored by servers.

>In the event that the server supports no protocols that the client advertises, then the server SHALL respond with a fatal "no_application_protocol" alert.
https://tools.ietf.org/html/rfc7301#section-3.1

### Steps to Reproduce
Apply:
```
apiVersion: apps/v1                  
kind: Deployment
metadata:                               
  name: sleep     
spec:    
  selector:      
    matchLabels:
      app: sleep
  template:  
    metadata:
      annotations:
      labels:            
        app: sleep
    spec:
      containers:                       
      - name: sleep  
        image: pstauffer/curl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
--- 
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http2.pro
spec:
  hosts:
  - http2.pro
  ports:
  - name: http
    number: 443
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: http2.pro
spec:
  host: http2.pro
  trafficPolicy:
    tls:
      mode: SIMPLE
```
Attempt to access external service and observe failure:
```
$ kubectl exec -t sleep-69bd787db7-tmvqn -n istio-monitoring -c sleep -- curl -v -s --http2  http://http2.pro:443/api/v1
*   Trying 8.9.5.7...
* TCP_NODELAY set
* Connected to http2.pro (8.9.5.7) port 443 (#0)
> GET /api/v1 HTTP/1.1
> Host: http2.pro:443
> User-Agent: curl/7.60.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
upstream connect error or disconnect/reset before headers. reset reason: connection failure< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Fri, 12 Jun 2020 01:50:04 GMT
< server: envoy
<
```
Envoy log:
```
[2020-06-12T01:50:04.423Z] "GET /api/v1 HTTP/1.1" 503 "upstream_reset_before_response_started{connection failure,TLS error: 268435715:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL 268435605:SSL rout
ines:OPENSSL_internal:ERROR_PARSING_EXTENSION 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT}" UF,URX "-" "TLS error: 268435715:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL 268435605:SSL rout
ines:OPENSSL_internal:ERROR_PARSING_EXTENSION 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT" 0 91 503 - "-" "curl/7.60.0" "dc47bd2e-7827-46df-a123-c52f5733e96c" "http2.pro:443" "8.9.5.7:443" outbou
nd|443||http2.pro - 8.9.5.7:443 172.23.5.168:51367 - default 
```
### Analysis
We first noticed connections to external services defined in ServiceEntries with envoy TLS origination no longer worked when we upgraded from 1.4.X to 1.5.4.

It appears that the outbound HTTP connection manager always overrides the alpn with istio-h2 or istio-http1.1. Could it add the non-istio variants as well?
https://github.com/istio/istio/blob/1.5.4/pilot/pkg/networking/core/v1alpha3/listener.go#L1802

Response from 1.4.4:
```
$ kubectl exec -t sleep-69bd787db7-hb66q -n istio-monitoring -c sleep -- curl  -s --http2  http://http2.pro:443/api/v1
{"http2":0,"protocol":"HTTP\/1.1","push":0,"user_agent":"curl\/7.60.0"}
```

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes #24619

This allows outbound TLS origination to maintain standard ALPN values
(rather than `istio-` values). A more proper solution would be to send
only istio ones when the destination is a sidecar, and only standard
ones when not, but this requires a total change of how the filter works.

The end result here is no impact on sidecar traffic other than an
additional ALPN set, which should never impact filter chain matching
(since first ALPN has precedence), but outbound TLS will have multiple
ALPNs set and the standard ALPNs should be selected.

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]

**Comment by howardjohn** [comment]
/retest

Will add regression tests then mark this as ready

**Comment by howardjohn** [comment]
After https://github.com/istio/istio/issues/29538 I have pretty much no confidence in making changes to any Envoy config we make. Not sure its safe to touch the bear

**Comment by ramaraochavali** [comment]
@howardjohn What issue is this fixing just to have some context?

**Comment by howardjohn** [comment]
Sorry, this is to fix https://github.com/istio/istio/issues/24619

File: pilot/pkg/xds/filters/filters.go [hunk 1]
```diff
@@ -163,9 +163,12 @@ var (
 	// These ALPNs are injected in the client side by the ALPN filter.
 	// "istio" is added for each upstream protocol in order to make it
 	// backward compatible. e.g., 1.4 proxy -> 1.3 proxy.
-	mtlsHTTP10ALPN = []string{"istio-http/1.0", "istio"}
-	mtlsHTTP11ALPN = []string{"istio-http/1.1", "istio"}
-	mtlsHTTP2ALPN  = []string{"istio-h2", "istio"}
+	// Non istio-* variants are added to ensure that traffic sent out of the mesh has a valid ALPN;
+	// ideally this would not be added, but because the override filter is in the HCM, rather than cluster,
```
Comment (ramaraochavali) [inline pilot/pkg/xds/filters/filters.go:167]: This PR https://github.com/envoyproxy/envoy/pull/13922 adds ALPN   options to cluster.  I have n't through your PR fully,  but FYI so that you are aware and think about any changes needed/improvements given that it is supported at cluster now.

File: releasenotes/notes/standard-alpn.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+apiVersion: release-notes/v2
+kind: feature
+area: networking
+releaseNotes:
+- |
+  **Added** support for virtual service delegate for sidecar proxies.
```
Comment (ramaraochavali) [inline releasenotes/notes/standard-alpn.yaml:6]: nit: wrong release notes?

**Comment by howardjohn** [comment]
I don't think that PR is sufficient. We need to send istio-http/1.1 for
mTLS traffic and http/1.1 for non-mtls.

**Comment by hzxuzhonghu** [comment]
Should refer to `BestEffortInferServiceMTLSMode`

**Comment by howardjohn** [comment]
> Should refer to `BestEffortInferServiceMTLSMode`

I am not sure how that helps? envoy doesn't provide a way to set the alpn at that granularity as far as I know.

**Comment by hzxuzhonghu** [comment]
Trying to catch up, if could override alpn in cluster, it would be much easier.

**Comment by howardjohn** [comment]
I agree. Actually to be even better we need it in the transport socket since a single cluster may have both sidecar and non-sidecar endpoints which we match on transport_socket_match. As far as I know the current implementation is the best we can do with current envoy. Note that the alpn configuration we are doing today is already a  custom filter we wrote as well

**Comment by howardjohn** [comment]
@hzxuzhonghu any more comments?

**Review by hzxuzhonghu — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Comment by howardjohn** [comment]
/retest

flake I fixed in another PR

**Review by mandarjog — APPROVED** [review]
Thanks.
1. tacks on standard protocol names at the end
2. Will not affect sidecars, as earlier names will be used.
3. A non-istio endpoints with proper alpn processing will select a standard protocol.
