### PR TITLE
Let --force really work in 'manifest apply'

### LINKED ISSUE #23376: Fields removed without deprecation (TracerLightStepConfig.cacertPath and secure)
A PR yesterday, https://github.com/istio/istio/pull/23220 , removed `cacertPath` and `secure` from `v1alpha1.TracerLightStepConfig`.

I hadn't even looked at that pull... the name "Add TLS settings to tracer" did not make me think anything was going away.

This breaks our deprecation/upgrade policy.

I don't know how many users have a TracerLightStepConfig setting in their IOP file, so maybe 1.5.x users will not be affected.  No one who makes an IstioOperator from scratch will be affected.  Folks who created their "iop.yaml" file using `istioctl profile dump > iop.yaml` may be affected.

My problem is that users on 1.6.0-alpha who do the install have an IOP written to the cluster.  With my PR, users doing `istioctl upgrade` or `istioctl manifest apply` use the in-cluster IOP if it exists instead of the `default` profile, leading to 

```
Error: failed to apply manifests: unknown field "cacertPath" in v1alpha1.TracerLightStepConfig
```

This is because the IstioOperator contains `cacertPath: ""`.

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/23376 by letting --force really work when there are unknown fields in the IOP offered to `istioctl manifest apply`.

Also fixes the case where there is unparse-able creationTime metadata in an IOP.

### CODE REVIEW

File: operator/pkg/helmreconciler/render.go [hunk 1]
```diff
@@ -27,8 +27,10 @@ import (
 // RenderCharts renders charts for h.
 func (h *HelmReconciler) RenderCharts() (name.ManifestMap, error) {
 	iopSpec := h.iop.Spec
-	if err := validate.CheckIstioOperatorSpec(iopSpec, false); err != nil {
-		return nil, err
+	if !h.opts.Force {
+		if err := validate.CheckIstioOperatorSpec(iopSpec, false); err != nil {
```
Comment (howardjohn) [inline operator/pkg/helmreconciler/render.go:31]: should we warn here?

File: operator/pkg/util/yaml.go [hunk 2]
```diff
@@ -72,6 +75,19 @@ func UnmarshalWithJSONPB(y string, out proto.Message, allowUnknownField bool) er
 		return err
 	}
 
+	// Remove creationTimestamp from jb if it exists
+	content := make(map[string]interface{})
+	err = json.Unmarshal(jb, &content)
```
Comment (howardjohn) [inline operator/pkg/util/yaml.go:80]: What is this for? Any reference to an issue? Can we add a test?

**Review by howardjohn — COMMENTED** [review]
lgtm for the force part

File: operator/pkg/util/yaml.go (hunk 2 above)
Comment (esnible) [reply operator/pkg/util/yaml.go:80]: The bug was https://github.com/istio/istio/issues/18615 .  The reason is that API Machinery defines CreationTimestamp with `json:"creationTimestamp,omitempty" protobuf:"bytes,8,opt,name=creationTimestamp"` and IstioOperator uses the other protobuf library.  Until we have a fix for this issue I don't know how to test it.

Comment (howardjohn) [reply operator/pkg/util/yaml.go:80]: That bug was supposedly fixed though. Where are you seeign this now?

Comment (esnible) [reply operator/pkg/util/yaml.go:80]: Using 1.6.0-beta.0, with Istio already installed, do `./bin/istioctl manifest apply -f <(kubectl -n istio-system get istiooperator installed-state -o yaml)` and you will see the problem.  (`generate` reports the same problem but it is less obvious because the error message is huge).

File: operator/pkg/helmreconciler/render.go (hunk 1 above)
Comment (esnible) [reply operator/pkg/helmreconciler/render.go]: Fixed.

File: operator/pkg/util/yaml.go (hunk 2 above)
Comment (howardjohn) [reply operator/pkg/util/yaml.go:80]: Fixing in `UnmarshalWithJSONPB` won't work I think. This is a generic method. maybe it should be in UnmarshalIOP?

Comment (esnible) [reply operator/pkg/util/yaml.go]: Fixed.

**Review by howardjohn — APPROVED** [review]
