### PR TITLE
Fix waypoint routing for multi-cluster on single network

### LINKED ISSUE #58133: [Ambient/multi-cluster] single-network waypoint fails on remote service VIP
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Summary
- We did some testing of ambient multi-cluster on single network with waypoint. We thought there could be bugs of waypoint there. It might be the issue of how service VIP is handled, or the host/authority not handled properly. We don't know the exact root cause yet.

Our Setup
- On EKS, single flat network, multi-clusters, clusters are labeled with the same network label
- No E-W gateway
- For istiod setup, enabled AMBIENT_ENABLE_MULTI_NETWORK=true as some functionalities are enabled via that flag

Issue
- Out of the box, we hit intermittent failures when the local waypoint tries to handle a remote cluster VIP, or vice versa: the waypoint failed as there is no filter chain match for the remote service VIP in local waypoint.

Two workarounds that seemed to address the issue
- Keeping both the waypoint and backend service to cluster-local by removing the `isito.io/global=true` label. This will let ztunnels always picks the local waypoint and waypoint only handles the VIP of the local service. And because EDS still contains endpoints from different clusters so the local waypoint can still route to either local or remote service endpoints.
- Disabling the DNS proxying so the service name always resolves to the local VIP only

### Version

```Text
istioctl version
client version: 1.27.1
control plane version: 1.27.0

 kubectl version
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.14-eks-113cf36
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by garrettheel**
This fixes #58133 by allowing multi-cluster waypoint routing on a single network deployment (no E-W gateway). The current issue is that remote cluster waypoints do not include other clusters' VIPs on the IP matcher, causing traffic to fall through and NR.

Note that this is currently gated behind `AMBIENT_ENABLE_MULTI_NETWORK` which doesn't really make sense since it's in service of single network, but it's consistent with other functionality required to make single network function. I'm open to alternate gating ideas from maintainers.

In addition to unit tests, I also tested this E2E to ensure that everything works on a pair of EKS clusters.

### CODE REVIEW

**Comment by keithmattix** [comment]
Thanks for the contribution!

/ok-to-test

File: pilot/pkg/model/service.go [hunk 1]
```diff
@@ -1808,6 +1806,18 @@ func (s *Service) getAllAddressesForProxy(node *Proxy) []string {
 	return nil
 }
 
+// GetAllClusterVIPs returns all VIPs for this service across all known clusters.
+// Used by waypoint proxies in single-network multi-cluster deployments where a
+// waypoint may receive traffic destined for a remote cluster's VIP for the same
+// logical service. See https://github.com/istio/istio/issues/58133.
+func (s *Service) GetAllClusterVIPs() []string {
```
Comment (keithmattix) [inline pilot/pkg/model/service.go]: What does `GetAllAddressesForProxy` need from the `model.Node` being passed in and why doesn't this function need it? I suspect it may have something to do with dualstack and we need to be careful not to regress here

Comment (garrettheel) [reply pilot/pkg/model/service.go]: `GetAllAddressesForProxy` uses node for three things:

 1)  `node.Metadata.ClusterID` to filter the ClusterVIPs used
 2) filtering VIPs by IP families supported by the node
 3) appends auto-allocated IP addresses if the node supports it

I believe that 1 is unnecessary here (since we're intentionally looking to avoid filtering to the local cluster).

I think 2 is also unnecessary in this context (worst case we have extra matches on different IP families that should never be hit), but I can update to apply the same dual-stack filtering based on `node.GetIPMode()` if you think it's better to keep the config cleaner. Let me know if I'm missing anything here too.

For 3 I don't think this is applicable to waypoints either, but let me know if I'm missing something.

Comment (garrettheel) [reply pilot/pkg/model/service.go]: The integration tests were helpful in showing why 3 was a bug, so I've reworked this a bit to use the same approach as `GetAllAddressesForProxy` but change the approach for fetching service VIPs to span all clusters

File: pilot/pkg/model/service.go [hunk 2]
```diff
@@ -1781,12 +1779,35 @@ func nodeUsesAutoallocatedIPs(node *Proxy) bool {
...
+}
+
+// GetAddressesForProxyAllClusters is like GetAllAddressesForProxy but collects VIPs
+// from all clusters rather than only the proxy's local cluster.
+// Used by waypoint proxies in single-network multi-cluster deployments where a
+// waypoint may receive traffic destined for a remote cluster's VIP for the same
+// logical service. See https://github.com/istio/istio/issues/58133.
+func (s *Service) GetAddressesForProxyAllClusters(node *Proxy) []string {
+	var addresses []string
+	for _, addrs := range s.ClusterVIPs.GetAddresses() {
```
Comment (krinkinmu) [inline pilot/pkg/model/service.go]: Does ClusterVIPs include addresses from clusters on different networks?

I'm asking because address ranges in different networks are allowed to conflict with each other, so if it includes VIPs from different networks, we have to exclude them.

Comment (krinkinmu) [reply pilot/pkg/model/service.go]: Another thing to consider is service scope. I don't think we should expose service VIP or endpoints from a remote cluster for locally scoped services, though, so far, we didn't have to define the semantics of service scope in single-network cases, so maybe an argument could be made that LOCAL scope could mean "network" - I do not advocate for that, just mention that it could be a possibility.

File: pilot/pkg/networking/core/listener_waypoint.go [hunk 3]
```diff
@@ -396,11 +323,17 @@ func (lb *ListenerBuilder) buildWaypointInternal(wls []model.WorkloadInfo, svcs
...
 	for _, svc := range svcs {
 		var waypoint host.Name
-		if isAmbientEastWestGateway && features.EnableAmbientMultiNetwork {
+		if isEastWestGateway && features.EnableAmbientMultiNetwork {
 			waypoint = lb.findServiceWaypoint(svc)
 		}
 
-		svcAddresses := svc.GetAllAddressesForProxy(lb.node)
+		var svcAddresses []string
+		if features.EnableAmbientMultiNetwork {
```
Comment (grnmeira) [inline pilot/pkg/networking/core/listener_waypoint.go]: I see your note in the description, but from a quick glance on the code I didn't find any single network points being guarded by this feature flag. Do you have any examples?

File: pilot/pkg/model/service.go (hunk 2 above)
Comment (garrettheel) [reply pilot/pkg/model/service.go]: ClusterVIPs does include addresses from different networks. I pushed an update that filters based on the cluster networks defined in `meshNetworks` -- how does that look? I guess this could become complicated with the network being overridden at different scopes (e.g. what if the waypoint itself overrides the network?)

For service scope - non-global services should already be filtered out for multi-cluster service merging, and I didn't change that here. For my E2E test to work I had to make the waypoint global in order for ztunnel to attempt to route to these remote cluster VIPs. That said, I think it does make sense to only include IPs in the matcher for global services (if only for hygiene) so I've updated accordingly

File: pilot/pkg/networking/core/listener_waypoint.go (hunk 3 above)
Comment (garrettheel) [reply pilot/pkg/networking/core/listener_waypoint.go]: I think https://github.com/istio/istio/blob/516ce411e1c3493aad7d35ca4fef158ca0afe98b/pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go#L228-L230 is one area but there may be others. In practice I was not able to get basic multi-cluster functionality without this flag enabled

File: pilot/pkg/networking/core/listener_waypoint.go [hunk 4]
```diff
@@ -1263,3 +1203,29 @@ func buildCommonConnectTLSContext(proxy *model.Proxy, push *model.PushContext) *
 	security.EnforceCompliance(ctx)
 	return ctx
 }
+
+// sameNetworkClustersForProxy returns the set of cluster IDs that share the
```
Comment (krinkinmu) [inline pilot/pkg/networking/core/listener_waypoint.go]: @garrettheel I'm not sure this is correct, but I'm also not terribly well familiar with that part of the code either, so bear with me.

My understanding is that you here read MeshNetworks config (that's where I think `push.Networks` is coming from). For Ambient multi-network you don't need to configure MeshNetworks at all (e.g., I have a local setup with 2 kind clusters and I can see that MeshNetworks ConfigMap is basically empty).

With that in mind, I don't think we can rely on the MeshNetworks as a way to figure out complete mapping of clusters to networks.

Besides that, for endpoints you can specify either FromRegistry or FromCidr, but not both (at least that's how I understand https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Network-NetworkEndpoints), so it could be that you'll have CIDR range there rather than a registry/cluster name.

Maybe you could test (or have tested already) to prove my understanding wrong here?


Assuming for a second that I'm correct, what could be done instead of looking into the MeshNetworks?

We could maintain an index from cluster to network somewhere (e.g., using something similar to https://github.com/istio/istio/blob/516ce411e1c3493aad7d35ca4fef158ca0afe98b/pilot/pkg/serviceregistry/kube/controller/ambient/services.go#L196-L204 to build it) - seems like a generally useful thing.

Or, alternatively, we can just lookup ServiceInfo by Service using ambient index and ServiceInfo will contain all the same VIPs, but with network as part of the workloadapi.Service structure.

Comment (garrettheel) [reply pilot/pkg/networking/core/listener_waypoint.go]: I suspect you're right - I'm less familiar with multi-network setups so appreciate your help walking through these cases.

I changed the implementation to use `workloadapi.Service` from ambient index to look up the network and defensively fall back to the existing implementation that uses the local cluster's VIP. Let me know what you think.

File: pilot/pkg/model/push_context.go [hunk 5]
```diff
@@ -2639,3 +2639,8 @@ func (ps *PushContext) ServicesWithWaypoint(key string) []ServiceWaypointInfo {
 func (ps *PushContext) ServiceInfo(key string) *ServiceInfo {
 	return ps.ambientIndex.ServiceInfo(key)
 }
+
```
Comment (krinkinmu) [inline pilot/pkg/model/push_context.go]: Rather than doing this, can we instead allow to override of the memory.DiscoveryService via NewConfigGenTest TestOptions parameter?

memory.DiscoveryService is a test only service registry where we already have an ability to customize various behaviors to suit tests. Currently, NewConfigGenTest unconditionally creates it from scratch and allows to add additional registries on top of that, but not replace it the cluster registry, but we can overcome that.

We can add a new option to the TestOptions to provide the cluster service registry. When it's not provided NewConfigGenTest will do all the same things it currently does, but when it's provided instead of creating a new service registry, it could use the provided one and the rest of the logic will stay the same.

This way you'd only need methods to customize behavior in the memory.DiscoveryService which exists for this purpose.

File: pilot/pkg/networking/core/listener_waypoint.go [hunk 6]
```diff
@@ -396,11 +324,19 @@ func (lb *ListenerBuilder) buildWaypointInternal(wls []model.WorkloadInfo, svcs
...
-		if isAmbientEastWestGateway && features.EnableAmbientMultiNetwork {
+		if isEastWestGateway && features.EnableAmbientMultiNetwork {
 			waypoint = lb.findServiceWaypoint(svc)
 		}
 
 		svcAddresses := svc.GetAllAddressesForProxy(lb.node)
+		if features.EnableAmbientMultiNetwork {
+			key := fmt.Sprintf("%s/%s", svc.Attributes.Namespace, svc.Hostname)
+			svcInfo := lb.push.ServiceInfo(key)
+			if svcInfo != nil && svcInfo.Scope == model.Global {
```
Comment (krinkinmu) [inline pilot/pkg/networking/core/listener_waypoint.go]: nit: I'd suggest moving this whole if statements into globalServiceVIPs, so that in this function you can just do something like the following unconditionally:

svcAddresses = lb.globalServiceVIPs(svc)

Motivation is that buildWaypointInternal is already quite long and, as a result, not easy to follow - adding to that even more details of multicluster logic exacerbates the problem.

File: pilot/pkg/networking/core/listener_waypoint.go (hunk 4 above)
Comment (krinkinmu) [reply pilot/pkg/networking/core/listener_waypoint.go]: It looks close to what I'd probably do now. Thank you!

File: pilot/pkg/model/push_context.go (hunk 5 above)
Comment (krinkinmu) [reply pilot/pkg/model/push_context.go]: Actually, I think I misread the code, and it's even easier - we don't need any changes to NewConfigGenTest or TestOptions.

When it comes to calling ServiceInfo on the aggregate controller, we only look at the Kubernetes provider, so we can just provide an additional registry with the provider.Kubernetes provider ID and that should be enough to inject the custom ServiceDiscovery implementation.

Comment (garrettheel) [reply pilot/pkg/model/push_context.go]: Sounds good - I was able to get this to work, I just needed to implement `ServiceInfo` on the in-memory service discovery

File: pilot/pkg/networking/core/listener_waypoint.go (hunk 6 above)
Comment (garrettheel) [reply pilot/pkg/networking/core/listener_waypoint.go]: Updated

File: pilot/pkg/networking/core/listener_waypoint.go [hunk 7]
```diff
@@ -1263,3 +1195,32 @@ func buildCommonConnectTLSContext(proxy *model.Proxy, push *model.PushContext) *
 	security.EnforceCompliance(ctx)
 	return ctx
 }
+
+// globalServiceVIPs returns network-filtered and IP-family-filtered VIP addresses
+// from a globally-scoped service.
+func (lb *ListenerBuilder) globalServiceVIPs(svc *model.Service) []string {
```
Comment (krinkinmu) [inline pilot/pkg/networking/core/listener_waypoint.go:1274]: nit: I would even check the feature flag here instead of buildWaypointInternal, but not critical.

File: pilot/pkg/networking/core/listener_builder_test.go [hunk 8]
```diff
@@ -1014,6 +1022,365 @@ func TestExtProcExistForInferencePoolEnabledGateway(t *testing.T) {
...
+	if l.FilterChainMatcher == nil {
+		return nil
+	}
+
+	mt, ok := l.FilterChainMatcher.MatcherType.(*matcher.Matcher_MatcherTree_)
+	if !ok || mt.MatcherTree == nil {
+		return nil
+	}
+
+	// When ambient multi-network is enabled, hostnames are preferred and the IP matcher
```
Comment (krinkinmu) [inline pilot/pkg/networking/core/listener_builder_test.go]: nit: I'd rather not call it a preference here, you can just say that the matching configuration first compares against host names and if none matched falls back to VIPs, not critical - but it might confuse folks reading the comment later.

File: pilot/pkg/networking/core/listener_builder_test.go [hunk 9]
```diff
@@ -1014,6 +1022,365 @@ func TestExtProcExistForInferencePoolEnabledGateway(t *testing.T) {
...
+				ConfigNamespace: "default",
+				Metadata: &model.NodeMetadata{
+					ClusterID: "cluster-1",
+					Network:   network.ID(tc.proxyNetwork),
+				},
+				IPAddresses: tc.proxyIPs,
+			}
+			proxy = cg.SetupProxy(proxy)
+
+			lb := &ListenerBuilder{
```
Comment (krinkinmu) [inline pilot/pkg/networking/core/listener_builder_test.go:1172]: nit: I think you should be able to use `cg.Listeners()` here and then just find the listener by name using `MainInternalName` constant (e.g., `xdstest.ExtractListener(MainInternalName, listeners)`). The rest of the logic remains the same. Again, not critical, just more in line with the rest of the tests.

**Review by stevenctl — DISMISSED** [review]
It may be possible that VIPs overlap beetween clusters, wouldn't' it be preferable to make sure we always send hostnames in the HBONE header on the client side?

**Comment by krinkinmu** [comment]
I think VIPs can overlap on different networks, when you're on the same
network overlapping VIPs will result in incorrect routing sometimes.

File: pilot/pkg/networking/core/listener_builder_test.go (hunk 9 above)
Comment (garrettheel) [reply pilot/pkg/networking/core/listener_builder_test.go:1172]: This is possible but it requires implementing `ServicesForWaypoint` in `serviceregistry/memory/discovery.go` to return non-nil, and adding something like `func (sd *ServiceDiscovery) AddServiceInfoForWaypoint(waypointName string, ...)` in order for the test to register the association. Do you want to go that route or did you have something else in mind?

**Comment by stevenctl** [comment]
Pod IPs can overlap on different networks, which makes using a gateway a hard requirement, regardless of pod IP reachability. 

On multi-cluster, regardless of networks, we don't make any guarantees about VIPs being safe for re-use. Sidecar->SNI gateway used a hostname via the SNI header. E/W gateway in ambient currently has the ztunnel sending a hostname. 

i think we fix this in ztunnel.

**Comment by krinkinmu** [comment]
> Pod IPs can overlap on different networks, which makes using a gateway a hard requirement, regardless of pod IP reachability.

That's what I was saying - they can overlap, but only when on different networks. VIPs cannot overlap when it's the same network. This PR is only about the case of multi-cluster single-network, so overlapping VIPs are not a problem.

Also, at least in sidecar mode E/W gateway is not actually a hard requirement even in multi-network case - direct reachability is enough and non-overlapping VIPs are enough - we discussed that somewhat surprising behavior in a WG meeting not that long ago.

> On multi-cluster, regardless of networks, we don't make any guarantees about VIPs being safe for re-use. Sidecar->SNI gateway used a hostname via the SNI header. E/W gateway in ambient currently has the ztunnel sending a hostname.

@stevenctl I don't quite understand what you mean by "re-use" here? VIPs assigned to services at any given point in time must be unique within the same network, otherwise we will have other issues.


I'm not against the suggestion to just switch matching to service names instead of VIPs in principle, but that change would go a bit beyon just multi-cluster feature. E.g., if we are doing this change, then I don't see a good reason why this behavior has to be multi-cluster specific at least - and we should not multiply different behaviors we need to support without a good reason.

**Comment by stevenctl** [comment]
> I don't see a good reason why this behavior has to be multi-cluster specific

Totally agree

> VIPs cannot overlap when it's the same network
>  non-overlapping VIPs are enough

In non ambient multi-network we don't require VIPs to be unique across clusters (regardless of network), we simply avoid running into that issue by requiring that you have a local definition of a Service you want to access in multi-cluster and only ever using `ClusterViPs[local cluster id]`. 

Maybe we document that you want the VIP pools to be unique but _technically_ we don't require it. 

But starting with ambient, looks like we now introduce a harder requirement that "VIPs are unique across the network" so I tthis is ok, but I think we can do slightly better.

**Comment by keithmattix** [comment]
For a while, sidecar multinetwork with "smartDNS" didn't require a local service; DNS resolution took care of it. And in that situation, I think VIP uniqueness was required

**Comment by krinkinmu** [comment]
@stevenctl given that switching to hostnames affects not just single-network multicluster, I'd say we should prototype and validate the approach against somewhat first. I'm less concerned with the way this PR does things, because it only affects single-network multicluster and single-network multicluster is in early stages at the moment.

**Comment by garrettheel** [comment]
Just to illustrate, I created https://github.com/istio/ztunnel/pull/1776 (have not tested E2E yet) which I think is what @stevenctl is proposing we do instead. I agree this is much simpler/cleaner, though seems like the blast radius would also be larger and it could be complementary to this change.

I don't have a strong opinion here so happy to go with whichever solution you all decide on.

**Comment by stevenctl** [comment]
* Without this: Clients that don't know to send hostnames instead of VIPs will likely just fail b/c they send a VIP we don't set up matching for
* With this: We match those remote cluster VIPs (only if same network) so if we have proper VIP uniqueness things just work 

i think i'm ok with this

**Comment by keithmattix** [comment]
I think we have a flake/break from another PR
