### PR TITLE
TTL clamping for leaf certificates

### LINKED ISSUE #59768: istiod issues leaf certs with NotAfter beyond signing cert
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Istiod's certificate signing path does not clamp the leaf certificate's NotAfter to the signing certificate's NotAfter. This means istiod can issue leaf/workload certificates that outlive its own intermediate CA certificate, causing certificate chain validation failures when the intermediate expires before the leaf.

### Version

```Text
client version: 1.29.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lcopi**
Closes: https://github.com/istio/istio/issues/59768

**Summary**
Prevents leaf certificates from outliving their signing certificate by adding TTL clamping logic in certificate generation. This fixes TLS handshake failures where the intermediate CA has shorter validity than requested leaf certificate TTL.

**Changes**
- Added expired signing certificate guard in `genCertTemplateFromCSR` 
- Added TTL clamping when leaf cert would extend beyond signing cert NotAfter
- Added unit tests `TestGenCertFromCSRWithTTLClamping` and `TestSignCSRWithTTLClamping` validating IstioCA.Sign() path

### CODE REVIEW

File: security/pkg/pki/ca/ca_test.go [hunk 1]
```diff
@@ -889,11 +1003,12 @@ func TestBuildSecret(t *testing.T) {
 }
 
 func createCA(maxTTL time.Duration, ecSigAlg util.SupportedECSignatureAlgorithms) (*IstioCA, error) {
-	// Generate root CA key and cert.
+	// Generate root CA key and cert. Use a 2-year TTL so the signing cert's validity does not
```
Comment (jaellio) [inline security/pkg/pki/ca/ca_test.go]: nit: Why 2 years? During testing the leaf cert ttl should be much smaller

Comment (lcopi) [reply security/pkg/pki/ca/ca_test.go]: I chose it arbitrarily because it seemed like a valid real world amount of time. I can make it shorter if desired

File: security/pkg/pki/util/generate_cert.go [hunk 2]
```diff
@@ -327,13 +329,24 @@ func genCertTemplateFromCSR(csr *x509.CertificateRequest, subjectIDs []string, t
 	if err != nil {
 		return nil, err
 	}
+
+	// Reject expired signing certificates to prevent issuing already-expired leaf certificates
+	if signingCert != nil && !now.Before(signingCert.NotAfter) {
+		return nil, fmt.Errorf("signing certificate has expired at %v", signingCert.NotAfter)
+	}
+
+	notAfter := now.Add(ttl)
```
Comment (jaellio) [inline security/pkg/pki/util/generate_cert.go:339]: nit: I don't think this matters, but do we want `notAfter` and `notBefore` to be relative to the same `now` value?

File: security/pkg/pki/util/generate_cert.go [hunk 3]
```diff
@@ -327,13 +329,24 @@ func genCertTemplateFromCSR(csr *x509.CertificateRequest, subjectIDs []string, t
...
+	if signingCert != nil && !notAfter.Before(signingCert.NotAfter) {
```
Comment (jaellio) [inline security/pkg/pki/util/generate_cert.go:340]: Thoughts on adding a debug log here just in case a user is confused regrading an unexpected ttl? This shouldn't and doesn't need to contain any identifying information.

File: security/pkg/pki/util/generate_cert_test.go [hunk 4]
```diff
@@ -969,3 +969,141 @@ func TestMergeCertOptions(t *testing.T) {
...
+		},
+		{
+			name:          "TTL longer than signing cert - clamped",
+			ttl:           2 * time.Hour,
+			expectClamped: true,
+		},
+		{
+			name:          "TTL exactly equals signing cert remaining lifetime - clamped (boundary)",
+			ttl:           time.Hour,
+			expectClamped: true,
```
Comment (jaellio) [inline security/pkg/pki/util/generate_cert_test.go]: I am not sure this test case covers a consistent/meaningful scenario - Based on when this test case runs relative to when the CA is created, `now` + `ttl` may exceed the `notAfter` of the CA. While the value would be clamped regardless, the test name isn't accurate.

File: security/pkg/pki/util/generate_cert_test.go [hunk 5]
```diff
@@ -969,3 +969,141 @@ func TestMergeCertOptions(t *testing.T) {
...
+			if c.expectClamped {
+				// Leaf NotAfter must not exceed signing cert NotAfter.
+				if leafCert.NotAfter.After(signingCert.NotAfter) {
+					t.Errorf("leaf cert NotAfter (%v) exceeds signing cert NotAfter (%v)", leafCert.NotAfter, signingCert.NotAfter)
+				}
+				if !leafCert.NotAfter.Equal(signingCert.NotAfter) {
+					t.Errorf("expected leaf cert NotAfter to be clamped to %v, got %v", signingCert.NotAfter, leafCert.NotAfter)
+				}
+			} else {
+				// Leaf NotAfter should be approximately now+ttl (within a few seconds).
```
Comment (jaellio) [inline security/pkg/pki/util/generate_cert_test.go]: These seems subject to test flakiness.

File: security/pkg/pki/ca/ca_test.go (hunk 1 above)
Comment (lcopi) [reply security/pkg/pki/ca/ca_test.go]: shortened it to double the leaf length in https://github.com/istio/istio/pull/59766/commits/399b6492930cd42be195ebab6a27320eafd1ef5a

File: security/pkg/pki/util/generate_cert.go (hunk 3 above)
Comment (lcopi) [reply security/pkg/pki/util/generate_cert.go:340]: added a debug log in https://github.com/istio/istio/pull/59766/commits/399b6492930cd42be195ebab6a27320eafd1ef5a

File: security/pkg/pki/util/generate_cert_test.go (hunk 4 above)
Comment (lcopi) [reply security/pkg/pki/util/generate_cert_test.go]: removed in https://github.com/istio/istio/pull/59766/commits/399b6492930cd42be195ebab6a27320eafd1ef5a

File: security/pkg/pki/util/generate_cert_test.go (hunk 5 above)
Comment (lcopi) [reply security/pkg/pki/util/generate_cert_test.go]: reworked the logic in https://github.com/istio/istio/pull/59766/commits/399b6492930cd42be195ebab6a27320eafd1ef5a

**Comment by jaellio** [comment]
Will take a look tomorrow!

**Review by jaellio — APPROVED** [review]
