### PR TITLE
Fix #10975. Avoid Prometheus export error by using default label core…

### LINKED ISSUE #10975: Prometheus export errors in Galley logs
**Describe the bug**
I installed a recent Istio 1.1 release. (48caa5300d4552a31ec7700a64b1640bf1c7f705)
Galley emits log messages every few seconds complaining about an error during the export of Prometheus metrics:
```
2019-01-15T06:53:23.238319Z     info    Failed to export to Prometheus: inconsistent label cardinality: expected 3 label values but got 2 in []string{"v1", "Pod"}
```

It looks like Galley emits metrics about the pods in the Kubernetes cluster and tries to created labelled metrics containing the apiVersion, kind and group.
For Pods the group seems to be empty.

**Expected behavior**
No Failure messages in the logs.

**Steps to reproduce the bug**
Install Istio 1.1.
Not much more that I have done.

**Version**
Current Istio 1.1 running on Kubernetes 1.10.3 as delivered by Docker for Mac.

**Installation**
```
helm template ~/go/src/istio.io/istio/install/kubernetes/helm/istio --name istio --namespace istio-system -f values-istio-auth.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set global.hub=istio --set global.tag=48caa5300d4552a31ec7700a64b1640bf1c7f705 --set tracing.enabled=true|k create -f -
```

**Environment**
Running on my local Mac.

### PR DESCRIPTION
**Pull request by robertpanzer**
… as K8s group if not set

Galley records metrics about the Kubernetes resource events that it processes and uses the apiVersion, group and kind as metric labels.
For Pods and Nodes the group is empty.
Therefore the export to Prometheus fails:
```
2019-01-15T06:52:38.260821Z     info    Failed to export to Prometheus: inconsistent label cardinality: expected 3 label values but got 2 in []string{"
v1", "Node"}                                                                                                                                          
2019-01-15T06:52:38.261000Z     info    Failed to export to Prometheus: inconsistent label cardinality: expected 3 label values but got 2 in []string{"
v1", "Pod"}                                                                                                                                            
```

This PR tries to fix this problem reported at #10975 by using the kind `core` if it is empty.

For me this made the log entries disappear.

### CODE REVIEW

File: galley/pkg/kube/source/monitoring.go [hunk 1]
```diff
@@ -88,6 +89,9 @@ func recordConverterResult(success bool, apiVersion, group, kind string) {
 	} else {
 		metric = sourceConversionFailure
 	}
+	if len(group) == 0 {
+		group = coreGroup
+	}
```
Comment (ayj) [inline galley/pkg/kube/source/monitoring.go]: lgtm

Can you add a short one-line comment about why this is needed for future readers?

Comment (robertpanzer) [reply galley/pkg/kube/source/monitoring.go]: Thanks for the feedback.
I added a comment, I hope it makes things clearer.

**Comment by robertpanzer** [comment]
Rebased and squashed
