### PR TITLE
[Galley] Fix for ServiceEntry event ordering

### LINKED ISSUE #12820: TestConversion/networking.istio.io_v1alpha3_synthetic_serviceEntry is flaky
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12819/istio-integ-local-tests/7409

### PR DESCRIPTION
**Pull request by nmittler**
The integration test was encountering this, exposing a real bug. If nodes/pod events occur after service/endpoints (which should generally be unusual) then it is possible to have a ServiceEntry missing pod/node information (e.g. locality).

Fixes #12820

### CODE REVIEW

File: galley/pkg/runtime/projections/serviceentry/convert/convert.go [hunk 1]
```diff
@@ -123,22 +121,16 @@ func Endpoints(endpoints *coreV1.Endpoints, pods pod.Cache, nodes node.Cache, ou
...
 		for _, address := range subset.Addresses {
 			locality := ""
+			var labels map[string]string
 
 			ip := address.IP
 			p, hasPod := pods.GetPodByIP(ip)
-			var labels map[string]string
 			if hasPod {
 				labels = p.Labels
+				locality = p.Locality
```
Comment (ozevren) [inline galley/pkg/runtime/projections/serviceentry/convert/convert.go]: Is this changing behavior? Always using pod locality?

Comment (nmittler) [reply galley/pkg/runtime/projections/serviceentry/convert/convert.go]: No change in behavior.  Pods don't have locality, nodes do.  I've merged the node and pod caches into one (podCache). The podCache is now responsible for detecting when pods change (including if their backing node changed). This abstracts away the need to separately track nodes from the converter ... the pod has everything it needs now.
