### PR TITLE
embed on Windows uses forward slash

### LINKED ISSUE #32380: Cannot install 1.10.0-rc.0 on Windows 10 Enterprise
**Bug description**

I unzipped `istio-1.10.0-alpha.1-win.zip` and set `PATH` to the `bin` directory. Then I `cd`ed to the `manifest` subdirectory and invoked `istioctl install --manifests . --verify --set profile=demo --set values.global.jwtPolicy=first-party-jwt --skip-confirmation=true` and got the error message _error: list files: open charts\base: invalid argument_. The whole output is appended at the end.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
No installation problem as with 1.9.x.

**Steps to reproduce the bug**
See above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

$ istioctl version --remote:
no running Istio pods in "istio-system"_
1.10.0-alpha.1
$ kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.7

**How was Istio installed?**
See above

**Environment where the bug was observed (cloud vendor, OS, etc)**
Windows 10 Enterprise 20H2, Docker Desktop 3.3.1

**Complete installation output**
```
istioctl install --manifests . --verify --set profile=demo --set values.global.jwtPolicy=first-party-jwt --skip-confirmation=true
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.10/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
Error: failed to install manifests: errors occurred during operation: failed to create Istio control plane with spec:
profile:"demo" install_package_path:"." hub:"docker.io/istio" tag:1.10.0-alpha.1 mesh_config:<key:"accessLogFile" value:/dev/stdout > mesh_config:<key:"defaultConfig" value:map[proxyMetadata:map[]] > mesh_config:<key:"enablePrometheusMerge" value:true > components:<base:<enabled:<BoolValue:<value:true > > > pilot:<enabled:<BoolValue:<value:true > > tag:<nil> spec:<nil> k8s:<env:<name:"PILOT_TRACE_SAMPLING" value:"100" > resources:<requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"100Mi" > > > > cni:<enabled:<BoolValue:<> > tag:<nil> spec:<nil> > istiod_remote:<enabled:<BoolValue:<> > tag:<nil> spec:<nil> > ingress_gateways:<enabled:<BoolValue:<value:true > > name:"istio-ingressgateway" tag:<nil> k8s:<resources:<requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"40Mi" > > service:<ports:<name:"status-port" port:15021 targetPort:<IntOrString:<type:0 intVal:15021 strVal:"" > > > ports:<name:"http2" port:80 targetPort:<IntOrString:<type:0 intVal:8080 strVal:"" > > > ports:<name:"https" port:443 targetPort:<IntOrString:<type:0 intVal:8443 strVal:"" > > > ports:<name:"tcp" port:31400 targetPort:<IntOrString:<type:0 intVal:31400 strVal:"" > > > ports:<name:"tls" port:15443 targetPort:<IntOrString:<type:0 intVal:15443 strVal:"" > > > > > > egress_gateways:<enabled:<BoolValue:<value:true > > name:"istio-egressgateway" tag:<nil> k8s:<resources:<requests:<key:"cpu" value:"10m" > requests:<key:"memory" value:"40Mi" > > > > > values:<key:"base" value:map[enableCRDTemplates:false validationURL:] > values:<key:"gateways" value:map[istio-egressgateway:map[autoscaleEnabled:false env:map[] name:istio-egressgateway secretVolumes:[map[mountPath:/etc/istio/egressgateway-certs name:egressgateway-certs secretName:istio-egressgateway-certs] map[mountPath:/etc/istio/egressgateway-ca-certs name:egressgateway-ca-certs secretName:istio-egressgateway-ca-certs]] type:ClusterIP zvpn:map[]] istio-ingressgateway:map[autoscaleEnabled:false env:map[] name:istio-ingressgateway secretVolumes:[map[mountPath:/etc/istio/ingressgateway-certs name:ingressgateway-certs secretName:istio-ingressgateway-certs] map[mountPath:/etc/istio/ingressgateway-ca-certs name:ingressgateway-ca-certs secretName:istio-ingressgateway-ca-certs]] type:LoadBalancer zvpn:map[]]] > values:<key:"global" value:map[configValidation:true defaultNodeSelector:map[] defaultPodDisruptionBudget:map[enabled:true] defaultResources:map[requests:map[cpu:10m]] imagePullPolicy: imagePullSecrets:[] istioNamespace:istio-system istiod:map[enableAnalysis:false] jwtPolicy:first-party-jwt logAsJson:false logging:map[level:default:info] meshNetworks:map[] mountMtlsCerts:false multiCluster:map[clusterName: enabled:false] network: omitSidecarInjectorConfigMap:false oneNamespace:false operatorManageWebhooks:false pilotCertProvider:istiod priorityClassName: proxy:map[autoInject:enabled clusterDomain:cluster.local componentLogLevel:misc:error enableCoreDump:false excludeIPRanges: excludeInboundPorts: excludeOutboundPorts: image:proxyv2 includeIPRanges:* logLevel:warning privileged:false readinessFailureThreshold:30 readinessInitialDelaySeconds:1 readinessPeriodSeconds:2 resources:map[limits:map[cpu:2000m memory:1024Mi] requests:map[cpu:10m memory:40Mi]] statusPort:15020 tracer:zipkin] proxy_init:map[image:proxyv2 resources:map[limits:map[cpu:2000m memory:1024Mi] requests:map[cpu:10m memory:10Mi]]] sds:map[token:map[aud:istio-ca]] sts:map[servicePort:0] tracer:map[datadog:map[] lightstep:map[] stackdriver:map[] zipkin:map[]] useMCP:false] > values:<key:"istiodRemote" value:map[injectionURL:] > values:<key:"pilot" value:map[autoscaleEnabled:false autoscaleMax:5 autoscaleMin:1 configMap:true cpu:map[targetAverageUtilization:80] deploymentLabels:<nil> enableProtocolSniffingForInbound:true enableProtocolSniffingForOutbound:true env:map[ENABLE_LEGACY_FSGROUP_INJECTION:false] image:pilot keepaliveMaxServerConnectionAge:30m nodeSelector:map[] replicaCount:1 traceSampling:1] > values:<key:"telemetry" value:map[enabled:true v2:map[enabled:true metadataExchange:map[wasmEnabled:false] prometheus:map[enabled:true wasmEnabled:false] stackdriver:map[configOverride:map[] enabled:false logging:false monitoring:false topology:false]]] >
error: list files: open charts\base: invalid argument
```

### PR DESCRIPTION
**Pull request by ericvn**
Attempting to replace the use of the os.FileSeparator with `/` as embed continues to use `/` even on Windows.

Fixes #32380. 

This gets me by a number of errors.

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: operator/pkg/helm/helm.go [hunk 1]
```diff
@@ -63,7 +63,7 @@ type TemplateRenderer interface {
 // The format of helmBaseDir and profile strings determines the type of helm renderer returned (compiled-in, file,
 // HTTP etc.)
 func NewHelmRenderer(operatorDataDir, helmSubdir, componentName, namespace string) TemplateRenderer {
-	dir := filepath.Join(ChartsSubdirName, helmSubdir)
+	dir := strings.Join([]string{ChartsSubdirName, helmSubdir}, "/")
```
Comment (howardjohn) [inline operator/pkg/helm/helm.go:66]: not a criticism of your code but of embedd - this kind of sucks? :slightly_smiling_face:. You would think that you would be able to write code for both embed and standard files

Comment (howardjohn) [reply operator/pkg/helm/helm.go:66]: Actually - does this work? since I think we do use this code for embedded and standard files?

This may fix windows for `istioctl install` but not `istioctl install -d manifests/` possibly?

Comment (ericvn) [reply operator/pkg/helm/helm.go:66]: I haven't tried anything with passed in paths, and I suspect that may cause more issues.  I at least wanted to publicize what changes were needed to make a few of the failing commands I was trying to work. Things like `istioctl manifest generate --dry-run --set profile=demo` and  `istioctl manifest generate --dry-run --set profile=demo --manifests manifests` which had different errors originally now both yield generated output so things are getting further.

**Comment by ericvn** [comment]
I did try commands like `istioctl manifest generate --dry-run --set profile=demo --manifests some-directory/manifests` and `istioctl manifest generate --dry-run --set profile=demo --manifests somedirectory\manifests` as well as `istioctl manifest generate --dry-run --set profile=demo --manifests manifests -f samples/operator/pilot-k8s.yaml` and `istioctl manifest generate --dry-run --set profile=demo --manifests manifests -f samples\operator\pilot-k8s.yaml` and they all generated data.

File: operator/pkg/helm/helm.go (hunk 1 above)
Comment (ericvn) [reply operator/pkg/helm/helm.go:66]: Comment below, but I did try using --manifests(-d) and --file with `istioctl manifest` and that worked. I've asked for other things to test in Slack. For now, I'm not seeing any failures, so I'm not pursuing more changes and this is ready to go.

**Review by Monkeyanator — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
