### PR TITLE
Fix envoy memory leaks occur in scenarios with high packet loss rates when using HTTPS

### LINKED ISSUE #52850: Envoy memory leaks occur in scenarios with high packet loss rates when using HTTPS
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have observed that when using versions of Istio 1.19 and above, Envoy exhibits memory leaks under HTTPS scenarios with high packet loss rates over the network:

image

Our investigation revealed that the "envoy_listener_downstream_pre_cx_active" metric for Envoy aligns with the upward trend in memory usage:

image

Upon further investigation, we discovered this Istio [PR](https://github.com/istio/istio/pull/46227/files#diff-52cfa21853af325e375479ea6e0046ca6c982f094727bd3b623d066ecf966c51R584), which sets the `listener_filters_timeout` to `0s`. This configuration disables Envoy's timer for checking execution timeouts on listener filters.

The logic here is flawed. The timer should not be canceled as long as there exists a filter in the listener filters. In our scenario, under the HTTPS context, the TLSInspector filter is required, which necessitates reading the request data until the `TLS Client Hello` parsing is completed.

In an environment with severe packet loss on the network, the server may not receive a complete TLS Client Hello, leading to ActiveTcpSocket objects in Envoy never being reclaimed, resulting in a memory leak:

https://github.com/envoyproxy/envoy/blob/5dd33ce39e2977cb85a9c72dbf742e10c8483257/source/common/listener_manager/active_tcp_socket.cc#L153-L154

### Version

```Text
control plane version: >= 1.19
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by johnlanni**
**Please provide a description of this PR:**

fixes #52850

### CODE REVIEW

File: pilot/pkg/networking/core/listener.go [hunk 1]
```diff
@@ -592,7 +592,10 @@ func buildListenerFromEntry(builder *ListenerBuilder, le *outboundListenerEntry,
 
 	if needHTTPInspector {
 		l.ListenerFilters = append(l.ListenerFilters, xdsfilters.HTTPInspector)
-		// Enable timeout only if they configure it and we have an HTTP inspector.
+	}
+
```
Comment (ramaraochavali) [inline pilot/pkg/networking/core/listener.go:596]: if no listener filters are configured, why would envoy check for this timeout?

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: I think before this change we only configured a timeout if the http inspector was added, not taking into account the TLS inspector

**Comment by zirain** [comment]
I do believe this worth notes and tests

File: pilot/pkg/networking/core/listener.go (hunk 1 above)
Comment (ramaraochavali) [reply pilot/pkg/networking/core/listener.go:596]: Ok. I see

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: No, we did not configure the timeout at all in 99.99% of cases. See the `This is really unsafe, so hopefully not used...` comment. Its off by default.

**Review by howardjohn — CHANGES_REQUESTED** [review]
See comment thread

File: pilot/pkg/networking/core/listener.go (hunk 1 above)
Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: @howardjohn Yes, currently, the timeout is only configured when an HTTPInspector exists in the listener filters (with a default value of 5 seconds, which can be customized by users, though there's a risk involved if users set this value themselves, as I understand is the point of this comment);
The [issue](https://github.com/istio/istio/issues/52850) we encountered is that when there's no HTTPInspector but a TLSInspector present in the listener filters, not setting a timeout leads to a memory leak.

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: I don't believe we are setting the timeout in any case by default. there is an option to do it for http but it's off by default because it's unsafe. 

We have seen that legitimate traffic fails even with large timeouts O(5s)

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: @howardjohn Oh, yes, I see my mistake now. By default, there indeed isn't any timeout set. It appears that my fix should involve adding a default timeout. Otherwise, in scenarios with high packet loss, the issue of memory leaks would remain unresolved.

It might be worth considering directly removing this configuration and adopting Envoy's default 15-second timeout, as was the behavior in Istio versions prior to 1.19.

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: In my view, if a client's ClientHello message is not completed within 5 seconds, this traffic should not be considered legitimate traffic; instead, it may potentially be a part of a Denial-of-Service attack utilizing slow requests.

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: I agree we shouldn't indefinitely hold the connection/memory btw. But we should make sure we do not continue on timeout, and that the timeout is large... larger than 5s. 15s maybe. 

Is there a difference in inbound/outbound/gateway?

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: Note as well it's the timeout to detect the *payload* of the tcp connection matches a certain protocol... what we want is really "timeout if the connection isn't established"

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: but for example, it's perfectly legitimate to open a connection, wait 60s, then send some data on it. We cannot reject that - real apps do this for legitimate reasons

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: maybe we need an alternative configuration in envoy to timeout connection established

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-field-config-listener-v3-filterchain-transport-socket-connect-timeout?

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: @keithmattix This configuration will not work because the transport socket connect timeout is set after the listener filters have been processed. I don't think additional timeout configurations are necessary; since listener filters require network I/O to read data, a timeout should be set when listener filters are present.

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: The issue is that it's legitimate (and seen in real world) to open a connection and not send data for a long time. Not all protocols are request-response protocols. 

The issue with packet loss seems to be around connections failing to establish not establishing and then not sending data, right?

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: Ah right that config is per filter chain. In that case yeah the listener filter timeout is really what we want to check. Feels like maybe istio shouldn't set it by default but allow for easier override (e.g to the user-
Defined idle timeout)

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: I realized my comments about connection establishment didn't make sense since that is handed by the OS... 

In the case where there was/is no listener filters, how would you solve this? the transport socket timeout? maybe you need both then...? 


The thing is it's not safe to set the timeout for protocol detection. TLS inspector for known-tls traffic is a bit different

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: Yeah if there's no listener filter, you use the transport socket timeout since there wouldn't be any listener filters to execute and you'd go straight to FCM. Protocol detection is a conundrum...but ultimately you do need an upper bound. For an edge proxy, what's the use case for a downstream opening a connection and not sending any data for longer than, say, 15s? 30s?

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: Yes, inspired by the discussions above, I believe the `transport_socket_connect_timeout` should also be set, as stated in the Envoy [issue](https://github.com/envoyproxy/envoy/issues/11426) where this feature is provided:

>  The effective value of these timeouts could be reduced based on memory pressure to **increase resiliency to memory exhaustion attacks** and improving the proxy's ability to accept legitimate connections/requests.

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: We have tls_inspector at edge/ingress so sounds like a listener_filter would be valid there (maybe as part of #2471?). I take your point on arbitrary protocols (not including TLS), but it certainly seems like it ought to be configurable?

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: It is configurable: ProtocolDetectionTimeout

I am fine with a timeout for TLS_inspector on the edge as well for the reasons above

Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:596]: Ah it's undocumented :) https://github.com/istio/api/blob/6e7441d4920eaa11dd660dbea6b69f738ec5ede3/mesh/v1alpha1/config.proto#L68. Sounds good

**Comment by jaellio** [comment]
@johnlanni could you add a release note for this fix in `releasenotes/notes`?

File: pilot/pkg/networking/core/listener.go (hunk 1 above)
Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: Based on the above discussion, I restored the default value (0) for ProtocolDetectionTimeout and set this timeout based on the configuration when either the HTTP Inspector or the TLS Inspector is present.
It appears that we should also modify this part of the api repository to expose this configuration in the documentation: https://github.com/istio/api/blob/6e7441d4920eaa11dd660dbea6b69f738ec5ede3/mesh/v1alpha1/config.proto#L52

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:596]: I really don't think we want the "continue on filter timeout" behavior for your use case..

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: I agree, it has been modified, and I have also added the handling of logic related to the gateway.

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:596]: @howardjohn If you think these changes are fine, I will further supplement the release notes.

**Comment by howardjohn** [comment]
do we need to change the sidecars or only gateway?

**Comment by howardjohn** [comment]
I worry for sidecars we have already given users 2 options, and they can pick which one is less bad for them. but for gateways there is a clearly best option

**Comment by johnlanni** [comment]
@howardjohn I understand your suggestion, which is to make the ProtocolDetectionTimeout configuration only effective for the sidecar (as it was before), and set a fixed optimal default value for the gateway scenario (I am considering removing this configuration, which would use Envoy's default value of 15 seconds)

**Comment by hzxuzhonghu** [comment]
It is not safe to change gateway listener filter timeout from 0 to 15s, there should be an option. I think we can reuse meshConfig.ProtocolDetectionTimeout rather than introducing another one.  It is not documented this option is only for sidecar

**Comment by howardjohn** [comment]
> It is not safe to change gateway listener filter timeout from 0 to 15s, there should be an option. I think we can reuse meshConfig.ProtocolDetectionTimeout rather than introducing another one. It is not documented this option is only for sidecar

If it's not safe to change the default to 15s, then it's also not safe to change it to meshConfig.ProtocolDetectionTimeout which is probably even less than 15s for users who set it? From the introduction of protocol sniffing it was intended to never be used on gateway so I'd avoid changing that 

What makes you think it's not safe at 15s on gateway? I originally felt the same but changed my mind so am curious your view

**Comment by hzxuzhonghu** [comment]
Some protocols doesnot send message immediately after connection established, changing timeout to 15 should cause the connection closed. Especially for server first protocol, we cannot assume when the data packet can be sent. 

I admit indefinitely waiting is not good, this can cause dos attack.  We should leave the option to user.

**Comment by howardjohn** [comment]
yeah yes to clarify I am only in favor of default to a timeout (of 15s) for gateway TLS - where we know it's not a server first protocol

**Comment by johnlanni** [comment]
@keithmattix @howardjohn @hzxuzhonghu Based on the above discussion and my careful consideration, I have decided to set a timeout exclusively for the gateway scenario. For listener filters, I will utilize Envoy's default timeout values. As for the transport socket connect timeout, I have established a default timeout of 15 seconds. This configuration enhances the robustness of scenarios employing Istio as a gateway in handling memory exhaustion attacks

File: pilot/pkg/networking/core/listener.go [hunk 2]
```diff
@@ -1111,18 +1114,20 @@ func buildGatewayListener(opts gatewayListenerOpts, transport istionetworking.Tr
...
 
 	res := &listener.Listener{
 		TrafficDirection: core.TrafficDirection_OUTBOUND,
 		ListenerFilters:  listenerFilters,
 		FilterChains:     filterChains,
-		// For Gateways, we want no timeout. We should wait indefinitely for the TLS if we are sniffing.
-		// The timeout is useful for sidecars, where we may operate on server first traffic; for gateways if we have listener filters
-		// we know those filters are required.
-		ContinueOnListenerFiltersTimeout: false,
-		ListenerFiltersTimeout:           durationpb.New(0),
```
Comment (keithmattix) [inline pilot/pkg/networking/core/listener.go:1125]: I don't love that we're taking away functionality here; this field is no longer overridable. Should the proxy detection timeout override the default? Should we just add a new field?

**Review by keithmattix — CHANGES_REQUESTED** [review]

File: pilot/pkg/networking/core/listener.go (hunk 2 above)
Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:1125]: I feel that too many configuration options can confuse users, and if users really have the need to make changes, they can do so through EnvoyFilter. Here, the behavior remains consistent with before, using default values, but in a more straightforward manner, directly employing Envoy's default settings.

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:1125]: FWIW I think this is effectively the same as the default in 1.19 that was unintentionally (I think?) change. I don't really see too much usage for someone to change the timeout here. Did you expect users would want to make it longer or shorter?

**Review by howardjohn — COMMENTED** [review]
LGTM personally as is -- thanks for the iteration here.

File: pilot/pkg/networking/core/listener.go (hunk 2 above)
Comment (keithmattix) [reply pilot/pkg/networking/core/listener.go:1125]: Oh my bad, I thought the protocol detect timeout previously affected this. If this is the same as 1.19, then this LGTM

**Review by keithmattix — COMMENTED** [review]
Resetting my change request, but this does need tests IMO

File: pilot/pkg/networking/core/listener.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pilot/pkg/networking/core/listener.go:1125]: #47970 intended to set no timeout

Comment (howardjohn) [reply pilot/pkg/networking/core/listener.go:1125]: > #47970 intended to set no timeout

ah thanks, forgot about that. 

I definitely think part of that PR is right - we should never continue on timeout. Whether we have no timeouts at all is another thing... it does seem like a good practice in general to have timeouts for everything especially at edge?

**Review by howardjohn — APPROVED** [review]

File: pilot/pkg/networking/core/listener.go [hunk 3]
```diff
@@ -1111,18 +1114,20 @@ func buildGatewayListener(opts gatewayListenerOpts, transport istionetworking.Tr
 		filterChains = append(filterChains, &listener.FilterChain{
 			FilterChainMatch: match,
 			TransportSocket:  transportSocket,
+			// Setting this timeout enables the gateway to enhance its resistance against memory exhaustion attacks,
+			// such as slow TLS Handshake attacks.
+			TransportSocketConnectTimeout: durationpb.New(defaultGatewayTransportSocketConnectTimeout),
```
Comment (hzxuzhonghu) [inline pilot/pkg/networking/core/listener.go:1119]: Looks this is also useful for sidecars @howardjohn

Comment (johnlanni) [reply pilot/pkg/networking/core/listener.go:1119]: OK, I will add them uniformly

**Comment by johnlanni** [comment]
@keithmattix Do you have any more suggestions for revisions? Could you please review it again

**Comment by hzxuzhonghu** [comment]
This should not backport @zirain Need to run in master branch for some time to check if any defect exist

**Comment by jaellio** [comment]
> @keithmattix Do you have any more suggestions for revisions? Could you please review it again

I believe @keithmattix is looking for some sort of tests. Are you looking for recommendations on how to write tests for this change?

**Review by keithmattix — APPROVED** [review]
I'll approve but opened #53094 to make sure we get tests in
