### PR TITLE
Import cluster local ExternalName services

### LINKED ISSUE #9950: Incorrect handling of ExternalName k8s services
When a request is made to a VirtualService backed by a Kubernetes service of type `ExternalName` (in my case, pointing to a cluster local name), the request doesn't get through and the reply is `503 Service Unavailable`. 

```
$ kubectl -n test get svc
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP                                           PORT(S)   AGE
nginx            ExternalName   <none>          nginx-internal.test.svc.cluster.local                 <none>    16m
nginx-internal   ClusterIP      10.71.251.104   <none>                                                80/TCP    2h
www              ExternalName   <none>          istio-ingressgateway.istio-system.svc.cluster.local   <none>    1h
```

VirtualService for host `www.test.svc.cluster.local` is backed by `nginx.test.svc.cluster.local` (http.route.destination.host field of the VirtualService object).

Hitting `http://www.test.svc.cluster.local/` from within the cluster gives `503 Service Unavailable`.

### Expected behavior
If the VirtualService is backed by `nginx-internal.test.svc.cluster.local`, the request gets through. It should work the same for `nginx.test.svc.cluster.local`. 

### Steps to reproduce the bug
Create test namespace and services as shown above. `nginx-internal` is a normal service backed by pods in the same namespace (via a label selector):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  namespace: test
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
```

Create Gateway and VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
spec:
  gateways:
  - test-gateway.test.svc.cluster.local
  - mesh
  hosts:
  - www.test.svc.cluster.local
  http:
  - route:
    - destination:
        host: nginx.test.svc.cluster.local
      weight: 100
```

Create a pod with bash and curl in istio-system. Exec into the pod and hit `http://www.test.svc.cluster.local/`. You'll get `503 Service Unavailable`.

### Workaround
1. Delete the backing ExternalName k8s service (`nginx`)
2. Create an Istio ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: nginx-se
  namespace: test
spec:
  hosts:
  - nginx.test.svc.cluster.local
  endpoints:
  - address: nginx-internal.test.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
```

With the ServiceEntry in place of the ExternalName service, requests will get through. 

### Version
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.15", GitCommit:"3567055982b92fc8ae6935ec8f304ab867a4fe00", GitTreeState:"clean", BuildDate:"2018-11-03T00:01:41Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.2", GitRevision:"bd24a62648c07e24ca655c39727aeb0e4761919a", User:"root", Host:"6408abaf1dac", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}
```

## Environment
GKE, Container-Optimized OS

## Cluster state
[istio-dump.tar.gz](https://github.com/istio/istio/files/2578887/istio-dump.tar.gz)

### PR DESCRIPTION
**Pull request by imikushin**
Fix #9950

### CODE REVIEW

File: pilot/pkg/serviceregistry/kube/conversion.go [hunk 1]
```diff
@@ -74,8 +74,12 @@ func convertService(svc v1.Service, domainSuffix string) *model.Service {
 
 	if svc.Spec.Type == v1.ServiceTypeExternalName && svc.Spec.ExternalName != "" {
 		external = svc.Spec.ExternalName
-		resolution = model.Passthrough
-		meshExternal = true
+		if strings.HasSuffix(external, "."+domainSuffix) {
+			resolution = model.DNSLB
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/conversion.go]: add a comment here as to why you are doing this (that you can back an exterbal service with in cluster service)

**Comment by imikushin** [comment]
Apparently this doesn't fix the problem. What am I missing?

**Comment by imikushin** [comment]
Looks like I've missed ServiceInstances!

**Comment by imikushin** [comment]
This is ready for another look. The fix works!

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 2]
```diff
@@ -116,6 +116,8 @@ type Controller struct {
 	sync.RWMutex
 	// servicesMap stores hostname ==> service, it is used to reduce convertService calls.
 	servicesMap map[model.Hostname]*model.Service
+	// instanceMap stores hostname ==> instance, is used to store ExternalName k8s services
+	instanceMap map[model.Hostname][]*model.ServiceInstance
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/controller.go]: please rename accordingly.. externalNameSvcInstanceMap

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 3]
```diff
@@ -741,6 +751,39 @@ func (c *Controller) AppendInstanceHandler(f func(*model.ServiceInstance, model.
...
+		svc, ok := obj.(*v1.Service)
+		if !ok {
+			return nil
+		}
+
+		if svc.Namespace == meta_v1.NamespaceSystem {
+			return nil
+		}
+
+		svcConv := convertService(*svc, c.domainSuffix)
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/controller.go]: cant you skip all this by checking apriori if this is an external name service?

File: pilot/pkg/serviceregistry/kube/conversion.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/conversion.go]: Have a doubt: is this a reasonable way to use  ExternalName service? How many users would use it like this? Is it worth the complexity?

 ExternalName service is meant to expose external service(not to mask
internal service) to cluster.

File: pilot/pkg/serviceregistry/kube/conversion.go [hunk 4]
```diff
@@ -118,6 +122,29 @@ func convertService(svc v1.Service, domainSuffix string) *model.Service {
...
+		return nil
+	}
+	var out []*model.ServiceInstance
+	for _, portEntry := range svc.Ports {
+		out = append(out, serviceInstance(k8sSvc, portEntry, svc))
+	}
+	return out
+}
+
+func serviceInstance(k8sSvc v1.Service, portEntry *model.Port, svc *model.Service) *model.ServiceInstance {
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/conversion.go]: I would inline this function in case some others misuse it.

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 5]
```diff
@@ -435,6 +438,13 @@ func (c *Controller) InstancesByPort(hostname model.Hostname, reqSvcPort int,
 		return nil, nil
 	}
 
+	c.RLock()
+	instances := c.instanceMap[hostname]
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller.go]: Is this only for externalService?

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: Also should move in front.

File: pilot/pkg/serviceregistry/kube/conversion.go (hunk 1 above)
Comment (rshriram) [reply pilot/pkg/serviceregistry/kube/conversion.go]: Thats a good point.. Until this PR, I did not even know that its possible to use external name services in this way.

File: pilot/pkg/serviceregistry/kube/conversion.go [hunk 6]
```diff
@@ -74,8 +74,12 @@ func convertService(svc v1.Service, domainSuffix string) *model.Service {
...
 	if svc.Spec.Type == v1.ServiceTypeExternalName && svc.Spec.ExternalName != "" {
 		external = svc.Spec.ExternalName
-		resolution = model.Passthrough
-		meshExternal = true
+		if strings.HasSuffix(external, "."+domainSuffix) {
+			resolution = model.DNSLB
+		} else {
+			resolution = model.Passthrough
+			meshExternal = true
+		}
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/conversion.go]: So thinking more about this, we should keep the meshExternal = true.. We should not be doing the (if the externalname is an internal service...) as it breaks the semantics for an external name service. I would remove the if block and permanently mark all externalName services as model.DNSLB as they are simply cname records anyway.

File: pilot/pkg/serviceregistry/kube/controller.go (hunk 2 above)
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: Done

File: pilot/pkg/serviceregistry/kube/controller.go (hunk 3 above)
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: Done

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 7]
```diff
@@ -741,6 +751,39 @@ func (c *Controller) AppendInstanceHandler(f func(*model.ServiceInstance, model.
 		}
 		return nil
 	})
+
+	c.services.handler.Append(func(obj interface{}, event model.Event) error {
```
[the remark this answers is not in the document]
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: ~~Weird what you're trying to achieve with this comment.~~

If I understand correctly, the purpose of `AppendInstanceHandler` is to add a callback (for the relevant service instances - in istio model) to be called when an event affecting these instances occurs in the backing model (in this case, k8s).

`c.services` here are k8s services, not Istio `model.Service`s. And we're only interested in `type: ExternalName` services that we're using to obtain specific  `model.ServiceInstance`s and call the handler with them. 

Do you have a better idea how to do this?

File: pilot/pkg/serviceregistry/kube/conversion.go (hunk 1 above)
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/conversion.go]: Look, `ExternalName` is obviously a victim of bad naming here. But it's already in the k8s API as is. And it works, without istio.

I want my k8s services to be usable, both without and **with** istio. 

My use case: I have a facade service and two internal services (one of them in a different namespace), and I need to **switch** the facade between them.

File: pilot/pkg/serviceregistry/kube/conversion.go (hunk 4 above)
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/conversion.go]: Done

File: pilot/pkg/serviceregistry/kube/controller.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: Not any, but after another thought this LGTM.

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 8]
```diff
@@ -741,6 +751,39 @@ func (c *Controller) AppendInstanceHandler(f func(*model.ServiceInstance, model.
...
+		instances := externalNameServiceInstances(*svc, svcConv)
+		switch event {
+		case model.EventDelete:
+			c.Lock()
+			delete(c.externalNameSvcInstanceMap, svcConv.Hostname)
+			c.Unlock()
+		default:
+			c.Lock()
+			if instances != nil {
+				c.externalNameSvcInstanceMap[svcConv.Hostname] = instances
```
Comment (hzxuzhonghu) [inline pilot/pkg/serviceregistry/kube/controller.go]: But I have another concern: How can externalName service instances update when the service object stays unchanged? It is an issue deserves consideration.

Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: If `AppendServiceHandler()` is called in the same context as `AppendInstanceHandler()` (which it is), then both services and instances should receive updates at about the same time.

Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: There's no need! Pods don't have anything to do with ExternalName services. Updates to services do trigger these event handlers for both services and instances of this type.

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: My question is there is no way to update `externalNameSvcInstanceMap[svcConv.Hostname]` when pod(add/update/delete).

Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: But `externalNameSvcInstanceMap` is used to get serviceInstances for ExternalName service.

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 9]
```diff
@@ -435,6 +438,13 @@ func (c *Controller) InstancesByPort(hostname model.Hostname, reqSvcPort int,
 		return nil, nil
 	}
 
+	c.RLock()
+	instances := c.externalNameSvcInstanceMap[hostname]
```
[the remark this answers is not in the document]
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: That was exactly my question when I started working on this PR: how do you update services? I've found exactly one place: in a handler added in `AppendServiceHandler`.

Updates to `c.externalNameSvcInstanceMap` mirror updates to `c.servicesMap`. So, for ExternalName service instances, the answer is: in a handler added in `AppendInstanceHandler`.

[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: You mean here https://github.com/istio/istio/pull/9975/files#diff-c306f3343ec67abc1d89a34528710958R788, sorry this does not resolve my question.  ExternalName service is a mirror of a internal service, when internal service endpoints add/update/delete, there is no way to sense as you do not provide a relation record now.

**Comment by hzxuzhonghu** [comment]
And overall, I do not feel strongly about this use case.  I would leave it to @rshriram to decide.

File: pilot/pkg/serviceregistry/kube/controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: So my patch shouldn't work then, but it does. I've provided tests to prove it. I've manually tested that it indeed fixes the issue it's supposed to fix (#9950). 

If this PR does not work for you somehow, can you provide criteria that it breaks? Best in the form of tests / examples.

**Comment by imikushin** [comment]
@hzxuzhonghu Can you clear your review / request for changes? Otherwise please specify what exactly is broken based on examples / test cases.

**Comment by imikushin** [comment]
@rshriram Is there anything else I need to change to have this approved?

File: pilot/pkg/serviceregistry/kube/controller.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: Can you print `c.externalNameSvcInstanceMap[hostname]`, when internal service endpoints update?

I can not imagine how `c.externalNameSvcInstanceMap[hostname]` can change when only service instance scale up or down.

[the remark this answers is not in the document]
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: ExternalName k8s service, when imported to the Pilot object model, should IMO work pretty much like ServiceEntry object (which, obviously, doesn't do anything "when internal service endpoints add/update/delete"). 

I'll gladly update this PR if there's any externally observable property or behavior that this implementation is breaking. Right now I don't see anything like that.

[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/serviceregistry/kube/controller.go]: If you scale down and up all your instances are modified and your get the stale ones from here. Still you can get your traffic through?

[the remark this answers is not in the document]
Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: It absolutely works!

File: pilot/pkg/serviceregistry/kube/controller.go [hunk 10]
```diff
@@ -435,6 +438,13 @@ func (c *Controller) InstancesByPort(hostname model.Hostname, reqSvcPort int,
 		return nil, nil
 	}
 
+	c.RLock()
```
Comment (rshriram) [inline pilot/pkg/serviceregistry/kube/controller.go]: kill all the logic in the AppendInstanceHandler below.. It will cause unnecessary config reloads and mess with incremental EDs we have.

Instead do the following here:
``` if service.type == meshExternal {
   getKubeService(service.Hostname) // orwhatever way you get the kube service
  return []*ServiceInstance{
    {
        Endpoint: model.NetworkEndpoint{
				Address:     k8sSvc.Spec.ExternalName,
				Port:        portEntry.Port,
				ServicePort: portEntry,
			},
			Service: svc,
			Labels:  k8sSvc.Labels,
    }
  }
}
```

The reason to do so is one of performance. CDS code will call out to this function for all external services. And you could directly return service instances for such services. the Service itself is already monitored byother handlers. So anytime the service changes, we will be able to get the updated set of instances.

Comment (imikushin) [reply pilot/pkg/serviceregistry/kube/controller.go]: That was my original approach. Didn't work.

Without adding a handler in `AppendInstanceHandler`, requests to ExternalName services don't get through (if made via the mesh). 

Looks like `AppendInstanceHandler`'s role is to actively propagate changes to the routing mesh whenever such changes occur in the backend model (k8s).
