### PR TITLE
fix wait option for operator init command.

### LINKED ISSUE #20322: Operator init command doesn't honor 'wait' and 'readiness-timeout' options
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Build the istioctl with latest code from master, try the `istioctl operator init -w`, you will find that it will exit before all the operator controller pods are starting running or timeout:
```
# make istioctl
...
# out/linux_amd64/istioctl operator init -w
Using operator Deployment image: docker.io/istio/operator:f729b5aa6d66edd60ae5b48900f620f997e7c5b4

- Applying manifest for component Operator...
✔ Finished applying manifest for component Operator.
Component Operator installed successfully.

*** Success. ***

# kubectl -n istio-operator get pod
NAME                              READY   STATUS         RESTARTS   AGE
istio-operator-64d54bc4c4-qh8l2   0/1     ErrImagePull   0          13s
``` 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/20322

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: operator/cmd/mesh/operator-init.go [hunk 1]
```diff
@@ -165,6 +165,13 @@ func applyManifest(manifestStr, componentName string, opts *kubectlcmd.Options,
 	opts.Prune = pointer.BoolPtr(false)
 	out, objs := manifest.ApplyManifest(name.ComponentName(componentName), manifestStr, version.OperatorBinaryVersion.String(), *opts)
 
+	if opts.Wait {
+		err := manifest.WaitForResources(objs, opts)
```
Comment (richardwxn) [inline operator/cmd/mesh/operator-init.go]: Is there a default waittimeout number exists?

Comment (morvencao) [reply operator/cmd/mesh/operator-init.go]: Yes, default values is 300 seconds.

**Review by howardjohn — APPROVED** [review]
