### PR TITLE
fix shellcheck error

### LINKED ISSUE #8333: Shellcheck is failing
CI task Shellcheck is failing after https://github.com/istio/istio/pull/8173 in
```
#!/bin/sh -eo pipefail
/root/project/tools/run_shellcheck.sh

In /root/project/tests/e2e/local/minikube/install_prereqs_debian.sh line 3:
source "../common_linux.sh"
^-- SC1091: Not following: ../common_linux.sh was not specified as input (see shellcheck -x).


In /root/project/tests/e2e/local/minikube/install_prereqs_debian.sh line 34:
  if ! (curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.27.0/minikube-linux-amd64 && \ 
                                                                                                           ^-- SC1101: Delete trailing spaces after \ to break line (or use quotes for literal space).


In /root/project/tests/e2e/local/minikube/install_prereqs_macos.sh line 3:
source ../common_macos.sh
^-- SC1091: Not following: ../common_macos.sh was not specified as input (see shellcheck -x).


In /root/project/tests/e2e/local/vagrant/install_prereqs_debian.sh line 3:
source ../common_linux.sh
^-- SC1091: Not following: ../common_linux.sh was not specified as input (see shellcheck -x).


In /root/project/tests/e2e/local/vagrant/install_prereqs_macos.sh line 3:
source ../common_macos.sh
^-- SC1091: Not following: ../common_macos.sh was not specified as input (see shellcheck -x).
```
I'll have a fix

/cc @m1093782566 @hklai

### PR DESCRIPTION
**Pull request by lichuqiang**
fix #8333

### CODE REVIEW

**Comment by lichuqiang** [comment]
fix #8333

**Comment by m1093782566** [comment]
Nice catch! @lichuqiang 

LGTM

File: tests/e2e/local/minikube/install_prereqs_macos.sh [hunk 1]
```diff
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# shellcheck source=tests/e2e/local/common_macos.sh
```
Comment (ymesika) [inline tests/e2e/local/minikube/install_prereqs_macos.sh]: Can you please add double quotation marks like in the other scripts or remove from other to keep it consistent?

File: tests/e2e/local/vagrant/install_prereqs_debian.sh [hunk 2]
```diff
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# shellcheck source=tests/e2e/local/common_linux.sh
 source ../common_linux.sh
```
Comment (ymesika) [inline tests/e2e/local/vagrant/install_prereqs_debian.sh]: Same

File: tests/e2e/local/vagrant/install_prereqs_macos.sh [hunk 3]
```diff
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# shellcheck source=tests/e2e/local/common_macos.sh
 source ../common_macos.sh
```
Comment (ymesika) [inline tests/e2e/local/vagrant/install_prereqs_macos.sh]: Same

File: tests/e2e/local/minikube/install_prereqs_macos.sh (hunk 1 above)
Comment (lichuqiang) [reply tests/e2e/local/minikube/install_prereqs_macos.sh]: you mean make it this way?

```
SCRIPTPATH="$(cd "$(dirname "$0")" ; pwd -P)"
ROOTDIR="$(dirname "${SCRIPTPATH}")"
# shellcheck source=tests/e2e/local/common_macos.sh
source "${ROOTDIR}/common_macos.sh"
```

Comment (ymesika) [reply tests/e2e/local/minikube/install_prereqs_macos.sh]: Take a look at `tests/e2e/local/minikube/install_prereqs_debian.sh`.
Over there it's `source "../common_linux.sh"` and here `source ../common_macos.sh`. Just make it consistent.

Comment (m1093782566) [reply tests/e2e/local/minikube/install_prereqs_macos.sh]: I agree with @lichuqiang - we should not make too much changes in this PR for the sake of merging this fix ASAP.

Regarding to separate or merge these files, we can discuss it later - I separated them for better readability. Make sense?

File: tests/e2e/local/minikube/install_prereqs_debian.sh [hunk 4]
```diff
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-source "../common_linux.sh"
```
Comment (ymesika) [inline tests/e2e/local/minikube/install_prereqs_debian.sh]: OK, you didn't understand what I mean so I will write the code I expect for each file:

source "../common_linux.sh"

File: tests/e2e/local/minikube/install_prereqs_debian.sh [hunk 5]
```diff
@@ -1,6 +1,9 @@
...
+SCRIPTPATH="$(cd "$(dirname "$0")" ; pwd -P)"
```
Comment (ymesika) [inline tests/e2e/local/minikube/install_prereqs_debian.sh]: source "../common_linux.sh"

File: tests/e2e/local/minikube/install_prereqs_macos.sh [hunk 6]
```diff
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-source ../common_macos.sh
```
Comment (ymesika) [inline tests/e2e/local/minikube/install_prereqs_macos.sh]: source "../common_macos.sh"

File: tests/e2e/local/vagrant/install_prereqs_debian.sh [hunk 7]
```diff
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-source ../common_linux.sh
```
Comment (ymesika) [inline tests/e2e/local/vagrant/install_prereqs_debian.sh]: source "../common_linux.sh"

File: tests/e2e/local/vagrant/install_prereqs_macos.sh [hunk 8]
```diff
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-source ../common_macos.sh
```
Comment (ymesika) [inline tests/e2e/local/vagrant/install_prereqs_macos.sh]: source "../common_macos.sh"

**Comment by lichuqiang** [comment]
@hklai Can you pls take a look at this?

File: tests/e2e/local/minikube/install_prereqs_macos.sh (hunk 1 above)
Comment (lichuqiang) [reply tests/e2e/local/minikube/install_prereqs_macos.sh]: > feel it may be better to just combine the first two lines since SCRIPTPATH is only referenced in the second line anyway.

Hmm, I thought about it too. What I worried about it is that would make the statement too complex to understand. So, I'd prefer to leave them  independent to make it clearer.
And seems scripts that in need of parent path(e.g bin/ci2gubernator.sh) also behaviors the same way.
WDYT?

**Comment by hklai** [comment]
Merging as the test failures are unrelated
