### PR TITLE
Merge profile before diff'ing

### LINKED ISSUE #30112: incorrect "istioctl profile diff default openshift" output
Fails with both 1.8.0 and Master

`istioctl profile diff default openshift` and `~/go/src/istio.io/istio/out/darwin_amd64/istioctl profile diff default openshift -d manifests` should produce similar output to `diff <(~/go/src/istio.io/istio/out/darwin_amd64/istioctl profile dump openshift -d manifests) <(~/go/src/istio.io/istio/out/darwin_amd64/istioctl profile dump default -d manifests/)`, but they don't.

Thanks @frankbu for reporting.  cc @ostromart 

The problem is that `profile diff` compares the unmerged profiles.  The `openstack` profile is a tiny set of additions, not a full profile, so it fails.

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/30112

@ostromart @istio/wg-environments-maintainers This subcommand has no unit tests that I could find.

I could easily implement a brittle test that looks for specific output, but I didn't originate this code and lack good ideas for how to make a unit test that doesn't break every time we twiddle with the profiles.  Can someone from Environments comment on the feasibility of testing this?  Or write a unit test?  I was nervous about my implementation of the `--manifests` option, which is needed in Master but not in official releases.  Ideally a unit test would make sure fixes work in both Master (with `--manifests`) and releases (without).

It might be possible to make an integration or doc test if unit testing is too hard.

cc @frankbu

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
What about adding testing similar to https://github.com/istio/istio/blob/master/operator/cmd/mesh/manifest-generate_test.go and write the `profile diff` output to the goldens, so that each time we update profiles, the `profile diff` goldens are also updated.

**Comment by esnible** [comment]
@morvencao I started working on tests for `istioctl profile diff`.  I wrote a simple test setup.  The setup I have doesn't block the `os.Exit(1)` that `profile diff` uses to set `$?` to `1` if the profiles are different.

I realize tests are possible, and I've checked in arg checking tests and tests for when the profile is itself.  I don't want to make this PR a large PR about changes needed to get testing working.  The @istio/wg-environments-maintainers should create an Issue for `profile diff` being undertested and set a priority for the work.

@ostromart Can you review the function and the simple testing I started?

**Comment by ostromart** [comment]
1. I suggest restructuring the code a bit so that the os.Exit is in a calling function. That will make the main function more testable.
2. It's going to be a little painful but I highly recommend avoiding using a golden file in this case, because you will have to refresh it every time a profile changes which is often. The alternative is to use operator/cmd/mesh data-snapshot which you can see being used in the tests there to avoid the constant refreshing. However, imo it would be preferable to even do a simple string search on a stable part of the diff string to avoid going the golden file route.

**Comment by esnible** [comment]
@ostromart @morvencao Please re-review.  I added real tests, that use string matches to avoid golden files.

File: operator/cmd/mesh/profile-diff.go [hunk 1]
```diff
@@ -75,7 +79,10 @@ func profileDiff(cmd *cobra.Command, rootArgs *rootArgs, pfArgs *profileDiffArgs
 		cmd.Println("Profiles are identical")
 	} else {
 		cmd.Printf("The difference between profiles:\n%s", diff)
-		os.Exit(1)
+		// The command was a success, but we return an error so that the process will
+		// exit with 1.  We don't want to tell the user there was an error because there wasn't.
+		cmd.SilenceErrors = true
+		return fmt.Errorf("dummy")
```
Comment (ostromart) [inline operator/cmd/mesh/profile-diff.go:85]: what i had in mind more to make this more testable is to create a wrapper function with the existing signature and an internal function which could take an extra parameter (bool for exit?). then you could call it like this:
<inside profileDiff>
 err, doExit := doProfileDiff()..
 if doExit { os.Exit(1) }
Hope that makes sense - we can chat directly if it doesn't.
I think that would be a cleaner solution than returning dummy errors.

Comment (esnible) [reply operator/cmd/mesh/profile-diff.go]: OK, I have refactored so that it works as suggested.

The changes I made somehow seem to have also fixed https://github.com/istio/istio/issues/30375 .  That issue also has a PR, and the two PRs may conflict.

**Review by ostromart — APPROVED** [review]
lgtm, thanks Ed!
