### PR TITLE
virtualHost.Domains for dual stack

### LINKED ISSUE #45557: dual stack proxy config missing a svc IP in virtualHost domains list
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**This is a fail closed situation: traffic which should be allowed is being denied***

In dual stack k8s svcs get assigned an IPv4 and an IPv6 address. Only 1 of those addresses is being populated into the domains list in the routes. This has some effects on things like AuthorizationPolicy where they won't be applied correctly to the missing IP which is flowing through a passthrough. Not exhaustively tested but in my first quick check it did fail shut at least denying traffic that should have been allowed.

The IP Family address which get's populated is the one which appears first in the list.

**abbreviated proxy-config route & k8s svc:**
```shell
❯ istioctl pc routes sleep-9454cc476-jrgnj.default --name 8000 -ojson
[
    {
        "name": "8000",
        "virtualHosts": [
            {
                "name": "httpbin.httpbin.svc.cluster.local:8000",
                "domains": [
                    "httpbin.httpbin.svc.cluster.local",
                    "httpbin.httpbin",
                    "httpbin.httpbin.svc",
                    "[fd00:10:96::bc57]"
                ],
REMAINDER OMITTED FOR BREVITY...

❯ k get svc -n httpbin httpbin -o yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
    service: httpbin
  name: httpbin
  namespace: httpbin
spec:
  clusterIP: fd00:10:96::bc57
  clusterIPs:
  - fd00:10:96::bc57
  - 10.96.19.25
  ipFamilies:
  - IPv6
  - IPv4
REMAINDER OMITTED FOR BREVITY...
```

### Version

```Text
❯ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (7 proxies)

❯ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.3

FWIW this behavior has also been observed on multiple Istio 1.17 versions
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by ilrudie**
**Please provide a description of this PR:**

fixes #45557

Adds the additional IP from services spec.clusterIPs into the virtualHost.Domains

### CODE REVIEW

**Comment by ilrudie** [comment]
@nmittler, this touches some code you wrote in GetAddressForProxy in pilot/pkg/model/service.go so I would appreciate your feedback on the PR.

TYIA

File: pilot/pkg/networking/core/v1alpha3/httproute.go [hunk 1]
```diff
@@ -567,6 +569,14 @@ func generateVirtualHostDomains(service *model.Service, listenerPort int, port i
 	if len(svcAddr) > 0 && svcAddr != constants.UnspecifiedIP {
 		domains = appendDomainPort(domains, svcAddr, port)
 	}
+
+	// handle dual stack's extra address when generating the virtualHost domains
+	// assumes that conversion is stripping out the DefaultAddress from ClusterVIPs
+	extraAddr := service.GetExtraAddressesForProxy(node)
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/httproute.go:575]: I recommended initially, and continue to believe, the concept of "Extra" addresses is flawed. It just gives the codebase a super easy way to forget to handle the fact we can have multiple addresses.

Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/httproute.go:575]: Also it seems like Get**Extra**AddressesForProxy is not really "Extra" addresses, but rather **all** addresses. So not sure how  are not getting duplicate addresses here? Maybe we are

**Comment by howardjohn** [comment]
cc @zhlsunshine

**Comment by howardjohn** [comment]
Should this/can this be covered by the ISTIO_DUAL_STACK flag somehow? The dual stack code is pretty unstable, I don't want it impact normal users

**Comment by ilrudie** [comment]
> Should this/can this be covered by the ISTIO_DUAL_STACK flag somehow? The dual stack code is pretty unstable, I don't want it impact normal users

I can investigate that. seems plausible to wrap the bit which adds extraAddr to domains though if we want

File: pilot/pkg/networking/core/v1alpha3/httproute.go (hunk 1 above)
Comment (ilrudie) [reply pilot/pkg/networking/core/v1alpha3/httproute.go:575]: service conversion from a k8s svc to model strips it out right now. Otherwise it would duplicate, you are correct. Not sure long term that is actually the way to go and maybe its just better to align with K8s (and potentially remove the "extra" nomenclature while we're at it).

**Comment by zhlsunshine** [comment]
Hi @howardjohn @ilrudie, I submitted a PR [here](https://github.com/istio/istio/pull/45578) to cover function `GetExtraAddressesForProxy` via Dual Stack flag.

**Comment by ilrudie** [comment]
Would it be reasonable to divide this into two issues?
1. address the specific ds domains issue; limiting the diff
2. address the "extra" IPs concept and move towards assumptions that services are likely to have multiple IPs which need to be handled gracefully

File: pilot/pkg/networking/core/v1alpha3/httproute.go (hunk 1 above)
Comment (ilrudie) [reply pilot/pkg/networking/core/v1alpha3/httproute.go:575]: > Also it seems like Get**Extra**AddressesForProxy is not really "Extra" addresses, but rather **all** addresses. So not sure how are not getting duplicate addresses here? Maybe we are

I was (partially) mistaken in my initial response to this. There are other code paths that create services which this method needs to be able to handle and those do include duplicate IPs so the content of the field isn't consistent across the project. Sometimes we do get extra IPs and sometimes we don't depending on how the service was created.

**Comment by zhlsunshine** [comment]
> Would it be reasonable to divide this into two issues?
> 
> 1. address the specific ds domains issue; limiting the diff
> 2. address the "extra" IPs concept and move towards assumptions that services are likely to have multiple IPs which need to be handled gracefully

Hi @ilrudie, besides the service support multiple IPs, I think we need to think it more. Assumption that Istio is deployed in a Dual Stack cluster, then pods and endpoints have 2 IP addresses (IPv4 and IPv6), however, the k8s service is not necessarily, it depends on the deployment yaml of k8s service.

File: pilot/pkg/serviceregistry/kube/conversion.go [hunk 2]
```diff
@@ -73,10 +73,9 @@ func ConvertService(svc corev1.Service, domainSuffix string, clusterID cluster.I
 		addr = svc.Spec.ClusterIP
 		if len(svc.Spec.ClusterIPs) > 0 {
 			for _, ip := range svc.Spec.ClusterIPs {
-				// exclude the svc.Spec.ClusterIP
-				if ip != addr {
-					extrAddrs = append(extrAddrs, ip)
-				}
+				// pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go also performs a conversion from k8s svc -> model
+				// it doesn't exclude the "default" IP from this slice, this conversion should align which also makes it more like k8s
+				extrAddrs = append(extrAddrs, ip)
```
Comment (howardjohn) [inline pilot/pkg/serviceregistry/kube/conversion.go:78]: So we will have a list like `[]{ip1, ip1, ip2}`? Is that what we want? seems a bit odd..?

File: pilot/pkg/networking/core/v1alpha3/httproute_test.go [hunk 3]
```diff
@@ -252,7 +285,13 @@ func TestGenerateVirtualHostDomains(t *testing.T) {
 	for _, c := range cases {
 		c := c
 		t.Run(c.name, func(t *testing.T) {
+			if c.enableDualStack {
+				features.EnableDualStack = true
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/httproute_test.go:289]: use test.SetForTest

File: pilot/pkg/model/service.go [hunk 4]
```diff
@@ -1118,6 +1118,12 @@ func (s *Service) GetAddresses(node *Proxy) []string {
 // GetAddressForProxy returns a Service's address specific to the cluster where the node resides
 func (s *Service) GetAddressForProxy(node *Proxy) string {
 	if node.Metadata != nil {
+		// pilot/pkg/serviceregistry/kube/conversion.go was updated to remove
+		// DefaultAddress from ClusterVIPs. We need to handle that here in
+		// order to build virtualHost Domains correctly for dual stack
+		if s.DefaultAddress != "" && s.DefaultAddress != constants.UnspecifiedIP {
+			return s.DefaultAddress
+		}
```
Comment (howardjohn) [inline pilot/pkg/model/service.go:1126]: Not sure I am following this?

**Review by howardjohn — COMMENTED** [review]
The route vhost part lgtm. I am a bit confused by the rest, may just be misunderstanding it

File: pilot/pkg/serviceregistry/kube/conversion.go (hunk 2 above)
Comment (ilrudie) [reply pilot/pkg/serviceregistry/kube/conversion.go:78]: 100% it's not. I had wanted []{ip1, ip2} and had not seen that around line 110 when we build the struct we prepend addr to extraAddrs. TY

File: pilot/pkg/model/service.go (hunk 4 above)
Comment (ilrudie) [reply pilot/pkg/model/service.go:1126]: Will likely rework this anyway in light of your other comments.

**Review by howardjohn — APPROVED** [review]
thanks!
