### PR TITLE
citadel: use chain cert if available otherwise use root cert

### LINKED ISSUE #13125: TLS handshakes from istio-nodeagent to citadel fail when using custom certificates
**Describe the bug**

TLS handshakes from istio-nodeagent to citadel fail when using custom certificates.

**Expected behavior**

Installing Istio with `security.selfSigned=false` and SDS enabled works.

**Steps to reproduce the bug**

Using the config from the [SDS example](https://raw.githubusercontent.com/istio/istio/release-1.1/install/kubernetes/helm/istio/values-istio-sds-auth.yaml):

```
global:
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
```

Setting `security.selfSigned=false` when installing via Helm, after first installing the certificates from `./samples/certs` into the namespace.

Trying to hit the ingress gateway IP results in the following:

```
$ curl -i http://$INGRESS_IP/productpage
HTTP/1.1 503 Service Unavailable
content-length: 57
content-type: text/plain
date: Sun, 07 Apr 2019 19:33:06 GMT
server: istio-envoy

upstream connect error or disconnect/reset before headers
```

Observe connections from the nodeagent to citadel fail with the following:

```console
$ kubectl -n istio-system logs -f istio-nodeagent-kqmsd
2019-04-07T19:02:34.848530Z     info    unalbe to fetch CA TLS root cert: failed to get CA TLS root cert: configmaps "istio-security" not found, retry in 2s
2019-04-07T19:02:34.860404Z     info    parsed scheme: ""
2019-04-07T19:02:34.860715Z     info    scheme "" not registered, fallback to default scheme
2019-04-07T19:02:34.862816Z     info    ccResolverWrapper: sending new addresses to cc: [{istio-citadel:8060 0  <nil>}]
2019-04-07T19:02:34.862902Z     info    ClientConn switching balancer to "pick_first"
2019-04-07T19:02:34.862985Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, CONNECTING
2019-04-07T19:02:35.007015Z     info    SDS gRPC server start, listen "/var/run/sds/uds_path"

2019-04-07T19:02:35.007114Z     info    Start SDS grpc server
2019-04-07T19:02:54.863362Z     info    grpc: addrConn.createTransport failed to connect to {istio-citadel:8060 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.6.203.12
7:8060: i/o timeout". Reconnecting...
2019-04-07T19:02:54.863534Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, TRANSIENT_FAILURE
2019-04-07T19:02:54.863822Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, CONNECTING
2019-04-07T19:02:55.095489Z     info    grpc: addrConn.createTransport failed to connect to {istio-citadel:8060 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: c
ertificate signed by unknown authority". Reconnecting...
2019-04-07T19:02:55.095660Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, TRANSIENT_FAILURE
2019-04-07T19:02:56.557837Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, CONNECTING
2019-04-07T19:02:57.346965Z     info    grpc: addrConn.createTransport failed to connect to {istio-citadel:8060 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: c
ertificate signed by unknown authority". Reconnecting...
2019-04-07T19:02:57.347119Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, TRANSIENT_FAILURE
2019-04-07T19:02:59.413722Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420038560, CONNECTING
2019-04-07T19:02:59.665745Z     info    grpc: addrConn.createTransport failed to connect to {istio-citadel:8060 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: c
ertificate signed by unknown authority". Reconnecting...
```

This seems to be due to the nodeagent fetching the root certificate from the istio-security `ConfigMap`, but the validation of the cert chain is missing the intermediates (namely Istio CA).

The certificate that citadel presents:

```
root@go-f7fc9d4d6-rrfbt:/go/src/github.com/square/certigo# certigo connect istio-citadel.istio-system:8060
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_RSA key exchange, AES_128_GCM_SHA256 cipher

Server has requested a client certificate:
Acceptable issuers:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
Supported Signature Schemes:
        RSA-PKCS1 with SHA256
        ECDSA with P256 and SHA256
        RSA-PKCS1 with SHA384
        ECDSA with P384 and SHA384
        RSA-PKCS1 with SHA512
        ECDSA with P521 and SHA512
        RSA-PKCS1 with SHA1
        ECDSA with SHA1

** CERTIFICATE 1 **
Valid: 2019-04-07 18:45 UTC to 2019-07-06 18:45 UTC
Subject:

Issuer:
        C=US, ST=California, L=Sunnyvale, O=Istio, CN=Istio CA
DNS Names:
        istio-ca, istio-citadel, istio-citadel.istio-system.svc.cluster.local

Failed to verify certificate chain:
        x509: certificate is valid for istio-ca, istio-citadel, istio-citadel.istio-system.svc.cluster.local, not istio-citadel.istio-system
```

Note issuer: `CN=Istio CA`.

The certificate in the `ConfigMap` (after base64 decoding):

```
$ kubectl -n istio-system get configmap istio-security -o=jsonpath='{.data.caTLSRootCert}' | base64 -D | certigo dump
** CERTIFICATE 1 **
Valid: 2018-01-24 19:15 UTC to 2117-12-31 19:15 UTC
Subject:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
Issuer:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
Warnings:
        Certificate is a CA cert, but key usage 'cert sign' missing
```

Note subject: `CN=Root CA`.

I was able to fix this by concatenating the intermediate and the root cert, placing this back into the `istio-security` `ConfigMap` (i.e. the `ConfigMap` now contains both the CA and root):

```
$ certigo dump <( cat ./istio/samples/certs/ca-cert.pem ./istio/samples/certs/root-cert.pem )
** CERTIFICATE 1 **
Valid: 2018-01-24 19:15 UTC to 2117-12-31 19:15 UTC
Subject:
        C=US, ST=California, L=Sunnyvale, O=Istio, CN=Istio CA
Issuer:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
DNS Names:
        ca.istio.io

** CERTIFICATE 2 **
Valid: 2018-01-24 19:15 UTC to 2117-12-31 19:15 UTC
Subject:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
Issuer:
        C=US, ST=California, L=Sunnyvale, O=Istio, OU=Test, CN=Root CA
Warnings:
        Certificate is a CA cert, but key usage 'cert sign' missing
```

Restarted the nodeagent and checked to confirm the nodeagent is connecting to citadel and handling SDS requests, as expected:

```
$ kubectl -n istio-system logs -f istio-nodeagent-29rhc
2019-04-07T19:05:34.114520Z     info    parsed scheme: ""
2019-04-07T19:05:34.114575Z     info    scheme "" not registered, fallback to default scheme
2019-04-07T19:05:34.115549Z     info    ccResolverWrapper: sending new addresses to cc: [{istio-citadel:8060 0  <nil>}]
2019-04-07T19:05:34.115605Z     info    ClientConn switching balancer to "pick_first"
2019-04-07T19:05:34.115689Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc4204440c0, CONNECTING
2019-04-07T19:05:34.205334Z     info    SDS gRPC server start, listen "/var/run/sds/uds_path"

2019-04-07T19:05:34.205470Z     info    Start SDS grpc server
2019-04-07T19:05:34.331690Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc4204440c0, READY
2019-04-07T19:05:42.440610Z     info    SDS: push key/cert pair from node agent to proxy: "sidecar~10.2.3.105~ratings-v1-7c9949d479-vpv2b.default~default.svc.cluster.local-4"

2019-04-07T19:05:42.597823Z     info    SDS: push root cert from node agent to proxy connection: "sidecar~10.2.3.105~ratings-v1-7c9949d479-vpv2b.default~default.svc.cluster.local-3"

2019-04-07T19:05:42.597824Z     info    SDS: push root cert from node agent to proxy connection: "sidecar~10.2.3.105~ratings-v1-7c9949d479-vpv2b.default~default.svc.cluster.local-1"

2019-04-07T19:05:42.826372Z     info    SDS: push key/cert pair from node agent to proxy: "sidecar~10.2.3.105~ratings-v1-7c9949d479-vpv2b.default~default.svc.cluster.local-2"
```

**Environment**

GKE: `1.12.6-gke.10`, VMs: `Container-Optimized OS`

**Version**

```
$ cat ./istio/istio.VERSION
# DO NOT EDIT THIS FILE MANUALLY instead use
# install/updateVersion.sh (see install/README.md)
export GALLEY_HUB="docker.io/istio"
export GALLEY_TAG="1.1.2"
export CITADEL_HUB="docker.io/istio"
export CITADEL_TAG="1.1.2"
export MIXER_HUB="docker.io/istio"
export MIXER_TAG="1.1.2"
export PILOT_HUB="docker.io/istio"
export PILOT_TAG="1.1.2"
export PROXY_HUB="docker.io/istio"
export PROXY_TAG="1.1.2"
export ISTIO_NAMESPACE="istio-system"
export PILOT_DEBIAN_URL="https://storage.googleapis.com/istio-release/releases/1.1.2/deb"
export FORTIO_HUB="docker.io/fortio"
export FORTIO_TAG="latest_release"
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by lsjostro**
Fixes #13125

### CODE REVIEW

File: security/pkg/pki/ca/ca.go [hunk 1]
```diff
@@ -323,7 +323,14 @@ func BuildSecret(saName, scrtName, namespace string, certChain, privateKey, root
 }
 
 func updateCertInConfigmap(namespace string, client corev1.CoreV1Interface, keyCertBundle util.KeyCertBundle) error {
-	_, _, _, cert := keyCertBundle.GetAllPem()
+	var cert []byte
+	cert = keyCertBundle.GetCertChainPem()
+	if cert == nil {
+		cert = keyCertBundle.GetRootCertPem()
+		if cert == nil {
+			return fmt.Errorf("No valid certs available")
```
Comment (golangcibot) [inline security/pkg/pki/ca/ca.go]: error strings should not be capitalized or end with punctuation or a newline (from `golint`)

File: security/pkg/pki/ca/ca.go [hunk 2]
```diff
@@ -323,7 +323,14 @@ func BuildSecret(saName, scrtName, namespace string, certChain, privateKey, root
 }
 
 func updateCertInConfigmap(namespace string, client corev1.CoreV1Interface, keyCertBundle util.KeyCertBundle) error {
-	_, _, _, cert := keyCertBundle.GetAllPem()
+	var cert []byte
```
Comment (golangcibot) [inline security/pkg/pki/ca/ca.go]: S1021: should merge variable declaration with assignment on next line (from `gosimple`)

**Comment by lsjostro** [comment]
> #10567 used rootcert is because signedcert may rotate(see [comment](https://github.com/istio/istio/pull/10567#discussion_r242768768)); If this is true, we need to handle chaincert rotate/expire in both citadel and nodeagent, otherwise connection will fail.

@quanjielin I don't fully follow. This is a regression right? nodeagent will need the full chain to be able to communicate with citadel (when having an intermediate ca). I don't think citadel need to care about chain cert rotation? as when using custom certs you as the user are in full charge of handling rotation of the CA yourself. 

When the CA expires you need to populate citadel with new certs and restart both citadel and the nodeagents? citadel will then issue new certs to services and push new certs to istio-proxy pods?

**Comment by quanjielin** [comment]
If using custom certs, as you mentioned user is in charge so this PR is probably OK; better to let nodeagent monitor the cert(from configmap) used to communicate with CA to avoid restart (which is enhancement anyway without this PR)

However the codepath is same when using citadel, cert(issued by citadel) rotate every 24 hours, which means nodeagent <-> CA may break every day (while using root cert is relatively stable). 

To alleviate the problem for now, how about keep using root cert if selfsigned==true ? and cert chain when selfsigned==false ?

**Comment by lsjostro** [comment]
@quanjielin What do you think about that? Now we are being explicit. When using self signed, populate RootCert to the configmap and when using plugged certs (selfSigned=false) try to use chain cert otherwise use rootcert. 

Cheers!
