### PR TITLE
`Instance.SubsetOf` should check if key exists

### LINKED ISSUE #35722: DestinationRule: subsets labels with empty values
### Bug Description

I tested a Istio traffic management use-case I want to implement, where I am using multiple subsets. The selection of the subset should be done by a label without value:

k get deploy nginx-v1-1 -o yaml | grep -A3 labels                                                                        
      labels:
        app: svc-b
        dev/early-adopter: ""
        dev/stable: ""
        
k get deploy nginx-v1-2 -o yaml | grep -A3 labels                                                                         
      labels:
        app: svc-b
        dev/main-dev: ""
        version: v1.2

So I am using the labels `dev/main-dev`, `dev/early-adopter` and `dev/stable` to identify the subset. Using a simple "dev" label would not working in my case, because I need to apply multiple values to one deployment. When I am now creating a DestinationRule for that, traffic is not routed to the correct deployment. Traffic is still spitted 50:50 between both deployments. When I add a value to my labels, it is working correctly. 

A dr would look like this: 
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr-svc-b
  namespace: svc-b
spec:
  host: "svc-b.svc-b.svc.cluster.local"
  subsets:
  - name: main-dev
    labels:
      dev/main-dev: ""
```
```
istioctl x describe pod nginx-v1-2-596847b5bc-9nvhl 
Pod: nginx-v1-2-596847b5bc-9nvhl
   Pod Ports: 80 (nginx), 15090 (istio-proxy)
--------------------
Service: svc-b
   Port: http 80/HTTP targets pod port 80
DestinationRule: dr-svc-b for "svc-b.svc-b.svc.cluster.local"
   Matching subsets: main-dev
   No Traffic Policy
VirtualService: vs-svc-b
   1 HTTP route(s)
```

### Version

```prose
istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (12 proxies)
kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.2-eks-0389ca3
```

### Additional Information

Target cluster context: arn:aws:eks:us-east-1:494495723522:cluster/eks-u9q42vv8

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-10-25 13:23:26.781095 +0200 CEST

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.11.3", GitRevision:"6bda7c161d3925c48fbea3f297ffa52461893f3b", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.11.3"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.11.3}

Fetching proxy logs for the following containers:

istio-system//nginx/nginx
istio-system/grafana/grafana-68cc7d6d78-bdpmp/grafana
istio-system/istio-egressgateway/istio-egressgateway-566697b759-jsdz6/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-7776dd578-8r7vv/istio-proxy
istio-system/istiod/istiod-b9c8c9487-g4wwv/discovery
istio-system/jaeger/jaeger-5d44bc5c5d-h9dr5/jaeger
istio-system/kiali/kiali-fd9f88575-9xdlx/kiali
istio-system/prometheus/prometheus-77b49cb997-lcnnd/prometheus-server
istio-system/prometheus/prometheus-77b49cb997-lcnnd/prometheus-server-configmap-reload
svc-a/nginx-v1-2/nginx-v1-2-74cb4b7666-58kld/istio-proxy
svc-a/nginx-v1-2/nginx-v1-2-74cb4b7666-58kld/nginx
svc-a/nginx-v1-2/nginx-v1-2-74cb4b7666-lcqcg/istio-proxy
svc-a/nginx-v1-2/nginx-v1-2-74cb4b7666-lcqcg/nginx
svc-a/nginx-v1-3/nginx-v1-3-8bf97cb5b-nsvjd/istio-proxy
svc-a/nginx-v1-3/nginx-v1-3-8bf97cb5b-nsvjd/nginx
svc-a/nginx-v1-3/nginx-v1-3-8bf97cb5b-rbzc4/istio-proxy
svc-a/nginx-v1-3/nginx-v1-3-8bf97cb5b-rbzc4/nginx
svc-a/nginx-v2-0/nginx-v2-0-5f9c6764b4-9jqst/istio-proxy
svc-a/nginx-v2-0/nginx-v2-0-5f9c6764b4-9jqst/nginx
svc-a/nginx-v2-0/nginx-v2-0-5f9c6764b4-b4m99/istio-proxy
svc-a/nginx-v2-0/nginx-v2-0-5f9c6764b4-b4m99/nginx
svc-b/nginx-v1-1/nginx-v1-1-6d95f74456-h5qdh/istio-proxy
svc-b/nginx-v1-1/nginx-v1-1-6d95f74456-h5qdh/nginx
svc-b/nginx-v1-1/nginx-v1-1-6d95f74456-tcx4d/istio-proxy
svc-b/nginx-v1-1/nginx-v1-1-6d95f74456-tcx4d/nginx
svc-b/nginx-v1-2/nginx-v1-2-596847b5bc-9nvhl/istio-proxy
svc-b/nginx-v1-2/nginx-v1-2-596847b5bc-9nvhl/nginx
svc-b/nginx-v1-2/nginx-v1-2-596847b5bc-w7gb2/istio-proxy
svc-b/nginx-v1-2/nginx-v1-2-596847b5bc-w7gb2/nginx

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service grafana.istio-system) Port name service (port: 3000, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Creating an archive at bug-report.tar.gz.
Cleaning up temporary files in /var/folders/3c/sq2jbt0j6_dc5yk3s_mshxbmdl6w_5/T/bug-report.
Done.

### PR DESCRIPTION
**Pull request by dddddai**
Signed-off-by: dddddai <dddwq@foxmail.com>

**Please provide a description of this PR:**
If there is a label whose value is `""`, `Instance.SubsetOf` will return true though the key does NOT exist in the other

It may lead to inconsistency when the label value is an empty string, so this PR fixes it

Fix #35722

### CODE REVIEW

**Comment by dddddai** [comment]
@googlebot I signed it!

File: pkg/config/labels/instance_test.go [hunk 1]
```diff
@@ -24,6 +24,7 @@ func TestInstance(t *testing.T) {
 	a := labels.Instance{"app": "a"}
 	a1 := labels.Instance{"app": "a", "prod": "env"}
 	a2 := labels.Instance{"app": "b", "prod": "env"}
+	b := labels.Instance{"foo": ""}
```
Comment (howardjohn) [inline pkg/config/labels/instance_test.go:27]: I don't think this is sufficient test coverage as we don't have a test case with it negative

It would be ideal to rewrite these tests to use https://dave.cheney.net/2019/05/07/prefer-table-driven-tests format so we can have a big list of `{left, right, bool expected}` and compare all cases.

Comment (dddddai) [reply pkg/config/labels/instance_test.go]: @howardjohn Thanks for your review!
I have rewrited the tests as you addressed, PTAL :)

**Review by hzxuzhonghu — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
lgtm, thanks for the test!
