### PR TITLE
Fix local IP discovery in CNI

### LINKED ISSUE #36871: CNI plugin fails to configure pods in IPv6 clusters
### Bug Description

When deploying workloads into the service mesh while running the Istio CNI plugin in an IPv6 kind cluster, the workload pods seem to always end up in a cyclic crash loop. Using istio-init (ie w/o CNI plugin) appears to works fine.
Am I missing something?

Is it expected that CNI reports ENABLE_INBOUND_IPV6=false (while istio-init in a similar environment reports true)?

**Edit:** I observed the same behavior in a native IPv6 cluster with docker/k8s hosts assigned only IPv6 addresses.

```
$ cat ipv6.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
$ kind create cluster --image=kindest/node:v1.21.2 --name=ipv6 --config=ipv6.yaml

$ helm upgrade istio-cni \
    manifests/charts/istio-cni \
    --install \
    --namespace kube-system \
    --set global.hub=gcr.io/istio-release \
    --set global.tag=1.12.1 \
    --set cni.logLevel=debug

$ helm upgrade istio-base \
    manifests/charts/base \
    --install \
    --namespace istio-system \
    --create-namespace

$ helm upgrade istiod \
    manifests/charts/istio-control/istio-discovery \
    --install \
    --namespace istio-system \
    --set global.hub=gcr.io/istio-release \
    --set global.tag=1.12.1 \
    --set istio_cni.enabled=true \
    --wait

$ kubectl create namespace test
$ kubectl label namespace test istio-injection=enabled
$ kubectl apply -n test -f samples/sleep/sleep.yaml

$ kubectl get pods -n test -w
NAME                     READY   STATUS     RESTARTS   AGE
sleep-557747455f-gt5f4   0/2     Init:0/1   0          14s
sleep-557747455f-gt5f4   0/2     Init:0/1   0          40s
sleep-557747455f-gt5f4   0/2     Init:Error   0          47s
sleep-557747455f-gt5f4   0/2     Init:0/1     1          51s
sleep-557747455f-gt5f4   0/2     Terminating   1          51s
sleep-557747455f-gt5f4   0/2     Terminating   1          52s
sleep-557747455f-rdtfk   0/2     Pending       0          0s
sleep-557747455f-rdtfk   0/2     Pending       0          0s
sleep-557747455f-rdtfk   0/2     Init:0/1      0          1s
sleep-557747455f-rdtfk   0/2     Init:0/1      0          13s
sleep-557747455f-rdtfk   0/2     Init:Error    0          19s
sleep-557747455f-rdtfk   0/2     Init:0/1      1          22s
sleep-557747455f-rdtfk   0/2     Terminating   1          22s
sleep-557747455f-rdtfk   0/2     Terminating   1          23s
sleep-557747455f-kg7tw   0/2     Pending       0          1s
sleep-557747455f-kg7tw   0/2     Pending       0          1s
sleep-557747455f-kg7tw   0/2     Init:0/1      0          2s
sleep-557747455f-kg7tw   0/2     Init:0/1      0          16s
sleep-557747455f-kg7tw   0/2     Init:Error    0          22s
...

$ kubectl logs -n kube-system istio-cni-node-phw5h
...
2022-01-18T15:25:37.564975Z     info    repair  Pod detected as broken, deleting: test/sleep-557747455f-rdtfk
2022-01-18T15:25:38.237229Z     info    repair  Pod detected as broken, deleting: test/sleep-557747455f-rdtfk
2022-01-18T15:25:41.916866Z     info    cni     istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:sleep-557747455f-kg7tw K8S_POD_NAMESPACE:test K8S_POD_INFRA_CONTAINER_ID:12f1622e01ad06335c4cd7ae05bfb0939b40a7991729e6c96f2b24a79101d930}
2022-01-18T15:25:41.916888Z     info    cni     ============= Start iptables configuration for sleep-557747455f-kg7tw =============
2022-01-18T15:25:41.916892Z     info    cni     Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
2022-01-18T15:25:41.916894Z     info    cni     Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020,15021,15090
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=15020
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=/var/run/netns/cni-c6459cec-3d6e-cdb4-a14a-433b029d1043
CNI_MODE=true
EXCLUDE_INTERFACES=
2022-01-18T15:25:41.916897Z     info    cni     Writing following contents to rules file: /tmp/iptables-rules-1642519541608327696.txt3276312655
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2022-01-18T15:25:41.916899Z     info    cni     Running command: nsenter --net=/var/run/netns/cni-c6459cec-3d6e-cdb4-a14a-433b029d1043 -- iptables-restore --noflush /tmp/iptables-rules-1642519541608327696.txt3276312655
2022-01-18T15:25:41.916902Z     info    cni     Writing following contents to rules file: /tmp/ip6tables-rules-1642519541845170871.txt3226216103
2022-01-18T15:25:41.916904Z     info    cni     Running command: nsenter --net=/var/run/netns/cni-c6459cec-3d6e-cdb4-a14a-433b029d1043 -- ip6tables-restore --noflush /tmp/ip6tables-rules-1642519541845170871.txt3226216103
2022-01-18T15:25:41.916905Z     info    cni     Running command: nsenter --net=/var/run/netns/cni-c6459cec-3d6e-cdb4-a14a-433b029d1043 -- iptables-save
2022-01-18T15:25:41.916908Z     info    cni     Command output: 
# Generated by iptables-save v1.8.7 on Tue Jan 18 15:25:41 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Tue Jan 18 15:25:41 2022
2022-01-18T15:25:41.916913Z     info    cni     Running command: nsenter --net=/var/run/netns/cni-c6459cec-3d6e-cdb4-a14a-433b029d1043 -- /opt/cni/bin/istio-cni configure-routes
2022-01-18T15:25:41.916916Z     error   cni     Command error output: 
{"level":"info","time":"2022-01-18T15:25:41.913060Z","msg":"Added ::6 address"}
2022-01-18T15:25:41.916917Z     info    cni     ============= End iptables configuration for sleep-557747455f-kg7tw =============
```

### Version

```prose
Istio 1.12.1
Kubernetes 1.21.2
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mKeRix**
**Please provide a description of this PR:**

Currently there is a disparity in IP detection when using the CNI vs. regular usage of the proxy. Since the latter runs on the host, IP detection will also be based on the host network (vs the pod network interfaces for the latter). This is for example an issue when you have dual-stack hosts, but a single-stack IPv6 cluster. In this case the CNI should setup for IPv6, but instead thinks it is running on an IPv4 cluster. A prominent example of this is EKS in IPv6 mode.

This change will make the CNI run its iptables code in the pod network namespace, just like it would when running without the CNI.

Fixes #36871.

### CODE REVIEW

File: cni/pkg/plugin/iptables.go [hunk 1]
```diff
@@ -55,11 +61,25 @@ func (ipt *iptables) Program(podName, netns string, rdrct *Redirect) error {
...
-	if err := iptablesCmd.Execute(); err != nil {
+
+	netNs, err := getNs(netns)
+	if err != nil {
+		err = fmt.Errorf("failed to open netns %q: %s", netns, err)
 		return err
 	}
+	defer netNs.Close()
+
+	if err = netNs.Do(func(_ ns.NetNS) error {
```
Comment (howardjohn) [inline cni/pkg/plugin/iptables.go:72]: Isn't this unsafe? https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix? It seems like _maybe_ its safer now, but still need to do some more effort to lock things: https://github.com/vishvananda/netns#note

Comment (mKeRix) [reply cni/pkg/plugin/iptables.go:72]: Interesting article! The locking mentioned in there is thankfully already handled by the package in the `Do` method. They also provide a few remarks surrounding safety in their [README](https://github.com/containernetworking/plugins/tree/master/pkg/ns). The Istio CNI process should exit fairly quickly, minimizing the risk even further.

This namespace switching can also be found in other popular CNI projects, e.g. [cilium](https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/chaining/generic-veth/generic-veth.go#L57-L64), so it's not completely out there.

Unfortunately, I can't think of a better way to make the code behave the same within a pod and on the host atm. We could provide the IP from the CNI `prevResult` as a parameter to the istio-iptables code, but that would a) be a bigger change and b) also possibly lead to different behavior between the two "modes".

Comment (howardjohn) [reply cni/pkg/plugin/iptables.go:72]: Ah interesting. I guess my info is from 2017 :stuck_out_tongue: .

So one concern is we already have logic to run stuff in the network namespace. so now we enter the netns, then from within the netns we enter it again? This probably is technical fine but likely means we have over complicated things -- if its safe to do for this use case we can simplify the rest of the code as well?

How the rest works is we shell out - https://github.com/istio/istio/blob/abaae0893cc14c44edf290e48b9b748d2fcd45d1/tools/istio-iptables/pkg/capture/run.go#L287 - for everything that is done in the pod netns.

So my thinking is either we should do the same thing in both places. I don't think I am educated enough right now to say which one we should do - ciliums reference makes this approach seem plausible.
cc @bianpengyuan @lambdai

**Review by Arhell — COMMENTED** [review]
/ok-to-test

File: cni/pkg/plugin/iptables.go (hunk 1 above)
Comment (bianpengyuan) [reply cni/pkg/plugin/iptables.go:72]: I think we'd have to nsenter when shell out?  Not sure how do we keep the namespace for a subprocess with this mechanism?

Comment (mKeRix) [reply cni/pkg/plugin/iptables.go:72]: I looked at the shell out code and believe it should work fine using this mechanism as well, without `nsenter`. `Cmd.Run` [documents](https://github.com/golang/go/blob/d588f487703e773ba4a2f0a04f2d4141610bff6b/src/os/exec/exec.go#L333-L336) that in a locked thread the network namespace will be inherited for the executed command.

That being said, if you spawn a new goroutine from within `Do` it will not inherit the new namespace and behave unexpectedly. I thought about it some more and would propose the following changes to this pull request:

- namespace switching as implemented here is moved from the plugin to istio-iptables, which would allow us to just wrap the relevant `getLocalIP` call [here](https://github.com/istio/istio/blob/abaae0893cc14c44edf290e48b9b748d2fcd45d1/tools/istio-iptables/pkg/cmd/root.go#L152) if the `CNIMode` flag is set
- if you wish, the other calls can also be wrapped within go by adapting the namespaced [execute](https://github.com/istio/istio/blob/abaae0893cc14c44edf290e48b9b748d2fcd45d1/tools/istio-iptables/pkg/dependencies/implementation.go#L74-L78) instead of using nsenter - maybe in a follow up PR to keep the changeset small on this one?

What do you think @howardjohn & @bianpengyuan?

**Comment by mKeRix** [comment]
Just wanted to check in and see if there is something I can do to help move this PR along? Based on the most recent PR comments I'm not really sure whether you'd like to see any adaptions or this is just waiting for more reviews.

**Review by bianpengyuan — APPROVED** [review]
