### PR TITLE
fix: bypass stricter gateway hostname with wildcard tlsroute hostname

### LINKED ISSUE #59229: TLSRoute allows TLS handshakes to bypass a stricter SNI hostname match set on Gateway
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

To address a bug found in https://github.com/kubernetes-sigs/gateway-api/pull/4583#discussion_r2841346367

A TLS handshake can pass through a Gateway even if its SNI hostname does not match the listener's specified hostname. For example, a handshake using the SNI `non.matching.com` successfully reaches the backend, despite the listener matching `*.example.com` only, and if backend has a Certificated with `non.matching.com`, the TLS connection will be established.

To reproduce this issue, attach a broader TLSRoute (e.g. `*.com`) to a Gateway listener configured with a more restrictive hostname (e.g. `*.example.com`), as shown below:
```
kind: Gateway
spec:
  listeners:
  - protocol: TLS
    port: 443
    hostname: "*.example.com"
    tls:
      mode: Passthrough

kind: TLSRoute
spec:
  hostnames:
  - abc.example.com
  rules:
  - backendRefs:
    - name: tls-backend
      port: 443

kind: TLSRoute
spec:
  hostnames:
  - "*.com"
  rules:
  - backendRefs:
    - name: tls-backend-2
      port: 443
```

### Version

```Text
$ istioctl version
client version: unknown
control plane version: 1.30-alpha.dab802576418864986da01d3ad801279cb7a57c2
data plane version: 1.30-alpha.dab802576418864986da01d3ad801279cb7a57c2 (2 proxies)

$ kubectl version
Client Version: v1.33.8
Kustomize Version: v5.6.0
Server Version: v1.33.5-gke.2326000
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jgreeer**
**Please provide a description of this PR:**

Added intersection between gateway listener hostname and tlsroute sni hostname when creating virtural services. This respects [the spec](https://gateway-api.sigs.k8s.io/concepts/hostnames/#sni-matching), where we match the request sni with the **intersected** hostname, not just the route hostnames.

Fixes #59229

### CODE REVIEW

File: pilot/pkg/config/kube/gateway/conversion.go [hunk 1]
```diff
@@ -414,6 +414,37 @@ func compatibleRoutesForHost(routes []*istio.TLSRoute, parentHost string) []*ist
...
+// hostname (e.g. *.com) attached to a listener with a narrower hostname (e.g. *.example.com)
+// only matches the intersection (*.example.com), not the full route hostname.
+func constrainTLSRoutesToListenerHost(routes []*istio.TLSRoute, listenerHost string) []*istio.TLSRoute {
+	if listenerHost == "" {
+		return routes
+	}
+	listenerNames := host.NewNames([]string{listenerHost})
+	res := make([]*istio.TLSRoute, 0, len(routes))
+	for _, r := range routes {
+		r = r.DeepCopy()
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/conversion.go:428]: I don't see anywhere that we're changing `r` so why is this deepcopy necessary?

File: pilot/pkg/config/kube/gateway/conversion.go [hunk 2]
```diff
@@ -414,6 +414,37 @@ func compatibleRoutesForHost(routes []*istio.TLSRoute, parentHost string) []*ist
...
+		for _, m := range r.Match {
+			routeNames := host.NewNames(m.SniHosts)
+			m.SniHosts = slices.Map(routeNames.Intersection(listenerNames), func(n host.Name) string { return string(n) })
```
Comment (keithmattix) [inline pilot/pkg/config/kube/gateway/conversion.go:431]: Just confirming that `Intersection` is a host intersection and not a set intersection?

**Review by keithmattix — COMMENTED** [review]
Are we already running the conformance tests from https://github.com/kubernetes-sigs/gateway-api/pull/4583? If so, how do we currently pass? If not, we shouldrun them

File: pilot/pkg/config/kube/gateway/conversion.go (hunk 2 above)
Comment (jgreeer) [reply pilot/pkg/config/kube/gateway/conversion.go:431]: yes, `Intersection` is a method of host.Names that produces a subset of intersecting hostnames between itself and the method argument (also a host.Names)

File: pilot/pkg/config/kube/gateway/conversion.go (hunk 1 above)
Comment (jgreeer) [reply pilot/pkg/config/kube/gateway/conversion.go:428]: i think the problem with not deepcopying is that  `routes` is `gwResult.routes` in `TLSRouteCollection()` which is shared between parents. so if we compute the intersection for `match.sniHosts` for one `istio.TLSRoute`, the next parent will have an incorrect value to do its intersection.  happy to test if this is actually needed though

Comment (jgreeer) [reply pilot/pkg/config/kube/gateway/conversion.go:428]: also we do change `r` right? `m.SniHosts` is part of `r.Match`

Comment (keithmattix) [reply pilot/pkg/config/kube/gateway/conversion.go:428]: Ah sorry missed that assignment. Yeah deepcopy makes sense

**Comment by jgreeer** [comment]
> Are we already running the conformance tests from [kubernetes-sigs/gateway-api#4583](https://github.com/kubernetes-sigs/gateway-api/pull/4583)? If so, how do we currently pass? If not, we shouldrun them

I believe we're skipping it right now? `TLSRouteHostnameIntersection` is in the `skippedTests` map in `gateway_conformance_test.go`. should i just uncomment it in this PR?

**Comment by keithmattix** [comment]
@jgreeer ah yep please unskip it so we can confirm this works

**Comment by jgreeer** [comment]
passing all tests including `TLSRouteHostnameIntersection`

File: tests/integration/pilot/gateway_conformance_test.go [hunk 3]
```diff
@@ -96,7 +96,7 @@ var skippedTests = map[string]string{
 	"MeshHTTPRoute307Redirect": "TODO",
 	"MeshHTTPRoute308Redirect": "TODO",
 
-	"TLSRouteHostnameIntersection":                 "TODO",
+	// "TLSRouteHostnameIntersection":                 "TODO",  // unskipped — fix implemented
```
Comment (keithmattix) [inline tests/integration/pilot/gateway_conformance_test.go:99]: Do we need to do this for ambient conformance too?

Comment (jgreeer) [reply tests/integration/pilot/gateway_conformance_test.go:99]: yes, let me uncomment that too
