### PR TITLE
Infloop13

### LINKED ISSUE #14242: Envoy infinite loops requests to itself, causing 4x memory usage
https://snapshot.raintank.io/dashboard/snapshot/jOGp3TQdrrCQcjzdaFd6rKXbylbplzw3?panelId=72&fullscreen&orgId=2

Leaks about 1GB  (23 -> 24 gb) over a day period, but seems to level off after that.

This is running from master.

I switched half of the proxy images over to 1.1.7 and didn't see any real changes, which means this is likely not a regression in master.

@silentdai I think you worked on something like this before, any other useful info we can get? I can give you access to the cluster too

@mandarjog

### PR DESCRIPTION
**Pull request by silentdai**
Another attempt to fix #14242, #14443

This PR is part of the picture deprecating containerPort by isolate inbound listener and outbound listeners. More specifically, sidecar proxy need to avoid inf loop in the below conditions

- inbound listeners and outbound listeners are split and not accessible from each other
- iptables redirect all incoming traffic to inbound listener

This is done by bind magical local address when redirecting unmatched inbound listeners. Notes it's common when we allow user not specify containerPort. See istio design doc `Better Default Networking`

Meanwhile this PR should **NOT** break any functionality when in/out listener is not split.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by silentdai** [comment]
Close for now as it is not ready to be reviewed

File: pilot/pkg/networking/core/v1alpha3/listener_builder.go [hunk 1]
```diff
@@ -284,13 +279,57 @@ func newBlackholeFilter(enableAny bool) listener.Filter {
...
+	// ipv4 and ipv6
+	filterChains := make([]listener.FilterChain, 0, 2)
+	for _, clusterName := range []string{util.InboundPassthroughClusterIpv4, util.InboundPassthroughClusterIpv6} {
+
+		tcpProxy := &tcp_proxy.TcpProxy{
+			StatPrefix:       clusterName,
+			ClusterSpecifier: &tcp_proxy.TcpProxy_Cluster{Cluster: clusterName},
+		}
+
+		matchingIp := ""
```
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/listener_builder.go]: var `matchingIp` should be `matchingIP` (from `golint`)

File: pilot/pkg/networking/core/v1alpha3/cluster.go [hunk 2]
```diff
@@ -418,6 +418,33 @@ func buildInboundLocalityLbEndpoints(bind string, port int) []endpoint.LocalityL
 	}
 }
 
+func generateInboundPassthroughClusters(env *model.Environment) []*apiv2.Cluster {
```
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/cluster.go]: `generateInboundPassthroughClusters` is unused (from `deadcode`)

File: pilot/pkg/networking/core/v1alpha3/listener_builder.go (hunk 1 above)
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/listener_builder.go]: var `matchingIp` should be `matchingIP` (from `golint`)

File: pilot/pkg/networking/core/v1alpha3/cluster.go [hunk 3]
```diff
@@ -418,6 +420,33 @@ func buildInboundLocalityLbEndpoints(bind string, port int) []endpoint.LocalityL
...
+	inboundPassthroughClusterIpv6.UpstreamBindConfig = &core.BindConfig{
+		SourceAddress: core.SocketAddress{
+			Address: util.InboundPassthroughBindIpv6,
+			PortSpecifier: &core.SocketAddress_PortValue{
+				PortValue: uint32(0),
+			},
+		},
+	}
+	clusters = append(clusters, inboundPassthroughClusterIpv4, inboundPassthroughClusterIpv6)
+	return clusters
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/cluster.go]: nit: you could just do `return []*apiv2.Cluster{inboundPassthroughClusterIpv4, inboundPassthroughClusterIpv6}`

File: pilot/pkg/networking/util/util.go [hunk 4]
```diff
@@ -51,6 +51,14 @@ const (
 	// PassthroughRouteName is the name of the route that forwards traffic to the
 	// PassthroughCluster
 	PassthroughRouteName = "allow_any"
+
+	// Inbound pass through cluster need to the bind the loopback ip address for the security and loop avoidance.
+	InboundPassthroughClusterIpv4 = "InboundPassthroughClusterIpv4"
+	InboundPassthroughClusterIpv6 = "InboundPassthroughClusterIpv6"
+	// 6 is the magical number for inbound: 15006, 127.0.0.6, ::6
```
Comment (howardjohn) [inline pilot/pkg/networking/util/util.go]: This is extremely subtle - I understand it only because I've thought about it for hours. I think this needs a lot more comments, both here and in the cluster/listener creation. Otherwise this will become the "crazy pilot code no one understands" :slightly_smiling_face:

**Comment by howardjohn** [comment]
> Meanwhile this PR should break any functionality when in/out listener is not split.

do you mean should or should not?

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 5]
```diff
@@ -239,23 +239,23 @@ func TestLDSWithDefaultSidecar(t *testing.T) {
 		return
 	}
 
-	// Expect 6 listeners : 2 orig_dst, 1 http inbound + 4 outbound (http, tcp1, istio-policy and istio-telemetry)
-	// plus 2 extra due to the mem registry
+	// Expect 7 listeners : 2 orig_dst, 1 http inbound + 4 outbound (http, tcp1, istio-policy and istio-telemetry)
 	if (len(adsResponse.HTTPListeners) + len(adsResponse.TCPListeners)) != 7 {
-		t.Fatalf("Expected 8 listeners, got %d\n", len(adsResponse.HTTPListeners)+len(adsResponse.TCPListeners))
+		t.Fatalf("Expected 7 listeners, got %d\n", len(adsResponse.HTTPListeners)+len(adsResponse.TCPListeners))
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/lds_test.go]: A general problem with pilot tests - I think we can do better than just checking the length of the response. Just checking the number seems like we are just trying to get code coverage without wanting to write a real test

File: pilot/pkg/proxy/envoy/v2/lds_test.go [hunk 6]
```diff
@@ -239,23 +239,23 @@ func TestLDSWithDefaultSidecar(t *testing.T) {
...
-	// Expect 10 CDS clusters: 1 inbound + 7 outbound (2 http services, 1 tcp service, 2 istio-system services,
-	// and 2 subsets of http1), 1 blackhole, 1 passthrough
-	// plus 2 extra due to the mem registry
-	if (len(adsResponse.Clusters) + len(adsResponse.EDSClusters)) != 10 {
+	// Expect 12 CDS clusters:
+	// 3 inbound(http, inbound passthroughipv4 and inbound passthroughipv6)
+	// 9 outbound (2 http services, 1 tcp service, 2 istio-system services,
+	//   and 2 subsets of http1, 1 blackhole, 1 passthrough)
+	if (len(adsResponse.Clusters) + len(adsResponse.EDSClusters)) != 12 {
 		t.Fatalf("Expected 12 Clusters in CDS output. Got %d", len(adsResponse.Clusters)+len(adsResponse.EDSClusters))
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/lds_test.go]: I like that the number here was wrong to begin with..

File: pilot/pkg/networking/core/v1alpha3/cluster.go [hunk 7]
```diff
@@ -418,6 +420,33 @@ func buildInboundLocalityLbEndpoints(bind string, port int) []endpoint.LocalityL
...
+	inboundPassthroughClusterIpv4.UpstreamBindConfig = &core.BindConfig{
+		SourceAddress: core.SocketAddress{
+			Address: util.InboundPassthroughBindIpv4,
+			PortSpecifier: &core.SocketAddress_PortValue{
+				PortValue: uint32(0),
+			},
+		},
+	}
+
+	inboundPassthroughClusterIpv6 := buildDefaultPassthroughCluster(env)
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/cluster.go]: will this get a mixer filter applied?

Comment (silentdai) [reply pilot/pkg/networking/core/v1alpha3/cluster.go]: I think so. Mixer filter is added in buildVirtualInboundFilter

File: pilot/pkg/networking/core/v1alpha3/cluster.go (hunk 3 above)
Comment (silentdai) [reply pilot/pkg/networking/core/v1alpha3/cluster.go]: Great catch! Besides it I erase the clusters var. See update

File: pilot/pkg/networking/util/util.go (hunk 4 above)
Comment (silentdai) [reply pilot/pkg/networking/util/util.go]: If even you feel we need more comment, I will add.

Which particular part are you referring to? 
magical 6? 2 cluster/bindip? Or something else?

File: pilot/pkg/proxy/envoy/v2/lds_test.go (hunk 5 above)
Comment (silentdai) [reply pilot/pkg/proxy/envoy/v2/lds_test.go]: Honestly I don't have the full pictures of the test. I feel it is the regression test: Better not to verify too many details at this point.

**Comment by silentdai** [comment]
```
--- FAIL: TestStreamSecretsPush (5.02s)
    sdsservice_test.go:382: failed to send push notificiation to proxy "sidecar~127.0.0.1~id2~local-1"
```

I don't think I crash this one

/retest

**Comment by silentdai** [comment]
@costinm Could you take look? The bottom line of this PR is not to break anything and I think it is reached

File: pilot/pkg/networking/util/util.go (hunk 4 above)
Comment (costinm) [reply pilot/pkg/networking/util/util.go]: The entire reason for the magic. And why IPv6 is even more magic.

**Comment by costinm** [comment]
Looks good otherwise - and I don't mind adding the extra control and docs in a separate PR so we can shard the testing. Approving - but please don't forget the requirements on alpha features.

/lgtm
/approve

**Comment by silentdai** [comment]
> As usual my primary concern is safety/reliability. How do we turn it off ? How do we deploy it gradually to reduce risks ? Getting a messed up iptables or something broken when a user upgrades from 1.2 to 1.3 is not acceptable IMO.

Safety
iptables, ip, clusters are safe as long as no one use the magical ipv4 and ipv6 address. There is risk that user used 127.0.0.6 or people use ::6, or istio somehow refers the new "InboundPassthroughClusterIpv4/6" cluster already. That's almost impossible.
If people don't use it these rules and cluster add very little burden to istio.

> The general rule is that any new (or alpha) feature should be off by default and require some user action
to enable. I think we still have the metadata to control the generation of the config - can we use it to control the new iptable config ? And please confirm that by default ( with the capture option off) we keep generating the same config as in 1.2, the new code should only be triggered when we enable the new mode.
( separate discussion - we need a global way to turn this on via values.yaml, once users have tested
it with individual workloads )

I will leave the killswitch to when pilot start to utilize the clusters or the iptables rule in following PRs. That PR would assume the iptables/clusters are provided.
