### PR TITLE
detect metadata-only secret rotation events

### LINKED ISSUE #59912: pilot-agent does not reflect certificate changes after second rotation for file-mounted secrets used in DestinationRule
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

When using file-mounted certificates for originating mTLS from a mesh pod to an external service (via DestinationRule with clientCertificate, privateKey, and caCertificates)
, pilot-agent stops detecting certificate updates after the second rotation. The first and second certificate updates are picked up correctly, but the third update is
silently ignored.

Reproduction steps:

-  Install Istio (1.29.2)
- Generate 3 sets of client/server certificates (Set 1, Set 2, Set 3), all signed by the same CA
- Create Kubernetes secrets and mount them to the respective pods (with Set 1): sleep-credential, sleep-credential-cacert, nginx-credential, nginx-credential-cacert
- Deploy a sleep pod inside the mesh and an nginx pod outside the mesh
   ```yaml
	apiVersion: v1
	kind: ServiceAccount
	metadata:
	  name: sleep
	---
	apiVersion: v1
	kind: Service
	metadata:
	  name: sleep
	  labels:
	    app: sleep
	spec:
	  ports:
	  - port: 80
	    name: http
	  selector:
	    app: sleep
	---
	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  labels:
	    app: sleep
	  name: sleep
	spec:
	  selector:
	    matchLabels:
	      app: sleep
	  template:
	    metadata:
	      annotations:
	        proxy.istio.io/config: |
	          proxyMetadata:
	            ISTIO_META_DNS_CAPTURE: "true"
	            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
	        sidecar.istio.io/userVolume: '{"client-secret":{"secret":{"secretName":"sleep-credential"}},"ca-secret":{"secret":{"secretName":"sleep-credential-cacert"}}}'
	        sidecar.istio.io/userVolumeMount: '{"client-secret":{"mountPath":"/etc/sleep/client_certs/client.example.com","readOnly":true},"ca-secret":{"mountPath":"/etc/sleep/ca_certs/example.com"}}'
	      labels:
	        app: sleep
	        sidecar.istio.io/inject: "true"
	    spec:
	      imagePullSecrets:
	      - name: armdocker
	      containers:
	      - command:
	        - /bin/sleep
	        - 3650d
	        image: busybox
	        imagePullPolicy: Always
	        name: sleep
	---

- Create the necessary ServiceEntry, VirtualService, and DestinationRule for mTLS origination. The DestinationRule references file-mounted certificates:
  ``` yaml
	apiVersion: networking.istio.io/v1beta1
	kind: ServiceEntry
	metadata:
	  name: nginx
	spec:
	  hosts:
	  - nginx.example.com
	  ports:
	  - name: http
	    number: 80
	    protocol: HTTP
	  - name: https
	    number: 443
	    protocol: HTTP
	  resolution: DNS
	  endpoints:
	  - address: nginx
	---
	apiVersion: networking.istio.io/v1alpha3
	kind: VirtualService
	metadata:
	  name: nginx
	spec:
	  hosts:
	  - nginx.example.com
	  http:
	  - match:
	    - port: 80
	    route:
	    - destination:
	        host: nginx.example.com
	        port:
	          number: 443
	---
	apiVersion: networking.istio.io/v1alpha3
	kind: DestinationRule
	metadata:
	  name: nginx
	spec:
	  host: nginx.example.com
	  trafficPolicy:
	    loadBalancer:
	      simple: ROUND_ROBIN
	    portLevelSettings:
	    - port:
	        number: 443
	      tls:
	        mode: MUTUAL
	        clientCertificate: /etc/sleep/client_certs/client.example.com/tls.crt
	        privateKey: /etc/sleep/client_certs/client.example.com/tls.key
            caCertificates: /etc/sleep/ca_certs/example.com/cacert

- Update the secrets with the second set of certificates:
  ```	
  #Sleep certs
  kubectl  --namespace istio-mt-ecalonu-0 create secret generic sleep-credential-cacert   --from-file=cacert=egress_renew_cert_set_2/ca/example.com.crt   --dry-run=true   --save-config   --output yaml > casecret2.yaml
  kubectl  --namespace istio-mt-ecalonu-0  create secret tls sleep-credential  --cert=egress_renew_cert_set_2/certs/sleep.crt   --key=egress_renew_cert_set_2/certs/sleep.key   --dry-run=true   --save-config   --output yaml > certsecret2.yaml
	
  kubectl apply -f casecret2.yaml -n istio-mt-ecalonu-0
  kubectl apply -f certsecret2.yaml -n istio-mt-ecalonu-0
	
  #Nginx certs
  kubectl   --namespace istio-mt-ecalonu-0 create secret generic nginx-credential-cacert   --from-file=cacert=egress_renew_cert_set_2/ca/example.com.crt   --dry-run=true   --save-config   --output yaml > casecret2nginx.yaml
  kubectl  --namespace istio-mt-ecalonu-0  create secret tls nginx-credential  --cert=egress_renew_cert_set_2/certs/nginx.crt   --key=egress_renew_cert_set_2/certs/nginx.key   --dry-run=true   --save-config   --output yaml > certsecret2nginx.yaml
	
  kubectl apply -f casecret2nginx.yaml -n istio-mt-ecalonu-0
  kubectl apply -f certsecret2nginx.yaml -n istio-mt-ecalonu-0
	
After that before reloading nginx instance to activate the nginx's certficates, send curl request from sleep pod to nginx and it should return 503. Because sleep pod would have the new certs but nginx would be still using old certs. After reloading nginx the requests will start to return 200.

- After updating the secrets with the third set similar to in the previous step, curl request will never return 503 because pilot-agent will not send the updates to Envoy proxy. Although the certificates within the sleep pod are updated, they are not actively used. Below I share the md5sum of istioctl output and and cert file mounted in the sleep pod. You can see the difference.

```	
	istioctl pc secrets -n istio-mt-ecalonu-0 sleep-6548446f94-jjclv -ojson | jq '.dynamicActiveSecrets[] | select(.name == "file-cert:/etc/sleep/client_certs/client.example.com/tls.crt~/etc/sleep/client_certs/client.example.com/tls.key") | .secret.tlsCertificate.certificateChain.inlineBytes' -r | base64 -d | md5sum
	be45d6fd0e8860dc55f2a0564356bc0b  -
	
	kubectl exec -it -n istio-mt-ecalonu-0 sleep-6548446f94-jjclv -c istio-proxy -- bash
	istio-proxy@sleep-6548446f94-jjclv:/$ cat /etc/sleep/client_certs/client.example.com/tls.crt | md5sum
    ea3f6f43d3bf19b73ba661c1dee08e9f  -

### Version

```Text
$ ./istioctl version -i istio-mt-ecalonu-0
client version: 1.29.2
control plane version: 1.29.2
data plane version: 1.29.2 (2 proxies)
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.32.2
```

### Additional Information

Here is the logs from sleep pod's istio-proxy container.
In the logs you can see that

- at  07:10:03 the first set of certs are read
- at 07:14:44 the second set of certs are read
- at 07:14:57 send a curl request and 503 returned from nginx. after that nginx has been reloaded to use the second set as well then curl requests returns 200
- at 07:17:21 we have third set updates however there is no "read certificates from file" log at all. After that although sleep pod needs to use the third set of certs to communicate with nginx, it is still using the second set, that's why 503 is not returned. However, it should be using the 3rd set of certs.

```
2026-04-17T07:10:02.668065Z     info    FLAG: --concurrency="0"
2026-04-17T07:10:02.668089Z     info    FLAG: --domain="istio-mt-ecalonu-0.svc.cluster.local"
2026-04-17T07:10:02.668093Z     info    FLAG: --help="false"
2026-04-17T07:10:02.668099Z     info    FLAG: --log_as_json="false"
2026-04-17T07:10:02.668102Z     info    FLAG: --log_caller=""
2026-04-17T07:10:02.668107Z     info    FLAG: --log_output_level="default:info"
2026-04-17T07:10:02.668109Z     info    FLAG: --log_stacktrace_level="default:none"
2026-04-17T07:10:02.668119Z     info    FLAG: --log_target="[stdout]"
2026-04-17T07:10:02.668125Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2026-04-17T07:10:02.668127Z     info    FLAG: --outlierLogPath=""
2026-04-17T07:10:02.668130Z     info    FLAG: --profiling="true"
2026-04-17T07:10:02.668132Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2026-04-17T07:10:02.668137Z     info    FLAG: --proxyLogLevel="warning"
2026-04-17T07:10:02.668140Z     info    FLAG: --serviceCluster="istio-proxy"
2026-04-17T07:10:02.668143Z     info    FLAG: --stsPort="0"
2026-04-17T07:10:02.668145Z     info    FLAG: --templateFile=""
2026-04-17T07:10:02.668147Z     info    FLAG: --tokenManagerPlugin=""
2026-04-17T07:10:02.668150Z     info    FLAG: --vklog="0"
2026-04-17T07:10:02.668153Z     info    Version 1.29.2-0c774325b938c4dbda4ea4ad4fb6156e80a12de8-Clean
2026-04-17T07:10:02.668331Z     info    Proxy role      ips=[10.244.0.12 fd00:10:244::26b6] type=sidecar id=sleep-6548446f94-jjclv.istio-mt-ecalonu-0 domain=istio-mt-ecalonu-0.svc.cluster.local
2026-04-17T07:10:02.668387Z     info    Apply proxy config from env {"discoveryAddress":"istiod.istio-mt-ecalonu-0.svc:15012","proxyMetadata":{"ISTIO_META_DNS_AUTO_ALLOCATE":"true","ISTIO_META_DNS_CAPTURE":"true"}}

2026-04-17T07:10:02.669583Z     info    Apply proxy config from annotation proxyMetadata:
  ISTIO_META_DNS_CAPTURE: "true"
  ISTIO_META_DNS_AUTO_ALLOCATE: "true"

2026-04-17T07:10:02.669700Z     info    cpu limit detected as 2, setting concurrency
2026-04-17T07:10:02.670069Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-mt-ecalonu-0.svc:15012
drainDuration: 45s
proxyAdminPort: 15000
proxyMetadata:
  ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  ISTIO_META_DNS_CAPTURE: "true"
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s

2026-04-17T07:10:02.670083Z     info    JWT policy is third-party-jwt
2026-04-17T07:10:02.670087Z     info    using credential fetcher of JWT type in cluster.local trust domain
2026-04-17T07:10:02.871719Z     info    monitoring      The default Prometheus naming translation strategy is planned to be changed from otlptranslator.NoUTF8EscapingWithSuffixes to otlptranslator.UnderscoreEscapingWithSuffixes in a future release. Add prometheus.WithTranslationStrategy(otlptranslator.NoUTF8EscapingWithSuffixes) to preserve the existing behavior, or prometheus.WithTranslationStrategy(otlptranslator.UnderscoreEscapingWithSuffixes) to opt into the future default behavior.
2026-04-17T07:10:02.872226Z     info    dns     Starting local udp DNS server on 127.0.0.1:15053
2026-04-17T07:10:02.873048Z     info    Opening status port 15020
2026-04-17T07:10:02.873185Z     info    dns     Starting local tcp DNS server on 127.0.0.1:15053
2026-04-17T07:10:02.873265Z     info    Starting default Istio SDS Server
2026-04-17T07:10:02.873284Z     info    CA Endpoint istiod.istio-mt-ecalonu-0.svc:15012, provider Citadel
2026-04-17T07:10:02.873307Z     info    Using CA istiod.istio-mt-ecalonu-0.svc:15012 cert with certs: var/run/secrets/istio/root-cert.pem
2026-04-17T07:10:02.874004Z     info    xdsproxy        Initializing with upstream address "istiod.istio-mt-ecalonu-0.svc:15012" and cluster "Kubernetes"
2026-04-17T07:10:02.874514Z     info    sds     Starting SDS grpc server
2026-04-17T07:10:02.874550Z     info    sds     Starting SDS server for workload certificates, will listen on "var/run/secrets/workload-spiffe-uds/socket"
2026-04-17T07:10:02.875578Z     info    Pilot SAN: [istiod.istio-mt-ecalonu-0.svc]
2026-04-17T07:10:02.876549Z     info    Starting proxy agent
2026-04-17T07:10:02.876587Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev.json --drain-time-s 45 --drain-strategy immediate --local-address-ip-version v4 --file-flush-interval-msec 1000 --disable-hot-restart --allow-unknown-static-fields -l warning --component-log-level misc:error --skip-deprecated-logs --concurrency 2]
2026-04-17T07:10:02.934501Z     info    xdsproxy        connected to delta upstream XDS server: istiod.istio-mt-ecalonu-0.svc:15012       id=1
2026-04-17T07:10:02.939800Z     info    cache   generated new workload certificate      resourceName=default latency=65.072985ms ttl=23h59m59.060203219s
2026-04-17T07:10:02.939851Z     info    cache   Root cert has changed, start rotating root cert
2026-04-17T07:10:02.939886Z     info    cache   returned workload trust anchor from cache       ttl=23h59m59.060115205s
2026-04-17T07:10:03.004119Z     info    ads     ADS: new connection for node:1
2026-04-17T07:10:03.004305Z     info    ads     ADS: new connection for node:2
2026-04-17T07:10:03.004510Z     info    cache   adding watcher for symlink certificate /etc/sleep/ca_certs/example.com/cacert -> /etc/sleep/ca_certs/example.com/..data/cacert
2026-04-17T07:10:03.004540Z     info    cache   read certificate from file      resource=file-root:/etc/sleep/ca_certs/example.com/cacert
2026-04-17T07:10:03.004641Z     info    cache   adding watcher for symlink certificate /etc/sleep/client_certs/client.example.com/tls.crt -> /etc/sleep/client_certs/client.example.com/..data/tls.crt
2026-04-17T07:10:03.004676Z     info    cache   read certificate from file      resource=file-cert:/etc/sleep/client_certs/client.example.com/tls.crt~/etc/sleep/client_certs/client.example.com/tls.key
2026-04-17T07:10:03.010818Z     info    ads     ADS: new connection for node:3
2026-04-17T07:10:03.010940Z     info    cache   returned workload trust anchor from cache       ttl=23h59m58.989061904s
2026-04-17T07:10:03.011464Z     info    ads     ADS: new connection for node:4
2026-04-17T07:10:03.011640Z     info    cache   returned workload certificate from cache        ttl=23h59m58.988361381s
2026-04-17T07:10:03.557403Z     info    Readiness succeeded in 892.248666ms
2026-04-17T07:10:03.557667Z     info    Envoy proxy is ready
[2026-04-17T07:12:49.998Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 5 5 "-" "curl/8.6.0" "3121cb76-66bc-4909-8ce5-01e3cb31a43d" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:34090 10.96.86.147:80 10.244.0.12:60516 - -
[2026-04-17T07:14:44.245Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 1 1 "-" "curl/8.6.0" "4932a364-d8cd-4508-84e9-290b938a938d" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:50390 10.96.86.147:80 10.244.0.12:38076 - -
2026-04-17T07:14:44.708003Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_14_44.469913782 : CREATE, pushing to proxy
2026-04-17T07:14:44.708049Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_14_44.469913782 : CHMOD, pushing to proxy
2026-04-17T07:14:44.708059Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..data_tmp : CREATE, pushing to proxy
2026-04-17T07:14:44.708067Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..data : CREATE, pushing to proxy
2026-04-17T07:14:44.708071Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/cacert : CHMOD, pushing to proxy
2026-04-17T07:14:44.708095Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_09_57.2724259091 : REMOVE, pushing to proxy
2026-04-17T07:14:44.708102Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_14_44.849786940 : CREATE, pushing to proxy
2026-04-17T07:14:44.708110Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_14_44.849786940 : CHMOD, pushing to proxy
2026-04-17T07:14:44.708113Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..data_tmp : CREATE, pushing to proxy
2026-04-17T07:14:44.708121Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..data : CREATE, pushing to proxy
2026-04-17T07:14:44.708128Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/tls.crt : CHMOD, pushing to proxy
2026-04-17T07:14:44.708138Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_09_57.3587670804 : REMOVE, pushing to proxy
2026-04-17T07:14:44.708271Z     info    cache   read certificate from file      resource=file-root:/etc/sleep/ca_certs/example.com/cacert
2026-04-17T07:14:44.708510Z     info    cache   read certificate from file      resource=file-cert:/etc/sleep/client_certs/client.example.com/tls.crt~/etc/sleep/client_certs/client.example.com/tls.key
[2026-04-17T07:14:57.428Z] "GET / HTTP/1.1" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure|TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:verify_cert_failed:_X509_verify_cert:_certificate_verification_error_at_depth_0:_unable_to_get_local_issuer_certificate:TLS_error_end} - "TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:verify_cert_failed:_X509_verify_cert:_certificate_verification_error_at_depth_0:_unable_to_get_local_issuer_certificate:TLS_error_end" 0 359 39 - "-" "curl/8.6.0" "f5049a2f-4f35-4d05-91cf-e20f520e56cf" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com - 10.96.86.147:80 10.244.0.12:43568 - -
[2026-04-17T07:15:54.091Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 4 4 "-" "curl/8.6.0" "50204f2f-e6c9-456a-b21b-259b49f5c1ee" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:52726 10.96.86.147:80 10.244.0.12:50146 - -
[2026-04-17T07:16:38.781Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 1 1 "-" "curl/8.6.0" "67daf4fa-9397-449f-abb5-bb050aaaca84" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:42438 10.96.86.147:80 10.244.0.12:56328 - -
2026-04-17T07:17:21.805096Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_17_21.2769404793 : CREATE, pushing to proxy
2026-04-17T07:17:21.805128Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_17_21.2769404793 : CHMOD, pushing to proxy
2026-04-17T07:17:21.805150Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..data_tmp : CREATE, pushing to proxy
2026-04-17T07:17:21.805161Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..data : CREATE, pushing to proxy
2026-04-17T07:17:21.805204Z     info    cache   event for file certificate /etc/sleep/client_certs/client.example.com/..2026_04_17_07_14_44.849786940 : REMOVE, pushing to proxy
2026-04-17T07:17:21.805363Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_17_21.2560987359 : CREATE, pushing to proxy
2026-04-17T07:17:21.805375Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_17_21.2560987359 : CHMOD, pushing to proxy
2026-04-17T07:17:21.805475Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..data_tmp : CREATE, pushing to proxy
2026-04-17T07:17:21.805492Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..data : CREATE, pushing to proxy
2026-04-17T07:17:21.805497Z     info    cache   event for file certificate /etc/sleep/ca_certs/example.com/..2026_04_17_07_14_44.469913782 : REMOVE, pushing to proxy
[2026-04-17T07:17:39.661Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 0 0 "-" "curl/8.6.0" "ba0b39bc-1d24-441e-8b87-8226280d7ffe" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:42438 10.96.86.147:80 10.244.0.12:42704 - -
2026-04-17T07:39:41.297745Z     info    xdsproxy        connected to delta upstream XDS server: istiod.istio-mt-ecalonu-0.svc:15012       id=2
2026-04-17T08:08:28.277701Z     info    xdsproxy        connected to delta upstream XDS server: istiod.istio-mt-ecalonu-0.svc:15012       id=3
[2026-04-17T08:31:24.240Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 4 3 "-" "curl/8.6.0" "b17678f8-3690-4a86-919f-1b1e85908bb1" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:55970 10.96.86.147:80 10.244.0.12:57672 - -
[2026-04-17T08:31:25.775Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 896 1 1 "-" "curl/8.6.0" "776d3708-a384-48a5-a1e7-571bf7b69a68" "nginx.example.com" "10.96.86.147:443" outbound|443||nginx.example.com 10.244.0.12:55976 10.96.86.147:80 10.244.0.12:57676 - -

### PR DESCRIPTION
**Pull request by kfaseela**
File-mounted cert updates are missed after initial Kubernetes secret rotation, so pilot-agent stops pushing refreshed certs to workloads. This bug affects second+ secret rotations only: first rotation typically has a direct cert event, while later rotations may be metadata-only and were skipped by old matching logic.

Fixes: https://github.com/istio/istio/issues/59912

The fix updates file-event matching to treat Kubernetes secret rotation metadata path ..data as valid cert-change signal, and refreshes symlink target watchers when ..data flips, so second-and-later rotations reliably trigger `OnSecretUpdate`.

And an interesting read on the notification sequence here: https://github.com/envoyproxy/envoy/issues/9359#issuecomment-579314094

### CODE REVIEW

File: security/pkg/nodeagent/cache/secretcache_test.go [hunk 1]
```diff
@@ -1256,6 +1257,45 @@ func TestSymlinkDirectoryCleanup(t *testing.T) {
 	})
 }
 
+func TestHandleFileEventKubernetesSecretRotationEventsTriggerUpdate(t *testing.T) {
```
Comment (jaellio) [inline security/pkg/nodeagent/cache/secretcache_test.go:1260]: Does this test fail without the new changes? Want to make sure it captures this failure path so we don't revert in the future.

Comment (kfaseela) [reply security/pkg/nodeagent/cache/secretcache_test.go:1260]: Yes @jaellio. I added two tests .. the first rotation TC passes even without the new changes, but the second rotation test will pass only with this change.

**Comment by calikonur** [comment]
Hi,
Just fyi, I tested the changes done by @kfaseela here in my local environment, and can confirm that the fix resolves our issue.

**Review by hzxuzhonghu — COMMENTED** [review]
I feel the original implement is very tricky, can we reuse https://github.com/istio/istio/tree/master/pkg/filewatcher to be consistent with pilot

**Comment by hzxuzhonghu** [comment]
cc @ramaraochavali to take a look

**Comment by ramaraochavali** [comment]
>I feel the original implement is very tricky, can we reuse https://github.com/istio/istio/tree/master/pkg/filewatcher to be consistent with pilot

How will moving to filewatcher help here? IIRC, it did not support some thing at the time when we implemented this. - that is why we had to use fsnotify directly here. We can reevaluate that in a separate PR

**Review by ramaraochavali — COMMENTED** [review]
LGTM

**Comment by kfaseela** [comment]
> LGTM

Thanks @ramaraochavali and @hzxuzhonghu !

**Comment by kfaseela** [comment]
@jaellio : I have added an integration test to cover this use case as well. Could you please take another look when you get time?

**Review by jaellio — APPROVED** [review]
