### PR TITLE
Fix runaway ingress status errors

### LINKED ISSUE #31336: Removing the default ingress gateway causes runaway logs
**Description**

After installing Istio 1.9.1 with the default profile using istioctl, and subsequently disabling the default istio-ingressgateway with an IstioOperator file and istioctl, the istiod pod/discovery container outputs huge amounts of logs in the format:

```
2021-03-09T07:06:33.010074Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.010260Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.010449Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.010768Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.010970Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.011142Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.011280Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
2021-03-09T07:06:33.011464Z info Work item handle failed (service "istio-ingressgateway" not found), retry after delay 1s
```

When I first applied the change, it was outputing about 2000 logs lines/minute.  This linearly increased over 4 hours to 18000 log lines/minute.  I then restarted the `istiod` deployment and the issue stopped.

If left unnoticed, this could cause very large amounts of logs to be generated (and stored, costing much money).

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

No work should have been attempted on `istio-ingressgateway` as it was removed.  and/or, less log lines should have been generated.

**Steps to reproduce the bug**

Using GKE:

1. Create a new GKE cluster (I used v1.18.16-gke.300)
2. Install Istio 1.9.1 using `istioctl install`
3. Disable the default ingress gateway by applying this config using `istioctl install -f config.yaml`

config.yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
```

4. istiod pod, discovery container starts outputing many logs to stdout

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (3 proxies)

Client Version: v1.16.6-beta.0
Server Version: v1.18.16-gke.300

**How was Istio installed?**

`istioctl install`

**Environment where the bug was observed (cloud vendor, OS, etc)**

Google Cloud / GKE

### PR DESCRIPTION
**Pull request by Monkeyanator**
Fixes #31336, probably want to cherry-pick back through 1.8

Still unclear to me how there could be 2000-18000 logs per minute with the queue rate limiting the errors without multiple status controller queues, which there don't seem to be from goroutine dump

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: pilot/pkg/config/kube/ingress/status.go [hunk 1]
```diff
@@ -84,12 +80,13 @@ func NewStatusSyncer(meshHolder mesh.Holder, client kubelib.Client) *StatusSynce
 		nodeLister:         client.KubeInformer().Core().V1().Nodes().Lister(),
 		ingressClassLister: ingressClassLister,
 		queue:              q,
-		ingressService:     meshHolder.Mesh().IngressService,
-		ingressSelector:    meshHolder.Mesh().IngressSelector,
 	}
 }
 
 func (s *StatusSyncer) onEvent() error {
+	if !s.ingressGatewayExists() {
```
Comment (howardjohn) [inline pilot/pkg/config/kube/ingress/status.go:87]: nit: rather than an extra GET should we just check the resulting err from runningAddresses for IsNotFound? Just to avoid extra calls

**Review by howardjohn — APPROVED** [review]

File: pilot/pkg/config/kube/ingress/status.go (hunk 1 above)
Comment (Monkeyanator) [reply pilot/pkg/config/kube/ingress/status.go]: Makes sense, done
