### PR TITLE
fix namespace parsing in istioctl validate

### LINKED ISSUE #13408: istioctl validate does not parse namespace from input files
Running istioctl validate on YAMLs with namespaces shows that the namespace field is ignored.

### PR DESCRIPTION
**Pull request by kyessenov**
Use goyaml.v2 to parse YAMLs.

Fixes #13408 
Contributes to #12773 
/assign @ozevren 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
/assign @geeknoid 
for vendor update

**Comment by kyessenov** [comment]
@ozevren PTAL
I reverted the update to yaml v3 since I found after experimentation that it does not actually fix the original issue with producing `map[interface{}]interface{}`.

File: istioctl/pkg/validate/validate.go [hunk 1]
```diff
@@ -79,112 +70,106 @@ func (v *validator) validateResource(un *unstructured.Unstructured) error {
...
 		})
 	}
-	return fmt.Errorf("%s.%s validation is not supported", un.GetKind(), un.GetAPIVersion())
-}
 
-var errMissingResource = errors.New(`error: you must specify resources by --filename.
-Example resource specifications include:
-   '-f rsrc.yaml'
-   '--filename=rsrc.json'`)
+	return nil
```
Comment (ozevren) [inline istioctl/pkg/validate/validate.go]: Doesn't this change behavior?

File: istioctl/pkg/validate/validate_test.go [hunk 2]
```diff
@@ -104,15 +104,20 @@ spec:
   - handler: handler-for-valid-rule.denier
     instances:
     - instance-for-valid-rule.checknothing`
-	invalidUnsupportedKey = `
```
Comment (ozevren) [inline istioctl/pkg/validate/validate_test.go]: Not sure why we're removing this test case? Is it subsumed?

File: istioctl/pkg/validate/validate.go (hunk 1 above)
Comment (kyessenov) [reply istioctl/pkg/validate/validate.go]: I found it strange that istioctl invalidates k8s services. I think it should only enforce validation on config that istio owns.

File: istioctl/pkg/validate/validate_test.go (hunk 2 above)
Comment (kyessenov) [reply istioctl/pkg/validate/validate_test.go]: This test is not valuable since validation of k8s envelope is better left to k8s. The tool should be focused on istio config validation, not duplicating the work of other tools.

Comment (kyessenov) [reply istioctl/pkg/validate/validate_test.go]: It is also incorrect to assume that "spec" and "status" are the only fields in the object. That is not part of k8s specification, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#endpoints-v1-core, for example.

Comment (esnible) [reply istioctl/pkg/validate/validate_test.go]: We should keep the check for unknown top-level keys, e.g. `unexpected_junk:`.  The reason is that a common user error is incorrect YAML indentation on optional fields.  Users consistently un-indent fields to the level of `Spec` and then wonder why their field is not respected.

Comment (kyessenov) [reply istioctl/pkg/validate/validate_test.go]: Restored the extra key test for pilot and mixer configs. PTAL.

**Comment by kyessenov** [comment]
@esnible can you /lgtm and /approve?
