### PR TITLE
envoyfilter: fixing patch for http_route affects other virtualhosts

### LINKED ISSUE #44820: patch the route of a specific virtualhost, affecting other virtualhosts
### Bug Description

different virtualHosts may share same routes pointer(which is a slice) as: 
https://github.com/istio/istio/blob/80bf81b2937dfb1a506a88150204bfbee53aaadf/pilot/pkg/networking/core/v1alpha3/httproute.go#L447

but patch the http route inplace:
https://github.com/istio/istio/blob/80bf81b2937dfb1a506a88150204bfbee53aaadf/pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go#L257-L258

reproduce:
1. create virtual service with more then one hosts:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld
  namespace: default
spec:
  hosts:
  - helloworld
  - hellofoo
  http:
  - match:
    - name: exact
      uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
        subset: v1
      weight: 10
    - destination:
        host: helloworld
        port:
          number: 5000
        subset: v2
      weight: 90
```

  got routeconfiguration like：

```
# before apply envoyfilter
$ istioctl proxy-config route xxx.demo -ojson | jq '.[] | select(.name =="5000")'
{
  "name": "5000",
  "virtualHosts": [
    {
// ....
    },
    {
      "name": "hellofoo.default.svc.cluster.local:5000",
      "domains": [...],
      "routes": [
        {
          "name": ".exact",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    },
    {
      "name": "helloworld.default.svc.cluster.local:5000",
      "domains": [
        "helloworld.default.svc.cluster.local",
        "helloworld.default",
        "helloworld.default.svc",
        "10.96.214.152"
      ],
      "routes": [
        {
          "name": ".exact",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    }
  ],
  "validateClusters": false,
  "ignorePortInHostMatching": true
}
```

2.  use envoyfilter to modify the route of vh `helloworld.default.svc.cluster.local:5000` like:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio.io/rev: default
  namespace: demo
  name: patch-helloworld
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: helloworld.default.svc.cluster.local:5000
          route:
            name: .exact
    patch:
      operation: MERGE
      value:
        name: modified-route-name
```

  got routeconfiguration like：

```
# before apply envoyfilter
$ istioctl proxy-config route xxx.demo -ojson | jq '.[] | select(.name =="5000")'
{
  "name": "5000",
  "virtualHosts": [
    {
// ....
    },
    {
      "name": "hellofoo.default.svc.cluster.local:5000",
      "domains": [...],
      "routes": [
        {
          "name": "modified-route-name",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    },
    {
      "name": "helloworld.default.svc.cluster.local:5000",
      "domains": [
        "helloworld.default.svc.cluster.local",
        "helloworld.default",
        "helloworld.default.svc",
        "10.96.214.152"
      ],
      "routes": [
        {
          "name": "modified-route-name",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    }
  ],
  "validateClusters": false,
  "ignorePortInHostMatching": true
}
```

### Version

```Text
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (4 proxies)
$ kubectl version --short  
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by believening**
**Please provide a description of this PR:**

fix #44820

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
It also need a release note, otherwise lgtm

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go [hunk 1]
```diff
@@ -389,6 +394,11 @@ func routeMatch(httpRoute *route.Route, rp *model.EnvoyFilterConfigPatchWrapper)
 	return true
 }
 
-func cloneVhostRouteByRouteIndex(virtualHost *route.VirtualHost, routeIndex int) {
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: How come this previous code did not work? Seems the issue is the route is shared, but here we clone the route that is modified?

Comment (believening) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: Actually, we shared a slice of routes but not a single route itself.

**Comment by believening** [comment]
> It also need a release note, otherwise lgtm

added

**Review by hzxuzhonghu — APPROVED** [review]

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go (hunk 1 above)
Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: If we just share the slice, isn't it more performant to just shallow copy the array and keep cloneVhostRouteByRouteIndex?

Imagine we have 100 elements. We modify 1. 

In this PR, we deep-copy all 100. I think we can just copy the array (cheap) and the 1

Comment (believening) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: I agree. The fix now is based on the code before `cloneVhostRouteByRouteIndex` was introduced. We can simply copy a slice in `cloneVhostRoutes` instead of clone each route. 

If needed, I can submit an optimization to keep cloneVhostRouteByRouteIndex, like:
```
func cloneVhostRoutes(routes []*route.Route) []*route.Route {
	out := make([]*route.Route, len(routes))
	copy(out, routes)
	return out
}
```

**Comment by hzxuzhonghu** [comment]
@ericvn @howardjohn The bot did not work well, i am not codeowner of `releasenotes`. But it merged. Not sure if it is related to recent change

**Comment by hanxiaop** [comment]
> @ericvn @howardjohn The bot did not work well, i am not codeowner of releasenotes. But it merged. Not sure if it is related to recent change

@hzxuzhonghu FYI https://github.com/istio/istio/pull/44395. It is intended to prevent the mere approval of release notes resulting in PR merging.

**Comment by hzxuzhonghu** [comment]
Thanks for the link

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go (hunk 1 above)
Comment (howardjohn) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: I think you can just use `slices.Clone(routes)` now, but SGTM!

Comment (believening) [reply pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go:392]: ack, and please review https://github.com/istio/istio/pull/44885
