### PR TITLE
Pilot: only generate passthrough infra with ip versions provided by proxy

### LINKED ISSUE #16763: Split listener chain binds to ipv6 when ipv6 is not supported, causing LDS ACK ERROR
**Bug description**
I have deployed 1.3.0-rc.1 in my environment with demo profile. and then deployed bookinfo. I found that I cannot visit productpage. 
```
root@cyang1:~/istio-1.3.0-rc.1# kubectl get pod -n default -owide
NAME                              READY   STATUS    RESTARTS   AGE     IP               NODE             NOMINATED NODE   READINESS GATES
details-v1-68fbb76fc-z62pf        2/2     Running   0          4m23s   192.168.14.189   172.16.246.121   <none>           <none>
productpage-v1-6c6c87ffff-tk7r5   2/2     Running   0          4m20s   192.168.14.139   172.16.246.121   <none>           <none>
ratings-v1-7bdfd65ccc-ng92l       2/2     Running   0          4m23s   192.168.14.179   172.16.246.121   <none>           <none>
reviews-v1-5c5b7b9f8d-54hmd       2/2     Running   0          4m22s   192.168.14.188   172.16.246.121   <none>           <none>
reviews-v2-569796655b-sv44k       2/2     Running   0          4m22s   192.168.14.135   172.16.246.121   <none>           <none>
reviews-v3-844bc59d88-vkrfd       2/2     Running   0          4m21s   192.168.14.155   172.16.246.121   <none>           <none>
root@cyang1:~/istio-1.3.0-rc.1# curl 192.168.14.139:9080
curl: (7) Failed to connect to 192.168.14.139 port 9080: Connection refused
```
istioctl ps output
```
root@cyang1:~/istio-1.3.0-rc.1# istioctl ps
NAME                                                   CDS                            LDS                            EDS        RDS          PILOT                            VERSION
details-v1-68fbb76fc-z62pf.default                     STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
istio-egressgateway-75cbf7445d-vvr6b.istio-system      SYNCED                         SYNCED                         SYNCED     NOT SENT     istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
istio-ingressgateway-5cdbc4cdf5-7vzcl.istio-system     SYNCED                         SYNCED                         SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
productpage-v1-6c6c87ffff-tk7r5.default                STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
ratings-v1-7bdfd65ccc-ng92l.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
reviews-v1-5c5b7b9f8d-54hmd.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
reviews-v2-569796655b-sv44k.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
reviews-v3-844bc59d88-vkrfd.default                    STALE (Never Acknowledged)     STALE (Never Acknowledged)     SYNCED     SYNCED       istio-pilot-85dd8f5755-hz5qv     1.3.0-rc.1
```
there is no `15006` listener.

```
root@cyang1:~/istio-1.3.0-rc.1# istioctl pc l productpage-v1-6c6c87ffff-tk7r5.default
ADDRESS            PORT      TYPE
192.168.14.139     9080      HTTP
172.16.0.116       443       TCP
172.16.0.10        53        TCP
172.16.0.116       15032     TCP
172.16.0.128       15011     TCP
172.16.0.1         443       TCP
172.16.0.18        443       TCP
172.16.0.116       15443     TCP
172.16.0.116       15029     TCP
172.16.0.116       15031     TCP
172.16.0.161       443       TCP
172.16.0.176       443       TCP
172.16.0.116       15030     TCP
172.16.0.112       27017     TCP
172.16.0.24        443       TCP
172.16.0.24        15443     TCP
172.16.0.182       8443      TCP
0.0.0.0            27017     TCP
172.16.0.116       31400     TCP
172.16.0.119       8935      TCP
0.0.0.0            28995     TCP
0.0.0.0            8060      TCP
172.16.0.225       9443      TCP
172.16.0.131       3000      TCP
172.16.0.247       3001      TCP
172.16.0.19        42422     TCP
172.16.0.64        4000      TCP
0.0.0.0            20001     TCP
172.16.0.8         8500      TCP
0.0.0.0            8985      TCP
0.0.0.0            9411      TCP
172.16.0.210       10443     TCP
172.16.0.61        8942      TCP
172.16.0.250       14267     TCP
0.0.0.0            9080      TCP
0.0.0.0            9091      TCP
172.16.0.8         8600      TCP
0.0.0.0            9901      TCP
0.0.0.0            80        TCP
172.16.0.116       15020     TCP
172.16.0.250       14268     TCP
172.16.0.225       3100      TCP
172.16.0.79        8383      TCP
0.0.0.0            8080      TCP
172.16.0.120       39001     TCP
0.0.0.0            15004     TCP
172.16.0.118       443       TCP
172.16.0.83        9443      TCP
172.16.0.185       28674     TCP
172.16.0.109       16686     TCP
0.0.0.0            44134     TCP
172.16.0.133       80        TCP
172.16.0.211       3001      TCP
0.0.0.0            9494      TCP
0.0.0.0            15014     TCP
172.16.0.240       6969      TCP
172.16.0.83        4300      TCP
0.0.0.0            3000      TCP
172.16.0.144       7998      TCP
172.16.0.212       80        TCP
172.16.0.230       443       TCP
172.16.0.46        3000      TCP
0.0.0.0            9090      TCP
0.0.0.0            8082      TCP
0.0.0.0            15010     TCP
172.16.0.63        4500      TCP
172.16.0.62        3000      TCP
0.0.0.0            15001     TCP
192.168.14.139     15020     TCP
0.0.0.0            15090     HTTP
```
I have tried in another environment, it works well. I am not sure it is an environment issue or it is a bug. I can append more information if needed. Thanks.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

### PR DESCRIPTION
**Pull request by lambdai**
Generate passthough cluster and listener by ip versions provided by proxy.

fix #16763

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/networking/core/v1alpha3/cluster_test.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ package v1alpha3
 
 import (
 	"fmt"
+	"istio.io/istio/pilot/pkg/networking/util"
```
Comment (golangcibot) [inline pilot/pkg/networking/core/v1alpha3/cluster_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

**Comment by rlenglet** [comment]
@lambdai This will need to be backported to `release-1.3`, so please comment `/cherrypick release-1.3`.

**Comment by rlenglet** [comment]
Hmmm the backport PR didn't get created yet. Normally it happens very quickly.

**Comment by rlenglet** [comment]
@lambdai This doesn't backport cleanly. Please submit a manual backport. Thanks!

**Comment by lambdai** [comment]
ack: manual cp
