### PR TITLE
Fix ingress sds memory leak

### LINKED ISSUE #13197: ingress-sds issues/possible memory-leak
**Describe the bug**
I observed several possibly related issues while using the ingress-sds
1) on larger cluster the ingress-sds seems to leak memory, in magnitude of 2-3 GBs over the span of 3 or 4 days; this seems to correlated with bursts of messages
```
2019-04-09T23:39:34.206560Z	info	SDS: push key/cert pair from node agent to proxy: "router~10.24.24.97~istio-ingressgateway-598b5d6fdc-7qrgj.istio-system~istio-system.svc.cluster.local-39832"
```
10s in a second, thousands a day
```
k logs -n istio-system istio-ingressgateway-598b5d6fdc-7qrgj  ingress-sds --tail 10000 | grep "push key/cert pair from node agent to proxy" | grep "2019-04-09T23:39:34" | wc -l
      38
k logs -n istio-system istio-ingressgateway-598b5d6fdc-7qrgj  ingress-sds  | grep "push key/cert pair from node agent to proxy" | grep "2019-04-09" | wc -l
   21975
```

2) I was able to reproduce similar behavior locally, if I create secret with an empty cert. In such case, the loop never ends, and the process quickly drains memory, until the secret is removed.
(The leak from above can be to some extent reproduced by having this running for a time period, however fixing the cert results in most of the memory released after period of time) 
```
k logs -n istio-system istio-ingressgateway-6796fc8477-d48qv  ingress-sds | grep "2019-04-09T23:52:19" | grep "push key/cert pair from node agent to proxy" | wc -l
     554
```

3) In at least one case, on removal of the secret in question, the sds agent died 
```
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11d88db]

goroutine 631 [running]:
istio.io/istio/security/pkg/nodeagent/sds.pushSDS(0xc4297c4200, 0x15db980, 0x0)
    /workspace/go/src/istio.io/istio/security/pkg/nodeagent/sds/sdsservice.go:344 +0x1db
istio.io/istio/security/pkg/nodeagent/sds.(*sdsservice).StreamSecrets(0xc4203f7040, 0x168ab00, 0xc421028100, 0x0, 0x0)
    /workspace/go/src/istio.io/istio/security/pkg/nodeagent/sds/sdsservice.go:213 +0x7aa
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._SecretDiscoveryService_StreamSecrets_Handler(0x13b9180, 0xc4203f7040, 0x1686480, 0xc420224580, 0x1f55830, 0xc4233ee300)
    /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/sds.pb.go:175 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420311680, 0x168c7e0, 0xc42065a900, 0xc4370be000, 0xc420406720, 0x1f1f7e0, 0x0, 0x0, 0x0)
    /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x911
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420311680, 0x168c7e0, 0xc42065a900, 0xc4370be000, 0x0)
    /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4200445c0, 0xc420311680, 0x168c7e0, 0xc42065a900, 0xc4370be000)
    /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
```

**Expected behavior**
The sds should not leak memory/fail on secret with missing certificate.   

**Steps to reproduce the bug**
follow https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/
when creating the secret, pass an empty file for the cert

```
touch empty.cert.pem
kubectl create -n istio-system secret generic httpbin-credential \
--from-file=key=httpbin.example.com/3_application/private/httpbin.example.com.key.pem \
--from-file=cert=empty.cert.pem
```

**Version**
```
bin/istioctl version --remote
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
galley version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
ingressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
policy version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
telemetry version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
helm template install/kubernetes/helm/istio --set global.mtls.enabled=true --set gateways.istio-egressgateway.enabled=false --set gateways.istio-ingressgateway.sds.enabled=true --name istio --namespace istio-system > ./istio.yaml
kubectl apply -f istio.yaml
```

**Environment**
docker edge for mac (local)
custom build cluster over azure nodes (remote, issue 1))

**Cluster state**
empty cluster with freshly installed istio (for the local reproduction)
cluster served by CI pipeline with handful of random applications (remote)

### PR DESCRIPTION
**Pull request by JimmyCYJ**
When ingress agent starts serving SDS but k8s secret does not exist, instead of sending error message back, let ingress gateway agent wait until k8s secret is ready, and send SDS response with the key/cert. This change follows the [xDS protocol](https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md#acknack-and-versioning). ```The management server may reply either immediately or when the requested resources are available with a DiscoveryResponse```

When k8s secret is deleted by operator, ingress gateway agent will close the stream and force the gateway to send another SDS request. On receiving the new SDS request, instead of sending error message, the ingress gateway agent will wait until a new k8s secret is added. When that k8s secret is added, the ingress gateway agent will notify the gateway by pushing new resource in SDS response. This change follows the [xDS protocol](https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md#when-to-send-an-update). ```The management server should only send updates to the Envoy client when the resources in the DiscoveryResponse have changed. Envoy replies to any DiscoveryResponse with a DiscoveryRequest containing the ACK/NACK immediately after it has been either accepted or rejected. If the management server provides the same set of resources rather than waiting for a change to occur, it will cause Envoy and the management server to spin and have a severe performance impact.```

Fixes #13197

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
I am adding tests for this change.

**Comment by howardjohn** [comment]
From the issue:
```
touch empty.cert.pem
kubectl create -n istio-system secret generic httpbin-credential \
--from-file=key=httpbin.example.com/3_application/private/httpbin.example.com.key.pem \
--from-file=cert=empty.cert.pem
```

This creates a secret, but with an empty cert. This change seems to only handle the case when there is no secret.

Following the above command I saw 50k SDS pushes/second.

Will this change fix this as well or will we need another change?

**Comment by JimmyCYJ** [comment]
> This creates a secret, but with an empty cert. This change seems to only handle the case when there is no secret.

If the secret has an empty cert, the gateway agent does not add that secret into its local storage. Therefore it will not return any secret to the ingress gateway, and the SDS request is still pending. Once the operator deletes the invalid secret and create a valid secret, the ingress gateway agent will add the valid secret into its local storage, and notify the gateway by pushing the new secret.

**Comment by howardjohn** [comment]
Is this still a wip?

File: security/pkg/nodeagent/sds/sdsservice_test.go [hunk 1]
```diff
@@ -471,3 +471,7 @@ func (ms *mockSecretStore) DeleteSecret(conID, resourceName string) {
 	}
 	ms.secrets.Delete(key)
 }
+
+func (ms *mockSecretStore) ShouldWaitForIngressGatewaySecret(connectionID, resourceName, token string) bool {
+	return false
```
Comment (duderino) [inline security/pkg/nodeagent/sds/sdsservice_test.go]: So this mocks out the new code instead of testing it.  It'd be nice to see a test for the new code.

Comment (duderino) [reply security/pkg/nodeagent/sds/sdsservice_test.go]: Looks like the test case arrived at the same time I added this comment.  Thanks for adding it

Comment (JimmyCYJ) [reply security/pkg/nodeagent/sds/sdsservice_test.go]: The mock in this test is to test success cases, which means a SDS response is always sent out from the server, and the test verifies that response contains expected key/cert. 

I don't find an easy way to test the case when ShouldWaitForIngressGatewaySecret returns true. Because when ShouldWaitForIngressGatewaySecret return true, [stream.Recv()](https://github.com/istio/istio/blob/b43c5a1704164aa5d3a72f7bc67f0df6bdf9f28e/security/pkg/nodeagent/sds/sdsservice_test.go#L395) in the test does not return, the server just holds the stream and waits for secret to be ready. Without this change, the server sends an error message and that causes the gateway to send another SDS request immediately, which causes the memory issue.

Maybe I can add some e2e tests for the ingress sds in tests/e2e, or add a new test framework in nodeagent/ to support testing this scenario. Is it okay to let these tests in a separate PR?

**Comment by JimmyCYJ** [comment]
I built a docker image docker.io/jimmycyj/node-agent-k8s:b43c5a1704164aa5d3a72f7bc67f0df6bdf9f28e with this fix. I create 70 gateways with 70 credentials but no k8s secret is created, this forces ingress gateway to send SDS request but does not get any response. The ingress-sds does not send error message now, and I am watching the memory usage.

**Comment by JimmyCYJ** [comment]
@duderino could you please help to merge this PR?

**Comment by JimmyCYJ** [comment]
Screenshot from 2019-04-11 16-54-06

Here is the memory usage, I add 70 gateway around 23:15, the memory consumption is 7M. Previously this is over 200M
