### PR TITLE
ensure validatingwebhookconfigurations deleted before test suite return

### LINKED ISSUE #7593: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot: service "istio-galley" not found
https://k8s-gubernator.appspot.com/build/istio-prow/istio-pilot-e2e-envoyv2-v1alpha3/4840/

### PR DESCRIPTION
**Pull request by lichuqiang**
fix #7593 

ensure validatingwebhookconfigurations deleted before test suite return

### CODE REVIEW

**Comment by lichuqiang** [comment]
/assign @ayj 
Add the check in kubernetes framework, PTAL

File: tests/util/kube_utils.go [hunk 1]
```diff
@@ -127,6 +127,15 @@ func NamespaceDeleted(n string, kubeconfig string) (bool, error) {
 	return false, err
 }
 
+// ValidatingWebhookConfigurationDeleted check if a kubernetes ValidatingWebhookConfiguration is deleted
+func ValidatingWebhookConfigurationDeleted(name string, kubeconfig string) (bool, error) {
```
Comment (ayj) [inline tests/util/kube_utils.go]: Only the boolean `deleted` value is checked and the `err` return value is always ignored. Consider removing the error unless the caller needs to do something with the error value.

Comment (lichuqiang) [reply tests/util/kube_utils.go]: done

File: tests/util/kube_utils.go [hunk 2]
```diff
@@ -127,6 +127,15 @@ func NamespaceDeleted(n string, kubeconfig string) (bool, error) {
 	return false, err
 }
 
+// ValidatingWebhookConfigurationDeleted check if a kubernetes ValidatingWebhookConfiguration is deleted
+func ValidatingWebhookConfigurationDeleted(name string, kubeconfig string) bool {
+	output, _ := ShellSilent("kubectl get validatingwebhookconfiguration %s -o name --kubeconfig=%s", name, kubeconfig)
+	if strings.Contains(output, "NotFound") {
```
Comment (ayj) [inline tests/util/kube_utils.go]: You can use the `strings.Contains` return value directly, i.e.

```golang
return strings.Contains(output, "NotFound")
```

**Comment by ayj** [comment]
@lichuqiang, are you still actively working on this PR?

**Comment by lichuqiang** [comment]
@ayj Yeah, I've got your comments addressed. But seems I'll still need comments from someone with approve permission of test path.

**Comment by ayj** [comment]
cc @hklai

File: tests/e2e/framework/kubernetes.go [hunk 3]
```diff
@@ -491,12 +491,20 @@ func (k *KubeInfo) Teardown() error {
...
+	validatingWebhookConfigurationDeleted := false
 	log.Infof("Deleting namespace %v", k.Namespace)
 	for attempts := 1; attempts <= maxAttempts; attempts++ {
 		namespaceDeleted, _ = util.NamespaceDeleted(k.Namespace, k.KubeConfig)
-		if namespaceDeleted {
+		// As validatingWebhookConfiguration "istio-galley" will
+		// be delete by kubernetes GC controller asynchronously,
+		// we need to ensure it's deleted before return.
+		// TODO: find a more general way as long term solution.
+		validatingWebhookConfigurationDeleted = util.ValidatingWebhookConfigurationDeleted("istio-galley", k.KubeConfig)
```
Comment (hklai) [inline tests/e2e/framework/kubernetes.go]: is the name is always "istio-galley"? If so, do we even need to parameterize it in util.ValidatingWebhookConfigurationDeleted?

Comment (ayj) [reply tests/e2e/framework/kubernetes.go]: My understanding is what `istio.io/istio/tests/util` is fairly generic k8s test utility code. The configuration validation webhook is typically named `istio-galley`, but in theory istio-galley could be renamed and/or we find other uses for validating webhooks.
