### PR TITLE
Fix connection lock

### LINKED ISSUE #26216: TestSyncz/return_the_sent_and_ack_status_of_adsClient_connections flake
**Bug description**

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26112/unit-tests_istio/18321

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
hope to fix #26216

### CODE REVIEW

File: pilot/pkg/xds/ads.go [hunk 1]
```diff
@@ -482,12 +482,11 @@ func (s *DiscoveryServer) initConnection(node *core.Node, con *Connection) error
 	}
 
 	// First request so initialize connection id and start tracking it.
-	con.mu.Lock()
```
Comment (hzxuzhonghu) [inline pilot/pkg/xds/ads.go:485]: We donot need this lock, it is initiated here will not be used before adding to connection pool
