### PR TITLE
Fix excessive mixer cpu usage in release 1.0

### LINKED ISSUE #9604: Performance Regression: mixer cpu use significantly higher in 1.0.3
Hey, 
Noticed this this morning.  In one of our production clusters on 1.0.2 (actually getting 10x the load of pre-prod):

Istio policy is nice and low
screen shot 2018-10-29 at 13 26 35

And then our 1.0.3 upgraded pre-prod cluster, istio-policy using 15x as much:
screen shot 2018-10-29 at 13 26 51

### PR DESCRIPTION
**Pull request by bianpengyuan**
Reduce channel reads for crd discovery retry.

Fix #9604

### CODE REVIEW

File: mixer/pkg/config/crd/store.go [hunk 1]
```diff
@@ -204,17 +204,19 @@ func (s *Store) retryCreateCache(
...
 		case <-s.donec:
 			stopRetry = true
-		case <-tick:
+		default:
 			rm := s.checkAndCreateCaches(d, lwBuilder, remaining)
 			if len(rm) < len(remaining) {
 				log.Debugf("discovered %v new kinds, remaining undiscovered kinds: %v", len(remaining)-len(rm), rm)
 			}
 			remaining = rm
-		default:
```
Comment (mandarjog) [inline mixer/pkg/config/crd/store.go]: Simply having an empty `default` will potentially cause a tight loop, so removing `default` case will also help and will be minimal change. 
how did you test this?

Comment (bianpengyuan) [reply mixer/pkg/config/crd/store.go]: Why does removing `default` help? All channel cases will still be checked without any interval between loops right? By changing loop condition into `range tick`, number of channel reads reduces, so does cpu.

I repro the cpu issue and fixed it with this change. I cannot find a good way to add an unit test for this change tho. The unit test for the origin change was to test if retry interval is respected by checking if the total execution time of background retry longer than a certain period.

Comment (hzxuzhonghu) [reply mixer/pkg/config/crd/store.go]: Agree, remove default can also solve it.

File: mixer/pkg/config/crd/store.go [hunk 2]
```diff
@@ -204,17 +204,19 @@ func (s *Store) retryCreateCache(
 	tick := time.Tick(s.bgRetryInterval)
```
Comment (hzxuzhonghu) [inline mixer/pkg/config/crd/store.go]: Here should use NewTicker,  and should stop ticker.

File: mixer/pkg/config/crd/store.go (hunk 1 above)
Comment (mandarjog) [reply mixer/pkg/config/crd/store.go]: Peter, selecting on multiple blocking channels will not cause a tight loop. Select blocks until one of the channel fires. When default is added, default always fires and causes the tight loop.

Comment (bianpengyuan) [reply mixer/pkg/config/crd/store.go]: I see. Thanks!

File: mixer/pkg/config/crd/store.go (hunk 2 above)
Comment (bianpengyuan) [reply mixer/pkg/config/crd/store.go]: Done.

**Comment by mandarjog** [comment]
@bianpengyuan please also send a PR to 1.1 / master branch as necessary.
