### PR TITLE
multi-network: gateways filter out endpoints for other gateways

### LINKED ISSUE #26293: multi-network causes extra gateway hops
** Tasks **
- [X] Make EDS use REQUESTED_NETWORK_VIEW (#26729) 
- [x] Add samples/test for a separate east-west gateway, with network view set (#27222)
- [x] Include east-west gateway in multicluster/multinetwork docs
- [x] Add support to istioctl for more easily deploying east-west gateway

**Bug description**

<details>

<summary> Bug description </summary>

In https://github.com/istio/istio/pull/26393, it's apparent that when load balancing traffic for the same service deployed in different networks, the instances in the same network as the origin are preferred. 

Note: In the example below, clusters 0, 1 and 2 share a network, clusters 3 and 4 share a different network. Every cluster has an ingress-gateway. 

```
2020-08-12T22:19:37.531901Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-0]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:26 cluster-1:30 cluster-2:32 cluster-3:4 cluster-4:8]
2020-08-12T22:19:37.940415Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-0] (408.506665ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1
2020-08-12T22:19:37.940744Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:28 cluster-1:20 cluster-2:25 cluster-3:12 cluster-4:15]
2020-08-12T22:19:38.325885Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1] (385.133412ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2
2020-08-12T22:19:38.326141Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:24 cluster-1:28 cluster-2:25 cluster-3:15 cluster-4:8]
2020-08-12T22:19:38.770892Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2] (444.742841ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3
2020-08-12T22:19:38.771178Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:20 cluster-1:14 cluster-2:14 cluster-3:23 cluster-4:29]
2020-08-12T22:19:39.162013Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3] (390.829998ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4
2020-08-12T22:19:39.162233Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:17 cluster-1:15 cluster-2:18 cluster-3:27 cluster-4:23]
2020-08-12T22:19:39.566030Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4] (403.791484ms)' ===
```

This is likely due to the fact that the gateways in each network/cluster perform their own client side loadbalancing to the destination service. The gateways in the second network may include the gateways from the first network in their endpoints adding more complexity.

Given a setup with:
- 3 clusters in network 1
- 2 clusters in network 2
- the same "echo" service in every cluster
- an ingress gateway in every cluster

An envoy in network1 will have 3 endpoints for the local network's instances, and 2 endpoints for each of the remote gateways. The logic in  [EndpointsByNetworkFilter](https://github.com/istio/istio/blob/4d59ea4d42d69d2323d25e66eec5180ec0ef7b80/pilot/pkg/xds/ep_filters.go#L33) ensures that network1 endpoints will have a weight of 2 while the network2 gateway endpoints will also have a weight of 2. 

IIUC the gateways themselves will also perform some load-balancing that may further skew this. Routing requests back to the origin cluster. I need to confirm/deny this with somehow. 

https://github.com/istio/istio/blob/4d59ea4d42d69d2323d25e66eec5180ec0ef7b80/pilot/pkg/xds/ep_filters.go#L28-L41

**Expected behavior**

Traffic is nearly even to each cluster in the mesh.

**Steps to reproduce the bug**

1. Setup a mesh with at least 2 clusters in one network and 1 cluster in another. 
2. Deploy the same service to all clusters. 
3. From the network with multiple clusters, make a large number of requests. 
4. Check the origin of the responses. This bug causes them to mostly come from clusters in the origin network. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Latest master (1.7.x)

**How was Istio installed?**

Using the test framework

**Environment where bug was observed (cloud vendor, OS, etc)**

KinD, GKE. 

</details>

### PR DESCRIPTION
**Pull request by stevenctl**
This should prevent scenarios in multi-network where a gateway sends traffic back to another gateway. It probably won't solve the problem of having equal traffic distribution. For multiple clusters in a network that each have their own gateway. 

- Default requested network view includes all networks
- The default unspecified network is always in scope
- Endpoint filters respect network view

fixes https://github.com/istio/istio/issues/26293

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: pilot/pkg/xds/ep_filters.go [hunk 1]
```diff
@@ -111,10 +112,16 @@ func EndpointsByNetworkFilter(push *model.PushContext, proxyNetwork string, endp
...
 				// TODO: figure out a way to extract locality data from the gateway public endpoints in meshNetworks
 				gwEp.Metadata = util.BuildLbEndpointMetadata(network, model.IstioMutualTLSModeLabel)
-				lbEndpoints = append(lbEndpoints, gwEp)
+				remoteLbEps = append(remoteLbEps, gwEp)
 			}
 		}
 
+		// Only include remote endpoints for a gateway if we have no local endpoints
+		// Normal proxies always get all the endpoints.
+		if proxyType != model.Router || (len(remoteLbEps) > 0 && len(lbEndpoints) == 0) {
```
Comment (hzxuzhonghu) [inline pilot/pkg/xds/ep_filters.go:121]: Could this egress gateway always send traffic to local cluster endpoints?

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:121]: I understand for a gateway, only add the endpoints of remote cluster/network if there is no  local endpoints

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:125]: @stevenctl

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:125]: Egress gateways should be sending traffic outside the mesh. This is intended to force local network endpoints, not local cluster. We can't expect every cluster in a network to run an ingress.

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:125]: But this is a regression in some degree, lets discuss it. @howardjohn

Comment (howardjohn) [reply pilot/pkg/xds/ep_filters.go:125]: @stevenctl are we only filtering other gateways? IE if I have my gateway in network "A" and I am sending a request to some external service in network "B" (not a gateway!), will it still show up?

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:125]: If we're building endpoints for a gateway, we will not send traffic to another gateway.

In what case would we set network for an external service? IIUC the primary purpose of setting network is to intentionally go through an istio gateway with passthrough.

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:125]: So if somehow we had things setup to go pod -> egress gw (net A) -> ingress (net B) -> svc net B, that would get blocked. 

pod -> egress -> external service should be fine, not sure where networks come into play though.

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:125]: Actually we did support clients in a cluster to send traffic out via egress gateway,  in this case 

client pods in cluster A  --> egress gateway in cluster A  ---> server pods in cluster A
                                                               | 
                                                               |   X
                                                               | 
                                                              cluster B pods

Here one cluster is in one network

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:125]: Ah. I suppose in that case we're not at risk of the bug this intends to fix, and we should still be able to go cross-network. I'll look into how to determine this is only for _ingress_ gateway. Thanks!

File: pilot/pkg/xds/ep_filters.go [hunk 2]
```diff
@@ -111,10 +111,17 @@ func EndpointsByNetworkFilter(push *model.PushContext, proxyNetwork string, endp
...
 				// TODO: figure out a way to extract locality data from the gateway public endpoints in meshNetworks
 				gwEp.Metadata = util.BuildLbEndpointMetadata(network, model.IstioMutualTLSModeLabel)
-				lbEndpoints = append(lbEndpoints, gwEp)
+				remoteLbEps = append(remoteLbEps, gwEp)
 			}
 		}
 
+		// Only include remote endpoints for an ingress-gateway if we have no local endpoints
+		// Normal proxies or egress gateways always get all the endpoints.
+		isIngress := b.proxyType == model.Router && b.routerMode == model.SniDnatRouter
```
Comment (stevenctl) [inline pilot/pkg/xds/ep_filters.go:120]: Can you confirm `SniDnatRouter` is a valid way to determine that this is ingress? @hzxuzhonghu

File: pilot/pkg/xds/ep_filters.go (hunk 1 above)
Comment (ramaraochavali) [reply pilot/pkg/xds/ep_filters.go]: @hzxuzhonghu I am curious what is the usecase for client pods to go via egress gateway to server pods in same cluster and network?

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go]: Just when the server instances are across networks and let's say the client can not access the remote network gateway.

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go]: From the client's view, they are not aware of where the server resides. Only a service hostname is known

File: pilot/pkg/xds/ep_filters.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:120]: Not right, the sni-dnat is for all the gateways as you can see from the default yaml

File: pilot/pkg/xds/ep_filters.go (hunk 1 above)
Comment (ramaraochavali) [reply pilot/pkg/xds/ep_filters.go]: Ok. Only when server instances span across multiple networks?

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go]: Yes. Rare use case

Comment (ramaraochavali) [reply pilot/pkg/xds/ep_filters.go]: Ok. got it. thanks

File: pilot/pkg/xds/ep_filters.go (hunk 2 above)
Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:120]: Is the label `istio=ingressgateway` reliable? Seems like the user really doesn't have to have this and it could me missing if they have a custom setup.

Comment (howardjohn) [reply pilot/pkg/xds/ep_filters.go:120]: No, we cannot rely on the labels. The goal is to determine if its an ingress or egress gateway? We don't have a way to do this - egress and ingress gateways are technically the same and are just used different as a standard practice.

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:120]: In comment thread above @hzxuzhonghu explained a case this would break if we are going from `client in network a -> egress in network a -> ingress in network b -> server in network -> b`, where we have the destination service in both networks. So we'd still want egress to talk to ingress, but ingress should only go to the actual endpoints. 

Alternatives would be:
1. wait for BTS to allow header based routing and `Forwarded` header. 
2. Use priority + outlier detection to just use the other network as a failover in the egress case. 
3. Something at the user-config level that's only applied to ingress
4. Ignore that edge-case

**Comment by tbarrella** [comment]
What about setting `ISTIO_META_REQUESTED_NETWORK_VIEW` on the gateway in multi-network setups? It looks like it's meant to be used for this purpose, although it's not clear to me that it actually works..

File: pilot/pkg/xds/ep_filters.go (hunk 2 above)
Comment (tbarrella) [reply pilot/pkg/xds/ep_filters.go:120]: What about setting `ISTIO_META_REQUESTED_NETWORK_VIEW` on the gateway Deployment? It appears to be intended for this purpose, of filtering out endpoints in other networks. I'm not sure if it works though

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:120]: I don't see any references to that outside of YAML :/  Do you see references in docs?

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:120]: I'm assuming you mean, if it's not "external" then don't build the cross-network endpoints, right? If we go that direction, and we already as default for egress, we'd need to make sure it's documented for people who want to setup custom gateways.

Comment (tbarrella) [reply pilot/pkg/xds/ep_filters.go:120]: I saw it when looking at code; it sets node metadata `RequestedNetworkView` which is used to filter out endpoints in clusters https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L219

It seems like if the value is the name of the gateway's network, it would filter out endpoints from other networks

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go:120]: My bad - grep shouldn't have included `ISTIO_META_`. Seems like that would work. For the case where we have a service in network b, it wouldn't be reachable from `network a` ingress, but that's probably fine if we're only setting the network-view for a special cross-cluster ingress.

Comment (hzxuzhonghu) [reply pilot/pkg/xds/ep_filters.go:120]: `RequestedNetworkView`  could be a good direction, And I find that we donot consider it when filtering eds currently.

Comment (stevenctl) [reply pilot/pkg/xds/ep_filters.go]: Seems like a good idea, but we should make sure we don't add additional confusion to multi-network installation. 

1. The default for all proxies is currently `{"":true}` - meaning by default, proxies are _already_ filtering out DNSLB services for cross-network. We should change the default to be "this proxy sees all networks". 

2. Users shouldn't really use the same gateway for normal ingress and cross-network. Since the cross-network concern has special requirements, does it make sense to have a `istio-cross-network` deployment template to help users set things up, and provide an example for when the want to do something custom. 

cc @nmittler

File: manifests/charts/gateways/istio-ingress/templates/deployment.yaml [hunk 3]
```diff
@@ -223,6 +223,14 @@ spec:
           - name: ISTIO_META_NETWORK
             value: {{ .Values.global.network }}
           {{- end }}
+          {{- if $network_set }}
+          - name: ISTIO_META_NETWORK
+            value: {{ $network_set }}
+          {{- end }}
+          {{- if and (not $network_set) .Values.global.network }}
```
Comment (nmittler) [inline manifests/charts/gateways/istio-ingress/templates/deployment.yaml:230]: Isn't this the same condition as above? Should we just merge it?

Comment (stevenctl) [reply manifests/charts/gateways/istio-ingress/templates/deployment.yaml:230]: Sort of - one is if they set it in values.global, one is if they set it themselves. Can be merged to just resolve the final value of the var and then use it.

Comment (stevenctl) [reply manifests/charts/gateways/istio-ingress/templates/deployment.yaml:230]: Probably removing this from ingress though.

File: pilot/pkg/xds/ep_filters.go (hunk 2 above)
Comment (nmittler) [reply pilot/pkg/xds/ep_filters.go]: Yes, we should have completely different ingress deployments for an ingress used for east-west traffic in general. We should also update the samples to use custom ingresses:

- https://github.com/istio/istio/tree/master/samples/cross-network-gateway
- https://github.com/istio/istio/tree/master/samples/istiod-gateway

WDYT?

File: pilot/pkg/xds/endpoint_builder.go [hunk 4]
```diff
@@ -78,9 +82,18 @@ func (b EndpointBuilder) Key() string {
 	if b.service != nil {
 		params = append(params, string(b.service.Hostname)+"/"+b.service.Attributes.Namespace)
 	}
+	if b.networkView != nil {
```
Comment (stevenctl) [inline pilot/pkg/xds/endpoint_builder.go:85]: cc @ramaraochavali @howardjohn does this make sense?

File: pilot/pkg/xds/endpoint_builder.go [hunk 5]
```diff
@@ -30,8 +30,10 @@ import (
 
 type EndpointBuilder struct {
 	// These fields define the primary key for an endpoint, and can be used as a cache key
+	proxyName       string
```
Comment (howardjohn) [inline pilot/pkg/xds/endpoint_builder.go:33]: if its not in the key it should be below L42

Comment (howardjohn) [reply pilot/pkg/xds/endpoint_builder.go:33]: actually its not used at all, can just remove it?

File: pilot/pkg/xds/endpoint_builder.go [hunk 6]
```diff
@@ -78,9 +82,18 @@ func (b EndpointBuilder) Key() string {
 	if b.service != nil {
 		params = append(params, string(b.service.Hostname)+"/"+b.service.Attributes.Namespace)
 	}
+	if b.networkView != nil {
+		for nw := range b.networkView {
+			params = append(params, nw)
+		}
```
Comment (rshriram) [inline pilot/pkg/xds/endpoint_builder.go:88]: this is not right.. the order of iteration on a map is non-deterministic. So the key string will change from one call ot another for the same endpoint.

File: pilot/pkg/xds/endpoint_builder.go [hunk 7]
```diff
@@ -78,9 +82,18 @@ func (b EndpointBuilder) Key() string {
...
+	}
 	return strings.Join(params, "~")
 }
 
+func (b *EndpointBuilder) IsMultinetwork() bool {
+	return b.push.Networks != nil && len(b.push.Networks.Networks) > 0
```
Comment (rshriram) [inline pilot/pkg/xds/endpoint_builder.go:94]: what does this mean? if endpoints have network setting but the global meshNetworks map is not present? How do we distinguish between a temporarily unavailable meshNetworks map (one where the admin forgot to add it) vs one that is truly absent (i.e. user telling us to ignore networks field)?

Comment (stevenctl) [reply pilot/pkg/xds/endpoint_builder.go:94]: This just moves current behavior into a method. The name isn't great though, I'll try to clarify. 

I don't think we care about whether or not the user _meant_ to have the meshNetworks settings missing. But I guess it should go in the cache key so we can recompute if it's added/removed later.

File: pilot/pkg/xds/endpoint_builder.go [hunk 8]
```diff
@@ -78,9 +83,53 @@ func (b EndpointBuilder) Key() string {
 	if b.service != nil {
 		params = append(params, string(b.service.Hostname)+"/"+b.service.Attributes.Namespace)
 	}
+	params = append(params, b.multinetworkKey()...)
 	return strings.Join(params, "~")
 }
 
+func (b EndpointBuilder) multinetworkKey() []string {
```
Comment (stevenctl) [inline pilot/pkg/xds/endpoint_builder.go:90]: I'm concerned that the EDS cache issues with multicluster/multinetwork. 

- When new endpoints for a service that's already in the cache are discovered in a different cluster-registry, will the cache be evicted? Does this apply just to multicluster? 
- For multi-network it's clear that as-is, changes to the multi-network config will not effect EDS and we'll just be using cached responses. This PR tries to fix some of that but needs a lot of cleanup.

Comment (stevenctl) [reply pilot/pkg/xds/endpoint_builder.go:90]: Thoughts on making multi-network "uncacheable" in this PR then implementing that properly in a follow-up? @howardjohn

**Comment by stevenctl** [comment]
This should work fine though. There's an edge case where all proxies with a cache entry for the same network view and endpoint have their network view change, the cache entries aren't evicted till the cached service is updated.

File: pilot/pkg/xds/eds.go [hunk 9]
```diff
@@ -277,8 +277,8 @@ func (s *DiscoveryServer) generateEndpoints(b EndpointBuilder) *endpoint.Cluster
 
 	// If networks are set (by default they aren't) apply the Split Horizon
 	// EDS filter on the endpoints
-	if b.push.Networks != nil && len(b.push.Networks.Networks) > 0 {
-		l.Endpoints = EndpointsByNetworkFilter(b.push, b.network, l.Endpoints)
+	if b.MultinetworkConfigured() {
```
Comment (hzxuzhonghu) [inline pilot/pkg/xds/eds.go:280]: s/MultinetworkConfigured/MultiNetworkConfigured

File: pilot/pkg/xds/eds.go [hunk 10]
```diff
@@ -362,6 +362,8 @@ func (eds *EdsGenerator) Generate(proxy *model.Proxy, push *model.PushContext, w
 			}
 		}
 		builder := NewEndpointBuilder(clusterName, proxy, push)
+
+		// TODO(landow) we're using cached endpoints even if eps' networks change or eps are added from diff cluster
```
Comment (hzxuzhonghu) [inline pilot/pkg/xds/eds.go:366]: What do you mean here? the cache is cleared in `AdsPushAll`. 

```
	if len(req.ConfigsUpdated) == 0 {
		s.cache.ClearAll()
	} else {
		// Otherwise, just clear the updated configs
		s.cache.Clear(req.ConfigsUpdated)
	}
```

**Review by hzxuzhonghu — APPROVED** [review]

File: pkg/test/framework/components/istio/operator.go [hunk 11]
```diff
@@ -477,8 +477,14 @@ func deployControlPlane(c *operatorComponent, cfg Config, cluster resource.Clust
...
 		if networkName := cluster.NetworkName(); networkName != "" {
-			installSettings = append(installSettings, "--set", "values.global.meshID="+meshID,
-				"--set", "values.global.network="+networkName)
+			installSettings = append(installSettings,
+				"--set", "values.global.meshID="+meshID,
+				"--set", "values.global.network="+networkName,
+				// TODO(landow) remove these in favor of a dedicated cross-network gateway deployment
+				// ingress must be enabled for multi-network
+				"--set", "values.gateways.istio-ingressgateway.enabled=true",
+				// prevents gateways from calling gateways and throwing off cross-network traffic
```
Comment (howardjohn) [inline pkg/test/framework/components/istio/operator.go:486]: Will users need to set this?

**Review by howardjohn — APPROVED** [review]

File: pkg/test/framework/components/istio/operator.go (hunk 11 above)
Comment (stevenctl) [reply pkg/test/framework/components/istio/operator.go:486]: To fix this issue, they need the second flag. Multinetwork will function without it though. I'm going to follow up with a doc/PR for having a separate deployment just for cross-network.
