### PR TITLE
Simplify istioctl version warning

### LINKED ISSUE #18986: `istioctl version` on a cluster without istio shows strange warning
**Bug description**
```
~ 🏎  $ istioctl version
2019-11-15T14:48:41.027389Z	warn	will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.4.0
```

**Expected behavior**

**Steps to reproduce the bug**
Run `istioctl version` on a cluster which does not have istio installed

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
Not Installed

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

@esnible

### PR DESCRIPTION
**Pull request by shamsher31**
This fixes #18986

### CODE REVIEW

File: istioctl/cmd/version.go [hunk 1]
```diff
@@ -64,6 +66,16 @@ func getRemoteInfo() (*istioVersion.MeshInfo, error) {
 	return kubeClient.GetIstioVersions(istioNamespace)
 }
 
+func getRemoteInfoWrapper(pc **cobra.Command) func() (*istioVersion.MeshInfo, error) {
```
Comment (dgn) [inline istioctl/cmd/version.go]: Why introduce a wrapper? The method is only used in this one place, it might as well implement proper error handling directly
