### PR TITLE
Fix linter errors.

### LINKED ISSUE #1446: Istio-security linter errors
```
I1103 22:41:44.803] security/cmd/node_agent/na/nodeagent_test.go:1::warning: file is not gofmted with -s (gofmt)
I1103 22:41:44.803] security/pkg/pki/ca/ca.go:1::warning: file is not gofmted with -s (gofmt)
I1103 22:41:44.804] security/pkg/pki/ca/ca_test.go:1::warning: file is not gofmted with -s (gofmt)
I1103 22:41:44.804] security/pkg/pki/ca/controller/secret.go:1::warning: file is not gofmted with -s (gofmt)
I1103 22:41:44.804] security/pkg/pki/ca/controller/secret_test.go:1::warning: file is not gofmted with -s (gofmt)
I1103 22:41:53.633] security/cmd/node_agent/na/nodeagent_test.go:1::warning: file is not goimported (goimports)
I1103 22:41:53.634] security/pkg/pki/ca/ca.go:1::warning: file is not goimported (goimports)
I1103 22:41:53.672] security/pkg/pki/ca/ca_test.go:1::warning: file is not goimported (goimports)
I1103 22:41:53.672] security/pkg/pki/ca/controller/secret.go:1::warning: file is not goimported (goimports)
I1103 22:41:53.673] security/pkg/pki/ca/controller/secret_test.go:1::warning: file is not goimported (goimports)
I1103 22:41:53.791] security/cmd/node_agent/na/nafactory.go:35:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.791] security/cmd/node_agent/na/nodeagent.go:43:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.792] security/cmd/node_agent/na/nodeagent.go:51:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.792] security/cmd/node_agent/na/nodeagent_test.go:50:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.792] security/cmd/node_agent/na/nodeagent_test.go:145:50:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.792] security/pkg/pki/crypto.go:34:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.792] security/pkg/pki/crypto.go:39:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.793] security/pkg/pki/crypto.go:50:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.793] security/pkg/pki/crypto.go:54:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.793] security/pkg/pki/crypto.go:63:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.793] security/pkg/pki/crypto.go:70:27:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.793] security/pkg/pki/crypto.go:76:27:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.794] security/pkg/pki/crypto.go:80:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.794] security/pkg/pki/san.go:92:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.794] security/pkg/pki/san.go:104:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.794] security/pkg/pki/san.go:111:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.794] security/pkg/pki/san.go:116:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:101:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:105:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:109:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:113:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:117:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.795] security/pkg/pki/testutil/util.go:121:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.796] security/pkg/platform/aws.go:90:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.796] security/pkg/platform/aws.go:95:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.796] security/pkg/platform/aws.go:100:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.796] security/pkg/platform/aws.go:105:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.796] security/pkg/platform/aws.go:110:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.797] security/pkg/platform/aws.go:121:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.797] security/pkg/platform/aws.go:126:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.797] security/pkg/platform/client.go:57:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.797] security/pkg/platform/onprem.go:68:25:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.798] security/pkg/platform/onprem.go:77:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.798] security/pkg/platform/onprem.go:95:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.798] security/pkg/platform/onprem.go:102:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
I1103 22:41:53.798] security/pkg/platform/onprem.go:107:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
```

### PR DESCRIPTION
**Pull request by JimmyCYJ**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1446

**Special notes for your reviewer**:
The following linter errors are reported by linters.sh, and are fixed in this PR.
security/integration/main.go:151:13:warning: "Succesfully" is a misspelling of "Successfully" (misspell)
security/integration/main.go:368::error: unreachable code (vet)
security/cmd/istio_ca/main.go:171::warning: declaration of "ca" shadows declaration at security/cmd/istio_ca/main.go:32 (vetshadow)
security/cmd/istio_ca/main.go:191::warning: declaration of "ca" shadows declaration at security/cmd/istio_ca/main.go:32 (vetshadow)
security/integration/main.go:155::warning: declaration of "err" shadows declaration at security/integration/main.go:146 (vetshadow)
security/integration/main.go:167::warning: declaration of "err" shadows declaration at security/integration/main.go:146 (vetshadow)
security/integration/main.go:174::warning: declaration of "err" shadows declaration at security/integration/main.go:146 (vetshadow)
security/integration/utils/kubernetes.go:111::warning: declaration of "uuid" shadows declaration at security/integration/utils/kubernetes.go:26 (vetshadow)
security/integration/utils/kubernetes.go:146:2:warning: ineffectual assignment to pod (ineffassign)
security/pkg/platform/aws_test.go:168:20:warning: ineffectual assignment to err (ineffassign)
security/cmd/node_agent/na/nafactory.go:35:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/cmd/node_agent/na/nodeagent.go:44:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/cmd/node_agent/na/nodeagent.go:52:26:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:66:2:warning: don't use underscores in Go names; struct field org_root_cert should be orgRootCert (golint)
security/integration/main.go:67:2:warning: don't use underscores in Go names; struct field org_cert_chain should be orgCertChain (golint)
security/integration/main.go:146:2:warning: don't use underscores in Go names; var self_signed_ca_pod should be selfSignedCaPod (golint)
security/integration/main.go:158:9:warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
security/integration/main.go:169:9:warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
security/integration/main.go:177:9:warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
security/integration/main.go:192:2:warning: don't use underscores in Go names; var ca_pod should be caPod (golint)
security/integration/main.go:200:2:warning: don't use underscores in Go names; var ca_service should be caService (golint)
security/integration/main.go:207:2:warning: don't use underscores in Go names; var na_pod should be naPod (golint)
security/integration/main.go:215:2:warning: don't use underscores in Go names; var na_service should be naService (golint)
security/integration/main.go:231:9:warning: if block ends with a return statement, so drop this else and outdent its block (golint)
security/integration/main.go:269:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:288:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:302:6:warning: func readUri should be readURI (golint)
security/integration/main.go:318:2:warning: don't use underscores in Go names; var max_retry should be maxRetry (golint)
security/integration/main.go:321:2:warning: don't use underscores in Go names; var org_root_cert should be orgRootCert (golint)
security/integration/main.go:323:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:326:2:warning: don't use underscores in Go names; var org_cert_chain should be orgCertChain (golint)
security/integration/main.go:328:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:351:22:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/main.go:387:20:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
security/integration/utils/kubernetes.go:32:1:warning: exported function CreateClientset should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:47:1:warning: exported function CreateTestNamespace should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:63:1:warning: exported function DeleteTestNamespace should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:71:1:warning: exported function CreateService should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:106:1:warning: exported function DeleteService should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:110:1:warning: exported function CreatePod should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:158:1:warning: exported function DeletePod should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:162:1:warning: exported function CreateRole should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:190:1:warning: exported function CreateRoleBinding should have comment or be unexported (golint)
security/integration/utils/kubernetes.go:275:1:warning: exported function WaitForSecretExist should have comment or be unexported (golint)
security/pkg/credential/token.go:45:1:warning: comment on exported method GcpTokenFetcher.FetchServiceAccount should be of the form "FetchServiceAccount ..." (golint)
security/pkg/server/grpc/authorizer.go:27:6:warning: type sameIdAuthorizer should be sameIDAuthorizer (golint)
security/pkg/server/grpc/authorizer.go:44:22:warning: error strings should not be capitalized or end with punctuation or a newline (golint)

**Release note**:

```Fix linter errors.
```

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
This PR addressed the same issue as #1841, and #1841 is closed due to incorrect set up of my github repository. Please take a look and apologize for the inconvenience.

File: security/integration/main.go [hunk 1]
```diff
@@ -73,185 +73,182 @@ func init() {
...
 
 	cmd.InitializeFlags(rootCmd)
 }
 
 func main() {
 	// HACKHACK: let `flag.Parsed()` return true to prevent glog from emitting errors
 	flag.CommandLine = flag.NewFlagSet("", flag.ContinueOnError)
-	if err := flag.CommandLine.Parse([]string{}); err != nil {
-		glog.Fatal(err)
+	if errors := flag.CommandLine.Parse([]string{}); errors != nil {
```
Comment (lookuptable) [inline security/integration/main.go]: What's reason for renaming `err` to `errors`? I believe `err` is more widely used.

File: security/pkg/platform/aws_test.go [hunk 2]
```diff
@@ -165,7 +165,7 @@ func TestAwsGetServiceIdentity(t *testing.T) {
 			client: ec2metadata.New(unit.Session, &aws.Config{Endpoint: aws.String(server.URL + "/latest")}),
 		}
 
-		serviceIdentity, err := awsc.GetServiceIdentity()
+		serviceIdentity, _ := awsc.GetServiceIdentity()
```
Comment (lookuptable) [inline security/pkg/platform/aws_test.go]: Doesn't this frustrate the linter since returned error is unchecked?

Comment (myidpt) [reply security/pkg/platform/aws_test.go]: Can you check this error?

Comment (JimmyCYJ) [reply security/pkg/platform/aws_test.go]: Thanks for pointing that out. Added a check for this error.

File: security/integration/main.go (hunk 1 above)
Comment (wattli) [reply security/integration/main.go]: +1, errors is not accurate, it should be error, but since error can stand for a lib, usually people use err for golang.

Comment (JimmyCYJ) [reply security/integration/main.go]: Thanks for the comments. I have changed errors back to err. 
Linter complains that at line 167 and line 173, declaration of "err" shadows declaration at security/integration/main.go:146 (vetshadow), so I rename these two err to delErr and creErr respectively.

Comment (wattli) [reply security/integration/main.go]: It's because you are trying to declare an already existed var. 

For declaration, you should use
err := ***

And after the err is declared,  you should use

err = *** (no ':' any more)
