### PR TITLE
istioctl manifest and profile enhancements

### LINKED ISSUE #21015: Istioctl does not accept istioControlPlane configuration via STDIN
**Bug description**

When attempting to provide an `IstioControlPlane` configuration to `istioctl manifest apply -f -`, Istioctl fails to recognize the configuration _file_ being presented to it.

**Expected behavior**

Istioctl should accept the STDIN as configuration if it has valid syntax.

**Steps to reproduce the bug**

1) Define an `istioControlPlane` configuration and `cat` & `|` it into Istioctl. 
2) Istioctl produces an error message:

```
$> cat ~/Desktop/example.yml | envsubst | istioctl manifest apply -f -
Failed to generate and apply manifests, error: failed to generate manifest: could not read values from file -: open -: no such file or directory
```

If  you change the operator from `-f -` to `-f <()`, Istioctl doesn't complain. However, it DOES simply ignore the configuration entirely and just deploys the Default profile.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

*Istio:* 1.4.3
*Kubernetes:* 1.17.0

**How was Istio installed?**

I used the scary recommended method of piping the internet into my shell. 

**Environment where bug was observed (cloud vendor, OS, etc)**

Local `kubeadm` based cluster.

### PR DESCRIPTION
**Pull request by ayj**
This PR includes several UX enhancements for the istioctl manifest and profile subcommands:

* `istioctl profile dump` prints a valid IstioOperator CR by default when the `--config-path` option is not used. The output can now be directly applied by istioctl.

* `istioctl profile dump` now accepts an optional `-o|--output` argument. This can be combined with `jq` as an alternative to `--config-path`, e.g. `istioctl profile dump default -s -o json | jq .spec.component.pilot`

fixes https://github.com/istio/istio/issues/21015

### CODE REVIEW

**Review by elfinhe — COMMENTED** [review]
LGTM, thanks Jason

File: operator/cmd/mesh/profile-common.go [hunk 1]
```diff
@@ -47,8 +47,16 @@ var scope = log.RegisterScope("installer", "installer", 0)
...
 // Otherwise it will be the compiled in profile YAMLs.
 // In step 3, the remaining fields in the same user overlay are applied on the resulting profile base.
+
 // The force flag causes validation errors not to abort but only emit log/console warnings.
-func GenerateConfig(inFilenames []string, setOverlayYAML string, force bool, kubeConfig *rest.Config, l *Logger) (string, *v1alpha1.IstioOperatorSpec, error) {
+func GenerateConfig(
+	inFilenames []string,
+	setOverlayYAML string,
+	force bool,
+	includeDefaults bool,
```
Comment (ostromart) [inline operator/cmd/mesh/profile-common.go]: this function had gotten into a pretty bad state due to doing too many things and after doing a cleanup recently i'd rather avoid this sort of bolt-on functionality because the main function is already hard to understand without these special addons. 
since the display of the derived profile without inherited values is basically just outputting the profile overlay file, could it be implemented that way rather than overloading GenerateConfig?

File: operator/cmd/mesh/profile-dump.go [hunk 2]
```diff
@@ -68,17 +91,55 @@ func profileDump(args []string, rootArgs *rootArgs, pdArgs *profileDumpArgs, l *
...
 		return err
 	}
 
-	l.print(y + "\n")
+	if pdArgs.configPath == "" {
+		metaHeader := `apiVersion: install.istio.io/v1alpha2
+kind: IstioControlPlane
+spec:`
+		// indent spec by two space and prepend the k8s metadata header
+		indentedSpec := strings.ReplaceAll("\n"+y, "\n", "\n  ")
```
Comment (ostromart) [inline operator/cmd/mesh/profile-dump.go]: suggest using tpath.AddSpecRoot since performance is not critical. also would be good to farm this and the jsonoutput logic out to helper function to limit the length of the function and help readability.

Comment (ayj) [reply operator/cmd/mesh/profile-dump.go]: ack

File: operator/cmd/mesh/profile-common.go (hunk 1 above)
Comment (ayj) [reply operator/cmd/mesh/profile-common.go]: The output should also include any overrides from the command line via `--set`. This is useful to generate new ICP as a delta from a base profile which can then be committed back to SCM.

I think this would be missed if we simplify output the profile overlay file? What is the right place to add this logic to get that desired behavior?

**Comment by esnible** [comment]
The discussion calls the new flag `show-inherited` but the code refers to the flag `hide-inherited`?

**Comment by ayj** [comment]
> The discussion calls the new flag show-inherited but the code refers to the flag hide-inherited?

Oops, I forgot to update the PR description to match the flag inversion - thanks!

**Review by esnible — APPROVED** [review]

File: operator/cmd/mesh/profile-common.go (hunk 1 above)
Comment (ayj) [reply operator/cmd/mesh/profile-common.go]: I removed the changes to show the profile w/o defaults (profile overlay) from this PR. PTAL.

**Review by ostromart — APPROVED** [review]
Thanks Jason!
