### PR TITLE
Fix data race 

### LINKED ISSUE #16737: WorkloadLabels race
```
==================
WARNING: DATA RACE
Read at 0x00c0011123a0 by goroutine 807:
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarOutboundHTTPRouteConfig()
      /home/prow/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/httproute.go:162 +0x6d4
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildHTTPRoutes()
      /home/prow/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/httproute.go:48 +0x14a
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawRoutes()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:59 +0x23a
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushRoute()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:30 +0x6a
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:374 +0x33df
  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      /home/prow/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.6/envoy/service/discovery/v2/ads.pb.go:195 +0xcd
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1199 +0x1535
  google.golang.org/grpc.(*Server).handleStream()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1279 +0x12e5
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xac

Previous write at 0x00c0011123a0 by goroutine 606:
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).WorkloadUpdate()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:469 +0x40f
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestLDSWithWorkloadLabelUpdate.func1()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/mem.go:111 +0x530
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Goroutine 807 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xb8
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/internal/transport/http2_server.go:429 +0x1705
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/internal/transport/http2_server.go:470 +0x3b2
  google.golang.org/grpc.(*Server).serveStreams()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:706 +0x170
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      /home/prow/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:668 +0x4c

Goroutine 606 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x65a
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestLDSWithWorkloadLabelUpdate()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds_test.go:551 +0x331
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
```

From https://prow.k8s.io/view/gcs/istio-prow/logs/istio-racetest-master/4590

Seems broken by https://github.com/istio/istio/pull/16501

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fixes #16737

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 1]
```diff
@@ -444,6 +455,10 @@ func (s *DiscoveryServer) StreamAggregatedResources(stream ads.AggregatedDiscove
 			} else {
 				con.mu.Unlock()
 			}
+		case updateEv := <-con.updateChannel:
+			if updateEv.workloadLabel && con.modelNode != nil {
+				con.modelNode.WorkloadLabels = nil
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/ads.go]: setting to nil so it gets updated later seems kind of hacky, can we properly update it here?

File: pilot/pkg/proxy/envoy/v2/eds.go [hunk 2]
```diff
@@ -464,9 +464,13 @@ func (s *DiscoveryServer) WorkloadUpdate(shard, id string, workloadLabels map[st
 	adsClientsMutex.RLock()
 	for _, connection := range adsClients {
 		// update node label
-		if connection.modelNode.IPAddresses[0] == id {
-			// set to nil, trigger re-set in SetWorkloadLabels
-			connection.modelNode.WorkloadLabels = nil
+		if connection.modelNode.IPAddresses[0] == ip {
+			select {
+			// trigger re-set in SetWorkloadLabels
+			case connection.updateChannel <- &UpdateEvent{workloadLabel: true}:
```
Comment (howardjohn) [inline pilot/pkg/proxy/envoy/v2/eds.go]: why not block here? we may miss updated this way

File: pilot/pkg/proxy/envoy/v2/ads.go (hunk 1 above)
Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/ads.go]: make sense

File: pilot/pkg/proxy/envoy/v2/eds.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pilot/pkg/proxy/envoy/v2/eds.go]: the channel is buffered with capacity 1, if this blocks, there is already labels updates un-processed.

Comment (howardjohn) [reply pilot/pkg/proxy/envoy/v2/eds.go]: hm I guess so. if we extend this updateChannel with future update types we need to be careful though, but I think it's fine for now

File: pilot/pkg/proxy/envoy/v2/ads.go [hunk 3]
```diff
@@ -444,6 +455,10 @@ func (s *DiscoveryServer) StreamAggregatedResources(stream ads.AggregatedDiscove
 			} else {
 				con.mu.Unlock()
 			}
+		case updateEv := <-con.updateChannel:
+			if updateEv.workloadLabel && con.modelNode != nil {
+				con.modelNode.SetWorkloadLabels(s.Env, true)
```
Comment (golangcibot) [inline pilot/pkg/proxy/envoy/v2/ads.go]: Error return value of `con.modelNode.SetWorkloadLabels` is not checked (from `errcheck`)

**Comment by hzxuzhonghu** [comment]
I am working on removing it. Should be ok tomorrow.
/retest
