### PR TITLE
dynamically set Lease Duration for operator

### LINKED ISSUE #27509: Managed Istio: Manager exited non-zero
Hi team! We have the managed istio on multiple IKS clusters.
We are using the latest 1.7.2 version and sporadically on some clusters we can see logs as the following:
```
2020-09-24T13:23:12.697712Z	error	error retrieving resource lock ibm-operators/istio-operator-lock: Get "https://172.21.0.1:443/api/v1/namespaces/ibm-operators/configmaps/istio-operator-lock": context deadline exceeded
2020-09-24T13:23:12.697802Z	info	failed to renew lease ibm-operators/istio-operator-lock: timed out waiting for the condition
2020-09-24T13:23:12.697865Z	fatal	Manager exited non-zero: leader election lost
```

and as:
```
    Sep 24 15:23:13kube-brq9cjpd05d8tb2l7bfg-ghostfordoc-default-00000115syslogE0924 13:23:13.260809    6966 pod_workers.go:191] Error syncing pod bd4d62ea-e38d-4e67-98c0-48b339f06337 ("managed-istio-operator-88cc547b4-8p9x4_ibm-operators(bd4d62ea-e38d-4e67-98c0-48b339f06337)"), skipping: failed to "StartContainer" for "istio-operator" with CrashLoopBackOff: "back-off 10s restarting failed container=istio-operator pod=managed-istio-operator-88cc547b4-8p9x4_ibm-operators(bd4d62ea-e38d-4e67-98c0-48b339f06337)"

    Sep 24 15:23:13kube-brq9cjpd05d8tb2l7bfg-ghostfordoc-default-00000115kubelet.logE0924 13:23:13.260809    6966 pod_workers.go:191] Error syncing pod bd4d62ea-e38d-4e67-98c0-48b339f06337 ("managed-istio-operator-88cc547b4-8p9x4_ibm-operators(bd4d62ea-e38d-4e67-98c0-48b339f06337)"), skipping: failed to "StartContainer" for "istio-operator" with CrashLoopBackOff: "back-off 10s restarting failed container=istio-operator pod=managed-istio-operator-88cc547b4-8p9x4_ibm-operators(bd4d62ea-e38d-4e67-98c0-48b339f06337)"
```

This seems to appear only some days and everything seems to be fine (the system works as usually). 

The `istioctl analyze -n namespace` doesn't show any problem.
The `istioctl version` shows that every proxy is updated to latest 1.7.2 version.

Any ideas? Are there action that we can take to avoid those crash?

If required, I can attach some extra logs.

### PR DESCRIPTION
**Pull request by GregHanson**
The RENEW_DEADLINE is configuable but the leaseDuration limits the renewDeadline.

If RENEW_DEADLINE is set to 30s, the following error occurs when the operator pod tries to start.

```
2021-04-09T18:45:44.565506Z	info	installer	Controller added
2021-04-09T18:45:44.565541Z	info	Starting the Cmd.
2021-04-09T18:45:44.565767Z	fatal	Manager exited non-zero: leaseDuration must be greater than renewDeadline
```

It seems like the leaseDuration defaults to 15s

resolves: https://github.com/istio/istio/issues/27509

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

File: operator/cmd/operator/server.go [hunk 1]
```diff
@@ -117,7 +133,10 @@ func run() {
 		log.Warn("Leader election namespace not set. Leader election is disabled. NOT APPROPRIATE FOR PRODUCTION USE!")
 	}
 
+	// TODO renewDeadline cannot be greater than leaseDuration
 	renewDeadline := getRenewDeadline()
+	leaseDuration := getLeaseDuration()
```
Comment (howardjohn) [inline operator/cmd/operator/server.go:138]: Does it make sense to make it relative to renewDeadline? like half or 2x or something?

File: releasenotes/notes/27509-lease-duration.yaml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+apiVersion: release-notes/v2
+kind: bug-fix
+area: installation
+issue:
+  - 27509
+releaseNotes:
+  - |
+    **Fixed** allow custom configuration of LEASE_DURATION for istio operator manager.
```
Comment (shamsher31) [inline releasenotes/notes/27509-lease-duration.yaml:8]:
```suggestion
    **Fixed** allow custom configuration of `LEASE_DURATION` for Istio operator manager.
```

File: operator/cmd/operator/server.go [hunk 3]
```diff
@@ -106,6 +106,22 @@ func getRenewDeadline() *time.Duration {
...
+func getLeaseDuration() *time.Duration {
+	ddl, found := os.LookupEnv("LEASE_DURATION")
+	// default duration in controller-runtime package
+	df := time.Second * 15
+	if !found {
+		return &df
+	}
+	duration, err := time.ParseDuration(ddl)
+	if err != nil {
+		log.Errorf("failed to parse leaseDuration: %v, use default value", err)
```
Comment (shamsher31) [inline operator/cmd/operator/server.go:119]:
```suggestion
		log.Errorf("failed to parse LEASE_DURATION: %v, using default value: %v", err, &df)
```

File: operator/cmd/operator/server.go (hunk 1 above)
Comment (GregHanson) [reply operator/cmd/operator/server.go:138]: Open to suggestions.  Currently the dependent go package causes the operator to fail to start which is no good.  
1. No `LEASE_DURATION` configuration option exposed and lease duration is just always set 2x larger than renew deadline
2. Expose `LEASE_DURATION` configuration option but log a `WARN` when renew deadline is larger than lease duration and instead revert `RENEW_DEADLINE` back to default 10s value
3. something else

Comment (William-Newshutz) [reply operator/cmd/operator/server.go:138]: From what I understand the ratio of LEASE_DURATION to RENEW_DEADLINE depends on how much you want to tolerate clock skew rate https://pkg.go.dev/k8s.io/client-go/tools/leaderelection

Having Lease Duration default to a set ratio (especially 2x) leverages the upstream knowledge of how much skew rate the operator needs to tolerate.

Having Lease Duration configurable relies on the user knowledge of how much skew rate the operator needs to tolerate.

I think either option 1 or 2 are solid picks. I lean towards option 1 since 2x tolerance is a solid margin already.

Comment (GregHanson) [reply operator/cmd/operator/server.go:138]: defaults in the dependent go library are 10s and 15s, so I will go with option 1 and use a factor of 1.5x to remain what exists currently.  Fewer configurable environment variables sounds like the way to go

File: operator/cmd/operator/server.go (hunk 3 above)
Comment (GregHanson) [reply operator/cmd/operator/server.go]: removed method

File: releasenotes/notes/27509-lease-duration.yaml (hunk 2 above)
Comment (GregHanson) [reply releasenotes/notes/27509-lease-duration.yaml]: PTAL at latest

**Review by richardwxn — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]
