### PR TITLE
Fix to enable choice of TLS parameters within Envoy Filters

### LINKED ISSUE #28996: TLS parameters cannot be configured with EnvoyFilter
**Bug description**
We are unable to configure TLS parameters (to control the TLS version, or set TLS ciphersuites, curves etc.) using an Envoy Filter.
Specifically, we would like to force the use of TLSv1_3 and of the CECPQ2 curve, a Post-Quantum key exchange available in BoringSSL, which works fine in stand-alone Envoy.
For that, we wrote a configuration patch in an EnvoyFilter. It should be sufficient to then apply it, but the behaviour of the function used to merge the configurations: `proto.merge`, is not correct. The resulting configuration is broken and essentially ignores the patch.

**What we observed**: 
Instead of merging our config with the main one:
For the clusters: it adds it after as a new item and is not taken into account.
For the listeners: it erases part of the main config, where the merge should have been done.
(Checked using `$ istioctl proxy-config cluster/listener`).

We wrote a fix and tested it, both for cluster and listener’s patch in the EnvoyFilter handling Go code.

We would like to open a PR after some community discussion.

Our fix can be used to configure any TLS parameters, and can be duplicated to be used for other configurations.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**
We have 2 services, Service1 and Service2, deployed with sidecars. Service1 sends a simple http get request to Service2. The request goes to (the egress port of) the sidecar of Service1, which initiates a TLS connection to (the ingress port of) the sidecar of Service2. We want this TLS connection to be TLS1.3 with curve CECPQ2.

Service1 ---(http)--> SidecarOfService1 ---(https)--> SidecarOfService2 ---(http)--> Service2  

The communication, as described above, is established between one sidecar to the other one with:
`$ kubectl exec -it <pod name of service1> -c service1 -- curl -v http://service2.default:8050/myservice/2`

Our EnvoyFilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-protocol
  namespace: default
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.transport_sockets.tls"
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_params:
                tls_maximum_protocol_version: TLSv1_3
                tls_minimum_protocol_version: TLSv1_3
                ecdh_curves:
                - "CECPQ2"
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_params:
                tls_maximum_protocol_version: TLSv1_3
                tls_minimum_protocol_version: TLSv1_3
                ecdh_curves:
                - "CECPQ2"
```

**Version**
Output of `istioctl version --remote`
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (4 proxies)

Output of `kubectl version --short`
Client Version: v1.18.6
Server Version: v1.17.5

**Related issues**
#13138 (and PR #27500) allows to set a baseline TLS configuration for the entire Mesh. With our fix, the user can be very flexible on the choice of the TLS parameters, including the TLS version, the cipher suites, the curves. In addition, these parameters can be applied to a smaller scope, like specific proxies. As one example, this will allow people to require TLS 1.3 to be used everywhere, for compliance reasons

#18169 #24330
Same root cause as us: the function proto.merge

### PR DESCRIPTION
**Pull request by laek3**
Fixes #28996

We would like to be able to configure any TLS parameters (TLS version, TLS ciphersuites, curves etc.) using Envoy Filters.
Specifically, we would like to be Post-Quantum secure, i.e. use TLSv1_3 and CECPQ2 curve, a Post-Quantum key exchange available in BoringSSL. It already works fine in stand-alone Envoy.
We encountered a bug when applying our EnvoyFilter: the behaviour of the function used to merge the configurations, proto.merge, is not correct. The resulting configuration is broken and essentially ignores the patch.

Instead of merging our config with the main one:
For the clusters: it is not able to match the main TransportSocket configuration with ours, so it adds it after as a new item and is not taken into account.
For the listeners: it erases part of the main config, where the merge should have been done, and results in a failure.
(Checked using $ istioctl proxy-config cluster/listener).

We propose the following fix, for clusters' and listeners' patches. It allows the merge of a deep configuration for TransportSockets. We added tests that are passing with our fix, and are not passing without it. It explicitly demonstrates the problem we encountered. The fix won't affect the users, it only affect the use of EnvoyFilter when a patch needs to be merged.

Our fix can be used to configure any TLS parameters, and can be duplicated to be used for other deep configurations that are failing.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by laek3** [comment]
@googlebot I signed it!

**Review by ramaraochavali — CHANGES_REQUESTED** [review]
I am not very comfortable making this specific structure based matches using conditions like `isTransportSocketPatch` and `isTlsConfig` - It will be error prone and will be hard to maintain.

@howardjohn  @hzxuzhonghu  What do you think?

**Comment by howardjohn** [comment]
I agree with Rama.

**Comment by hzxuzhonghu** [comment]
Yeah, this is really hacky

**Comment by laek3** [comment]
Can you advise me on a less hacky way to make it work?

**Comment by laek3** [comment]
I understand your comments. It was the only solution found since the function proto.merge cannot handle this structure, and we wanted to keep the flexibility of the envoy filters (regarding the TLS parameters, which connections to apply it to etc.)

Would it be a better solution to follow what was done on the PR #27500 and have a Post-Quantum flag with the version and the key exchange wanted?
Do you have other suggestions?

**Comment by ramaraochavali** [comment]
If you define them with flags, it is not possible to apply those settings per connection etc as mentioned by you

 "we wanted to keep the flexibility of the envoy filters (regarding the TLS parameters, which connections to apply it to etc.)". 

What exactly do you want to configure? Is it minTLSVersion as TLSV1_3 and ecdh_curves to X25519?

**Comment by laek3** [comment]
Yes, the fix was written to allow other users to use it with their own tls/clusters/... parameters.
In our case, we can work in a more strict environment if this is the only solution.
Our parameters are : tls_minimum_protocol_version: TLSv1_3, ecdh_curves: CECPQ2

**Comment by laek3** [comment]
But again, we would ideally like to work in an environment as flexible as possible, so with Envoy Filters. It would allow us to better supervise our tests, control which connections get which configuration (e.g. incremental deployment), and handle interoperability problems.

**Comment by laek3** [comment]
Reopen

**Comment by howardjohn** [comment]
not stale

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go [hunk 1]
```diff
@@ -39,12 +40,66 @@ func ApplyClusterMerge(pctx networking.EnvoyFilter_PatchContext, efw *model.Envo
...
+			}
 		}
 	}
 	return c
 }
 
+// Test if the patch contains a config for TransportSocket
+func mergeTransportSocketCluster(c *cluster.Cluster, cp *model.EnvoyFilterConfigPatchWrapper) (bool, error) {
+
+	err := fmt.Errorf("ERROR function mergeTransportSocketCluster failed.")
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:59]: We should not have a generic error message here, usually we add context at each relevant point. Also do not prefix with ERROR

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go [hunk 2]
```diff
@@ -39,12 +40,66 @@ func ApplyClusterMerge(pctx networking.EnvoyFilter_PatchContext, efw *model.Envo
...
+
+	cpValueCast, okCpCast := (cp.Value).(*cluster.Cluster)
+	if !okCpCast {
+		log.Errorf("ERROR Cast of cp.Value: %v", okCpCast)
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:63]: I think we avoid logging in this code as it is called 1000s of times and can overload logs.

Also, I don't think this can actually happen

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go [hunk 3]
```diff
@@ -39,12 +40,66 @@ func ApplyClusterMerge(pctx networking.EnvoyFilter_PatchContext, efw *model.Envo
...
+		return false, err
+	}
+
+	var tsmPatch *cluster.Cluster_TransportSocketMatch
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:67]: We will generate config that uses TransportSocketMatch normally, but technically it can still also be in TransportSocket (if auto mtls is enabled). So we may need to handle that case as well

**Review by howardjohn — COMMENTED** [review]
So I think based on our conversations, our options are:

1. This PR
2. Add TRANSPORT_SOCKET native type to https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo
3. Make generic proto.merge fork that does deep Any merging
4. Create a specialized API just for TLS parameter

We will discuss in the next networking WG meeting

**Comment by PiotrSikora** [comment]
> So I think based on our conversations, our options are:
> 
> 1. This PR
> 2. Add TRANSPORT_SOCKET native type to https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo
> 3. Make generic proto.merge fork that does deep Any merging
> 4. Create a specialized API just for TLS parameter
> 
> We will discuss in the next networking WG meeting

Please expose those features via Istio API ([we already do that for Gateways](https://istio.io/latest/docs/reference/config/networking/gateway/)), we should be moving away from EnvoyFilters as much as possible, especially for such generic features.

**Comment by howardjohn** [comment]
not stale

File: pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go [hunk 4]
```diff
@@ -39,12 +42,71 @@ func ApplyClusterMerge(pctx networking.EnvoyFilter_PatchContext, efw *model.Envo
...
+		// Merge the patch and the cluster at a lower level
+		dstCluster := tsmPatch.GetTypedConfig()
+		srcPatch := cpValueCast.GetTransportSocket().GetTypedConfig()
+
+		if dstCluster != nil && srcPatch != nil {
+
+			retVal, errMerge := util.MergeAnyWithAny(dstCluster, srcPatch)
+			if errMerge != nil {
+				err = fmt.Errorf("function MergeAnyWithAny failed for ApplyClusterMerge: %v", errMerge)
+				return false, err
```
Comment (howardjohn) [inline pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:97]: nit: just do `return false, fmt.Errorf("function MergeAnyWithAny failed for ApplyClusterMerge: %v", errMerge)`

**Review by howardjohn — APPROVED** [review]

**Review by ramaraochavali — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@laek3 could you fix the linter warnings and run `make gen`? Thanks!
