### PR TITLE
fix: istioctl remove all revisions of istio operator when not specify revision

### LINKED ISSUE #45242: `istioctl operator remove` will remove all revision when not specify revison
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`istioctl operator remove`  and `istioctl operator remove -r default` will remove all revision of operator, like:

```
$ istioctl operator remove --dry-run
All revisions of Istio operator will be removed from cluster, Proceed? (y/N) y
Removing Istio operator...
Not pruning object Deployment:istio-operator:istio-operator because of dry run.
Not pruning object Deployment:istio-operator:istio-operator-v1 because of dry run.
Not pruning object Deployment:istio-operator:istio-operator-v2 because of dry run.
Not pruning object Service:istio-operator:istio-operator because of dry run.
Not pruning object Service:istio-operator:istio-operator-v1 because of dry run.
Not pruning object Service:istio-operator:istio-operator-v2 because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator-v1 because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator-v2 because of dry run.
Not pruning object ClusterRole::istio-operator because of dry run.
Not pruning object ClusterRole::istio-operator-v1 because of dry run.
Not pruning object ClusterRole::istio-operator-v2 because of dry run.
Not pruning object ClusterRoleBinding::istio-operator because of dry run.
Not pruning object ClusterRoleBinding::istio-operator-v1 because of dry run.
Not pruning object ClusterRoleBinding::istio-operator-v2 because of dry run.
✔ Removal complete
$
$
$
$ istioctl operator remove --dry-run -r default
All revisions of Istio operator will be removed from cluster, Proceed? (y/N) y
Removing Istio operator...
Not pruning object Deployment:istio-operator:istio-operator because of dry run.
Not pruning object Deployment:istio-operator:istio-operator-v1 because of dry run.
Not pruning object Deployment:istio-operator:istio-operator-v2 because of dry run.
Not pruning object Service:istio-operator:istio-operator because of dry run.
Not pruning object Service:istio-operator:istio-operator-v1 because of dry run.
Not pruning object Service:istio-operator:istio-operator-v2 because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator-v1 because of dry run.
Not pruning object ServiceAccount:istio-operator:istio-operator-v2 because of dry run.
Not pruning object ClusterRole::istio-operator because of dry run.
Not pruning object ClusterRole::istio-operator-v1 because of dry run.
Not pruning object ClusterRole::istio-operator-v2 because of dry run.
Not pruning object ClusterRoleBinding::istio-operator because of dry run.
Not pruning object ClusterRoleBinding::istio-operator-v1 because of dry run.
Not pruning object Cl
```

**What do we expect**: only remove default revision istio operator.

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (8 proxies)
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by my-git9**
*Please provide a description of this PR:**

Fix  istioctl operator remove and istioctl operator remove -r default will remove all revision of operator.

Fix https://github.com/istio/istio/issues/45242

### CODE REVIEW

**Comment by my-git9** [comment]
The test result:

image

**Review by zirain — CHANGES_REQUESTED** [review]
please add e2e test for this

File: operator/cmd/mesh/operator-common.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ const (
 // isControllerInstalled reports whether an operator deployment exists in the given namespace.
 func isControllerInstalled(cs kubernetes.Interface, operatorNamespace string, revision string) (bool, error) {
 	orn := operatorResourceName
-	if revision != "" {
+	if revision != "" && revision != "default" {
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-common.go:58]: How it can be `default`? I thought we explicitly set `default` to `` in all of these kind of commands.

File: operator/cmd/mesh/operator-remove.go [hunk 2]
```diff
@@ -78,13 +78,17 @@ func operatorRemove(cmd *cobra.Command, args *RootArgs, orArgs *operatorRemoveAr
...
 	// If the user is performing purge but also specified a revision, an error message
 	// should be displayed and do nothing
-	if orArgs.purge && orArgs.revision != "" {
+	case orArgs.purge && orArgs.revision != "":
 		orArgs.revision = ""
 		l.LogAndFatal("At most one of the --revision or --purge flags could be set\n")
-	} else if orArgs.revision == "default" {
+	case orArgs.purge:
 		orArgs.revision = ""
+	case orArgs.revision == "":
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-remove.go:89]: This is not correct, In other commands, we only set `default` to empty, why here set empty to `default`? This may cause some errors since the component may become something like `istiod-default` instead of `istiod`

Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:89]: This is where it needs to work with the place commented above:

```
func isControllerInstalled(cs kubernetes.Interface, operatorNamespace string, revision string) (bool, error) {
	orn := operatorResourceName
	if revision != "" && revision != "default" {
```

File: operator/cmd/mesh/operator-common.go (hunk 1 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-common.go:58]: If `orArgs.revision == ""` https://github.com/istio/istio/blob/master/operator/cmd/mesh/operator-remove.go#L87,
all revision will be hit.

File: operator/cmd/mesh/operator-remove.go [hunk 3]
```diff
@@ -78,13 +78,17 @@ func operatorRemove(cmd *cobra.Command, args *RootArgs, orArgs *operatorRemoveAr
 		l.LogAndFatal(err)
 	}
 
+	switch {
 	// If the user is performing purge but also specified a revision, an error message
 	// should be displayed and do nothing
-	if orArgs.purge && orArgs.revision != "" {
+	case orArgs.purge && orArgs.revision != "":
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-remove.go:84]: I think `purge` takes precedence, regardless of the specified revision. We don't care about/set revision if the operation is a `purge`.

There may be a situation where a user specifies both 'purge' and a 'revision'. In such cases, we may need to warn the user that all revisions will still be purged even if they specify the revision.

File: operator/cmd/mesh/operator-common.go (hunk 1 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-common.go:58]: When no revision is specified we want only the `default` revision in `istioctl operator remove`, so special handling of default revision is required here.

File: operator/cmd/mesh/operator-remove.go (hunk 3 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:84]: I did not modify the logic here, this is because of the previous discussion: https://github.com/istio/istio/pull/41548#discussion_r1009826463

File: operator/cmd/mesh/operator-common.go (hunk 1 above)
Comment (hanxiaop) [reply operator/cmd/mesh/operator-common.go:58]: The default revision should be the same as non-revision, so we only need to handle `if revision != ""`. I think the original logic is slightly flawed. We should not tie 'purge' and 'revision' together. Instead, we only need to warn users that all revisions will be purged if they specify both flags, rather than disallowing them from setting the flags. This should be similar to the 'uninstall purge' scenario.

File: operator/cmd/mesh/operator-remove.go (hunk 3 above)
Comment (hanxiaop) [reply operator/cmd/mesh/operator-remove.go:84]: I see. I think it's fine to provide a warning instead of error, since we still have the confirmation before the actual removal, and users will see that they gonna purge everything. This is more consistent to the uninstall command. @zirain Do you have any ideas?

File: operator/cmd/mesh/operator-common.go (hunk 1 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-common.go:58]: If default is not processed here, according to the previous processing, the final deployment name to be processed will be `istio-operator-default`.
And if the previous processing sets the default revisions to "", then all revisions will be hit, it's not we expect.

Comment (hanxiaop) [reply operator/cmd/mesh/operator-common.go:58]: I think the expected behavior is: when we init, no matter `init` or `init --revision default`, it should all be `istio-operator`

Comment (my-git9) [reply operator/cmd/mesh/operator-common.go:58]: Yes, but when deleting now, if you don’t know the revision or revision == `default`, all revisions will be cleaned up:https://github.com/istio/istio/issues/45242#issue-1736615170

File: tests/integration/operator/switch_cr_test.go [hunk 4]
```diff
@@ -123,7 +123,36 @@ func TestController(t *testing.T) {
 			cleanupInClusterCRs(t, cs)
 
 			// test operator remove command
-			scopes.Framework.Infof("checking operator remove command")
+			scopes.Framework.Infof("checking operator remove command for default revision")
```
Comment (zirain) [inline tests/integration/operator/switch_cr_test.go:126]: I don't think this's the right place, you should create a new test case.

File: operator/cmd/mesh/operator-remove.go (hunk 3 above)
Comment (zirain) [reply operator/cmd/mesh/operator-remove.go:84]: we should keep same with `istioctl uninstall`

File: tests/integration/operator/switch_cr_test.go (hunk 4 above)
Comment (my-git9) [reply tests/integration/operator/switch_cr_test.go:126]: OK, I will modify it later

File: operator/cmd/mesh/operator-remove.go (hunk 3 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:84]: OK

File: operator/cmd/mesh/operator-remove.go [hunk 5]
```diff
@@ -78,13 +78,17 @@ func operatorRemove(cmd *cobra.Command, args *RootArgs, orArgs *operatorRemoveAr
...
 		orArgs.revision = ""
-		l.LogAndFatal("At most one of the --revision or --purge flags could be set\n")
-	} else if orArgs.revision == "default" {
+		l.LogAndPrint("Purge remove will remove all Istio operator controller, ignoring the specified revision\n")
+	case orArgs.purge:
 		orArgs.revision = ""
+	case orArgs.revision == "":
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-remove.go:89]: I think we never set empty revision string to `default` in the code logic.

Comment (hanxiaop) [reply operator/cmd/mesh/operator-remove.go:89]: I've checked the old version, the `operator remove` behavior was if you were specifying a revision, the revision would be deleted, and if you were not specifying a revision, all revisions would be deleted.

I think `case orArgs.purge` is correct since it's gonna get all of the revisions, and do the deletion. However, I don't think `case orArgs.revision == ""` is reasonable. The better approach should be to just use the same logic as what `uninstall` does, if you are not specifying revision, it will throw an error `Error: at least one of the --revision (or --set revision=<revision>), --filename or --purge flags must be set`, then if we want to remove the default operator controller, we must do something like `operator remove -r default`, and you won't have this kind of post-processing logics.

Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:89]: Now these modifications are adjustments made without changing usage, and this logic was decided in this discussion: https://github.com/istio/istio/pull/41548#discussion_r1001892926

Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:89]: I followed the suggestion and updated the code, please review again, thanks

File: operator/cmd/mesh/operator-common.go (hunk 1 above)
Comment (hanxiaop) [inline operator/cmd/mesh/operator-common.go:58]: Can you do all these things in Args? I don't think this is the right layer to do the arg validation

File: operator/cmd/mesh/operator-common.go [hunk 6]
```diff
@@ -55,7 +55,7 @@ const (
 // isControllerInstalled reports whether an operator deployment exists in the given namespace.
 func isControllerInstalled(cs kubernetes.Interface, operatorNamespace string, revision string) (bool, error) {
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-common.go:56]: Also, this is not only used by `operator remove`, I'm not sure if doing it like this will change other commands' behaviors.

**Review by hanxiaop — CHANGES_REQUESTED** [review]
Blocking since I don't think this is a right layer to do the change. You need to pass the correct args to `RunE` instead of validating them in `RunE`.

File: operator/cmd/mesh/operator-remove.go [hunk 7]
```diff
@@ -78,16 +78,26 @@ func operatorRemove(cmd *cobra.Command, args *RootArgs, orArgs *operatorRemoveAr
...
+		l.LogAndFatal("At least one of the --revision or --purge flags must be set")
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-remove.go:90]: IMO this should not be the right layer to do the args validation in a cobra command, I think it's better to add these kind of thing to the `Args` part, and after successfully validate the args, the correct args can be passed into `RunE` and perform the rest operations.

File: operator/cmd/mesh/operator-remove.go [hunk 8]
```diff
@@ -78,16 +87,20 @@ func operatorRemove(cmd *cobra.Command, args *RootArgs, orArgs *operatorRemoveAr
...
 	if orArgs.purge && orArgs.revision != "" {
 		orArgs.revision = ""
-		l.LogAndFatal("At most one of the --revision or --purge flags could be set\n")
-	} else if orArgs.revision == "default" {
-		orArgs.revision = ""
+		l.LogAndPrint("Purge remove will remove all Istio operator controller, ignoring the specified revision\n")
+	}
+
+	var installed bool
+	if orArgs.revision == "default" {
```
Comment (hanxiaop) [inline operator/cmd/mesh/operator-remove.go:98]: nit: this if/else check seems to be redundant, I think we can set the revision to be `""` if it's `default` before passing `orArgs.revision` into `isControllerInstalled `, then we won't need this if/else check.
```go
if orArgs.revision == "default {
    orArgs.revision = ""
}
```

**Review by hanxiaop — COMMENTED** [review]
Nice, only one comment from me, otherwise LGTM

File: operator/cmd/mesh/operator-remove.go (hunk 8 above)
Comment (hanxiaop) [reply operator/cmd/mesh/operator-remove.go:98]: I see. NVM I think it's fine to leave it like this. Thanks for the contribution!

**Review by hanxiaop — APPROVED** [review]

File: operator/cmd/mesh/operator-remove.go (hunk 8 above)
Comment (my-git9) [reply operator/cmd/mesh/operator-remove.go:98]: Thank you for your long and serious review

**Comment by hanxiaop** [comment]
@zirain PTAL. Tests are added.

**Comment by my-git9** [comment]
@zirain Could you review again? Thanks

**Comment by my-git9** [comment]
This PR has been a long time ago, could you review it again? thanks @zirain

**Review by zirain — APPROVED** [review]

File: releasenotes/notes/45243.yaml [hunk 9]
```diff
@@ -0,0 +1,8 @@
+apiVersion: release-notes/v2
+kind: bug-fix
+area: istioctl
+issue:
+  - 45242
+releaseNotes:
+  - |
+    **Fixed** `istioctl operator remove` will remove all revisions of operator controller when not specify revision or the revision is "default".
```
Comment (ericvn) [inline releasenotes/notes/45243.yaml:8]:
```suggestion
    **Fixed** `istioctl operator remove` will remove all revisions of operator controller when the revision is "default" or not specified.
```

**Comment by my-git9** [comment]
@ericvn PTAL, thanks

**Review by ericvn — APPROVED** [review]
