### PR TITLE
Fix validatingwebhookconfiguration installation error

### LINKED ISSUE #45204: Cannot install istio from master
```
build complete
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                                                                                                                               Error: failed to process default webhook: failed to apply YAML: Apply failed with 1 conflict: conflict with "pilot-discovery" using admissionregistration.k8s.io/v1: .webhooks[name="validation.istio.io"].failurePolicy
```

8841329a39 seems to break it @hanxiaop

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/45204

### CODE REVIEW

File: operator/pkg/helmreconciler/reconciler.go [hunk 1]
```diff
@@ -660,7 +662,52 @@ func applyManifests(kubeClient kube.Client, manifests string) error {
...
 		}
 
-		_, err := kubeClient.Dynamic().Resource(ogvr).Namespace(obj.GetNamespace()).Patch(
+		// webhook failurePolicy is managed by istiod, so if currently we already have a webhook in cluster,
+		// we remove setting it from the manifest
+		webhooks, found, err := unstructured.NestedSlice(obj.Object, "webhooks")
+		if err != nil {
+			return fmt.Errorf("failed to get webhooks: %w", err)
+		}
+		if found && ogvr == gvr.ValidatingWebhookConfiguration {
```
Comment (howardjohn) [inline operator/pkg/helmreconciler/reconciler.go:671]: do we need to post-process this or can we just not include it in the webhook yaml?

Comment (howardjohn) [reply operator/pkg/helmreconciler/reconciler.go:671]: Oof, I thought the default was Ignore but it is Fail. So we cannot.

I am a bit concerned by this approach but don't see any obviously ideas...

TBH I wonder if we can just default to Fail now. The reason we didn't initially is we installed istio CRs during install. We don't anymore. But users may in their own pipelines...

@therealmitchconnors any ideas?

Comment (howardjohn) [reply operator/pkg/helmreconciler/reconciler.go:671]: So if we force we have a small possible missed validation. Not terrible (because it needs Istiod to be down as well to not work), but not great...

Comment (hanxiaop) [reply operator/pkg/helmreconciler/reconciler.go:671]: I don't think this approach is great enough, and I can't come up with any ideas either... IIRC, last time when I fixed the readinessProbe issue, users may have been sensitive to the validation downtime; force to `Fail` changes the installation behavior. I think if post-processing and force setting to `Fail` are both not very great, the simplest approach is to keep the original `Ignore` and let pilot revise it?

Comment (hanxiaop) [reply operator/pkg/helmreconciler/reconciler.go:671]: I kinda like the idea of directly setting it to `Fail`, since it's cleaner installation process and the legacy validation check can be removed. However, I'm not really sure how many users will be affected. Waiting for more ideas

Comment (howardjohn) [reply operator/pkg/helmreconciler/reconciler.go:671]: ok I think this approach may be fine but we shouldn't put the logic in `applyManifests` and should instead be in `ProcessDefaultWebhook`. 

This already fetches the webhook, so we don't need to do it again. It also fetches it in the typed form, so its much easier to process than all the casting. Its also a layering violation -- ideally `applyManifests` is agnostic to the inputs and just applies them

Comment (hanxiaop) [reply operator/pkg/helmreconciler/reconciler.go]: Thanks, this makes sense to me.

File: istioctl/pkg/tag/generate.go [hunk 2]
```diff
@@ -149,6 +151,29 @@ func Generate(ctx context.Context, client kube.Client, opts *GenerateOptions, is
 	return tagWhYAML, nil
 }
 
+func fixWhFailurePolicy(client kube.Client, vwc *admitv1.ValidatingWebhookConfiguration) (*admitv1.ValidatingWebhookConfiguration, error) {
+	var curWebhooks []admitv1.ValidatingWebhook
+	curObj, err := client.Kube().AdmissionregistrationV1().ValidatingWebhookConfigurations().
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:156]: We already get the webhook on L104, and we even have `fixWhConfig` on L140, can we reuse those?

File: istioctl/pkg/tag/generate.go [hunk 3]
```diff
@@ -149,6 +151,29 @@ func Generate(ctx context.Context, client kube.Client, opts *GenerateOptions, is
...
+		if !errors.IsNotFound(err) {
+			return nil, err
+		}
+	}
+	if curObj != nil {
+		curWebhooks = curObj.Webhooks
+	}
+	for i := range vwc.Webhooks {
+		if curWebhooks != nil && i < len(curWebhooks) {
+			failurePolicy := curWebhooks[i].FailurePolicy
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:168]: this seems suspicious. The indexes are probably the same but could not be. I think my comment about re-using the existing code probably makes it easier

File: istioctl/pkg/tag/generate.go [hunk 4]
```diff
@@ -149,6 +151,29 @@ func Generate(ctx context.Context, client kube.Client, opts *GenerateOptions, is
...
+			if *failurePolicy == admitv1.Fail {
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:169]: could be nil I think

**Review by howardjohn — COMMENTED** [review]
Looks much better! thanks for the improvements

File: istioctl/pkg/tag/generate.go (hunk 2 above)
Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:156]: The webhook on L104 is `MutatingWebhookConfiguration` and the one actually need to be fixed is `ValidatingWebhookConfiguration`, I think we still need to fetch the in-cluster VWC to do the comparision?

Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:156]: I think putting logics into the `fixWhConfig` is a great idea

File: istioctl/pkg/tag/generate.go [hunk 5]
```diff
@@ -149,15 +158,36 @@ func Generate(ctx context.Context, client kube.Client, opts *GenerateOptions, is
...
 		if err == nil {
 			webhookURL.Path = "/validate"
 			whConfig.URL = webhookURL.String()
 		}
 	}
-	return whConfig
+
+	// ValidatingWebhookConfiguration failurePolicy is managed by Istiod, so if currently we already have a webhook in cluster
+	// that is set to `Fail` by Istiod, we avoid of setting it back to the default `Ignore`.
+	vwh, err := client.Kube().AdmissionregistrationV1().ValidatingWebhookConfigurations().
```
Comment (howardjohn) [inline istioctl/pkg/tag/generate.go:172]: We do not need to fetch it, we already did on L110

**Review by howardjohn — COMMENTED** [review]
hm... even with this PR I still get errors.

```
Error: failed to process default webhook: failed to apply YAML: Apply failed with 5 conflicts: conflicts with "istio-kube-client" using admissionregistration.k8s.io/v1:
- .metadata.labels.install.operator.istio.io/owning-resource
- .webhooks[name="namespace.sidecar-injector.istio.io"].rules
- .webhooks[name="object.sidecar-injector.istio.io"].rules
- .webhooks[name="rev.namespace.sidecar-injector.istio.io"].rules
- .webhooks[name="rev.object.sidecar-injector.istio.io"].rules
```

I guess it is from different case

```yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"sidecar-injector","install.operator.istio.io/owning-resource":"unknown","istio.io/rev":"default","istio.io/tag":"default","operator.istio.io/component":"Pilot","release":"istio"},"name":"istio-revision-tag-default"},"webhooks":[{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"rev.namespace.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio.io/rev","operator":"In","values":["default"]},{"key":"istio-injection","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"rev.object.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio.io/rev","operator":"DoesNotExist"},{"key":"istio-injection","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]},{"key":"istio.io/rev","operator":"In","values":["default"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"namespace.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio-injection","operator":"In","values":["enabled"]}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"object.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio-injection","operator":"DoesNotExist"},{"key":"istio.io/rev","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"In","values":["true"]},{"key":"istio.io/rev","operator":"DoesNotExist"}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"}]}
    creationTimestamp: "2023-06-06T20:07:18Z"
    generation: 1
    labels:
      app: sidecar-injector
      install.operator.istio.io/owning-resource: unknown
      istio.io/rev: default
      istio.io/tag: default
      operator.istio.io/component: Pilot
      release: istio
    managedFields:
    - apiVersion: admissionregistration.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:istio.io/rev: {}
            f:istio.io/tag: {}
            f:operator.istio.io/component: {}
            f:release: {}
        f:webhooks:
          .: {}
          k:{"name":"namespace.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              .: {}
              f:caBundle: {}
              f:service:
                .: {}
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:matchPolicy: {}
            f:name: {}
            f:namespaceSelector: {}
            f:objectSelector: {}
            f:reinvocationPolicy: {}
            f:rules: {}
            f:sideEffects: {}
            f:timeoutSeconds: {}
          k:{"name":"object.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              .: {}
              f:caBundle: {}
              f:service:
                .: {}
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:matchPolicy: {}
            f:name: {}
            f:namespaceSelector: {}
            f:objectSelector: {}
            f:reinvocationPolicy: {}
            f:rules: {}
            f:sideEffects: {}
            f:timeoutSeconds: {}
          k:{"name":"rev.namespace.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              .: {}
              f:caBundle: {}
              f:service:
                .: {}
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:matchPolicy: {}
            f:name: {}
            f:namespaceSelector: {}
            f:objectSelector: {}
            f:reinvocationPolicy: {}
            f:rules: {}
            f:sideEffects: {}
            f:timeoutSeconds: {}
          k:{"name":"rev.object.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              .: {}
              f:caBundle: {}
              f:service:
                .: {}
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:matchPolicy: {}
            f:name: {}
            f:namespaceSelector: {}
            f:objectSelector: {}
            f:reinvocationPolicy: {}
            f:rules: {}
            f:sideEffects: {}
            f:timeoutSeconds: {}
      manager: istio-kube-client
      operation: Update
      time: "2023-06-06T20:07:18Z"
    name: istio-revision-tag-default
    resourceVersion: "443139345"
    uid: 3d1899ec-8480-4eaa-9484-5512a92bdcbd
  webhooks:
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: rev.namespace.sidecar-injector.istio.io
    namespaceSelector:
      matchExpressions:
      - key: istio.io/rev
        operator: In
        values:
        - default
      - key: istio-injection
        operator: DoesNotExist
    objectSelector:
      matchExpressions:
      - key: sidecar.istio.io/inject
        operator: NotIn
        values:
        - "false"
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: rev.object.sidecar-injector.istio.io
    namespaceSelector:
      matchExpressions:
      - key: istio.io/rev
        operator: DoesNotExist
      - key: istio-injection
        operator: DoesNotExist
    objectSelector:
      matchExpressions:
      - key: sidecar.istio.io/inject
        operator: NotIn
        values:
        - "false"
      - key: istio.io/rev
        operator: In
        values:
        - default
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: namespace.sidecar-injector.istio.io
    namespaceSelector:
      matchExpressions:
      - key: istio-injection
        operator: In
        values:
        - enabled
    objectSelector:
      matchExpressions:
      - key: sidecar.istio.io/inject
        operator: NotIn
        values:
        - "false"
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: object.sidecar-injector.istio.io
    namespaceSelector:
      matchExpressions:
      - key: istio-injection
        operator: DoesNotExist
      - key: istio.io/rev
        operator: DoesNotExist
    objectSelector:
      matchExpressions:
      - key: sidecar.istio.io/inject
        operator: In
        values:
        - "true"
      - key: istio.io/rev
        operator: DoesNotExist
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    creationTimestamp: "2023-06-06T20:03:50Z"
    generation: 13
    labels:
      app: sidecar-injector
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: default
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: unknown
      release: istio
    managedFields:
    - apiVersion: admissionregistration.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app: {}
            f:install.operator.istio.io/owning-resource: {}
            f:install.operator.istio.io/owning-resource-namespace: {}
            f:istio.io/rev: {}
            f:operator.istio.io/component: {}
            f:operator.istio.io/managed: {}
            f:operator.istio.io/version: {}
            f:release: {}
        f:webhooks:
          k:{"name":"namespace.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              f:service:
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:name: {}
            f:rules: {}
            f:sideEffects: {}
          k:{"name":"object.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              f:service:
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:name: {}
            f:rules: {}
            f:sideEffects: {}
          k:{"name":"rev.namespace.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              f:service:
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:name: {}
            f:rules: {}
            f:sideEffects: {}
          k:{"name":"rev.object.sidecar-injector.istio.io"}:
            .: {}
            f:admissionReviewVersions: {}
            f:clientConfig:
              f:service:
                f:name: {}
                f:namespace: {}
                f:path: {}
                f:port: {}
            f:failurePolicy: {}
            f:name: {}
            f:rules: {}
            f:sideEffects: {}
      manager: istio-operator
      operation: Apply
      time: "2023-06-06T22:10:47Z"
    - apiVersion: admissionregistration.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:webhooks:
          k:{"name":"namespace.sidecar-injector.istio.io"}:
            f:clientConfig:
              f:caBundle: {}
          k:{"name":"object.sidecar-injector.istio.io"}:
            f:clientConfig:
              f:caBundle: {}
          k:{"name":"rev.namespace.sidecar-injector.istio.io"}:
            f:clientConfig:
              f:caBundle: {}
          k:{"name":"rev.object.sidecar-injector.istio.io"}:
            f:clientConfig:
              f:caBundle: {}
      manager: pilot-discovery
      operation: Update
      time: "2023-06-06T20:03:58Z"
    - apiVersion: admissionregistration.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:webhooks:
          k:{"name":"namespace.sidecar-injector.istio.io"}:
            f:namespaceSelector: {}
            f:objectSelector: {}
          k:{"name":"object.sidecar-injector.istio.io"}:
            f:namespaceSelector: {}
            f:objectSelector: {}
          k:{"name":"rev.namespace.sidecar-injector.istio.io"}:
            f:namespaceSelector: {}
            f:objectSelector: {}
          k:{"name":"rev.object.sidecar-injector.istio.io"}:
            f:namespaceSelector: {}
            f:objectSelector: {}
      manager: grun
      operation: Update
      time: "2023-06-06T22:10:51Z"
    name: istio-sidecar-injector
    resourceVersion: "443265733"
    uid: f8c4e2b7-23eb-4576-bfa9-f99573cdb682
  webhooks:
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: rev.namespace.sidecar-injector.istio.io
    namespaceSelector:
      matchLabels:
        istio.io/deactivated: never-match
    objectSelector:
      matchLabels:
        istio.io/deactivated: never-match
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: rev.object.sidecar-injector.istio.io
    namespaceSelector:
      matchLabels:
        istio.io/deactivated: never-match
    objectSelector:
      matchLabels:
        istio.io/deactivated: never-match
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: namespace.sidecar-injector.istio.io
    namespaceSelector:
      matchLabels:
        istio.io/deactivated: never-match
    objectSelector:
      matchLabels:
        istio.io/deactivated: never-match
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
    - v1beta1
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUkydlJZQk5EY1pHcW85N01OTDMzR3N3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNRFl5TURBek5UaGFGdzB6TXpBMgpNRE15TURBek5UaGFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZTTDY0SHRKdVJBbU5vZUViQnBubjdCZmdPbTZlM2ZGYjF0QXYKdzkvSkNrVjdta2FvaXVmOUxFekgrUS9IWHFIdEdMODNrQ0Z5Z0lqWi9kTXEzM1B6THBkSVlRNXJnNENSUmowMgo1TndKZk9MbkhvbEJMRnMxbkMrWTIyVXFIYmwvSzNmS1NsdFJIaGR3YUIrYTBHdUo0V0VGN3lKWlRxVlVlUjN1CjBVY0NoREFtTTRveDhRL2w4a0hHYTlka2JMcWVOcXZrSG11cFgrM0lyQU90bXZMNjNuaG9SS2krMUlhVEVlWXMKaDZrbGc5MVVLbzdCUmxzMlNGeHgzdkdHMUt6am0veGlOTzJ3VExya1ZSaVlRTXpWS0RyNXRXclkvVlN5bERvTwpJL1JVZWRLTE9nUWNuWUJWN0R0QlZ3TytmTWtNUE9JZFRCWU03VGpLRlBxUXQ0V0JBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNrQ0diOEkvWE8KeVNkWCtyMTk1bkdMaHZpOXNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGVll5QVpaNC9Rc2ZTRDRqQlNCbwpHTjgvZURiRFFreGxldExrelZqU2lnb2c4SDNxRWdORi9VQWVMM0RCOHJMN0luQ2JzOTVaaGowdnhVQjRuVVZiCmR0bGc0SloyM1IvSXZNdU1OYlgySm5PSGpNNldZcGxCRWk3c3J3dDdrVWZIUWR4WHFpdUpRZ2ptVktQRUZWMmkKdFpjWEgrNjhRWE92THY4QzBPcXplUEhGYVpoUkREQkFVUjBvRFY0SkNkZTlDb2kxSFhUVE0xTjgrNW03SG5SOApBZGtCSWdNSFZWYUR1QzBwbEd3V3cxM2g0cDF5VTM3ODVnK3lVa2orRUJwZUp6TlFhOWdNeU5nTlovV2p3SUFXCmlaQmpLblJRM2lSTEhRalFWem9ycFN0TmN6ZEpMTDlGOXlPWDZsMVBTNDdBMHkrcy83NFBqSmtKU0V5c1Nrb3oKQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: istiod
        namespace: istio-system
        path: /inject
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: object.sidecar-injector.istio.io
    namespaceSelector:
      matchLabels:
        istio.io/deactivated: never-match
    objectSelector:
      matchLabels:
        istio.io/deactivated: never-match
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
kind: List
metadata:
  resourceVersion: ""
```

is the full config I have

**Review by howardjohn — APPROVED** [review]

File: istioctl/pkg/tag/generate.go (hunk 5 above)
Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:172]: `GetWebhooksWithTag ` Only gets `MutatingWebhookConfiguration` and here gets the `ValidatingWebhookConfigurations` to fix the VWC.

> Maybe we just need Force: true. The rest of Istio operator uses this. Seems to fix my issue

I think you are right, It appears that both the VWC and MWC have issues. Originally, I was attempting to fix the issues with the VWC which is mentioned in the https://github.com/istio/istio/issues/45204, but now it seems the MWC also has problems. It may be better to apply the force logic rather than implementing those post-processing logics - which may still have errors.

Comment (hanxiaop) [reply istioctl/pkg/tag/generate.go:172]: I see, the old logic use `ApplyYAMLFiles` to apply the generated webhook, and it has a different field manager `istio-kube-client`. I think we can keep the post-processing logic and also set `Force` to `true` to resolve it. Thanks

**Review by GregHanson — APPROVED** [review]
