### PR TITLE
CA retries three times when requesting secret creation.

### LINKED ISSUE #3844: istio-ca fails to create secret (timeout from kube-apiserver)
Istio-CA received the service account notification but failed to create the associated secret:

$ k logs istio-ca-5df978dd8f-nnsm6      -n istio-system | grep Failed
2018-02-28T23:15:46.133060Z	error	Failed to create secret (error: the server was unable to return a response in the time allotted, but may still be processing the request (post secrets))

Solution is to retry here (also add the name of the secret as part of the error log)
https://github.com/istio/istio/blob/master/security/pkg/pki/ca/controller/secret.go#L210

This is Envoy in CrashBackoff:
[2018-02-28 23:22:51.982][21][info][main] external/envoy/source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.256.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2018-02-28 23:22:52.004][21][critical][main] external/envoy/source/server/server.cc:71] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': unable to read file: /etc/certs/root-cert.pem

This is the secret in the correct namespace, istio.default is missing:

$ k get secret -n istio
NAME                  TYPE                                  DATA      AGE
default-token-5jwrn   kubernetes.io/service-account-token   3         25m
test-token-l9gr6      kubernetes.io/service-account-token   3         9m

### PR DESCRIPTION
**Pull request by incfly**
Also includes the unit test to inject the failure.

fix #3844

### CODE REVIEW

File: security/pkg/pki/ca/controller/secret.go [hunk 1]
```diff
@@ -207,9 +210,17 @@ func (sc *SecretController) upsertSecret(saName, saNamespace string) {
 		PrivateKeyID: key,
 		RootCertID:   rootCert,
 	}
-	_, err = sc.core.Secrets(saNamespace).Create(secret)
+
+	// We retry several times when create secret.
```
Comment (wattli) [inline security/pkg/pki/ca/controller/secret.go]: Mention this is to reduce transient network issue?

File: security/pkg/pki/ca/controller/secret.go [hunk 2]
```diff
@@ -207,9 +210,17 @@ func (sc *SecretController) upsertSecret(saName, saNamespace string) {
...
+	for i := 0; i < secretCreationRetry; i++ {
+		_, err = sc.core.Secrets(saNamespace).Create(secret)
+		if err == nil {
+			break
```
Comment (wattli) [inline security/pkg/pki/ca/controller/secret.go]: Otherwise print out some logs for debugging purpose?

File: security/pkg/pki/ca/controller/secret.go [hunk 3]
```diff
@@ -207,9 +210,17 @@ func (sc *SecretController) upsertSecret(saName, saNamespace string) {
 		PrivateKeyID: key,
 		RootCertID:   rootCert,
 	}
-	_, err = sc.core.Secrets(saNamespace).Create(secret)
+
+	// We retry several times when create secret.
+	for i := 0; i < secretCreationRetry; i++ {
```
Comment (myidpt) [inline security/pkg/pki/ca/controller/secret.go]: Do you think it's better to add a delay between the retries?

File: security/pkg/pki/ca/controller/secret.go (hunk 1 above)
Comment (incfly) [reply security/pkg/pki/ca/controller/secret.go]: Done.

File: security/pkg/pki/ca/controller/secret.go (hunk 2 above)
Comment (incfly) [reply security/pkg/pki/ca/controller/secret.go]: Good point, done.

File: security/pkg/pki/ca/controller/secret.go (hunk 3 above)
Comment (incfly) [reply security/pkg/pki/ca/controller/secret.go]: Changed it to sleep 1 second.

**Comment by myidpt** [comment]
Can you rebase to trigger the tests again?
