### PR TITLE
[release-1.7] Fix namespace isn't resolved correctly in VirtualService delegation

### LINKED ISSUE #30429: [release-1.7] Fix namespace isn't resolved correctly in VirtualService delegation
Manual cherrypick required.

#30423 failed to apply on top of branch "release-1.7":
```
Applying: resolve virtual service short name before merge
Using index info to reconstruct a base tree...
M	pilot/pkg/model/push_context.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/model/push_context.go
CONFLICT (content): Merge conflict in pilot/pkg/model/push_context.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 resolve virtual service short name before merge
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fix #30429 
cherry-pick #30423

### CODE REVIEW

File: pilot/pkg/model/push_context.go [hunk 1]
```diff
@@ -1149,6 +1150,7 @@ func (ps *PushContext) initVirtualServices(env *Environment) error {
 					ps.privateVirtualServicesByNamespaceAndGateway[ns][gw] = append(ps.privateVirtualServicesByNamespaceAndGateway[ns][gw], virtualService)
 				}
 			} else if ps.defaultVirtualServiceExportTo[visibility.Public] {
+				fmt.Println("---gwname ", gwNames)
```
Comment (xichengliudui) [inline pilot/pkg/model/push_context.go:1153]: can the print here be remove or replace with log?

Comment (hzxuzhonghu) [reply pilot/pkg/model/push_context.go:1153]: I should remove, it was used to debug ut failure

**Review by jwendell — APPROVED** [review]
