### PR TITLE
networking: match multiple VIPs in sidecar outbound listener

### LINKED ISSUE #51747: Listeners missing for service entries with TCP ports and multiple addresses [1.22]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgrading from 1.21 to 1.22 listeners are missing for second and consecutive addresses listed in `addresses` block in service entry definition when resolution is `NONE` and protocol is `TCP`.

If I change protocol from `TCP` to `TLS` additional listeners get added to match the number of hosts specified in the spec but only the first address entry is used.

### Version

```Text
$ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (18 proxies)

$ kubectl version
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b

$ helm version --short
v3.14.3+gf03cc04
```

### Istio 1.21 and Kubernetes 1.29
Added this for comparison. Configuration is taken from an identical cluster that runs Istio 1.21 and Kubernetes 1.29.
As you can see three listeners have been created - one for each address entry. The sample-app can communicate with the external service (all three AWS MSK brokers).
```
$ kubectl --context=cluster-02 get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.8.192/28
  - 10.123.8.208/28
  - 10.123.8.224/28
exportTo:
  - .
hosts:
  - b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-2.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-3.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: tcp
    number: 9092
    protocol: TCP
  - name: tcp-2
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9092
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9092 Addr: 10.123.8.192/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.208/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.224/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 ALL                   Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9098
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9098 Addr: 10.123.8.192/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.208/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.224/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 ALL                   Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TCP` protocol

Only one listener gets created in this case. The sample-app can talk to only one MSK broker, other requests end up being BlackHole'd.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TCP
  - name: msk-iam-auth
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9092 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9092 Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9098 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9098 Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TLS` protocol

Not sure if this is relevant, since Istio seems to be using SNI only and probably ignores addresses block. The sample-app can communicate with all MSK brokers.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TLS
  - name: msk-iam-auth
    number: 9098
    protocol: TLS
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9092 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9092 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9098 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9098 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

Fixes #51747

What did I change:
1. `GetAllAddressesForProxy` and `GetExtraAddressesForProxy` always return all addresses for the proxy's IP family. Previously these functions were returning all addresses only when `ISTIO_DUAL_STACK` was enabled.
2. `buildSidecarOutboundListener` used these functions to configure CIDR matching. These functions always returned the default address, so outbound listeners couldn't match all the addresses. Now, all CIDRs are configured for the supported IP family.
3. `convertServices` created internal service instance for each [host, address] pair. Now, it creates an instance for each [host,  address list] pair.

**Example:**
When the following SE is applied:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns
spec:
  hosts:
  - "fake.service.local"
  addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
  location: MESH_EXTERNAL
  resolution: NONE
  ports:
  - number: 9092
    name: tcp
    protocol: TCP
```
and I check listeners for port 9092:
```
istioctl pc l deploy/sleep --port 9092
```
I get the following results:
1. Istio 1.21:
```
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9092 ALL                    PassthroughCluster
0.0.0.0   9092 Addr: 10.123.16.192/28 Cluster: outbound|9092||fake.service.local
0.0.0.0   9092 Addr: 10.123.16.208/28 Cluster: outbound|9092||fake.service.local
0.0.0.0   9092 Addr: 10.123.16.224/28 Cluster: outbound|9092||fake.service.local
```
2. Istio 1.22:
```
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9092 ALL                    PassthroughCluster
0.0.0.0   9092 Addr: 10.123.16.192/28 Cluster: outbound|9092||fake.service.local
```
3. This branch:
```
ADDRESSES PORT MATCH                                                    DESTINATION
0.0.0.0   9092 ALL                                                      PassthroughCluster
0.0.0.0   9092 Addr: 10.123.16.192/28,10.123.16.208/28,10.123.16.224/28 Cluster: outbound|9092||fake.service.local
```

### CODE REVIEW

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Is this a breaking change

**Review by hzxuzhonghu — COMMENTED** [review]
Dual stack usage percentage is less compared with pure ipv4

**Comment by jewertow** [comment]
> Is this a breaking change

> Dual stack usage percentage is less compared with pure ipv4

@hzxuzhonghu I am not sure if I understand what you mean, but this change does not enable dual-stack by default. `GetAllAddressesForProxy` will always return all addresses for the proxy's IP family, i.e. if a proxy is IPv4, then `GetAllAddressesForProxy` will return all IPv4 addresses. Similarly for IPv6. All addresses, IPv4 and IPv6, will be returned only if `DUAL_STACK` is enabled.

File: tests/integration/pilot/common/routing.go [hunk 1]
```diff
@@ -3826,6 +3833,67 @@ spec:
 	}
 }
 
+func testServiceEntryWithMultipleVIPsAndResolutionNone(t TrafficContext) {
```
Comment (howardjohn) [inline tests/integration/pilot/common/routing.go:3836]: Can all the ambient tests splitting out the SE to v4 and v6 (`dummy-v4.example.com`) be joined now? or I think we need to do the same logic for routes as well probably

**Review by howardjohn — APPROVED** [review]
If we do this we will need to followup with making Routes do it as well

**Comment by howardjohn** [comment]
This LGTM but its a pretty big change, want to get some more eyes

@leosarra @ramaraochavali @keithmattix

File: pilot/pkg/model/service.go [hunk 2]
```diff
@@ -1261,25 +1261,52 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
 			return addresses
 		}
+		var ipv4Addresses []string
+		var ipv6Addresses []string
+		for _, addr := range addresses {
+			if strings.Contains(addr, "/") {
+				if prefix, err := netip.ParsePrefix(addr); err != nil {
+					log.Warnf("failed to parse prefix address '%s': %s", addr, err)
+					continue
+				} else if prefix.Addr().Is4() {
```
Comment (howardjohn) [inline pilot/pkg/model/service.go:1290]: do we need `else IsV6 {...}`?

**Review by howardjohn — COMMENTED** [review]
Route fix:

```diff
diff --git a/pilot/pkg/networking/core/httproute.go b/pilot/pkg/networking/core/httproute.go
index 6a1b65d3d4..ece89b8082 100644
--- a/pilot/pkg/networking/core/httproute.go
+++ b/pilot/pkg/networking/core/httproute.go
@@ -400,6 +400,7 @@ func BuildSidecarOutboundVirtualHosts(node *model.Proxy, push *model.PushContext
 			servicesByName[svc.Hostname] = &model.Service{
 				Hostname:       svc.Hostname,
 				DefaultAddress: svc.GetAddressForProxy(node),
+				ClusterVIPs: *svc.ClusterVIPs.DeepCopy(),
 				MeshExternal:   svc.MeshExternal,
 				Resolution:     svc.Resolution,
 				Ports:          []*model.Port{svcPort},
@@ -411,10 +412,6 @@ func BuildSidecarOutboundVirtualHosts(node *model.Proxy, push *model.PushContext
 					K8sAttributes:   svc.Attributes.K8sAttributes,
 				},
 			}
-			if features.EnableDualStack {
-				// cannot correctly build virtualHost domains for dual stack without ClusterVIPs
-				servicesByName[svc.Hostname].ClusterVIPs = *svc.ClusterVIPs.DeepCopy()
-			}
 		}
 	}
 
```

File: pilot/pkg/model/service.go (hunk 2 above)
Comment (jewertow) [reply pilot/pkg/model/service.go:1290]: Yes, of course. I wasn't sure if IPv6 is applicable for these settings in Envoy.

Done.

**Comment by jewertow** [comment]
If it comes to HTTP, I will submit a follow-up PR later this week.

File: pilot/pkg/model/service.go [hunk 3]
```diff
@@ -1261,25 +1261,54 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
+					ipv6Addresses = append(ipv6Addresses, addr)
+				}
+			} else {
+				if ipAddr, err := netip.ParseAddr(addr); err != nil {
+					log.Warnf("failed to parse address '%s': %s", addr, err)
+					continue
+				} else if ipAddr.Is4() {
+					ipv4Addresses = append(ipv4Addresses, addr)
+				} else if ipAddr.Is6() {
+					ipv6Addresses = append(ipv6Addresses, addr)
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/service.go:1302]: nit： for single stack, ignore the other check

File: pilot/pkg/model/service.go [hunk 4]
```diff
@@ -1261,25 +1261,54 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
+			}
+		}
+		if node.SupportsIPv4() && len(ipv4Addresses) > 0 {
+			return ipv4Addresses
+		}
+		if node.SupportsIPv6() && len(ipv6Addresses) > 0 {
+			return ipv6Addresses
+		}
 	}
 	if a := s.GetAddressForProxy(node); a != "" {
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/service.go:1313]: This is already confusing, tbh i donot quite understand calling GetAllAddressesForProxy -> GetAddressForProxy

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Let's first sort out when to use GetAllAddressesForProxy GetAddressForProxy and GetExtraAddressesForProxy

File: pilot/pkg/model/service.go (hunk 3 above)
Comment (jewertow) [reply pilot/pkg/model/service.go]: Done

File: pilot/pkg/model/service.go (hunk 4 above)
Comment (jewertow) [reply pilot/pkg/model/service.go:1313]: `GetAddressForProxy` is called when `ClusterVIPs` is empty. Then this function returns `DefaultAddress`.

**Comment by jewertow** [comment]
> Let's first sort out when to use GetAllAddressesForProxy GetAddressForProxy and GetExtraAddressesForProxy

1. `GetAddressForProxy` - get the default address.
2. `GetExtraAddressesForProxy` - get all addresses except the default, e.g. when we set `additional_addresses` in a listener.
3. `GetAllAddressesForProxy` - get all addresses for a given IP family or all if ambient or dual-stack is enabled.

File: pilot/pkg/model/service.go (hunk 4 above)
Comment (jewertow) [reply pilot/pkg/model/service.go:1313]: I am going to revise usage of `GetAddressForProxy` in the future, but first I want to implement support for multiple VIPs in HTTP route, because I have to make sure that we no longer need the default address.

**Review by leosarra — COMMENTED** [review]
LGTM, I don´t have much to add with respect to what was already said.

I think the logical organization in GetAddressForProxy/GetExtraAddresses/GetAllAddresses and their output makes sense.

I wonder though if having only a GetAllAddresses and update existing code to use it (with proper ranges set) would be better. Anyway this is unrelated to the PR since those functions existed well before it :)

**Comment by jewertow** [comment]
> I wonder though if having only a GetAllAddresses and update existing code to use it

Actually, that was my initial approach, but I ended up in settings `addresses[0]` and `addresses[1:]`, etc., and then I thought that someone added these functions for a reason, and maybe I shouldn't change it.

Anyway, if you also think that we should use only single function to get addresses, I could do it in a near future, and now I would like to focus on making it work for HTTP as well. At the end I will submit a PR that will unify usage of these functions. What do you think?

**Comment by leosarra** [comment]
> Actually, that was my initial approach, but I ended up in settings `addresses[0]` and `addresses[1:]`, etc., and then I thought that someone added these functions for a reason, and maybe I shouldn't change it.
> 
I'm pretty sure that the original reasoning regarding that separation was made by Steve in order to keep single-stack and DS code as separated as possible. Now that the getAllAddresses became relevant for other usecases it would make sense to revisit that decision.
I agree, it does not make sense to refactor it as part of this PR. Either of us can tackle it in the future 😊

File: pilot/pkg/model/service.go [hunk 5]
```diff
@@ -1261,25 +1261,54 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
 // GetExtraAddressesForProxy returns a k8s service's extra addresses to the cluster where the node resides.
 // Especially for dual stack k8s service to get other IP family addresses.
 func (s *Service) GetExtraAddressesForProxy(node *Proxy) []string {
```
[the remark this answers is not in the document]
Comment (howardjohn) [reply pilot/pkg/model/service.go:1263]: Yeah long term I would like to remove GetExtraAddressesForProxy and the DS flag

**Comment by howardjohn** [comment]
LGTM, seems like the current concerns are just refactorings around DS handling in the future?

File: pilot/pkg/model/service.go [hunk 6]
```diff
@@ -1261,25 +1261,54 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
+	if node.Metadata != nil && node.Metadata.ClusterID != "" {
 		addresses := s.ClusterVIPs.GetAddressesFor(node.Metadata.ClusterID)
-		if len(addresses) > 0 {
+		if (features.EnableDualStack || features.EnableAmbient) && len(addresses) > 0 {
 			return addresses
 		}
+		var ipv4Addresses []string
+		var ipv6Addresses []string
+		for _, addr := range addresses {
+			if strings.Contains(addr, "/") {
```
Comment (keithmattix) [inline pilot/pkg/model/service.go:1286]: nit: maybe refactor for clarity?

File: pilot/pkg/model/service.go (hunk 4 above)
Comment (keithmattix) [reply pilot/pkg/model/service.go:1313]: Yeah I'd recommend renaming this function at some point (fast followup?); it's getting difficult to know what each one does

**Review by keithmattix — COMMENTED** [review]
I'm a general +1; I think this is a needed change that reduces the complexity of our dualstack support. I also agree with a lot of the other cleanup comments, but this is a good first step

File: pilot/pkg/model/service.go [hunk 7]
```diff
@@ -1261,25 +1261,54 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
 func (s *Service) GetAllAddressesForProxy(node *Proxy) []string {
-	if (features.EnableDualStack || features.EnableAmbient) && node.Metadata != nil && node.Metadata.ClusterID != "" {
+	return s.getAllAddressesForProxy(node)
+}
+
+func (s *Service) getAllAddressesForProxy(node *Proxy) []string {
+	if node.Metadata != nil && node.Metadata.ClusterID != "" {
 		addresses := s.ClusterVIPs.GetAddressesFor(node.Metadata.ClusterID)
-		if len(addresses) > 0 {
+		if (features.EnableDualStack || features.EnableAmbient) && len(addresses) > 0 {
```
[the remark this answers is not in the document]
Comment (jewertow) [reply pilot/pkg/model/service.go:1280]: Ambient just supports dual-stack out of the box - that was John's expectation, but it was done in this PR: https://github.com/istio/istio/pull/51939.

[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/model/service.go:1280]: Oh nice good to know

File: pilot/pkg/model/service.go (hunk 6 above)
Comment (jewertow) [reply pilot/pkg/model/service.go:1286]: Do you have any specific idea? `netip` does not provide any clever function that can parse a single address or a range.

File: pilot/pkg/model/service.go (hunk 4 above)
Comment (jewertow) [reply pilot/pkg/model/service.go:1313]: I think it will be just removed when multiple addresses will be supported for all types of listeners, so I will not change it at the moment.

File: pilot/pkg/model/service.go (hunk 6 above)
Comment (jewertow) [reply pilot/pkg/model/service.go]: Done

**Review by keithmattix — APPROVED** [review]

File: pilot/pkg/model/service.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/model/service.go:1263]: DS flag cannot be removed very soon. It is still alpha

File: pilot/pkg/model/service.go [hunk 8]
```diff
@@ -1261,22 +1261,26 @@ func (s *Service) GetAddressForProxy(node *Proxy) string {
...
 // Especially for dual stack k8s service to get other IP family addresses.
 func (s *Service) GetAllAddressesForProxy(node *Proxy) []string {
-	if (features.EnableDualStack || features.EnableAmbient) && node.Metadata != nil && node.Metadata.ClusterID != "" {
+	return s.getAllAddressesForProxy(node)
+}
+
+func (s *Service) getAllAddressesForProxy(node *Proxy) []string {
+	if node.Metadata != nil && node.Metadata.ClusterID != "" {
 		addresses := s.ClusterVIPs.GetAddressesFor(node.Metadata.ClusterID)
+		if (features.EnableDualStack || features.EnableAmbient) && len(addresses) > 0 {
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/service.go:1280]: donot we need to check whether pod support dual stack?

Comment (hzxuzhonghu) [reply pilot/pkg/model/service.go:1280]: Like a multi cluster mesh, one cluster support only ipv4, the other support dual stack

Comment (jewertow) [reply pilot/pkg/model/service.go:1280]: No, this function returns addresses relevant for the cluster of the requesting proxy.

Btw. this is irrelevant in this PR, as I didn't change anything related to dual-stack.

**Comment by jewertow** [comment]
@hzxuzhonghu as you requested changes, could you clarify what do you expect to be changed? You didn't point any issue, just raised your concerns, so this is confusing.

File: pilot/pkg/model/service.go (hunk 8 above)
Comment (hzxuzhonghu) [reply pilot/pkg/model/service.go:1280]: Yes, none of your bussiness. Just see this and indeed it is a bug

**Review by hzxuzhonghu — APPROVED** [review]

File: pilot/pkg/model/service.go (hunk 8 above)
Comment (bleggett) [reply pilot/pkg/model/service.go:1280]: In general, we shouldn't be making decisions based on `EnableDualStack` and should treat it as a deprecated field - it's almost never the correct signal to check.
