### PR TITLE
Dedupe wildcard routes based on the virtualservice with the most specific match

### LINKED ISSUE #45415: Wrong route configuration when multi-level wildcards are used
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone,
I encountered an issue while tinkering with SE and VS resources that uses wildcards.
I noticed that under certain configuration I can end up with an incorrect route being generated.

Here are some steps to reproduce (archive with the CRs: [resources.tar.gz](https://github.com/istio/istio/files/11723372/resources.tar.gz)):
- Install Istio (I used 1.17.2)
- Deploy Sleep with sidecar in istio-system
```
kubectl label ns istio-system istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml -n istio-system
```
- Deploy a SE with "host: *.hello.test.abc.example.com" host and one with  "host: *.abc.example.com"
You can use the resources inside my zip and deploy them with `kubectl apply -f serviceentries/ -n istio-system`
- Deploy two VS, one for each host. Those VS needs to define a route to the respective wildcard host.
You can deploy my two VS using `kubectl apply -f virtualservices/ -n istio-system`
- Check the configdump and you will notice that the *.abc.example.com virtual host ended up with a route to *.hello.test.abc.example.com instead of the route to *.abc.example.com.
```
{
     "version_info": "2023-06-12T12:47:43Z/11",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "443",
      "virtual_hosts": [
       {
        "name": "*.abc.example.com:443",
        "domains": [
         "*.abc.example.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|443||*.hello.test.abc.example.com",
           "timeout": "15s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,reset,unavailable,cancelled,resource-exhausted",
            "num_retries": 3,
            "per_try_timeout": "15s",
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
              }
             }
            ],
            "host_selection_retry_max_attempts": "5"
           },
           "max_grpc_timeout": "15s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/virtual-service/vs1"
            }
           }
          },
          "decorator": {
           "operation": "*.hello.test.abc.example.com:443/*"
          },
          "name": ".https-port"
         }
        ],
        "include_request_attempt_count": true
       },
```

I suspect that this issue originates from the fact that the wildcard *.abc.example.com of the SE matches the wildcard in the VSs.
Is this the intended behavior? Can something be done to support this multi-level wildcard scenario?

### Version

```Text
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (2 proxies)
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11723350/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by keithmattix**
**Please provide a description of this PR:**
Fixes #45415.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is there a tl;dr of before/after for a user? I see the tests but `g.Expect(vhost.Services).To(HaveLen(1))` is hard to map to user facing behavior

**Comment by keithmattix** [comment]
Ah sure. Previously, the scenario described in #45415 resulted in duplicate virtual hosts; pilot would reject one of the hosts (which one varies based on creation order), and users would see virtual service config meant for one wildcard (e.g *.example.com) applied to an overlapping wildcard (e.g *.foo.example.com) even though there is a different VS for the more specific config. This PR generates a map to look up which VS contains the most specific matching host so that virtual services with hosts that match more generically can ignore the more specific host name (because it will be handled later by the more specific VS), thus avoiding the duplication

**Comment by keithmattix** [comment]
Just to make this a bit clearer, here are the logs from my repro:

```
2023-11-28T18:48:17.172267Z	info	ads	Push Status: {
    "pilot_vservice_dup_domain": {
        "*.abc.example.com:443": {
            "proxy": "httpbin-5c5944c58c-zzxdw.default",
            "message": "duplicate domain from service: *.abc.example.com:443"
        }
    }
}
2023-11-28T18:48:18.309785Z	info	ads	Incremental push, service *.hello.test.abc.example.com at shard External/Kubernetes has no endpoints
2023-11-28T18:48:18.410068Z	info	ads	Push debounce stable[16006] 1 for config ServiceEntry/default/*.hello.test.abc.example.com: 100.231399ms since last change, 100.231184ms since last push, full=true
2023-11-28T18:48:18.411152Z	info	ads	XDS: Pushing:2023-11-28T18:48:18Z/69 Services:11 ConnectedEndpoints:3 Version:2023-11-28T18:48:18Z/69
2023-11-28T18:48:18.411486Z	info	ads	CDS: PUSH for node:httpbin-5c5944c58c-zzxdw.default resources:22 size:19.9kB cached:17/18
2023-11-28T18:48:18.412455Z	info	ads	LDS: PUSH for node:httpbin-5c5944c58c-zzxdw.default resources:17 size:41.9kB
2023-11-28T18:48:18.412715Z	info	ads	RDS: PUSH for node:httpbin-5c5944c58c-zzxdw.default resources:9 size:7.6kB cached:7/9
2023-11-28T18:48:27.172609Z	info	ads	Push Status: {
    "pilot_vservice_dup_domain": {
        "*.abc.example.com:443": {
            "proxy": "httpbin-5c5944c58c-zzxdw.default",
            "message": "duplicate domain from service: *.abc.example.com:443"
        },
        "*.hello.test.abc.example.com:443": {
            "proxy": "httpbin-5c5944c58c-zzxdw.default",
            "message": "duplicate domain from service: *.hello.test.abc.example.com:443"
        }
    }
}
2023-11-28T18:49:39.782535Z	info	ads	ADS: "10.224.0.131:48540" aks-istio-egressgateway-asm-1-17-55d795df96-rnbhv.aks-istio-egress-4075 terminated
```

File: pilot/pkg/networking/core/v1alpha3/route/route.go [hunk 1]
```diff
@@ -101,6 +107,39 @@ func BuildSidecarVirtualHostWrapper(routeCache *Cache, node *model.Proxy, push *
...
 
+	// For correctness, we need to maintain a mapping of hostnames to the
+	// virtual services that have the most specific wildcard host match
+	// match for that hostname. Unfortunately, we have to loop through all of
+	// hosts in all of the virtualservices an extra time...
+	//
+	// TODO: Investigate whether it's worth it to maintain this map in the
+	// pushContext or something else higher level for _all_ virtualServices
+	vsWithMostSpecificWildcardHosts := make(map[host.Name]vsHostEntry)
+	for _, vs := range virtualServices {
```
[the remark this answers is not in the document]
Comment (ramaraochavali) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:118]: What is impact of performance on looping through all virtual services every time?

File: pilot/pkg/networking/core/v1alpha3/route/route.go [hunk 2]
```diff
@@ -172,14 +214,21 @@ func separateVSHostsAndServices(virtualService config.Config,
 			hosts = append(hosts, string(hostname))
 			continue
 		}
-		// Say host is *.global
+		// Say this VS's host is *.global and there's another VS with host *.foo.global
 		foundSvcMatch := false
 		// Say we have Services *.foo.global, *.bar.global
 		for svcHost, svc := range serviceRegistry {
 			// *.foo.global matches *.global
 			if svcHost.Matches(hostname) {
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:222]: `Matches` is noted as bidirectional throughout the code and seems to be used intentionally. I think we should continue using it for backwards compatibility, but continue to call out its implications

File: pilot/pkg/networking/core/v1alpha3/route/route.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:118]: I'm glad someone asked; I left a comment calling this out. It's not as bad as it could be since we only need to process hosts with wildcards; I don't anticipate their being even 100 such hosts/virtualServices for a given pilot instance. That being said, I'm definitely open to optimizations as long as we can avoid unneeded complexity. The egress listener could maintain this index at its level so we don't have to recompute so frequently. The extreme version would be to compute a true for all of the wildcards (unnecessary IMO).

[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:118]: @hzxuzhonghu the loop can't be moved down because we need the full map computed in the next loop

File: pilot/pkg/networking/core/v1alpha3/route/route.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:222]: Unrelated : Just personal view, could break compatibility if changed

File: pilot/pkg/networking/core/v1alpha3/route/route.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (hzxuzhonghu) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:118]: Yeah, it should be precalculated beforehand. The performance influence is unneglected.  Here it does calculate on time per route. 
It can be optimized maybe one time per proxy or even one time per Sidecar.

[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/route/route.go:118]: Ack, I figured as much but wanted a second opinion. I'll add the map to the egress listener

File: pilot/pkg/networking/core/v1alpha3/route/route.go [hunk 3]
```diff
@@ -172,14 +214,21 @@ func separateVSHostsAndServices(virtualService config.Config,
...
-				servicesInVirtualService = append(servicesInVirtualService, svc)
 				foundSvcMatch = true
+				// BUT we need to check for the most specific match since another VS
+				// exists that matches *.foo.global more specifically.
+				entry, ok := vsWithMostSpecificWildcardHosts[svcHost]
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/networking/core/v1alpha3/route/route.go]: Was able to get around this with https://github.com/istio/istio/blob/master/pilot/pkg/model/config.go#L294

**Comment by keithmattix** [comment]
I believe current unit test failures are because of assumptions that the oldest VirtualService wins when there's an overlap between hosts due to a wildcard (like in [this case](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go#L2240)). With the index added we can actually do better than "oldest wins"....but it may break people? I could do a more manual match (instead of using `MostSpecificHostMatch`) and keep the "oldest wins" heuristic....I'm not sure what the best path is here. @ramaraochavali @howardjohn @hzxuzhonghu any thoughts?

**Comment by keithmattix** [comment]
All 3 of the remaining test failures appear to be because the tests expect the "oldest wins" heuristic to be in place for VirtualService hosts that overlap due to wildcards. Because we have the index, we can actually do better than oldest wins (which is why the tests are now failing). I could do a more manual building of the index and try and enforce that oldest wins to be extra conservative with backwards compatibility, but it feels like a lot of effort to keep what is, at best, a compromise. @ramaraochavali @hzxuzhonghu @howardjohn what are your thoughts?

**Comment by keithmattix** [comment]
Added a feature flag to allow users to persist the "oldest wins" heuristic for VS if they happen to be relying on this (undocumented and edge case) behavior. The default behavior will choose the most specific wildcard

File: releasenotes/notes/45415-overlapping-wildcards.yaml [hunk 4]
```diff
@@ -0,0 +1,17 @@
+apiVersion: release-notes/v2
+kind: bug-fix
+area: traffic-management
+
+issue:
+  - 45415
+
+releaseNotes:
+  - |
+    **Fixed** A bug where overlapping wildcard hosts in VirtualService would produce incorrect routing configuration when wildcard services (e.g. in ServiceEntries) were selected.
```
Comment (dhawton) [inline releasenotes/notes/45415-overlapping-wildcards.yaml:10]:
```suggestion
    **Fixed** a bug where overlapping wildcard hosts in a VirtualService would produce incorrect routing configuration when wildcard services were selected (e.g. in ServiceEntries).
```

File: releasenotes/notes/45415-overlapping-wildcards.yaml [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+upgradeNotes:
+  - title: Overlapping Wildcard Conflicts
+    content: |
+      This fix changes the behavior of overlapping wildcard hosts in VirtualService.Previously, the oldest VirtualService would take precedence
+      regardless of whether or not it was the most specific host match. Now, the most specific host match will take precedence. To persist the old behavior,
+      set the `PERSIST_OLDEST_FIRST_HEURISTIC_FOR_TRAFFIC_POLICY` env variable to `true` on istiod.
```
Comment (dhawton) [inline releasenotes/notes/45415-overlapping-wildcards.yaml:17]:
```suggestion
      This fix changes the behavior of overlapping wildcard hosts in VirtualService. Previously, the oldest VirtualService would take precedence
      regardless of whether or not it was the most specific host match. Now, the most specific host match will take precedence. To persist the old behavior,
      set the `PERSIST_OLDEST_FIRST_HEURISTIC_FOR_TRAFFIC_POLICY` environment variable to `true` on istiod.
```

**Review by dhawton — APPROVED** [review]
Release note look good to me

File: pilot/pkg/model/sidecar.go [hunk 6]
```diff
@@ -198,6 +199,8 @@ type IstioEgressListenerWrapper struct {
 	// a private virtual service for serviceA from the local namespace,
 	// with a different path rewrite or no path rewrites.
 	virtualServices []config.Config
+
+	mostSpecificWildcardSvcIndex map[host.Name]types.NamespacedName
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/sidecar.go:203]: what is the value

File: pilot/pkg/model/sidecar.go [hunk 7]
```diff
@@ -828,6 +842,39 @@ func serviceMatchingVirtualServicePorts(service *Service, vsDestPorts sets.Set[i
 	return nil
 }
 
+// computeWildcardHostVirtualServiceIndex computes the wildcardHostVirtualServiceIndex for a given
+// list of virtualServices. This is used to optimize the lookup of the most specific wildcard host
+func computeWildcardHostVirtualServiceIndex(virtualServices []config.Config, services []*Service) map[host.Name]types.NamespacedName {
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/sidecar.go:847]: add a test for it

**Comment by kfaseela** [comment]
LGTM. The internal tests run fine with this PR, thanks @keithmattix ! Would wait for Zhonghu's approval once you add the unit tests as he suggested.

File: pilot/pkg/model/config.go [hunk 8]
```diff
@@ -331,6 +336,46 @@ func mostSpecificHostWildcardMatch[V any](needle string, wildcard map[host.Name]
 	return matchHost, matchValue, found
 }
 
+// OldestMatchingHost returns the oldest matching host for a given needle (whether specific or wildcarded)
+func OldestMatchingHost[V CreationTimestamper](needle host.Name, specific map[host.Name]V,
```
Comment (ramaraochavali) [inline pilot/pkg/model/config.go:340]: Why can't we just take Config map[host.Name]Config as argument? Why does it need to be templatized with specific interface (CreationTimestamper)?

File: pilot/pkg/features/pilot.go [hunk 9]
```diff
@@ -704,6 +704,10 @@ var (
 
 	StackdriverAuditLog = env.Register("STACKDRIVER_AUDIT_LOG", false, ""+
 		"If enabled, StackDriver audit logging will be enabled.").Get()
+
+	PersistOldestWinsHeuristicForTrafficPolicy = env.Register("PERSIST_OLDEST_FIRST_HEURISTIC_FOR_TRAFFIC_POLICY", false,
```
Comment (ramaraochavali) [inline pilot/pkg/features/pilot.go:708]: PERSIST_OLDEST_FIRST_HEURISTIC_FOR_TRAFFIC_POLICY seems very generic traffic policy flag. Should we be more specific like 
`PERSIST_OLDEST_FIRST_HEURISTIC_FOR_WILD_CAR_HOST_MATCHING` ?

File: pilot/pkg/model/config.go (hunk 8 above)
Comment (keithmattix) [reply pilot/pkg/model/config.go:340]: I wanted to keep it generic like MostSpecificHostMatch. To keep it generic, you need an interface type constraint so I created CreationTimestamper

File: pilot/pkg/features/pilot.go (hunk 9 above)
Comment (keithmattix) [reply pilot/pkg/features/pilot.go:708]: Oldest wins is a common heuristic throughout the codebase; I thought the flag could be more generally useful if we need to migrate away from that in the future, but I don't feel super strongly. I'll err on the side of specificity and take your suggestion

Comment (ramaraochavali) [reply pilot/pkg/features/pilot.go:708]: > Oldest wins is a common heuristic throughout the codebase; I thought the flag could be more generally useful if we need to migrate away from that in the future,

I doubt we will change any of that in future :-). Being specific is better IMO

File: pilot/pkg/model/config.go (hunk 8 above)
Comment (ramaraochavali) [reply pilot/pkg/model/config.go:340]: The existing MostSpecificHostMatch is used for `set` of host names also. That is the reason we have made it generic. But in this specific case there may not be any such need - we always operate on Config here. NBD just pointing out

Comment (keithmattix) [reply pilot/pkg/model/config.go:340]: Fair, I had to add the GetCreation Timestamp func to begin with. What I think I'll do is remove the generic and just make the args take the interface instead of a type param so that pointers are stored in the maps instead of copying large config objects around

File: pilot/pkg/model/sidecar.go (hunk 6 above)
Comment (keithmattix) [reply pilot/pkg/model/sidecar.go:206]: Added a comment

File: pilot/pkg/features/pilot.go (hunk 9 above)
Comment (keithmattix) [reply pilot/pkg/features/pilot.go]: Agreed. Changed

File: pilot/pkg/features/pilot.go [hunk 10]
```diff
@@ -704,6 +704,10 @@ var (
 
 	StackdriverAuditLog = env.Register("STACKDRIVER_AUDIT_LOG", false, ""+
 		"If enabled, StackDriver audit logging will be enabled.").Get()
+
+	PersistOldestWinsHeuristicForWildcardHostMatching = env.Register("PERSIST_OLDEST_FIRST_HEURISTIC_FOR_WILDCARD_HOST_MATCHING", false,
```
Comment (hzxuzhonghu) [inline pilot/pkg/features/pilot.go:708]: @keithmattix can you document what's the behavior change with `PERSIST_OLDEST_FIRST_HEURISTIC_FOR_WILDCARD_HOST_MATCHING = false`

And also PERSIST_OLDEST_FIRST_HEURISTIC_FOR_WILDCARD_HOST_MATCHING = true.

I feel both would change something

Comment (keithmattix) [reply pilot/pkg/features/pilot.go:708]: Yes, is a change in behavior regardless of the flag's value because the current behavior is broken; overlapping wildcards result in duplicate virtual hosts. The default behavior (flag off) matches services to virtual services configuration based on the most specifc VS host. With the flag set to true, the oldest matching virtual service is selected when building the virtual host configuration for the service.

File: pilot/pkg/model/sidecar.go [hunk 11]
```diff
@@ -828,6 +845,39 @@ func serviceMatchingVirtualServicePorts(service *Service, vsDestPorts sets.Set[i
...
+	fqdnVirtualServiceHostIndex := make(map[host.Name]config.Config, len(virtualServices))
+	wildcardVirtualServiceHostIndex := make(map[host.Name]config.Config, len(virtualServices))
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/model/sidecar.go:852]: The length is just a hint; we know we will have at least len(virtualservices) number of hosts so we can preallocate memory for at least that much. I wouldn't say it's useless; it's just a starting point

File: pilot/pkg/model/config.go (hunk 8 above)
Comment (keithmattix) [reply pilot/pkg/model/config.go]: I was worried about large config specs being copied in the slice, but then I realized that the actual spec is `any` so no worries there. Changed it

**Comment by keithmattix** [comment]
> Is there a tl;dr of before/after for a user? I see the tests but `g.Expect(vhost.Services).To(HaveLen(1))` is hard to map to user facing behavior

The new test I added at @hzxuzhonghu's suggestion help explain this a bit better: https://github.com/istio/istio/pull/48071/files#diff-0d29da6c28e51088a0af53a34dc0cc5003f5d29f1e7c7eebd66892bdeb9b6762R2762

**Review by howardjohn — COMMENTED** [review]
LGTM, will leave to @ramaraochavali or @hzxuzhonghu since it looked like there were some comments, and I didn't super thoroughly review it

File: pilot/pkg/model/config.go [hunk 12]
```diff
@@ -43,6 +44,10 @@ type ConfigKey struct {
 	Namespace string
 }
 
+type CreationTimestamper interface {
```
Comment (hzxuzhonghu) [inline pilot/pkg/model/config.go:47]: nit : remove

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM

**Comment by ramaraochavali** [comment]
LGTM as well apart from @hzxuzhonghu 's comments

File: pilot/pkg/model/config.go (hunk 12 above)
Comment (keithmattix) [reply pilot/pkg/model/config.go]: Done

File: pilot/pkg/model/sidecar.go [hunk 13]
```diff
@@ -198,6 +199,11 @@ type IstioEgressListenerWrapper struct {
 	// a private virtual service for serviceA from the local namespace,
 	// with a different path rewrite or no path rewrites.
 	virtualServices []config.Config
+
+	// An index of hostname to the namespaced name of the VirtualService containing the most
+	// relevant host match. Depending on the `PERSIST_OLDEST_FIRST_HEURISTIC_FOR_WILDCARD_HOST_MATCHING`
+	// feature flag, it could be the most specific host match or the oldest host match.
+	mostSpecificWildcardSvcIndex map[host.Name]types.NamespacedName
```
[the remark this answers is not in the document]
Comment (keithmattix) [reply pilot/pkg/model/sidecar.go]: Done

File: pilot/pkg/features/pilot.go (hunk 10 above)
Comment (keithmattix) [reply pilot/pkg/features/pilot.go:708]: Fair enough. Will rename to PERSIST_OLDEST_FIRST_HEURISTIC_FOR_VIRTUAL_SERVICE_HOST_MATCHING

**Review by ramaraochavali — APPROVED** [review]

File: pilot/pkg/model/sidecar.go [hunk 14]
```diff
@@ -828,6 +844,39 @@ func serviceMatchingVirtualServicePorts(service *Service, vsDestPorts sets.Set[i
...
+func computeWildcardHostVirtualServiceIndex(virtualServices []config.Config, services []*Service) map[host.Name]types.NamespacedName {
+	fqdnVirtualServiceHostIndex := make(map[host.Name]config.Config, len(virtualServices))
+	wildcardVirtualServiceHostIndex := make(map[host.Name]config.Config, len(virtualServices))
+	for _, vs := range virtualServices {
+		v := vs.Spec.(*networking.VirtualService)
+		for _, h := range v.Hosts {
+			if host.Name(h).IsWildCarded() {
+				wildcardVirtualServiceHostIndex[host.Name(h)] = vs
+			} else {
+				fqdnVirtualServiceHostIndex[host.Name(h)] = vs
```
Comment (keithmattix) [inline pilot/pkg/model/sidecar.go:858]: I think this is a bug; we don't check for duplicate fqdn hosts so we'd silently override it. This didn't get released so i'll put up a PR to fix it

/cc @hzxuzhonghu
